import {KittyFlat} from '../kitty/studio/flat.tsx';
import {useEffect,useId,useMemo,useRef,useState,type PointerEvent, type ReactNode} from 'react';
import {ENCOUNTER_PACKS,encounterPack,type EncounterTheme} from './encounterPacks.ts';
import {encounterCompositionDigest,type SharedEncounter,type EncounterCommand,type EncounterChoice} from './encounterContracts.ts';
import {IndexedDbEncounterStore,sendEncounterPrivate,type EncounterClient,type EncounterDeviceStore,type EncounterDeviceDraft,type EncounterPending} from './encounterClient.ts';
import {encounterKeepsakePng,encounterKeepsakeSvg,encounterSceneMarkup,encounterStudioRecipe,encounterStudioPreview,type EncounterStudioRecipe,type EncounterWardrobeArt} from './encounterKeepsake.ts';
import type {VaultClientScope} from './vaultClient.ts';
import type {EncounterPrivateView,EncounterRevealedAnswer} from '../../workers/hearthsideVaultEncounters.ts';
import './encounter.css';
export type EncounterWardrobeItem=EncounterWardrobeArt&{name:string;preview:ReactNode};
export type EncounterProps={client:EncounterClient;scope:VaultClientScope;theme:EncounterTheme;encounter:SharedEncounter;roster:{memberId:string;name:string}[];enabled?:boolean;
  submit:(command:EncounterCommand)=>Promise<boolean>;refresh:()=>Promise<void>;onReplay:(packId:string)=>void;
  onStudioKeepsake:(recipe:EncounterStudioRecipe)=>Promise<void>;
  onMemoryKeepsake:(input:{encounterId:string;compositionDigest:string;title:string;image:Blob;answers:EncounterRevealedAnswer[]})=>Promise<void>;
  wardrobe?:EncounterWardrobeItem[];onOpenWardrobe?:()=>void;experiences?:{id:string;title:string}[];deviceStore?:EncounterDeviceStore};
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
function message(error:unknown){const text=error instanceof Error?error.message:'';
  if(/PRIVATE_STORAGE/.test(text))return'This device could not keep the private draft. Your words are still on this screen; free some device space and try saving again.';
  if(/PENDING_ENCOUNTER_ACTION/.test(text))return'Retry the interrupted action first. Its original identity is kept on this device.';
  if(/ANSWER_CHANGED|ENCOUNTER_CHANGED/.test(text))return'This version changed. Refresh, read your current answer and choose again. Nothing is revealed by an old review.';
  if(/AUDIENCE_CHANGED|SCOPE_CHANGED|FORBIDDEN|UNAUTHENTICATED/.test(text))return'The household or signed-in account changed. This draft remains with its original account.';
  if(/WITHDRAWN/.test(text))return'This reveal has been withdrawn. You can start a fresh encounter whenever you choose.';
  if(/DISABLED|UNAVAILABLE/.test(text))return'This private service is unavailable here. Your device draft is kept for later.';
  return'That did not finish. Your pending action is kept; retry it when the connection is ready.';
}
export function Encounter(props:EncounterProps){return <EncounterSurface key={JSON.stringify([props.scope.environment,props.scope.householdId,props.scope.memberId,props.scope.subject,props.encounter.id])} {...props}/>;}
function EncounterSurface({client,scope,theme,encounter,roster,enabled=true,submit,refresh,onReplay,onStudioKeepsake,onMemoryKeepsake,wardrobe=[],onOpenWardrobe,experiences=[],deviceStore}:EncounterProps){
  const pack=encounterPack(encounter.packId),id=useId(),alive=useRef(true),busyRef=useRef(false),heading=useRef<HTMLHeadingElement>(null);
  const [view,setView]=useState<EncounterPrivateView|null>(null),[draft,setDraft]=useState<EncounterDeviceDraft>({text:'',objectId:pack.notice.objects[0]!.id,wardrobeId:null});
  const [pending,setPending]=useState<EncounterPending|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[discovered,setDiscovered]=useState<string|null>(null),[ready,setReady]=useState(false);
  const [privateReview,setPrivateReview]=useState(false),[withdrawReview,setWithdrawReview]=useState(false),[stage,setStage]=useState<'notice'|'make'|'keep'>('notice');
  const [choice,setChoice]=useState<EncounterChoice>(()=>encounter.choices.find(c=>c.memberId===scope.memberId)??{memberId:scope.memberId,revision:1,colourId:pack.make.colours[0]!.id,order:pack.make.items.map(i=>i.id),words:'',drawing:[],wardrobeId:null});
  const choiceDirty=useRef(false),choiceBase=useRef(encounter.choices.find(c=>c.memberId===scope.memberId)?.revision??0);
  const [digest,setDigest]=useState(''),[keepReview,setKeepReview]=useState(false),[link,setLink]=useState(encounter.experienceId??'');
  const store=useMemo(()=>{try{return deviceStore??new IndexedDbEncounterStore();}catch{const fail=async():Promise<never>=>{throw Error('PRIVATE_STORAGE_UNAVAILABLE');};return{read:fail,draft:fail,make:fail,reserve:fail,settle:fail} as EncounterDeviceStore;}},[deviceStore]);
  const name=(member:string)=>roster.find(r=>r.memberId===member)?.name??'Household member';
  const current=useRef(encounter);current.current=encounter;
  const loadPending=async()=>{const value=await store.read(scope,encounter.id);if(alive.current)setPending(value.pending);};
  const readPrivate=async()=>{const value=await client.command({operation:'encounter-private',input:{encounterId:encounter.id,action:'read'}}) as EncounterPrivateView;if(alive.current){setView(value);setPrivateReview(false);}return value;};
  useEffect(()=>{alive.current=true;let cancelled=false;
    void Promise.all([store.read(scope,encounter.id),readPrivate()]).then(([local,remote])=>{if(cancelled)return;setDraft(local.draft??(remote.own?{text:remote.own.text,objectId:remote.own.objectId,wardrobeId:remote.own.wardrobeId}:{text:'',objectId:pack.notice.objects[0]!.id,wardrobeId:null}));setPending(local.pending);if(local.make){choiceDirty.current=true;choiceBase.current=local.make.baseRevision;setChoice(local.make.choice);}setReady(true);}).catch(e=>{if(!cancelled){setError(message(e));setReady(true);}});
    return()=>{cancelled=true;alive.current=false;if(!deviceStore)void Promise.resolve().then(()=>{if(!alive.current)return store.close?.();});};
  },[client,store]);
  useEffect(()=>{let cancelled=false;void encounterCompositionDigest(encounter).then(value=>{if(!cancelled)setDigest(value);});setKeepReview(false);return()=>{cancelled=true;};},[encounter.compositionRevision,encounter.reveal,encounter.choices]);
  useEffect(()=>{const accepted=encounter.choices.find(c=>c.memberId===scope.memberId);if(accepted&&!choiceDirty.current){choiceBase.current=accepted.revision;setChoice(accepted);}},[encounter.choices.find(c=>c.memberId===scope.memberId)?.revision]);
  const editChoice=(value:EncounterChoice)=>{choiceDirty.current=true;setChoice(value);void store.make(scope,encounter.id,{baseRevision:choiceBase.current,choice:value}).catch(e=>{if(alive.current)setError(message(e));});};
  const editDraft=(value:EncounterDeviceDraft)=>{setDraft(value);setPrivateReview(false);void store.draft(scope,encounter.id,value).catch(e=>{if(alive.current)setError(message(e));});};
  const run=async(label:string,fn:()=>Promise<void>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(label);setError('');setNotice('');try{await fn();}catch(e){if(alive.current)setError(message(e));}finally{busyRef.current=false;if(alive.current){setBusy('');void loadPending().catch(()=>{});}}};
  const privateCommand=async(input:Parameters<typeof sendEncounterPrivate>[3])=>{if(!alive.current)throw Error('SCOPE_CHANGED');const value=await sendEncounterPrivate(client,store,scope,input);if(alive.current){setView(value);setPrivateReview(false);}return value;};
  const shared=async(command:EncounterCommand)=>{if(!alive.current)throw Error('SCOPE_CHANGED');if(!await submit(command))throw Error('ENCOUNTER_COMMAND_UNCERTAIN');};
  const revealed=Boolean(view?.reveal&&same(view.reveal.binding,encounter.reveal)),paused=encounter.pausedMemberIds.includes(scope.memberId)||view?.paused;
  const savedMatches=Boolean(view?.own&&same(draft,{text:view.own.text,objectId:view.own.objectId,wardrobeId:view.own.wardrobeId}));
  const studioPreview=useMemo(()=>pack.keep.medium==='studio'&&encounter.choices.length===2&&encounter.reveal?encounterStudioPreview(encounter):null,[encounter.choices,encounter.reveal,pack.id]);
  const blocked=Boolean(busy)||!enabled||!ready,allKept=encounter.keptMemberIds.length===2&&encounter.pausedMemberIds.length===0;
  const changeStage=(next:'notice'|'make'|'keep')=>{setStage(next);queueMicrotask(()=>heading.current?.focus());};
  const previewChoices=[...encounter.choices.filter(c=>c.memberId!==scope.memberId),choice].sort((a,b)=>a.memberId.localeCompare(b.memberId));
  return <article className="hearth-encounter" data-theme={theme} data-pack-theme={pack.theme} aria-labelledby={`${id}-title`} aria-busy={Boolean(busy)}>
    <header className="encounter-heading"><p className="encounter-kicker">{pack.season} · {pack.theme==='taylor'?'Taylor’s Scrapbook':pack.theme==='newfoundland'?'Newfoundland':'Classic Hearth'}</p><h2 id={`${id}-title`}>{pack.title}</h2><p>A small encounter, in your own time.</p></header>
    <nav className="encounter-stages" aria-label="Encounter parts">{(['notice','make','keep'] as const).map((part,i)=><button key={part} aria-current={stage===part?'step':undefined} disabled={part!=='notice'&&!revealed} onClick={()=>changeStage(part)}>{i+1}. {part[0]!.toUpperCase()+part.slice(1)}</button>)}</nav>
    {error&&<p role="alert" className="encounter-error">{error}</p>}<p role="status" className="encounter-status">{busy||notice}</p>
    <div className="encounter-toolbar"><button disabled={Boolean(busy)} onClick={()=>void run('Opening the current encounter…',async()=>{await refresh();await readPrivate();setNotice('The current encounter is open.');})}>Refresh our encounter</button>
      <button disabled={Boolean(busy)||!ready} onClick={()=>void run(paused?'Returning to the encounter…':'Pausing your part…',async()=>{await privateCommand({encounterId:encounter.id,action:paused?'resume':'pause'});await shared({kind:paused?'encounter.resume':'encounter.pause',id:encounter.id});setNotice(paused?'You can continue in your own time.':'Your participation is paused. No responsibility has moved to the other person.');})}>{paused?'Resume my part':'Pause my part'}</button></div>
    {pending&&<aside className="encounter-recovery"><p>An interrupted private action is kept on this device.</p><button disabled={Boolean(busy)} onClick={()=>void run('Retrying the same private action…',async()=>{await privateCommand(pending.input);setNotice('That same action has been recovered.');})}>Retry interrupted action</button></aside>}
    {view?.withdrawn?<section><h3>This reveal is withdrawn</h3><p>Earlier independently kept memories or pieces stay separate.</p><button onClick={()=>onReplay(pack.id)}>Begin a fresh encounter</button></section>:<>
    <div className="encounter-illustration" aria-hidden="true" dangerouslySetInnerHTML={{__html:encounterSceneMarkup(pack,stage==='notice'?encounter.choices:stage==='make'?previewChoices:encounter.choices,discovered,pack.mechanic==='mummers'&&encounter.choices.length<2?[]:wardrobe)}}/>
    {stage==='notice'&&<section className="encounter-notice" aria-labelledby={`${id}-part`}><h3 ref={heading} tabIndex={-1} id={`${id}-part`}>{pack.notice.title}</h3><p>{pack.notice.invitation}</p>
      <div className="encounter-notice-objects">{pack.notice.objects.map(object=><button key={object.id} aria-pressed={discovered===object.id} onClick={()=>{setDiscovered(object.id);editDraft({...draft,objectId:object.id});}}>{object.name}</button>)}</div>
      {discovered&&<p role="status" className="encounter-discovery">{pack.notice.objects.find(o=>o.id===discovered)?.discovery}</p>}
      <div className="encounter-private-paper"><p className="encounter-kicker">Only your signed-in account can open this answer before reveal</p><label htmlFor={`${id}-answer`}>{pack.notice.prompt}</label><textarea id={`${id}-answer`} maxLength={4000} value={draft.text} disabled={Boolean(busy)||Boolean(paused)} onChange={e=>editDraft({...draft,text:e.target.value})}/>
        {pack.mechanic==='mummers'&&<label>My actual wardrobe item<select value={draft.wardrobeId??''} disabled={blocked} onChange={e=>editDraft({...draft,wardrobeId:e.target.value||null})}><option value="">Choose from my wardrobe</option>{wardrobe.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}
        {pack.mechanic==='mummers'&&<p>{wardrobe.length===0?'Your wardrobe shelf is empty. ':''}{onOpenWardrobe&&<button type="button" onClick={onOpenWardrobe}>Open the real wardrobe</button>}</p>}
        <div className="encounter-toolbar"><button disabled={blocked||Boolean(paused)||!draft.text.trim()||(pack.mechanic==='mummers'&&!draft.wardrobeId)} onClick={()=>void run('Saving only your answer…',async()=>{await store.draft(scope,encounter.id,draft);await privateCommand({encounterId:encounter.id,action:'save',expectedRevision:view?.own?.revision??0,answer:{...draft,revision:(view?.own?.revision??0)+1}});setNotice('Your answer is saved privately. Any answer edit clears earlier reveal choices.');})}>Save my private answer</button>
          <button disabled={blocked||!view?.own} onClick={()=>void run('Deleting your private answer…',async()=>{await privateCommand({encounterId:encounter.id,action:'delete',expectedRevision:view!.own!.revision});await store.draft(scope,encounter.id,null);if(alive.current)setDraft({text:'',objectId:pack.notice.objects[0]!.id,wardrobeId:null});})}>Delete my answer</button></div>
        {view?.choiceSubmitted&&<p className="encounter-own-submission">You chose to reveal this answer. You can review and choose again whenever you want.</p>}
        {savedMatches&&!paused&&<button disabled={blocked} onClick={()=>void run('Opening your exact reveal review…',async()=>{const value=await privateCommand({encounterId:encounter.id,action:'review',expectedRevision:view!.own!.revision});if(value.own&&!value.withdrawn&&alive.current)setPrivateReview(true);})}>Review my choice to reveal</button>}
      </div>
      {privateReview&&view?.own&&savedMatches&&<section className="encounter-reveal-review" aria-label="Review your private answer"><h4>Your exact answer</h4><p className="encounter-own-words">{view.own.text}</p><p>Reveal this answer only when both of us choose the current versions. Any answer change clears those choices. There are no answer or read receipts.</p>
        <button disabled={blocked} onClick={()=>void run('Saving your deliberate reveal choice…',async()=>{await privateCommand({encounterId:encounter.id,action:'reveal',expectedRevision:view.own!.revision,challenge:view.challenge});setNotice('Your choice is saved for this version. Return whenever you want to open the current encounter.');})}>Choose to reveal this version</button><button onClick={()=>setPrivateReview(false)}>Keep it private for now</button></section>}
      {view?.reveal&&<section className="encounter-revealed" aria-label="Our deliberately revealed answers"><h4>Two answers, in our own words</h4>{view.reveal.answers.map(answer=><article key={answer.memberId}><h5>{name(answer.memberId)}</h5><p>{answer.text}</p>{answer.wardrobeId&&pack.mechanic!=='mummers'&&<div>{wardrobe.find(w=>w.id===answer.wardrobeId)?.preview}<p>{wardrobe.find(w=>w.id===answer.wardrobeId)?.name??'Selected wardrobe item unavailable'}</p></div>}</article>)}
        <button disabled={blocked||Boolean(paused)} onClick={()=>void run('Opening the making table…',async()=>{if(!revealed)await shared({kind:'encounter.reveal',id:encounter.id,expectedRevision:current.current.revision,binding:view.reveal!.binding});changeStage('make');})}>Continue to making</button></section>}
    </section>}
    {stage==='make'&&revealed&&<section className="encounter-make" aria-labelledby={`${id}-make`}><h3 ref={heading} tabIndex={-1} id={`${id}-make`}>{pack.make.title}</h3><p>{pack.make.instruction}</p>{pack.mechanic==='mummers'&&<p>The portrait illustrations stay covered until each person places a guess or another clue. There are no points or right-answer grades.</p>}<p className="encounter-preview-label">Your arrangement above is a device draft until you place your contribution.</p>{choiceDirty.current&&(encounter.choices.find(c=>c.memberId===scope.memberId)?.revision??0)!==choiceBase.current&&<aside className="encounter-recovery"><p>Your shared contribution changed on another device. This draft has not overwritten it.</p><button onClick={()=>{const accepted=encounter.choices.find(c=>c.memberId===scope.memberId);if(accepted){choiceDirty.current=false;choiceBase.current=accepted.revision;setChoice(accepted);void store.make(scope,encounter.id,null);}}}>Use my current shared contribution</button></aside>}
      <fieldset><legend>My colour</legend><div className="encounter-colours">{pack.make.colours.map(c=><button type="button" key={c.id} aria-pressed={choice.colourId===c.id} disabled={blocked||Boolean(paused)} onClick={()=>editChoice({...choice,colourId:c.id})}><i style={{background:c.hex}} aria-hidden="true"/>{c.name}</button>)}</div></fieldset>
      <ol className="encounter-arrangement">{choice.order.map((item,index)=><li key={item}><strong>{pack.make.items.find(i=>i.id===item)?.name}</strong><span>Position {index+1}</span><button disabled={blocked||Boolean(paused)||index===0} aria-label={`Move ${pack.make.items.find(i=>i.id===item)?.name} earlier`} onClick={()=>{const order=[...choice.order];[order[index-1],order[index]]=[order[index]!,order[index-1]!];editChoice({...choice,order});}}>Move earlier</button></li>)}</ol>
      <label>{pack.make.wordLabel}<textarea maxLength={pack.mechanic==='incise'?16:500} value={choice.words} disabled={blocked||Boolean(paused)} onChange={e=>editChoice({...choice,words:e.target.value})}/></label>
      {pack.mechanic==='mummers'&&<label>Actual wardrobe piece for my portrait<select disabled={blocked} value={choice.wardrobeId??''} onChange={e=>editChoice({...choice,wardrobeId:e.target.value||null})}><option value="">Choose an available item</option>{wardrobe.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label>}
      <EncounterDrawing points={choice.drawing} disabled={blocked||Boolean(paused)} onChange={drawing=>editChoice({...choice,drawing})}/>
      <div className="encounter-toolbar"><button disabled={blocked||Boolean(paused)||(pack.mechanic==='mummers'&&(!choice.wardrobeId||!choice.words.trim()))} onClick={()=>void run('Placing your contribution…',async()=>{const previous=choiceBase.current;await store.make(scope,encounter.id,{baseRevision:previous,choice});await shared({kind:'encounter.choose',id:encounter.id,expectedChoiceRevision:previous,choice:{...choice,memberId:scope.memberId,revision:previous+1}});choiceDirty.current=false;choiceBase.current=previous+1;await store.make(scope,encounter.id,null);setNotice('Your contribution is shared. The other person’s work keeps its own author.');})}>Place my contribution</button><button disabled={encounter.choices.length!==2} onClick={()=>changeStage('keep')}>Review our keepsake</button></div>
      <section aria-label="Our placed contributions">{encounter.choices.map(c=><article key={c.memberId}><h4>{name(c.memberId)} placed</h4><p>{c.words||'An arrangement without words.'}</p><p>{c.order.map(i=>pack.make.items.find(item=>item.id===i)?.name).join(' → ')}</p></article>)}</section>
    </section>}
    {stage==='keep'&&revealed&&<section className="encounter-keep" aria-labelledby={`${id}-keep`}><h3 ref={heading} tabIndex={-1} id={`${id}-keep`}>{pack.keep.title}</h3><p>{pack.keep.invitation}</p>{studioPreview&&<figure className="encounter-studio-preview"><KittyFlat piece={{id:'encounter-preview',createdAt:'1970-01-01T00:00:00.000Z',firedAt:null,sculpt:studioPreview.sculpt,paint:{base:studioPreview.base,parts:{},strokes:studioPreview.derivedStrokes.map(s=>s.stroke),stamps:studioPreview.stamps}}} fired={false}/><figcaption>The actual Studio recipe, ready for your review. It is not fired yet.</figcaption></figure>}
      {view!.reveal!.answers.map(answer=><article className="encounter-caption" key={answer.memberId}><h4>{name(answer.memberId)} — their own words</h4><p>{answer.text}</p><p>{encounter.choices.find(c=>c.memberId===answer.memberId)?.words}</p><p>{encounter.choices.find(c=>c.memberId===answer.memberId)?.order.map(id=>pack.make.items.find(item=>item.id===id)?.name).join(' → ')}</p></article>)}
      <label className="encounter-check"><input type="checkbox" checked={keepReview} disabled={blocked||allKept} onChange={e=>setKeepReview(e.target.checked)}/>I reviewed this whole composition and both people’s words.</label>
      <button disabled={blocked||!keepReview||encounter.choices.length!==2||encounter.keptMemberIds.includes(scope.memberId)||Boolean(paused)} onClick={()=>void run('Keeping the composition you reviewed…',async()=>{await shared({kind:'encounter.keep',id:encounter.id,digest});setNotice('Your choice to keep this exact composition is saved.');})}>{encounter.keptMemberIds.includes(scope.memberId)?'You chose to keep this composition':'Keep this exact composition'}</button>
      {allKept&&<section className="encounter-kept"><h4>Chosen by both of us</h4><p>The next step opens a real creation or memory draft for review.</p>
        <button disabled={blocked} onClick={()=>void run('Opening the deliberate keepsake…',async()=>{const latest=await readPrivate();if(!latest.reveal||!same(latest.reveal.binding,encounter.reveal))throw Error('ANSWER_CHANGED');if(pack.keep.medium==='studio'){const recipe=await encounterStudioRecipe(encounter);if(alive.current)await onStudioKeepsake(recipe);}else{const svg=encounterKeepsakeSvg(encounter,view!.reveal!.answers,Object.fromEntries(roster.map(r=>[r.memberId,r.name])),wardrobe);const image=await encounterKeepsakePng(svg);if(alive.current)await onMemoryKeepsake({encounterId:encounter.id,compositionDigest:digest,title:pack.keep.label,image,answers:view!.reveal!.answers});}})}>{pack.keep.medium==='studio'?'Make this piece from our choices':'Open this card as a memory draft'}</button>
        {pack.keep.medium==='studio'&&<p>Made from the choices you both kept. You can continue shaping and painting in the Studio.</p>}</section>}
      <details><summary>Let this gesture belong to an intention</summary><p>This only links to an intention that already exists.</p><label>Existing intention<select value={link} onChange={e=>setLink(e.target.value)}><option value="">Keep this as its own gesture</option>{experiences.map(e=><option value={e.id} key={e.id}>{e.title}</option>)}</select></label><button disabled={blocked} onClick={()=>void run('Saving the chosen link…',()=>shared({kind:'encounter.link',id:encounter.id,expectedRevision:encounter.revision,experienceId:link||null}))}>Save this optional link</button></details>
      <button onClick={()=>onReplay(pack.id)}>Begin a fresh encounter</button>
    </section>}
    {(view?.reveal||encounter.reveal)&&<button className="encounter-withdraw" disabled={Boolean(busy)} onClick={()=>setWithdrawReview(true)}>Withdraw this reveal</button>}
    {withdrawReview&&<section className="encounter-reveal-review" aria-label="Withdraw this reveal"><h3>Close this reveal?</h3><p>Access to these answers closes first. Independently kept memories and pieces stay separate. Replay starts a fresh occurrence.</p><button disabled={Boolean(busy)} onClick={()=>void run('Closing this reveal…',async()=>{await privateCommand({encounterId:encounter.id,action:'withdraw'});await store.draft(scope,encounter.id,null);await store.make(scope,encounter.id,null);if(alive.current){setWithdrawReview(false);setDraft({text:'',objectId:pack.notice.objects[0]!.id,wardrobeId:null});}})}>Withdraw these answers now</button><button onClick={()=>setWithdrawReview(false)}>Keep it here</button></section>}
    </>}
  </article>;
}
function EncounterDrawing({points,onChange,disabled}:{points:{x:number;y:number}[];onChange:(points:{x:number;y:number}[])=>void;disabled:boolean}){
  const svg=useRef<SVGSVGElement>(null),active=useRef(false),working=useRef(points);working.current=points;
  const add=(e:PointerEvent<SVGSVGElement>)=>{if(disabled||!active.current||working.current.length>=128)return;const rect=e.currentTarget.getBoundingClientRect();const point={x:Math.round(Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width))*1000)/1000,y:Math.round(Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height))*1000)/1000};working.current=[...working.current,point];onChange(working.current);};
  return <details className="encounter-drawing"><summary>Add a drawn mark or a typed line</summary><p>The text field above is a complete alternative. A mark remains part of your own contribution.</p><svg ref={svg} viewBox="0 0 400 120" role="img" aria-label="Your optional drawn mark" onPointerDown={e=>{if(disabled)return;active.current=true;e.currentTarget.setPointerCapture(e.pointerId);add(e);}} onPointerMove={add} onPointerUp={()=>active.current=false} onPointerCancel={()=>active.current=false}><polyline points={points.map(p=>`${p.x*400},${p.y*120}`).join(' ')} fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/></svg><button disabled={disabled||!points.length} onClick={()=>onChange([])}>Clear my drawn mark</button><button disabled={disabled} onClick={()=>onChange([{x:.15,y:.6},{x:.35,y:.3},{x:.55,y:.6},{x:.8,y:.3}])}>Add a simple zigzag</button></details>;
}
export function SeasonalDiscoveries({theme,encounters,onOpen,onStart}:{theme:EncounterTheme;encounters:SharedEncounter[];onOpen:(id:string)=>void;onStart:(packId:string)=>void}){
  return <section className="seasonal-discoveries" data-theme={theme} aria-label="Seasonal discoveries"><h2>A season to discover together</h2><p>Choose any season. These are free, replayable encounters; there is no calendar deadline.</p><div className="seasonal-pack-grid">{ENCOUNTER_PACKS.filter(p=>p.theme===theme).map(pack=><article key={pack.id}><div aria-hidden="true" dangerouslySetInnerHTML={{__html:encounterSceneMarkup(pack)}}/><p>{pack.season}</p><h3>{pack.title}</h3><p>{pack.notice.invitation}</p><button onClick={()=>onStart(pack.id)}>Begin {pack.title}</button>{encounters.filter(e=>e.packId===pack.id).map((e,i)=><button key={e.id} onClick={()=>onOpen(e.id)}>Return to encounter {i+1}</button>)}</article>)}</div></section>;
}
