/** Original authored encounter content. No supplied lyrics, invented personal history, or money. */
export type EncounterTheme = 'classic' | 'taylor' | 'newfoundland';
export type EncounterSeason = 'spring' | 'summer' | 'autumn' | 'winter';
export type EncounterMechanic = 'pot' | 'weave' | 'incise' | 'hearth' | 'layers' | 'setlist' | 'ribbons' | 'foil' | 'boats' | 'berries' | 'kettle' | 'mummers';
export type EncounterPack = {
  version: 1; id: string; theme: EncounterTheme; season: EncounterSeason; title: string; mechanic: EncounterMechanic;
  notice: { title: string; invitation: string; prompt: string; objects: { id: string; name: string; discovery: string }[] };
  make: { title: string; instruction: string; wordLabel: string; items: { id: string; name: string }[]; colours: { id: string; name: string; hex: string }[] };
  keep: { title: string; invitation: string; medium: 'studio' | 'memory'; label: string };
};
const objects = (rows: [string, string, string][]) => rows.map(([id, name, discovery]) => ({ id, name, discovery }));
const items = (rows: [string, string][]) => rows.map(([id, name]) => ({ id, name }));
const colours = (rows: [string, string, string][]) => rows.map(([id, name, hex]) => ({ id, name, hex }));
const warm = colours([['ochre','Golden ochre','#bc762b'],['sage','Garden sage','#658568'],['clay','Terracotta','#b45b45'],['blue','Window blue','#537e9b']]);
const paper = colours([['rose','Pressed rose','#b75e80'],['blue','Notebook blue','#527bad'],['gold','Marigold foil','#b17b24'],['green','Vellum green','#638b71']]);
const coast = colours([['red','Painted red','#ae4d44'],['blue','Harbour blue','#346f8e'],['yellow','Lantern yellow','#b98b24'],['green','Spruce green','#467662']]);
export const ENCOUNTER_PACKS: readonly EncounterPack[] = [
  {version:1,id:'classic-spring-window',theme:'classic',season:'spring',title:'First Warm Window',mechanic:'pot',
    notice:{title:'Notice the light',invitation:'Open the little things on the sill. Keep one thought folded until you both choose to open it.',prompt:'What is one ordinary thing you would like more room for?',objects:objects([['window','Open the warm window','The room can hold a small beginning. It need not become a plan.'],['seed','Turn the seed packet','A seed asks for a little room, not a promise about the whole garden.'],['pot','Lift the empty pot','A shape can begin with what you already have.']])},
    make:{title:'Shape a place for it',instruction:'Choose your clay colour, arrange a base, belly and rim, and add a word. Both contributions shape the proposed seed-pot cat.',wordLabel:'A word to grow beside it',items:items([['base','Low base'],['belly','Round belly'],['rim','Open rim']]),colours:warm},keep:{title:'A small beginning, made by us',invitation:'Review both choices. This recipe opens a real Studio piece; firing remains your choice.',medium:'studio',label:'Seed-pot cat'}},
  {version:1,id:'classic-summer-evening',theme:'classic',season:'summer',title:'The Long Evening',mechanic:'weave',
    notice:{title:'Stay with an ordinary detail',invitation:'The evening needs no special occasion. Open the objects and choose what to notice.',prompt:'Which tiny detail of today would you like to tell me about?',objects:objects([['glass','Turn the water glass','A glass catches the last light even on an unremarkable day.'],['chair','Pull out the chair','There is space to sit down without having something impressive to say.'],['cord','Uncoil the linen cord','Separate strands can keep their own colour while becoming one thing.']])},
    make:{title:'Weave the evening',instruction:'Place your three strands in an order, choose their colour, and name your detail. Moving either person’s strands changes the woven card.',wordLabel:'My detail of this evening',items:items([['near','Near strand'],['over','Crossing strand'],['far','Far strand']]),colours:warm},keep:{title:'The evening cord',invitation:'Keep the exact weave you made, with each person’s own words. Linking it to an evening is optional.',medium:'memory',label:'Woven evening card'}},
  {version:1,id:'classic-autumn-shelf',theme:'classic',season:'autumn',title:'Stock the Shelf',mechanic:'incise',
    notice:{title:'Look at what has stayed',invitation:'The shelf holds only things you actually choose. Look closely before making another mark.',prompt:'What is something we have made room for that you still value?',objects:objects([['shelf','Brush the shelf','An empty place is ready, not evidence that anything is missing.'],['tool','Pick up the wooden tool','A deliberate mark can say enough.'],['cloth','Unfold the firing cloth','The final piece will be reviewed before any firing.']])},
    make:{title:'Leave a deliberate mark',instruction:'Choose an incision pattern, place its three marks, and add your own word. A real chosen piece can be brought back to the Studio, or you can begin a new one.',wordLabel:'My word for the incised-style pattern (16 characters)',items:items([['dash','Short incision'],['arc','Curved incision'],['dot','Round impression']]),colours:warm},keep:{title:'A piece for the shelf',invitation:'The Studio receives an attributed recipe. Choose and review a real revision there before firing.',medium:'studio',label:'Incised shelf cat'}},
  {version:1,id:'classic-winter-fire',theme:'classic',season:'winter',title:'Bank the Fire',mechanic:'hearth',
    notice:{title:'A little warmth',invitation:'This is an imagined hearth. Nothing needs to be earned before you sit here.',prompt:'What is one thing I did, or one thing about you, that you appreciate?',objects:objects([['log','Turn a little log','It can hold an ordinary kindness.'],['hearth','Look into the drawn hearth','The illustration stays warm whether or not you write tonight.'],['match','Open the matchbox','You may leave this for another evening.']])},
    make:{title:'Build the drawn hearth',instruction:'Arrange three named logs in your half of the hearth. Choose a colour and add your appreciation; the two arrangements make one illustration.',wordLabel:'My appreciation',items:items([['small','Small log'],['long','Long log'],['fork','Forked log']]),colours:warm},keep:{title:'Warmth we chose to keep',invitation:'Review the hearth card together. It can stay a gesture or be linked deliberately to an existing intention.',medium:'memory',label:'Drawn hearth card'}},
  {version:1,id:'taylor-spring-spread',theme:'taylor',season:'spring',title:'Blank Spread',mechanic:'layers',
    notice:{title:'Lift the first corner',invitation:'These are original paper stocks, ready for your words. No photograph or memory is assumed.',prompt:'What would you like to leave room for on this new page?',objects:objects([['vellum','Lift the vellum','Some things can remain lightly held.'],['lined','Touch the ruled paper','A line is somewhere to begin, not a deadline.'],['tape','Peel the paper tape','You can move things before you choose to keep them.']])},
    make:{title:'Layer our pages',instruction:'Choose your stock colour and move torn, ruled and vellum strips into a stack. Add your words; the stacking order changes the shared spread.',wordLabel:'My words for the page',items:items([['torn','Torn paper'],['ruled','Ruled strip'],['vellum','Vellum strip']]),colours:paper},keep:{title:'Our two-tone spread',invitation:'Review the actual layers and both texts. The memory draft will carry a new image of this composition.',medium:'memory',label:'Two-tone seasonal spread'}},
  {version:1,id:'taylor-summer-setlist',theme:'taylor',season:'summer',title:'Setlist of Us',mechanic:'setlist',
    notice:{title:'An ordinary soundtrack',invitation:'Bring your own song names and moments. This is an original page, without supplied lyrics or an invented ticket.',prompt:'Name a song and an ordinary moment you connect with it. A sound or silence is welcome too.',objects:objects([['speaker','Tap the drawn speaker','No music plays automatically. The song belongs to your own recollection.'],['page','Turn the blank setlist','You decide what was actually part of your day.'],['pencil','Pick up the pencil','A title and a few words can be enough.']])},
    make:{title:'Arrange our original setlist',instruction:'Choose an opening, middle and closing slot for your contribution. Enter your own song names or sounds, one per line; reorder the slots to change the card.',wordLabel:'My titles or sounds, one per line',items:items([['opening','Opening'],['middle','Middle'],['closing','Closing']]),colours:paper},keep:{title:'A setlist we supplied',invitation:'Review the names and moments. No lyrics, listening history or outside account is imported.',medium:'memory',label:'Original setlist card'}},
  {version:1,id:'taylor-autumn-ribbons',theme:'taylor',season:'autumn',title:'Ribbon Archive',mechanic:'ribbons',
    notice:{title:'Unfold a chosen month',invitation:'Choose what you want this season to hold. Earlier memories remain where you kept them.',prompt:'What ordinary part of this season would you like to remember in your own words?',objects:objects([['spool','Unwind the ribbon spool','A colour can belong to an ordinary month.'],['tag','Turn the empty tag','Write only what you choose to share.'],['spine','Open the blank spine','You can add a page without rewriting the earlier ones.']])},
    make:{title:'Tie our ribbon spine',instruction:'Set your ribbon colour, order the loop, knot and tail, and author your own tag. Each arrangement changes the illustrated binding.',wordLabel:'My ribbon tag',items:items([['loop','Ribbon loop'],['knot','Loose knot'],['tail','Ribbon tail']]),colours:paper},keep:{title:'A spine for this season',invitation:'Keep this ribbon composition first. It can later be deliberately selected for a memory reel.',medium:'memory',label:'Ribbon spine card'}},
  {version:1,id:'taylor-winter-foil',theme:'taylor',season:'winter',title:'Foil Stamp',mechanic:'foil',
    notice:{title:'Turn a word toward the light',invitation:'An original foil plate waits on the table. A word can be a possibility without becoming a resolution.',prompt:'What word would you like to hold lightly for the coming year?',objects:objects([['foil','Lift the foil sheet','The shine is decorative, never a reward.'],['plate','Turn the blank plate','Two words can sit beside one another.'],['press','Open the little press','Nothing is stamped until you choose the composition.']])},
    make:{title:'Arrange the cover plate',instruction:'Choose foil colour and place a star, leaf and ring. Your positions and your word shape an original cover plate, with room for the other person’s choices.',wordLabel:'My word for the year',items:items([['star','Original star'],['leaf','Leaf impression'],['ring','Simple ring']]),colours:paper},keep:{title:'A word, kept lightly',invitation:'Review both words and the exact plate. There are no progress targets or promises attached.',medium:'memory',label:'Original foil cover plate'}},
  {version:1,id:'newfoundland-spring-ice',theme:'newfoundland',season:'spring',title:'Ice Out',mechanic:'boats',
    notice:{title:'At an imagined harbour',invitation:'This chart is imagined scenery. Open its little objects, then keep your own answer private until you choose to reveal.',prompt:'Is there something you would like to set down for a while? “Nothing today” is a complete answer.',objects:objects([['ice','Turn the paper ice floe','The drawn water does not measure how you feel.'],['boat','Unfold the paper boat','Letting something rest need not mean making a decision.'],['chart','Look at the imagined chart','No location, route or personal journey is being recorded.']])},
    make:{title:'Launch two paper boats',instruction:'Choose your boat colour, arrange an inlet, channel and open-water route, and name what your boat carries. Each route stays its author’s.',wordLabel:'My boat carries',items:items([['inlet','Quiet inlet'],['channel','Narrow channel'],['open','Open water']]),colours:coast},keep:{title:'Our imagined chart',invitation:'Review both boats and their words. Keeping the chart does not create a trip or a task.',medium:'memory',label:'Imagined harbour chart'}},
  {version:1,id:'newfoundland-summer-berries',theme:'newfoundland',season:'summer',title:'Berry Ground',mechanic:'berries',
    notice:{title:'A small patch of summer',invitation:'The berry ground is illustrated. Bring an actual detail from your day if you want to.',prompt:'What is a small summer detail you would put in this bucket?',objects:objects([['patch','Look beneath the leaves','Ordinary details are welcome here.'],['bucket','Lift the empty bucket','There is no amount you need to collect.'],['label','Turn the preserve label','It will say only what you supply.']])},
    make:{title:'Fill our illustrated bucket',instruction:'Choose your berry colour and arrange three handfuls. Add your detail to the label; the other person’s colours and arrangement fill the other half.',wordLabel:'My detail for the label',items:items([['one','First handful'],['two','Second handful'],['three','Third handful']]),colours:coast},keep:{title:'A little summer preserved',invitation:'Review the bucket and separately authored label. This is a creative keepsake, not a claim that you visited a real berry patch.',medium:'memory',label:'Summer preserve label'}},
  {version:1,id:'newfoundland-autumn-mugup',theme:'newfoundland',season:'autumn',title:'Mug-Up',mechanic:'kettle',
    notice:{title:'Pull up a chair',invitation:'The drawn kettle can wait. There is no need to be here at the same time.',prompt:'Tell one small story from your day in your own words.',objects:objects([['kettle','Lift the kettle lid','A story can be short or unfinished.'],['mug','Turn the enamel mug','There is room for two accounts of an ordinary day.'],['stove','Look at the illustrated stove','The warmth is here without a contribution or a timer.']])},
    make:{title:'Set our mug-up table',instruction:'Arrange your mug, spoon and cloth, choose enamel colour and add the line you want to keep. Your placements form one table with two accounts.',wordLabel:'My line from today',items:items([['mug','Enamel mug'],['spoon','Small spoon'],['cloth','Folded cloth']]),colours:coast},keep:{title:'Both accounts, beside the stove',invitation:'Review each person’s words without merging them into a single story.',medium:'memory',label:'Mug-up stove card'}},
  {version:1,id:'newfoundland-winter-mummers',theme:'newfoundland',season:'winter',title:'Mummers’ Night',mechanic:'mummers',
    notice:{title:'Something familiar, disguised',invitation:'Use an actual item from your wardrobe collection. If the shelf is empty, you can make one in the Studio first.',prompt:'Choose your own clue for the other person. You decide how easy or mysterious it is.',objects:objects([['wardrobe','Open the wardrobe rail','Only actual wardrobe items can be selected below.'],['door','Tap the painted door','There is no demand to answer or visit now.'],['portrait','Turn the portrait frame','A dressed-up portrait will use what you actually chose.']])},
    make:{title:'Dress up and guess together',instruction:'Choose an available wardrobe piece and an optional clue. Place three portrait flourishes; then offer a guess in your own text. There are no points or correct-answer grades.',wordLabel:'My guess or another clue',items:items([['spark','A little spark'],['ribbon','Portrait ribbon'],['snow','Paper snow']]),colours:coast},keep:{title:'The two of us, dressed up',invitation:'Review the actual chosen wardrobe references and the illustrated portrait. It can remain playful without becoming a memory.',medium:'memory',label:'Mummers’ portrait card'}},
];
export function encounterPack(id: string): EncounterPack {
  const pack = ENCOUNTER_PACKS.find(p => p.id === id); if (!pack) throw new Error('ENCOUNTER_PACK_UNAVAILABLE'); return pack;
}
