import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {GuestRoomView} from './GuestRoomView.tsx';
import {guestClient,guestError,guestPendingStore,type GuestAuth,type GuestHostState,type GuestPending,type GuestSourceChoice,type GuestStreetState} from './guestClient.ts';
import type {GuestInvitationReview,GuestPrepareInput,GuestReview,GuestRoomKind,GuestSourceItem,GuestStreetCard,GuestTheme,GuestVisit} from './guestContracts.ts';
import './guestVisits.css';
export type GuestVisitsProps={auth:GuestAuth;theme:GuestTheme;embedded?:boolean;host?:{householdId:string;choices:GuestSourceChoice[]};onClose:()=>void};
/** Keying the entire surface prevents old identity content from rendering during scope transitions. */
export function GuestVisits(props:GuestVisitsProps){return <GuestVisitsScope key={props.auth.scopeKey+'|'+(props.host?.householdId||'street')} {...props}/>;}
const roomNames:Record<GuestRoomKind,string>={common:'Common room',studio:'Studio',conservatory:'Conservatory',theatre:'Theatre'};
const approvalText=(approvals:GuestReview['approvals'],memberId:string)=>approvals.map(p=>`${p.memberId===memberId?'You':'Household member'}: ${p.approved?'approved':'waiting'}`).join(' · ');
function GuestVisitsScope({auth,theme,host,onClose,embedded=false}:GuestVisitsProps){
 const Container=embedded?'section':'main',Heading=embedded?'h2':'h1';
 const client=useMemo(()=>guestClient(auth),[auth]),[street,setStreet]=useState<GuestStreetState|null>(null),[hosting,setHosting]=useState<GuestHostState|null>(null),[page,setPage]=useState<'street'|'host'>('street'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<GuestPending|null>(null),[ready,setReady]=useState(false),[label,setLabel]=useState(''),[active,setActive]=useState<{card:GuestStreetCard;host:boolean}|null>(null);
 const alive=useRef(true),abort=useRef(new AbortController()),titleRef=useRef<HTMLHeadingElement>(null);
 const refresh=useCallback(async()=>{const [nextStreet,nextHost]=await Promise.all([client.street(abort.current.signal),host?client.host(host.householdId,abort.current.signal):Promise.resolve(null)]);if(alive.current){setStreet(nextStreet);setHosting(nextHost);}},[client,host]);
 useEffect(()=>{alive.current=true;abort.current=new AbortController();void Promise.all([refresh(),guestPendingStore(auth.scopeKey)]).then(([,saved])=>{if(alive.current){setPending(saved);setReady(true);}}).catch(e=>{if(alive.current){setError(guestError(e));setReady(true);}});return()=>{alive.current=false;abort.current.abort();};},[auth.scopeKey,refresh]);
 async function submit(path:string,body:unknown,label:string){if(busy||pending||!ready)return;const intent:GuestPending={version:1,scopeKey:auth.scopeKey,path,body,label,createdAt:Date.now()};setBusy(true);setError('');try{await guestPendingStore(auth.scopeKey,intent);if(!alive.current)return;setPending(intent);await run(intent);}catch(e){if(alive.current)setError(guestError(e));}finally{if(alive.current)setBusy(false);}}
 async function run(intent:GuestPending){if(intent.scopeKey!==auth.scopeKey)throw Error('GUEST_UNAUTHENTICATED');await client.request(intent.path,intent.body,abort.current.signal);await guestPendingStore(auth.scopeKey,null);if(!alive.current)return;setPending(null);await refresh();}
 async function retry(){if(!pending||busy)return;setBusy(true);setError('');try{await run(pending);}catch(e){if(alive.current)setError(guestError(e));}finally{if(alive.current)setBusy(false);}}
 const hostAction=(body:unknown,label:string)=>host&&submit('host/'+host.householdId,body,label),disabled=busy||!!pending||!ready;
 const openHost=(p:GuestReview)=>{setActive({host:true,card:{id:p.id,publicationId:p.id,title:p.arrangement.title,theme:p.arrangement.theme,room:p.arrangement.room,mode:p.arrangement.mode,expiresAt:Number.MAX_SAFE_INTEGER}});};
 if(active)return <GuestVisitSession key={active.card.publicationId+active.card.id} embedded={embedded} auth={auth} hostHouseholdId={active.host?host?.householdId:undefined} card={active.card} onClose={()=>{setActive(null);void refresh().catch(e=>setError(guestError(e)));requestAnimationFrame(()=>titleRef.current?.focus());}}/>;
 return <Container className="guest-visits" data-guest-theme={theme} aria-label="Guest visits"><header className="guest-page-header"><div><p className="guest-eyebrow">The Boathouse · private street</p><Heading ref={titleRef} tabIndex={-1}>An open door, by invitation.</Heading><p>A small place to visit the rooms people have chosen to share with you.</p></div><button onClick={onClose}>Return to the Boathouse</button></header><nav className="guest-tabs" aria-label="Guest visits"><button aria-current={page==='street'?'page':undefined} onClick={()=>setPage('street')}>My street</button>{host&&<button aria-current={page==='host'?'page':undefined} onClick={()=>setPage('host')}>Prepare our room</button>}<button disabled={busy} onClick={()=>{setError('');void refresh().catch(e=>setError(guestError(e)));}}>Refresh</button></nav>
 {error&&<p className="guest-error" role="alert">{error}</p>}{!ready&&<p role="status">Opening your private street…</p>}
 {pending&&<aside className="guest-recovery" aria-label="Saved request"><h2>Finish your saved request</h2><p>{pending.label}. Its acknowledgement is uncertain. Retrying uses the same request.</p><button disabled={busy} onClick={()=>void retry()}>Retry saved request</button><button disabled={busy} onClick={()=>{void guestPendingStore(auth.scopeKey,null).then(()=>{if(alive.current)setPending(null);}).catch(e=>setError(guestError(e)));}}>Dismiss local request</button><p>Dismissal leaves any server acceptance in place. Refresh to review it.</p></aside>}
 {page==='street'?<><section className="guest-street" aria-label="Your invitations"><div className="guest-street-sky" aria-hidden="true"><span/><span/><span/></div><div className="guest-street-houses">{street?.visits.map(card=><article className="guest-house" key={card.id} data-guest-theme={card.theme}><div className="guest-house-roof" aria-hidden="true"/><div className="guest-house-front"><span className="guest-house-window" aria-hidden="true"/><h2>{card.title}</h2><p>{roomNames[card.room]}</p><p>{card.mode==='hosted'?'Visit while a host is here':'Visit in your own time'}</p><button className="guest-door" onClick={()=>setActive({card,host:false})}>Visit room</button><small>Until {new Date(card.expiresAt).toLocaleDateString()}</small><button className="guest-quiet" disabled={disabled} onClick={()=>void submit('visit/'+card.publicationId,{operation:'leave-street',grantId:card.id},'Leave this invitation')}>Leave my street</button></div></article>)}</div>{street&&!street.visits.length&&<div className="guest-street-empty"><h2>Your street has room to grow.</h2><p>Make a calling card and give its code to someone you know. Their room appears here after their household approves your invitation.</p></div>}</section>
 <section className="guest-calling-card"><div><p className="guest-eyebrow">A personal introduction</p><h2>Your calling cards</h2><p>You choose the name and share the code yourself. A card can receive new invitations for seven days. Revoking it closes invitations made with it.</p></div><form onSubmit={e=>{e.preventDefault();void submit('cards',{operation:'create',id:crypto.randomUUID(),label:label.trim()},'Create your calling card');}}><label>Name on this card<input value={label} maxLength={60} onChange={e=>setLabel(e.target.value)} required autoComplete="nickname"/></label><button disabled={disabled||!label.trim()}>Create a calling card</button></form><ul>{street?.cards.map(card=><li key={card.id}><strong>{card.label}</strong><span>{card.revoked?'Revoked':`New invitations until ${new Date(card.redeemBefore).toLocaleDateString()}`}</span>{!card.revoked&&<><label>Calling card code<input readOnly value={card.id} onFocus={e=>e.currentTarget.select()}/></label><button onClick={()=>void navigator.clipboard?.writeText(card.id).catch(()=>setError('Select the card code to copy it manually.'))}>Copy code</button><button disabled={disabled} onClick={()=>void submit('cards',{operation:'revoke',id:card.id},'Revoke this calling card and its visits')}>Revoke card and visits</button></>}</li>)}</ul></section></>:host&&<><GuestPrepareForm theme={theme} choices={host.choices} disabled={disabled} onPrepare={input=>void hostAction({operation:'prepare',input},'Prepare the exact guest room for joint review')}/><section aria-label="Joint room reviews" className="guest-reviews">{hosting?.publications.map(({publication:p,invitations})=><GuestPublication key={p.id} review={p} invitations={invitations} memberId={hosting.memberId} disabled={disabled} command={hostAction} onHost={()=>openHost(p)} loadMedia={(id,signal)=>client.media('host/'+host.householdId+'/media/'+id,{'X-Guest-Publication':p.id},signal)}/>)}</section></>}
 </Container>;
}
function GuestPrepareForm({theme,choices,disabled,onPrepare}:{theme:GuestTheme;choices:GuestSourceChoice[];disabled:boolean;onPrepare:(input:GuestPrepareInput)=>void}){
 const [title,setTitle]=useState('Our open door'),[welcome,setWelcome]=useState(''),[room,setRoom]=useState<GuestRoomKind>('common'),[mode,setMode]=useState<'hosted'|'anytime'>('hosted'),[selected,setSelected]=useState<GuestSourceItem[]>([]);
 function toggle(choice:GuestSourceChoice){setSelected(old=>old.some(i=>i.id===choice.id&&i.kind===choice.kind)?old.filter(i=>i.id!==choice.id||i.kind!==choice.kind):[...old,{kind:choice.kind,id:choice.id,revision:choice.revision,...(choice.designId?{designId:choice.designId}:{}),x:.2+(old.length%3)*.3,y:.3+Math.floor(old.length/3)*.14}]);}
 return <section className="guest-prepare"><div><p className="guest-eyebrow">A room you both choose</p><h2>Prepare a guest copy</h2><p>Choose exactly what belongs in this visit. You will both review the copied room before it can open. Each invitation then receives its own joint approval.</p></div><form onSubmit={e=>{e.preventDefault();onPrepare({publicationId:crypto.randomUUID(),title,welcome,theme,room,mode,items:selected});}}><div className="guest-form-pair"><label>Room name<input value={title} maxLength={100} required onChange={e=>setTitle(e.target.value)}/></label><label>Room<select value={room} onChange={e=>setRoom(e.target.value as GuestRoomKind)}>{Object.entries(roomNames).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label></div><label>Welcome message<textarea value={welcome} maxLength={800} onChange={e=>setWelcome(e.target.value)}/></label><fieldset><legend>When can guests visit?</legend><label><input type="radio" name="guest-mode" checked={mode==='hosted'} onChange={()=>setMode('hosted')}/> While a host is here</label><label><input type="radio" name="guest-mode" checked={mode==='anytime'} onChange={()=>setMode('anytime')}/> In their own time</label></fieldset><fieldset><legend>Objects for this copy ({selected.length}/12)</legend>{choices.length?choices.map(choice=>{const index=selected.findIndex(i=>i.id===choice.id&&i.kind===choice.kind),item=selected[index];return <div className="guest-source-choice" key={choice.kind+'/'+choice.id}><label><input type="checkbox" checked={!!item} disabled={!item&&selected.length>=12} onChange={()=>toggle(choice)}/>{choice.label}</label>{choice.detail&&<small>{choice.detail}</small>}{item&&<div className="guest-form-pair">{(['x','y'] as const).map(axis=><label key={axis}>{axis==='x'?'Across':'Down'}: {Math.round(item[axis]*100)}%<input type="range" min="10" max="90" step="1" value={Math.round(item[axis]*100)} onChange={e=>setSelected(old=>old.map((v,i)=>i===index?{...v,[axis]:Number(e.target.value)/100}:v))}/></label>)}</div>}</div>;}):<p>No shared objects are available. You can prepare an empty room with your own welcome.</p>}</fieldset><button disabled={disabled||!title.trim()}>Prepare exact room for review</button></form></section>;
}
function GuestPublication({review:p,invitations,memberId,disabled,command,onHost,loadMedia}:{review:GuestReview;invitations:GuestInvitationReview[];memberId:string;disabled:boolean;command:(body:unknown,label:string)=>unknown;onHost:()=>void;loadMedia:(id:string,signal:AbortSignal)=>Promise<Blob>}){
 const [card,setCard]=useState(''),[days,setDays]=useState(7),[checked,setChecked]=useState(false),[invitationChecks,setInvitationChecks]=useState<Record<string,boolean>>({});const mine=p.approvals.find(a=>a.memberId===memberId),approved=p.approvals.every(a=>a.approved);
 return <article className="guest-publication"><header><div><p className="guest-eyebrow">{p.state==='active'?'Open for approved invitations':p.state==='revoked'?'Closed guest copy':'Exact room review'}</p><h2>{p.arrangement.title}</h2><p>{approvalText(p.approvals,memberId)}</p></div><span>{p.arrangement.mode==='hosted'?'Host present':'Visit anytime'}</span></header>{p.state!=='revoked'&&<GuestRoomView arrangement={p.arrangement} loadMedia={loadMedia}/>}<div className="guest-review-actions">{p.state==='prepared'&&!mine?.approved&&<><label><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/> I reviewed this exact copied room and its contents.</label><button disabled={disabled||!checked} onClick={()=>command({operation:'approve',publicationId:p.id,digest:p.digest},'Approve this exact guest room')}>Approve this room</button></>}{(p.state==='prepared'||p.state==='accepted')&&<button disabled={disabled||!approved||p.ownerMemberId!==memberId} onClick={()=>command({operation:'activate',publicationId:p.id},'Open this jointly approved room')}>{p.ownerMemberId===memberId?'Open approved room':'Room creator opens this copy'}</button>}{p.state==='active'&&<button onClick={onHost}>Enter as host</button>}{p.state!=='revoked'&&<button disabled={disabled} onClick={()=>command({operation:'revoke',publicationId:p.id},'Close the guest room and all invitations')}>Close room and all visits</button>}</div>
 {p.state==='active'&&<form className="guest-invite-form" onSubmit={e=>{e.preventDefault();command({operation:'prepare-invitation',publicationId:p.id,input:{id:crypto.randomUUID(),cardCode:card.trim(),expiresAt:Date.now()+days*86400000}},'Prepare an invitation for joint review');}}><h3>Invite someone with their calling card</h3><label>Calling card code<input value={card} onChange={e=>setCard(e.target.value)} required pattern="[0-9a-f-]{36}" spellCheck={false}/></label><label>Invitation lasts<select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>One day</option><option value={7}>Seven days</option><option value={30}>Thirty days</option></select></label><button disabled={disabled}>Prepare invitation review</button></form>}
 <ul className="guest-invitations">{invitations.map(g=><li key={g.id}><h3>{g.recipientLabel}</h3><p>{g.state==='revoked'?'Invitation closed':`Invitation until ${new Date(g.expiresAt).toLocaleString()}`}</p><p>{approvalText(g.approvals,memberId)}</p>{g.state==='prepared'&&!g.approvals.find(a=>a.memberId===memberId)?.approved&&<><label><input type="checkbox" checked={!!invitationChecks[g.id]} onChange={e=>setInvitationChecks(old=>({...old,[g.id]:e.target.checked}))}/> I reviewed this recipient and expiry for this exact room.</label><button disabled={disabled||!invitationChecks[g.id]} onClick={()=>command({operation:'approve-invitation',publicationId:p.id,id:g.id,digest:g.digest},'Approve this exact invitation')}>Approve invitation</button></>}{g.state==='prepared'&&<button disabled={disabled||!g.approvals.every(a=>a.approved)} onClick={()=>command({operation:'activate-invitation',publicationId:p.id,id:g.id},'Add the approved invitation to their private street')}>Add approved invitation to their street</button>}{g.state!=='revoked'&&<button disabled={disabled} onClick={()=>command({operation:'revoke-invitation',publicationId:p.id,id:g.id},'Revoke this invitation')}>Revoke invitation</button>}</li>)}</ul></article>;
}
function GuestVisitSession({auth,card,hostHouseholdId,onClose,embedded=false}:{auth:GuestAuth;embedded?:boolean;card:GuestStreetCard;hostHouseholdId?:string;onClose:()=>void}){
 const Container=embedded?'section':'main',Heading=embedded?'h2':'h1';
 const client=useMemo(()=>guestClient(auth),[auth]),[visit,setVisit]=useState<GuestVisit|null>(null),[label,setLabel]=useState(''),[error,setError]=useState(''),[entered,setEntered]=useState(false),[busy,setBusy]=useState(false),sessionId=useRef(crypto.randomUUID()),alive=useRef(true),abort=useRef(new AbortController()),enteredRef=useRef(false),audio=useRef<AudioContext|null>(null);
 const path=hostHouseholdId?'host/'+hostHouseholdId:'visit/'+card.publicationId;
 const command=useCallback((operation:string,extra:Record<string,unknown>={},signal?:AbortSignal)=>client.request<GuestVisit>(path,hostHouseholdId?{operation:'host-'+operation,publicationId:card.publicationId,sessionId:sessionId.current,...extra}:{operation,grantId:card.id,sessionId:sessionId.current,...extra},signal),[client,path,hostHouseholdId,card]);
 const leave=useCallback(()=>{if(enteredRef.current){enteredRef.current=false;void command('leave',{},AbortSignal.timeout(5000)).catch(()=>{});}setEntered(false);setVisit(null);void audio.current?.close().catch(()=>{});audio.current=null;},[command]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;abort.current.abort();leave();};},[leave]);
 useEffect(()=>{if(!entered)return;let running=false;const timer=setInterval(()=>{if(running||!enteredRef.current)return;running=true;void command('pulse',{},abort.current.signal).then(result=>{if(alive.current&&enteredRef.current)setVisit(result);}).catch(e=>{if(alive.current){setError(guestError(e));leave();}}).finally(()=>{running=false;});},3000);const hidden=()=>{if(document.hidden){abort.current.abort();abort.current=new AbortController();leave();setError('The visit paused while you were away. Enter again when you are ready.');}};document.addEventListener('visibilitychange',hidden);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',hidden);};},[entered,command,leave]);
 async function enter(){setBusy(true);setError('');try{const result=await command('enter',{label:label.trim()},abort.current.signal);if(alive.current){enteredRef.current=true;setVisit(result);setEntered(true);}}catch(e){if(alive.current)setError(guestError(e));}finally{if(alive.current)setBusy(false);}}
 async function play(toy:'chime'|'firefly'|'ball'){if(hostHouseholdId||!enteredRef.current)return;try{const result=await command('toy',{toy,x:toy==='ball'?.58:.5,y:toy==='ball'?.8:.3},abort.current.signal);if(alive.current&&enteredRef.current){setVisit(result);if(toy==='chime'){if(typeof AudioContext==='undefined'){setError('The chime is shown visually on this device.');return;}const context=audio.current||(audio.current=new AudioContext());void context.resume().then(()=>{if(!enteredRef.current||context.state==='closed')return;const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=660;gain.gain.setValueAtTime(.045,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.5);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.5);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};}).catch(()=>{});}}}catch(e){if(alive.current)setError(guestError(e));}}
 const loadMedia=useCallback((id:string,signal:AbortSignal)=>client.media(path+'/media/'+id,hostHouseholdId?{'X-Guest-Publication':card.publicationId}:{'X-Guest-Grant':card.id},signal),[client,path,hostHouseholdId,card]);
 return <Container className="guest-visits guest-session" data-guest-theme={card.theme} aria-label="Private visit"><header className="guest-page-header"><div><p className="guest-eyebrow">{hostHouseholdId?'Hosting your room':'A private visit'}</p><Heading>{card.title}</Heading></div><button onClick={()=>{leave();onClose();}}>Leave room</button></header>{error&&<p role="alert" className="guest-error">{error}</p>}{!entered?<form className="guest-enter" onSubmit={e=>{e.preventDefault();void enter();}}><h2>How shall we introduce you?</h2><label>Name shown during this visit<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={60} autoComplete="nickname" required/></label><button disabled={busy||!label.trim()}>Enter {hostHouseholdId?'as host':'room'}</button><p>{card.mode==='hosted'?'This room stays open while a host is present.':'This is a shared copy you can visit in your own time.'}</p></form>:visit&&<><GuestRoomView arrangement={visit.arrangement} presence={visit.presence} toys={visit.toys} loadMedia={loadMedia}/>{!hostHouseholdId&&<nav className="guest-play" aria-label="Play in the room"><button onClick={()=>void play('chime')}>Ring the chime</button><button onClick={()=>void play('firefly')}>Release a firefly</button><button onClick={()=>void play('ball')}>Roll a soft ball</button></nav>}<p className="guest-footnote">The objects in this room are the exact copy its household approved.</p></>}</Container>;
}
