import {NestGuestOrnament} from './NestGuestOrnament.tsx';
import {useEffect,useId,useRef,useState} from 'react';
import {RoomScene} from './RoomScene.tsx';
import {KittyFlat} from '../kitty/studio/flat.tsx';
import {guestDisplayPiece,type GuestMedia,type GuestObject} from './guestContracts.ts';
import type {GuestPreviewProps} from './guestClient.ts';
import './guestVisits.css';
function Media({media,load}:{media:GuestMedia;load:NonNullable<GuestPreviewProps['loadMedia']>}){const [url,setUrl]=useState(''),[failed,setFailed]=useState(false);useEffect(()=>{const abort=new AbortController();let objectUrl='';void load(media.id,abort.signal).then(blob=>{if(abort.signal.aborted)return;objectUrl=URL.createObjectURL(blob);setUrl(objectUrl);}).catch(()=>{if(!abort.signal.aborted)setFailed(true);});return()=>{abort.abort();if(objectUrl)URL.revokeObjectURL(objectUrl);setUrl('');};},[media.id,load]);if(failed)return <p role="status">This shared media is unavailable.</p>;if(!url)return <p role="status">Opening shared media…</p>;return media.kind==='image'?<img src={url} alt={media.alt} loading="lazy" onError={()=>setFailed(true)}/>:<audio src={url} controls preload="metadata" aria-label={media.alt||'Shared voice recording'} onError={()=>setFailed(true)}/>;}
function objectTitle(object:GuestObject){return object.kind==='piece'?'Painted cat':object.kind==='note'?'Welcome note':object.title;}
export function GuestRoomView({arrangement,presence=[],toys=[],loadMedia}:GuestPreviewProps){const id=useId().replace(/:/g,''),[opened,setOpened]=useState<string|null>(null),detail=useRef<HTMLDivElement>(null);const object=arrangement.objects.find(o=>o.id===opened);const composition=JSON.stringify(arrangement);useEffect(()=>{setOpened(null);},[composition]);return <section className="guest-room" data-guest-theme={arrangement.theme} aria-label={`${arrangement.title}, ${arrangement.room} room`}><div className="guest-authored-room"><RoomScene room={arrangement.room} theme={arrangement.theme} furniture={arrangement.furniture} illustrated objects={arrangement.objects.map(o=>({id:id+'-'+o.id,kind:o.kind,label:objectTitle(o),surfaceLabel:o.kind==='memory'?'Memory':o.kind==='piece'?'Painted cat':o.kind==='note'?'Welcome note':'An intention',x:o.x,y:o.y,preview:o.kind==='piece'?<><KittyFlat piece={guestDisplayPiece(o.appearance)} step={0} fired={false} title="Painted cat at a standard display size"/>{o.appearance.ornament&&<NestGuestOrnament ornament={o.appearance.ornament}/>}</>:undefined,onActivate:()=>{setOpened(o.id);requestAnimationFrame(()=>detail.current?.focus());}}))}/><div className="guest-toy-layer" aria-hidden="true">{toys.map(toy=><span key={toy.id} className={`guest-toy guest-toy--${toy.toy}`} style={{left:`${toy.x*100}%`,top:`${toy.y*100}%`}}>{toy.toy==='chime'?'♪':toy.toy==='firefly'?'✦':'●'}</span>)}</div></div><p className="guest-welcome">{arrangement.welcome||'A room prepared for a visit.'}</p>{presence.length>0&&<p className="guest-presence" aria-live="polite">Here now: {presence.map(p=>`${p.label} (${p.host?'host':'guest'})`).join(', ')}</p>}{object&&<div className="guest-object-detail" ref={detail} tabIndex={-1} role="region" aria-label={objectTitle(object)}><h3>{objectTitle(object)}</h3>{object.kind==='piece'?<><KittyFlat piece={guestDisplayPiece(object.appearance)} step={0} fired={false} title="Painted cat at a standard display size"/>{object.appearance.ornament&&<NestGuestOrnament ornament={object.appearance.ornament}/>}</>:object.kind==='memory'?<>{object.captions.map((c,i)=><blockquote key={i}><p>{c.text}</p><cite>{c.label}</cite></blockquote>)}{object.pieces.map((appearance,i)=><span key={i}><KittyFlat piece={guestDisplayPiece(appearance)} step={0} fired={false} title={`Painted cat ${i+1} at a standard display size`}/>{appearance.ornament&&<NestGuestOrnament ornament={appearance.ornament}/>}</span>)}{loadMedia&&object.media.map(m=><Media key={m.id} media={m} load={loadMedia}/>)}</>:<p>{object.text}</p>}<button onClick={()=>{setOpened(null);document.getElementById(id+'index')?.focus();}}>Close detail</button></div>}<span id={id+'index'} tabIndex={-1} className="guest-sr">Room contents</span></section>;}
