import type {GuestArrangement,GuestInvitationReview,GuestReview,GuestSourceItem,GuestStreetCard,GuestVisit} from './guestContracts.ts';
export type GuestAuth={/** Stable identity/session partition supplied by Auth, never a host household replica. */scopeKey:string;token:()=>Promise<string>;baseUrl?:string};
export type GuestOwnedCard={version:1;id:string;label:string;redeemBefore:number;revoked:boolean};
export type GuestHostState={version:1;memberId:string;publications:{publication:GuestReview;invitations:GuestInvitationReview[]}[]};
export type GuestStreetState={version:1;visits:GuestStreetCard[];cards:GuestOwnedCard[]};
export type GuestSourceChoice=Omit<GuestSourceItem,'x'|'y'>&{label:string;detail?:string};
export type GuestPending={version:1;scopeKey:string;path:string;body:unknown;label:string;createdAt:number};
export function guestError(error:unknown):string {
 const code=error instanceof Error?error.message:'';
 if(code==='AbortError')return 'The visit has closed.';
 return ({GUEST_IMAGE_PREPARATION_REQUIRED:'One image needs to be prepared again before it can enter a guest copy. Open its memory and choose the photo again.',GUEST_DISABLED:'Guest visits are not enabled here yet.',GUEST_PUBLICATION_DISABLED:'Publishing is not enabled here yet.',GUEST_UNAUTHENTICATED:'Sign in again to continue.',GUEST_HOST_AWAY:'Your hosts are away. This room opens while a host is here.',GUEST_ROSTER_CHANGED:'The household has changed. Prepare a new review together.',GUEST_SOURCE_CHANGED:'The selected content changed. Prepare a new review.',GUEST_SOURCE_UNAVAILABLE:'Some selected content is no longer available for sharing.',GUEST_CARD_UNAVAILABLE:'That calling card is unavailable or has expired.',GUEST_APPROVAL_REQUIRED:'Everyone in the household needs to approve this exact review.',GUEST_CREATOR_REQUIRED:'The person who prepared the room can finish opening it.',GUEST_CLOSED:'This visit has closed.',GUEST_NOT_FOUND:'This visit is no longer available.',GUEST_GRANT_REVOKED:'This invitation has closed.',GUEST_TOY_PAUSE:'Give the room a moment before playing again.',GUEST_RESTORE_REQUIRED:'Guest records are recovering. Please try again later.',GUEST_ID_REUSED:'That saved request no longer matches. Dismiss it and start a new review.'} as Record<string,string>)[code]||'The connection was interrupted. Your saved request can be retried.';
}
export function guestClient(auth:GuestAuth){
 async function credential(signal:AbortSignal):Promise<string>{return new Promise((resolve,reject)=>{const stop=()=>reject(new DOMException('Guest request ended','AbortError'));if(signal.aborted){stop();return;}signal.addEventListener('abort',stop,{once:true});void auth.token().then(token=>{signal.removeEventListener('abort',stop);if(signal.aborted)stop();else resolve(token);},error=>{signal.removeEventListener('abort',stop);reject(error);});});}
 const bounded=(signal?:AbortSignal)=>signal?AbortSignal.any([signal,AbortSignal.timeout(12000)]):AbortSignal.timeout(12000);
 async function request<T>(path:string,body?:unknown,signal?:AbortSignal,extra?:Record<string,string>):Promise<T>{signal=bounded(signal);const token=await credential(signal);if(signal?.aborted)throw new DOMException('Closed','AbortError');const response=await fetch((auth.baseUrl||'')+'/api/hearthside-guests/development/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:`Bearer ${token}`,...(body===undefined?{}:{'Content-Type':'application/json'}),...extra},cache:'no-store',signal,...(body===undefined?{}:{body:JSON.stringify(body)})});if(!response.ok){let code='GUEST_UNAVAILABLE';try{code=(await response.json()).code||code;}catch{/* Provider bodies are not user-facing. */}throw Error(code);}return response.json() as Promise<T>;}
 async function media(path:string,headers:Record<string,string>,signal:AbortSignal):Promise<Blob>{signal=bounded(signal);const token=await credential(signal);if(signal.aborted)throw new DOMException('Closed','AbortError');const response=await fetch((auth.baseUrl||'')+'/api/hearthside-guests/development/'+path,{headers:{Authorization:`Bearer ${token}`,...headers},cache:'no-store',signal});if(!response.ok){await response.body?.cancel();throw Error('GUEST_NOT_FOUND');}const length=Number(response.headers.get('Content-Length')),mime=response.headers.get('Content-Type')?.split(';')[0]||'';if(length>8*1024*1024||!['image/png','image/jpeg','audio/webm','audio/mp4','audio/ogg'].includes(mime)||!response.body){await response.body?.cancel();throw Error('GUEST_MEDIA_CHANGED');}const reader=response.body.getReader(),chunks:ArrayBuffer[]=[];let size=0;try{while(true){const part=await reader.read();if(part.done)break;size+=part.value.byteLength;if(size>8*1024*1024)throw Error('GUEST_MEDIA_CHANGED');chunks.push(new Uint8Array(part.value).buffer);}if(!size||length&&size!==length)throw Error('GUEST_MEDIA_CHANGED');return new Blob(chunks,{type:mime});}finally{await reader.cancel().catch(()=>{});reader.releaseLock();}}
 return {request,media,street:(signal?:AbortSignal)=>request<GuestStreetState>('street',undefined,signal),host:(householdId:string,signal?:AbortSignal)=>request<GuestHostState>('host/'+encodeURIComponent(householdId),undefined,signal)};
}
/** A single durable manual intent per identity partition. No token, media or source snapshot. */
export async function guestPendingStore(scopeKey:string,value?:GuestPending|null):Promise<GuestPending|null>{
 const db=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('hearthside-guest-intents-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('pending');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('Guest recovery storage is unavailable.'));});
 try{return await new Promise<GuestPending|null>((resolve,reject)=>{const tx=db.transaction('pending',value===undefined?'readonly':'readwrite'),store=tx.objectStore('pending');let result:GuestPending|null=null;const request=value===undefined?store.get(scopeKey):value===null?store.delete(scopeKey):store.put(value,scopeKey);request.onsuccess=()=>{if(value===undefined)result=request.result as GuestPending||null;};tx.oncomplete=()=>resolve(result);tx.onerror=tx.onabort=()=>reject(Error('Guest recovery storage is unavailable.'));});}finally{db.close();}
}
export type GuestPreviewProps={arrangement:GuestArrangement;presence?:GuestVisit['presence'];toys?:GuestVisit['toys'];loadMedia?:(id:string,signal:AbortSignal)=>Promise<Blob>};
