import {useEffect,useRef,useState} from 'react';
import type {Household} from '../core/types.ts';
import type {SharedExperience} from './contracts.ts';
import {commitHearthside,type HearthsideOperation} from './commands.ts';
type Draft={recordId:string;title:string;notes:string;date:string;end:string;assignee:string;allDay:boolean;timezone:string};
export function LifeStepComposer(props:{kind:'task'|'date';experience:SharedExperience;household:Household;memberId:string;identity:string;canSave:boolean;submit:(operation:HearthsideOperation)=>Promise<boolean>;onClose:()=>void}){
  return <Composer key={`${props.identity}:${props.experience.id}:${props.kind}`} {...props}/>;
}
function Composer({kind,experience,household,memberId,identity,canSave,submit,onClose}:Parameters<typeof LifeStepComposer>[0]){
  const key=`hearth:hearthside:step:${identity}:${experience.id}:${kind}`;
  const [recovery]=useState(()=>{const blank:Draft={recordId:`${kind==='task'?'TASK':'EVENT'}-${crypto.randomUUID()}`,title:experience.title,notes:'',date:'',end:'',assignee:'',allDay:true,timezone:'America/Toronto'};
    try{const raw=sessionStorage.getItem(key);if(!raw)return {draft:blank,error:''};const value=JSON.parse(raw) as Draft;if(!value||Object.keys(value).some(k=>!Object.keys(blank).includes(k))||Object.entries(blank).some(([k,v])=>typeof value[k as keyof Draft]!==typeof v)||!new RegExp(`^${kind==='task'?'TASK':'EVENT'}-[a-zA-Z0-9-]{1,80}$`).test(value.recordId))throw Error();return {draft:value,error:''};}catch{return {draft:blank,error:'The earlier device draft could not be read. It is retained for recovery.'};}});
  const [draft,setDraft]=useState(recovery.draft),[message,setMessage]=useState(recovery.error),[working,setWorking]=useState(false),alive=useRef(false),lock=useRef(false);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  useEffect(()=>{if(recovery.error)return;try{sessionStorage.setItem(key,JSON.stringify(draft));}catch{setMessage('This device cannot retain the unfinished step. Keep this page open.');}},[key,draft]);
  useEffect(()=>{if(experience.references.some(ref=>ref.id===draft.recordId&&ref.kind===(kind==='task'?'task':'calendar-event'))){sessionStorage.removeItem(key);onClose();}},[experience.revision]);
  function edit<K extends keyof Draft>(field:K,value:Draft[K]){setDraft({...draft,[field]:value});}
  async function save(){
    if(!canSave||lock.current||recovery.error)return;lock.current=true;setWorking(true);setMessage('');
    const common={id:experience.id,expectedRevision:experience.revision};
    const operation:HearthsideOperation=kind==='task'?{...common,kind:'experience.add-task',task:{memberId,id:draft.recordId,expectedRevision:0,task:{visibility:'household',title:draft.title,notes:draft.notes,listId:null,parentId:null,doDate:draft.date||null,dueDate:null,repeat:'none',cue:'none',assigneeId:draft.assignee||null,backupId:null,chapterId:null,planReference:null,moneyLink:null,expectedAmountCents:null,deleted:false}}}:{...common,kind:'experience.schedule',event:{memberId,id:draft.recordId,expectedRevision:0,event:{visibility:'household',title:draft.title,notes:draft.notes,start:draft.date,end:draft.end||draft.date,allDay:draft.allDay,timezone:draft.timezone,fold:'earlier',repeat:'none',until:null,location:'',exceptions:{},deleted:false}}};
    try{commitHearthside(household,{version:1,id:crypto.randomUUID(),scope:{environment:household.environment,householdId:household.householdId,memberId},operation});if(await submit(operation)){sessionStorage.removeItem(key);if(alive.current)onClose();}}catch(error){if(alive.current)setMessage(error instanceof Error?error.message:'This step could not be confirmed.');}finally{if(alive.current){lock.current=false;setWorking(false);}}
  }
  return <section className="hearthside-editor" aria-label={kind==='task'?'Connected task draft':'Connected date draft'}><form onSubmit={e=>{e.preventDefault();void save();}}><h2>{kind==='task'?'A practical next step':'Make a little time for this'}</h2><p>Connected to {experience.title}.</p><label>{kind==='task'?'What needs doing':'What we are making time for'}<input autoFocus required maxLength={160} disabled={working} value={draft.title} onChange={e=>edit('title',e.target.value)}/></label><label>A little context<textarea aria-label="A little context" maxLength={2000} disabled={working} value={draft.notes} onChange={e=>edit('notes',e.target.value)}/></label>
    {kind==='task'?<><label>Who will take it<select aria-label="Who will take it" value={draft.assignee} disabled={working} onChange={e=>edit('assignee',e.target.value)}><option value="">We will choose</option>{household.members.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>A day to do it, if useful<input type="date" disabled={working} value={draft.date} onChange={e=>edit('date',e.target.value)}/></label><p>The responsible person accepts it in the Planner. Completion stays with that one task.</p></>:<><label className="hearthside-checkbox"><input type="checkbox" disabled={working} checked={draft.allDay} onChange={e=>{setDraft({...draft,allDay:e.target.checked,date:draft.date.slice(0,10)+(e.target.checked?'':'T18:00'),end:draft.end.slice(0,10)+(e.target.checked?'':'T19:00')});}}/>An all-day date</label><label>Starts<input required disabled={working} type={draft.allDay?'date':'datetime-local'} value={draft.date} onChange={e=>edit('date',e.target.value)}/></label><label>Ends<input required={!draft.allDay} disabled={working} type={draft.allDay?'date':'datetime-local'} value={draft.end} onChange={e=>edit('end',e.target.value)}/></label><label>Timezone<input required disabled={working} value={draft.timezone} onChange={e=>edit('timezone',e.target.value)}/></label><p>This creates one linked date in Hearth’s Calendar. Its plans and costs remain separate.</p></>}
    {message&&<p role="status">{message}</p>}<div className="hearthside-actions"><button disabled={!canSave||working||Boolean(recovery.error)}>{kind==='task'?'Add this connected task':'Add this date to Calendar'}</button><button type="button" disabled={working} onClick={onClose}>Keep draft for later</button></div></form></section>;
}
