import {useEffect,useId,useRef,useState,type RefObject} from 'react';
import {createPortal} from 'react-dom';
import {clampFurnitureCoordinate,roomFurnitureCatalogue,roomFurnitureOffset,type FurnitureMove,type FurnitureRoom,type RoomFurnitureLayout} from './roomFurniture.ts';
type Props={room:FurnitureRoom;layout:RoomFurnitureLayout;scene:RefObject<HTMLElement|null>;onSave?: (move:FurnitureMove)=>Promise<void>;onPreview:(layout:RoomFurnitureLayout|null)=>void;suspended?:boolean;saveAvailable?:boolean};
/** Local drafts never enter shared state. The host resolves Save only after its authenticated CAS command succeeds. */
export function FurnitureArranger({room,layout,scene,onSave,onPreview,suspended=false,saveAvailable=true}:Props){
 const id=useId(),[draft,setDraft]=useState<FurnitureMove|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[handle,setHandle]=useState<{x:number;y:number}|null>(null);
 const live=useRef(true),returnFocus=useRef<HTMLButtonElement|null>(null),preview=useRef(onPreview);preview.current=onPreview;
 const dragging=useRef<{id:number;clientX:number;clientY:number;x:number;y:number;inverse:DOMMatrix}|null>(null),dragButton=useRef<HTMLButtonElement|null>(null);
 const rows=roomFurnitureCatalogue(room),definition=rows.find(r=>r.id===draft?.furnitureId),latest=layout.placements.find(p=>p.furnitureId===draft?.furnitureId),conflict=Boolean(draft&&latest?.revision!==draft.expectedRevision),layoutKey=JSON.stringify(layout);
 const selected=draft&&!suspended?{...layout,placements:layout.placements.map(p=>p.furnitureId===draft.furnitureId?{...p,x:draft.x,y:draft.y}:p)}:null;
 const active=useRef({draft,definition,busy,suspended});active.current={draft,definition,busy,suspended};
 useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
 useEffect(()=>{preview.current(selected);},[draft?.furnitureId,draft?.x,draft?.y,draft?.expectedRevision,layoutKey,suspended]); // The preview callback changes identity with the host render.
 useEffect(()=>{if(suspended){setDraft(null);dragging.current=null;}},[suspended]);
 useEffect(()=>{
  if(!draft||suspended)return;const element=scene.current,svg=element?.querySelector<SVGSVGElement>('.hsr-art'),stage=element?.querySelector<HTMLElement>('.hsr-stage');if(!element||!svg||!stage)return;
  const art=Array.from(svg.querySelectorAll<SVGGElement>(`[data-furniture-art="${draft.furnitureId}"]`));art.forEach(g=>g.dataset.furnitureSelected='true');
  function start(event:PointerEvent){const current=active.current;if(current.busy||current.suspended||!current.draft||event.button!==0)return;const target=event.target as Element;if(!target.closest(`[data-furniture-art="${current.draft.furnitureId}"]`)&&!target.closest('.hsr-furniture-handle'))return;const matrix=svg!.getScreenCTM();if(!matrix)return;event.preventDefault();const capture=event.currentTarget as Element;capture.setPointerCapture(event.pointerId);dragging.current={id:event.pointerId,clientX:event.clientX,clientY:event.clientY,x:current.draft.x,y:current.draft.y,inverse:matrix.inverse()};}
  function move(event:PointerEvent){const d=dragging.current,current=active.current;if(!d||d.id!==event.pointerId||!current.definition||!current.draft)return;event.preventDefault();const dx=event.clientX-d.clientX,dy=event.clientY-d.clientY;setDraft({...current.draft,x:clampFurnitureCoordinate(d.x+(d.inverse.a*dx+d.inverse.c*dy)*.42/current.definition.travel[0]),y:clampFurnitureCoordinate(d.y+(d.inverse.b*dx+d.inverse.d*dy)*.42/current.definition.travel[1])});}
  function end(event:PointerEvent){const d=dragging.current;if(!d||d.id!==event.pointerId)return;if(event.type==='pointercancel'||event.type==='lostpointercapture')setDraft(current=>current?{...current,x:d.x,y:d.y}:null);dragging.current=null;const capture=event.currentTarget as Element;if(capture.hasPointerCapture(event.pointerId))capture.releasePointerCapture(event.pointerId);}
  const targets=[svg,dragButton.current].filter(Boolean) as (SVGSVGElement|HTMLButtonElement)[];for(const t of targets){t.addEventListener('pointerdown',start as EventListener);t.addEventListener('pointermove',move as EventListener);for(const e of ['pointerup','pointercancel','lostpointercapture'])t.addEventListener(e,end as EventListener);}
  return()=>{dragging.current=null;art.forEach(g=>delete g.dataset.furnitureSelected);for(const t of targets){t.removeEventListener('pointerdown',start as EventListener);t.removeEventListener('pointermove',move as EventListener);for(const e of ['pointerup','pointercancel','lostpointercapture'])t.removeEventListener(e,end as EventListener);}};
 },[draft?.furnitureId,suspended,handle===null]);
 useEffect(()=>{if(!selected||!definition){setHandle(null);return;}const svg=scene.current?.querySelector<SVGSVGElement>('.hsr-art'),stage=scene.current?.querySelector<HTMLElement>('.hsr-stage');if(!svg||!stage)return;const place=()=>{const matrix=svg.getScreenCTM();if(!matrix)return;const delta=roomFurnitureOffset(selected,definition.id),point=new DOMPoint(definition.anchor[0]+delta[0],definition.anchor[1]+delta[1]).matrixTransform(matrix),box=stage.getBoundingClientRect();setHandle({x:point.x-box.left,y:point.y-box.top});};place();const observer=new ResizeObserver(place);observer.observe(stage);window.addEventListener('resize',place);return()=>{observer.disconnect();window.removeEventListener('resize',place);};},[draft?.furnitureId,draft?.x,draft?.y,suspended]);
 function close(){if(busy)return;dragging.current=null;setDraft(null);setMessage('');requestAnimationFrame(()=>returnFocus.current?.focus());}
 function begin(furnitureId:FurnitureMove['furnitureId'],button:HTMLButtonElement){const value=layout.placements.find(p=>p.furnitureId===furnitureId)!;returnFocus.current=button;setDraft({room,furnitureId,expectedRevision:value.revision,x:value.x,y:value.y});setMessage('');}
 async function save(){if(!draft||!onSave||conflict||busy||!saveAvailable)return;setBusy(true);const label=definition!.label;try{await onSave({...draft});if(live.current){setDraft(null);setMessage(`${label} position saved.`);requestAnimationFrame(()=>returnFocus.current?.focus());}}catch(error){if(live.current)setMessage(error instanceof Error&&error.message==='HEARTHSIDE_FURNITURE_CONFLICT'?'This piece moved while you were arranging. Use its latest position and review your change again.':'The position has not been confirmed. Keep this draft, then try Save again.');}finally{if(live.current)setBusy(false);}}
 return <section className="hsr-furniture-index" aria-labelledby={`${id}-furniture`}><header><h3 id={`${id}-furniture`}>The room around us</h3><p>{onSave?'Give the furniture a place that feels like us.':'Furniture in this room’s saved arrangement.'}</p></header><ul>{rows.map(row=>{const value=layout.placements.find(p=>p.furnitureId===row.id)!;return <li key={row.id}><span><strong>{row.label}</strong><small>{row.description}</small></span>{onSave?<button type="button" disabled={busy} id={`hearthside-furniture-${room}-${row.id}`} aria-label={`Arrange ${row.label}`} onClick={e=>begin(row.id,e.currentTarget)}>Arrange <span aria-hidden="true">↔</span></button>:<span className="hsr-furniture-position">{(value.x*100).toFixed(1)}% across · {(value.y*100).toFixed(1)}% depth</span>}</li>;})}</ul>
 {draft&&!suspended&&definition&&onSave&&<form className="hsr-arranger hsr-furniture-arranger" aria-label={`Arrange furniture: ${definition.label}`} onSubmit={e=>{e.preventDefault();void save();}} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();close();}}}><h3>A place for {definition.label.toLowerCase()}</h3>{!saveAvailable&&!busy&&<p role="status">Saving is unavailable right now. This arrangement remains a draft.</p>}<p>The whole room is visible while you arrange. Drag the highlighted furniture or its handle, or use these precise sliders. The same position follows you between themes and devices.</p>{conflict&&<p role="alert">This piece has a newer saved position. Your draft has not replaced it.</p>}{conflict&&<button type="button" disabled={busy} onClick={()=>{setDraft({...draft,expectedRevision:latest!.revision,x:latest!.x,y:latest!.y});setMessage('Latest position loaded. Review before saving.');}}>Use latest position</button>}
 <label htmlFor={`${id}-x`}>Across its space <output>{(draft.x*100).toFixed(1)}%</output><input autoFocus id={`${id}-x`} type="range" min=".08" max=".92" step=".001" disabled={busy} value={draft.x} aria-valuetext={`${(draft.x*100).toFixed(1)}% across its bounded space`} onChange={e=>setDraft({...draft,x:clampFurnitureCoordinate(Number(e.target.value))})}/></label>
 <label htmlFor={`${id}-y`}>Nearer or farther <output>{(draft.y*100).toFixed(1)}%</output><input id={`${id}-y`} type="range" min=".08" max=".92" step=".001" disabled={busy} value={draft.y} aria-valuetext={`${(draft.y*100).toFixed(1)}% into its bounded space`} onChange={e=>setDraft({...draft,y:clampFurnitureCoordinate(Number(e.target.value))})}/></label><div><button type="submit" disabled={busy||conflict||!saveAvailable}>{busy?'Saving position…':'Save furniture position'}</button><button type="button" disabled={busy} onClick={close}>Cancel</button></div></form>}
 <p role="status" className="hsr-furniture-status">{message}</p>
 {draft&&!suspended&&handle&&scene.current?.querySelector('.hsr-stage')&&createPortal(<button type="button" ref={dragButton} className="hsr-furniture-handle" disabled={busy} style={{left:handle.x,top:handle.y}} aria-label={`Move ${definition?.label}; use arrow keys for precision`} onKeyDown={e=>{if(busy)return;const steps:Record<string,[number,number]>={ArrowLeft:[-.001,0],ArrowRight:[.001,0],ArrowUp:[0,-.001],ArrowDown:[0,.001]},step=steps[e.key];if(step){e.preventDefault();setDraft({...draft,x:clampFurnitureCoordinate(draft.x+step[0]*(e.shiftKey?10:1)),y:clampFurnitureCoordinate(draft.y+step[1]*(e.shiftKey?10:1))});}if(e.key==='Escape'){e.preventDefault();close();}}}><span aria-hidden="true">✥</span></button>,scene.current.querySelector('.hsr-stage')!)}
 </section>;
}
