import {useEffect,useRef,useState,type ReactNode} from 'react';
import type {Household} from '../core/types.ts';
import type {KitchenCommand} from '../kitchenCommand.ts';
import type {DesignReference} from './contracts.ts';
import {restoreBasis,sharedLifeRestoreKey,type SharedLifeRestorePreview,type SharedLifeRestoreTarget,type SharedLifeRestoreChange,type SharedLifeRestorePointOption} from './sharedLifeRestoreContracts.ts';
import {useSharedLifeRestore} from './useSharedLifeRestore.ts';
import './sharedLifeRestore.css';

export type {SharedLifeRestorePointOption} from './sharedLifeRestoreContracts.ts';
export interface SharedLifeRestoreSource {
 sharedLifeRestorePoints(signal?:AbortSignal):Promise<SharedLifeRestorePointOption[]>;
 sharedLifeRestorePreview(input:{pointId:string;selection:SharedLifeRestoreTarget[]},signal?:AbortSignal):Promise<SharedLifeRestorePreview>;
}
export type SharedLifeRestoreProps={household:Household;memberId:string;identity:string;theme:'classic'|'taylor'|'newfoundland';connected:boolean;source:()=>SharedLifeRestoreSource|null;onCommand:KitchenCommand;onClose:()=>void;onEditMemory:(id:string)=>void;renderDesign?:(reference:DesignReference)=>ReactNode};
const preserved=[['Today’s books and plans','Balances, transactions, budgets, Tasks, Calendar, Chapter and Ritual progress keep their current truth.'],['What happened since','Later objects, recorded room views, occasion occurrences, Studio design documents and their full histories remain.'],['Every choice to withdraw','Withdrawn notes, memories, guests and shared artifacts stay unavailable. Private letters, capsules and media access are never restored here.']];
function RestoreIllustration({theme}:Pick<SharedLifeRestoreProps,'theme'>){return <svg className="slr-illustration" viewBox="0 0 560 200" aria-hidden="true">
 {theme==='classic'?<><path d="M32 168V53L56 30h449l24 23v115Z" fill="#6c4230"/><path d="M54 51h455v105H54z" fill="#c89158"/><path d="M65 63h209v80H65zm222 0h209v80H287z" fill="#ead9af"/><path d="M280 50v109M78 82h127m-127 15h173m-173 15h148m56-30h131m-131 15h165m-165 15h143" stroke="#8b6544" strokeWidth="3"/><path d="M33 157h496v15H33z" fill="#402f29"/><circle cx="278" cy="156" r="9" fill="#d8b369"/></>:theme==='taylor'?<><path d="m41 46 222-16 17 131-222 16Z" fill="#efdce1" stroke="#835f67"/><path d="m295 28 215 23-13 133-215-23Z" fill="#fff2cd" stroke="#987948"/><path d="m69 26 66-4 2 28-66 4m302 7 65 6-3 26-65-6" fill="#b7d5c4" opacity=".85"/><path d="m76 83 148-10m-146 28 162-12m-159 30 123-9m55-22 150 16m-152 2 137 15m-139 4 151 16" stroke="#a37c79" strokeWidth="3"/><path d="M226 162q51 33 100-1" fill="none" stroke="#ac5f75" strokeDasharray="4 5"/><circle cx="254" cy="44" r="5" fill="#94753d"/></>:<><path d="M27 166 47 33h460l25 133Z" fill="#385761"/><path d="M48 156 63 48h430l18 108Z" fill="#b9c8be"/><path d="m80 72 145-8 20 70-156 8Zm220-8 148 8-10 70-160-8Z" fill="#f2e3bd" stroke="#837450"/><path d="m102 91 100-6m-98 25 117-7m93-18 100 8m-103 13 111 10" stroke="#8a8066" strokeWidth="3"/><path d="M36 171q54-18 108 0t108 0 108 0 108 0 63-2" fill="none" stroke="#a5c7cb" strokeWidth="6"/><circle cx="273" cy="47" r="14" fill="#d9b269"/><path d="m273 34 4 12-4 12-4-12Z" fill="#425d60"/></>}
 </svg>;}
function Change({value,renderDesign}: {value:SharedLifeRestoreChange;renderDesign?:SharedLifeRestoreProps['renderDesign']}){return <article className="slr-change"><h3>{value.label}</h3>{value.fields.map((field,i)=><div className="slr-field" key={i}><h4>{field.label}</h4><div><section><span>Today</span>{field.label==='Saved design revisions'&&value.designs&&renderDesign?<div className="slr-designs">{value.designs.before.length?value.designs.before.map(ref=><div key={`${ref.documentId}/${ref.pieceId}/${ref.revision}`}>{renderDesign(ref)}<small>Revision {ref.revision}</small></div>):<p>No saved piece</p>}</div>:<p>{field.before||'No words added'}</p>}</section><section><span>After restoring</span>{field.label==='Saved design revisions'&&value.designs&&renderDesign?<div className="slr-designs">{value.designs.after.length?value.designs.after.map(ref=><div key={`${ref.documentId}/${ref.pieceId}/${ref.revision}`}>{renderDesign(ref)}<small>Revision {ref.revision}</small></div>):<p>No saved piece</p>}</div>:<p>{field.after||'No words added'}</p>}</section></div></div>)}{value.aftercare.map(line=><p className="slr-aftercare" key={line}>{line}</p>)}</article>;}
export function SharedLifeRestore(props:SharedLifeRestoreProps){const scopeKey=JSON.stringify([props.identity,props.household.environment,props.household.householdId,props.memberId]);return <RestoreReview key={scopeKey} {...props}/>;}
function RestoreReview({household:h,memberId,identity,theme,connected,source,onCommand,onClose,onEditMemory,renderDesign}:SharedLifeRestoreProps){
 const commands=useSharedLifeRestore({environment:h.environment,householdId:h.householdId,memberId},identity,connected,onCommand);
 const [points,setPoints]=useState<SharedLifeRestorePointOption[]>([]),[pointId,setPointId]=useState(''),[selection,setSelection]=useState<SharedLifeRestoreTarget[]>([]),[preview,setPreview]=useState<SharedLifeRestorePreview|null>(null),[reviewId,setReviewId]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 const pair=h.members.filter(m=>m.active).map(m=>m.id).sort(),reviews=(h.hearthside?.restoreReviews??[]).filter(r=>r.audience.environment===h.environment&&r.audience.householdId===h.householdId&&JSON.stringify(r.audience.memberIds)===JSON.stringify(pair)),review=reviews.find(r=>r.id===reviewId),request=useRef(0);
 const actualPoint=review?.pointId??pointId,actualSelection=review?.selection??selection,selectionKey=JSON.stringify(actualSelection);
 useEffect(()=>{const abort=new AbortController(),client=source();if(!client||!connected){setPoints([]);return;}
  void client.sharedLifeRestorePoints(abort.signal).then(rows=>{if(!abort.signal.aborted&&source()===client)setPoints(rows);}).catch(()=>{if(!abort.signal.aborted)setError('Saved sync points are unavailable. Reconnect and try again.');});return()=>abort.abort();
 },[connected,source,refresh]);
 useEffect(()=>{const epoch=++request.current,abort=new AbortController(),client=source();setPreview(null);setError('');if(!actualPoint||!client||!connected||review&&review.state!=='pending'){setLoading(false);return;}
  setLoading(true);void client.sharedLifeRestorePreview({pointId:actualPoint,selection:actualSelection},abort.signal).then(value=>{if(!abort.signal.aborted&&request.current===epoch&&source()===client){setPreview(value);setLoading(false);}}).catch(error=>{if(!abort.signal.aborted&&request.current===epoch){setLoading(false);setError(error instanceof Error?error.message:'The restore review is unavailable.');}});return()=>abort.abort();
 },[actualPoint,selectionKey,h.hearthside,connected,source,refresh]);
 const exact=!!preview&&(!review||review.reviewDigest===preview.reviewDigest),mine=review?.approvals.includes(memberId),both=review?.approvals.length===2,material=!!preview&&preview.changes.length>0&&!preview.blocked.length;
 async function propose(){if(!preview||!material)return;const id='LIFE-RESTORE-'+crypto.randomUUID();if(await commands.submit({kind:'propose',id,basis:restoreBasis(preview)})){setReviewId(id);setRefresh(n=>n+1);}}
 function selectPoint(id:string){setReviewId('');setPointId(id);setSelection([]);setPreview(null);}
 function newReview(){if(review){setPointId(review.pointId);setSelection(review.selection);}setReviewId('');setRefresh(n=>n+1);}
 const readableError=error.includes('SOURCE_AUDIENCE')?'This saved point belongs to a different member pair. Its earlier content is not available here.':error.includes('MISSING')?'That saved point is no longer retained. Choose another point.':error.includes('NO_STORY')?'This point predates the shared home. It has no shared-life version to restore.':error.includes('CHANGED')?'The shared home or access changed while this review was loading. Refresh to see today’s choices.':error?'The saved point cannot be verified right now. Nothing has been restored.':'';
 return <section className="shared-life-restore" data-theme={theme} aria-labelledby="slr-title">
  <header className="slr-header"><div><p className="slr-eyebrow">A deliberate return, together</p><h2 id="slr-title" tabIndex={-1}>Bring back a little of before</h2><p>Choose earlier words and arrangements to bring into today’s home. Review every change, then each of you approves this exact version.</p></div><RestoreIllustration theme={theme}/><button className="slr-close" onClick={onClose}>Back to our room</button></header>
  <div className="slr-layout"><aside className="slr-drawer" aria-label="Choose a saved point"><h3>Our saved versions</h3><p>These are verified sync points kept by your shared home.</p><label>Saved point<select aria-label="Saved point" value={review?review.pointId:pointId} disabled={loading||!connected} onChange={e=>selectPoint(e.target.value)}><option value="">Choose a point</option>{points.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label>{!points.length&&<p>No retained sync points are available yet.</p>}<button onClick={()=>setRefresh(n=>n+1)} disabled={loading||!connected}>Refresh saved versions</button>
   {!!reviews.length&&<nav aria-label="Restore reviews"><h3>Choices we’re reviewing</h3>{[...reviews].reverse().map((r,i)=><button key={r.id} aria-current={reviewId===r.id?'page':undefined} onClick={()=>{setReviewId(r.id);setPreview(null);}}>Review {reviews.length-i} · {r.state==='pending'?`${r.approvals.length} of 2 approvals`:r.state==='applied'?'Restored':'Cancelled'}</button>)}</nav>}
  </aside><div className="slr-workbench">
   {loading&&<p role="status">Reading the saved version and checking today’s shared home…</p>}
   {readableError&&<p className="slr-notice" role="alert">{readableError}</p>}
   {!actualPoint&&!loading&&<div className="slr-empty"><h3>Keep what matters from an earlier version</h3><p>A note’s old wording, an intention’s name, the sofa where you liked it. You choose the parts; the rest of your life keeps moving.</p></div>}
   {review&&review.state!=='pending'&&<article className="slr-success" role="status"><h3>{review.state==='applied'?'Restored together':'Review cancelled'}</h3><p>{review.state==='applied'?`${review.selection.length} selected parts were restored as new revisions at accepted revision ${review.appliedRevision}. Your later objects, history and withdrawals remain current.`:'No restore was applied by this review.'}</p>{review.state==='applied'&&review.selection.some(t=>t.kind==='memory')&&<p>Restored memories still need a fresh Keep from each of you before returning to display.</p>}<button onClick={newReview} disabled={!commands.canStart}>Review another change from this point</button></article>}
   {preview&&<><div className="slr-point-caption"><p>Saved {new Date(preview.point.createdAt).toLocaleString()}</p><h3>{preview.point.label}</h3></div>
    {!review&&<fieldset className="slr-selection"><legend>Choose exactly what to review</legend>{preview.catalogue.filter(option=>option.status==='available'||option.status==='fresh-memory'||selection.some(t=>sharedLifeRestoreKey(t)===sharedLifeRestoreKey(option.target))).map(option=>{const key=sharedLifeRestoreKey(option.target),checked=selection.some(t=>sharedLifeRestoreKey(t)===key);return <div className="slr-option" key={key}><label><input type="checkbox" checked={checked} disabled={option.status==='unavailable'||option.status==='unchanged'||!commands.canStart||!checked&&selection.length>=100} onChange={e=>setSelection(e.target.checked?[...selection,option.target]:selection.filter(t=>sharedLifeRestoreKey(t)!==key))}/><span><strong>{option.label}</strong><small>{option.target.kind==='furniture'?`${option.target.room} · furniture`:option.target.kind}</small></span></label>{option.reason&&<p>{option.reason}</p>}{option.status==='fresh-memory'&&<button onClick={()=>onEditMemory(option.target.id)}>Open this memory’s editor</button>}</div>;})}{!preview.catalogue.some(o=>o.status==='available'||o.status==='fresh-memory')&&<p>These restorable fields already match, or their objects are no longer shared.</p>}</fieldset>}
    {!review&&preview.catalogue.some(o=>o.status==='unchanged'||o.status==='unavailable')&&<details className="slr-other-parts"><summary>{preview.catalogue.filter(o=>o.status==='unchanged'||o.status==='unavailable').length} parts already match or are unavailable</summary><ul>{preview.catalogue.filter(o=>o.status==='unchanged'||o.status==='unavailable').map(o=><li key={sharedLifeRestoreKey(o.target)}><strong>{o.label}</strong><span>{o.reason}</span></li>)}</ul></details>}
    {!!preview.blocked.length&&<aside className="slr-notice" aria-label="Selected changes requiring attention"><h3>Some selected material needs another choice</h3>{preview.blocked.map(option=><div key={sharedLifeRestoreKey(option.target)}><strong>{option.label}</strong><p>{option.reason}</p>{option.status==='fresh-memory'&&<button onClick={()=>onEditMemory(option.target.id)}>Review fresh media and Keep in the memory editor</button>}</div>)}<p>No partial restore will be applied. Change the selection or use the memory editor first.</p></aside>}
    {!!preview.changes.length&&<div className="slr-changes" aria-label="Exact restoration changes">{preview.changes.map(value=><Change key={sharedLifeRestoreKey(value.target)} value={value} renderDesign={renderDesign}/>)}</div>}
    {review?.state==='pending'&&!exact&&<aside className="slr-notice" role="alert"><h3>This review has changed</h3><p>Its earlier approvals cannot apply to today’s home. Start a fresh review of the changes shown here.</p><button onClick={newReview} disabled={!commands.canStart}>Start a fresh review</button></aside>}
    {review?.state==='applied'?<p className="slr-success" role="status">These changes were restored as new revisions. Your later objects, history and withdrawals remain current.</p>:review?.state==='cancelled'?<p role="status">This review was cancelled. No restore was applied.</p>:<div className="slr-approval"><h3>{review?'A choice from each of us':'Ready to review together'}</h3><p>Both approvals refer to the exact changes above. Changes to the saved point, affected objects or access require a new review.</p>{review?<><ol className="slr-members">{pair.map(id=><li key={id}><strong>{h.members.find(m=>m.id===id)?.name??'Household member'}</strong><span>{review.approvals.includes(id)?'Approved this exact review':'Has not approved yet'}</span></li>)}</ol><div className="slr-actions"><button disabled={!commands.canStart||!exact||!material||mine} onClick={()=>void commands.submit({kind:'approve',id:review.id,reviewDigest:review.reviewDigest})}>{mine?'I approved this review':'I approve these exact changes'}</button><button className="primary" disabled={!commands.canStart||!exact||!material||!both} onClick={()=>void commands.submit({kind:'apply',id:review.id,reviewDigest:review.reviewDigest})}>Restore these changes</button><button disabled={!commands.canStart} onClick={()=>void commands.submit({kind:'cancel',id:review.id,reviewDigest:review.reviewDigest})}>Cancel this review</button></div></>:<button className="primary" disabled={!commands.canStart||!material} onClick={()=>void propose()}>Invite us to review these changes</button>}</div>}
   </>}
   <section className="slr-preserved" aria-labelledby="slr-current-title"><h3 id="slr-current-title">What stays with today</h3>{preserved.map(([title,body])=><article key={title}><h4>{title}</h4><p>{body}</p></article>)}</section>
  </div></div>
  {(commands.message||commands.retry||!connected)&&<div className="slr-status" role="status"><p>{commands.message||'Reconnect to load, approve or apply an exact restore review.'}</p>{commands.retry&&<button disabled={commands.pending||!connected} onClick={()=>void commands.retryNow()}>Check and retry this same request</button>}</div>}
 </section>;
}
