import { useEffect, useRef, useState } from 'react';
import { readEntryLocal, writeEntryLocal, clearEntryLocal } from './workspaceDraft.ts';
import { useAppearance } from '../theme/ThemeProvider.tsx';
import { latestArtifacts, type ArtifactVersion, type WorkspaceProject } from '../workspace/contracts.ts';
import { workspaceExperienceDigest, workspaceExperienceKey, type WorkspaceExperienceContext, type WorkspaceExperienceScope } from './workspaceContext.ts';
import { experienceArtifactReviewDigest, assertArtifactPublicationReceipt, preparedExperienceArtifact, artifactPublication, type ArtifactPublicationReceipt, type ExperienceArtifactReview } from './workspacePublication.ts';
import { HearthsideResident } from './resident.tsx';
import { residentActivities, residentDraft } from './resident.ts';
import './workspaceSurface.css';

export type HearthsideWorkspaceBinding={scope:WorkspaceExperienceScope;experience:WorkspaceExperienceContext;onReturn:()=>void;
  onPublication?:(review:ExperienceArtifactReview,digest:string)=>Promise<ArtifactPublicationReceipt>;
  onWithdrawal?:(id:string)=>Promise<ArtifactPublicationReceipt>;
};
export type WorktableDraft={title:string;content:string;experienceDigest:string;artifactId:string;versionId:string|null};
type Draft=WorktableDraft;
const freshDraft=(title:string,digest:string):Draft=>({title:title.slice(0,180),content:'',experienceDigest:digest,artifactId:crypto.randomUUID(),versionId:null});
function restoredDraft(key:string,title:string,digest:string):Draft{const saved=readEntryLocal<Draft>(key);return saved&&typeof saved.title==='string'&&typeof saved.content==='string'&&saved.title.length<=180&&saved.content.length<=500000&&/^[a-f0-9]{64}$/.test(saved.experienceDigest)&&/^[a-zA-Z0-9_-]{1,100}$/.test(saved.artifactId)&&(saved.versionId===null||typeof saved.versionId==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(saved.versionId))?saved:freshDraft(title,digest);}
export type ExperienceWorktableProps={hearthside:HearthsideWorkspaceBinding;project?:WorkspaceProject|null;busy?:boolean;executionEnabled?:boolean;
  onSave?:(draft:Draft)=>Promise<{artifactId:string;versionId:string}|null>;
  onRefreshContext?:()=>Promise<boolean>;onApproveDisclosure?:()=>Promise<boolean>;
};
/** May be mounted even when hosted Workspace execution/service flags are off. Opening renders only local authored content. */
export function ExperienceWorktable(props:ExperienceWorktableProps){
  const key=workspaceExperienceKey(props.hearthside.scope,props.hearthside.experience.id,props.hearthside.experience.version===2?'personal':'household');
  return <ExperienceWorktableScope key={key} {...props} draftKey={'hearthside-worktable:'+key}/>;
}
function ExperienceWorktableScope({hearthside,project,busy=false,executionEnabled=false,onSave,onRefreshContext,onApproveDisclosure,draftKey}:ExperienceWorktableProps&{draftKey:string}){
  const {scene}=useAppearance(), context=hearthside.experience, digest=workspaceExperienceDigest(context);
  const [draft,setDraft]=useState<Draft>(()=>restoredDraft(draftKey,context.title,digest));
  const [notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[reviewProvider,setReviewProvider]=useState(false),[reviewed,setReviewed]=useState(false);
  const generation=useRef(0),urls=useRef(new Set<string>()), latestDigest=useRef(digest);latestDigest.current=digest;
  useEffect(()=>{const gen=++generation.current;return()=>{if(generation.current===gen)generation.current++;for(const url of urls.current)URL.revokeObjectURL(url);urls.current.clear();};},[]);
  useEffect(()=>{setReviewed(false);setReviewProvider(false);},[digest,project?.experience?.digest]);
  useEffect(()=>{if(!writeEntryLocal(draftKey,draft))setNotice('Private device storage is unavailable. Download your writing before leaving.');},[draft,draftKey]);
  const changed=draft.experienceDigest!==digest;
  const currentSource=project?latestArtifacts(project).find(a=>a.artifactId===draft.artifactId):undefined;
  const sourceChanged=!!currentSource&&!!draft.versionId&&currentSource.id!==draft.versionId;
  const sourceDeleted=!!project?.deletedArtifactIds?.includes(draft.artifactId);
  const projectChanged=!!project?.experience && project.experience.digest!==digest;
  async function save(){if(!onSave || saving || !draft.content.trim() || changed||sourceChanged||sourceDeleted)return;const gen=generation.current, submitted={...draft};setSaving(true);try{const saved=await onSave(submitted);if(saved&&gen===generation.current){setDraft(current=>current.artifactId===submitted.artifactId?{...current,...saved}:current);setNotice('Saved privately in this intention’s workspace. You can return to the same accepted work on another signed-in device.');}}catch{if(gen===generation.current)setNotice('The save needs checking. Your writing is still here.');}finally{if(gen===generation.current)setSaving(false);}}
  function download(){const url=URL.createObjectURL(new Blob([draft.content],{type:'text/markdown;charset=utf-8'}));urls.current.add(url);const a=document.createElement('a');a.href=url;a.download=(draft.title.replace(/[^a-zA-Z0-9 _-]/g,'').slice(0,120)||'A little thought')+'.md';a.click();queueMicrotask(()=>{URL.revokeObjectURL(url);urls.current.delete(url);});}
  async function approve(){if(!reviewed || !onApproveDisclosure)return;const gen=generation.current, exact=digest;setSaving(true);try{if(await onApproveDisclosure() && gen===generation.current && latestDigest.current===exact){setReviewProvider(false);setNotice('This exact intention context is approved for activated Workspace runs. Sending a message is a separate action.');}}catch{if(gen===generation.current)setNotice('The context review could not be saved. Review it again after reconnecting.');}finally{if(gen===generation.current)setSaving(false);}}
  return <section className={`hs-worktable hs-worktable--${scene.theme}`} aria-label="Selected intention worktable"><div className="hs-worktable-heading"><div><p className="hs-worktable-eyebrow">Brought from the Boathouse · version {context.revision}</p><h2>{context.title}</h2><p>{context.intention || 'There is room to discover what this means.'}</p></div><button onClick={hearthside.onReturn}>Return to this intention</button></div>
    <HearthsideResident experience={context}/><div className="hs-worktable-activities">{residentActivities.map(activity=><button key={activity.id} disabled={!!draft.content.trim()} onClick={()=>setDraft({...freshDraft(context.title,digest),...residentDraft(activity.id,context.title)})}><strong>{activity.title}</strong><span>{activity.description}</span></button>)}</div>
    <div className="hs-worktable-paper"><p className="hs-worktable-eyebrow">Your private working notes</p><label>Working title<input value={draft.title} maxLength={180} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>A page for this intention<textarea aria-label="A page for this intention" value={draft.content} maxLength={500000} rows={7} onChange={e=>setDraft({...draft,content:e.target.value})} placeholder="Put a thought here. It can stay small."/></label><p>Drafts stay in your private device storage. Saving to Workspace keeps an accepted version across your signed-in devices. Sharing is a separate review.</p>
      {changed&&<div role="alert"><p>The intention changed since you began this draft. Your words are preserved. Review the current intention above before continuing.</p><button onClick={()=>setDraft({...draft,experienceDigest:digest})}>Keep my draft with this version</button></div>}
      {sourceChanged&&currentSource&&<section className="hs-worktable-review" aria-label="Review newer private source"><h3>This private source has a newer version</h3><p>Your draft above is preserved. Compare the currently saved source before using it as the base of another version.</p><pre style={{whiteSpace:'pre-wrap'}}>{currentSource.content}</pre><button onClick={()=>setDraft({...draft,versionId:currentSource.id})}>Use this reviewed source version as my base</button></section>}
      {sourceDeleted&&<div role="status"><p>This private source was deleted. Your local writing is still here.</p><button onClick={()=>setDraft({...draft,artifactId:crypto.randomUUID(),versionId:null})}>Keep my writing as a new private source</button></div>}
      <div className="hs-worktable-actions"><button disabled={!draft.content.trim()} onClick={download}>Download my writing</button>{onSave&&<button disabled={busy||saving||!draft.content.trim()||!draft.title.trim()||changed||projectChanged||sourceChanged||sourceDeleted} onClick={()=>void save()}>Save privately to Workspace</button>}<button disabled={!draft.content.trim()||saving} onClick={()=>{clearEntryLocal(draftKey);setDraft(freshDraft(context.title,digest));setNotice('The local draft was cleared. Saved work and shared copies remain available.');}}>Clear this local draft</button></div></div>
    {projectChanged&&<section className="hs-worktable-review" aria-label="Review refreshed intention"><h3>The {context.version===2?'private':'shared'} intention has changed</h3><p>The Workspace context is version {project?.experience?.context.revision}. Review version {context.revision} above to refresh it. Existing working files stay private, and provider permission resets.</p><button disabled={busy||saving} onClick={()=>void onRefreshContext?.()}>Use this reviewed intention version</button></section>}
    {project?.experience&&!projectChanged&&<details className="hs-worktable-disclosure" open={reviewProvider} onToggle={e=>setReviewProvider(e.currentTarget.open)}><summary>What an activated Hercules run can use</summary><p>Opening this worktable sends nothing to a model. If you approve and send a message, Workspace can send this exact selected intention, the instructions and files you deliberately place in this private project, and its tool results to Gemini. Personal books, unrelated Household records and another person’s private sources are excluded.</p><pre>{JSON.stringify(context,null,2)}</pre><p>Only intentionally published shared copies can be added through a separate content review. Public research and external actions retain their own approvals.</p>{project.experience.providerApprovalDigest===digest?<p>This version has your disclosure approval.</p>:<><label className="hs-worktable-checkbox"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed this context and the provider disclosure.</label><button disabled={busy||saving||!reviewed||!executionEnabled} onClick={()=>void approve()}>Approve this context for activated runs</button>{!executionEnabled&&<p>Model execution is not activated. Your writing and local activities remain available.</p>}</>}</details>}
    {notice&&<p role="status">{notice}</p>}
  </section>;
}
export function ExperienceArtifactSharing({hearthside,projectId,artifact,onClose}:{hearthside:HearthsideWorkspaceBinding;projectId:string;artifact:ArtifactVersion;onClose:()=>void}){
  const key=workspaceExperienceKey(hearthside.scope,hearthside.experience.id,hearthside.experience.version===2?'personal':'household')+':publication';
  return <ExperienceArtifactSharingScope key={key} hearthside={hearthside} projectId={projectId} artifact={artifact} onClose={onClose} storageKey={key}/>;
}
function ExperienceArtifactSharingScope({hearthside,projectId,artifact,onClose,storageKey}:{hearthside:HearthsideWorkspaceBinding;projectId:string;artifact:ArtifactVersion;onClose:()=>void;storageKey:string}){
  const persisted=useRef(readEntryLocal<{review:ExperienceArtifactReview;pending:boolean}>(storageKey));
  const [review,setReview]=useState<ExperienceArtifactReview>(()=>persisted.current?.review??{version:1,id:crypto.randomUUID(),projectId,artifactVersionId:artifact.id,experienceId:hearthside.experience.id,experienceRevision:hearthside.experience.revision,title:artifact.title,format:artifact.format,content:artifact.content});
  const [pending,setPending]=useState(persisted.current?.pending??false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const generation=useRef(0);
  useEffect(()=>{const gen=++generation.current;return()=>{if(gen===generation.current)generation.current++;};},[]);
  const changed=review.experienceRevision!==hearthside.experience.revision||review.artifactVersionId!==artifact.id;
  useEffect(()=>{writeEntryLocal(storageKey,{review,pending});},[storageKey,review,pending]);
  async function publish(){if(!hearthside.onPublication||busy)return;let digest:string;try{digest=experienceArtifactReviewDigest(review);}catch{setNotice('A title and the full reviewed content are required.');return;}if(!writeEntryLocal(storageKey,{review,pending:true})){setNotice('Allow private draft storage before sharing so this receipt can be recovered.');return;}setPending(true);setBusy(true);const gen=generation.current;try{const expected=artifactPublication(preparedExperienceArtifact(review,hearthside.scope.memberId));const receipt=assertArtifactPublicationReceipt(await hearthside.onPublication(review,digest),expected);if(gen!==generation.current)return;clearEntryLocal(storageKey);setNotice('Shared this exact copy with the intention. Receipt: '+receipt.id);setPending(false);onClose();}catch(error){if(gen===generation.current){if(error instanceof Error&&/^(ARTIFACT_CHANGED|EXPERIENCE_CONTEXT_CHANGED|DISCLOSURE_REVIEW_CHANGED|ARTIFACT_SOURCE_FORBIDDEN|ARTIFACT_WITHDRAWN)$/.test(error.message)){setPending(false);setNotice('This review changed. Your text is preserved; close this review and compare the current source before sharing again.');}else setNotice('The shared copy needs checking. Retry this exact review to recover its original receipt.');}}finally{if(gen===generation.current)setBusy(false);}}
  return <section className="hs-worktable-review" aria-label="Review intention artifact"><h2>Place this exact copy with {hearthside.experience.title}</h2><p>Both household members can read the entire copy below. Private conversation, source links and earlier versions stay in your private Workspace. Later source edits or deletion do not change this copy; withdraw the shared copy separately.</p><label>Shared title<input disabled={pending} maxLength={180} value={review.title} onChange={e=>setReview({...review,id:crypto.randomUUID(),title:e.target.value})}/></label><label>Full content to share<textarea disabled={pending} value={review.content} maxLength={500000} rows={12} onChange={e=>setReview({...review,id:crypto.randomUUID(),content:e.target.value})}/></label>{changed&&!pending&&<p role="alert">The source or intention changed. Close this review to compare the latest version.</p>}<button disabled={busy||!hearthside.onPublication||changed&&!pending} onClick={()=>void publish()}>{pending?'Check original publication':'Share this reviewed copy'}</button>{!pending&&<button onClick={()=>{clearEntryLocal(storageKey);onClose();}}>Close review</button>}{notice&&<p role="status">{notice}</p>}</section>;
}
