import { describe, it, expect } from 'vitest';
import { acceptReviewedAccountHistory, approveAccountHistoryReview, prepareAccountHistoryReview, acceptedAccountOpeningCoverage, economicAccountBalanceAsOf, type AccountHistoryInput } from '../src/core/accountHistory.ts';
import { catalogHousehold, postOpeningBalances, postEntry, reversePostedMoney, compileHousehold, booksEquation, trialBalance, splitForSync, assembleHousehold, undoLedgerConfirm, acceptHouseholdWrite } from '../src/core/index.ts';
import { captureCommand } from '../src/ledgerSync/capture.ts';
const member='MEM-001';
function base(){const h=catalogHousehold();h.transactions=[];h.commandReceipts=[];h.kitchen.books.closedMonths=[];return h;}
function input(accountId='ACC-CHEQUING',balance=100_00):AccountHistoryInput{return {createdBy:member,visibility:'household',accounts:[{accountId,openingDate:'2026-08-31',openingBalanceCents:balance,closingDate:'2026-09-30',closingBalanceCents:balance}],rows:[]};}
function accept(h=base(),i=input(),id='history-1'){const review=prepareAccountHistoryReview(h,i);return acceptReviewedAccountHistory(h,{createdBy:member,review,confirmationId:id});}
function backfill(){const h=postOpeningBalances(base(),{createdBy:member,confirmationId:'legacy',asOfDate:'2026-09-01',lines:[{accountId:'ACC-CHEQUING',amountCents:1000_00},{accountId:'ACC-VISA',amountCents:50_00}]}).household;const i=input('ACC-CHEQUING',800_00);i.accounts[0]!.openingDate='2026-07-31';i.accounts[0]!.closingBalanceCents=1000_00;i.rows=[{sourceIdentity:'FITID-1',sourceHash:'source',accountId:'ACC-CHEQUING',date:'2026-08-01',amountCents:200_00,type:'income',subcategoryId:'SUB-INCOME-WAGES',note:'Earlier deposit',decision:'post'}];return {h,i};}
function approvals(h:ReturnType<typeof base>,r:ReturnType<typeof prepareAccountHistoryReview>){for(const m of h.members.filter(m=>m.active))h=approveAccountHistoryReview(h,{createdBy:m.id,review:r}).household;return h;}
describe('reviewed account history',()=>{
 it('accepts explicit zero coverage without a zero journal entry',()=>{const r=accept(base(),input('ACC-CHEQUING',0));expect(r.household.transactions).toHaveLength(0);expect(acceptedAccountOpeningCoverage(r.household,{visibility:'household'}).checkpoints).toEqual([expect.objectContaining({signedBalanceCents:0,transactionId:null})]);});
 it.each([['ACC-CHEQUING',-12500],['ACC-VISA',7500]])('supports the opposite economic side for %s', (id,amount)=>{const r=accept(base(),input(id,amount));expect(economicAccountBalanceAsOf(r.household,id,'2026-09-30')).toBe(amount);expect(booksEquation(compileHousehold(r.household)).holds).toBe(true);expect(trialBalance(compileHousehold(r.household)).inBalance).toBe(true);});
 it('retains the first-money restriction of the ordinary opening command',()=>{const r=accept();expect(()=>postOpeningBalances(r.household,{createdBy:member,confirmationId:'ordinary',asOfDate:'2026-08-31',lines:[{accountId:'ACC-VISA',amountCents:50}]})).toThrow(/already posted/);});
 it('appends original-date reversal and preserves unrelated legacy batch accounts and the old checkpoint',()=>{const {h,i}=backfill();const review=prepareAccountHistoryReview(h,i);expect(()=>acceptReviewedAccountHistory(h,{createdBy:member,review,confirmationId:'rebase'})).toThrow(/Both members/);const approved=approvals(h,review);const r=acceptReviewedAccountHistory(approved,{createdBy:member,review,confirmationId:'rebase'});expect(r.household.transactions.find(t=>t.reversalOfId)?.date).toBe('2026-09-01');expect(r.household.transactions.filter(t=>t.accountId==='ACC-VISA')).toHaveLength(1);expect(economicAccountBalanceAsOf(r.household,'ACC-CHEQUING','2026-09-01')).toBe(1000_00);expect(booksEquation(compileHousehold(r.household)).holds).toBe(true);expect(()=>reversePostedMoney(r.household,r.postedIds[0]!,{createdBy:member})).toThrow(/atomic history/);expect(()=>undoLedgerConfirm(r.household,r.undo)).toThrow(/atomic history/);});
 it('blocks unexplained statement differences and incorrect old checkpoints',()=>{const i=input();i.accounts[0]!.closingBalanceCents++;expect(()=>prepareAccountHistoryReview(base(),i)).toThrow(/reconcile/);const b=backfill();b.i.accounts[0]!.openingBalanceCents++;expect(()=>prepareAccountHistoryReview(b.h,b.i)).toThrow(/old opening checkpoint/);});
 it('blocks each affected closed period including the original opening date',()=>{const {h,i}=backfill();h.kitchen.books.closedMonths=[{monthKey:'2026-09',closedAt:'2026-10-01T00:00:00.000Z',closedBy:member} as never];expect(()=>prepareAccountHistoryReview(h,i)).toThrow(/closed/);});
 it('detects concurrent activity before accepting a reviewed history',()=>{const {h,i}=backfill(),review=prepareAccountHistoryReview(h,i);const changed=postEntry(h,{date:'2026-09-20',type:'expense',amount:3,accountId:'ACC-CHEQUING',subcategoryId:'SUB-FOOD-GROCERIES',createdBy:member,note:'New',confirmDuplicate:true}).household;expect(()=>acceptReviewedAccountHistory(changed,{createdBy:member,review,confirmationId:'changed'})).toThrow();});
 it('retries the same Confirm exactly once and rejects reused identity for different review',()=>{const h=base(),review=prepareAccountHistoryReview(h,input());const r=acceptReviewedAccountHistory(h,{createdBy:member,review,confirmationId:'same'});expect(acceptReviewedAccountHistory(r.household,{createdBy:member,review,confirmationId:'same'}).household.transactions).toHaveLength(1);expect(()=>acceptReviewedAccountHistory(r.household,{createdBy:member,review:{...review,digest:'wrong'},confirmationId:'same'})).toThrow(/another history/);});
 it('authoritatively rejects repeated accepted source identities under a new Confirm',()=>{const {h,i}=backfill(),review=prepareAccountHistoryReview(h,i);const r=acceptReviewedAccountHistory(approvals(h,review),{createdBy:member,review,confirmationId:'first'});expect(()=>prepareAccountHistoryReview(r.household,i)).toThrow(/already accepted/);});
 it('keeps own Personal checkpoints and approvals out of Shared and the partner replica',()=>{const h=base();const a=h.accounts.find(a=>a.id==='ACC-CHEQUING')!;a.scope='personal';a.ownerMemberId=member;const i={...input(),visibility:'personal' as const};const r=accept(h,i);const split=splitForSync(r.household,member),partner=splitForSync(r.household,'MEM-002');expect(split.shared.accountOpeningCheckpoints).toEqual([]);expect(split.personal.accountOpeningCheckpoints).toHaveLength(1);expect(partner.personal.accountOpeningCheckpoints).toEqual([]);expect(assembleHousehold(split.shared,split.personal).accountOpeningCheckpoints).toHaveLength(1);expect(()=>prepareAccountHistoryReview(h,{...i,createdBy:'MEM-002'})).toThrow(/outside/);});
 it('rejects a transfer without the second account and prevents two posted copies',()=>{const i=input();i.rows=[{sourceIdentity:'x',sourceHash:'h',date:'2026-09-01',accountId:'ACC-CHEQUING',toAccountId:'ACC-VISA',amountCents:100,type:'transfer',note:'Payment',decision:'post'}];expect(()=>prepareAccountHistoryReview(base(),i)).toThrow(/both tracked/);i.accounts.push({...input('ACC-VISA',0).accounts[0]!});i.rows.push({...i.rows[0]!,sourceIdentity:'y'});expect(()=>prepareAccountHistoryReview(base(),i)).toThrow(/canonical transfer/);});
 it('accepts one canonical transfer and reconciles both accounts',()=>{const i=input();i.accounts[0]!.closingBalanceCents=9000;i.accounts.push({...input('ACC-VISA',-3000).accounts[0]!,closingBalanceCents:-2000});i.rows=[{sourceIdentity:'x',sourceHash:'h',date:'2026-09-01',accountId:'ACC-CHEQUING',toAccountId:'ACC-VISA',amountCents:1000,type:'transfer',note:'Payment',decision:'post'}];const r=accept(base(),i);expect(r.household.transactions.filter(t=>t.type==='transfer')).toHaveLength(2);expect(economicAccountBalanceAsOf(r.household,'ACC-VISA','2026-09-30')).toBe(-2000);});
 it('uses the normal acceptance boundary and refuses forged checkpoint writes',async()=>{const h=base(),r=accept(h);let persisted=false;const adapters={persist:async()=>{persisted=true;},ingest:async()=>({ok:true}),validateCandidate:async()=>({ok:true})};const valid=await acceptHouseholdWrite({previous:h,candidate:r.household,commandKind:'acceptReviewedAccountHistory',confirmationId:'history-1',actingMemberId:member,postedIds:r.postedIds,adapters});expect(valid.ok,valid.userMessage??'').toBe(true);expect(persisted).toBe(true);const fake=captureCommand('postEntry',(before)=>({...r,household:{...before,accountOpeningCheckpoints:r.household.accountOpeningCheckpoints}}))(h);const bad=await acceptHouseholdWrite({previous:h,candidate:fake.household,commandKind:'postEntry',actingMemberId:member,postedIds:[],adapters});expect(bad.ok).toBe(false);});
});

it('shares exact pending review across isolated principals and records each own approval through authority',async()=>{
 const {submitAccountHistoryReview,pendingAccountHistoryReviews}=await import('../src/core/accountHistory.ts');
 const {capturedIntent,clearCapturedIntent}=await import('../src/ledgerSync/capture.ts');
 const {commandFromCapture}=await import('../src/ledgerSync/protocol.ts');
 const {prepareCommand}=await import('../src/ledgerSync/authority.ts');
 const {h,i}=backfill();clearCapturedIntent(h);const review=prepareAccountHistoryReview(h,i),one=splitForSync(h,member),two=splitForSync(h,'MEM-002');
 let state={sequence:h.revision,shared:one.shared,personal:new Map([[member,one.personal],['MEM-002',two.personal]])};
 const scope={environment:h.environment,householdId:h.householdId,memberId:member,subject:'first',role:'owner' as const,expires:Date.now()+60000,aclEpoch:1};
 async function execute(result:ReturnType<typeof acceptReviewedAccountHistory>,actor:string){const actorScope={...scope,memberId:actor};const cmd=await commandFromCapture(capturedIntent(result.household)!,actorScope,crypto.randomUUID());const accepted=await prepareCommand(state,cmd,actorScope,()=>{});state={sequence:accepted.receipt.sequence,shared:accepted.shared,personal:new Map([...state.personal,[actor,accepted.personal]])};return assembleHousehold(state.shared,state.personal.get(actor));}
 await execute(submitAccountHistoryReview(h,{createdBy:member,review}),member);
 let peer=assembleHousehold(state.shared,state.personal.get('MEM-002'));expect(pendingAccountHistoryReviews(peer,{visibility:'household'})[0]?.review).toEqual(review);
 peer=await execute(approveAccountHistoryReview(peer,{createdBy:'MEM-002',review}),'MEM-002');
 let author=assembleHousehold(state.shared,state.personal.get(member));author=await execute(approveAccountHistoryReview(author,{createdBy:member,review}),member);
 const accepted=await execute(acceptReviewedAccountHistory(author,{createdBy:member,review,confirmationId:'preview-confirm'}),member);
 expect(economicAccountBalanceAsOf(accepted,'ACC-CHEQUING','2026-09-01')).toBe(100000);expect(pendingAccountHistoryReviews(accepted,{visibility:'household'})).toEqual([]);
});

it('persists the signed rebase journal through real PGlite constraints',async()=>{
 const {openMemoryBooks,ingestBooks}=await import('../src/ledger/engine.ts');
 const {h,i}=backfill(),review=prepareAccountHistoryReview(h,i),r=acceptReviewedAccountHistory(approvals(h,review),{createdBy:member,review,confirmationId:'sql-rebase'});
 const db=await openMemoryBooks();try{expect((await ingestBooks(db,r.household,compileHousehold(r.household))).ok).toBe(true);expect((await db.query('SELECT * FROM v_unbalanced_entries')).rows).toEqual([]);const row=await db.query<{debit_cents:number;credit_cents:number}>('SELECT debit_cents,credit_cents FROM v_trial_balance WHERE account_id = $1',['ACC-CHEQUING']);expect(Number(row.rows[0]!.debit_cents)-Number(row.rows[0]!.credit_cents)).toBe(100000);}finally{await db.close();}
},30000);

it('refuses old clients after checkpoint adoption while ordinary new-client entries still work',async()=>{
 const {capturedIntent,clearCapturedIntent}=await import('../src/ledgerSync/capture.ts');const {commandFromCapture}=await import('../src/ledgerSync/protocol.ts');const {prepareCommand}=await import('../src/ledgerSync/authority.ts');
 const h=accept().household;clearCapturedIntent(h);const split=splitForSync(h,member),scope={environment:h.environment,householdId:h.householdId,memberId:member,subject:'first',role:'owner' as const,expires:Date.now()+60000,aclEpoch:1};
 const state={sequence:h.revision,shared:split.shared,personal:new Map([[member,split.personal]])};
 const posted=postEntry(h,{date:'2026-09-20',type:'expense',amount:3,accountId:'ACC-CHEQUING',subcategoryId:'SUB-FOOD-GROCERIES',createdBy:member,note:'Ordinary current purchase',confirmDuplicate:true});
 const cmd=await commandFromCapture(capturedIntent(posted.household)!,scope,crypto.randomUUID());await expect(prepareCommand(state,{...cmd,accountHistoryVersion:undefined},scope,()=>{})).rejects.toThrow(/CLIENT_RELOAD_REQUIRED/);expect((await prepareCommand(state,cmd,scope,()=>{})).shared.transactions).toHaveLength(2);
});
it('preserves explicit zero lineage against ordinary legacy opening and tampered reload',async()=>{
 const {assertAcceptableBooks}=await import('../src/core/booksValidation.ts');const h=accept(base(),input('ACC-CHEQUING',0)).household;
 expect(()=>postOpeningBalances(h,{createdBy:member,confirmationId:'new',asOfDate:'2026-08-31',lines:[{accountId:'ACC-CHEQUING',amountCents:1}]})).toThrow(/already posted/);
 h.accountOpeningCheckpoints![0]!.signedBalanceCents=1;expect(()=>assertAcceptableBooks(h)).toThrow(/explicit zero/);
});
it('reconciles every intermediate checkpoint and retains distinct equal-amount source rows',()=>{
 const i=input('ACC-CHEQUING',0);i.accounts[0]!.closingBalanceCents=2000;i.accounts[0]!.checkpoints=[{date:'2026-09-10',balanceCents:1000}];
 i.rows=[1,2].map(n=>({sourceIdentity:`FITID-${n}`,sourceHash:'file',date:n===1?'2026-09-10':'2026-09-20',accountId:'ACC-CHEQUING',amountCents:1000,type:'income' as const,subcategoryId:'SUB-INCOME-WAGES',note:'Deposit',decision:'post' as const}));
 expect(accept(base(),i).household.transactions.filter(t=>t.source==='import')).toHaveLength(2);i.accounts[0]!.checkpoints![0]!.balanceCents=999;expect(()=>prepareAccountHistoryReview(base(),i)).toThrow(/intermediate/);
});

it('never includes a partner Personal review or unconfirmed history in model context',async()=>{
 const {householdForView,householdForAiDisclosure}=await import('../src/core/visibility.ts');const {submitAccountHistoryReview}=await import('../src/core/accountHistory.ts');
 const h=base();h.accounts.find(a=>a.id==='ACC-CHEQUING')!.scope='personal';h.accounts.find(a=>a.id==='ACC-CHEQUING')!.ownerMemberId=member;const i={...input(),visibility:'personal' as const};const r=submitAccountHistoryReview(h,{createdBy:member,review:prepareAccountHistoryReview(h,i)}).household;
 expect(householdForView(r,'MEM-002','personal').accountHistoryReviews).toEqual([]);expect(householdForView(r,member,'household').accountHistoryReviews).toEqual([]);expect(householdForAiDisclosure(r,member,{view:'personal'}).accountHistoryReviews).toEqual([]);
});
