// @vitest-environment jsdom
import {act,createElement} from 'react';
import {createRoot} from 'react-dom/client';
import {describe,it,expect,vi} from 'vitest';
import {CalculatorBody} from '../src/widgets/CalculatorPad.tsx';
import {catalogHousehold} from '../src/core/index.ts';
import type {DeskForm,DeskMode} from '../src/widgets/deskTypes.ts';
vi.mock('../src/widgets/useFurniture.ts',()=>({useFurniture:()=>({current:null})}));
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
async function mount(){const h=catalogHousehold(),host=document.createElement('div'),root=createRoot(host);document.body.append(host);let form={amount:'12.34',accountId:'A0',subcategoryId:'C0',memberId:'MEM-001',note:'Coffee'} as DeskForm;const onPost=vi.fn(),setForm=vi.fn((next:DeskForm)=>{form=next;});const props={scopeKey:'development:house:member:shared',form,setForm,mode:'expense' as DeskMode,household:h,accounts:Array.from({length:9},(_,i)=>({...h.accounts[0]!,id:`A${i}`,name:`Account ${i}`,active:true})),categories:Array.from({length:12},(_,i)=>({...h.categories[0]!,id:`C${i}`,name:`Category ${i}`,active:true})),postLabel:'Review',error:'',busy:false,onPost,onMore:()=>{},onMilk:()=>{},onCoffee:()=>{}};const render=()=>act(async()=>{props.form=form;root.render(createElement(CalculatorBody,props));});await render();const button=(name:string)=>[...host.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent===name);return {props,host,setForm,onPost,render,button,form:()=>form,click:async(name:string)=>{await act(async()=>button(name)!.click());await render();},close:async()=>{await act(async()=>root.unmount());host.remove();}};}
describe('Calculator pad full eligible choice list',()=>{
 it('reaches tail IDs without losing amount, preserves selected tail visibility, and never posts from disclosure or choice',async()=>{const m=await mount();try{expect(m.button('Account 8')).toBeUndefined();expect(m.button('Category 11')).toBeUndefined();await m.click('More accounts');await m.click('More categories');expect(m.setForm).not.toHaveBeenCalled();const initial=m.form();await m.click('Account 8');expect(m.form()).toEqual({...initial,accountId:'A8'});await m.click('Category 11');expect(m.form()).toEqual({...initial,accountId:'A8',subcategoryId:'C11'});await m.click('Fewer accounts');await m.click('Fewer categories');expect(m.button('Account 8')!.getAttribute('aria-pressed')).toBe('true');expect(m.button('Category 11')!.getAttribute('aria-pressed')).toBe('true');expect(m.button('Account 7')).toBeUndefined();expect(m.button('Category 10')).toBeUndefined();expect(m.onPost).not.toHaveBeenCalled();}finally{await m.close();}});
 it('removes stale labels synchronously, resets disclosures by scope/mode, and preserves disabled and transfer paths',async()=>{const m=await mount();try{await m.click('More accounts');await m.click('Account 8');m.props.accounts=m.props.accounts.map(a=>a.id==='A8'?{...a,active:false}:a);m.props.categories=m.props.categories.filter(c=>c.id!=='C0');await m.render();expect(m.button('Account 8')).toBeUndefined();expect(m.host.textContent).toContain('Choose an account.');expect(m.host.textContent).toContain('Choose a category.');expect(m.form().accountId).toBe('A8');m.props.scopeKey='development:house:member:personal';await m.render();expect(m.button('More accounts')!.getAttribute('aria-expanded')).toBe('false');m.props.busy=true;await m.render();expect(m.button('Account 0')!.disabled).toBe(true);m.props.mode='transfer';await m.render();expect(m.host.querySelector('.calculator-choices')).toBeNull();expect(m.host.textContent).toContain('Transfer. Not spend.');expect(m.form().amount).toBe('12.34');expect(m.onPost).not.toHaveBeenCalled();}finally{await m.close();}});
});
