// @vitest-environment jsdom
import {act,createElement} from 'react';import {createRoot} from 'react-dom/client';import {describe,it,expect} from 'vitest';import {ClaimsBody} from '../src/widgets/ClaimsTray.tsx';import {AppointmentsPage} from '../src/Appointments.tsx';import {catalogHousehold,postVisit} from '../src/core/index.ts';
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
function fixture(){let h=catalogHousehold();for(const [note,amount] of [['First visit',100],['Second visit',200]] as const)h=postVisit(h,{date:'2026-09-01',amount,note,accountId:'ACC-VISA',subcategoryId:'SUB-HEALTH-DENTAL',expectedRecovery:amount/2,confirmDuplicate:true,createdBy:'MEM-001'}).household;return h;}
function pointer(el:Element,type:string,x=100){const e=new Event(type,{bubbles:true});Object.assign(e,{pointerId:1,isPrimary:true,button:0,clientX:x,clientY:100});el.dispatchEvent(e);}
describe('Attached claim rows',()=>{
 it('names every displayed claim and reveals its exact review callback without any command',async()=>{Object.assign(HTMLElement.prototype,{setPointerCapture(){},releasePointerCapture(){},hasPointerCapture(){return false;}});const host=document.createElement('div');document.body.append(host);const root=createRoot(host),h=fixture(),calls:string[]=[];try{await act(async()=>root.render(createElement(ClaimsBody,{household:h,memberId:'MEM-001',view:'household',today:'2026-09-08',busy:false,onAskSettle:id=>calls.push(id),onCalendar:()=>{}})));const rows=host.querySelectorAll('.row-reveal');expect(rows.length).toBe(2);const row=rows[0]!,handle=row.querySelector('button')!;await act(async()=>{pointer(handle,'pointerdown');pointer(handle,'pointermove',150);});expect(calls).toEqual([]);expect(row.querySelector('[inert]')).not.toBeNull();await act(async()=>pointer(handle,'pointerup',150));const review=row.querySelector<HTMLButtonElement>('[aria-label="Review transfer for Second visit"]')!;expect(review).not.toBeNull();await act(async()=>review.click());expect(calls).toEqual([h.claims[1]!.id]);expect(h.transactions.filter(t=>t.type==='transfer')).toEqual([]);}finally{await act(async()=>root.unmount());host.remove();}});
 it('hosts the same attached action in the existing phone Owed list',async()=>{const host=document.createElement('div');document.body.append(host);const root=createRoot(host),h=fixture(),calls:string[]=[];try{await act(async()=>root.render(createElement(AppointmentsPage,{household:h,memberId:'MEM-001',view:'household',today:'2026-09-08',busy:false,onCommand:()=>{throw Error('Gesture wrote');},onAskVisit:()=>{},onAskSettle:id=>calls.push(id),onAskWriteOff:()=>{},onAskStartJar:()=>{}})));const button=(name:string)=>[...host.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent?.trim()===name)!;await act(async()=>button('Owed').click());expect(host.querySelectorAll('.row-reveal')).toHaveLength(2);const row=host.querySelector('.row-reveal')!,handle=row.querySelector<HTMLButtonElement>('.row-reveal-handle')!;await act(async()=>handle.click());const review=row.querySelector<HTMLButtonElement>('[aria-label^="Review transfer for"]')!;await act(async()=>review.click());expect(calls).toHaveLength(1);expect(h.transactions.filter(t=>t.type==='transfer')).toEqual([]);}finally{await act(async()=>root.unmount());host.remove();}});
});
