import {describe,it,expect} from 'vitest';
import {catalogHousehold,addAppointment,postVisit,settleClaim,reversePostedMoney,splitForSync,type Household} from '../src/core/index.ts';
import {claimSettlementReview,type ClaimSettlementRequest} from '../src/core/claimSettlementReview.ts';
import {capturedIntent,clearCapturedIntent} from '../src/ledgerSync/capture.ts';import {commandFromCapture,type Scope} from '../src/ledgerSync/protocol.ts';import {prepareCommand,type AuthorityState} from '../src/ledgerSync/authority.ts';import {executeIntent} from '../src/ledgerSync/registry.ts';
function fixture(){let h=addAppointment(catalogHousehold(),{title:'Hygienist',kind:'dentist',nextDate:'2026-09-01',cadence:{kind:'monthly',interval:6},typicalCost:248,typicalRecovery:180,subcategoryId:'SUB-HEALTH-DENTAL',accountId:'ACC-VISA',sensitivity:'household',memberId:'MEM-001'}).household;h=postVisit(h,{date:'2026-09-01',amount:248,appointmentId:h.appointments[0]!.id,expectedRecovery:180,confirmDuplicate:true,createdBy:'MEM-001'}).household;clearCapturedIntent(h);const r:ClaimSettlementRequest={environment:h.environment,householdId:h.householdId,memberId:'MEM-001',view:'household',claimId:h.claims[0]!.id,toAccountId:'ACC-CHEQUING',date:'2026-09-08',amountCents:18000};return {h,r};}
const input=(r:ClaimSettlementRequest)=>({claimId:r.claimId,toAccountId:r.toAccountId,date:r.date,amount:(r.amountCents/100).toFixed(2),createdBy:r.memberId,visibility:'household' as const,confirmDuplicate:true,claimReview:r});
function state(h:Household):AuthorityState{const a=splitForSync(h,'MEM-001'),b=splitForSync(h,'MEM-002');return {sequence:h.revision,shared:a.shared,personal:new Map([['MEM-001',a.personal],['MEM-002',b.personal]])};}
describe('Reviewed claim remainder',()=>{
 it('records an exact two-leg transfer with explicit destination and never adds income',()=>{const {h,r}=fixture(),before=JSON.stringify(h),reading=claimSettlementReview(h,r);expect(reading.kind).toBe('ready');expect(JSON.stringify(h)).toBe(before);const result=settleClaim(h,input(r)),rows=result.household.transactions.filter(t=>result.postedIds.includes(t.id));expect(rows).toHaveLength(2);expect(rows.every(t=>t.type==='transfer'&&t.amountCents===18000&&t.date===r.date)).toBe(true);expect(rows.map(t=>t.accountId)).toContain(r.toAccountId);expect(result.household.claims[0]!.receivedCents).toBe(18000);expect(()=>settleClaim(result.household,input(r))).toThrow(/owing changed/);});
 it('hashes current source meaning through authority, retains explicit destination under account reorder and rejects remote changes',async()=>{const {h,r}=fixture(),scope:Scope={environment:h.environment,householdId:h.householdId,memberId:r.memberId,subject:'test-one',role:'owner',expires:Date.now()+60000,aclEpoch:1},result=settleClaim(h,input(r)),command=await commandFromCapture(capturedIntent(result.household)!,scope,crypto.randomUUID());expect(command.steps[0]!.resources).toEqual([{key:'claim-settlement-review',hash:expect.any(String)}]);expect(JSON.stringify(command)).not.toContain('Hygienist');await expect(prepareCommand(state({...h,accounts:[...h.accounts].reverse()}),command,scope,()=>{})).resolves.toBeDefined();const partial=settleClaim(h,{...input(r),claimReview:undefined,amount:'25'}).household;for(const next of [partial,{...h,accounts:h.accounts.map(a=>a.id===r.toAccountId?{...a,name:'Other name'}:a)},{...h,transactions:h.transactions.map(t=>t.id===h.claims[0]!.recoveryTransactionId?{...t,note:'Changed evidence'}:t)}])await expect(prepareCommand(state(next),command,scope,()=>{})).rejects.toThrow('BUSINESS_PRECONDITION_CHANGED');expect(()=>executeIntent(h,'settleClaim',[input(r)],'MEM-002',crypto.randomUUID())).toThrow('ACTOR_MISMATCH');});
 it('refuses mixed private sources, private destinations, malformed amounts and closed posting months',()=>{const {h,r}=fixture();const privateSource={...h,transactions:h.transactions.map(t=>t.id===h.claims[0]!.expenseTransactionId?{...t,visibility:'personal' as const,createdBy:'MEM-002'}:t)};expect(claimSettlementReview(privateSource,r).kind).toBe('unavailable');expect(claimSettlementReview({...h,accounts:h.accounts.map(a=>a.id===r.toAccountId?{...a,scope:'personal' as const,ownerMemberId:'MEM-001'}:a)},r).kind).toBe('unavailable');for(const patch of [{amount:undefined},{amount:'179.99'},{visibility:'personal'},{toAccountId:'ACC-VISA'}])expect(()=>settleClaim(h,{...input(r),...patch} as Parameters<typeof settleClaim>[1])).toThrow('INVALID_CLAIM_REVIEW');expect(claimSettlementReview({...h,kitchen:{...h.kitchen,books:{...h.kitchen.books,closedMonths:[{monthKey:'2026-09'} as Household['kitchen']['books']['closedMonths'][number]]}}},r).kind).toBe('unavailable');});
 it('refuses reversed recovery, missing settlement mate and reversed partial settlement instead of guessing counters',()=>{const {h,r}=fixture();expect(claimSettlementReview(reversePostedMoney(h,h.claims[0]!.recoveryTransactionId!,{createdBy:'MEM-001'}).household,r).kind).toBe('unavailable');const partial=settleClaim(h,{...input(r),claimReview:undefined,amount:'25'}).household,remaining={...r,amountCents:15500};expect(claimSettlementReview(partial,remaining).kind).toBe('ready');const missing=partial.claims[0]!.settleTransferIds[1]!;expect(claimSettlementReview({...partial,transactions:partial.transactions.filter(t=>t.id!==missing)},remaining).kind).toBe('unavailable');expect(claimSettlementReview(reversePostedMoney(partial,partial.claims[0]!.settleTransferIds[0]!,{createdBy:'MEM-001'}).household,remaining).kind).toBe('unavailable');});
 it('refuses future visit or partial settlement history, malformed dates and unexpected incoming mates',()=>{const {h,r}=fixture();for(const date of [undefined,7,'2026-09-08 '])expect(claimSettlementReview(h,{...r,date} as unknown as ClaimSettlementRequest).kind).toBe('unavailable');const future=postVisit(catalogHousehold(),{date:'2026-09-09',amount:248,note:'Future visit',accountId:'ACC-VISA',subcategoryId:'SUB-HEALTH-DENTAL',expectedRecovery:180,confirmDuplicate:true,createdBy:'MEM-001'}).household;expect(claimSettlementReview(future,{...r,householdId:future.householdId,claimId:future.claims[0]!.id}).kind).toBe('unavailable');const partial=settleClaim(h,{...input(r),claimReview:undefined,amount:25,date:'2026-09-09'}).household;expect(claimSettlementReview(partial,{...r,amountCents:15500}).kind).toBe('unavailable');const current=settleClaim(h,{...input(r),claimReview:undefined,amount:25}).household,leg=current.transactions.find(t=>t.id===current.claims[0]!.settleTransferIds[0])!;expect(claimSettlementReview({...current,transactions:[...current.transactions,{...leg,id:'unexpected-incoming',transferPairId:leg.id}]},{...r,amountCents:15500}).kind).toBe('unavailable');});
 it('reads Shared claim money from Personal view without copying quiet card titles into journal or wire',async()=>{const {h,r}=fixture(),quiet={...h,appointments:h.appointments.map(a=>({...a,title:'QUIET-CANARY-922',sensitivity:'quiet' as const,memberId:'MEM-001'}))},request={...r,view:'personal' as const},reading=claimSettlementReview(quiet,request);expect(reading.kind).toBe('ready');if(reading.kind==='ready')expect(reading.detail).toContain('QUIET-CANARY-922');const result=settleClaim(quiet,input(request));expect(result.household.transactions.filter(t=>result.postedIds.includes(t.id)).every(t=>!t.note.includes('QUIET-CANARY-922')&&t.visibility==='household')).toBe(true);const scope:Scope={environment:h.environment,householdId:h.householdId,memberId:r.memberId,subject:'test-one',role:'owner',expires:Date.now()+60000,aclEpoch:1};const command=await commandFromCapture(capturedIntent(result.household)!,scope,crypto.randomUUID());expect(JSON.stringify(command)).not.toContain('QUIET-CANARY-922');await expect(prepareCommand(state(quiet),command,scope,()=>{})).resolves.toBeDefined();expect(claimSettlementReview(quiet,r).kind).toBe('unavailable');});
});
