// @vitest-environment jsdom
import {act,createElement} from 'react';import {createRoot} from 'react-dom/client';import {describe,it,expect} from 'vitest';import {ConfirmSheet} from '../src/Confirm.tsx';
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
async function mount(width=390){Object.defineProperty(window,'innerWidth',{value:width,writable:true,configurable:true});Object.assign(HTMLElement.prototype,{setPointerCapture(){},releasePointerCapture(){},hasPointerCapture(){return false;}});const host=document.createElement('div');document.body.append(host);const root=createRoot(host),writes:string[]=[],closes:string[]=[];let live='A';const props={danger:true,title:'Reverse this row?',body:'Fictional12.34purchase.',confirmLabel:'Reverse',busy:false,review:{openingId:'1',identity:'A',readIdentity:()=>live},onConfirm:()=>writes.push('confirm'),onCancel:()=>closes.push('cancel')};const render=()=>act(async()=>root.render(createElement(ConfirmSheet,props)));await render();const button=(name:string)=>[...host.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent===name);return{host,props,writes,closes,button,render,setLive:(next:string)=>{live=next;},input:()=>host.querySelector<HTMLInputElement>('input[type=range]')!,close:async()=>{await act(async()=>root.unmount());host.remove();}};}
function pointer(node:Element,type:string,id=1){const event=new Event(type,{bubbles:true});Object.assign(event,{pointerId:id,isPrimary:id===1,button:0});node.dispatchEvent(event);}
async function value(input:HTMLInputElement,next:number){await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,String(next));input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));});}
describe('Phone destructive disclosure and review lifetime',()=>{
 it('focuses Cancel and separates range release or named Show from the only Confirm callback',async()=>{const m=await mount();try{expect(document.activeElement).toBe(m.button('Cancel'));expect(m.button('Reverse')).toBeUndefined();await act(async()=>pointer(m.input(),'pointerdown'));await value(m.input(),100);expect(m.button('Reverse')).toBeUndefined();await act(async()=>pointer(m.input(),'pointerup'));expect(m.button('Reverse')).toBeDefined();expect(m.writes).toEqual([]);await act(async()=>m.button('Reverse')!.click());expect(m.writes).toEqual(['confirm']);}finally{await m.close();}});
 it('restores cancelled gestures, ignores late input, and gives the sheet the second Escape',async()=>{const m=await mount();try{for(const reason of ['pointercancel','lostpointercapture','Escape','second']){const range=m.input();range.focus();await act(async()=>pointer(range,'pointerdown'));await value(range,100);await act(async()=>{if(reason==='Escape')range.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));else pointer(range,reason==='second'?'pointerdown':reason,reason==='second'?2:1);});await value(range,100);expect(range.value).toBe('0');expect(m.button('Reverse')).toBeUndefined();}expect(m.closes).toEqual([]);await act(async()=>m.input().dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));expect(m.closes).toEqual(['cancel']);expect(m.writes).toEqual([]);}finally{await m.close();}});
 it('latches changed source through A-B-A and checks source again on the named event, until a new opening',async()=>{const m=await mount();try{await act(async()=>m.button('Show Reverse')!.click());m.setLive('B');await act(async()=>m.button('Reverse')!.click());expect(m.writes).toEqual([]);expect(m.host.textContent).toContain('This review changed');m.setLive('A');await m.render();expect(m.button('Reverse')).toBeUndefined();m.props.review={...m.props.review,openingId:'2'};await m.render();await act(async()=>m.button('Show Reverse')!.click());m.props.review={...m.props.review,identity:'B'};m.setLive('B');await m.render();m.props.review={...m.props.review,identity:'A'};m.setLive('A');await m.render();expect(m.button('Reverse')).toBeUndefined();expect(m.writes).toEqual([]);}finally{await m.close();}});
 it('preserves keyboard focus across busy/viewport changes, resets disclosure and leaves normal Confirm direct',async()=>{const m=await mount();try{await act(async()=>m.button('Show Reverse')!.click());m.button('Reverse')!.focus();m.props.busy=true;await m.render();expect(document.activeElement?.className).toBe('confirm-status');m.props.busy=false;await m.render();expect(m.button('Reverse')).toBeUndefined();await act(async()=>m.button('Show Reverse')!.click());m.button('Cancel')!.focus();await act(async()=>{window.innerWidth=1100;window.dispatchEvent(new Event('resize'));});expect(document.activeElement).toBe(m.button('Cancel'));expect(m.input()).toBeNull();expect(m.button('Reverse')!.disabled).toBe(false);m.props.danger=false;await m.render();await act(async()=>m.button('Reverse')!.click());expect(m.writes).toEqual(['confirm']);}finally{await m.close();}});
});
