// @vitest-environment jsdom
import {act,createElement,useState} from 'react';import {createRoot,type Root} from 'react-dom/client';import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';import {useDialog} from '../src/useDialog.ts';import {DocumentCamera} from '../src/imports/DocumentCamera.tsx';import {captureQualityWarnings,type CaptureQuality} from '../src/imports/captureQuality.ts';
const fixture=vi.hoisted(()=>({ready:false,delay:false,encode:null as null|BlobCallback}));vi.mock('../src/imports/documentClarity.ts',()=>({CLARITY_READY_SCORE:72,scoreDocumentFrame:()=>({ready:fixture.ready,score:fixture.ready?90:40,issues:fixture.ready?[]:['Too dim','Too soft','Too small','Low contrast','Crumpled edge'],sharp:0,contrast:0,brightness:0,textiness:0,reason:'quality'})}));
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let host:HTMLDivElement,root:Root,stop:ReturnType<typeof vi.fn>,captures:Array<{file:File;quality:CaptureQuality}>,closed:number;
const props=()=>({open:true,onClose:()=>closed++,onCapture:(file:File,quality:CaptureQuality)=>{captures.push({file,quality});}});
const button=(text:string)=>[...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent===text)!;
beforeEach(()=>{vi.useFakeTimers();fixture.ready=false;fixture.delay=false;fixture.encode=null;closed=0;captures=[];stop=vi.fn();host=document.createElement('div');document.body.append(host);root=createRoot(host);Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:vi.fn(async()=>({getTracks:()=>[{stop}]}))}});vi.spyOn(HTMLMediaElement.prototype,'play').mockResolvedValue();for(const [key,value] of [['videoWidth',640],['videoHeight',480],['readyState',4]] as const)Object.defineProperty(HTMLVideoElement.prototype,key,{configurable:true,get:()=>value});vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue({drawImage:vi.fn()} as unknown as CanvasRenderingContext2D);vi.spyOn(HTMLCanvasElement.prototype,'toBlob').mockImplementation(callback=>{if(fixture.delay)fixture.encode=callback;else callback(new Blob(['image'],{type:'image/jpeg'}));});});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.restoreAllMocks();vi.useRealTimers();});
describe('Explicit camera quality override',()=>{
 it('never counts passive frames, shows every issue and requires two rejected user attempts',async()=>{await act(async()=>root.render(createElement(DocumentCamera,props())));await act(async()=>vi.advanceTimersByTime(2000));expect(document.querySelectorAll('.doc-camera-issues li')).toHaveLength(5);expect(button('Capture anyway')).toBeUndefined();await act(async()=>button('Capture tip sheet').click());expect(button('Capture anyway')).toBeUndefined();await act(async()=>button('Capture tip sheet').click());expect(captures).toHaveLength(0);await act(async()=>button('Capture anyway').click());expect(captures).toHaveLength(1);expect(captures[0]!.quality).toMatchObject({overridden:true,issues:['Too dim','Too soft','Too small','Low contrast','Crumpled edge']});expect(captureQualityWarnings(captures[0]!.quality)).toHaveLength(6);expect(closed).toBe(1);expect(stop).toHaveBeenCalled();});
 it('captures a freshly clear frame normally without quality warnings',async()=>{await act(async()=>root.render(createElement(DocumentCamera,props())));fixture.ready=true;await act(async()=>button('Capture tip sheet').click());expect(captures).toHaveLength(1);expect(captureQualityWarnings(captures[0]!.quality)).toEqual([]);});
 it('discards an encoded frame after Close and resets attempts on reopen',async()=>{await act(async()=>root.render(createElement(DocumentCamera,props())));await act(async()=>button('Capture tip sheet').click());await act(async()=>button('Capture tip sheet').click());fixture.delay=true;await act(async()=>button('Capture anyway').click());await act(async()=>button('Close').click());await act(async()=>fixture.encode!(new Blob(['late'])));expect(captures).toHaveLength(0);await act(async()=>root.render(createElement(DocumentCamera,{...props(),open:false})));await act(async()=>root.render(createElement(DocumentCamera,props())));expect(button('Capture anyway')).toBeUndefined();});
 it('gives a nested camera exclusive Escape and restores Add focus/background state',async()=>{let parentClosed=0;function Parent(){const [open,setOpen]=useState(false),ref=useDialog(true,()=>parentClosed++);return createElement('div',{ref,role:'dialog','aria-modal':true},createElement('button',{onClick:()=>setOpen(true)},'Open nested camera'),createElement(DocumentCamera,{...props(),open,onClose:()=>setOpen(false)}));}await act(async()=>root.render(createElement(Parent)));const invoker=button('Open nested camera');invoker.focus();await act(async()=>invoker.click());expect(host.hasAttribute('inert')).toBe(true);expect(document.activeElement).toBe(button('Close'));await act(async()=>document.activeElement!.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));expect(parentClosed).toBe(0);expect(document.querySelector('.doc-camera-overlay')).toBeNull();expect(document.activeElement).toBe(invoker);expect(host.hasAttribute('inert')).toBe(false);});
 it('stops late camera startup and keeps unavailable cameras unable to capture',async()=>{let release!:(stream:MediaStream)=>void;Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:()=>new Promise<MediaStream>(r=>release=r)}});await act(async()=>root.render(createElement(DocumentCamera,props())));expect(button('Capture tip sheet').disabled).toBe(true);await act(async()=>root.render(createElement(DocumentCamera,{...props(),open:false})));await act(async()=>release({getTracks:()=>[{stop}]} as unknown as MediaStream));expect(stop).toHaveBeenCalled();expect(captures).toHaveLength(0);});
});
