// @vitest-environment jsdom
import {act,createElement} from 'react';import {createRoot} from 'react-dom/client';import {describe,it,expect} from 'vitest';
import {DuePreviewSheet} from '../src/DuePreviewSheet.tsx';import {catalogHousehold,addRecurrence,dueRecurrencePreview} from '../src/core/index.ts';
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
async function mount(){Object.assign(HTMLElement.prototype,{setPointerCapture(){},releasePointerCapture(){},hasPointerCapture(){return false;}});localStorage.clear();const h=addRecurrence(catalogHousehold(),{cadence:'monthly',nextDate:'2026-09-01',type:'expense',amount:'75.25',accountId:'ACC-CHEQUING',subcategoryId:'SUB-FOOD-GROCERIES',note:'Internet'}).household,host=document.createElement('div'),root=createRoot(host);document.body.append(host);const writes:unknown[]=[],props={rows:dueRecurrencePreview(h,'2026-09-08'),household:h,memberId:'MEM-001',view:'household' as const,today:'2026-09-08',busy:false,isCurrent:()=>true,onDismiss:()=>{},onPost:async(review:unknown)=>{writes.push(review);return true;}};const render=()=>act(async()=>root.render(createElement(DuePreviewSheet,props)));await render();const button=(name:string)=>[...host.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent===name)!;return{host,props,render,button,writes,handle:()=>host.querySelector<HTMLButtonElement>('.row-reveal-handle')!,close:async()=>{await act(async()=>root.unmount());host.remove();}};}
function pointer(el:Element,type:string,x=100,y=100,id=1){const e=new Event(type,{bubbles:true});Object.assign(e,{pointerId:id,isPrimary:id===1,button:0,clientX:x,clientY:y});el.dispatchEvent(e);}
describe('Inline Due row',()=>{
 it('reveals only, retains one inline review, and waits for named accepted posting',async()=>{const m=await mount();try{await act(async()=>{pointer(m.handle(),'pointerdown');pointer(m.handle(),'pointermove',150);});expect(m.host.querySelector('[inert]')).not.toBeNull();expect(m.writes).toEqual([]);await act(async()=>pointer(m.handle(),'pointerup',150));expect(m.host.querySelector('[role=dialog]')).toBeNull();let finish!:(ok:boolean)=>void;m.props.onPost=async r=>{m.writes.push(r);return new Promise(resolve=>finish=resolve);};await m.render();m.button('Confirm payment · Internet').focus();await act(async()=>m.button('Confirm payment · Internet').click());expect(document.activeElement?.hasAttribute('data-row-status')).toBe(true);expect(m.host.textContent).toContain('Waiting for acceptance');expect(m.host.textContent).toContain('Internet');await act(async()=>finish(true));expect(m.host.textContent).toContain('1 occurrence posted');expect(m.host.querySelector('.row-reveal')).toBeNull();}finally{await m.close();}});
 it('cancels drag and late click without hiding or posting; named local deferral changes no schedule',async()=>{const m=await mount();try{const before=JSON.stringify(m.props.household);for(const reason of ['pointercancel','lostpointercapture','second','Escape']){await act(async()=>{pointer(m.handle(),'pointerdown');pointer(m.handle(),'pointermove',150);if(reason==='Escape')m.handle().dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));else pointer(m.handle(),reason==='second'?'pointerdown':reason,150,100,reason==='second'?2:1);m.handle().dispatchEvent(new MouseEvent('click',{bubbles:true,detail:1}));});expect(m.host.querySelector('.row-reveal')!.getAttribute('data-side')).toBe('rest');}await act(async()=>m.button('Later').click());expect(m.writes).toEqual([]);await act(async()=>m.button('Hide this reminder').click());expect(JSON.stringify(m.props.household)).toBe(before);expect(m.writes).toEqual([]);expect(m.host.querySelector('.row-reveal')).toBeNull();}finally{await m.close();}});
 it('latches a changed amount through source ABA and refreshes all displayed facts explicitly',async()=>{const m=await mount();try{await act(async()=>m.button('Actions').click());const original=m.props.household;m.props.household={...original,recurrences:original.recurrences.map(r=>({...r,amountCents:9900,note:'Changed bill'}))};await m.render();expect(m.button('Confirm payment · Internet')).toBeUndefined();m.props.household=original;await m.render();expect(m.button('Confirm payment · Internet')).toBeUndefined();m.props.household={...original,recurrences:original.recurrences.map(r=>({...r,amountCents:9900,note:'Changed bill'}))};await m.render();await act(async()=>m.button('Review current details').click());expect(m.host.textContent).toContain('$99.00');expect(m.host.textContent).not.toContain('$75.25');expect(document.activeElement).toBe(m.handle());await act(async()=>m.button('Actions').click());expect(m.button('Confirm payment · Changed bill')).toBeDefined();expect(m.writes).toEqual([]);}finally{await m.close();}});
 it('keeps a rejected row, restores keyboard focus and blocks stale scope confirmation',async()=>{const m=await mount();try{let finish!:(ok:boolean)=>void;m.props.onPost=async()=>new Promise(resolve=>finish=resolve);await m.render();await act(async()=>m.button('Actions').click());m.button('Confirm payment · Internet').focus();await act(async()=>m.button('Confirm payment · Internet').click());expect(document.activeElement?.hasAttribute('data-row-status')).toBe(true);await act(async()=>finish(false));expect(document.activeElement).toBe(m.handle());expect(m.host.textContent).toContain('Not yet accepted');m.props.isCurrent=()=>false;await m.render();expect(m.button('Actions').disabled).toBe(true);expect(m.writes).toEqual([]);}finally{await m.close();}});
});
