// @vitest-environment jsdom
import {describe,it,expect} from 'vitest';
import {catalogHousehold,addRecurrence,postOneRecurrence,postEntry,splitForSync,type Household} from '../src/core/index.ts';
import {dueOccurrenceReview,hideDueOccurrence,dueOccurrenceHidden,type DueOccurrenceRequest} from '../src/core/dueOccurrenceReview.ts';
import {capturedIntent,clearCapturedIntent} from '../src/ledgerSync/capture.ts';
import {commandFromCapture,type Scope} from '../src/ledgerSync/protocol.ts';
import {prepareCommand,type AuthorityState} from '../src/ledgerSync/authority.ts';
import {executeIntent} from '../src/ledgerSync/registry.ts';
export function fixture(){const h=addRecurrence(catalogHousehold(),{cadence:'monthly',nextDate:'2026-09-01',type:'expense',amount:'75.25',accountId:'ACC-CHEQUING',subcategoryId:'SUB-FOOD-GROCERIES',note:'Internet'}).household;clearCapturedIntent(h);const request:DueOccurrenceRequest={environment:h.environment,householdId:h.householdId,memberId:'MEM-001',view:'household',today:'2026-09-08',recurrenceId:h.recurrences[0]!.id,occurrenceDate:'2026-09-01'};return {h,request};}
function state(h:Household):AuthorityState{const one=splitForSync(h,'MEM-001'),two=splitForSync(h,'MEM-002');return {sequence:h.revision,shared:one.shared,personal:new Map([['MEM-001',one.personal],['MEM-002',two.personal]])};}
describe('Due occurrence authority',()=>{
 it('posts the displayed overdue occurrence once, never today or the newly advanced occurrence',()=>{const {h,request}=fixture(),before=JSON.stringify(h),reading=dueOccurrenceReview(h,request);expect(reading.kind).toBe('ready');expect(JSON.stringify(h)).toBe(before);const result=postOneRecurrence(h,request.recurrenceId,request.today,{createdBy:request.memberId,dueReview:request});expect(result.household.transactions.filter(tx=>result.postedIds.includes(tx.id)).every(tx=>tx.date==='2026-09-01'&&tx.amountCents===7525)).toBe(true);expect(result.household.recurrences[0]!.nextDate).toBe('2026-10-01');expect(()=>postOneRecurrence(result.household,request.recurrenceId,request.today,{createdBy:request.memberId,dueReview:request})).toThrow(/occurrence changed/);});
 it('hashes the exact derived sources at authoritative replay and tolerates unrelated activity',async()=>{const {h,request}=fixture(),scope:Scope={environment:h.environment,householdId:h.householdId,memberId:request.memberId,subject:'test-one',role:'owner',expires:Date.now()+60000,aclEpoch:1};const result=postOneRecurrence(h,request.recurrenceId,request.today,{createdBy:request.memberId,dueReview:request}),command=await commandFromCapture(capturedIntent(result.household)!,scope,crypto.randomUUID());expect(command.steps[0]!.resources).toEqual([{key:'due-occurrence-review',hash:expect.any(String)}]);expect(JSON.stringify(command)).not.toContain('Internet');await expect(prepareCommand(state(h),command,scope,()=>{})).resolves.toBeDefined();for(const next of [{...h,accounts:h.accounts.map(a=>a.id==='ACC-CHEQUING'?{...a,name:'Changed source'}:a)},{...h,categories:h.categories.map(c=>c.id==='SUB-FOOD-GROCERIES'?{...c,name:'Changed category'}:c)},{...h,recurrences:h.recurrences.map(r=>({...r,amountCents:9999}))}])await expect(prepareCommand(state(next),command,scope,()=>{})).rejects.toThrow('BUSINESS_PRECONDITION_CHANGED');const unrelated=postEntry(h,{date:'2026-09-08',type:'expense',amount:'1.23',accountId:'ACC-VISA',subcategoryId:'SUB-FOOD-COFFEE',createdBy:'MEM-001'}).household;await expect(prepareCommand(state(unrelated),command,scope,()=>{})).resolves.toBeDefined();expect(()=>executeIntent(h,'postOneRecurrence',[request.recurrenceId,request.today,{createdBy:'MEM-001',dueReview:request}],'MEM-002',crypto.randomUUID())).toThrow('ACTOR_MISMATCH');});
 it('refuses unsupported Personal accounts, private goals, invalid dates and moved occurrences',()=>{const {h,request}=fixture();for(const r of [{...request,occurrenceDate:'2026-09-02'},{...request,today:'2026-02-30'},{...request,memberId:'missing'}])expect(dueOccurrenceReview(h,r).kind).toBe('unavailable');const personal={...h,accounts:h.accounts.map(a=>a.id==='ACC-CHEQUING'?{...a,scope:'personal' as const,ownerMemberId:'MEM-001'}:a)};expect(dueOccurrenceReview(personal,{...request,view:'personal'}).kind).toBe('unavailable');expect(()=>postOneRecurrence(h,request.recurrenceId,request.today,{createdBy:'MEM-001',dueReview:request,allowNotDue:true})).toThrow('INVALID_DUE_REVIEW');});
 it('describes transfer Joint allocation and refuses a private linked goal',()=>{const {h,request}=fixture();const transfer:Household={...h,recurrences:h.recurrences.map(r=>({...r,type:'transfer',transferToAccountId:'ACC-VISA',splits:[{party:'missing-member',amountCents:r.amountCents}]}))};const reading=dueOccurrenceReview(transfer,request);expect(reading.kind).toBe('ready');if(reading.kind==='ready')expect(reading.detail).toContain('Split: Joint $75.25');const posted=postOneRecurrence(transfer,request.recurrenceId,request.today,{createdBy:request.memberId,dueReview:request});expect(posted.household.transactions.filter(t=>posted.postedIds.includes(t.id)).every(t=>t.splits.every(s=>s.party==='joint'))).toBe(true);const privateGoal:Household={...transfer,goals:[{id:'private-goal',name:'Private goal',targetCents:100000,savedCents:0,deadline:null,arrivalDate:null,shared:false,ownerMemberId:'MEM-001',subcategoryId:null,status:'open',funded:false,retiredAt:null,purchaseId:null,createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-01T00:00:00Z'}],recurrences:transfer.recurrences.map(r=>({...r,goalId:'private-goal'}))};expect(dueOccurrenceReview(privateGoal,request).kind).toBe('unavailable');});
 it('hides only this member/view/occurrence/day on this device without changing Books or schedule',()=>{localStorage.clear();const {h,request}=fixture(),before=JSON.stringify(h);hideDueOccurrence(request);expect(dueOccurrenceHidden(request)).toBe(true);for(const r of [{...request,memberId:'MEM-002'},{...request,view:'personal' as const},{...request,occurrenceDate:'2026-10-01'},{...request,today:'2026-09-09'},{...request,householdId:'another'}])expect(dueOccurrenceHidden(r)).toBe(false);expect(JSON.stringify(h)).toBe(before);});
});
