// @vitest-environment jsdom
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {entryDraftKey,writeEntryLocal,loadEntryDraft,entryConfirmation,readEntrySubmission,clearEntryConfirmation,type EntryDraft} from '../src/entryDraft.ts';
const key=(mode:'expense'|'income'|'transfer'|'shift',member='member-a',view='personal',identity='google-a')=>entryDraftKey('development','house-a',member,view,identity,mode);
const fixture=(mode:EntryDraft['mode']):EntryDraft=>({version:1,mode,form:{date:'2026-09-08',amount:'12.34',accountId:'private-a'} as EntryDraft['form'],slide:2,details:false,launchAccountId:'private-a',focusedAccountId:'private-a',categoryTouched:true,codingHint:'',presetId:null,hoursDirty:false,shiftGate:'finished',workShiftDate:'2026-09-08',workShiftDraft:null,split:{members:['member-a','member-b'],percents:{'member-a':30,'member-b':70}}});
beforeEach(()=>{sessionStorage.clear();});afterEach(()=>vi.restoreAllMocks());
describe('scoped entry recovery',()=>{
 it.each(['expense','income','transfer','shift'] as const)('%s retains editable fields and splits through a fresh module load',async mode=>{const scope=key(mode);writeEntryLocal(scope,fixture(mode));vi.resetModules();const reloaded=await import('../src/entryDraft.ts');expect(reloaded.loadEntryDraft(scope)).toEqual(fixture(mode));expect(reloaded.loadEntryDraft(key(mode,'member-b'))).toBeNull();expect(reloaded.loadEntryDraft(key(mode,'member-a','household'))).toBeNull();expect(reloaded.loadEntryDraft(key(mode,'member-a','personal','google-b'))).toBeNull();});
 it('reuses only the exact pending review and rejects changed money',()=>{const scope=key('expense')+crypto.randomUUID(),review=JSON.stringify({amount:'12.34',account:'private-a'});const id=entryConfirmation(scope,review);expect(entryConfirmation(scope,review)).toBe(id);expect(()=>entryConfirmation(scope,JSON.stringify({amount:'23.45',account:'private-a'}))).toThrow(/awaiting/i);clearEntryConfirmation(scope,'stale-id');expect(readEntrySubmission(scope)?.id).toBe(id);clearEntryConfirmation(scope,id);expect(entryConfirmation(scope,review)).not.toBe(id);});
 it('refuses confirmation when its recovery identity cannot be saved',()=>{vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new DOMException('quota','QuotaExceededError');});const scope=key('income')+crypto.randomUUID();expect(()=>entryConfirmation(scope,'review')).toThrow(/cannot save/i);expect(readEntrySubmission(scope)).toBeNull();});
 it('does not manufacture a new confirmation identity over a corrupt receipt',()=>{const scope=key('transfer')+crypto.randomUUID();sessionStorage.setItem(scope+':confirmation','{broken');expect(()=>entryConfirmation(scope,'review')).toThrow(/damaged/i);});
 it('honours explicit storage removal instead of reviving an old memory copy',()=>{const scope=key('income')+crypto.randomUUID();writeEntryLocal(scope,fixture('income'));sessionStorage.removeItem(scope);expect(loadEntryDraft(scope)).toBeNull();});
 it('keeps the latest in-memory draft when a stored overwrite fails',()=>{const scope=key('expense')+crypto.randomUUID();writeEntryLocal(scope,fixture('expense'));vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new DOMException('quota','QuotaExceededError');});const changed={...fixture('expense'),form:{...fixture('expense').form,amount:'23.45'}};expect(writeEntryLocal(scope,changed)).toBe(false);expect(loadEntryDraft(scope)?.form.amount).toBe('23.45');});
 it('rejects corrupted recovery metadata without throwing',()=>{const scope=key('shift')+crypto.randomUUID();writeEntryLocal(scope,{version:1,mode:'shift',form:{amount:'12',date:'2026-09-08'},slide:2,split:{members:null}});expect(loadEntryDraft(scope)).toBeNull();});
});
