import {captureRoomFurniture} from '../src/hearthside/roomFurniture.ts';
import {describe,expect,it,vi} from 'vitest';
import {guestClient} from '../src/hearthside/guestClient.ts';
import {createHmac,createHash} from 'node:crypto';
import {newKittyPiece} from '../src/core/kittyStudio.ts';
import {decodeGuestArrangement,decodeGuestPrepare,guestDigest,guestDisplayPiece,type GuestPrepareInput} from '../src/hearthside/guestContracts.ts';
import {captureGuestSources,validateGuestSources,type GuestSourceCatalogue} from '../src/hearthside/guestProjection.ts';
import {guestAuthorityAttestation,resolveGuestAuthority} from '../workers/hearthsideGuestAuthority.ts';
const id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const input:GuestPrepareInput={publicationId:id,title:'Our open door',welcome:'Come in for a moment.',theme:'classic',room:'common',mode:'anytime',items:[{kind:'experience',id:'EXP-private-source-id',revision:2,x:.2,y:.3},{kind:'piece',id:'PIECE-private-source-id',designId:'DESIGN-private-source-id',revision:7,x:.7,y:.6},{kind:'memory',id:'MEMORY-private-source-id',revision:3,x:.4,y:.5}]};
function catalogue():GuestSourceCatalogue {const piece=newKittyPiece('PIECE-private-source-id','2026-09-12T00:00:00.000Z');return {furniture:room=>captureRoomFurniture(room),activeMemberIds:['MEM-A','MEM-B'],experience:()=>({shared:true,archived:false,revision:2,title:'A small journey',intention:'Time together'}),note:()=>null,memory:()=>({shared:true,withdrawn:false,revision:3,title:'Our afternoon',recollections:[{memberId:'MEM-A',text:'My exact words.'},{memberId:'MEM-B',text:'My separate memory.'}],approvals:[{memberId:'MEM-A',revision:3},{memberId:'MEM-B',revision:3}],media:[],publicationId:'memory-publication',designs:[]}),memoryAccess:async()=>true,piece:async()=>({shared:true,archived:false,revision:7,piece}),media:async()=>null};}
describe('guest copy and authority boundaries',()=>{
 it('copies the exact selected shared content without source identifiers, financial fields or original cat identity',async()=>{const captured=await captureGuestSources(input,catalogue()),json=JSON.stringify(captured.arrangement);expect(json).not.toMatch(/private-source-id|MEM-A|MEM-B|createdAt|firedAt|household|balance|target|bank|contribution/);expect(json).toContain('My exact words.');const piece=captured.arrangement.objects.find(o=>o.kind==='piece');expect(piece?.kind).toBe('piece');if(piece?.kind==='piece'){expect(piece.displaySize).toBe('standard');expect(guestDisplayPiece(piece.appearance).id).toBe('guest-display');}expect(captured.proof.selection.items[0]!.id).toBe('EXP-private-source-id');expect(captured.proof.digest).toBe(await guestDigest({selection:decodeGuestPrepare(input),arrangement:captured.arrangement,memoryBindings:captured.proof.memoryBindings}));});
 it('rejects unselected/private/withdrawn records and stale mutual approval',async()=>{for(const changed of [{experience:()=>({shared:false,archived:false,revision:2,title:'Hidden',intention:'secret'})},{memory:()=>({...catalogue().memory('x')!,withdrawn:true})},{memory:()=>({...catalogue().memory('x')!,approvals:[{memberId:'MEM-A',revision:3}]})},{piece:async()=>({...(await catalogue().piece('x','x',7))!,shared:false})}])await expect(captureGuestSources(input,{...catalogue(),...changed})).rejects.toThrow(/GUEST_SOURCE/);});
 it('keeps an activated copy stable after source edits, while denying later private visibility',async()=>{const source=catalogue(),captured=await captureGuestSources(input,source);source.experience=()=>({shared:true,archived:false,revision:3,title:'Changed',intention:'Other words'});expect(await validateGuestSources(captured.proof,source,'activation')).toBe(false);expect(await validateGuestSources(captured.proof,source,'visit')).toBe(true);expect(captured.arrangement.objects[0]).toMatchObject({title:'A small journey'});source.experience=()=>({shared:false,archived:false,revision:3,title:'Changed',intention:'Other words'});expect(await validateGuestSources(captured.proof,source,'visit')).toBe(false);});
 it('rejects extra fields and accessor/sparse nested input without reading getters',async()=>{expect(()=>decodeGuestPrepare({...input,balance:200})).toThrow();expect(()=>decodeGuestPrepare({...input,items:[{...input.items[0],designId:'hidden'}]})).toThrow();const getter=vi.fn(()=>input.items);const raw={...input};Object.defineProperty(raw,'items',{get:getter});expect(()=>decodeGuestPrepare(raw)).toThrow();expect(getter).not.toHaveBeenCalled();const sparse=new Array(1);expect(()=>decodeGuestPrepare({...input,items:sparse})).toThrow();const copy=(await captureGuestSources(input,catalogue())).arrangement;expect(()=>decodeGuestArrangement({...copy,householdId:'HH-secret'})).toThrow();const obj={...copy.objects[1],financialScale:2};expect(()=>decodeGuestArrangement({...copy,objects:[obj]})).toThrow();});
 it('keeps words and authored designs without requiring a Vault publication',async()=>{const source=catalogue();source.memory=()=>({...catalogue().memory('x')!,publicationId:null,designs:[{designId:'DESIGN-private-source-id',pieceId:'PIECE-private-source-id',revision:7}]});source.memoryAccess=async binding=>binding.publicationId===null&&binding.revision===3;const captured=await captureGuestSources(input,source);expect(captured.proof.memoryBindings).toEqual([{id:'MEMORY-private-source-id',revision:3,publicationId:null}]);const memory=captured.arrangement.objects.find(o=>o.kind==='memory');expect(memory?.kind==='memory'&&memory.pieces).toHaveLength(1);expect(await validateGuestSources(captured.proof,source,'visit')).toBe(true);source.memoryAccess=async()=>false;expect(await validateGuestSources(captured.proof,source,'visit')).toBe(false);});
 it('supports an explicitly reviewed empty guest room without inventing keepsakes',async()=>{const copy=await captureGuestSources({...input,items:[]},catalogue());expect(copy.arrangement.objects).toEqual([]);expect(copy.media).toEqual([]);});
 it('binds server proof to the exact JWT and requested host while keeping the raw token out',async()=>{const env={HEARTHSIDE_GUEST_AUTHORITY_KEY:'34'.repeat(32),HEARTHSIDE_GUEST_AUTHORITY_KEY_ID:'synthetic-key'},token='synthetic.jwt',at=1900000000;const signed=await guestAuthorityAttestation(env,token,'HH-HOST',at),hash=createHash('sha256').update(token).digest('hex'),material=['hearthside-guest-authority-v1','synthetic-key','development','HH-HOST',String(at),hash].join('\n');expect(signed.p_signature).toBe(createHmac('sha256',Buffer.from(env.HEARTHSIDE_GUEST_AUTHORITY_KEY,'hex')).update(material).digest('hex'));expect(JSON.stringify(signed)).not.toContain(token);expect((await guestAuthorityAttestation(env,token,null,at)).p_signature).not.toBe(signed.p_signature);expect((await guestAuthorityAttestation(env,'other.jwt','HH-HOST',at)).p_signature).not.toBe(signed.p_signature);});
 it('fails closed without explicit authority configuration and redacts provider errors',async()=>{await expect(resolveGuestAuthority({},'token',null)).rejects.toThrow('GUEST_DISABLED');const env={SUPABASE_URL:'https://synthetic.test',SUPABASE_PUBLISHABLE_KEY:'synthetic',HEARTHSIDE_GUEST_AUTHORITY_KEY:'34'.repeat(32),HEARTHSIDE_GUEST_AUTHORITY_KEY_ID:'synthetic-key',HEARTHSIDE_GUEST_CONTROL_PLANE:{fetch:async()=>new Response('private provider body',{status:500})}};await expect(resolveGuestAuthority(env,'token',null)).rejects.toThrow(/^GUEST_UNAVAILABLE$/);});
});

describe('guest client bounded resources',()=>{
 it('cancels an unresolved token lookup on scope abort without making a request',async()=>{const fetcher=vi.fn();vi.stubGlobal('fetch',fetcher);try{const abort=new AbortController(),client=guestClient({scopeKey:'own',token:()=>new Promise(()=>{})});const pending=client.request('street',undefined,abort.signal);abort.abort();await expect(pending).rejects.toMatchObject({name:'AbortError'});expect(fetcher).not.toHaveBeenCalled();}finally{vi.unstubAllGlobals();}});
 it('caps chunked media bytes before creating a Blob and cancels the stream',async()=>{let cancelled=false;const stream=new ReadableStream({pull(controller){controller.enqueue(new Uint8Array(1024*1024));},cancel(){cancelled=true;}});vi.stubGlobal('fetch',vi.fn(async()=>new Response(stream,{headers:{'Content-Type':'image/png'}})));try{const client=guestClient({scopeKey:'own',token:async()=> 'synthetic.token'});await expect(client.media('visit/copy/media/asset',{},new AbortController().signal)).rejects.toThrow('GUEST_MEDIA_CHANGED');expect(cancelled).toBe(true);}finally{vi.unstubAllGlobals();}});
});
