// @vitest-environment jsdom
import {webcrypto} from 'node:crypto';
import {act,createElement} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {ExperienceBankEntry} from '../src/hearthside/ExperienceBankEntry.tsx';
import {KittyBankRoom} from '../src/kitty/KittyBankRoom.tsx';
import {commitHearthside} from '../src/hearthside/commands.ts';
import {addGoal} from '../src/core/commands.ts';
import {BankTestAuthority} from './fixtures/hearthside-bank.ts';
import type {KittyAcceptedCommandReader} from '../src/hearthside/bankReceipt.ts';
vi.mock('../src/kitty/KittyStage.tsx',()=>({KittyStage:()=>createElement('div',{'data-kitty-stage':true})}));
vi.mock('../src/kitty/studio/flat.tsx',()=>({KittyFlat:()=>createElement('svg')}));
let root:Root,host:HTMLDivElement,f:BankTestAuthority;
const button=(text:string)=>[...document.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent?.trim()===text)!;
const click=async(text:string)=>{expect(button(text),text).toBeTruthy();await act(async()=>{button(text).click();await new Promise(r=>setTimeout(r,35));});};
async function input(label:string,value:string){const control=[...document.querySelectorAll('label')].find(l=>l.firstChild?.textContent?.trim()===label)?.querySelector('input,textarea,select') as HTMLInputElement;expect(control,label).toBeTruthy();await act(async()=>{const proto=control.tagName==='SELECT'?HTMLSelectElement.prototype:control.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value')!.set!.call(control,value);control.dispatchEvent(new Event(control.tagName==='SELECT'?'change':'input',{bubbles:true}));});}
beforeEach(()=>{vi.stubGlobal('crypto',webcrypto);vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('requestAnimationFrame',(fn:FrameRequestCallback)=>setTimeout(()=>fn(0),0));localStorage.clear();sessionStorage.clear();f=new BankTestAuthority();history.replaceState({},'',`/hearthside/experiences/EXP-slow?household=${f.h.householdId}&room=common&mode=present`);host=document.createElement('div');document.body.append(host);root=createRoot(host);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.unstubAllGlobals();});
function draw(memberId='MEM-001',reader:KittyAcceptedCommandReader=f.reader){root.render(createElement(ExperienceBankEntry,{key:memberId,household:f.h,experience:f.h.hearthside!.experiences[0]!,identity:`synthetic:${memberId}`,memberId,connected:true,canStart:true,onCommand:f.command,onReadSubmission:f.status,onReadAcceptedCommand:reader}));}
async function render(){f.onAccepted=()=>draw();await act(async()=>draw());}
async function reload(){await act(async()=>root.unmount());root=createRoot(host);await act(async()=>draw());}
async function reviewCreation(){await click('Choose a bank for this');await click('Create a new shared bank');expect((document.querySelector('input') as HTMLInputElement).value).toBe('A slow weekend');await input('How much (CAD)','120');await click('Review shared bank');expect(f.calls).toHaveLength(0);expect(document.body.textContent).toContain('No money will be moved.');}
describe('actual intention → KittyBankRoom → reviewed connection',()=>{
 it('creates one shared bank, separately confirms its connection and returns focus to the intention',async()=>{await render();const initial=f.h.goals.length;await reviewCreation();await click('Final Confirm');expect(f.calls.map(c=>c.kind)).toEqual(['addGoal']);expect(f.h.goals).toHaveLength(initial+1);expect(f.h.hearthside!.experiences[0]!.references).toEqual([]);await click('Review this connection');expect(document.body.textContent).toContain('Breakfast, a walk and time together.');await click('Final Confirm');expect(f.calls.map(c=>c.kind)).toEqual(['addGoal','commitHearthside']);expect(f.calls[0]!.id).not.toBe(f.calls[1]!.id);expect(f.h.hearthside!.experiences[0]!.references).toEqual([{kind:'bank',id:f.receipts.get(f.calls[0]!.id)!.postedIds[0]}]);await new Promise(r=>setTimeout(r,5));expect(document.activeElement).toBe(button('Choose a bank for this'));expect(document.querySelector('.kitty-room')).toBeNull();});
 it('recovers lost creation and link acknowledgements after reload without another creation or link submission',async()=>{f.hideCreation=true;await render();await reviewCreation();await click('Final Confirm');expect(f.calls).toHaveLength(1);expect(button('Check saved creation')).toBeTruthy();await reload();expect(button('Check saved creation')).toBeTruthy();f.hideCreation=false;await click('Check saved creation');expect(f.calls).toHaveLength(1);f.hideLink=true;await click('Review this connection');await click('Final Confirm');expect(f.calls).toHaveLength(2);await reload();await click('Open saved connection review');f.hideLink=false;await click('Check saved connection');expect(f.calls).toHaveLength(2);expect(f.h.hearthside!.experiences[0]!.references).toHaveLength(1);});
 it('keeps the accepted bank after a rejected link and reviews a new independent link identity',async()=>{await render();await reviewCreation();await click('Final Confirm');f.rejectLink=true;await click('Review this connection');await click('Final Confirm');expect(f.calls).toHaveLength(2);const rejected=f.calls[1]!.id;expect(document.body.textContent).toContain('your bank remains available');await click('Cancel');f.rejectLink=false;await click('Review this connection');await click('Final Confirm');expect(f.calls.filter(c=>c.kind==='addGoal')).toHaveLength(1);expect(f.calls.at(-1)!.id).not.toBe(rejected);expect(f.h.hearthside!.experiences[0]!.references).toHaveLength(1);});
 it('uses the same explicit connection review for an existing shared bank',async()=>{await f.command(h=>addGoal(h,{name:'An existing shared bank',target:'80'}),{confirmationId:crypto.randomUUID()});f.calls=[];const goal=f.h.goals.find(g=>g.shared)!;expect(goal).toBeTruthy();await render();await click('Choose a bank for this');await click('Choose an existing shared bank');await input('Shared bank',goal.id);await click('Review this connection');expect(f.calls).toHaveLength(0);await click('Final Confirm');expect(f.calls.map(c=>c.kind)).toEqual(['commitHearthside']);expect(f.h.hearthside!.experiences[0]!.references).toEqual([{kind:'bank',id:goal.id}]);});
 it('cancels a pending accepted-receipt read when the actor changes, retaining only the original actor’s recovery',async()=>{await render();await reviewCreation();let held=false,aborted=false;const read:KittyAcceptedCommandReader=async(id,signal)=>{held=true;return new Promise((resolve,reject)=>{signal?.addEventListener('abort',()=>{aborted=true;reject(Error('SCOPE_CLOSED'));},{once:true});if(!signal)resolve(f.reader(id));});};f.onAccepted=()=>act(()=>draw('MEM-001',read));await act(async()=>draw('MEM-001',read));await act(async()=>{button('Final Confirm').click();});await vi.waitFor(()=>expect(held).toBe(true));await act(async()=>draw('MEM-002'));expect(aborted).toBe(true);expect(document.body.textContent).not.toContain('Review this connection');expect(f.calls.filter(c=>c.kind==='commitHearthside')).toHaveLength(0);expect([...Object.keys(localStorage)].some(k=>k.includes('bank-create'))).toBe(true);});
 it('can cancel an unsubmitted creation and choose an existing bank without changing a free intention',async()=>{await render();await click('Choose a bank for this');await click('Create a new shared bank');await click('← Back to Hearthside');expect(document.querySelector('.kitty-room')).toBeNull();expect(button('Choose an existing shared bank')).toBeTruthy();expect(f.calls).toHaveLength(0);expect(f.h.hearthside!.experiences[0]!.references).toEqual([]);});
 it('shows a fresh intention review after its words change while creating the bank',async()=>{await render();await reviewCreation();await click('Final Confirm');const id=crypto.randomUUID();await act(async()=>{await f.command(h=>commitHearthside(h,{version:1,id,scope:{environment:h.environment,householdId:h.householdId,memberId:'MEM-001'},operation:{kind:'experience.save',expectedRevision:1,value:{...h.hearthside!.experiences[0]!,revision:2,intention:'Stay home and make soup together.'}}}),{confirmationId:id});});expect(document.body.textContent).toContain('This intention changed');await click('Review this connection');expect(document.querySelector('.guard')?.textContent).toContain('Stay home and make soup together.');await click('Final Confirm');expect(f.calls.filter(c=>c.kind==='addGoal')).toHaveLength(1);expect(f.h.hearthside!.experiences[0]!.references).toHaveLength(1);});
 it('requires Review and a durable confirmation identity in the standalone bank room too',async()=>{f.onAccepted=()=>{};await act(async()=>root.render(createElement(KittyBankRoom,{household:{...f.h,goals:[]},view:'household',memberId:'MEM-001',identity:'standalone',onCommand:f.command,onReadSubmission:f.status,onReadAcceptedCommand:f.reader,onClose:vi.fn()})));await click('＋ New bank');await input('Bank name','Standalone');await input('How much (CAD)','50');await click('Review shared bank');expect(f.calls).toHaveLength(0);await click('Final Confirm');expect(f.calls).toHaveLength(1);expect(f.calls[0]!.id).toMatch(/^[0-9a-f-]{36}$/);expect(document.body.textContent).toContain('The accepted bank is arriving in this view.');expect(button('Review shared bank')).toBeUndefined();});
});
