import {describe,expect,it} from 'vitest';
import {catalogHousehold,addGoal,type Household,type CommitResult} from '../src/core/index.ts';
import {splitForSync} from '../src/core/sync.ts';
import {prepareCommand,type AuthorityState} from '../src/ledgerSync/authority.ts';
import {commandFromCapture,type Scope} from '../src/ledgerSync/protocol.ts';
import {capturedIntent} from '../src/ledgerSync/capture.ts';
import {financialAuditHash} from '../src/core/commandIdentity.ts';
import {canonical} from '../src/ledgerSync/patch.ts';
import {commitHearthside} from '../src/hearthside/commands.ts';
import {emptyHearthside,type SharedExperience} from '../src/hearthside/contracts.ts';
import {acceptedCreatedBank,type BankScope,type KittyAcceptedCommand} from '../src/hearthside/bankReceipt.ts';
import {newBankEnvelope,readBankCreation,saveBankCreation,type BankCreationReview} from '../src/hearthside/bankCreation.ts';
import {acceptedBankLink,assertBankLinkReview,newBankJourney,readBankJourney,reviewBankLink,saveBankJourney} from '../src/hearthside/bankJourney.ts';
const experience:SharedExperience={version:1,id:'EXP-weekend',revision:1,title:'A weekend with room to breathe',intention:'Make breakfast slowly, then walk by the water.',state:'dreaming',horizon:'season',createdBy:'MEM-001',references:[]};
class StorageFixture{values=new Map<string,string>();getItem(key:string){return this.values.get(key)??null;}setItem(key:string,value:string){this.values.set(key,value);}removeItem(key:string){this.values.delete(key);}}
function fixture(){let h=catalogHousehold();h.hearthside={...emptyHearthside(),experiences:[structuredClone(experience)]};const scope:BankScope={identity:'synthetic-account',environment:h.environment,householdId:h.householdId,memberId:'MEM-001'},auth:Scope={environment:scope.environment,householdId:scope.householdId,memberId:scope.memberId,subject:'synthetic-account',role:'owner',expires:Date.now()+60000,aclEpoch:1};const first=splitForSync(h,scope.memberId);let state:AuthorityState={sequence:h.revision,shared:first.shared,personal:new Map(h.members.map(m=>[m.id,splitForSync(h,m.id).personal]))};
 return{scope,get h(){return h;},async accept(fn:(h:Household)=>CommitResult,id:string=crypto.randomUUID()){const p=fn(h),command=await commandFromCapture(capturedIntent(p.household)!,auth,id),a=await prepareCommand(state,command,auth,()=>{});h=a.household;state={sequence:a.receipt.sequence,shared:a.shared,personal:new Map([...state.personal,[scope.memberId,a.personal]])};return{environment:scope.environment,householdId:scope.householdId,memberId:scope.memberId,receipt:a.receipt,household:h} satisfies KittyAcceptedCommand;}};
}
const path=(h:Household)=>`/hearthside/experiences/EXP-weekend?household=${h.householdId}&room=common&mode=present`;
describe('accepted bank identity and separate intention link',()=>{
 it('keeps a free intention unchanged until explicit creation, then links the exact accepted goal without posting money',async()=>{const f=fixture(),before=structuredClone(f.h),j=newBankJourney(f.scope,experience,path(f.h),'hearthside-title');expect(f.h).toEqual(before);const created=await f.accept(h=>addGoal(h,{name:'The same bank name',target:'240',shared:true,ownerMemberId:null,envelope:newBankEnvelope(j.context.purpose)}));const bank=acceptedCreatedBank(created,created.receipt.id,f.scope,'household');expect(created.receipt.commandKind).toBe('addGoal');expect(created.receipt.postedIds).toEqual([bank.id]);expect(f.h.hearthside!.experiences).toEqual(before.hearthside!.experiences);for(const key of ['transactions','fundEvents','fundKittyAllocations','goalContributions','goalPurchases'] as const)expect(f.h[key]??[]).toEqual(before[key]??[]);
 const next={...j,bankId:bank.id,creationId:created.receipt.id};next.link=reviewBankLink(f.h,next);const money=await financialAuditHash(f.h),linked=await f.accept(h=>{assertBankLinkReview(h,next);return commitHearthside(h,{version:1,id:next.link!.id,scope:{environment:f.scope.environment,householdId:f.scope.householdId,memberId:f.scope.memberId},operation:next.link!.operation});},next.link.id);expect(linked.receipt.postedIds).toEqual([]);expect(acceptedBankLink(linked,next)).toBe(true);expect(await financialAuditHash(f.h)).toBe(money);expect(f.h.hearthside!.experiences[0]!.references).toEqual([{kind:'bank',id:bank.id}]);
 });
 it('never guesses a new bank from names, array position, other receipt actors or private goals',async()=>{const f=fixture();await f.accept(h=>addGoal(h,{name:'Same name',target:'10'}));const accepted=await f.accept(h=>addGoal(h,{name:'Same name',target:'10'})),id=accepted.receipt.id,goal=acceptedCreatedBank(accepted,id,f.scope,'household');expect(goal.id).toBe(accepted.receipt.postedIds[0]);for(const bad of [{...accepted,receipt:{...accepted.receipt,actor:'MEM-002'}},{...accepted,householdId:'other'},{...accepted,receipt:{...accepted.receipt,commandKind:'fundGoal'}},{...accepted,receipt:{...accepted.receipt,postedIds:[goal.id,'GOAL-other']}},{...accepted,household:{...accepted.household,goals:accepted.household.goals.filter(g=>g.id!==goal.id)}},{...accepted,household:{...accepted.household,goals:accepted.household.goals.map(g=>g.id===goal.id?{...g,shared:false,ownerMemberId:'MEM-002'}:g)}}])expect(()=>acceptedCreatedBank(bad,id,f.scope,'household')).toThrow();});
 it('requires a new explicit review after the intention or bank meaning changes, preserving the original creation context',async()=>{const f=fixture(),created=await f.accept(h=>addGoal(h,{name:'Weekend',target:'100'})),j={...newBankJourney(f.scope,experience,path(f.h),'hearthside-title'),bankId:created.receipt.postedIds[0]!};j.link=reviewBankLink(f.h,j);const changed={...f.h,hearthside:{...f.h.hearthside!,experiences:[{...experience,revision:2,intention:'A different purpose'}]}};expect(()=>assertBankLinkReview(changed,j)).toThrow('BANK_LINK_REVIEW_CHANGED');expect(()=>assertBankLinkReview(f.h,{...j,link:{...j.link!,operation:{...j.link!.operation,value:{...j.link!.operation.value,references:[...j.link!.operation.value.references,{kind:'bank',id:'HIDDEN-extra'}]}}}})).toThrow('BANK_LINK_REVIEW_CHANGED');const reviewed={...j,link:reviewBankLink(changed,j)};expect(()=>assertBankLinkReview(changed,reviewed)).not.toThrow();expect(reviewed.context.experienceRevision).toBe(1);expect(reviewed.link.operation.expectedRevision).toBe(2);expect(()=>assertBankLinkReview({...f.h,goals:f.h.goals.map(g=>g.id===j.bankId?{...g,targetCents:90000}:g)},j)).toThrow('BANK_LINK_REVIEW_CHANGED');});
 it('rechecks the reviewed bank at authority after handoff while independent paint still composes',async()=>{
  const f=fixture(),created=await f.accept(h=>addGoal(h,{name:'Weekend',target:'100',envelope:newBankEnvelope('Walk by the water')})),j={...newBankJourney(f.scope,experience,path(f.h),'hearthside-title'),bankId:created.receipt.postedIds[0]!};j.link=reviewBankLink(f.h,j);
  const auth:Scope={environment:f.scope.environment,householdId:f.scope.householdId,memberId:f.scope.memberId,subject:f.scope.identity,role:'owner',expires:Date.now()+60000,aclEpoch:1};
  const captured=commitHearthside(f.h,{version:1,id:j.link.id,scope:{environment:f.scope.environment,householdId:f.scope.householdId,memberId:f.scope.memberId},operation:j.link.operation}),command=await commandFromCapture(capturedIntent(captured.household)!,auth,j.link.id);
  expect(command.steps[0]!.resources).toHaveLength(1);
  const state=(h:Household):AuthorityState=>({sequence:h.revision,shared:splitForSync(h,f.scope.memberId).shared,personal:new Map(h.members.map(m=>[m.id,splitForSync(h,m.id).personal]))});
  const original=f.h.goals.find(g=>g.id===j.bankId)!;
  for(const patch of [{targetCents:90000},{name:'Changed name'},{envelope:{...original.envelope!,purpose:'Another intention'}},{shared:false,ownerMemberId:'MEM-002'},{envelope:{...original.envelope!,archivedAt:'2026-09-12T20:00:00Z'}}]){
   const changed={...f.h,goals:f.h.goals.map(g=>g.id===j.bankId?{...g,...patch}:g)};
   await expect(prepareCommand(state(changed),command,auth,()=>{})).rejects.toThrow();
  }
  const painted=structuredClone(f.h),paintedDraft=painted.goals.find(g=>g.id===j.bankId)!.envelope!.studio!.draft!;paintedDraft.paint.base='#aabbcc';
  const accepted=await prepareCommand(state(painted),command,auth,()=>{});
  expect(accepted.household.hearthside!.experiences[0]!.references).toEqual([{kind:'bank',id:j.bankId}]);
  expect(accepted.household.goals.find(g=>g.id===j.bankId)!.envelope!.studio!.draft!.paint.base).toBe('#aabbcc');
 });
 it('persists exact independent creation/link identities and rejects another actor, scope or modified stored creation',async()=>{const f=fixture(),storage=new StorageFixture(),j=newBankJourney(f.scope,experience,path(f.h),'hearthside-title'),review:BankCreationReview={version:1,scope:f.scope,context:j.context,confirmationId:crypto.randomUUID(),input:{name:'Weekend',target:'100',shared:true,ownerMemberId:null,envelope:newBankEnvelope()},attempted:true};saveBankCreation(storage,review);expect(readBankCreation(storage,f.scope,j.context)).toEqual(review);const created=await f.accept(h=>addGoal(h,review.input));j.bankId=created.receipt.postedIds[0]!;j.creationId=created.receipt.id;j.link=reviewBankLink(f.h,j);saveBankJourney(storage,j);expect(readBankJourney(storage,f.scope,experience.id)).toEqual(j);expect(j.link.id).not.toBe(review.confirmationId);expect(readBankJourney(storage,{...f.scope,memberId:'MEM-002'},experience.id)).toBeNull();const source=[...storage.values].find(([key])=>key.startsWith('hearth:bank-create:'))!;storage.setItem(source[0],canonical({...review,input:{...review.input,shared:false,ownerMemberId:'MEM-002'}}));expect(()=>readBankCreation(storage,f.scope,j.context)).toThrow('BANK_REVIEW_INVALID');});
});
