import {expect,it} from 'vitest';
import {createServer} from 'vite';
import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {createGuestRuntime} from './fixtures/hearthsideGuestRuntime.ts';
it('publishes and visits through actual React and guest Worker endpoints, then verifies all themed rooms and breakpoints',async()=>{
 const runtime=await createGuestRuntime(),directory='/tmp/hearthside-guests-proof',errors:string[]=[],evidence:unknown[]=[];await mkdir(directory,{recursive:true});
 const server=await createServer({configFile:false,root:process.cwd(),cacheDir:'/tmp/hearthside-guests-vite',esbuild:{jsx:'automatic'},logLevel:'error',server:{host:'127.0.0.1',port:0},plugins:[{name:'guest-proof',configureServer(vite){vite.middlewares.use(async(req,res,next)=>{if(req.url?.startsWith('/api/hearthside-guests/')){const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.from(chunk));const body=Buffer.concat(chunks);const response=await runtime.mf.dispatchFetch('http://localhost'+req.url,{method:req.method,headers:req.headers as Record<string,string>,...(body.length?{body}: {})});res.statusCode=response.status;response.headers.forEach((value,key)=>res.setHeader(key,value));res.end(Buffer.from(await response.arrayBuffer()));return;}if(req.url==='/__guest_proof'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width, initial-scale=1"><title>Local synthetic guest proof</title><style>body{margin:0}</style></head><body><div id="root"></div><script type="module" src="/test/fixtures/hearthsideGuestProof.tsx"></script></body></html>');return;}next();});}}]});
 await server.listen();const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),address=`http://127.0.0.1:${(server.httpServer!.address() as {port:number}).port}/__guest_proof`;page.setDefaultTimeout(10000);page.on('pageerror',error=>errors.push(error.message));
 const surfaceMatrix=async(name:string)=>{for(const theme of ['classic','taylor','newfoundland']){await page.getByLabel('Test theme').selectOption(theme);for(const width of [320,390,719,720,1100,1440,1920]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+'/'+theme+'/'+width).toBe(true);expect(await page.locator('.guest-visits button,.guest-visits input,.guest-visits select,.guest-visits textarea').evaluateAll(elements=>elements.filter(el=>{const r=el.getBoundingClientRect();return r.width>0&&(r.left< -1||r.right>innerWidth+1);}).map(el=>el.outerHTML)),name+'/'+theme+'/'+width).toEqual([]);evidence.push({surface:name,theme,width,overflow:false,controlsReachable:true});}await page.setViewportSize({width:390,height:1000});await page.screenshot({path:directory+'/'+theme+'-'+name+'-390.png',fullPage:true});const axe=await new AxeBuilder({page}).include('.guest-visits').withTags(['wcag2a','wcag2aa']).analyze();expect(axe.violations.map(v=>v.id),name+'/'+theme).toEqual([]);evidence.push({surface:name,theme,axeViolations:0});}await page.setViewportSize({width:1440,height:1000});await page.getByLabel('Test theme').selectOption('classic');};
 try{
  await runtime.control({target:'source',action:'change',input:{key:'state',value:{media:true}}});await page.addInitScript(()=>{const urls=new Set<string>(),create=URL.createObjectURL.bind(URL),revoke=URL.revokeObjectURL.bind(URL);URL.createObjectURL=blob=>{const url=create(blob);urls.add(url);return url;};URL.revokeObjectURL=url=>{urls.delete(url);revoke(url);};(window as unknown as {guestBlobCount:()=>number}).guestBlobCount=()=>urls.size;});await page.goto(address);await page.getByRole('heading',{name:'Your street has room to grow.'}).waitFor();
  await page.getByLabel('Test participant').selectOption('cara');await page.getByLabel('Name on this card').fill('Cara');await page.route('**/api/hearthside-guests/development/cards',async route=>{const response=await route.fetch();expect(response.status()).toBe(200);await route.abort('failed');await page.unroute('**/api/hearthside-guests/development/cards');});await page.getByRole('button',{name:'Create a calling card'}).click();await page.getByRole('button',{name:'Retry saved request'}).waitFor();await page.getByLabel('Test participant').selectOption('dan');await page.getByRole('heading',{name:'Your street has room to grow.'}).waitFor();expect(await page.getByRole('button',{name:'Retry saved request'}).count()).toBe(0);await page.getByLabel('Test participant').selectOption('cara');await page.getByRole('button',{name:'Retry saved request'}).click();await page.getByRole('button',{name:'Retry saved request'}).waitFor({state:'hidden'});await page.getByLabel('Calling card code',{exact:true}).waitFor();const cardCode=await page.getByLabel('Calling card code',{exact:true}).inputValue();expect(cardCode).toMatch(/^[0-9a-f-]{36}$/);
  await page.getByLabel('Test participant').selectOption('alice');await page.getByRole('button',{name:'Prepare our room'}).click();await page.getByLabel('Room name').fill('Our quiet afternoon');await page.getByLabel('Welcome message').fill('A little time together.');await page.getByLabel('In their own time').check();for(const name of ['A day by the water','Our painted cat','An afternoon together'])await page.getByLabel(name,{exact:true}).check();await page.getByRole('button',{name:'Prepare exact room for review'}).click();await page.getByLabel('I reviewed this exact copied room and its contents.').check();await page.getByRole('button',{name:'Approve this room',exact:true}).click();await page.getByRole('button',{name:'Approve this room',exact:true}).waitFor({state:'hidden'});
  await page.getByLabel('Test participant').selectOption('bob');await page.getByRole('button',{name:'Prepare our room'}).click();await page.getByLabel('I reviewed this exact copied room and its contents.').check();await page.getByRole('button',{name:'Approve this room',exact:true}).click();await page.getByRole('button',{name:'Approve this room',exact:true}).waitFor({state:'hidden'});
  await page.getByLabel('Test participant').selectOption('alice');await page.getByRole('button',{name:'Prepare our room'}).click();await page.getByRole('button',{name:'Open approved room'}).click();await page.getByLabel('Calling card code',{exact:true}).fill(cardCode);await page.getByRole('button',{name:'Prepare invitation review'}).click();await page.getByLabel('I reviewed this recipient and expiry for this exact room.').check();await page.getByRole('button',{name:'Approve invitation',exact:true}).click();await page.getByRole('button',{name:'Approve invitation',exact:true}).waitFor({state:'hidden'});
  await page.getByLabel('Test participant').selectOption('bob');await page.getByRole('button',{name:'Prepare our room'}).click();await page.getByLabel('I reviewed this recipient and expiry for this exact room.').check();await page.getByRole('button',{name:'Approve invitation',exact:true}).click();await page.getByRole('button',{name:'Approve invitation',exact:true}).waitFor({state:'hidden'});await page.getByRole('button',{name:'Add approved invitation to their street'}).click();await page.getByRole('button',{name:'Revoke invitation',exact:true}).waitFor();await page.screenshot({path:directory+'/joint-review.png',fullPage:true});await surfaceMatrix('publishing');
  await page.getByLabel('Test participant').selectOption('cara');await page.getByRole('button',{name:'Visit room'}).waitFor();await page.screenshot({path:directory+'/street-1440.png',fullPage:true});await surfaceMatrix('street');await page.getByRole('button',{name:'Visit room'}).click();await page.getByLabel('Name shown during this visit').fill('Cara');await page.getByRole('button',{name:'Enter room',exact:true}).click();await page.getByText('Here now: Cara').waitFor();await page.getByRole('button',{name:'Release a firefly'}).click();await page.locator('.guest-toy--firefly').waitFor();await page.locator('.hsr-object-index').getByRole('button').filter({hasText:'An afternoon together'}).click();await page.getByText('I remember your laugh.').waitFor();await page.getByAltText('A reviewed synthetic pixel').waitFor();expect(await page.evaluate(()=>(window as unknown as {guestBlobCount:()=>number}).guestBlobCount())).toBe(1);await page.waitForFunction(()=>document.querySelector('.guest-presence')?.textContent?.includes('Cara'));await page.waitForTimeout(3200);expect(await page.getByText('I remember your laugh.').count()).toBe(1);await page.screenshot({path:directory+'/visit-1440.png',fullPage:true});
  await page.getByLabel('Test participant').selectOption('dan');await page.getByRole('heading',{name:'Your street has room to grow.'}).waitFor();expect(await page.getByText('I remember your laugh.').count()).toBe(0);expect(await page.evaluate(()=>(window as unknown as {guestBlobCount:()=>number}).guestBlobCount())).toBe(0);expect(await page.getByRole('button',{name:'Visit room'}).count()).toBe(0);
  await page.getByLabel('Test participant').selectOption('cara');await page.getByRole('button',{name:'Visit room'}).waitFor();await page.getByRole('button',{name:'Revoke card and visits'}).click();await page.getByRole('heading',{name:'Your street has room to grow.'}).waitFor();
  await page.getByLabel('Isolated room matrix').check();
  for(const theme of ['classic','taylor','newfoundland']){await page.getByLabel('Test theme').selectOption(theme);for(const room of ['common','studio','conservatory','theatre']){await page.getByLabel('Test room').selectOption(room);for(const width of [320,390,719,720,1100,1440,1920]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);const bad=await page.locator('.guest-visits button').evaluateAll(buttons=>buttons.filter(el=>{const r=el.getBoundingClientRect();return r.width>0&&(r.left<0||r.right>innerWidth+1||r.height<43);}).map(el=>({text:el.textContent,rect:el.getBoundingClientRect().toJSON()})));expect(bad,`${theme}/${room}/${width}`).toEqual([]);evidence.push({theme,room,width,overflow:false,controlsReachable:true});if([390,1440].includes(width))await page.screenshot({path:`${directory}/${theme}-${room}-${width}.png`,fullPage:true});}}await page.setViewportSize({width:390,height:1000});const axe=await new AxeBuilder({page}).include('.guest-visits').withTags(['wcag2a','wcag2aa']).analyze();expect(axe.violations.map(v=>v.id),theme).toEqual([]);evidence.push({theme,axeViolations:0});}
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>document.documentElement.style.fontSize='200%');await page.locator('.hsr-object-index').getByRole('button').filter({hasText:'Painted cat'}).focus();await page.keyboard.press('Enter');await page.getByRole('region',{name:'Painted cat',exact:true}).waitFor();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:directory+'/newfoundland-reduced-large.png',fullPage:true});expect(errors).toEqual([]);evidence.push({journey:'joint publish, invitation, cross-household visit, toy, scope switch and revoke',passed:true});await writeFile(directory+'/evidence.json',JSON.stringify(evidence,null,2));
 }catch(error){await writeFile(directory+'/failure.html',await page.content());await page.screenshot({path:directory+'/failure.png',fullPage:true});throw error;}finally{await browser.close();await server.close();await runtime.mf.dispose();}
},120000);
