import {describe,expect,it,vi} from 'vitest';
import {NativeWidgetController,reviewNativeWidget,type NativeWidgetPlugin} from '../src/hearthside/nativeWidget.ts';
const scope={environment:'development' as const,householdId:'house-a',memberId:'a',subject:'google-a'};
const selection={version:1 as const,designId:'d',pieceId:'p',revision:0,pngBase64:'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j8e0AAAAASUVORK5CYII='};
const plugin=():NativeWidgetPlugin=>({widgetAvailability:async()=>({supported:true,reason:''}),setWidget:vi.fn(async()=>{}),clearWidget:vi.fn(async()=>{})});
describe('explicit native widget publication',()=>{
 it('requires exact image/immutable revision and current scope review',async()=>{const p=plugin(),c=new NativeWidgetController(p);await c.enterScope(scope);const r=await reviewNativeWidget(scope,selection);await c.select(scope,selection,r.reviewDigest);expect(p.setWidget).toHaveBeenCalledOnce();expect(JSON.stringify(vi.mocked(p.setWidget).mock.calls)).not.toMatch(/house-a|google-a|memberId|designId|backing|amount/);await expect(c.select(scope,{...selection,revision:1},r.reviewDigest)).rejects.toThrow('Review');});
 it('refuses financial payload extensions and clears before a new household can opt in',async()=>{const p=plugin(),c=new NativeWidgetController(p);await c.enterScope(scope);await expect(reviewNativeWidget(scope,{...selection,backing:42} as typeof selection)).rejects.toThrow();const r=await reviewNativeWidget(scope,selection);await c.enterScope({...scope,householdId:'house-b'});await expect(c.select(scope,selection,r.reviewDigest)).rejects.toThrow('Review');expect(p.clearWidget).toHaveBeenCalledTimes(2);});
 it('serializes a late accepted image ahead of sign-out clear',async()=>{const p=plugin();let finish!:()=>void;const held=new Promise<void>(r=>{finish=r;});p.setWidget=vi.fn(()=>held);const c=new NativeWidgetController(p);await c.enterScope(scope);const r=await reviewNativeWidget(scope,selection);const write=c.select(scope,selection,r.reviewDigest);await vi.waitFor(()=>expect(p.setWidget).toHaveBeenCalledOnce());const clear=c.clear();finish();await write;await clear;expect(p.clearWidget).toHaveBeenCalledTimes(2);expect(vi.mocked(p.clearWidget).mock.invocationCallOrder.at(-1)).toBeGreaterThan(vi.mocked(p.setWidget).mock.invocationCallOrder[0]!);});
 it('retries a failed scope clear and refuses selection until clearing succeeds',async()=>{const p=plugin(),c=new NativeWidgetController(p);await c.enterScope(scope);const next={...scope,householdId:'b'},r=await reviewNativeWidget(next,selection);p.clearWidget=vi.fn().mockRejectedValueOnce(new Error('locked')).mockResolvedValue(undefined);await expect(c.enterScope(next)).rejects.toThrow('locked');await expect(c.select(next,selection,r.reviewDigest)).rejects.toThrow('Review');await c.enterScope(next);await c.select(next,selection,r.reviewDigest);expect(p.setWidget).toHaveBeenCalledOnce();});
 it('does not silently report a failed removal as cleared',async()=>{const p=plugin(),c=new NativeWidgetController(p);await c.enterScope(scope);p.clearWidget=vi.fn(async()=>{throw new Error('locked');});await expect(c.clear()).rejects.toThrow('locked');});
});
