import {describe,expect,it} from 'vitest';
import {catalogHousehold} from '../src/core/index.ts';
import {keepWinAsMemory,dismissWin,type Win} from '../src/core/chapters.ts';
import {financialAuditHash} from '../src/core/commandIdentity.ts';
import {splitForSync,assembleHousehold} from '../src/core/sync.ts';
import {restoreArchive,seal,type Checkpoint,type ArchiveRecord,type Sealed} from '../src/ledgerSync/backup.ts';
import {capturedIntent} from '../src/ledgerSync/capture.ts';
import {commandFromCapture,type Scope} from '../src/ledgerSync/protocol.ts';
import {prepareCommand,type AuthorityState} from '../src/ledgerSync/authority.ts';
import {commitHearthside,hearthsideOperationalCollection,type HearthsideOperation} from '../src/hearthside/commands.ts';
import {emptyHearthside,decodeMemory,memoryKeptByEveryone} from '../src/hearthside/contracts.ts';
import {memoryCompositionDigest} from '../src/hearthside/memoryPublication.ts';
import {adoptWinMemory,winAdoptionOperation,winMemoryId,winSourceDigest,requireStableWinProvenance,rejectLegacyWinPublication} from '../src/hearthside/winMemory.ts';
import {memoryCaptionRows,memoryForStoryFile} from '../src/hearthside/winMemoryCaptions.ts';
import {winPublicCaption} from '../src/hearthside/winMemoryProvenance.ts';
import {currentSharedLifeRecords} from '../src/hearthside/creativeContinuity.ts';
const win=():Win=>({version:1,id:'WIN-old',chapterId:null,level:'first',title:'The quiet Sunday',evidenceRefs:['private-old-evidence'],shownAt:'2026-09-01T12:00:00.000Z',fadedAt:null,keptByMemberIds:['MEM-001','MEM-002'],authoredNote:'We heard the rain while the kettle warmed.',hideAmounts:false,updatedAt:'2026-09-01T12:00:00.000Z'});
function fixture(){const h=catalogHousehold();h.wins=[win()];h.hearthside=emptyHearthside();return h;}
describe('one canonical memory for an earlier Win',()=>{
 it('does not execute an accessor in either authority dispatch or operational projection',()=>{const h=fixture();let calls=0;const operation={kind:'memory.adopt-win'};Object.defineProperty(operation,'kind',{get:()=>{calls++;return 'experience.add-task';}});expect(hearthsideOperationalCollection(operation)).toBeNull();expect(()=>commitHearthside(h,{version:1,id:crypto.randomUUID(),scope:{environment:h.environment,householdId:h.householdId,memberId:'MEM-001'},operation:operation as HearthsideOperation})).toThrow('HEARTHSIDE_INVALID_OBJECT');expect(calls).toBe(0);});
 it('adopts exact history without inventing authors, approvals, photos or money',async()=>{const h=fixture(),source=h.wins![0]!,before=structuredClone(source),op=winAdoptionOperation(h,source),memory=adoptWinMemory(h,'MEM-001',op);expect(memory.id).toBe(winMemoryId(h,source.id));expect(memory.hideAmounts).toBe(true);expect(memory.media).toEqual([]);expect(memory.designs).toEqual([]);expect(memory.recollections).toEqual([]);expect(memory.approvals).toEqual([]);expect(memory.legacySource).toMatchObject({unattributedCaption:source.authoredNote,historicalKeptMemberIds:source.keptByMemberIds});expect(source).toEqual(before);expect(memoryKeptByEveryone(memory,['MEM-001','MEM-002'])).toBe(false);expect(JSON.stringify(memory)).not.toContain('private-old-evidence');});
 it('returns the existing identity after source deletion/financial restore and never revives withdrawal',()=>{const h=fixture(),op=winAdoptionOperation(h,h.wins![0]!);const memory=adoptWinMemory(h,'MEM-001',op);h.hearthside!.memories=[{...memory,revision:4,withdrawn:true}];h.wins=[];expect(adoptWinMemory(h,'MEM-002',op)).toEqual(h.hearthside!.memories[0]);const restored={...fixture(),environment:h.environment,householdId:h.householdId,...currentSharedLifeRecords(h)};expect(adoptWinMemory(restored,'MEM-001',op).withdrawn).toBe(true);});
 it('rejects changed/missing Win evidence, wrong scope identities, inactive authors and forged provenance',()=>{const h=fixture(),op=winAdoptionOperation(h,h.wins![0]!);h.wins![0]!.authoredNote='Changed';expect(()=>adoptWinMemory(h,'MEM-001',op)).toThrow('WIN_CHANGED');expect(()=>adoptWinMemory(h,'outsider',op)).toThrow('MEMBER_REQUIRED');expect(()=>adoptWinMemory(h,'MEM-001',{...op,memoryId:'different'})).toThrow('IDENTITY_CHANGED');h.wins=[];expect(()=>adoptWinMemory(h,'MEM-001',op)).toThrow('WIN_MISSING');const original=fixture(),memory=adoptWinMemory(original,'MEM-001',winAdoptionOperation(original,original.wins![0]!));expect(()=>requireStableWinProvenance(undefined,memory)).toThrow('ADOPTION_REQUIRED');expect(()=>requireStableWinProvenance(memory,{...memory,legacySource:undefined})).toThrow('IMMUTABLE');});
 it('hashes every visible legacy source field and excludes history identities from guest/story captions',async()=>{const h=fixture(),memory=adoptWinMemory(h,'MEM-001',winAdoptionOperation(h,h.wins![0]!)),hash=await memoryCompositionDigest(memory);for(const source of [{...memory.legacySource!,unattributedCaption:'Another note'},{...memory.legacySource!,historicalKeptMemberIds:[]},{...memory.legacySource!,sourceDigest:'0'.repeat(64)}])expect(await memoryCompositionDigest({...memory,legacySource:source})).not.toBe(hash);expect(memoryCaptionRows(memory,()=>{throw Error('No invented speaker');})).toEqual([{memberId:null,label:'Earlier note · author not recorded',text:win().authoredNote}]);const publicCopy=JSON.stringify([winPublicCaption(memory.legacySource),memoryForStoryFile(memory)]);expect(publicCopy).not.toContain('WIN-old');expect(publicCopy).not.toContain('MEM-001');expect(publicCopy).not.toContain('historicalKeptMemberIds');expect(publicCopy).toContain(win().authoredNote);expect(decodeMemory(memory)).toEqual(memory);});
 it('requires two new exact choices and invalidates them after an amount or caption edit through the real command authority',async()=>{
  let h=fixture();const original=h,before=await financialAuditHash(h),first=splitForSync(h,'MEM-001');let state:AuthorityState={sequence:h.revision,shared:first.shared,personal:new Map(h.members.map(m=>[m.id,splitForSync(h,m.id).personal]))};
  async function accept(actor:string,operation:HearthsideOperation){const id=crypto.randomUUID(),scope:Scope={environment:h.environment,householdId:h.householdId,memberId:actor,subject:`synthetic-${actor}`,role:'owner',expires:Date.now()+60000,aclEpoch:1};const result=commitHearthside(h,{version:1,id,scope:{environment:h.environment,householdId:h.householdId,memberId:actor},operation});const c=await commandFromCapture(capturedIntent(result.household)!,scope,id);const accepted=await prepareCommand(state,c,scope,()=>{});h=accepted.household;state={sequence:accepted.receipt.sequence,shared:accepted.shared,personal:new Map([...state.personal,[actor,accepted.personal]])};expect(accepted.receipt.postedIds).toEqual([]);}
  const op=winAdoptionOperation(h,h.wins![0]!);await accept('MEM-001',op);await accept('MEM-002',op);expect(h.hearthside!.memories).toHaveLength(1);let memory=h.hearthside!.memories[0]!;expect(memory.approvals).toEqual([]);
  await accept('MEM-001',{kind:'memory.keep',id:memory.id,expectedRevision:1});await accept('MEM-002',{kind:'memory.keep',id:memory.id,expectedRevision:1});expect(memoryKeptByEveryone(h.hearthside!.memories[0]!,['MEM-001','MEM-002'])).toBe(true);
  memory=h.hearthside!.memories[0]!;await accept('MEM-001',{kind:'memory.compose',expectedRevision:1,value:{...memory,revision:2,approvals:[],hideAmounts:false,recollections:[{memberId:'MEM-001',text:'My own later recollection.'}]}});expect(h.hearthside!.memories[0]!.approvals).toEqual([]);expect(h.hearthside!.memories[0]!.legacySource).toEqual(memory.legacySource);expect(await financialAuditHash(h)).toBe(before);expect(h.wins).toEqual(original.wins);
  expect(()=>keepWinAsMemory(h,{memberId:'MEM-001',winId:win().id})).toThrow('UPDATE_REQUIRED');expect(()=>rejectLegacyWinPublication([{kind:'keepWinAsMemory'}])).toThrow('UPDATE_REQUIRED');expect(()=>rejectLegacyWinPublication([{kind:'dismissWin'}])).not.toThrow();
 });
 it('recovers the same withdrawn adoption and receipts from a pre-adoption checkpoint plus complete shared history',async()=>{
  let h=fixture();const scope:Scope={environment:h.environment,householdId:h.householdId,memberId:'MEM-001',subject:'synthetic',role:'owner',expires:Date.now()+60000,aclEpoch:1};const first=splitForSync(h,scope.memberId);let state:AuthorityState={sequence:h.revision,shared:first.shared,personal:new Map(h.members.map(m=>[m.id,splitForSync(h,m.id).personal]))};
  const checkpoint=await seal<Checkpoint>({version:2,scope:`${h.environment}/${h.householdId}`,authorityInstance:crypto.randomUUID(),sequence:state.sequence,shared:state.shared,personal:[...state.personal],receipts:[]}),records:Sealed<ArchiveRecord>[]=[];
  const adoption=winAdoptionOperation(h,h.wins![0]!);
  for(const operation of [adoption,{kind:'memory.withdraw' as const,id:adoption.memoryId,expectedRevision:1}]){
   const id=crypto.randomUUID(),preview=commitHearthside(h,{version:1,id,scope:{environment:scope.environment,householdId:scope.householdId,memberId:scope.memberId},operation}),command=await commandFromCapture(capturedIntent(preview.household)!,scope,id),accepted=await prepareCommand(state,command,scope,()=>{});
   records.push(await seal({scope:checkpoint.data.scope,authorityInstance:checkpoint.data.authorityInstance,event:accepted.event,receipt:accepted.receipt}));h=accepted.household;state={sequence:accepted.receipt.sequence,shared:accepted.shared,personal:new Map([...state.personal,[scope.memberId,accepted.personal]])};
  }
  const recovered=await restoreArchive(checkpoint.data.scope,checkpoint,records),replica=assembleHousehold(recovered.shared,recovered.personal[0]![1]);expect(replica.hearthside!.memories).toEqual(h.hearthside!.memories);expect(recovered.receipts).toHaveLength(2);expect(adoptWinMemory(replica,scope.memberId,adoption).withdrawn).toBe(true);expect(replica.hearthside!.memories).toHaveLength(1);
  await expect(restoreArchive(checkpoint.data.scope,checkpoint,[records[1]!])).rejects.toThrow('ARCHIVE_GAP');
 });
 it('keeps dismissal and memory withdrawal independent',()=>{const h=fixture();h.wins![0]!.keptByMemberIds=[];const op=winAdoptionOperation(h,h.wins![0]!);h.hearthside!.memories=[adoptWinMemory(h,'MEM-001',op)];const dismissed=dismissWin(h,{memberId:'MEM-001',winId:win().id}).household;expect(dismissed.hearthside!.memories).toEqual(h.hearthside!.memories);expect(dismissed.wins![0]!.fadedAt).not.toBeNull();});
 it('accepts historical ISO variants while preserving the exact original source digest',()=>{const h=fixture();h.wins![0]!.shownAt='2026-09-01T12:00:00-04:00';const op=winAdoptionOperation(h,h.wins![0]!),memory=adoptWinMemory(h,'MEM-001',op);expect(memory.legacySource!.recordedAt).toBe('2026-09-01T16:00:00.000Z');expect(memory.legacySource!.sourceDigest).toBe(op.expectedWinDigest);expect(h.wins![0]!.shownAt).toBe('2026-09-01T12:00:00-04:00');});
 it('does not turn an unknown fallback date or routine acknowledgement into made-up memorabilia',()=>{const h=fixture();h.wins![0]!.shownAt='1970-01-01T00:00:00.000Z';expect(adoptWinMemory(h,'MEM-001',winAdoptionOperation(h,h.wins![0]!)).date).toBeNull();h.wins![0]!.level='acknowledgment';expect(()=>adoptWinMemory(h,'MEM-001',winAdoptionOperation(h,h.wins![0]!))).toThrow('WIN_MISSING');expect(winSourceDigest(win())).not.toBe(winSourceDigest({...win(),hideAmounts:true}));});
});
