import {afterEach,describe,expect,it,vi} from 'vitest';
import {clearSupabaseSession,installNativeSupabaseAuth,loadSupabaseSession,resetNativeSupabaseAuthForTests,resetSupabaseAuthConcurrencyForTests,saveSupabaseSession,setSupabaseSessionStore,startSupabaseGoogleSignIn,type HearthSupabaseSession} from '../src/auth/supabaseSession.ts';
import {NativeSessionStore,nativeSessionKey,validateNativeSession} from '../src/hearthside/nativeSessionStore.ts';
import {NativeAuthController,NATIVE_AUTH_PENDING_KEY,nativeCallbackCode,nativeAuthReturnPath,type NativeAuthPlugin} from '../src/hearthside/nativeAuth.ts';
const config={supabaseUrl:'https://example.supabase.co',publishableKey:'public-anon-key'},environment='development' as const;
const token=(user='user-a',issuer=config.supabaseUrl)=>`head.${btoa(JSON.stringify({iss:`${issuer}/auth/v1`,sub:user,session_id:`session-${user}`,email:`${user}@example.test`,exp:2000000000,user_metadata:{provider_id:`google-${user}`}}))}.signature`;
const session=(user='user-a'):HearthSupabaseSession=>({accessToken:token(user),refreshToken:`refresh-${user}`,userId:user,sessionId:`session-${user}`,email:`${user}@example.test`,googleSubject:`google-${user}`,displayName:'Person',expiresAt:2000000000000});
function deferred<T>(){let resolve!:(value:T)=>void;let reject!:(e:Error)=>void;const promise=new Promise<T>((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};}
class Plugin implements NativeAuthPlugin {
 async authStorageVersion(){return{version:2 as const};}
 values=new Map<string,string>();callback:string|null=null;auth=deferred<{callbackUrl:string}>();request:{url:string;state:string}|null=null;failWrite:string|null=null;afterWriteFail=false;
 async secureGet({key}:{key:string}){return{value:this.values.get(key)??null};}
 async secureSet({key,value}:{key:string;value:string}){if(this.failWrite===key&&!this.afterWriteFail)throw new Error('locked');this.values.set(key,value);if(this.failWrite===key)throw new Error('lost ack');}
 async secureRemove({key}:{key:string}){this.values.delete(key);}
 async authenticate(input:{url:string;state:string}){this.request=input;return this.auth.promise;}
 async peekAuthCallback(){return{callbackUrl:this.callback};}
 async acknowledgeAuthCallback({callbackUrl}:{callbackUrl:string}){if(this.callback&&this.callback!==callbackUrl)throw new Error('changed');this.callback=null;}
 async cancelAuthentication(){this.callback=null;}
 return(userCode='one-time-code'){const redirect=new URL(new URL(this.request!.url).searchParams.get('redirect_to')!);redirect.searchParams.set('code',userCode);this.callback=redirect.toString();this.auth.resolve({callbackUrl:this.callback});return this.callback;}
}
const response=(user='user-a')=>new Response(JSON.stringify({access_token:token(user),refresh_token:`refresh-${user}`,user:{id:user,email:`${user}@example.test`,user_metadata:{provider_id:`google-${user}`}}}),{status:200});
async function setup(fetcher:typeof fetch=vi.fn(async()=>response())){const plugin=new Plugin(),store=new NativeSessionStore(plugin,config.supabaseUrl),controller=new NativeAuthController(plugin,()=>config,fetcher,()=>1700000000000);installNativeSupabaseAuth(store,controller);await store.hydrate();return{plugin,store,controller};}
afterEach(()=>{resetNativeSupabaseAuthForTests();resetSupabaseAuthConcurrencyForTests();setSupabaseSessionStore(null);});
describe('native secure session projection',()=>{
 it('cannot read browser credentials before secure hydration or on a secure failure',async()=>{const plaintext={getItem:vi.fn(()=>JSON.stringify(session())),setItem:vi.fn(),removeItem:vi.fn()};setSupabaseSessionStore(plaintext);const plugin=new Plugin(),store=new NativeSessionStore(plugin,config.supabaseUrl);installNativeSupabaseAuth(store,{start:()=>false,cancel:async()=>{}});expect(()=>loadSupabaseSession(environment)).toThrow('not loaded');await store.hydrate();expect(loadSupabaseSession(environment)).toBeNull();expect(plaintext.getItem).not.toHaveBeenCalled();});
 it('publishes memory only after a durable secure write and recovers lost acknowledgement',async()=>{const {plugin,store}=await setup();const hold=deferred<void>(),original=plugin.secureSet.bind(plugin);plugin.secureSet=async input=>{await hold.promise;await original(input);};const write=saveSupabaseSession(environment,session());expect(store.load(environment)).toBeNull();hold.resolve();await write;expect(store.load(environment)?.userId).toBe('user-a');plugin.secureSet=original;plugin.failWrite=nativeSessionKey(environment);plugin.afterWriteFail=true;await saveSupabaseSession(environment,session('user-b'));expect(store.load(environment)?.userId).toBe('user-b');});
 it('rejects wrong issuer, environment, and contradictory Google identity on restart',async()=>{const {plugin}=await setup();await saveSupabaseSession(environment,session());const value=JSON.parse(plugin.values.get(nativeSessionKey(environment))!);value.environment='production';plugin.values.set(nativeSessionKey(environment),JSON.stringify(value));await expect(new NativeSessionStore(plugin,config.supabaseUrl).hydrate()).rejects.toThrow('scope');expect(()=>validateNativeSession({...session(),googleSubject:'another'},config.supabaseUrl)).toThrow('subject');expect(()=>validateNativeSession(session(),'https://other.supabase.co')).toThrow('issuer');});
 it('keeps development and production records separate and durable tombstones prevent resurrection',async()=>{const {plugin}=await setup();await saveSupabaseSession(environment,session());await saveSupabaseSession('production',session('user-b'));await clearSupabaseSession(environment);const cold=new NativeSessionStore(plugin,config.supabaseUrl);await cold.hydrate();expect(cold.load(environment)).toBeNull();expect(cold.load('production')?.userId).toBe('user-b');expect(JSON.parse(plugin.values.get(nativeSessionKey(environment))!).session).toBeNull();});
 it('does not claim failed clearing and runs identity cleanup before publishing another account',async()=>{const plugin=new Plugin(),cleanup=vi.fn(async()=>{}),store=new NativeSessionStore(plugin,config.supabaseUrl,cleanup);await store.hydrate();await store.save(environment,session());plugin.failWrite=nativeSessionKey(environment);await expect(store.clear(environment)).rejects.toThrow('locked');expect(store.load(environment)?.userId).toBe('user-a');expect(cleanup).toHaveBeenCalledTimes(2);});
});
describe('system-browser PKCE with durable recovery',()=>{
 it('uses S256 with a secure verifier and succeeds only after session durability',async()=>{const fetcher=vi.fn(async function(this:unknown,_input:RequestInfo|URL,_init?:RequestInit){expect(this).toBeUndefined();return response();}),{plugin,controller}=await setup(fetcher);expect(startSupabaseGoogleSignIn(environment,'https://kitchen.test',config)).toBe(true);await vi.waitFor(()=>expect(plugin.request).not.toBeNull());const url=new URL(plugin.request!.url),pending=JSON.parse(plugin.values.get(NATIVE_AUTH_PENDING_KEY)!);expect(url.searchParams.get('code_challenge_method')).toBe('s256');expect(url.toString()).not.toContain(pending.verifier);expect(pending.verifier).toHaveLength(43);plugin.return();await vi.waitFor(()=>expect(controller.getStatus().phase).toBe('complete'));expect(loadSupabaseSession(environment)?.userId).toBe('user-a');expect(JSON.parse(String(fetcher.mock.calls[0]?.[1]?.body))).toEqual({auth_code:'one-time-code',code_verifier:pending.verifier});expect(plugin.values.has(NATIVE_AUTH_PENDING_KEY)).toBe(false);expect(controller.takeCompletion()).toBe(environment);expect(controller.takeCompletion()).toBeNull();});
 it('recovers a cold callback without consuming it before token/session storage',async()=>{const {plugin,controller}=await setup();controller.start(environment,config,{});await vi.waitFor(()=>expect(plugin.request).not.toBeNull());const redirect=new URL(new URL(plugin.request!.url).searchParams.get('redirect_to')!);redirect.searchParams.set('code','cold');plugin.callback=redirect.toString();const coldStore=new NativeSessionStore(plugin,config.supabaseUrl),cold=new NativeAuthController(plugin,()=>config,vi.fn(async()=>response()),()=>1700000000000);await coldStore.hydrate();installNativeSupabaseAuth(coldStore,cold);await cold.recover();expect(cold.getStatus().phase).toBe('complete');expect(plugin.callback).toBeNull();});
 it('restarts after tokens were received but session storage failed, without reusing the code',async()=>{const fetcher=vi.fn(async()=>response()),{plugin,controller}=await setup(fetcher);plugin.failWrite=nativeSessionKey(environment);controller.start(environment,config,{});await vi.waitFor(()=>expect(plugin.request).not.toBeNull());plugin.return();await vi.waitFor(()=>expect(controller.getStatus().phase).toBe('error'));expect(JSON.parse(plugin.values.get(NATIVE_AUTH_PENDING_KEY)!).phase).toBe('received');expect(plugin.callback).not.toBeNull();plugin.failWrite=null;const store=new NativeSessionStore(plugin,config.supabaseUrl),coldFetch=vi.fn(async()=>response()),cold=new NativeAuthController(plugin,()=>config,coldFetch,()=>1700000000000);await store.hydrate();installNativeSupabaseAuth(store,cold);await cold.recover();expect(coldFetch).not.toHaveBeenCalled();expect(loadSupabaseSession(environment)?.userId).toBe('user-a');});
 it('rejects foreign issuer/account and never follows callback environment guesses',async()=>{const {plugin,controller}=await setup(vi.fn(async()=>response('user-b')));await saveSupabaseSession(environment,session());controller.start(environment,config,{});await vi.waitFor(()=>expect(plugin.request).not.toBeNull());plugin.return();await vi.waitFor(()=>expect(controller.getStatus().phase).toBe('error'));expect(loadSupabaseSession(environment)?.userId).toBe('user-a');const p=JSON.parse(plugin.values.get(NATIVE_AUTH_PENDING_KEY)!);expect(()=>nativeCallbackCode(`hearthside://auth/callback?state=${p.state}&hearthAuthEnv=production&code=x`,p)).toThrow('environment');});
 it('permits a deliberate account switch and blocks overlapping sign-ins',async()=>{const {plugin,controller}=await setup(vi.fn(async()=>response('user-b')));await saveSupabaseSession(environment,session());expect(controller.start(environment,config,{selectAccount:true})).toBe(true);expect(controller.start('production',config,{})).toBe(false);await vi.waitFor(()=>expect(plugin.request).not.toBeNull());expect(new URL(plugin.request!.url).searchParams.get('prompt')).toBe('select_account');plugin.return();await vi.waitFor(()=>expect(controller.getStatus().phase).toBe('complete'));expect(loadSupabaseSession(environment)?.userId).toBe('user-b');});
 it('cancels an exchange before a late token response and retains no recoverable credentials',async()=>{const network=deferred<Response>(),{plugin,controller}=await setup(vi.fn(()=>network.promise));controller.start(environment,config,{});await vi.waitFor(()=>expect(plugin.request).not.toBeNull());plugin.return();await vi.waitFor(()=>expect(controller.getStatus().phase).toBe('finishing'));await clearSupabaseSession(environment);network.resolve(response());await Promise.resolve();await controller.recover();expect(loadSupabaseSession(environment)).toBeNull();expect(JSON.parse(plugin.values.get(NATIVE_AUTH_PENDING_KEY)!).phase).toBe('cancelled');});
 it('preserves the own-auth street return through cold recovery and rejects external return paths',async()=>{const {plugin,controller}=await setup();controller.start(environment,config,{returnPath:'/hearthside/street'});await vi.waitFor(()=>expect(plugin.request).not.toBeNull());plugin.return();await vi.waitFor(()=>expect(controller.getStatus().phase).toBe('complete'));expect(controller.takeReturnPath()).toBe('/hearthside/street');for(const path of ['//example.test','/hearthside/street#access_token=x','/hearthside/street?refresh_token=x','/untrusted'])expect(()=>nativeAuthReturnPath(path)).toThrow();});
 it('can durably cancel a corrupted pending record without reading browser credentials',async()=>{const {plugin,controller}=await setup();plugin.values.set(NATIVE_AUTH_PENDING_KEY,'corrupt');await controller.cancel(environment);expect(plugin.values.has(NATIVE_AUTH_PENDING_KEY)).toBe(false);expect(controller.getStatus().phase).toBe('idle');});
 it('rejects duplicate parameters, fragments and bearer-token returns',()=>{const p={environment,state:'a'.repeat(43)},good=`hearthside://auth/callback?state=${p.state}&hearthAuthEnv=development&code=x`;for(const url of [good+'&code=y',good+'#access_token=z',good+'&access_token=z',good.replace('auth/','evil/'),good.replace('hearthside:','https:')])expect(()=>nativeCallbackCode(url,p)).toThrow();});
 it('preserves callbacks and pending verifier after an uncertain one-time exchange',async()=>{const {plugin,controller}=await setup(vi.fn(async()=>{throw new Error('offline');}));controller.start(environment,config,{});await vi.waitFor(()=>expect(plugin.request).not.toBeNull());plugin.return();await vi.waitFor(()=>expect(controller.getStatus().phase).toBe('error'));expect(plugin.callback).not.toBeNull();expect(JSON.parse(plugin.values.get(NATIVE_AUTH_PENDING_KEY)!).phase).toBe('exchanging');expect(loadSupabaseSession(environment)).toBeNull();});
});
