import {describe,it,expect,vi} from 'vitest';
import {FURNITURE_ROOMS,captureRoomFurniture,decodeRoomFurniture,decodeFurniturePlacements,decodeFurnitureMove,applyFurnitureMove,roomFurnitureCatalogue,roomFurnitureOffset,type FurniturePlacement} from '../src/hearthside/roomFurniture.ts';
import {captureGuestSources,validateGuestSources,type GuestSourceCatalogue} from '../src/hearthside/guestProjection.ts';
import {decodeGuestArrangement} from '../src/hearthside/guestContracts.ts';
describe('canonical nonfinancial furniture',()=>{
 it('has complete stable semantic defaults for every room and exact safe offsets',()=>{expect(FURNITURE_ROOMS.flatMap(r=>roomFurnitureCatalogue(r))).toHaveLength(14);for(const room of FURNITURE_ROOMS){const layout=captureRoomFurniture(room);expect(decodeRoomFurniture(layout)).toEqual(layout);for(const row of layout.placements)expect(roomFurnitureOffset(layout,row.furnitureId)).toEqual([0,0]);}});
 it('accepts one current per-piece CAS, rejects the stale partner move, preserves unrelated resources and never mutates input',()=>{const first={room:'common',furnitureId:'sofa',expectedRevision:0,x:.731,y:.501} as const,initial:FurniturePlacement[]=[],one=applyFurnitureMove(initial,first);expect(initial).toEqual([]);expect(()=>applyFurnitureMove(one,{...first,x:.2})).toThrow('HEARTHSIDE_FURNITURE_CONFLICT');const two=applyFurnitureMove(one,{...first,furnitureId:'coffee-table',x:.3});expect(two).toHaveLength(2);expect(two[0]).toEqual(one[0]);expect(applyFurnitureMove(two,{...first,expectedRevision:1,x:.9})[1]).toMatchObject({revision:2,x:.9});});
 it('rejects forged room, identity, revision, author, money, fractional precision and bounds',()=>{const valid={room:'common',furnitureId:'sofa',expectedRevision:0,x:.5,y:.5};for(const patch of [{room:'private'},{furnitureId:'bank'},{furnitureId:'projector'},{expectedRevision:-1},{expectedRevision:1.1},{authorId:'other'},{balance:1},{x:NaN},{x:.5001},{y:.93}])expect(()=>decodeFurnitureMove({...valid,...patch})).toThrow();expect(()=>applyFurnitureMove([], {...valid,expectedRevision:1})).toThrow('HEARTHSIDE_FURNITURE_CONFLICT');});
 it('rejects accessors, symbols, sparse/exotic arrays, duplicates and incomplete snapshots without executing getters',()=>{const value={room:'common',furnitureId:'sofa',revision:0,x:.5,y:.5},getter=vi.fn(()=>.5),accessor={...value};Object.defineProperty(accessor,'x',{get:getter});expect(()=>decodeFurniturePlacements([accessor])).toThrow();expect(getter).not.toHaveBeenCalled();for(const raw of [new Array(1),[value,value],Object.assign([value],{extra:true}),[{...value,[Symbol('secret')]:1}]])expect(()=>decodeFurniturePlacements(raw)).toThrow();expect(()=>decodeRoomFurniture({version:1,room:'common',placements:[value]})).toThrow();expect(()=>decodeRoomFurniture({...captureRoomFurniture('common'),version:2})).toThrow();});
 it('captures independent complete history values that survive later updates, roundtrip and a member return',()=>{const state=applyFurnitureMove([],{room:'studio',furnitureId:'worktable',expectedRevision:0,x:.7,y:.4}),frame=captureRoomFurniture('studio',state),restored=decodeRoomFurniture(JSON.parse(JSON.stringify(frame)));state[0]!.x=.8;expect(frame.placements[0]?.x).toBe(.7);const next=applyFurnitureMove(state,{room:'studio',furnitureId:'worktable',expectedRevision:1,x:.9,y:.5});expect(captureRoomFurniture('studio',next).placements[0]?.revision).toBe(2);expect(restored).toEqual(frame);expect(captureRoomFurniture('common',state).placements.every(p=>p.revision===0)).toBe(true);});
});
describe('reviewed guest furniture',()=>{
 const input={publicationId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',title:'Our room',welcome:'',theme:'classic',room:'common',mode:'anytime',items:[]};
 function source():GuestSourceCatalogue{return {activeMemberIds:['a','b'],furniture:room=>captureRoomFurniture(room),experience:()=>null,note:()=>null,memory:()=>null,memoryAccess:async()=>false,piece:async()=>null,media:async()=>null};}
 it('binds the exact full layout at prepare/activation but never reads live furniture during a visit',async()=>{const catalogue=source(),captured=await captureGuestSources(input,catalogue);expect(captured.arrangement.furniture).toEqual(captureRoomFurniture('common'));catalogue.furniture=room=>captureRoomFurniture(room,applyFurnitureMove([],{room:'common',furnitureId:'sofa',expectedRevision:0,x:.8,y:.5}));expect(await validateGuestSources(captured.proof,catalogue,'activation')).toBe(false);catalogue.furniture=vi.fn(()=>{throw Error('Live source layout must not be consulted');});expect(await validateGuestSources(captured.proof,catalogue,'visit')).toBe(true);expect(catalogue.furniture).not.toHaveBeenCalled();expect(captured.arrangement.furniture?.placements[0]).toMatchObject({x:.5,revision:0});});
 it('rejects source identities/financial additions or mismatched room in the furniture payload',async()=>{const copy=(await captureGuestSources(input,source())).arrangement,layout=copy.furniture!;for(const bad of [{...layout,householdId:'secret'},captureRoomFurniture('studio'),{...layout,placements:layout.placements.map(p=>({...p,bankId:'secret'}))}])expect(()=>decodeGuestArrangement({...copy,furniture:bad})).toThrow();});
 it('retains the legacy absent-layout digest; the visitor resolves frozen v1 defaults only',()=>{const raw={version:1,title:'Older room',welcome:'',theme:'classic',room:'common',mode:'anytime',objects:[]};expect(decodeGuestArrangement(raw)).toEqual(raw);});
});
