import {describe,it,expect,beforeAll,beforeEach,afterAll} from 'vitest';
import {createServer,type ViteDevServer} from 'vite';
import {chromium,type Browser,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import type {} from './fixtures/hearthsideWorkspaceProof.tsx';
describe('selected intention in the actual compact/full Workspace',()=>{
 let server:ViteDevServer,browser:Browser,page:Page,address:string;const errors:string[]=[];
 beforeAll(async()=>{const startedAt=performance.now();server=await createServer({configFile:false,root:process.cwd(),cacheDir:'node_modules/.hearthside-workspace-proof',optimizeDeps:{entries:['test/fixtures/hearthsideWorkspaceProof.tsx']},esbuild:{jsx:'automatic'},logLevel:'error',server:{host:'127.0.0.1',port:0},plugins:[{name:'workspace-proof',configureServer(vite){vite.middlewares.use('/__workspace_proof',(_req,res)=>{res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Synthetic worktable proof</title></head><body><div id="root"></div><script type="module" src="/test/fixtures/hearthsideWorkspaceProof.tsx"></script></body></html>');});}}]});await server.listen();address=`http://127.0.0.1:${(server.httpServer!.address()as{port:number}).port}/__workspace_proof`;browser=await chromium.launch({channel:'chrome',headless:true});page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',error=>errors.push(error.message));await mkdir('/tmp/hearthside-workspace-proof',{recursive:true});
 // Bootstrap the actual middleware entry within the existing 30s setup bound.
 // Keep the 3s interaction/reload checks after the module graph is ready.
 await page.goto(address);await page.getByRole('heading',{name:'An evening at home',exact:true}).waitFor();
 await writeFile('/tmp/hearthside-workspace-proof/startup.json',JSON.stringify({startupMs:Math.round(performance.now()-startedAt),entry:'hearthsideWorkspaceProof.tsx',errors},null,2));
 page.setDefaultTimeout(3000);},30000);
 beforeEach(async()=>{errors.length=0;await page.goto(address);await page.evaluate(()=>{sessionStorage.clear();localStorage.clear();});await page.reload();await page.getByRole('heading',{name:'An evening at home',exact:true}).waitFor();});
 afterAll(async()=>{await browser?.close();await server?.close();});
 it('keeps authored free writing through compact/full/hidden and scope switches without model or money calls',async()=>{
  await page.getByRole('button',{name:/Make room for possibilities/}).click();const paper=page.getByLabel('A page for this intention');await paper.fill('Our private unsaved writing');
  await page.evaluate(()=>window.workspaceProof.mode('compact'));expect(await paper.inputValue()).toBe('Our private unsaved writing');await page.getByRole('button',{name:'Open room ↗'}).click();expect(await paper.inputValue()).toBe('Our private unsaved writing');
  await page.evaluate(()=>window.workspaceProof.mode('hidden'));await paper.waitFor({state:'hidden'});await page.evaluate(()=>window.workspaceProof.mode('room'));expect(await paper.inputValue()).toBe('Our private unsaved writing');
  await page.evaluate(()=>window.workspaceProof.scope('HH-other'));expect(await paper.inputValue()).toBe('');await paper.fill('Other household words');await page.evaluate(()=>window.workspaceProof.scope('HH-proof'));expect(await paper.inputValue()).toBe('Our private unsaved writing');
  await page.reload();expect(await paper.inputValue()).toBe('Our private unsaved writing');expect(await page.evaluate(()=>window.workspaceProof.posts())).toEqual([]);await page.getByRole('button',{name:'Return to this intention'}).click();expect(await page.evaluate(()=>window.workspaceProof.returns())).toBe(1);expect(errors).toEqual([]);
 });
 it('saves real private artifacts, requires exact provider disclosure, and resets it for a changed intention',async()=>{
  await page.getByLabel('A page for this intention').fill('A useful little plan.');await page.getByRole('button',{name:'Save privately to Workspace'}).click();await page.getByText('Written by you. Review before sharing or relying on this work.').waitFor();
  let snapshot=await page.evaluate(()=>window.workspaceProof.snapshot());expect(snapshot.projects).toHaveLength(1);expect(snapshot.projects[0]?.artifacts).toHaveLength(1);expect(snapshot.projects[0]?.experience?.providerApprovalDigest).toBeNull();
  await page.getByLabel('Talk to Hercules').fill('Help me think about this.');expect(await page.getByRole('button',{name:'Send',exact:true}).isDisabled()).toBe(true);
  await page.getByText('What an activated Hercules run can use', {exact:true}).click();await page.getByLabel('I reviewed this context and the provider disclosure.').check();expect(await page.getByRole('button',{name:'Approve this context for activated runs'}).isDisabled()).toBe(true);
  await page.evaluate(()=>window.workspaceProof.execution());await page.getByRole('button',{name:'Approve this context for activated runs'}).click();await page.getByText('This version has your disclosure approval.').waitFor({state:'attached'});expect(await page.getByRole('button',{name:'Send',exact:true}).isEnabled()).toBe(true);
  await page.evaluate(()=>window.workspaceProof.revision());expect(await page.getByRole('button',{name:'Send',exact:true}).isDisabled()).toBe(true);await page.getByRole('button',{name:'Use this reviewed intention version'}).click();snapshot=await page.evaluate(()=>window.workspaceProof.snapshot());expect(snapshot.projects[0]?.experience?.context.revision).toBe(2);expect(snapshot.projects[0]?.experience?.providerApprovalDigest).toBeNull();expect(snapshot.projects[0]?.artifacts[0]?.content).toBe('A useful little plan.');expect(errors).toEqual([]);
 });
 it('keeps one authored artifact through repeated saves and edits',async()=>{
  await page.getByLabel('A page for this intention').fill('First private draft.');await page.getByRole('button',{name:'Save privately to Workspace'}).click();await page.getByText('Written by you. Review before sharing or relying on this work.').waitFor();const first=await page.evaluate(()=>window.workspaceProof.snapshot());const id=first.projects[0]!.artifacts[0]!.artifactId;
  await page.getByRole('button',{name:'Save privately to Workspace'}).click();expect((await page.evaluate(()=>window.workspaceProof.snapshot())).projects[0]!.artifacts).toHaveLength(1);
  await page.getByLabel('A page for this intention').fill('Second private draft.');await page.getByRole('button',{name:'Save privately to Workspace'}).click();await page.getByText('Manually edited; verify before relying on this version.').waitFor();const versions=(await page.evaluate(()=>window.workspaceProof.snapshot())).projects[0]!.artifacts;expect(versions).toHaveLength(2);expect(versions.map(v=>v.artifactId)).toEqual([id,id]);expect(versions[1]?.parentId).toBe(versions[0]?.id);expect(errors).toEqual([]);
 });
 it('preserves a draft when another device edits its source and requires an explicit reviewed base',async()=>{
  await page.getByLabel('A page for this intention').fill('My original writing.');await page.getByRole('button',{name:'Save privately to Workspace'}).click();await page.getByText('Written by you. Review before sharing or relying on this work.').waitFor();
  await page.getByLabel('A page for this intention').fill('My unsaved next version.');await page.evaluate(()=>window.workspaceProof.sourceRevision());await page.getByRole('heading',{name:'This private source has a newer version'}).waitFor();expect(await page.getByRole('button',{name:'Save privately to Workspace'}).isDisabled()).toBe(true);expect(await page.getByLabel('A page for this intention').inputValue()).toBe('My unsaved next version.');
  await page.getByRole('button',{name:'Use this reviewed source version as my base'}).click();await page.getByRole('button',{name:'Save privately to Workspace'}).click();const versions=(await page.evaluate(()=>window.workspaceProof.snapshot())).projects[0]!.artifacts;expect(versions.at(-1)?.parentId).toBe('other-device');expect(versions.at(-1)?.content).toBe('My unsaved next version.');expect(errors).toEqual([]);
 });
 it('recovers exact publication after a lost receipt, separates source deletion from withdrawal',async()=>{
  await page.getByLabel('A page for this intention').fill('Private source with a private paragraph.');await page.getByRole('button',{name:'Save privately to Workspace'}).click();await page.getByRole('button',{name:'Review sharing'}).click();await page.getByLabel('Full content to share').fill('Only this chosen sentence.');
  await page.evaluate(()=>window.workspaceProof.losePublication());await page.getByRole('button',{name:'Share this reviewed copy'}).click();await page.getByRole('button',{name:'Check original publication'}).waitFor();expect(await page.getByLabel('Full content to share').isDisabled()).toBe(true);
  const first=await page.evaluate(()=>window.workspaceProof.copies());expect(first).toHaveLength(1);await page.getByRole('button',{name:'Check original publication'}).click();await page.getByText('Copies placed with this intention',{exact:true}).click();await page.locator('.hw-shared-shelf details summary').first().click();await page.getByRole('button',{name:'Withdraw this shared copy'}).waitFor();
  expect((await page.evaluate(()=>window.workspaceProof.copies()))[0]?.id).toBe(first[0]?.id);
  await page.getByRole('button',{name:'Delete private source…'}).click();await page.getByRole('button',{name:'Delete these private source versions'}).click();expect((await page.evaluate(()=>window.workspaceProof.snapshot())).projects[0]?.artifacts).toEqual([]);expect((await page.evaluate(()=>window.workspaceProof.copies()))[0]?.state).toBe('active');
  await page.evaluate(()=>window.workspaceProof.loseWithdrawal());await page.getByRole('button',{name:'Withdraw this shared copy'}).click();await page.getByRole('button',{name:'Check original withdrawal'}).waitFor();expect((await page.evaluate(()=>window.workspaceProof.copies()))[0]?.state).toBe('withdrawn');await page.getByRole('button',{name:'Check original withdrawal'}).click();await page.getByRole('button',{name:'Check original withdrawal'}).waitFor({state:'hidden'});expect(errors).toEqual([]);
 });
 it('uses authored theme treatments and keeps controls readable at every required width and with enlarged text',async()=>{
  for(const theme of ['classic','taylor','newfoundland'] as const){await page.evaluate(value=>window.workspaceProof.theme(value),theme);for(const width of [320,390,719,720,1100,1440,1920]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(await page.locator('.hs-worktable button,.hs-worktable input,.hs-worktable textarea').evaluateAll(elements=>elements.filter(el=>{const r=el.getBoundingClientRect();return r.width>0&&(r.left< -1||r.right>innerWidth+1);}).length)).toBe(0);}await page.setViewportSize({width:390,height:1000});await page.screenshot({path:`/tmp/hearthside-workspace-proof/${theme}-phone.png`,fullPage:true});}
  await page.evaluate(()=>{window.workspaceProof.dark();document.documentElement.style.fontSize='200%';});await page.getByLabel('Working title').focus();await page.keyboard.press('Tab');expect(await page.getByLabel('A page for this intention').evaluate(el=>el===document.activeElement)).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(await page.getByLabel('Working title').evaluate(el=>Number(getComputedStyle(el).backgroundColor.match(/\d+/)?.[0])<128)).toBe(true);await page.screenshot({path:'/tmp/hearthside-workspace-proof/dark-enlarged.png',fullPage:true});expect(errors).toEqual([]);
 },30000);
});
