import {guestNestOrnament} from '../src/hearthside/nestGuestAppearance.ts';
import {afterEach,expect,it,vi} from 'vitest';
import {saveKittyNestDesign,nestLookAt,assertKittyNestTransition,shapeKittyNestDesigns} from '../src/core/kittyNestDesigns.ts';
import {financialAuditHash,recordBillPayment} from '../src/core/index.ts';
import {newKittyPiece} from '../src/core/kittyStudio.ts';
import {planLifeFixture} from './fixtures/plan-life.ts';
import {migrateNestDesign,applyNestDesignReference,assertNestDocumentVisible} from '../src/hearthside/nestDesignSource.ts';
import {decodeNestSource} from '../src/hearthside/nestDesignBinding.ts';
import {acceptKittyDesignOperation,checkpointKittyDesign,restoreKittyDesignCheckpoint,snapshotKittyDesignRevision,projectKittyDesign} from '../src/hearthside/design.ts';
import {normalizeExportSelection} from '../src/hearthside/exportKitty.ts';
import {decodeGuestAppearance,guestDisplayPiece} from '../src/hearthside/guestContracts.ts';
import {preserveGoalArtwork,currentSharedLifeRecords} from '../src/hearthside/creativeContinuity.ts';
import type {KittyDesignDocument,KittyDesignOperation} from '../src/hearthside/designContracts.ts';
const actor='MEM-001',at='2026-09-12T12:00:00.000Z';
const source=(designKey='king',view:'household'|'personal'='household')=>decodeNestSource({version:1,view,designKey,appearance:{version:1,tier:designKey==='king'?'king':'bill',category:designKey==='king'?null:'protect',theme:'newfoundland'}});
const stroke=(d:KittyDesignDocument,id:string,color='#abcdef'):KittyDesignOperation=>({version:1,id,designId:d.id,pieceId:d.legacy!.pieces[0]!.id,gestureId:'gesture-'+id,kind:'append-stroke',expectedEditEpoch:0,surfaceRevision:0,stroke:{part:'body',tool:'brush',color,size:12,opacity:1,mirror:false,pts:[.2,.2,.4,.4]}});
const accept=(d:KittyDesignDocument,o:KittyDesignOperation,actorId=actor)=>acceptKittyDesignOperation(d,o,{environment:d.scope.environment,householdId:d.scope.householdId,actorId,acceptedAt:new Date().toISOString(),order:d.revision+1}).document;
afterEach(()=>vi.useRealTimers());
it('preserves legacy shape, unknown history and setup; updates metadata without whole-studio or financial edits',async()=>{
 vi.useFakeTimers();vi.setSystemTime(at);let h=planLifeFixture('household');const legacy=newKittyPiece('legacy-king',at);legacy.sculpt.body='pear';legacy.paint.strokes=[{part:'body',tool:'brush',color:'#ab2233',size:12,opacity:1,mirror:false,pts:[.2,.2,.3,.3]}];
 h=saveKittyNestDesign(h,{memberId:actor,view:'household',bankKey:'king',expectedRevision:0,name:'Our crooked King',glaze:'cream',studio:{version:1,draft:legacy,fired:[]}}).household;
 const money=await financialAuditHash(h),goals=structuredClone(h.goals);let d=migrateNestDesign(h,actor,'DESIGN-king',source());h=applyNestDesignReference(h,d,at);
 expect(d.legacy?.authorship).toBe('unknown');expect(d.legacy?.pieces[0]).toEqual(legacy);expect(d.nest).toEqual(source());expect(h.goals).toEqual(goals);expect(h.kittyNestDesigns?.[0]?.studio).toBeUndefined();
 const migrated=h;const input={memberId:actor,view:'household' as const,bankKey:'king',expectedRevision:h.kittyNestDesigns![0]!.revision,name:'Our crooked King II',glaze:'cream' as const};
 expect(()=>saveKittyNestDesign(h,{...input,studio:{version:1,draft:legacy,fired:[]}})).toThrow('shared Studio');expect(()=>saveKittyNestDesign(h,{...input,completeSetup:true})).toThrow('Fire');
 h=saveKittyNestDesign(h,input).household;expect(()=>assertKittyNestTransition(migrated,h,actor,'saveKittyNestDesign')).not.toThrow();
 d=accept(d,stroke(d,'one'));d=accept(d,stroke(d,'two','#123abc'),'MEM-002');const before=projectKittyDesign(d),gesture=before.gestures.find(g=>g.id==='gesture-one')!;
 d=accept(d,{version:1,id:'undo',designId:d.id,pieceId:legacy.id,gestureId:'undo',kind:'undo-gesture',targetGestureId:gesture.id,expectedGestureRevision:gesture.revision,expectedEditEpoch:0});
 expect(projectKittyDesign(d).pieces[0]!.piece.paint.strokes.map(s=>s.color)).toEqual(['#ab2233','#123abc']);
 d=accept(d,{version:1,id:'fire',designId:d.id,pieceId:legacy.id,gestureId:'fire',kind:'fire',expectedRevision:d.revision});h=applyNestDesignReference(h,d,new Date().toISOString());
 h=saveKittyNestDesign(h,{...input,expectedRevision:h.kittyNestDesigns![0]!.revision,completeSetup:true}).household;expect(h.kittyNestDesigns![0]!.setupCompletedAt).toBe(at);
 expect(await financialAuditHash(h)).toBe(money);expect(restoreKittyDesignCheckpoint(checkpointKittyDesign(d))).toEqual(d);expect(currentSharedLifeRecords(h).kittyNestDesigns).toEqual(h.kittyNestDesigns);expect(preserveGoalArtwork(goals,goals)).toEqual(goals);
 expect(()=>assertKittyNestTransition(null,h)).not.toThrow();const forged=structuredClone(h);forged.kittyNestDesigns![0]!.designRef!.revision++;expect(()=>assertKittyNestTransition(h,forged,actor,'saveKittyNestDesign')).toThrow();
});
it('keeps old paid pottery inline, later paid pottery on its exact canonical revision, and never uses current art for either',()=>{
 vi.useFakeTimers();vi.setSystemTime('2026-09-01T12:00:00.000Z');let h=planLifeFixture('household');const recurrence=h.recurrences[0]!,key='recurrence:'+recurrence.id,legacy=newKittyPiece('receipt-piece','2026-09-01T12:00:00.000Z');
 h=saveKittyNestDesign(h,{memberId:actor,view:'household',bankKey:key,expectedRevision:0,name:'Rent pottery',glaze:'cream',category:'protect',studio:{version:1,draft:legacy,fired:[]}}).household;
 vi.setSystemTime('2026-09-02T12:00:00.000Z');h=recordBillPayment(h,{recurrenceId:recurrence.id,occurrenceDate:recurrence.nextDate,paymentDate:'2026-09-02',amount:'900',accountId:recurrence.accountId,createdBy:actor}).household;
 vi.setSystemTime('2026-09-03T12:00:00.000Z');let d=migrateNestDesign(h,actor,'DESIGN-rent',source(key));h=applyNestDesignReference(h,d,new Date().toISOString());
 d=accept(d,stroke(d,'paint-kept','#aa2233'));h=applyNestDesignReference(h,d,new Date().toISOString());
 vi.setSystemTime('2026-10-02T12:00:00.000Z');h=recordBillPayment(h,{recurrenceId:recurrence.id,occurrenceDate:'2026-10-20',paymentDate:'2026-10-02',amount:'900',accountId:recurrence.accountId,createdBy:actor}).household;
 vi.setSystemTime('2026-10-03T12:00:00.000Z');d=accept(d,stroke(d,'paint-later','#123abc'));h=applyNestDesignReference(h,d,new Date().toISOString());
 const row=h.kittyNestDesigns![0]!,old=nestLookAt(row,'2026-09-02T12:00:00.000Z')!,recent=nestLookAt(row,'2026-10-02T12:00:00.000Z')!;
 expect(old.designRef).toBeUndefined();expect(old.studio?.draft).toEqual(legacy);expect(recent.studio).toBeUndefined();expect(recent.designRef?.revision).toBe(1);
 const snapshot=snapshotKittyDesignRevision(d,legacy.id,recent.designRef!.revision);expect(snapshot.piece.paint.strokes.map(s=>s.color)).toEqual(['#aa2233']);expect(snapshot.appearance).toEqual(source(key).appearance);expect(d.revision).toBe(2);
 expect(shapeKittyNestDesigns(h.kittyNestDesigns)).toHaveLength(1);
 const hidden={...h,recurrences:[]};expect(()=>assertNestDocumentVisible(hidden,actor,d)).toThrow('DESIGN_NEST_UNAVAILABLE');expect(()=>assertNestDocumentVisible(h,'MEM-outsider',d)).toThrow('DESIGN_NEST_UNAVAILABLE');
});
it('validates immutable ornaments without private identifiers or current theme/backing; personal source requires its principal',()=>{
 let h=planLifeFixture('household');h=saveKittyNestDesign(h,{memberId:actor,view:'personal',bankKey:'king',expectedRevision:0,name:'Private King',glaze:'cream',studio:{version:1,draft:newKittyPiece('private-piece',at),fired:[]}}).household;
 const d=migrateNestDesign(h,actor,'DESIGN-private',source('king','personal'));h=applyNestDesignReference(h,d,at);expect(()=>assertNestDocumentVisible(h,'MEM-002',d)).toThrow();
 const s=snapshotKittyDesignRevision(d,'private-piece',0),exported=normalizeExportSelection({version:1,documentId:d.id,revision:0,piece:s.piece,appearance:s.appearance,heightMm:160,construction:'solid'});expect(exported.appearance).toEqual(source().appearance);
 const guest=decodeGuestAppearance({sculpt:s.piece.sculpt,paint:s.piece.paint,ornament:guestNestOrnament(s.appearance!)});expect(guestDisplayPiece(guest)).not.toHaveProperty('ornament');expect(guest.ornament).toEqual({version:1,motif:'crown'});for(const key of ['MEM-001','tier','category','designKey','view','backing'])expect(JSON.stringify(guest)).not.toContain(key);expect(()=>decodeGuestAppearance({sculpt:s.piece.sculpt,paint:s.piece.paint,ornament:s.appearance})).toThrow();expect(JSON.stringify(guest)).not.toContain('MEM-001');
 let calls=0;expect(()=>decodeNestSource({...source(),get designKey(){calls++;return 'king';}})).toThrow();expect(calls).toBe(0);
 expect(()=>decodeNestSource({...source(),designKey:'goal:fake'})).toThrow();expect(()=>decodeNestSource({...source(),appearance:{...source().appearance,tier:'plan'}})).toThrow();
});
it('requires the canonical Nest capability, accepts metadata through ordinary authority and blocks old whole-studio writes',async()=>{
 const [{splitForSync},{prepareCommand},{commandFromCapture},{capturedIntent},{applyAcceptedDesignReference}]=await Promise.all([import('../src/core/sync.ts'),import('../src/ledgerSync/authority.ts'),import('../src/ledgerSync/protocol.ts'),import('../src/ledgerSync/capture.ts'),import('../src/hearthside/designProjection.ts')]);
 let h=planLifeFixture('household');h=saveKittyNestDesign(h,{memberId:actor,view:'household',bankKey:'king',expectedRevision:0,name:'Our King',glaze:'cream',studio:{version:1,draft:newKittyPiece('legacy-king',at),fired:[]}}).household;const d=migrateNestDesign(h,actor,'DESIGN-command-king',source());h=applyAcceptedDesignReference(h,d,null);
 const scope={environment:h.environment,householdId:h.householdId,memberId:actor,subject:'fictional',role:'owner' as const,expires:Date.now()+60000,aclEpoch:1},state={sequence:h.revision,shared:splitForSync(h,actor).shared,personal:new Map(h.members.map(m=>[m.id,splitForSync(h,m.id).personal]))};
 const preview=saveKittyNestDesign(h,{memberId:actor,view:'household',bankKey:'king',expectedRevision:h.kittyNestDesigns![0]!.revision,name:'Our wonky King',glaze:'cream'}),command=await commandFromCapture(capturedIntent(preview.household)!,scope,crypto.randomUUID());
 const old={...command};delete old.nestDesignVersion;await expect(prepareCommand(state,old,scope,()=>{})).rejects.toThrow('CLIENT_RELOAD_REQUIRED');
 const accepted=await prepareCommand(state,command,scope,()=>{});expect(accepted.household.kittyNestDesigns![0]!.name).toBe('Our wonky King');expect(accepted.household.kittyNestDesigns![0]!.designRef).toEqual(h.kittyNestDesigns![0]!.designRef);expect(await financialAuditHash(accepted.household)).toBe(await financialAuditHash(h));
 const stale=structuredClone(command);Object.assign(stale.steps[0]!.args[0] as object,{studio:{version:1,draft:newKittyPiece('replacement',at),fired:[]}});await expect(prepareCommand(state,stale,scope,()=>{})).rejects.toThrow('shared Studio');
});
