import {expect,it} from 'vitest';
import type {seedHearthsideActualApp} from './fixtures/hearthsideActualApp.ts';
import {createServer,transformWithEsbuild} from 'vite';
import {chromium} from '@playwright/test';
import {mkdir,readFile,writeFile,realpath} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';

it('opens actual local App books, preserves room/object URLs and focused tool return without authenticated writes',async()=>{
 const appRoot=resolve(process.env.HEARTH_APP_PROOF_ROOT??process.cwd()),out=process.env.HEARTH_ARTIFACTS_DIR??'/tmp/hearthside-actual-app-proof';
 await mkdir(out,{recursive:true});const sourcePaths=['src/App.tsx','src/Hercules.tsx','src/hearthside/Hearthside.tsx','src/hearthside/routes.ts','src/hearthside/HouseholdRoom.tsx','src/planner/Planner.tsx','src/Calendar.tsx','src/hearthside/hearthside.css','src/hearthside/roomScene.css','src/styles.css','src/theme/worlds.css'];const sourceHashes=async()=>Object.fromEntries(await Promise.all(sourcePaths.map(async path=>[path,createHash('sha256').update(await readFile(appRoot+'/'+path)).digest('hex')])));const sourcesBefore=await sourceHashes();const fixture=await readFile(resolve('test/fixtures/hearthsideActualApp.ts'),'utf8');
 const server=await createServer({configFile:false,envFile:false,root:appRoot,cacheDir:out+'/vite-cache',logLevel:'error',esbuild:{jsx:'automatic'},optimizeDeps:{exclude:['@electric-sql/pglite']},worker:{format:'es'},define:{'import.meta.env.VITE_HEARTHSIDE':'"1"','import.meta.env.VITE_HEARTHSIDE_DESIGN':'"0"','import.meta.env.VITE_HEARTHSIDE_VAULT':'"0"','import.meta.env.VITE_HEARTHSIDE_WORKSPACE':'"0"','import.meta.env.VITE_HEARTHSIDE_GUESTS':'"0"','import.meta.env.VITE_HEARTHSIDE_AR':'"0"','import.meta.env.VITE_HEARTHSIDE_EXPORTS':'"0"','import.meta.env.VITE_LEDGER_SYNC_V2':'"0"','import.meta.env.VITE_LEDGER_SYNC_LOCAL_AUTH':'"0"','import.meta.env.VITE_PRODUCTION_CONTINUITY':'"0"','import.meta.env.VITE_HERCULES_PLAY':'"1"','import.meta.env.VITE_HERCULES_DRESSING_ROOM':'"1"','import.meta.env.VITE_HERCULES_WORKSPACE':'"1"'},server:{host:'127.0.0.1',port:0,fs:{allow:[appRoot,await realpath(appRoot+'/node_modules')]}},plugins:[{name:'actual-app-local-fixture',configureServer(vite){vite.middlewares.use(async(req,res,next)=>{
  if(req.url==='/__app_seed'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="en"><title>Synthetic local App seed</title><body>Preparing synthetic local books.</body></html>');return;}
  if(req.url?.split('?')[0]==='/test/fixtures/hearthsideActualApp.ts'){res.setHeader('Content-Type','application/javascript');res.end((await transformWithEsbuild(fixture.replaceAll("'../../","'/").replace("'./existing-books-onboarding.ts'","'/test/fixtures/existing-books-onboarding.ts'"),'fixture.ts')).code);return;}next();
 });}}]});await server.listen();
 const origin=`http://127.0.0.1:${(server.httpServer!.address() as {port:number}).port}`,browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:390,height:900},reducedMotion:'reduce'}),page=await context.newPage();
 const errors:string[]=[],blocked:string[]=[],geometryFailures:string[]=[],evidence:unknown[]=[];const stage=async(name:string)=>writeFile(out+'/stage.json',JSON.stringify({name,at:new Date().toISOString(),url:page.url()}));page.setDefaultTimeout(30000);page.on('pageerror',e=>{if(!errors.includes(e.message)&&errors.length<30)errors.push(e.message);});
 await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!==origin||/^\/(api|ledger-sync|sync|hercules\/|bank\/|work\/|documents\/)/.test(url.pathname)){blocked.push(url.origin===origin?url.pathname:url.origin);return route.abort();}return route.continue();});
 const settle=async()=>{await page.locator('.deferred-surface[aria-busy=true]').waitFor({state:'hidden'});const reminder=page.getByRole('button',{name:'Close reminders',exact:true});if(await reminder.count())await reminder.click();};
 const nav=async(name:string)=>{await page.locator('nav.nav').getByRole('button',{name,exact:true}).click();await settle();};
 try{
  await stage('seed');await page.goto(origin+'/__app_seed');
  const initial=await page.evaluate<Awaited<ReturnType<typeof seedHearthsideActualApp>>>("(async()=>{const m=await import('/test/fixtures/hearthsideActualApp.ts');return m.seedHearthsideActualApp();})()");
  await stage('opening-actual-app');await page.goto(origin);await page.locator('.app[data-books-readiness="ready"]').waitFor({state:'attached',timeout:90000});await page.locator('nav.nav').waitFor();await settle();
  expect(await page.locator('.app').getAttribute('data-ledger-mode')).toBe('household');await expect.poll(()=>page.locator('.hercules-pill-name,.hercules-help-label').innerText()).toMatch(/Rent|Phones/);
  await stage('arrival');await nav('Hearthside');await page.locator('.hearthside[data-room="common"]').waitFor();
  await expect.poll(()=>page.locator('.hercules-pill-name,.hercules-help-label').innerText()).toContain('A little company');expect(await page.locator('.hercules-pill.has-reminder,.hercules-reminder-label').count()).toBe(0);const roomUrl=page.url();expect(new URL(roomUrl).pathname).toBe('/hearthside/rooms/common');
  await page.locator('.hsr-object-index').getByRole('button',{name:/An evening just for us/}).click();
  await page.getByRole('heading',{name:'An evening just for us',exact:true}).waitFor();const intentionUrl=page.url();
  expect(new URL(intentionUrl).pathname).toBe('/hearthside/experiences/EXP-app-proof');
  await page.reload();await page.locator('.app[data-books-readiness="ready"]').waitFor({state:'attached',timeout:90000});await page.getByRole('heading',{name:'An evening just for us',exact:true}).waitFor();expect(page.url()).toBe(intentionUrl);
  await stage('task-return');await page.locator('#hearthside-linked-0').click();await page.locator('#planner-focused-task').waitFor();expect(await page.locator('.planner-day').filter({has:page.locator('#planner-focused-task')}).innerText()).toContain('Put out the good mugs');
  await page.getByRole('button',{name:'Return to Hearthside',exact:true}).click();await page.getByRole('heading',{name:'An evening just for us',exact:true}).waitFor();expect(page.url()).toBe(intentionUrl);await expect.poll(()=>page.evaluate(()=>document.activeElement?.id)).toBe('hearthside-linked-0');
  await stage('calendar-return');await page.locator('#hearthside-linked-1').click();await page.getByRole('button',{name:'Return to Hearthside',exact:true}).waitFor();await page.getByLabel('Event title',{exact:true}).waitFor();expect(await page.getByLabel('Event title',{exact:true}).inputValue()).toBe('Our quiet evening');
  await page.getByRole('button',{name:'Return to Hearthside',exact:true}).click();await page.getByRole('heading',{name:'An evening just for us',exact:true}).waitFor();expect(page.url()).toBe(intentionUrl);await expect.poll(()=>page.evaluate(()=>document.activeElement?.id)).toBe('hearthside-linked-1');
  evidence.push({arrival:'actual App/PGlite ready',objectReload:true,taskExactReturn:true,calendarExactReturn:true});
  await stage('themes');for(const theme of ['classic','taylor','newfoundland']){
   await page.getByRole('button',{name:/Status Centre/}).first().click();await settle();const comfort=page.locator('#status-comfort');if(await comfort.count()&&!await comfort.evaluate(e=>(e as HTMLDetailsElement).open))await comfort.locator('summary').click();await page.locator(`[data-preview-theme="${theme}"]`).click();await page.getByRole('button',{name:'Use theme',exact:true}).click();await nav('Hearthside');
   for(const room of ['common','studio'])for(const width of (room==='common'?[320,390,719,720,1100,1440,1920]:[390,1440])){await page.setViewportSize({width,height:900});await page.locator(`#hearthside-room-${room}`).click();await page.locator(`.hearthside[data-world="${theme}"][data-room="${room}"]`).waitFor();expect(new URL(page.url()).pathname).toBe(`/hearthside/rooms/${room}`);await expect.poll(()=>page.locator('.hercules-pill-name,.hercules-help-label').innerText()).toContain('A little company');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.evaluate(()=>scrollTo(0,0));expect(await page.locator('.theme-scene-heading').count()).toBe(0);const firstViewport=await page.evaluate(()=>{const header=document.querySelector('.hsr-heading')!.getBoundingClientRect(),nav=document.querySelector('nav.nav')!.getBoundingClientRect(),fund=[...document.querySelectorAll('.fund-ledge-grip,.onboarding-return-bar')].map(el=>el.getBoundingClientRect()).filter(r=>r.height>0&&r.top<innerHeight),bottom=Math.min(innerHeight,nav.top,...fund.map(r=>r.top));const objects=[...document.querySelectorAll<HTMLElement>('.hsr-placed')].map(el=>{const r=el.getBoundingClientRect();return {id:el.dataset.objectId,top:r.top,bottom:r.bottom,visible:r.top>=header.bottom&&r.bottom<=bottom&&r.left>=0&&r.right<=innerWidth};});return {headerTop:header.top,headerBottom:header.bottom,usableBottom:bottom,fundChrome:fund.map(r=>({top:r.top,bottom:r.bottom,left:r.left,right:r.right})),objects};});if(width===390){if(firstViewport.headerBottom>=firstViewport.usableBottom)geometryFailures.push(`${theme}/${room}: room header below fixed nav`);if(!firstViewport.objects.some(o=>o.visible))geometryFailures.push(`${theme}/${room}: no complete meaningful object above fixed nav`);}if([320,390,1440].includes(width)){await page.screenshot({path:`${out}/${theme}-${room}-${width}-first.png`});await page.screenshot({path:`${out}/${theme}-${room}-${width}.png`,fullPage:true});}const roomTop=await page.locator('.hsr').evaluate(el=>el.getBoundingClientRect().top+scrollY);const chrome=await page.locator('nav.nav button').evaluateAll(nodes=>nodes.map(el=>{const r=el.getBoundingClientRect();return {name:el.textContent,left:r.left,right:r.right,height:r.height};}).filter(r=>r.height>0&&r.right>r.left));evidence.push({theme,width,room,chrome});expect(chrome.every(b=>b.left>=-1&&b.right<=width+1&&b.height>=43),JSON.stringify(chrome)).toBe(true);evidence.push({theme,width,room,overflow:false,roomTop,firstViewport,chrome});
    if(room==='common'&&width===320){await page.evaluate(()=>document.documentElement.style.fontSize='200%');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);const object=page.locator('.hsr-object-index').getByRole('button',{name:/An evening just for us/});const focusId=await object.getAttribute('id');await object.focus();await page.keyboard.press('Enter');await page.getByRole('heading',{name:'An evening just for us',exact:true}).waitFor();await page.getByRole('button',{name:'← Back to common room',exact:true}).click();await expect.poll(()=>page.evaluate(()=>document.activeElement?.id)).toBe(focusId);await page.evaluate(()=>document.documentElement.style.fontSize='');evidence.push({theme,width,enlargedText:'200%',keyboardObjectOpenReturn:true});}}
  }
  await page.goto(intentionUrl);await page.getByRole('heading',{name:'An evening just for us',exact:true}).waitFor();
  await stage('task-reload-return');await page.locator('#hearthside-linked-0').click();await page.locator('#planner-focused-task').waitFor();await page.reload();await page.locator('.app[data-books-readiness="ready"]').waitFor({state:'attached',timeout:90000});await settle();await page.locator('#planner-focused-task').waitFor();await page.getByRole('button',{name:'Return to Hearthside',exact:true}).click();await page.getByRole('heading',{name:'An evening just for us',exact:true}).waitFor();expect(page.url()).toBe(intentionUrl);await expect.poll(()=>page.evaluate(()=>document.activeElement?.id)).toBe('hearthside-linked-0');
  evidence.push({taskReloadReturn:true});
  await page.locator('#hearthside-room-studio').click();await page.locator('#hearthside-open-studio').click();await page.locator('.hearthside-focused').waitFor();await page.screenshot({path:out+'/studio-focused.png',fullPage:true});
  // Same event contract used by the existing wardrobe controls; no fixture handler or auth is substituted.
  await stage('legacy-wardrobe');await nav('Home');await expect.poll(()=>page.locator('.hercules-pill.has-reminder,.hercules-reminder-label').innerText()).toMatch(/Rent|Phones/);await page.evaluate(scope=>window.dispatchEvent(new CustomEvent('hearth:open-fitting',{detail:{environment:'development',householdId:scope.householdId,memberId:scope.memberId}})),initial.scope);
  await page.locator('.hearthside[data-room="studio"]').waitFor();expect(new URL(page.url()).searchParams.get('surface')).toBe('wardrobe');await expect.poll(()=>page.locator('.hercules-pill-name,.hercules-help-label').innerText()).toContain('A little company');expect(await page.locator('.hercules-pill.has-reminder,.hercules-reminder-label').count()).toBe(0);
  await page.screenshot({path:out+'/legacy-wardrobe.png',fullPage:true});
  await page.locator('#hearthside-room-common').click();await page.locator('#hearthside-add-intention').click();await page.getByRole('region',{name:'Intention draft'}).waitFor();
  const sharedSubmit=page.getByRole('region',{name:'Intention draft'}).getByRole('button',{name:'Save our intention',exact:true});expect(await sharedSubmit.isDisabled()).toBe(true);
  const final=await page.evaluate("(async()=>{const m=await import('/test/fixtures/hearthsideActualApp.ts');return m.readHearthsideActualApp();})()");
  expect(final).toEqual({revision:initial.revision,financialHash:initial.financialHash,receipts:initial.receipts,sharedLife:initial.sharedLife});expect(errors).toEqual([]);expect(blocked.filter(path=>/^\/hercules\/(chat|plan|rig)/.test(path))).toEqual([]);expect(geometryFailures).toEqual([]);expect(await sourceHashes(),'tested source changed during proof').toEqual(sourcesBefore);
  evidence.push({residentLabel:'A little company',automaticReminderInHearthside:false,ordinaryHomeReminderRestored:true,herculesProviderRequests:0,legacyWardrobe:true,authenticatedSharedSave:false,sharedSubmitDisabled:true,navigatorLocksPresent:await page.evaluate(()=>Boolean(navigator.locks)),unchangedFinancialHash:true,unchangedReceipts:true,unchangedSharedMetadata:true});
 }catch(error){await writeFile(out+'/failure.html',await page.content());await writeFile(out+'/failure.txt',await page.locator('body').innerText());await page.screenshot({path:out+'/failure.png',fullPage:true});throw error;}finally{
  const sourcesAfter=await sourceHashes(),appSha256=sourcesAfter['src/App.tsx'];await writeFile(out+'/evidence.json',JSON.stringify({appRoot,appSha256,sourcesBefore,sourcesAfter,sourcesUnchanged:JSON.stringify(sourcesBefore)===JSON.stringify(sourcesAfter),fixtureSha256:createHash('sha256').update(fixture).digest('hex'),evidence,errors,geometryFailures,blocked,authenticatedWrites:false},null,2));await browser.close();await server.close();
 }
},180000);
