import {expect,it} from 'vitest';
import {createServer} from 'vite';
import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdir,writeFile} from 'node:fs/promises';
import {applyFurnitureMove,roomFurnitureCatalogue,type FurnitureRoom,type FurniturePlacement} from '../src/hearthside/roomFurniture.ts';
it('moves actual authored art with precise keyboard/pointer drafts, CAS race/recovery and all room/theme/width geometry',async()=>{
 const store=new Map<string,FurniturePlacement[]>(),directory='/tmp/hearthside-furniture-proof',evidence:unknown[]=[],errors:string[]=[];await mkdir(directory,{recursive:true});
 const server=await createServer({configFile:false,root:process.cwd(),cacheDir:'/tmp/hearthside-furniture-vite',esbuild:{jsx:'automatic'},logLevel:'error',server:{host:'127.0.0.1',port:0},plugins:[{name:'furniture-proof',configureServer(vite){vite.middlewares.use(async(req,res,next)=>{const url=new URL(req.url!,'http://local');if(url.pathname.startsWith('/__furniture/')){const household=url.searchParams.get('household')??'one';res.setHeader('Content-Type','application/json');try{if(url.pathname.endsWith('/move')){const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.from(chunk));store.set(household,applyFurnitureMove(store.get(household)??[],JSON.parse(Buffer.concat(chunks).toString())));}res.end(JSON.stringify(store.get(household)??[]));}catch(error){res.statusCode=409;res.end(JSON.stringify({code:(error as Error).message}));}return;}if(url.pathname==='/__furniture_proof'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width, initial-scale=1"><title>Local synthetic furniture proof</title><style>body{margin:0}.proof-controls{display:flex;flex-wrap:wrap;gap:12px;padding:16px;font:14px system-ui}.proof-controls button,.proof-controls select{min-height:44px}output[data-state]{display:block;overflow-wrap:anywhere;font:12px monospace}</style></head><body><div id="root"></div><script type="module" src="/test/fixtures/hearthsideFurnitureProof.tsx"></script></body></html>');return;}next();});}}]});await server.listen();
 const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),url=`http://127.0.0.1:${(server.httpServer!.address() as {port:number}).port}/__furniture_proof`;page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));
 const art=(id:string)=>page.locator(`[data-furniture-art="${id}"]`).first();
 try{
  await page.goto(url);await page.getByRole('button',{name:'Arrange Sofa',exact:true}).click();const before=await art('sofa').getAttribute('transform');const slider=page.getByLabel('Across its space');await slider.focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>art('sofa').getAttribute('transform')).not.toBe(before);await page.getByLabel('Test theme').selectOption('taylor');expect(await slider.inputValue()).toBe('0.501');await page.getByLabel('Test theme').selectOption('classic');await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect.poll(()=>art('sofa').getAttribute('transform')).toBe(before);expect(await page.getByRole('button',{name:'Arrange Sofa',exact:true}).evaluate(el=>el===document.activeElement)).toBe(true);
  await page.getByRole('button',{name:'Arrange Sofa',exact:true}).click();const body=art('sofa').locator('path').first();await body.scrollIntoViewIfNeeded();const bodyBox=(await body.boundingBox())!;await page.mouse.move(bodyBox.x+bodyBox.width*.2,bodyBox.y+bodyBox.height*.25);await page.mouse.down();await page.mouse.move(bodyBox.x+bodyBox.width*.2+25,bodyBox.y+bodyBox.height*.25,{steps:3});await page.mouse.up();await expect.poll(()=>art('sofa').getAttribute('transform')).not.toBe(before);await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Arrange Sofa',exact:true}).click();const handle=page.getByRole('button',{name:'Move Sofa; use arrow keys for precision'});await handle.scrollIntoViewIfNeeded();const box=(await handle.boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+60,box.y+box.height/2-10,{steps:5});await page.mouse.up();await expect.poll(()=>art('sofa').getAttribute('transform')).not.toBe(before);const dragged=await art('sofa').getAttribute('transform');expect(await page.getByLabel('Across its space').inputValue()).not.toBe('0.5');await page.route('**/__furniture/move?*',async route=>{await route.abort('failed');await page.unroute('**/__furniture/move?*');});await page.getByRole('button',{name:'Save furniture position'}).click();await page.getByText('The position has not been confirmed.',{exact:false}).waitFor();expect(await page.getByLabel('Across its space').isEnabled()).toBe(true);await page.getByRole('button',{name:'Save furniture position'}).click();await page.getByText('Sofa position saved.').waitFor();await page.reload();await page.getByRole('button',{name:'Arrange Sofa',exact:true}).waitFor();await expect.poll(()=>art('sofa').getAttribute('transform')).toBe(dragged);
  const partner=await context.newPage();partner.setDefaultTimeout(10000);await partner.goto(url);await partner.getByLabel('Test member').selectOption('bob');await partner.getByRole('button',{name:'Arrange Sofa',exact:true}).click();await page.getByRole('button',{name:'Arrange Sofa',exact:true}).click();await page.getByLabel('Across its space').focus();await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'Save furniture position'}).click();await partner.getByRole('alert').filter({hasText:'newer saved position'}).waitFor();expect(await partner.getByRole('button',{name:'Save furniture position'}).isDisabled()).toBe(true);await partner.getByRole('button',{name:'Use latest position'}).click();await partner.getByLabel('Across its space').focus();await partner.keyboard.press('ArrowRight');await partner.getByRole('button',{name:'Save furniture position'}).click();await partner.getByText('Sofa position saved.').waitFor();await partner.close();
  await page.getByRole('button',{name:'Arrange Sofa',exact:true}).click();await page.getByLabel('Across its space').focus();await page.keyboard.press('End');await page.getByLabel('Test member').selectOption('bob');expect(await page.getByRole('form',{name:'Arrange furniture: Sofa'}).count()).toBe(0);await page.getByLabel('Test member').selectOption('alice');await page.getByLabel('Test household').selectOption('two');await expect.poll(()=>art('sofa').getAttribute('transform')).toBe('translate(0 0)');await page.getByLabel('Test household').selectOption('one');await expect.poll(()=>art('sofa').getAttribute('transform')).not.toBe('translate(0 0)');
  await page.getByRole('button',{name:'Arrange Our painted piece'}).click();const placed=page.locator('[data-object-id="piece-1"]'),objectBox=(await placed.boundingBox())!;await placed.scrollIntoViewIfNeeded();const actualBox=(await placed.boundingBox())!;await page.mouse.move(actualBox.x+actualBox.width/2,actualBox.y+actualBox.height/2);await page.mouse.down();await page.mouse.move(actualBox.x+actualBox.width/2-30,actualBox.y+actualBox.height/2-10,{steps:4});await page.mouse.up();expect(objectBox.width).toBeGreaterThan(0);expect(await page.getByLabel('Across the room').inputValue()).not.toBe('0.7');await page.getByRole('button',{name:'Save position',exact:true}).click();
  for(const theme of ['classic','taylor','newfoundland']){await page.getByLabel('Test theme').selectOption(theme);for(const room of ['common','studio','conservatory','theatre'] as FurnitureRoom[]){await page.getByLabel('Test room').selectOption(room);for(const width of [320,390,719,720,1100,1440,1920]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${theme}/${room}/${width}`).toBe(true);for(const def of roomFurnitureCatalogue(room)){const element=art(def.id);expect(await element.count()).toBe(1);const original=await element.getAttribute('transform');await page.getByRole('button',{name:`Arrange ${def.label}`,exact:true}).click();await page.getByLabel('Across its space').focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>element.getAttribute('transform')).not.toBe(original);await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect.poll(()=>element.getAttribute('transform')).toBe(original);}expect(await page.locator('.hsr button').evaluateAll(buttons=>buttons.filter(el=>{const r=el.getBoundingClientRect();return r.width>0&&(r.left< -1||r.right>innerWidth+1||r.height<43);}).map(el=>el.getAttribute('aria-label')||el.textContent))).toEqual([]);evidence.push({theme,room,width,actualArtKeyboardCancel:true,overflow:false});if([390,1440].includes(width)){await page.screenshot({path:`${directory}/${theme}-${room}-${width}.png`,fullPage:true});}}await page.setViewportSize({width:390,height:1000});const axe=await new AxeBuilder({page}).include('.hsr').withTags(['wcag2a','wcag2aa']).analyze();expect(axe.violations.map(v=>v.id),`${theme}/${room}`).toEqual([]);evidence.push({theme,room,axeViolations:0});}}
  await page.getByLabel('Test room').selectOption('common');await page.setViewportSize({width:390,height:1000});await page.emulateMedia({reducedMotion:'reduce'});await page.getByRole('button',{name:'Arrange Sofa',exact:true}).click();const mobile=page.getByRole('button',{name:'Move Sofa; use arrow keys for precision'});await mobile.scrollIntoViewIfNeeded();const b=(await mobile.boundingBox())!;expect(b.x).toBeGreaterThanOrEqual(0);expect(b.x+b.width).toBeLessThanOrEqual(391);await mobile.focus();const x=Number(await page.getByLabel('Across its space').inputValue());await page.keyboard.press('Shift+ArrowLeft');expect(Number(await page.getByLabel('Across its space').inputValue())).toBeCloseTo(x-.01,3);const arrangingAxe=await new AxeBuilder({page}).include('.hsr').withTags(['wcag2a','wcag2aa']).analyze();expect(arrangingAxe.violations.map(v=>v.id)).toEqual([]);await page.screenshot({path:directory+'/newfoundland-phone-arranging.png',fullPage:true});await page.keyboard.press('Escape');await page.getByRole('button',{name:'Global action',exact:true}).click();await page.getByText('Global action works').waitFor();await page.evaluate(()=>document.documentElement.style.fontSize='200%');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);evidence.push({pointerDrag:true,cancel:true,perPieceRace:true,reload:true,memberReturn:true,scopeSwitch:true,existingObjectDrag:true,reducedMotion:true,keyboardPrecision:true,globalAction:true});await writeFile(directory+'/evidence.json',JSON.stringify(evidence,null,2));
 }catch(error){await writeFile(directory+'/failure.html',await page.content());await page.screenshot({path:directory+'/failure.png',fullPage:true});throw error;}finally{await browser.close();await server.close();}
},180000);
