import {afterAll,beforeAll,expect,it} from 'vitest';
import {build} from 'esbuild';
import {createServer,type Server} from 'node:http';
import {mkdir} from 'node:fs/promises';
import {chromium,expect as uiExpect,type Browser,type Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {ENCOUNTER_PACKS} from '../src/hearthside/encounterPacks.ts';
let browser:Browser,server:Server,base='';
declare global{interface Window{encounterProof:{select(pack:string,actor?:string):Promise<void>;actor(id:string):void;lose():void;state():unknown;bridges():{kind:string;size?:number;recipe?:unknown}[];calls():{id?:string;action:string}[];dispose():void;};}}
beforeAll(async()=>{
  const result=await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
    import React from'react';import{createRoot}from'react-dom/client';import{Encounter}from'./src/hearthside/Encounter.tsx';
    import{HearthsideVaultEncounters}from'./workers/hearthsideVaultEncounters.ts';import{applyEncounterCommand}from'./src/hearthside/encounterService.ts';import{encounterPack}from'./src/hearthside/encounterPacks.ts';
    let actor=localStorage.getItem('encounter-proof-actor')||'A',current=JSON.parse(localStorage.getItem('encounter-proof-current')||'null'),lose=false;
    const records=new Map(JSON.parse(localStorage.getItem('encounter-proof-records')||'[]')),calls=JSON.parse(localStorage.getItem('encounter-proof-calls')||'[]'),bridges=[];
    const save=()=>{localStorage.setItem('encounter-proof-current',JSON.stringify(current));localStorage.setItem('encounter-proof-records',JSON.stringify([...records]));localStorage.setItem('encounter-proof-calls',JSON.stringify(calls));localStorage.setItem('encounter-proof-actor',actor);};
    const people=[{memberId:'A',subject:'synthetic-A'},{memberId:'B',subject:'synthetic-B'}],policy={recipients:people,approvers:people};
    const vault=new HearthsideVaultEncounters({get:key=>structuredClone(records.get(key)),put:(key,value)=>{records.set(key,structuredClone(value));save();},list:prefix=>[...records].filter(([k])=>k.startsWith(prefix)).map(([,v])=>structuredClone(v)),transaction:action=>action()},s=>{if(!people.some(p=>p.memberId===s.memberId&&p.subject===s.subject))throw Error('FORBIDDEN');});
    const root=createRoot(document.getElementById('root')),clients=new Map();const scope=id=>({environment:'development',householdId:'HH-ENCOUNTER',memberId:id,subject:'synthetic-'+id});
    const clientFor=id=>{if(!clients.has(id))clients.set(id,{command:async request=>{calls.push(request.input);save();const value=await vault.command(scope(id),request.input,{id:current.id,packId:current.packId,participantMemberIds:['A','B'],wardrobeIds:['actual-scarf']},policy);if(lose&&request.input.action!=='read'){lose=false;throw Error('Lost acknowledgement');}return value;}});return clients.get(id);};
    const wardrobe=[{id:'actual-scarf',name:'Our chosen red scarf',stamp:{id:'actual-scarf',anchor:'chest',kind:'scarf',color:'#aa5544',size:.2,rotation:0},preview:<svg width="120" height="90" viewBox="0 0 120 90" role="img" aria-label="Synthetic actual wardrobe scarf"><path d="M15 20h80v25H60v35H35V45H15Z" fill="#aa5544"/></svg>}];
    async function submit(command){const evidence=current.reveal?await vault.evidence(scope(actor),current.reveal).catch(()=>undefined):undefined;const revealEvidence=command.kind==='encounter.reveal'?await vault.evidence(scope(actor),command.binding):evidence;
      current=await applyEncounterCommand(current,command,{actorId:actor,memberIds:['A','B'],experienceIds:['existing-intention'],wardrobeIds:['actual-scarf'],revealEvidence});save();render();return true;}
    function render(){if(!current)return;const pack=encounterPack(current.packId);root.render(<React.StrictMode><Encounter client={clientFor(actor)} scope={scope(actor)} theme={pack.theme} encounter={current} roster={[{memberId:'A',name:'Alex'},{memberId:'B',name:'Sam'}]} submit={submit} refresh={async()=>render()} onReplay={id=>select(id,actor,true)}
      onStudioKeepsake={async recipe=>{bridges.push({kind:'studio',recipe});render();}} onMemoryKeepsake={async input=>{const bytes=new Uint8Array(await input.image.arrayBuffer());if(bytes[0]!==137||bytes[1]!==80)throw Error('Not PNG');bridges.push({kind:'memory',size:input.image.size});render();}} wardrobe={wardrobe} experiences={[{id:'existing-intention',title:'A free evening'}]}/></React.StrictMode>);}
    async function select(id,next='A',replay=false){actor=next;current=await applyEncounterCommand(null,{kind:'encounter.start',id:'encounter-'+id+(replay?'-'+crypto.randomUUID():''),packId:id,participantMemberIds:['A','B'],experienceId:null},{actorId:actor,memberIds:['A','B'],experienceIds:[],wardrobeIds:['actual-scarf']});save();render();}
    window.encounterProof={select,actor:id=>{actor=id;save();render();},lose:()=>lose=true,state:()=>current,bridges:()=>bridges,calls:()=>calls,dispose:()=>root.unmount()};if(current)render();else select('classic-spring-window');
  `},bundle:true,write:false,outfile:'encounter-proof.js',platform:'browser',format:'iife',target:'es2022'});
  const js=result.outputFiles.find(f=>f.path.endsWith('.js'))!.text,css=result.outputFiles.find(f=>f.path.endsWith('.css'))!.text;
  server=createServer((request,response)=>{if(request.url==='/app.js'){response.setHeader('content-type','text/javascript');response.end(js);}else{response.setHeader('content-type','text/html');response.end(`<html lang="en"><head><title>Encounter synthetic proof</title><style>body{font-family:system-ui;margin:0;padding:12px}*{box-sizing:border-box}${css}</style></head><body><main><h1>Our seasonal encounter</h1><div id="root"></div></main><script src="/app.js"></script></body></html>`);}});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();if(!address||typeof address==='string')throw Error('No local server');base=`http://127.0.0.1:${address.port}`;browser=await chromium.launch({headless:true});await mkdir('/tmp/hearthside-encounter-proof',{recursive:true});
},60000);
afterAll(async()=>{await browser?.close();if(server)await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));});
async function saveAnswer(page:Page,text:string,mummers=false){await page.locator('.encounter-private-paper textarea').fill(text);if(mummers)await page.getByLabel('My actual wardrobe item').selectOption('actual-scarf');await page.getByRole('button',{name:'Save my private answer',exact:true}).click();await uiExpect(page.getByRole('status').filter({hasText:'Your answer is saved privately'})).toBeVisible();}
async function reveal(page:Page){await page.getByRole('button',{name:'Review my choice to reveal',exact:true}).click();await page.getByRole('button',{name:'Choose to reveal this version',exact:true}).click();}
async function actor(page:Page,id:string){await page.evaluate(id=>window.encounterProof.actor(id),id);await page.getByRole('button',{name:'Save my private answer',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.hearth-encounter')?.getAttribute('aria-busy')?.includes('true'));}
async function place(page:Page,text:string,mummers=false){await page.getByRole('button',{name:'Continue to making',exact:true}).click();await page.locator('.encounter-make textarea').fill(text);await page.locator('.encounter-colours button').nth(1).click();await page.locator('.encounter-arrangement button').nth(2).click();await page.getByText('Add a drawn mark or a typed line',{exact:true}).click();await page.getByRole('button',{name:'Add a simple zigzag',exact:true}).focus();await page.keyboard.press('Enter');if(mummers)await page.getByLabel('Actual wardrobe piece for my portrait').selectOption('actual-scarf');await page.getByRole('button',{name:'Place my contribution',exact:true}).click();await uiExpect(page.getByRole('status').filter({hasText:'Your contribution is shared'})).toBeVisible();}
async function keep(page:Page){await page.getByRole('button',{name:'Review our keepsake',exact:true}).click();await page.getByLabel('I reviewed this whole composition and both people’s words.').check();await page.getByRole('button',{name:'Keep this exact composition',exact:true}).focus();await page.keyboard.press('Enter');await uiExpect(page.getByRole('button',{name:'You chose to keep this composition',exact:true})).toBeVisible();}
it('completes both participants through all twelve real encounter components and explicit creation bridges',async()=>{
  const context=await browser.newContext({reducedMotion:'reduce'}),page=await context.newPage();await page.goto(base);
  for(const pack of ENCOUNTER_PACKS){
    await page.evaluate(pack=>window.encounterProof.select(pack),pack.id);await page.getByRole('heading',{name:pack.title,exact:true}).waitFor();
    await page.getByRole('button',{name:pack.notice.objects[1]!.name,exact:true}).click();await uiExpect(page.getByText(pack.notice.objects[1]!.discovery,{exact:true})).toBeVisible();
    await saveAnswer(page,'Alex privately noticed the light.',pack.mechanic==='mummers');await actor(page,'B');await uiExpect(page.getByText('Alex privately noticed the light.',{exact:true})).toHaveCount(0);
    await saveAnswer(page,'Sam privately noticed the sound.',pack.mechanic==='mummers');await reveal(page);await actor(page,'A');await reveal(page);
    await uiExpect(page.getByRole('heading',{name:'Two answers, in our own words'})).toBeVisible();await place(page,'Alex room',pack.mechanic==='mummers');
    await actor(page,'B');await place(page,'Sam colour',pack.mechanic==='mummers');await keep(page);
    await actor(page,'A');await page.getByRole('button',{name:'Continue to making',exact:true}).click();await keep(page);await uiExpect(page.getByRole('heading',{name:'Chosen by both of us'})).toBeVisible();
    if(['classic-spring-window','taylor-spring-spread','newfoundland-spring-ice'].includes(pack.id)){for(const width of [390,1440]){await page.setViewportSize({width,height:1000});const axe=await new AxeBuilder({page}).include('.hearth-encounter').analyze();expect(axe.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)}))).toEqual([]);}}
    const before=await page.evaluate(()=>window.encounterProof.bridges().length);await page.getByRole('button',{name:pack.keep.medium==='studio'?'Make this piece from our choices':'Open this card as a memory draft',exact:true}).click();await page.waitForFunction(n=>window.encounterProof.bridges().length===n+1,before);
    expect(await page.evaluate(()=>JSON.stringify(window.encounterProof.state()))).not.toContain('privately noticed');
    await page.setViewportSize({width:390,height:1000});await page.screenshot({path:`/tmp/hearthside-encounter-proof/${pack.id}-390.png`,fullPage:true});
  }
  expect(await page.evaluate(()=>window.encounterProof.bridges().filter(x=>x.kind==='studio').every(x=>(x.recipe as {derivedStrokes:unknown[]}).derivedStrokes.length===2))).toBe(true);expect(await page.evaluate(()=>window.encounterProof.bridges().map(x=>x.kind))).toEqual(ENCOUNTER_PACKS.map(p=>p.keep.medium));await context.close();
},120000);
it('keeps real IndexedDB drafts and request identity through lost acknowledgement, reload and account switch',async()=>{
  const context=await browser.newContext(),page=await context.newPage();await page.goto(base);await page.locator('.encounter-private-paper textarea').fill('A privately resumable answer');await page.evaluate(()=>window.encounterProof.lose());await page.getByRole('button',{name:'Save my private answer',exact:true}).click();await uiExpect(page.getByRole('alert')).toContainText('pending action');
  const id=await page.evaluate(()=>window.encounterProof.calls().find(c=>c.action==='save')!.id);await page.reload();await uiExpect(page.locator('.encounter-private-paper textarea')).toHaveValue('A privately resumable answer');await page.getByRole('button',{name:'Retry interrupted action'}).click();await uiExpect(page.getByRole('status').filter({hasText:'recovered'})).toBeVisible();
  expect(await page.evaluate(()=>window.encounterProof.calls().filter(c=>c.action==='save').map(c=>c.id))).toEqual([id,id]);await actor(page,'B');await uiExpect(page.locator('.encounter-private-paper textarea')).toHaveValue('');
  await page.getByRole('button',{name:'Pause my part',exact:true}).click();await uiExpect(page.getByRole('button',{name:'Resume my part',exact:true})).toBeVisible();await page.getByRole('button',{name:'Resume my part',exact:true}).click();await uiExpect(page.getByRole('button',{name:'Pause my part',exact:true})).toBeVisible();await context.close();
},60000);
it('keeps the author-only submitted choice stable while the partner privately saves, deletes and pauses',async()=>{
  const context=await browser.newContext(),page=await context.newPage();await page.goto(base);await saveAnswer(page,'My private first answer');await reveal(page);await uiExpect(page.locator('.encounter-own-submission')).toBeVisible();await page.reload();
  await uiExpect(page.locator('.encounter-own-submission')).toBeVisible();const ownPaper=await page.locator('.encounter-private-paper').innerText();
  await actor(page,'B');await saveAnswer(page,'A second private answer');await actor(page,'A');await uiExpect(page.locator('.encounter-own-submission')).toBeVisible();expect(await page.locator('.encounter-private-paper').innerText()).toBe(ownPaper);
  await actor(page,'B');await page.getByRole('button',{name:'Delete my answer',exact:true}).click();await uiExpect(page.locator('.encounter-private-paper textarea')).toHaveValue('');await actor(page,'A');await uiExpect(page.locator('.encounter-own-submission')).toBeVisible();expect(await page.locator('.encounter-private-paper').innerText()).toBe(ownPaper);
  await actor(page,'B');await page.getByRole('button',{name:'Pause my part',exact:true}).click();await uiExpect(page.getByRole('button',{name:'Resume my part',exact:true})).toBeVisible();await actor(page,'A');await uiExpect(page.locator('.encounter-own-submission')).toBeVisible();expect(await page.locator('.encounter-private-paper').innerText()).toBe(ownPaper);await uiExpect(page.getByRole('heading',{name:'Two answers, in our own words'})).toHaveCount(0);await context.close();
},60000);
it('provides phone/desktop compositions, keyboard discovery, drawing alternative and dark enlarged text in every theme',async()=>{
  for(const pack of [ENCOUNTER_PACKS[0]!,ENCOUNTER_PACKS[4]!,ENCOUNTER_PACKS[8]!]){
    const context=await browser.newContext({reducedMotion:'reduce'}),page=await context.newPage();await page.goto(base);await page.evaluate(id=>window.encounterProof.select(id),pack.id);
    const object=page.getByRole('button',{name:pack.notice.objects[0]!.name,exact:true});await object.focus();await page.keyboard.press('Enter');await uiExpect(page.getByText(pack.notice.objects[0]!.discovery,{exact:true})).toBeVisible();
    for(const width of [320,390,719,720,1100,1440,1920]){await page.setViewportSize({width,height:1000});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${pack.theme} ${width}`).toBe(true);
      if(width===390||width===1440){const axe=await new AxeBuilder({page}).include('.hearth-encounter').analyze();expect(axe.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>n.target)})),`${pack.theme} ${width}`).toEqual([]);await page.screenshot({path:`/tmp/hearthside-encounter-proof/${pack.theme}-notice-${width}.png`,fullPage:true});}}
    await page.emulateMedia({colorScheme:'dark'});await page.setViewportSize({width:390,height:1000});await page.addStyleTag({content:'.hearth-encounter{font-size:24px!important}'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page}).include('.hearth-encounter').analyze();expect(axe.violations.map(v=>v.id)).toEqual([]);await context.close();
  }
},120000);
