import {describe,it,expect} from 'vitest';
import {catalogHousehold,configureHouseholdFund,proposeHouseholdFundContribution,holdHouseholdFundContribution,projectHouseholdFund} from '../src/core/index.ts';
import {prepareAction,executeReviewedAction,availableHerculesActions,type ActionContext} from '../src/core/herculesActions.ts';
const context=():ActionContext=>({household:configureHouseholdFund(catalogHousehold(),{custodianMemberId:'MEM-001',createdBy:'MEM-001',openedOn:'2026-09-01'}).household,memberId:'MEM-001',view:'household',today:'2026-09-10'});
describe('Hercules Fund authority',()=>{
 it('keeps contributions proposed until the custodian separately confirms receipt',()=>{const c=context();c.memberId='MEM-002';const values={amount:'100',date:c.today,sourceKind:'external-received',explanation:'Synthetic savings already received',purpose:'September'};const review=prepareAction(c,'fund-propose',values);expect(projectHouseholdFund(c.household,c.today).operatingBalanceCents).toBe(0);const result=executeReviewedAction(c,review,crypto.randomUUID());expect(projectHouseholdFund(result.household,c.today)).toMatchObject({operatingBalanceCents:0,pendingContributionsCents:10000});expect(availableHerculesActions(c).some(a=>a.id==='fund-received')).toBe(false);});
 it('shows source/amount/hold state and invalidates the exact review after a new hold',()=>{const c=context();const proposal=proposeHouseholdFundContribution(c.household,{memberId:'MEM-002',contributorMemberId:'MEM-002',amount:'100',date:c.today,source:{version:1,kind:'external-received',explanation:'Synthetic savings'}});c.household=proposal.household;const values={proposalEventId:proposal.postedIds[0]!,date:c.today,received:'received'};const review=prepareAction(c,'fund-received',values);expect(JSON.stringify(review.rows)).toContain('Synthetic savings');expect(JSON.stringify(review.rows)).toContain('$100.00');c.household=holdHouseholdFundContribution(c.household,{memberId:c.memberId,proposalEventId:values.proposalEventId,date:c.today}).household;expect(()=>executeReviewedAction(c,review,crypto.randomUUID())).toThrow(/changed/);const refreshed=prepareAction(c,'fund-received',values);expect(JSON.stringify(refreshed.rows)).toContain('held');expect(projectHouseholdFund(executeReviewedAction(c,refreshed,crypto.randomUUID()).household,c.today).operatingBalanceCents).toBe(10000);});
 it('does not manufacture another member approval or monthly-plan agreement',()=>{const c=context();const review=prepareAction(c,'fund-plan',{monthKey:'2026-09',target:'100',buffer:'10'});const result=executeReviewedAction(c,review,crypto.randomUUID());expect(result.household.fundMonthPlans?.[0]?.agreedByMemberIds).toEqual(['MEM-001']);expect(result.household.householdFund?.approvals).toHaveLength(1);});
});
