import {describe,it,expect} from 'vitest';
import {catalogHousehold} from '../src/core/index.ts';
import {commitCompanion,companionFor} from '../src/core/herculesCompanion.ts';
import {commitCompanionGallery} from '../src/core/herculesWardrobe.ts';
import {commitCompanionPlay,playPrivateFor,rewardEvidence,hasPlayData,playBankFacts} from '../src/core/herculesPlay.ts';
import {DEFAULT_PORTRAIT,decodePlayPrivate,emptyPlayPrivate,decodePlayRoom,emptyPlayRoom,type PlayOperation} from '../src/core/playContracts.ts';
import {COZY_LOOK} from '../src/wardrobe/catalogue.ts';
import {assembleHousehold,splitForSync,mergeShared} from '../src/core/sync.ts';
import {capturedIntent} from '../src/ledgerSync/capture.ts';
import {commandFromCapture,type Scope} from '../src/ledgerSync/protocol.ts';
import {prepareCommand,type AuthorityState} from '../src/ledgerSync/authority.ts';
import {appendRestorePoint,applyRestorePoint} from '../src/core/restorePoints.ts';
import {eraseDevelopmentData} from '../src/core/stressSeed.ts';
const initial=()=>catalogHousehold();
function play(h:ReturnType<typeof initial>,operation:PlayOperation,memberId='MEM-001'){return commitCompanionPlay(h,{version:1,id:crypto.randomUUID(),scope:{environment:h.environment,householdId:h.householdId,memberId},operation});}
function fixture(){const h=initial(),scope:Scope={environment:h.environment,householdId:h.householdId,memberId:'MEM-001',subject:'synthetic',role:'owner',expires:Date.now()+60000,aclEpoch:1},parts=splitForSync(h,scope.memberId);return {h,scope,state:{sequence:h.revision,shared:parts.shared,personal:new Map([['MEM-001',parts.personal],['MEM-002',splitForSync(h,'MEM-002').personal]])} as AuthorityState};}
const operation:PlayOperation={kind:'slot',slotId:'keepsake-1',expectedRevision:0,value:{kind:'keepsake',id:'plant'}};
describe('Hercules Play authority and continuity',()=>{
 it('accepts a room change through real command authority without financial writes',async()=>{const{h,scope,state}=fixture();const candidate=play(h,operation);const command=await commandFromCapture(capturedIntent(candidate.household)!,scope,crypto.randomUUID());const accepted=await prepareCommand(state,command,scope,()=>{});expect(accepted.shared.playRoom?.slots[0]?.value?.id).toBe('plant');expect(accepted.receipt.postedIds).toEqual([]);expect(accepted.shared.transactions).toEqual(state.shared.transactions);expect(JSON.stringify(accepted.shared)).not.toContain('"discoveries"');});
 it('supports disjoint slot concurrency and refuses stale same-slot changes',async()=>{const {h,scope,state}=fixture();const c1=await commandFromCapture(capturedIntent(play(h,operation).household)!,scope,crypto.randomUUID());const otherScope={...scope,memberId:'MEM-002'};const c2=await commandFromCapture(capturedIntent(play(h,{...operation,slotId:'keepsake-2'},'MEM-002').household)!,otherScope,crypto.randomUUID());const a=await prepareCommand(state,c1,scope,()=>{});const after={sequence:a.receipt.sequence,shared:a.shared,personal:new Map([...state.personal,['MEM-001',a.personal]])};const b=await prepareCommand(after,c2,otherScope,()=>{});expect(b.shared.playRoom?.slots).toHaveLength(2);await expect(prepareCommand(after,{...c1,id:crypto.randomUUID()},scope,()=>{})).rejects.toThrow('PLAY_CHANGED');});
 it('keeps portrait preferences and discoveries in the member envelope',async()=>{const {h,scope,state}=fixture();const next=play(h,{kind:'private',expectedRevision:0,portrait:{...DEFAULT_PORTRAIT,caption:'PRIVATE-PLAY-CANARY'},sound:true,paused:true});const command=await commandFromCapture(capturedIntent(next.household)!,scope,crypto.randomUUID());const accepted=await prepareCommand(state,command,scope,()=>{});expect(JSON.stringify(accepted.shared)).not.toContain('PRIVATE-PLAY-CANARY');expect(accepted.personal.companionProfile?.play?.portrait.caption).toBe('PRIVATE-PLAY-CANARY');const other=assembleHousehold(accepted.shared,state.personal.get('MEM-002')??null);expect(playPrivateFor(other,'MEM-002').portrait.caption).toBe('');});
 it('blocks missing capabilities, spoofed actors and compound commands',async()=>{const{h,scope,state}=fixture();const c=await commandFromCapture(capturedIntent(play(h,operation).household)!,scope,crypto.randomUUID());await expect(prepareCommand(state,{...c,companionPlayVersion:undefined},scope,()=>{})).rejects.toThrow('CLIENT_RELOAD_REQUIRED');await expect(prepareCommand(state,c,{...scope,memberId:'MEM-002'},()=>{})).rejects.toThrow('ACTOR_MISMATCH');await expect(prepareCommand(state,{...c,steps:[...c.steps,...c.steps]},scope,()=>{})).rejects.toThrow('PLAY_SINGLE_OPERATION_REQUIRED');});
 it('rejects private and absent display references, invalid slots and unknown rewards',()=>{const h=initial();expect(()=>play(h,{kind:'slot',slotId:'portrait-1',expectedRevision:0,value:{kind:'portrait',id:'private'}})).toThrow('SHARED_PORTRAIT_REQUIRED');expect(()=>play(h,{kind:'slot',slotId:'toy-1',expectedRevision:0,value:{kind:'toy',id:'lantern'}})).toThrow('SHARED_REWARD_REQUIRED');expect(()=>play(h,{...operation,slotId:'bank-1'})).toThrow('PLAY_SLOT_MISMATCH');expect(()=>play(h,{kind:'claim',reward:'camera'})).toThrow('PLAY_MILESTONE_NOT_REACHED');});
 it('records each discovery once and validates contextual prerequisites',()=>{const h=initial();const found=play(h,{kind:'discover',discovery:'drawer',theme:'classic'}).household;const again=play(found,{kind:'discover',discovery:'drawer',theme:'classic'}).household;expect(playPrivateFor(again,'MEM-001').discoveries).toEqual(['drawer']);expect(playPrivateFor(again,'MEM-001').revision).toBe(1);expect(()=>play(h,{kind:'discover',discovery:'lighthouse',theme:'classic'})).toThrow('PLAY_DISCOVERY_THEME');expect(()=>play(h,{kind:'discover',discovery:'mirror',theme:'classic'})).toThrow('WEAR_GLASSES_TO_DISCOVER');});
 it('claims the private key once, explicitly shares it, and preserves it after source changes',()=>{let h=initial();for(const discovery of ['drawer','bell','spool','lamp','latch','tea'] as const)h=play(h,{kind:'discover',discovery,theme:'classic'}).household;h=play(h,{kind:'claim',reward:'key'}).household;expect(h.playRoom).toBeUndefined();expect(h.companionProfile?.play?.awards).toHaveLength(1);h=play(h,{kind:'claim',reward:'key',share:true}).household;expect(h.playRoom?.awards).toHaveLength(1);h=play(h,{kind:'claim',reward:'key',share:true}).household;expect(h.playRoom?.awards).toHaveLength(1);h.companionProfile!.play!.discoveries=[];expect(()=>play(h,{kind:'claim',reward:'key'})).not.toThrow();});
 it('shares a finite portrait snapshot and requires distinct outfits for camera',()=>{let h=initial();const scope=companionFor(h,'MEM-001').scope;h=commitCompanion(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'look.save',look:{...COZY_LOOK,portrait:{...DEFAULT_PORTRAIT,caption:'Shared caption'}},expectedRevision:0}}).household;for(let i=0;i<3;i++)h=commitCompanionGallery(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'gallery.publish',galleryId:`gallery-${i}`,sourceLookId:COZY_LOOK.id,expectedLookRevision:1,expectedRevision:0}}).household;expect(h.companionGallery?.[0]?.value?.look.portrait?.caption).toBe('Shared caption');expect(hasPlayData(h)).toBe(true);expect(rewardEvidence(h,'MEM-001','camera')).toBeNull();});
 it('preserves room tombstones through old-book restore and activity reset',async()=>{const h=initial(),point=(await appendRestorePoint(h,'MEM-001')).restorePoints![0]!;let next=play(h,operation).household;next=play(next,{...operation,expectedRevision:1,value:null}).household;for(const restored of [applyRestorePoint(next,point,'MEM-001'),eraseDevelopmentData(next)])expect(restored.playRoom).toEqual(next.playRoom);expect(()=>mergeShared(splitForSync(next,'MEM-001').shared,splitForSync(h,'MEM-001').shared)).toThrow('PLAY_REQUIRES_AUTHORITY');});
 it('does not present or reward legacy unbacked goal progress as money',()=>{
  const h=initial();h.goals=[{id:'legacy-bank',name:'Unbacked ambition',targetCents:10000,savedCents:10000,deadline:null,arrivalDate:null,shared:true,ownerMemberId:null,subcategoryId:null,status:'unfunded',funded:false,retiredAt:null,purchaseId:null,createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-01T00:00:00Z'}];
  h.goalContributions=[{id:'legacy-progress',goalId:'legacy-bank',memberId:'MEM-001',amountCents:10000,date:'2026-09-01',transferId:null,createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-01T00:00:00Z'}];
  expect(rewardEvidence(h,'MEM-001','lantern')).toBeNull();expect(playBankFacts(h,'legacy-bank','MEM-001')?.vaultCents).toBe(0);
 });
 it('rejects arbitrary scene URLs, sparse arrays and accessor objects',()=>{expect(()=>decodePlayRoom({...emptyPlayRoom(),url:'https://untrusted'})).toThrow();expect(()=>decodePlayPrivate({...emptyPlayPrivate(),discoveries:new Array(2)})).toThrow();const value={...emptyPlayPrivate()};Object.defineProperty(value,'sound',{get:()=>true});expect(()=>decodePlayPrivate(value)).toThrow();expect(()=>play(initial(),{kind:'claim',reward:'key',share:'yes'} as never)).toThrow('PLAY_INVALID_SHARE');});
});
