import { describe, expect, it } from 'vitest';
import { catalogHousehold, postEntry } from '../src/core/index.ts';
import { actionById, executeReviewedAction, findHerculesAction, initialActionValues, isFinalConfirm, prepareAction, type ActionContext } from '../src/core/herculesActions.ts';
import { commitCompanion, companionFor } from '../src/core/herculesCompanion.ts';
import { splitForSync, assembleHousehold } from '../src/core/sync.ts';
const context=():ActionContext=>({household:catalogHousehold(),memberId:'MEM-001',view:'household',today:'2026-09-10'});
function expense(c:ActionContext){return {amount:'23.45',date:c.today,accountId:c.household.accounts.find(a=>a.active&&a.scope!=='personal')!.id,subcategoryId:'SUB-FOOD-GROCERIES',split:c.memberId,note:'Groceries'};}
describe('confirmed conversational actions',()=>{
 it('recognizes everyday requests without enabling confirmation from ordinary agreement',()=>{const c=context();expect(findHerculesAction('I just bought something',c)?.id).toBe('expense');expect(findHerculesAction('I just finished my shift',c)?.id).toBe('worked-shift');expect(initialActionValues(actionById('expense',c),'I spent $23.45 yesterday',c)).toMatchObject({amount:'23.45',date:'2026-09-09'});for(const s of ['yes','yes final confirm','"final confirm"','final confirm this','go ahead'])expect(isFinalConfirm(s)).toBe(false);expect(isFinalConfirm(' Final Confirm ')).toBe(true);});
 it('prepares without mutating and applies the same existing expense command only after review',()=>{const c=context(),before=structuredClone(c.household),v=expense(c),review=prepareAction(c,'expense',v);expect(c.household).toEqual(before);expect(review.effects).toHaveLength(1);expect(review.effects[0]!.label).toContain('Household books');expect(review.facts).toMatch(/^[0-9a-f]{64}$/);const result=executeReviewedAction(c,review,crypto.randomUUID());expect(result.household.transactions.at(-1)?.amountCents).toBe(2345);const normalize=(rows:typeof result.household.transactions)=>rows.map(({id:_id,createdAt:_c,updatedAt:_u,...row})=>row);expect(normalize(result.household.transactions)).toEqual(normalize(postEntry(c.household,{date:v.date,amount:v.amount,type:'expense',accountId:v.accountId,subcategoryId:v.subcategoryId,note:v.note,createdBy:c.memberId,visibility:c.view,splits:[{party:c.memberId,amountCents:2345}]}).household.transactions));});
 it('invalidates a changed account or ledger view but tolerates private chat saves',()=>{const c=context(),review=prepareAction(c,'expense',expense(c));const chat={...c,household:{...c.household,companionProfile:companionFor(c.household,c.memberId)}};expect(()=>executeReviewedAction(chat,review,crypto.randomUUID())).not.toThrow();expect(()=>executeReviewedAction({...c,view:'personal'},review,crypto.randomUUID())).toThrow();const changed=structuredClone(c);changed.household.accounts[0]!.name='Changed';expect(()=>executeReviewedAction(changed,review,crypto.randomUUID())).toThrow(/changed/i);});
 it('supports unequal shares and links refunds to the accepted original purchase',()=>{const c=context(),v={...expense(c),split:'custom',split_0:'10.00',split_1:'13.45'};const posted=executeReviewedAction(c,prepareAction(c,'expense',v),crypto.randomUUID());const original=posted.household.transactions.at(-1)!;expect(original.splits.map(s=>s.amountCents)).toEqual([1000,1345]);c.household=posted.household;const refund={...expense(c),amount:'5',date:'2026-09-11',refundOfId:original.id};const result=executeReviewedAction(c,prepareAction(c,'refund',refund),crypto.randomUUID());expect(result.household.transactions.at(-1)?.refundOfId).toBe(original.id);});
 it('treats read questions and negated purchases as questions, not drafts',()=>{const c=context();for(const message of ['What did I buy yesterday?','I did not buy anything','How do I record a refund?'])expect(findHerculesAction(message,c)).toBeUndefined();});
 it('keeps duplicate review explicit',()=>{const c=context(),v=expense(c),r=executeReviewedAction(c,prepareAction(c,'expense',v),crypto.randomUUID());c.household=r.household;expect(()=>prepareAction(c,'expense',v)).toThrow();expect(prepareAction(c,'expense',v,true).duplicateAcknowledged).toBe(true);});
 it('rejects stale private draft claims and retains unresolved identity through personal sync',()=>{const c=context(),scope={environment:c.household.environment,householdId:c.household.householdId,memberId:c.memberId};const operation={kind:'workflow.set' as const,workflowId:'task-household',expectedRevision:0,view:c.view,generation:0,value:{version:1 as const,actionId:'expense',view:c.view,generation:0,values:expense(c),updatedAt:new Date().toISOString(),submission:{id:crypto.randomUUID(),review:JSON.stringify(prepareAction(c,'expense',expense(c)))}}};const first=commitCompanion(c.household,{version:1,id:crypto.randomUUID(),scope,operation});expect(()=>commitCompanion(first.household,{version:1,id:crypto.randomUUID(),scope,operation})).toThrow(/STALE/);expect(()=>commitCompanion(first.household,{version:1,id:crypto.randomUUID(),scope,operation:{...operation,expectedRevision:1,value:null}})).toThrow(/PENDING_HERCULES/);const parts=splitForSync(first.household,c.memberId);expect(JSON.stringify(parts.shared)).not.toContain(operation.value.submission.id);const restored=assembleHousehold(parts.shared,parts.personal);expect(companionFor(restored,c.memberId).workflows?.[0]?.value?.submission).toEqual(operation.value.submission);});
});
