import {describe,it,expect} from 'vitest';
import {catalogHousehold} from '../src/core/index.ts';
import {commitCompanion,companionFor} from '../src/core/herculesCompanion.ts';
import {commitCompanionGallery} from '../src/core/herculesWardrobe.ts';
import {commitCompanionPlay,playPrivateFor,rewardEvidence,hasPlayData,playBankFacts,stageOutfitFor} from '../src/core/herculesPlay.ts';
import {DEFAULT_PORTRAIT,decodePlayPrivate,emptyPlayPrivate,decodePlayRoom,emptyPlayRoom,type PlayOperation} from '../src/core/playContracts.ts';
import {COZY_LOOK} from '../src/wardrobe/catalogue.ts';
import {assembleHousehold,splitForSync,mergeShared} from '../src/core/sync.ts';
import {capturedIntent,clearCapturedIntent} from '../src/ledgerSync/capture.ts';
import {commandFromCapture,type Scope} from '../src/ledgerSync/protocol.ts';
import {prepareCommand,type AuthorityState} from '../src/ledgerSync/authority.ts';
import {appendRestorePoint,applyRestorePoint} from '../src/core/restorePoints.ts';
import {eraseDevelopmentData} from '../src/core/stressSeed.ts';
const initial=()=>catalogHousehold();
function play(h:ReturnType<typeof initial>,operation:PlayOperation,memberId='MEM-001'){return commitCompanionPlay(h,{version:1,id:crypto.randomUUID(),scope:{environment:h.environment,householdId:h.householdId,memberId},operation});}
function fixture(){const h=initial(),scope:Scope={environment:h.environment,householdId:h.householdId,memberId:'MEM-001',subject:'synthetic',role:'owner',expires:Date.now()+60000,aclEpoch:1},parts=splitForSync(h,scope.memberId);return {h,scope,state:{sequence:h.revision,shared:parts.shared,personal:new Map([['MEM-001',parts.personal],['MEM-002',splitForSync(h,'MEM-002').personal]])} as AuthorityState};}
const operation:PlayOperation={kind:'slot',slotId:'keepsake-1',expectedRevision:0,value:{kind:'keepsake',id:'plant'}};
describe('Hercules Play authority and continuity',()=>{
 it('accepts a room change through real command authority without financial writes',async()=>{const{h,scope,state}=fixture();const candidate=play(h,operation);const command=await commandFromCapture(capturedIntent(candidate.household)!,scope,crypto.randomUUID());const accepted=await prepareCommand(state,command,scope,()=>{});expect(accepted.shared.playRoom?.slots[0]?.value?.id).toBe('plant');expect(accepted.receipt.postedIds).toEqual([]);expect(accepted.shared.transactions).toEqual(state.shared.transactions);expect(JSON.stringify(accepted.shared)).not.toContain('"discoveries"');});
 it('supports disjoint slot concurrency and refuses stale same-slot changes',async()=>{const {h,scope,state}=fixture();const c1=await commandFromCapture(capturedIntent(play(h,operation).household)!,scope,crypto.randomUUID());const otherScope={...scope,memberId:'MEM-002'};const c2=await commandFromCapture(capturedIntent(play(h,{...operation,slotId:'keepsake-2'},'MEM-002').household)!,otherScope,crypto.randomUUID());const a=await prepareCommand(state,c1,scope,()=>{});const after={sequence:a.receipt.sequence,shared:a.shared,personal:new Map([...state.personal,['MEM-001',a.personal]])};const b=await prepareCommand(after,c2,otherScope,()=>{});expect(b.shared.playRoom?.slots).toHaveLength(2);await expect(prepareCommand(after,{...c1,id:crypto.randomUUID()},scope,()=>{})).rejects.toThrow('PLAY_CHANGED');});
 it('keeps portrait preferences and discoveries in the member envelope',async()=>{const {h,scope,state}=fixture();const next=play(h,{kind:'private',expectedRevision:0,portrait:{...DEFAULT_PORTRAIT,caption:'PRIVATE-PLAY-CANARY'},sound:true,paused:true});const command=await commandFromCapture(capturedIntent(next.household)!,scope,crypto.randomUUID());const accepted=await prepareCommand(state,command,scope,()=>{});expect(JSON.stringify(accepted.shared)).not.toContain('PRIVATE-PLAY-CANARY');expect(accepted.personal.companionProfile?.play?.portrait.caption).toBe('PRIVATE-PLAY-CANARY');const other=assembleHousehold(accepted.shared,state.personal.get('MEM-002')??null);expect(playPrivateFor(other,'MEM-002').portrait.caption).toBe('');});
 it('blocks missing capabilities, spoofed actors and compound commands',async()=>{const{h,scope,state}=fixture();const c=await commandFromCapture(capturedIntent(play(h,operation).household)!,scope,crypto.randomUUID());await expect(prepareCommand(state,{...c,companionPlayVersion:undefined},scope,()=>{})).rejects.toThrow('CLIENT_RELOAD_REQUIRED');await expect(prepareCommand(state,c,{...scope,memberId:'MEM-002'},()=>{})).rejects.toThrow('ACTOR_MISMATCH');await expect(prepareCommand(state,{...c,steps:[...c.steps,...c.steps]},scope,()=>{})).rejects.toThrow('PLAY_SINGLE_OPERATION_REQUIRED');});
 it('rejects private and absent display references, invalid slots and unknown rewards',()=>{const h=initial();expect(()=>play(h,{kind:'slot',slotId:'portrait-1',expectedRevision:0,value:{kind:'portrait',id:'private'}})).toThrow('SHARED_PORTRAIT_REQUIRED');expect(()=>play(h,{kind:'slot',slotId:'toy-1',expectedRevision:0,value:{kind:'toy',id:'lantern'}})).toThrow('SHARED_REWARD_REQUIRED');expect(()=>play(h,{...operation,slotId:'bank-1'})).toThrow('PLAY_SLOT_MISMATCH');expect(()=>play(h,{kind:'claim',reward:'camera'})).toThrow('PLAY_MILESTONE_NOT_REACHED');});
 it('records each discovery once and validates contextual prerequisites',()=>{const h=initial();const found=play(h,{kind:'discover',discovery:'drawer',theme:'classic'}).household;const again=play(found,{kind:'discover',discovery:'drawer',theme:'classic'}).household;expect(playPrivateFor(again,'MEM-001').discoveries).toEqual(['drawer']);expect(playPrivateFor(again,'MEM-001').revision).toBe(1);expect(()=>play(h,{kind:'discover',discovery:'lighthouse',theme:'classic'})).toThrow('PLAY_DISCOVERY_THEME');expect(()=>play(h,{kind:'discover',discovery:'mirror',theme:'classic'})).toThrow('WEAR_GLASSES_TO_DISCOVER');});
 it('claims the private key once, explicitly shares it, and preserves it after source changes',()=>{let h=initial();for(const discovery of ['drawer','bell','spool','lamp','latch','tea'] as const)h=play(h,{kind:'discover',discovery,theme:'classic'}).household;h=play(h,{kind:'claim',reward:'key'}).household;expect(h.playRoom).toBeUndefined();expect(h.companionProfile?.play?.awards).toHaveLength(1);h=play(h,{kind:'claim',reward:'key',share:true}).household;expect(h.playRoom?.awards).toHaveLength(1);h=play(h,{kind:'claim',reward:'key',share:true}).household;expect(h.playRoom?.awards).toHaveLength(1);h.companionProfile!.play!.discoveries=[];expect(()=>play(h,{kind:'claim',reward:'key'})).not.toThrow();});
 it('shares a finite portrait snapshot and requires distinct outfits for camera',()=>{let h=initial();const scope=companionFor(h,'MEM-001').scope;h=commitCompanion(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'look.save',look:{...COZY_LOOK,portrait:{...DEFAULT_PORTRAIT,caption:'Shared caption'}},expectedRevision:0}}).household;for(let i=0;i<3;i++)h=commitCompanionGallery(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'gallery.publish',galleryId:`gallery-${i}`,sourceLookId:COZY_LOOK.id,expectedLookRevision:1,expectedRevision:0}}).household;expect(h.companionGallery?.[0]?.value?.look.portrait?.caption).toBe('Shared caption');expect(hasPlayData(h)).toBe(true);expect(rewardEvidence(h,'MEM-001','camera')).toBeNull();});
 it('stages only a validated published outfit and revokes its rendered access when the source is withdrawn',()=>{let h=initial(),scope=companionFor(h,'MEM-001').scope;const privateLook={...COZY_LOOK,id:'private-stage-look',name:'PRIVATE-STAGE-NAME',portrait:{...DEFAULT_PORTRAIT,caption:'PRIVATE-STAGE-CAPTION'}};h=commitCompanion(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'look.save',look:privateLook,expectedRevision:0}}).household;expect(()=>play(h,{kind:'stage-outfit',expectedRevision:0,galleryId:'private-stage-look',expectedGalleryRevision:1})).toThrow('SHARED_STAGE_OUTFIT_REQUIRED');h=commitCompanionGallery(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'gallery.publish',galleryId:'shared-stage',sourceLookId:'private-stage-look',expectedLookRevision:1,expectedRevision:0}}).household;const wornBefore=structuredClone(h.companionProfile!.wornLook);h=play(h,{kind:'stage-outfit',expectedRevision:0,galleryId:'shared-stage',expectedGalleryRevision:1},'MEM-002').household;expect(h.companionProfile!.wornLook).toEqual(wornBefore);expect(h.playRoom?.stageOutfit.value).toMatchObject({galleryId:'shared-stage',galleryRevision:1,catalogueVersion:1,selections:privateLook.selections});expect(JSON.stringify(h.playRoom?.stageOutfit)).not.toContain('PRIVATE-STAGE');expect(stageOutfitFor(h)?.selections).toEqual(privateLook.selections);const partner=assembleHousehold(splitForSync(h,'MEM-002').shared,splitForSync(h,'MEM-002').personal);expect(stageOutfitFor(partner)?.selections).toEqual(privateLook.selections);expect(()=>play(h,{kind:'stage-outfit',expectedRevision:1,galleryId:'shared-stage',expectedGalleryRevision:0})).toThrow('PLAY_STAGE_OUTFIT_CHANGED');h=commitCompanionGallery(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'gallery.remove',galleryId:'shared-stage',expectedRevision:1}}).household;expect(stageOutfitFor(h)).toBeNull();expect(()=>play(h,{kind:'stage-outfit',expectedRevision:1,galleryId:'shared-stage',expectedGalleryRevision:2})).toThrow('SHARED_STAGE_OUTFIT_REQUIRED');});
 it('keeps an explicit cleared stage reference and gives legacy rooms a safe default',async()=>{let h=initial(),scope=companionFor(h,'MEM-001').scope;h=commitCompanion(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'look.save',look:COZY_LOOK,expectedRevision:0}}).household;h=commitCompanionGallery(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'gallery.publish',galleryId:'shared-stage',sourceLookId:COZY_LOOK.id,expectedLookRevision:1,expectedRevision:0}}).household;h=play(h,{kind:'stage-outfit',expectedRevision:0,galleryId:'shared-stage',expectedGalleryRevision:1}).household;h=play(h,{kind:'stage-outfit',expectedRevision:1,galleryId:null}).household;expect(h.playRoom?.stageOutfit).toEqual({revision:2,value:null});const point=(await appendRestorePoint(h,'MEM-001')).restorePoints![0]!;const restored=applyRestorePoint(h,point,'MEM-001');expect(restored.playRoom?.stageOutfit).toEqual(h.playRoom?.stageOutfit);const legacy=emptyPlayRoom() as Record<string,unknown>;delete legacy.stageOutfit;expect(decodePlayRoom(legacy).stageOutfit).toEqual({revision:0,value:null});});
 it('keeps the staged source across shared materialization and refuses an older shared snapshot',()=>{let h=initial(),scope=companionFor(h,'MEM-001').scope;h=commitCompanion(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'look.save',look:COZY_LOOK,expectedRevision:0}}).household;h=commitCompanionGallery(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'gallery.publish',galleryId:'shared-stage',sourceLookId:COZY_LOOK.id,expectedLookRevision:1,expectedRevision:0}}).household;const before=splitForSync(h,'MEM-001').shared;h=play(h,{kind:'stage-outfit',expectedRevision:0,galleryId:'shared-stage',expectedGalleryRevision:1}).household;const staged=splitForSync(h,'MEM-002').shared;expect(assembleHousehold(staged,splitForSync(h,'MEM-002').personal).playRoom?.stageOutfit).toEqual(h.playRoom?.stageOutfit);const oldClient=structuredClone(before) as Record<string,unknown>;oldClient.playRoom=structuredClone(staged.playRoom) as Record<string,unknown>;delete (oldClient.playRoom as Record<string,unknown>).stageOutfit;expect(()=>mergeShared(staged,oldClient as typeof staged)).toThrow('PLAY_REQUIRES_AUTHORITY');});
 it('preserves a staged outfit while authority accepts concurrent decor and another display slot',async()=>{let h=initial(),scope=companionFor(h,'MEM-001').scope;h=commitCompanion(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'look.save',look:COZY_LOOK,expectedRevision:0}}).household;h=commitCompanionGallery(h,{version:1,id:crypto.randomUUID(),scope,operation:{kind:'gallery.publish',galleryId:'shared-stage',sourceLookId:COZY_LOOK.id,expectedLookRevision:1,expectedRevision:0}}).household;h=play(h,{kind:'stage-outfit',expectedRevision:0,galleryId:'shared-stage',expectedGalleryRevision:1}).household;clearCapturedIntent(h);const stateParts=splitForSync(h,'MEM-001'),state:AuthorityState={sequence:h.revision,shared:stateParts.shared,personal:new Map([['MEM-001',stateParts.personal],['MEM-002',splitForSync(h,'MEM-002').personal]])};const one=await commandFromCapture(capturedIntent(play(h,{kind:'decor',expectedRevision:0,value:{...decodePlayRoom(h.playRoom).decor.value,lighting:'studio'}}).household)!,scope,crypto.randomUUID());clearCapturedIntent(h);const other={...scope,memberId:'MEM-002'};const two=await commandFromCapture(capturedIntent(play(h,{kind:'slot',slotId:'keepsake-2',expectedRevision:0,value:{kind:'keepsake',id:'plant'}},'MEM-002').household)!,other,crypto.randomUUID());const first=await prepareCommand(state,one,scope,()=>{});const next={sequence:first.receipt.sequence,shared:first.shared,personal:new Map([...state.personal,['MEM-001',first.personal]])};const second=await prepareCommand(next,two,other,()=>{});expect(second.shared.playRoom?.stageOutfit).toEqual(h.playRoom?.stageOutfit);expect(second.shared.playRoom?.decor.value.lighting).toBe('studio');expect(second.shared.playRoom?.slots.find(slot=>slot.id==='keepsake-2')?.value).toEqual({kind:'keepsake',id:'plant'});});
 it('preserves room tombstones through old-book restore and activity reset',async()=>{const h=initial(),point=(await appendRestorePoint(h,'MEM-001')).restorePoints![0]!;let next=play(h,operation).household;next=play(next,{...operation,expectedRevision:1,value:null}).household;for(const restored of [applyRestorePoint(next,point,'MEM-001'),eraseDevelopmentData(next)])expect(restored.playRoom).toEqual(next.playRoom);expect(()=>mergeShared(splitForSync(next,'MEM-001').shared,splitForSync(h,'MEM-001').shared)).toThrow('PLAY_REQUIRES_AUTHORITY');});
 it('does not present or reward legacy unbacked goal progress as money',()=>{
  const h=initial();h.goals=[{id:'legacy-bank',name:'Unbacked ambition',targetCents:10000,savedCents:10000,deadline:null,arrivalDate:null,shared:true,ownerMemberId:null,subcategoryId:null,status:'unfunded',funded:false,retiredAt:null,purchaseId:null,createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-01T00:00:00Z'}];
  h.goalContributions=[{id:'legacy-progress',goalId:'legacy-bank',memberId:'MEM-001',amountCents:10000,date:'2026-09-01',transferId:null,createdAt:'2026-09-01T00:00:00Z',updatedAt:'2026-09-01T00:00:00Z'}];
  expect(rewardEvidence(h,'MEM-001','lantern')).toBeNull();expect(playBankFacts(h,'legacy-bank','MEM-001')?.vaultCents).toBe(0);
 });
 it('rejects arbitrary scene URLs, sparse arrays and accessor objects',()=>{expect(()=>decodePlayRoom({...emptyPlayRoom(),url:'https://untrusted'})).toThrow();expect(()=>decodePlayPrivate({...emptyPlayPrivate(),discoveries:new Array(2)})).toThrow();const value={...emptyPlayPrivate()};Object.defineProperty(value,'sound',{get:()=>true});expect(()=>decodePlayPrivate(value)).toThrow();expect(()=>play(initial(),{kind:'claim',reward:'key',share:'yes'} as never)).toThrow('PLAY_INVALID_SHARE');});
});
