import {describe,it,expect} from 'vitest';
import {catalogHousehold,postEntry,addRecurrence,recordBillPayment} from '../src/core/index.ts';
import {prepareAction} from '../src/core/herculesActions.ts';
import {executeHerculesAction,cancelHerculesSubmission} from '../src/core/herculesExecution.ts';
import {commitCompanion,companionFor} from '../src/core/herculesCompanion.ts';
import {capturedIntent} from '../src/ledgerSync/capture.ts';
import {commandFromCapture,type Scope} from '../src/ledgerSync/protocol.ts';
import {prepareCommand} from '../src/ledgerSync/authority.ts';
import {splitForSync} from '../src/core/sync.ts';
function pending(){
 const h=catalogHousehold(),memberId='MEM-001',view='household' as const,today='2026-09-10',submissionId=crypto.randomUUID();
 const review=prepareAction({household:h,memberId,view,today},'expense',{amount:'24',date:today,accountId:'ACC-VISA',subcategoryId:'SUB-FOOD-GROCERIES',split:memberId,note:'Synthetic food'});
 const claimed=commitCompanion(h,{version:1,id:crypto.randomUUID(),scope:companionFor(h,memberId).scope,operation:{kind:'workflow.set',workflowId:'task-household',expectedRevision:0,view,generation:0,value:{version:1,actionId:'expense',view,generation:0,values:review.values,updatedAt:new Date().toISOString(),submission:{id:submissionId,review:JSON.stringify(review)}}}}).household;
 return{h,claimed,input:{memberId,view,today,submissionId,review}};
}
describe('Hercules authority claim',()=>{
 it('requires the exact claim and consumes it together with the accepted domain change',()=>{const {h,claimed,input}=pending();expect(()=>executeHerculesAction(h,input)).toThrow(/no longer pending/);const result=executeHerculesAction(claimed,input);expect(result.household.transactions).toHaveLength(h.transactions.length+1);expect(result.household.companionProfile?.workflows?.[0]?.value).toBeNull();expect(()=>executeHerculesAction(result.household,input)).toThrow();});
 it('cancels a claim before retry and cannot cancel an already consumed claim',()=>{const {claimed,input}=pending();const cancelled=cancelHerculesSubmission(claimed,input).household;expect(()=>executeHerculesAction(cancelled,input)).toThrow();const accepted=executeHerculesAction(claimed,input).household;expect(()=>cancelHerculesSubmission(accepted,input)).toThrow();});
 it('rejects altered values and changed accepted sources at authority execution',()=>{const {claimed,input}=pending();expect(()=>executeHerculesAction(claimed,{...input,review:{...input.review,values:{...input.review.values,amount:'25'}}})).toThrow(/review/);const changed=postEntry(claimed,{date:input.today,type:'expense',amount:'1',accountId:'ACC-VISA',subcategoryId:'SUB-FOOD-GROCERIES',createdBy:input.memberId}).household;expect(()=>executeHerculesAction(changed,input)).toThrow(/changed/);});
 it('retains unresolved identity when clearing chat and tombstones ordinary drafts',()=>{const {claimed,input}=pending();const cleared=commitCompanion(claimed,{version:1,id:crypto.randomUUID(),scope:companionFor(claimed,input.memberId).scope,operation:{kind:'conversation.clear',view:input.view,expectedGeneration:0}}).household;expect(cleared.companionProfile?.workflows?.[0]?.value).toMatchObject({generation:1,submission:{id:input.submissionId}});expect(()=>cancelHerculesSubmission(cleared,input)).not.toThrow();});
 it('replays as one typed command and binds submission identity on the server',async()=>{const {claimed,input}=pending();const scope:Scope={environment:claimed.environment,householdId:claimed.householdId,memberId:input.memberId,subject:'synthetic',role:'owner',expires:Date.now()+60000,aclEpoch:1};const one=splitForSync(claimed,input.memberId),two=splitForSync(claimed,'MEM-002');const state={sequence:claimed.revision,shared:one.shared,personal:new Map([[input.memberId,one.personal],['MEM-002',two.personal]])};const result=executeHerculesAction(structuredClone(claimed),input),capture=capturedIntent(result.household)!;expect(capture.steps.map(s=>s.kind)).toEqual(['executeHerculesAction']);const command=await commandFromCapture(capture,scope,input.submissionId);const accepted=await prepareCommand(state,command,scope,()=>{});expect(accepted.personal.companionProfile?.workflows?.[0]?.value).toBeNull();expect(accepted.receipt.postedIds).toHaveLength(1);await expect(prepareCommand(state,{...command,id:crypto.randomUUID()},scope,()=>{})).rejects.toThrow(/CONFIRMATION_ID_MISMATCH/);});
});
describe('actual bill payment',()=>{
 function bill(){const h=catalogHousehold();const added=addRecurrence(h,{cadence:'monthly',nextDate:'2026-09-01',type:'expense',amount:'50',accountId:'ACC-VISA',subcategoryId:'SUB-FOOD-GROCERIES',note:'Synthetic bill',splits:[{party:'MEM-001',amountCents:5000}]}).household;return {h:added,id:added.recurrences.at(-1)!.id};}
 it('uses actual payment details and advances from scheduled date without rewriting the template',()=>{const {h,id}=bill();const input={recurrenceId:id,occurrenceDate:'2026-09-01',paymentDate:'2026-09-03',amount:'47',accountId:'ACC-VISA',createdBy:'MEM-001'};const next=recordBillPayment(h,input).household;expect(next.transactions.at(-1)).toMatchObject({date:'2026-09-03',amountCents:4700});expect(next.recurrences.find(r=>r.id===id)).toMatchObject({nextDate:'2026-10-01',amountCents:5000,payments:[{paymentDate:'2026-09-03',amountCents:4700}]});expect(()=>recordBillPayment(next,input)).toThrow(/changed/);});
 it('matches existing evidence without a second transaction or duplicate occurrence',()=>{const {h,id}=bill();const posted=postEntry(h,{date:'2026-09-03',type:'expense',amount:'47',accountId:'ACC-VISA',subcategoryId:'SUB-FOOD-GROCERIES',createdBy:'MEM-001'});const next=recordBillPayment(posted.household,{recurrenceId:id,occurrenceDate:'2026-09-01',paymentDate:'2026-09-03',amount:'47',accountId:'ACC-VISA',createdBy:'MEM-001',matchTransactionId:posted.postedIds[0]});expect(next.household.transactions).toHaveLength(posted.household.transactions.length);expect(next.postedIds).toEqual([]);});
});

it.each(['household','personal'] as const)('accepts new %s Kitty plus private Plan and workflow release as one typed command',async(view)=>{
 const {planLifeFixture}=await import('./fixtures/plan-life.ts');const h=planLifeFixture(view),memberId='MEM-001',today='2026-09-11',submissionId=crypto.randomUUID();
 const review=prepareAction({household:h,memberId,view,today},'plan-guided-draft',{guideMode:'goal',monthKey:'2026-09',buildSource:'new-kitty',buildLabel:'Date night',buildTarget:'120',buildDeadline:'2026-09-25',buildPaydays:'Decide later',buildAmount:'60',buildDate:'2026-09-18',buildFunding:'unknown',buildStep:'Pick a date',constraints:'PRIVATE GOAL CONTEXT'});
 const claimed=commitCompanion(h,{version:1,id:crypto.randomUUID(),scope:companionFor(h,memberId).scope,operation:{kind:'workflow.set',workflowId:`task-${view}`,expectedRevision:0,view,generation:0,value:{version:1,actionId:review.actionId,view,generation:0,values:review.values,updatedAt:new Date().toISOString(),submission:{id:submissionId,review:JSON.stringify(review)}}}}).household;
 const scope:Scope={environment:claimed.environment,householdId:claimed.householdId,memberId,subject:'synthetic',role:'owner',expires:Date.now()+60000,aclEpoch:1};const one=splitForSync(claimed,memberId),two=splitForSync(claimed,'MEM-002'),state={sequence:claimed.revision,shared:one.shared,personal:new Map([[memberId,one.personal],['MEM-002',two.personal]])};
 const result=executeHerculesAction(structuredClone(claimed),{memberId,view,today,submissionId,review});expect(result.persistenceScope).toBeUndefined();expect(result.undo.commandKind).toBe('executeHerculesAction');expect(result.undo.snapshot).toEqual(claimed);
 const capture=capturedIntent(result.household)!;expect(capture.steps.map(s=>s.kind)).toEqual(['executeHerculesAction']);const command=await commandFromCapture(capture,scope,submissionId);const accepted=await prepareCommand(state,command,scope,()=>{});
 expect(accepted.personal.companionProfile?.workflows?.[0]?.value).toBeNull();expect(JSON.stringify(accepted.shared)).not.toContain('PRIVATE GOAL CONTEXT');expect(accepted.receipt.postedIds).toHaveLength(1);
 const goals=view==='household'?accepted.shared.goals:accepted.personal.goals;expect(goals?.some(g=>g.name==='Date night'&&g.savedCents===0)).toBe(true);expect(accepted.personal.planDrafts?.some(d=>d.lines.some(l=>l.labelSnapshot==='Date night'))).toBe(true);
});
