import {expect,it} from 'vitest';
import {createServer,transformWithEsbuild} from 'vite';
import {chromium} from '@playwright/test';
import {mkdir,readFile,writeFile,realpath} from 'node:fs/promises';
import {resolve} from 'node:path';
it('opens the renovation book from actual App and preserves books across themes and draft edits',async()=>{
 const appRoot=process.cwd(),out=process.env.HEARTH_ARTIFACTS_DIR??'/tmp/hearth-home-browser';await mkdir(out,{recursive:true});const fixture=await readFile(resolve('test/fixtures/hearthsideActualApp.ts'),'utf8');
 const server=await createServer({configFile:false,envFile:false,root:appRoot,cacheDir:out+'/vite-cache',logLevel:'error',esbuild:{jsx:'automatic'},optimizeDeps:{exclude:['@electric-sql/pglite']},worker:{format:'es'},define:{'import.meta.env.VITE_HEARTHSIDE':'"1"','import.meta.env.VITE_HEARTHSIDE_DESIGN':'"0"','import.meta.env.VITE_HEARTHSIDE_VAULT':'"0"','import.meta.env.VITE_HEARTHSIDE_WORKSPACE':'"0"','import.meta.env.VITE_HEARTHSIDE_GUESTS':'"0"','import.meta.env.VITE_HEARTHSIDE_AR':'"0"','import.meta.env.VITE_HEARTHSIDE_EXPORTS':'"0"','import.meta.env.VITE_LEDGER_SYNC_V2':'"0"','import.meta.env.VITE_LEDGER_SYNC_LOCAL_AUTH':'"0"','import.meta.env.VITE_PRODUCTION_CONTINUITY':'"0"','import.meta.env.VITE_HERCULES_PLAY':'"1"','import.meta.env.VITE_HERCULES_DRESSING_ROOM':'"1"','import.meta.env.VITE_HERCULES_WORKSPACE':'"1"'},server:{host:'127.0.0.1',port:0,fs:{allow:[appRoot,await realpath(appRoot+'/node_modules')]}},plugins:[{name:'actual-app-local-fixture',configureServer(vite){vite.middlewares.use(async(req,res,next)=>{
  if(req.url==='/__app_seed'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="en"><title>Synthetic local App seed</title><body>Preparing synthetic local books.</body></html>');return;}
  if(req.url?.split('?')[0]==='/test/fixtures/hearthsideActualApp.ts'){res.setHeader('Content-Type','application/javascript');res.end((await transformWithEsbuild(fixture.replaceAll("'../../","'/").replace("'./existing-books-onboarding.ts'","'/test/fixtures/existing-books-onboarding.ts'"),'fixture.ts')).code);return;}next();
 });}}]});await server.listen();
 const origin=`http://127.0.0.1:${(server.httpServer!.address() as {port:number}).port}`,browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),errors:string[]=[];
 page.on('pageerror',e=>errors.push(e.message));await context.route('**/*',route=>{const u=new URL(route.request().url());return u.origin!==origin||/^\/(api|ledger-sync|sync|hercules\/|bank\/|work\/|documents\/)/.test(u.pathname)?route.abort():route.continue();});
 try{
 await page.goto(origin+'/__app_seed');const initial=await page.evaluate("(async()=>{const m=await import('/test/fixtures/hearthsideActualApp.ts');return m.seedHearthsideActualApp();})()");await page.goto(origin+'/house/kitchen-table/above?household=HH-hearthside-app-synthetic&scope=household&surface=journey');await page.locator('.app[data-books-readiness="ready"]').waitFor({state:'attached',timeout:90000});const reminder=page.getByRole('button',{name:'Close reminders',exact:true});if(await reminder.count())await reminder.click();
 const entry=page.getByRole('button',{name:'⌂ Renovation book',exact:true});await entry.first().click();await page.getByRole('dialog').waitFor();
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});expect(await page.locator('dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await page.screenshot({path:out+`/classic-${width}.png`});}
 const placed=page.getByLabel('Select a placed furnishing',{exact:true});const target=await placed.boundingBox();expect(target!.height).toBeGreaterThanOrEqual(44);expect(target!.width).toBeGreaterThanOrEqual(44);await placed.selectOption({label:'Entry bench · My home · 1'});expect(await page.locator('.home-book__selection h2').innerText()).toBe('Entry bench');await page.getByRole('button',{name:'Store with contents',exact:true}).click();expect(await placed.locator('option').allTextContents()).not.toContain('Entry bench · My home · 1');await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Select My home',exact:true}).click();await page.setViewportSize({width:1440,height:1000});await page.getByRole('button',{name:'Preview project',exact:true}).first().click();await page.getByRole('button',{name:'Raise the frame',exact:true}).click();await page.getByRole('button',{name:'Fit the roof',exact:true}).click();await page.getByRole('button',{name:'Finish the room',exact:true}).click();await page.getByRole('button',{name:'Store with contents',exact:true}).click();await page.getByRole('button',{name:'Restore',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Redo',exact:true}).click();await page.getByRole('button',{name:'Discard draft and close',exact:true}).click();
 for(const theme of ['taylor','newfoundland']){await page.getByRole('button',{name:/Status Centre/}).first().click();const comfort=page.locator('#status-comfort');if(await comfort.count()&&!await comfort.evaluate(e=>(e as HTMLDetailsElement).open))await comfort.locator('summary').click();await page.locator(`[data-preview-theme="${theme}"]`).click();await page.getByRole('button',{name:'Use theme',exact:true}).click();await page.goto(origin+'/house/kitchen-table/above?household=HH-hearthside-app-synthetic&scope=household&surface=journey');await page.locator('.app[data-books-readiness="ready"]').waitFor({state:'attached',timeout:90000});if(await reminder.count())await reminder.click();await entry.first().click();await page.locator('.home-book--'+theme).waitFor();for(const width of [1440,390]){await page.setViewportSize({width,height:1000});expect(await page.locator('dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1)).toBe(true);await page.screenshot({path:out+`/${theme}-${width}.png`});}await page.getByRole('button',{name:'Discard draft and close',exact:true}).click();await page.setViewportSize({width:1440,height:1000});}
 const final=await page.evaluate("(async()=>{const m=await import('/test/fixtures/hearthsideActualApp.ts');return m.readHearthsideActualApp();})()");expect((final as {financialHash:string}).financialHash).toBe((initial as {financialHash:string}).financialHash);expect(errors).toEqual([]);await writeFile(out+'/evidence.json',JSON.stringify({errors,financialHashUnchanged:true,themes:['classic','taylor','newfoundland'],widths:[1440,390,320],authenticatedWrites:false}));
 }catch(error){await writeFile(out+'/failure.txt',await page.locator('body').innerText());await page.screenshot({path:out+'/failure.png'});throw error;}finally{await browser.close();await server.close();}
},180000);
