import * as THREE from 'three';
import {createHomeWorld} from '../src/home/world.ts';
import {splitForSync,assembleHousehold} from '../src/core/sync.ts';
import {describe,it,expect} from 'vitest';
import {catalogHousehold} from '../src/core/seed.ts';
import {commitPersonalLife} from '../src/hearthside/personalLifeCommands.ts';
import {decodePersonalLife} from '../src/hearthside/personalLifeContracts.ts';
import {decodeHearthside} from '../src/hearthside/contracts.ts';
import {starterHome,starterLayout,snapRoom,layoutIssues,decodeHome,exportBlueprint,clone,visibleObject} from '../src/home/model.ts';
import {homeProgress,grantHomeMilestones} from '../src/home/progression.ts';
import {acceptHome} from '../src/home/acceptance.ts';
import {claimHomePlot,HOME_PLOTS} from '../src/home/ownership.ts';
import {homeWalls,homeStairs,homeGeography,buildHomeArt} from '../src/home/geometry.ts';
import {homeSite,homeWorld} from '../src/home/site.ts';
import type {PlanVersion} from '../src/core/planSystem.ts';
import type {DateKey} from '../src/core/calendar.ts';
const today='2026-09-27' as DateKey;
const member='MEM-001';
function household(reviews=0){const h=catalogHousehold();h.planVersions=[];h.planReflections=[];for(let i=0;i<reviews;i++){const monthKey=`2026-${String(i+1).padStart(2,'0')}` as PlanVersion['monthKey'],id='plan-'+i;h.planVersions.push({id,scope:'household',monthKey,sequence:1,lines:[{id:'line-'+i} as PlanVersion['lines'][number]],assumptions:[],reason:'A useful plan',digest:'test',state:'active',createdBy:member,createdAt:monthKey+'-01T00:00:00.000Z',activatedAt:monthKey+'-01T00:00:00.000Z'});h.planReflections.push({id:'review-'+i,scope:'household',planVersionId:id,monthKey,outcomes:[],memberNotes:[],reviewedByMemberIds:[member],createdAt:monthKey+'-02T00:00:00.000Z',updatedAt:monthKey+'-02T00:00:00.000Z'});}return h;}
const value=(home=starterHome())=>({layout:home.layout,future:home.future,pinned:home.pinned,arrangements:home.arrangements});
function save(h=household(),home=starterHome(),actor=member,revision=0){return commitPersonalLife(h,{version:1,id:crypto.randomUUID(),scope:{environment:h.environment,householdId:h.householdId,memberId:actor},operation:{kind:'home.save',expectedRevision:revision,value:value(home)}});}
describe('Permanent, honest progression',()=>{
 it('credits historical distinct reviews once across reload and duplicate imports',()=>{const h=household(3);h.planReflections!.push({...h.planReflections![0]!,id:'duplicate'});const first=grantHomeMilestones(h,member,starterHome(),today);expect(first.awards.map(a=>a.id)).toEqual(['established','reading','garden','hosting','workshop','gallery']);expect(grantHomeMilestones(h,member,decodeHome(JSON.parse(JSON.stringify(first))),today)).toEqual(first);});
 it('does not count page activity, transaction volume or another member review',()=>{const h=household(3);expect(homeProgress(h,'MEM-002',starterHome(),today).find(p=>p.milestone.id==='reading')!.eligible).toBe(false);h.planReflections=[];expect(homeProgress(h,member,starterHome(),today).filter(p=>p.eligible).map(p=>p.milestone.id)).toEqual(['established']);});
 it('rejects scheduled and superseded-but-never-activated plans',()=>{const h=household(1);delete h.planVersions![0]!.activatedAt;h.planVersions![0]!.state='superseded';expect(homeProgress(h,member,starterHome(),today).some(p=>p.eligible)).toBe(false);});
 it('retains awards when honest corrections remove current evidence',()=>{const h=household(3),earned=grantHomeMilestones(h,member,starterHome(),today);h.planReflections=[];h.planVersions=[];const next=grantHomeMilestones(h,member,earned,today);expect(next.awards).toEqual(earned.awards);expect(homeProgress(h,member,next,today).find(p=>p.milestone.id==='garden')).toMatchObject({earned:true,eligible:false});});
 it('allows the member own personal review, never a partner private review',()=>{const h=household(1);h.planVersions![0]!.scope='personal';h.planVersions![0]!.ownerMemberId=member;h.planReflections![0]!.scope='personal';h.planReflections![0]!.ownerMemberId=member;expect(homeProgress(h,member,starterHome(),today)[1]!.eligible).toBe(true);h.planVersions![0]!.ownerMemberId='MEM-002';h.planReflections![0]!.ownerMemberId='MEM-002';expect(homeProgress(h,member,starterHome(),today).some(p=>p.eligible)).toBe(false);});
});
describe('Rooms, contents, circulation and recovery',()=>{
 it('migrates absent homes into a useful starter without touching an existing save',()=>{expect(layoutIssues(starterLayout())).toEqual([]);expect(decodeHome(undefined).layout.objects).toHaveLength(3);expect(()=>decodeHome({...starterHome(),version:2})).toThrow('newer Hearth');});
 it('snaps a real porch, moves its contents by room identity, stores and restores it',()=>{const l=starterLayout(),room=snapRoom(l,'porch','porch-1');expect(room.stored).toBe(false);l.rooms.push(room);l.objects.push({id:'bench-2',catalogueId:'bench',roomId:room.id,x:-1.5,z:-1.3,rotation:0,stored:false,variant:'hearth'});expect(l.objects[3]!.roomId).toBe('porch-1');room.stored=true;expect(visibleObject(l.objects[3]!,l)).toBe(false);room.stored=false;expect(visibleObject(l.objects[3]!,l)).toBe(true);expect(l.objects[3]!.id).toBe('bench-2');});
 it('rejects overlapping, disconnected and outside-plot construction',()=>{const l=starterLayout(),r=snapRoom(l,'porch','test');l.rooms.push({...r,x:0,z:0});expect(layoutIssues(l).some(s=>s.includes('overlaps'))).toBe(true);l.rooms[1]={...r,x:23,z:13};expect(layoutIssues(l).some(s=>s.includes('snap'))).toBe(true);l.rooms[1]={...r,x:40};expect(layoutIssues(l).some(s=>s.includes('inside'))).toBe(true);});
 it('opens corresponding adjoining walls and keeps a character-sized path',()=>{const l=starterLayout(),r=snapRoom(l,'nook','study');l.rooms.push(r);const walls=homeWalls(l),x=r.x>0?8:-8;expect(walls.some(w=>w.x===x&&w.z===0&&w.lintel)).toBe(true);const physics=homeGeography(l,{x:0,y:0,z:0});expect(physics.contact(x,0,0)).toBeNull();expect(physics.contact(x,2,0)).not.toBeNull();});
 it('has actual stair treads and a matching upper-floor opening',()=>{const l=starterLayout();l.rooms.push({...snapRoom(l,'upper','up'),stored:false});const stairs=homeStairs(l);expect(stairs).toHaveLength(1);const physics=homeGeography(l,{x:0,y:0,z:0}),s=stairs[0]!;const low=physics.surface(s.x,s.z-s.depth/2+.1,0),high=physics.surface(s.x,s.z+s.depth/2-.1,3.2);expect(low!.y).toBeGreaterThan(0);expect(high!.y).toBe(3.2);expect(physics.ceiling(s.x,s.z,0)).toBe(Infinity);});
 it('only allows earned objects in construction and accepts locked future blueprints',()=>{const h=household(),home=starterHome();home.future=clone(home.layout);home.future.rooms.push(snapRoom(home.future,'library','future-study'));expect(()=>acceptHome(h,member,undefined,0,value(home))).not.toThrow();home.layout=home.future;expect(()=>acceptHome(h,member,undefined,0,value(home))).toThrow('LOCKED');});
 it('preserves stored originals and rejects deletion of established identities',()=>{const h=household(),first=acceptHome(h,member,undefined,0,value());const next=clone(first);next.layout.objects.splice(0,1);expect(()=>acceptHome(h,member,first,1,value(next))).toThrow('STORE_OBJECT');});
 it('produces identical room footprint names at map and walk scale',()=>{const l=starterLayout();l.rooms.push(snapRoom(l,'porch','porch-1'));const map=buildHomeArt(l,{detail:'map'}),full=buildHomeArt(l,{detail:'full'});const names=(art:typeof map)=>art.group.children.filter(c=>c.name.startsWith('room:')).map(c=>c.name);expect(names(map)).toEqual(names(full));expect(names(map)).toContain('room:porch-1');map.dispose();full.dispose();});
});
describe('One private home and one plot per member',()=>{
 it('assigns distinct plots, preserves prior claims and refuses an eighth plot',()=>{let claims:ReturnType<typeof claimHomePlot>['claims']=[];for(let i=0;i<7;i++)claims=claimHomePlot(claims,'member-'+i).claims;expect(new Set(claims.map(c=>c.plotId)).size).toBe(7);expect(claimHomePlot(claims,'member-0').plotId).toBe(HOME_PLOTS[0]);expect(()=>claimHomePlot(claims,'member-8')).toThrow('FULL');});
 it('saves owner-only state, a minimal shared plot claim, and unchanged books',()=>{const h=household(),result=save(h),next=result.household;expect(next.personalLife?.ownerMemberId).toBe(member);expect(next.personalLife?.home?.revision).toBe(1);expect(next.hearthside?.homePlots).toEqual([{memberId:member,plotId:HOME_PLOTS[0]}]);expect(JSON.stringify(next.hearthside)).not.toContain('welcome-bench');expect(next.transactions).toEqual(h.transactions);expect(next.goals).toEqual(h.goals);expect(next.accounts).toEqual(h.accounts);expect(result.postedIds).toEqual([]);});
 it('allows a second member own home without overwriting the first assignment',()=>{const one=save().household;const second=save({...one,personalLife:undefined},starterHome(),'MEM-002').household;expect(second.personalLife!.ownerMemberId).toBe('MEM-002');expect(second.hearthside!.homePlots).toHaveLength(2);expect(second.hearthside!.homePlots![0]!.plotId).not.toBe(second.hearthside!.homePlots![1]!.plotId);});
 it('rejects inactive members, wrong ownership and stale revisions',()=>{const h=save().household;expect(()=>save(h)).toThrow('CHANGED');expect(()=>save(h,starterHome(),'MEM-002')).toThrow();h.members[0]!.active=false;expect(()=>save(h,starterHome(),member,1)).toThrow('SCOPE');});
 it('round-trips validated owner layouts and minimal shared claims',()=>{const next=save().household;expect(decodePersonalLife(JSON.parse(JSON.stringify(next.personalLife)),member)).toEqual(next.personalLife);expect(decodeHearthside(JSON.parse(JSON.stringify(next.hearthside)))).toEqual(next.hearthside);});
 it('rejects unknown pottery in future blueprints and saved arrangements',()=>{const home=starterHome();home.future=clone(home.layout);home.future.objects[1]!.display={kind:'piece',id:'private-secret',designId:'other-member',revision:1};expect(()=>acceptHome(household(),member,undefined,0,value(home))).toThrow('PIECE_UNAVAILABLE');});
 it('exports only anonymous geometry with no private notes or original-piece identities',()=>{const l=starterLayout();l.objects[1]!.display={kind:'piece',id:'original-1',designId:'private-design',revision:4};const exported=JSON.stringify(exportBlueprint(l));expect(exported).not.toContain('private-design');expect(exported).not.toContain('original-1');});
 it('reads the surveyed plot rotation and elevation instead of duplicating the baked height',()=>{const site=homeSite([{id:HOME_PLOTS[1],placeId:HOME_PLOTS[1],outline:[[0,0],[64,0],[64,44],[0,44]],door:{id:'door-test',xy:[32,44],height:19},rotationDegrees:-67}],HOME_PLOTS[1])!;expect(site.x).toBe(32);expect(site.y).toBe(19);expect(homeWorld(site,0,0)).toEqual({x:32,y:19,z:22});});
});

describe('Projection and private sync regression',()=>{
 it('keeps layouts out of shared and partner snapshots',()=>{const h=save().household,mine=splitForSync(h,member),partner=splitForSync(h,'MEM-002');expect(JSON.stringify(mine.shared)).not.toContain('welcome-bench');expect(partner.personal.personalLife).toBeUndefined();expect(assembleHousehold(mine.shared,mine.personal).personalLife?.home).toEqual(h.personalLife?.home);});
 it('updates the surveyed site when a first save claims a later plot',()=>{const reserves=HOME_PLOTS.slice(0,2).map((id,i)=>({id,placeId:id,outline:[[i*100,0],[i*100+64,0],[i*100+64,44],[i*100,44]] as [number,number][],door:{id:'door-'+i,xy:[i*100+32,44] as [number,number],height:10},rotationDegrees:0}));const world=createHomeWorld(new THREE.Scene(),reserves);world.set(starterLayout(),[],HOME_PLOTS[1]);expect(world.site?.x).toBe(132);expect(world.visit()?.x).toBe(132);world.dispose();});
 it('keeps furniture physical and reserves the actual upper stair footprint',()=>{const l=starterLayout(),physics=homeGeography(l,{x:0,y:0,z:0});expect(physics.contact(-5,5,0)?.id).toBe('home-object:welcome-bench');l.rooms.push({...snapRoom(l,'upper','up'),stored:false});l.objects[0]!.x=-2.75;l.objects[0]!.z=-2.75;expect(layoutIssues(l).some(e=>e.includes('stair flight'))).toBe(true);});
});
describe('Supported alternative milestone evidence',()=>{
 it('credits accepted historical starter budgets',()=>{const h=household();h.acceptedStarterPlans=[{id:'ONB-ADOPT-proof',proposalDigest:'proposal-v1-'+'a'.repeat(64),monthKey:'2026-09',memberIds:[member,'MEM-002'],plans:[{id:'budget-proof',active:true,monthKey:'2026-09',amountCents:1000,subcategoryId:'SUB-HOUSING-RENT'} as NonNullable<typeof h.acceptedStarterPlans>[number]['plans'][number]],acceptedAt:'2026-09-02T12:00:00.000Z'}];expect(homeProgress(h,member,starterHome(),today)[0]?.eligible).toBe(true);});
 it('uses an accepted standalone Studio firing and credits its actual author only',async()=>{const {createKittyDesignDocument,acceptKittyDesignOperation}=await import('../src/hearthside/design.ts');const {applyAcceptedDesignReference}=await import('../src/hearthside/designProjection.ts');const h=household(),scope={environment:h.environment,householdId:h.householdId,ownerMemberId:null};let doc=createKittyDesignDocument('home-gallery-proof',scope);const common={version:1,designId:doc.id,pieceId:'made-pot',gestureId:'make-pot'};doc=acceptKittyDesignOperation(doc,{...common,id:'create',kind:'create-piece',base:'cream'},{environment:scope.environment,householdId:scope.householdId,actorId:member,order:1,acceptedAt:'2026-09-01T12:00:00.000Z'}).document;let projected=applyAcceptedDesignReference(h,doc,null);expect(homeProgress(projected,member,starterHome(),today).find(p=>p.milestone.id==='gallery')?.eligible).toBe(false);doc=acceptKittyDesignOperation(doc,{...common,id:'fire',gestureId:'fire-pot',kind:'fire',expectedRevision:doc.revision},{environment:scope.environment,householdId:scope.householdId,actorId:member,order:2,acceptedAt:'2026-09-01T12:01:00.000Z'}).document;projected=applyAcceptedDesignReference(h,doc,null);expect(homeProgress(projected,member,starterHome(),today).find(p=>p.milestone.id==='gallery')?.eligible).toBe(true);expect(homeProgress(projected,'MEM-002',starterHome(),today).find(p=>p.milestone.id==='gallery')?.eligible).toBe(false);expect(projected.transactions).toEqual(h.transactions);});
 it('credits backed Fund allocations even though the separate savings counter is zero',async()=>{const {configureHouseholdFund,proposeHouseholdFundContribution,confirmHouseholdFundContribution,allocateHouseholdFundSurplus,addGoal}=await import('../src/core/index.ts');const {fundContributionReviewDigest}=await import('../src/core/fundContributionSources.ts');let h=configureHouseholdFund(household(),{custodianMemberId:member,openedOn:'2026-01-01',createdBy:member}).household;const proposal=proposeHouseholdFundContribution(h,{source:{version:1,kind:'external-received',explanation:'Synthetic local milestone test only.'},memberId:'MEM-002',contributorMemberId:'MEM-002',amount:'1000',date:'2026-09-01'});h=confirmHouseholdFundContribution(proposal.household,{received:true,expectedProposalDigest:fundContributionReviewDigest(proposal.household,proposal.postedIds[0]!),memberId:member,proposalEventId:proposal.postedIds[0]!}).household;h=addGoal(h,{name:'Fictional sanctuary goal',target:'100',shared:true,ownerMemberId:member}).household;const goal=h.goals.at(-1)!;h=allocateHouseholdFundSurplus(h,{memberId:member,date:'2026-09-02',allocations:[{goalId:goal.id,amount:'25'}]}).household;expect(h.goals.at(-1)!.savedCents).toBe(0);expect(homeProgress(h,member,starterHome(),today,goal.id).find(p=>p.milestone.id==='sanctuary')?.eligible).toBe(true);});
});
