import {expect,it} from 'vitest';
import {createServer,transformWithEsbuild} from 'vite';
import {chromium} from '@playwright/test';
import {mkdir,readFile,writeFile,realpath} from 'node:fs/promises';
import {resolve} from 'node:path';
it('walks the saved personal plot using the real Horizon body and dynamic collision',async()=>{
 const appRoot=process.cwd(),out='/tmp/hearth-home-island';await mkdir(out,{recursive:true});let fixture=await readFile(resolve('test/fixtures/hearthsideActualApp.ts'),'utf8');
 fixture=fixture.replace(" clearCapturedIntent(h);h.booksAcceptedHash=",` const {starterHome,snapRoom}=await import('../../src/home/model.ts');const {emptyPersonalLife}=await import('../../src/hearthside/personalLifeContracts.ts');const home=starterHome();home.revision=1;home.awards=[{id:'architecture',grantedAt:'2026-09-27'}];home.layout.rooms.push(snapRoom(home.layout,'porch','proof-porch'),snapRoom(home.layout,'upper','proof-upper'));h.personalLife={...emptyPersonalLife(APP_PROOF.memberId),home};h.hearthside!.homePlots=[{memberId:'MEM-001',plotId:'plot.terraces.1'},{memberId:APP_PROOF.memberId,plotId:'plot.terraces.2'}];clearCapturedIntent(h);h.booksAcceptedHash=`);
 const server=await createServer({configFile:false,envFile:false,root:appRoot,cacheDir:out+'/vite-cache',logLevel:'error',esbuild:{jsx:'automatic'},optimizeDeps:{exclude:['@electric-sql/pglite']},worker:{format:'es'},define:{'import.meta.env.VITE_HEARTH_HOUSE_WORLD':'"1"','import.meta.env.VITE_HEARTH_HARBOUR':'"1"','import.meta.env.VITE_HEARTHSIDE':'"1"','import.meta.env.VITE_HEARTHSIDE_DESIGN':'"0"','import.meta.env.VITE_HEARTHSIDE_VAULT':'"0"','import.meta.env.VITE_HEARTHSIDE_WORKSPACE':'"0"','import.meta.env.VITE_HEARTHSIDE_GUESTS':'"0"','import.meta.env.VITE_HEARTHSIDE_AR':'"0"','import.meta.env.VITE_HEARTHSIDE_EXPORTS':'"0"','import.meta.env.VITE_LEDGER_SYNC_V2':'"0"','import.meta.env.VITE_LEDGER_SYNC_LOCAL_AUTH':'"0"','import.meta.env.VITE_PRODUCTION_CONTINUITY':'"0"','import.meta.env.VITE_HERCULES_PLAY':'"1"','import.meta.env.VITE_HERCULES_DRESSING_ROOM':'"1"','import.meta.env.VITE_HERCULES_WORKSPACE':'"1"'},server:{host:'127.0.0.1',port:0,fs:{allow:[appRoot,await realpath(appRoot+'/node_modules')]}},plugins:[{name:'actual-app-local-fixture',configureServer(vite){vite.middlewares.use(async(req,res,next)=>{
  if(req.url==='/__app_seed'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="en"><title>Synthetic local App seed</title><body>Preparing synthetic local books.</body></html>');return;}
  if(req.url?.split('?')[0]==='/test/fixtures/hearthsideActualApp.ts'){res.setHeader('Content-Type','application/javascript');res.end((await transformWithEsbuild(fixture.replaceAll("'../../","'/").replace("'./existing-books-onboarding.ts'","'/test/fixtures/existing-books-onboarding.ts'"),'fixture.ts')).code);return;}next();
 });}}]});await server.listen();
 const origin=`http://127.0.0.1:${(server.httpServer!.address() as {port:number}).port}`,browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/*',route=>{const u=new URL(route.request().url());return u.origin!==origin||/^\/(api|ledger-sync|sync|hercules\/|bank\/|work\/|documents\/)/.test(u.pathname)?route.abort():route.continue();});
 try{await page.goto(origin+'/__app_seed');await page.evaluate("(async()=>{const m=await import('/test/fixtures/hearthsideActualApp.ts');return m.seedHearthsideActualApp();})()");await page.goto(origin+'/house/kitchen-table/above?household=HH-hearthside-app-synthetic&scope=household&surface=journey');await page.locator('.app[data-books-readiness="ready"]').waitFor({state:'attached',timeout:90000});const reminder=page.getByRole('button',{name:'Close reminders',exact:true});if(await reminder.count())await reminder.click();await page.getByRole('button',{name:'⌂ Renovation book',exact:true}).first().click();await page.getByRole('button',{name:'Visit my saved home',exact:true}).click();await page.waitForFunction(()=>Boolean((window as unknown as {__harbour?:unknown}).__harbour),{},{timeout:90000});
 const evidence=await page.evaluate(async()=>{const world=(window as unknown as {__harbour:import('../src/harbour/horizon/runtime/index.ts').HorizonRuntime}).__harbour;const plot=world.world.reserves.find(r=>r.id==='plot.terraces.2')!,site={x:plot.outline.reduce((s,p)=>s+p[0],0)/4,z:plot.outline.reduce((s,p)=>s+p[1],0)/4,y:('height' in plot.door?plot.door.height:0)??0,yaw:-plot.rotationDegrees*Math.PI/180};const homeLocal=(p:typeof site,x:number,z:number)=>({x:(x-p.x)*Math.cos(p.yaw)-(z-p.z)*Math.sin(p.yaw),z:(x-p.x)*Math.sin(p.yaw)+(z-p.z)*Math.cos(p.yaw)}),homeWorld=(p:typeof site,x:number,z:number)=>({x:p.x+x*Math.cos(p.yaw)+z*Math.sin(p.yaw),y:p.y,z:p.z-x*Math.sin(p.yaw)+z*Math.cos(p.yaw)});const visited=world.visitHome();await new Promise<void>((resolve,reject)=>{const start=Date.now();const check=()=>{if(world.airspaceReady(world.body().x,world.body().z))resolve();else if(Date.now()-start>20000)reject(Error('Plot terrain not ready'));else setTimeout(check,100);};check();});world.pause(false);const start=world.body();world.input({forward:1,strafe:0});const walked=world.simulateMotion(2).body;world.input({forward:0});const actions=world.homeActions();const arts=world.scene.children.filter(c=>c.name==='hearth-custom-home');const modules=arts.map(a=>a.children.filter(c=>c.name.startsWith('room:')).map(c=>c.name));const at=homeWorld(site,-2.65,-3.9);world.restore({world:'horizon:horizon-geo-1',geo:'horizon-geo-1',place:'court',...at,yaw:site.yaw});world.input({forward:1});const upstairs=world.simulateMotion(2.4).body;world.input({forward:0});return{visited,start:homeLocal(site,start.x,start.z),walked:homeLocal(site,walked.x,walked.z),actions,modules,upstairs:upstairs.y-site.y};});
 expect(await page.locator('.app').getAttribute('data-books-readiness')).toBe('ready');expect(await page.locator('.horizon-shell').evaluate(e=>e.getBoundingClientRect().height>=innerHeight*.9)).toBe(true);await page.screenshot({path:out+'/island.png'});await writeFile(out+'/evidence.json',JSON.stringify({evidence,errors},null,2));expect(evidence.visited).toBe(true);expect(evidence.start.z).toBeCloseTo(15,1);expect(evidence.walked.z).toBeLessThan(11);expect(evidence.actions.some(a=>a.id==='home-workspace:home')).toBe(true);expect(evidence.modules).toHaveLength(2);expect(evidence.modules[0]).toEqual(evidence.modules[1]);expect(evidence.upstairs).toBeCloseTo(3.2,1);expect(errors).toEqual([]);
 }catch(error){await writeFile(out+'/failure.txt',await page.locator('body').innerText());await page.screenshot({path:out+'/failure.png'});throw error;}finally{await browser.close();await server.close();}
},150000);
