// @vitest-environment jsdom
import {act,createElement} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {afterEach,beforeAll,describe,expect,it,vi} from 'vitest';
import KitchenHUD from '../src/harbour/horizon/kitchen/KitchenHUD.tsx';
import {createKitchenEngine} from '../src/harbour/horizon/kitchen/model.ts';
import {stationsFor} from '../src/harbour/horizon/kitchen/config.ts';
import type {KitchenView} from '../src/harbour/horizon/kitchen/types.ts';

beforeAll(()=>{(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;});
let root:Root|null=null,host:HTMLDivElement|null=null;
afterEach(()=>{act(()=>root?.unmount());host?.remove();root=null;host=null;});
function fixture(service:'first'|'lunch'|'practice'='lunch',players:1|2=1){const engine=createKitchenEngine({canReach:()=>true});engine.open();engine.start(service,players);return engine;}
function viewFor(engine:ReturnType<typeof fixture>):KitchenView{return{state:engine.snapshot(),stations:stationsFor(engine.state()),connections:[{chef:0,kind:'keyboard',label:'Keyboard',connected:true},{chef:1,kind:'gamepad',label:'Controller 1',connected:true}],available:true,progress:{version:1,completed:{},best:{},unlocks:[]},storageWarning:false,tossTargets:{},targetLabels:{}};}
function render(view:KitchenView,onCommand=vi.fn(),onInput=vi.fn()){if(!host){host=document.createElement('div');document.body.append(host);root=createRoot(host);}act(()=>root!.render(createElement(KitchenHUD,{view,onCommand,onInput})));return{host:host!,onCommand,onInput};}
function button(label:string){return [...host!.querySelectorAll('button')].find(b=>b.textContent?.includes(label))!;}
function click(element:HTMLElement){act(()=>element.click());}
function pointer(element:Element|Window,type:string,id=1,extra:MouseEventInit={}){const event=new MouseEvent(type,{bubbles:true,cancelable:true,...extra});Object.defineProperty(event,'pointerId',{value:id});act(()=>element.dispatchEvent(event));}

describe('Yacht Kitchen presentation reads real service state',()=>{
  it('never offers remote start and only opens a physically available menu',()=>{const engine=createKitchenEngine(),view=viewFor(engine);view.available=false;const {onCommand}=render(view);expect(host!.textContent).toBe('');view.available=true;render(view,onCommand);click(button('Menu board'));expect(onCommand).toHaveBeenCalledWith({type:'open'});expect(onCommand).not.toHaveBeenCalledWith(expect.objectContaining({type:'start'}));});
  it('offers all five services and blocks co-op selection until two controls connect',()=>{const engine=createKitchenEngine();engine.open();const view=viewFor(engine);view.connections[1]!.connected=false;const {onCommand}=render(view);expect(host!.querySelectorAll('input[name="kitchen-service"]')).toHaveLength(5);click([...host!.querySelectorAll<HTMLInputElement>('input[name="kitchen-players"]')][1]!);expect(button('Set the table').disabled).toBe(true);view.connections[1]!.connected=true;render(view,onCommand);expect(button('Set the table').disabled).toBe(false);click(button('Set the table'));expect(onCommand).toHaveBeenCalledWith(expect.objectContaining({type:'start',players:2}));});
  it('offers a deliberate resume or restart for an interrupted service',()=>{const engine=createKitchenEngine();engine.open();const view=viewFor(engine);view.resumable=true;const {onCommand}=render(view);click(button('Resume service'));click(button('Start fresh'));expect(onCommand.mock.calls.map(c=>c[0].type)).toEqual(['resume-saved','discard-saved']);});
  it('starts relaxed practice with extra cooking time and optional fires off',()=>{const engine=createKitchenEngine();engine.open();const {onCommand}=render(viewFor(engine));click([...host!.querySelectorAll<HTMLInputElement>('input[name="kitchen-service"]')][4]!);click(button('Set the table'));expect(onCommand).toHaveBeenCalledWith(expect.objectContaining({type:'start',service:'practice',assists:expect.objectContaining({forgiveness:2,hazards:false})}));});
  it('shows the actual interrupted-session warning without mislabelling it as storage failure',()=>{const engine=createKitchenEngine();engine.open();const view=viewFor(engine);view.storageWarning='The interrupted service no longer fits this galley. Start a fresh service.';render(view);expect(host!.textContent).toContain(view.storageWarning);expect(host!.textContent).not.toContain('cannot save');});
  it('each connected chef readies independently and disconnected chefs cannot ready',()=>{const engine=fixture('lunch',2),view=viewFor(engine);view.connections[1]!.connected=false;const {onCommand}=render(view);click(button('Ready, Chef 1'));expect(onCommand).toHaveBeenCalledWith({type:'action',chef:0,action:{type:'ready'}});expect(button('Ready, Chef 2').disabled).toBe(true);});
  it('guided orders show no fake deadline and practice has an explicit finish',()=>{const engine=fixture('first');engine.action(0,{type:'ready'});render(viewFor(engine));expect(host!.textContent).toContain('Take your time');expect(host!.textContent).not.toContain('0s');const practice=fixture('practice');practice.action(0,{type:'ready'});const {onCommand}=render(viewFor(practice));click(button('Finish practice'));expect(onCommand).toHaveBeenCalledWith({type:'action',chef:0,action:{type:'ready'}});});
  it('shared pause names the interruption and leaves a path back to one chef',()=>{const engine=fixture('lunch',2);engine.action(0,{type:'ready'});engine.action(1,{type:'ready'});engine.pause('Controller 1 disconnected. Both chefs are paused.');const {onCommand}=render(viewFor(engine));expect(host!.textContent).toContain('Shared service paused');expect(host!.textContent).toContain('Controller 1 disconnected');click(button('Continue with one chef'));expect(onCommand).toHaveBeenCalledWith({type:'leave-partner'});});
  it('retains held touch movement across a fresh parent callback and releases outside the pad',()=>{const engine=fixture();engine.action(0,{type:'ready'});const view=viewFor(engine),first=vi.fn(),latest=vi.fn(),command=vi.fn();render(view,command,first);const pad=host!.querySelector('.kitchen-stick')!;vi.spyOn(pad,'getBoundingClientRect').mockReturnValue({left:0,top:0,width:100,height:100,right:100,bottom:100,x:0,y:0,toJSON(){}});pointer(pad,'pointerdown',7,{clientX:50,clientY:10});expect(first).toHaveBeenLastCalledWith(0,{x:0,z:1});first.mockClear();render({...view,state:engine.snapshot()},command,latest);expect(first).not.toHaveBeenCalled();expect(latest).not.toHaveBeenCalled();pointer(window,'pointerup',7);expect(latest).toHaveBeenLastCalledWith(0,{x:0,z:0});});
  it('hold preparation supports keyboard press/release without synthetic tapping',()=>{const engine=fixture();engine.state().assists.prep='hold';engine.action(0,{type:'ready'});const {onInput}=render(viewFor(engine)),prepare=button('Hold to prepare');act(()=>prepare.dispatchEvent(new KeyboardEvent('keydown',{key:' ',bubbles:true,cancelable:true})));expect(onInput).toHaveBeenLastCalledWith(0,{prepareHeld:true});act(()=>prepare.dispatchEvent(new KeyboardEvent('keyup',{key:' ',bubbles:true,cancelable:true})));expect(onInput).toHaveBeenLastCalledWith(0,{prepareHeld:false});});
  it('presents held ingredients and a persistent ready-food warning from game state',()=>{const engine=fixture();engine.action(0,{type:'ready'});const pantry=stationsFor(engine.state()).find(s=>s.id==='yacht.galley.pantry')!;engine.setPose(0,{...pantry.approach,yaw:pantry.facing});engine.action(0,{type:'interact',target:pantry.id,ingredient:'bread'});const held=engine.state().chefs[0]!.held!;expect(held).not.toBeNull();const hob=stationsFor(engine.state()).find(s=>s.id==='yacht.galley.hob')!;engine.setPose(0,{...hob.approach,yaw:hob.facing});engine.action(0,{type:'interact',target:hob.id});engine.update(17);render(viewFor(engine));expect(host!.textContent).toMatch(/[Bb]read/);expect(host!.textContent).toContain('Ready · burning soon');});
});
