import {describe,it,expect,beforeAll} from 'vitest';
import {readFileSync} from 'node:fs';
import {createFleet,HANDLING,CRAFT_IDS,toWorld,toLocal,type CraftId,type WaterEnv} from '../src/harbour/horizon/movers/fleet/model.ts';
import {FLOORS,FIXTURES,GALLEY,SEATS,ROOMS,inside,BOARDING,HELM,DECK,floorHeight} from '../src/harbour/horizon/movers/fleet/layout.ts';
import {createHorizonGeography} from '../src/harbour/horizon/runtime/geography.ts';
import {decodeTerrainAsset} from '../src/harbour/horizon/land/terrain/asset.ts';
import {parseHorizonDefinition} from '../src/house/world/horizonAssets.ts';
import {createGliderEnv} from '../src/harbour/horizon/movers/glider/env.ts';
import {resolveTouchdown} from '../src/harbour/horizon/movers/glider/landing.ts';
import {waterHeightAt} from '../src/harbour/horizon/land/water/index.ts';
const water:WaterEnv={water:()=>0,ground:()=>-12,blocked:()=>false,width:2200,depth:1800};
const neutral={forward:0,steer:0,jump:false};
const pilot=(f:ReturnType<typeof createFleet>,id:CraftId)=>{const v=f.get(id);v.anchor=false;f.drive(id,neutral);return v;};
function run(id:CraftId,fps:number){const f=createFleet(water),v=pilot(f,id);v.x=1850;v.z=1200;for(let n=0;n<12*fps;n++){f.drive(id,{forward:1,steer:n>=8*fps?.2:0,jump:false});f.step(1/fps);}return v;}
describe('one watercraft simulation, distinct handling',()=>{
 for(const id of CRAFT_IDS)it(`${id}: 20/30/60/120 fps agree`,()=>{const a=run(id,120);expect(a.speed).toBeGreaterThan(HANDLING[id].max*.9);for(const fps of[20,30,60]){const b=run(id,fps);expect(b.x).toBeCloseTo(a.x,1);expect(b.z).toBeCloseTo(a.z,1);expect(b.speed).toBeCloseTo(a.speed,4);}});
 it('motorboat is fastest, kayak tightest, yacht deliberate',()=>{expect(run('motorboat',60).speed).toBeGreaterThan(run('dinghy',60).speed*1.8);expect(HANDLING.kayak.turn).toBeGreaterThan(HANDLING.yacht.turn*5);expect(HANDLING.yacht.accel).toBeLessThan(HANDLING.kayak.accel);});
 it('Space brakes even with throttle held; reverse remains capped',()=>{const f=createFleet(water),v=pilot(f,'motorboat');v.speed=12;for(let i=0;i<240;i++){f.drive(v.id,{forward:1,steer:0,jump:true});f.step(1/60);}expect(v.speed).toBe(0);for(let i=0;i<240;i++){f.drive(v.id,{forward:-1,steer:0,jump:false});f.step(1/60);}expect(v.speed).toBeCloseTo(-HANDLING.motorboat.reverse);});
 it('low bridges admit small boats but stop the yacht superstructure',()=>{const f=createFleet({...water,ceiling:()=>4});for(const v of f.vessels)expect(f.navigable(v,v.x,v.z),v.id).toBe(v.id!=='yacht');});
 it('minor contact stops propulsion without launching or spinning',()=>{const f=createFleet({...water,blocked:(x,_z)=>x>1540}),v=pilot(f,'dinghy');v.yaw=Math.PI/2;for(let i=0;i<600;i++){f.drive(v.id,{forward:1,steer:0,jump:false});f.step(1/60);}expect(v.x).toBeLessThan(1540);expect(Math.abs(v.y)).toBeLessThan(.15);expect(v.turn).toBe(0);});
 it('leaving helm retains motion, anchor settles it predictably',()=>{const f=createFleet(water),v=pilot(f,'yacht');v.speed=4;const p=f.seatBody(v);expect(f.actions(p).some(a=>a.id==='anchor')).toBe(true);f.act('leave-helm',p);f.step(.05);expect(v.speed).toBeGreaterThan(3.9);expect(v.z).toBeGreaterThan(1340);f.act('anchor',{...toWorld(v,{...HELM,x:1.6}),yaw:0});for(let i=0;i<600;i++)f.step(1/60);expect(v.speed).toBe(0);const at=v.z;f.step(.25);expect(v.z).toBe(at);});
});
describe('physical boarding, mooring and two real kayak seats',()=>{
 it('never offers yacht or remote helm on land',()=>{const f=createFleet(water),b={x:1523,y:1.2,z:1276,yaw:0};expect(f.actions(b).some(a=>a.craft==='yacht')).toBe(false);expect(f.act('helm',b)).toBeNull();});
 it('either kayak seat can be used by a single person',()=>{const f=createFleet(water),v=f.get('kayak');for(const i of[0,1]){const b={...toWorld(v,HANDLING.kayak.seats[i]!),yaw:0};const out=f.act('board-kayak-'+i,b);expect(out?.board).toBe('kayak');expect(f.get('kayak').seat).toBe(i);f.act('leave-kayak',f.seatBody(v));}});
 for(const id of ['kayak','dinghy','motorboat'] as const)it(`${id} can secure at stern and return`,()=>{const f=createFleet(water),v=pilot(f,id);v.x=1620;v.z=1314;const out=f.act('moor-'+id,f.seatBody(v));expect(out?.leave).toBe(true);expect(v.moored).toBe(true);expect(f.support(out!.body!)).not.toBeNull();const boarding={...toWorld(f.yacht,BOARDING),yaw:0};expect(f.act('return-'+id,boarding)?.board).toBe(id);expect(v.moored).toBe(false);});
 it('a companion occupies the other usable kayak seat locally',()=>{const f=createFleet(water),v=f.get('kayak');f.act('board-kayak-0',f.seatBody(v));f.act('kayak-companion',f.seatBody(v));expect(v.passenger).toBe(true);f.act('swap-seat',f.seatBody(v));expect(v.seat).toBe(1);expect(v.passenger).toBe(true);});
 it('ladder requires physical reach',()=>{const f=createFleet(water);expect(f.act('ladder',{x:0,y:0,z:0,yaw:0})).toBeNull();const b={...toWorld(f.yacht,{x:0,y:-.5,z:-23.5}),yaw:0};const out=f.act('ladder',b)!.body!;expect(f.support(out)).not.toBeNull();expect(f.actions(out).some(a=>a.id==='ladder')).toBe(false);});
});
describe('yacht floors, interiors and future galley',()=>{
 it('rigid transform preserves positions through moving and turning',()=>{const f=createFleet(water),v=f.yacht,p={x:4,y:DECK.main,z:10};const w=toWorld(v,p);v.x+=14;v.z-=12;v.yaw=Math.PI/3;const carried=toWorld(v,toLocal({...v,x:v.x-14,z:v.z+12,yaw:0},w));const local=toLocal(v,carried);expect(local.x).toBeCloseTo(p.x,8);expect(local.y).toBeCloseTo(p.y,8);expect(local.z).toBeCloseTo(p.z,8);});
 it('selects stacked decks under the feet, never floors above',()=>{const f=createFleet(water);for(const y of[DECK.lower,DECK.main,DECK.upper]){const p=toWorld(f.yacht,{x:0,y,z:6});expect(f.surface(p.x,p.z,p.y,.01)?.y).toBeCloseTo(y);}});
 for(const stair of FLOORS.filter(f=>f.rise))it(`${stair.id} has character headroom for its entire flight`,()=>{const f=createFleet(water);for(const d of FIXTURES.filter(f=>f.kind==='door'))f.doors.add(d.id);for(let z=stair.z0+.1;z<stair.z1;z+=.15){const p=toWorld(f.yacht,{x:(stair.x0+stair.x1)/2,y:floorHeight(stair,z),z});expect(f.ceiling(p.x,p.z,p.y)-p.y,`${stair.id} at ${z}`).toBeGreaterThan(1.25);expect(f.contact(p.x,p.z,p.y),`${stair.id} at ${z}`).toBeNull();}});
 it('all station approaches and seat standing positions fit the character',()=>{const f=createFleet(water);for(const p of[...GALLEY.map(s=>s.approach),...SEATS.map(s=>s.stand)]){const w=toWorld(f.yacht,p);expect(f.contact(w.x,w.z,w.y),JSON.stringify(p)).toBeNull();expect(f.support(w),JSON.stringify(p)).not.toBeNull();}});
 it('a door cannot close through its occupant and trap them',()=>{const f=createFleet(water),b={...toWorld(f.yacht,{x:0,y:DECK.lower,z:-20}),yaw:0};f.act('transom-door',b);f.act('transom-door',b);expect(f.doors.has('transom-door')).toBe(true);});
 it('every room and interaction connects from boarding through initially closed doors',()=>{
  const f=createFleet(water),nodes=new Map<string,{key:string;ix:number;iz:number;x:number;y:number;z:number}>(),columns=new Map<string,{key:string;ix:number;iz:number;x:number;y:number;z:number}[]>();
  for(const d of FIXTURES.filter(f=>f.kind==='door'))f.doors.add(d.id);
  for(let ix=-28;ix<=28;ix++)for(let iz=-92;iz<=80;iz++)for(const floor of FLOORS){const x=ix/4,z=iz/4;if(!inside(floor,x,z))continue;const y=floorHeight(floor,z),p=toWorld(f.yacht,{x,y,z});if(f.contact(p.x,p.z,p.y,.35)||(f.surface(p.x,p.z,p.y,.48)?.y??-100)>p.y+.02)continue;const key=ix+','+iz+','+y.toFixed(4);if(nodes.has(key))continue;const node={key,ix,iz,x,y,z};nodes.set(key,node);const a=columns.get(ix+','+iz)??[];a.push(node);columns.set(ix+','+iz,a);}
  f.doors.clear();const start=[...nodes.values()].find(n=>n.x===0&&n.z===-22&&n.y===DECK.lower)!;const queue=[start],seen=new Set([start.key]),actions=new Set<string>();
  for(let i=0;i<queue.length;i++){const n=queue[i]!,b={...toWorld(f.yacht,n),yaw:0};for(const a of f.actions(b)){actions.add(a.id);if(a.kind==='door'&&a.label.startsWith('Open ')){f.act(a.id,b);queue.push(...[...nodes.values()].filter(p=>seen.has(p.key)));}}
   for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]])for(const next of columns.get((n.ix+dx!)+','+(n.iz+dz!))??[]){const p=toWorld(f.yacht,next);if(seen.has(next.key)||Math.abs(next.y-n.y)>.3||f.contact(p.x,p.z,p.y,.35))continue;seen.add(next.key);queue.push(next);}}
  for(const id of['helm','anchor',...SEATS.map(s=>s.id),...GALLEY.map(s=>s.id),...FIXTURES.filter(f=>f.kind==='door').map(f=>f.id)])expect(actions.has(id),id).toBe(true);
  const reached=[...nodes.values()].filter(n=>seen.has(n.key));for(const [name,p]of Object.entries(ROOMS))expect(Math.min(...reached.filter(n=>Math.abs(n.y-p.y)<.15).map(n=>Math.hypot(n.x-p.x,n.z-p.z))),name).toBeLessThan(1.65);
 });
 it('all galley roles have stable unique hooks and .9m working surfaces',()=>{expect(new Set(GALLEY.map(s=>s.id)).size).toBe(GALLEY.length);for(const r of['storage','cold','prep','cook','plate','wash','waste','serve','return'])expect(GALLEY.some(s=>s.role===r)).toBe(true);for(const s of GALLEY)expect(s.surface.y-s.at.y).toBeCloseTo(.9);});
});
describe('atomic local restore',()=>{
 it('restores yacht-local support and secured boats together',()=>{const f=createFleet(water),v=pilot(f,'dinghy');v.x=1620;v.z=1314;const out=f.act('moor-dinghy',f.seatBody(v))!;const snap=f.snapshot(out.body);const next=createFleet(water),restore=next.restore(snap);expect(restore?.body).toEqual(out.body);expect(next.get('dinghy').moored).toBe(true);expect(next.vessels).toHaveLength(4);});
 it('restoration clears old optional state instead of merging it',()=>{const f=createFleet(water),s=JSON.parse(JSON.stringify(f.snapshot({...toWorld(f.yacht,BOARDING),yaw:0})));delete s.vessels[0].passenger;f.get('kayak').passenger=true;f.get('kayak').moor={x:999,y:0,z:999};expect(f.restore(s)).not.toBeNull();expect(f.get('kayak').passenger).toBe(false);expect(f.get('kayak').moor).toBeUndefined();});
 it('towed boats stop the yacht before reaching land and remain restorable',()=>{const f=createFleet({...water,ground:(_x,z)=>z<100?2:-12}),v=pilot(f,'dinghy');v.x=1620;v.z=1314;f.act('moor-dinghy',f.seatBody(v));f.yacht.z=150;f.yacht.anchor=false;f.drive('yacht',{...neutral,forward:-1});for(let i=0;i<2400;i++)f.step(1/60);const tender=f.get('dinghy');expect(tender.z-HANDLING.dinghy.length/2).toBeGreaterThanOrEqual(100);expect(f.restore(f.snapshot(f.seatBody(f.yacht)))).not.toBeNull();});
 it('rejects blocked local bodies and disconnected seating atomically',()=>{for(const corrupt of[(s:any)=>{s.aboard='yacht';s.local={x:0,y:DECK.main,z:8,yaw:0};},(s:any)=>{delete s.aboard;delete s.local;s.seat='sun-seat';}]){const f=createFleet(water),s=f.snapshot({...toWorld(f.yacht,BOARDING),yaw:0});s.vessels[3]!.x+=20;corrupt(s);expect(f.restore(s)).toBeNull();expect(f.yacht.x).toBe(1620);}});
 it('rejects duplicate, nonfinite and out-of-hull records without partially mutating fleet',()=>{for(const corrupt of[(s:any)=>s.vessels[1].id='kayak',(s:any)=>{s.vessels[2].moored=true;s.vessels[2].moor={x:NaN,y:0,z:0};},(s:any)=>{s.aboard='yacht';s.local={x:999,y:0,z:0,yaw:0};}]){const f=createFleet(water),s=f.snapshot({...toWorld(f.yacht,BOARDING),yaw:0});corrupt(s);expect(f.restore(s)).toBeNull();expect(f.yacht.x).toBe(1620);}});
});
describe('actual island and ordinary parachute landing',()=>{
 let geo:ReturnType<typeof createHorizonGeography>,fleet:ReturnType<typeof createFleet>,world:any,cuts:any;
 beforeAll(()=>{const bytes=readFileSync('public/horizon/world/horizon-geo-1.json.gz'),bin=readFileSync('public/horizon/terrain/horizon-geo-1.bin');world=parseHorizonDefinition(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer);const field=decodeTerrainAsset(bin.buffer.slice(bin.byteOffset,bin.byteOffset+bin.byteLength) as ArrayBuffer,'full');cuts={...world.collision,solids:world.geometry.solids,diagnostics:[]};geo=createHorizonGeography(field,cuts);fleet=createFleet({ground:geo.ground,blocked:geo.blocked,width:field.width,depth:field.depth,water:(x,z)=>{for(const w of cuts.waters){const h=waterHeightAt(w,x,z);if(h!==null)return h;}return null;}});},120000);
 it('launch hulls and offshore yacht fit actual water and collision',()=>{for(const v of fleet.vessels)expect(fleet.navigable(v,v.x,v.z),v.id).toBe(true);});
 it('restore rejects a wet centre whose hull overlaps the dock',()=>{const s=fleet.snapshot({...toWorld(fleet.yacht,BOARDING),yaw:0});Object.assign(s.vessels[3]!,{x:1527,z:1276});expect(fleet.restore(s)).toBeNull();expect(fleet.yacht.x).toBe(1620);});
 it('all small hulls have a clear approach to the stern',()=>{for(const id of['kayak','dinghy','motorboat'] as const){const v=fleet.get(id);for(let i=0;i<40;i++){const t=i/40,x=1530+90*t,z=1276+38*t;expect(fleet.navigable(v,x,z,Math.atan2(90,38)),`${id} ${i}`).toBe(true);}}});
 it('shared flight geography lands a parachute on real decks without a checkpoint',()=>{const off=geo.addDynamic(fleet),env=createGliderEnv({world,geography:geo,cuts});for(const local of[{x:0,y:DECK.main,z:17},{x:2,y:DECK.upper,z:0},{x:0,y:DECK.lower,z:-22}]){const p=toWorld(fleet.yacht,local);const outcome=resolveTouchdown(env.landingContext(p.y),{...p,mode:'parachute'},{airspeed:2,sink:1,groundSpeed:2,flared:true});expect(outcome.kind).toBe('walkoff');expect(outcome.at[1]).toBeCloseTo(p.y);}off();});
});
