import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8");
const office = readFileSync(new URL("../src/Office.tsx", import.meta.url), "utf8");
const officePhone = readFileSync(new URL("../src/OfficePhone.tsx", import.meta.url), "utf8");
const officeWide = readFileSync(new URL("../src/OfficeWide.tsx", import.meta.url), "utf8");
const books = readFileSync(new URL("../src/Books.tsx", import.meta.url), "utf8");
const ledger = readFileSync(new URL("../src/Ledger.tsx", import.meta.url), "utf8");
const calendar = readFileSync(new URL("../src/Calendar.tsx", import.meta.url), "utf8");
const shift = readFileSync(new URL("../src/WorkShiftPage.tsx", import.meta.url), "utf8");
const css = readFileSync(new URL("../src/ledger-story.css", import.meta.url), "utf8");
const officeCss = readFileSync(new URL("../src/office-wide.css", import.meta.url), "utf8");
const styles = readFileSync(new URL("../src/styles.css", import.meta.url), "utf8");
const hercules = readFileSync(new URL("../src/Hercules.tsx", import.meta.url), "utf8");
const kitty = readFileSync(new URL("../src/KittyBanks.tsx", import.meta.url), "utf8");
const sit = readFileSync(new URL("../src/SitDownGuide.tsx", import.meta.url), "utf8");
const panel = readFileSync(new URL("../src/HouseholdFundPanel.tsx", import.meta.url), "utf8");
const experience = readFileSync(new URL("../src/core/ledgerExperience.ts", import.meta.url), "utf8");
const accountsUi = readFileSync(new URL("../src/Accounts.tsx", import.meta.url), "utf8");

describe("D-164 ledger story UI fences", () => {
  it("routes every tab through projectLedgerExperience and a mode-aware purpose banner", () => {
    expect(app).toContain("projectLedgerExperience");
    expect(app).toContain("<LedgerPurposeBanner");
    expect(app).toContain("showsLedgerPurposeBanner(tab)");
    expect(app).toContain("data-ledger-mode={view}");
    expect(app).toContain("experience.exportHousehold");
    expect(app).toContain("data-ledger-confirm-purpose");
    expect(experience).toContain("showsLedgerPurposeBanner");
  });

  it("folds Shared Story into the wide notebook and keeps OfficePhone structurally unchanged", () => {
    expect(office).toContain("sharedStory={sharedStory}");
    expect(office).toContain("personalStory={personalStory}");
    expect(office).not.toContain("Also on this desk");
    expect(officeWide).toContain("<SharedLedgerStory");
    expect(officeWide).toContain("<PersonalLedgerFolio");
    expect(officeWide).toContain("paperHomeMosaic");
    expect(officePhone).not.toContain("SharedLedgerStory");
    expect(officePhone).not.toContain("Fund free-to-spend");
    expect(officePhone).not.toContain("runHealthCheck");
    expect(office).not.toContain('emitOfficeIntent({ type: "expand", id: "fund"');
    expect(css).toContain("min-width: 720px");
    expect(css).toContain("max-width: 899px");
    expect(officeCss).toMatch(/@media \(max-width: 899px\)[\s\S]*\.office-wide\.is-shared-home \.office-wide-desk \{\s*grid-template-columns: 1fr;/);
    expect(css).toContain("max-width: 719px");
    expect(css).toContain("strong.negative");
    expect(css).toContain("grid-template-areas");
  });

  it("keeps writers on the accepted snapshot and Add pickers on the scoped list", () => {
    expect(app).toContain("restoreAcceptedSnapshot");
    expect(app).toContain("persistLedgerWrite");
    expect(app).toContain("booksHousehold={household}");
    expect(app).toContain("projectHouseholdFund(household, today)");
    expect(app).toContain("? experience.scopedHousehold.accounts.filter((account) => account.active)");
    expect(app).not.toContain("pickerAccounts = displayHousehold.accounts");
    expect(app).toContain("healthFindings");
    expect(app).toContain("experience.herculesHousehold");
    expect(app).toContain("Choose who is using this ledger before exporting.");
    expect(app).toContain("Fund free-to-spend");
    expect(books).toContain("booksPresentationFloor(booksHousehold, memberId, view)");
    expect(books).toContain("compileHousehold(auditHousehold)");
    expect(books).not.toContain("compileHousehold(booksHousehold)");
    expect(books).not.toContain("compileHousehold(household)");
    expect(books).toContain("HouseholdFundPanel household={booksHousehold}");
    expect(books).toContain("closeBooksMonth(booksHousehold");
    expect(books).toContain("StatementsPane household={auditHousehold} writeHousehold={booksHousehold}");
    expect(books).toContain("AskBooks household={auditHousehold}");
    expect(books).not.toContain("queryBooks(");
    expect(books).toContain("Power SQL stays off scoped floors");
    expect(books).not.toContain("Run query");
    expect(books).not.toContain("books.chart[0]");
    expect(app).toContain("postDueRecurrences(current, today, ids)");
    expect(app).toContain("recurrenceIds");
    expect(office).toContain("integrityFindings");
    expect(office).toContain("buildSharedLedgerStory(booksHousehold");
    expect(office).toContain("PostcardBody household={booksHousehold}");
    expect(office).toContain("memberId={memberId} card={postcard}");
    expect(office).not.toContain("runHealthCheck(household)");
    expect(officeWide).toContain("PostcardBody household={booksHousehold}");
    expect(officeWide).toContain("memberId={memberId} card={postcard}");
    expect(officeWide).not.toContain("runHealthCheck");
    expect(panel).toContain("Fund free-to-spend");
    expect(panel).toContain("LEDGER_CUSTODY_DISCLOSURE");
    expect(panel).not.toContain("Free to spend");
  });

  it("gives Calendar, Shift, and Books a mode contract", () => {
    expect(calendar).toContain("view?: LedgerView");
    expect(calendar).toContain("calendar-stage");
    expect(calendar).not.toContain("hero calendar-hero");
    expect(shift).toContain("view?: LedgerView");
    expect(shift).toContain("worker-centered");
    expect(books).toContain("Household table");
    expect(books).toContain("My books");
    expect(books).toContain("On the table");
    expect(books).toContain("householdTableStory");
    expect(books).toContain("books-audit-office");
    expect(books).not.toContain("Together now");
    expect(books).not.toContain("Household story · double-entry");
    expect(books).not.toContain("kind=\"Books\"");
    expect(panel).toContain("<summary>Propose or confirm a contribution</summary>");
  });

  it("keeps Books off Shared primary nav and doors it from More", () => {
    expect(app).toContain("kitchenPrimaryNav(view)");
    expect(books).toContain("accepted-books position");
    expect(books).toContain("not a partner-hidden envelope");
    expect(books).not.toContain("Partner-personal stays out");
    expect(books).not.toContain("Partner Personal rows stay out");
    expect(books).toContain("walletForListedAccounts");
    expect(accountsUi).toContain("walletForListedAccounts");
    expect(app).not.toContain("Partner Personal rows stay out");
    expect(app).not.toContain("Open household table books");
    expect(app).not.toContain("Journal and Fund");
    expect(app).toContain('data-ledger-nav={view === "household" ? "shared" : "personal"}');
    expect(experience).toContain('return ["home", "calendar", "plan", "more"]');
    expect(experience).toContain('return ["home", "calendar", "shift", "ledger", "plan", "more"]');
    expect(app).toMatch(/>\s*Books\s*</);
    expect(styles).toContain(".nav[data-ledger-nav=\"personal\"]");
    expect(styles).toMatch(/\.nav\[data-ledger-nav="personal"\] \{\s*grid-template-columns: 1fr 1fr 1fr 56px 1fr 1fr 1fr;/);
  });

  it("replaces Plan Goals with Kitty Banks and keeps Shared Home as six tiles plus notebook", () => {
    expect(app).toContain("<KittyBanks");
    expect(app).not.toContain("Goals in this view");
    expect(app).not.toContain("Open Fund kitty");
    expect(app).not.toContain("Zero plan");
    expect(app).toContain("budget-remove");
    expect(kitty).toContain("Kitty Banks");
    expect(kitty).toContain("not a new envelope");
    expect(officeWide).toContain("is-shared-home");
    expect(officeWide).toContain("<KittyBanks");
    expect(officeWide).toContain("office-wide-stage");
    expect(officeWide).toContain("Leftover spend");
    expect(calendar).toContain("cal-titles");
    expect(calendar).toContain("cal-title");
    expect(calendar).toContain("calendar-board-stack");
    expect(calendar).not.toContain("calendar-wide-board");
    expect(sit).toContain("sitDownInfographicDeck");
    expect(sit).toContain("Leftover assignment lives on Shared");
    expect(sit).not.toContain("Household view plans for both of you.");
    expect(shift).toContain("Posted earnings");
    expect(shift).toContain("shiftEarningsTracker");
    expect(styles).toContain("overflow-y: auto");
    expect(styles).toContain(".shift-page .tabs button { min-height: 44px; }");
    expect(styles).toMatch(/\.hercules-bubble \{[\s\S]*background: var\(--card\)/);
    expect(hercules).toContain("hercules-pro-quiet");
    expect(hercules).toContain("helpAsked");
    expect(hercules).not.toContain("Use Hercules Pro");
    expect(books).toContain("askHercules(household, text, todayKey(), { memberId, view })");
    expect(kitty).toContain("function amountFor");
    expect(kitty).toContain("amounts[goalId]");
    expect(kitty).toContain("defaultOpen={false}");
    expect(kitty).toContain("data-kitty-step");
    expect(kitty).toContain("paper-bank");
    expect(books).toContain("booksPresentationFloor(booksHousehold, memberId, view)");
    expect(books).toContain("books-floor");
    expect(books).toContain("Shared is one account");
    expect(officeWide).toContain("posted in minus posted expenses");
    expect(officeWide).toContain("onGo(\"plan\")");
    expect(books).toContain("presentedTransactions={!sharedTable}");
    expect(ledger).toContain("presentedTransactions");
    expect(officePhone).toContain("Leftover spend");
    expect(officePhone).toContain('onGo("plan")');
    expect(calendar).toContain("dayOpen");
    expect(calendar).toContain("kind-${item.kind}");
    expect(shift).toContain("shift-earn-bubbles");
    expect(accountsUi).toContain("setPendingPost");
    expect(accountsUi).toContain("<ConfirmSheet");
    expect(kitty).toContain("account.scope !== \"personal\"");
  });
});
