import { describe,it,expect } from 'vitest';
import { planLifeFixture } from './fixtures/plan-life.ts';
import { actionById, findHerculesAction, prepareAction, executeReviewedAction, initialActionValues } from '../src/core/herculesActions.ts';
import { PLAN_GUIDE_ID, planGuideFields, guideAnswer, guideBack, guideQuestion, buildGuidedPlan, guideProjection } from '../src/core/planGuide.ts';
import { companionFor, commitCompanion } from '../src/core/herculesCompanion.ts';
const context=(view:'household'|'personal'='household')=>({household:planLifeFixture(view),memberId:'MEM-001',view,today:'2026-09-11'});
const open={monthKey:'2026-09',purpose:'Less scrambling',incomeSource:'skip',protectSource:'skip',prepareSource:'skip',buildSource:'skip',everydaySource:'skip',constraints:'Friday evenings stay free'};
describe('guided private Plan drafting',()=>{
 it.each(['Help me create a plan','Help us build our household plan','Can you help me make a budget?','Help me plan our month'])('starts the supported workflow for %s',message=>expect(findHerculesAction(message,context())?.id).toBe(PLAN_GUIDE_ID));
 it('uses the selected month and keeps all missing stages gradual',()=>{const c={...context(),planMonth:'2026-10'};const v=initialActionValues(actionById(PLAN_GUIDE_ID,c),'help me create a plan',c);expect(v).toMatchObject({monthKey:'2026-10'});expect(guideQuestion(c,v)?.key).toBe('purpose');expect(planGuideFields(c,open).every(f=>f.why.length>35)).toBe(true);expect(guideQuestion(c,open)).toBeUndefined();});
 it('reopens dependent answers when an earlier choice changes, without mutating the source',()=>{const c=context(),v={...open,protectSource:'unlinked',protectLabel:'Rent',protectAmount:'900',protectDate:'2026-09-15',protectOwner:'joint',protectFunding:'available'};const changed=guideAnswer(c,v,'protectSource','skip');expect(changed.protectAmount).toBeUndefined();expect(changed.prepareSource).toBeUndefined();expect(changed.purpose).toBe('Less scrambling');expect(v.protectAmount).toBe('900');expect(guideBack(c,v,'protectAmount').protectAmount).toBeUndefined();});
 it.each(['household','personal'] as const)('keeps existing %s decisions and explicit unknowns; preview never posts or shares',view=>{const c=context(view),before=structuredClone(c.household);const review=prepareAction(c,PLAN_GUIDE_ID,open);expect(c.household).toEqual(before);expect(review.rows.some(r=>r.value.includes('Everyday: kept existing allowance'))).toBe(true);const result=executeReviewedAction(c,review,crypto.randomUUID());expect(result.household.transactions).toEqual(before.transactions);expect(result.household.planVersions).toEqual(before.planVersions);const draft=result.household.planDrafts!.find(d=>d.ownerMemberId===c.memberId&&d.scope===view)!;expect(draft.lines).toEqual(before.planDrafts![0]!.lines);expect(draft.note).toContain('Friday evenings stay free');});
 it('does not invalidate review for private conversation saves, but does for changed Plan evidence',()=>{const c=context();c.household.companionProfile=companionFor(c.household,c.memberId);const review=prepareAction(c,PLAN_GUIDE_ID,open);const h=commitCompanion(c.household,{version:1,id:crypto.randomUUID(),scope:{environment:c.household.environment,householdId:c.household.householdId,memberId:c.memberId},operation:{kind:'workflow.set',workflowId:'task-household',expectedRevision:0,view:c.view,generation:0,value:{version:1,actionId:PLAN_GUIDE_ID,view:c.view,generation:0,values:open,updatedAt:new Date().toISOString(),submission:null}}}).household;expect(()=>executeReviewedAction({...c,household:h},review,crypto.randomUUID())).not.toThrow();h.planDrafts![0]!.lines[0]!.amountCents+=100;expect(()=>executeReviewedAction({...c,household:h},review,crypto.randomUUID())).toThrow(/changed/);});
 it('refuses a private partner bill even when its id is supplied directly',()=>{const c=context();c.household.accounts.push({...c.household.accounts[0]!,id:'partner-private',scope:'personal',ownerMemberId:'MEM-002'});c.household.recurrences.push({...c.household.recurrences[0]!,id:'private-bill',accountId:'partner-private'});const v={...open,protectSource:'private-bill',protectAmount:'40',protectDate:'2026-09-15',protectOwner:'joint',protectFunding:'available'};expect(planGuideFields(c,v).find(f=>f.key==='protectSource')!.choices!(c,v).some(r=>r.value==='private-bill')).toBe(false);expect(()=>prepareAction(c,PLAN_GUIDE_ID,v)).toThrow();});
 it('keeps an unlinked promise explicitly unlinked and reviews its consequence',()=>{const c=context();const v={...open,protectSource:'unlinked',protectLabel:'An estimate',protectAmount:'55',protectDate:'2026-09-18',protectOwner:'joint',protectFunding:'unknown'};const plan=buildGuidedPlan(c,v,'example');expect(plan.lines.at(-1)).toMatchObject({labelSnapshot:'An estimate',amountCents:5500});expect(plan.lines.at(-1)?.sourceReference).toBeUndefined();expect(prepareAction(c,PLAN_GUIDE_ID,v).rows.some(r=>r.value.includes('unlinked intention'))).toBe(true);});
});

describe('guided Plan existing evidence regressions',()=>{
 it('lets the second partner privately build from the shared version',()=>{const c={...context(),memberId:'MEM-002'};const before=structuredClone(c.household);const review=prepareAction(c,PLAN_GUIDE_ID,open);const result=executeReviewedAction(c,review,crypto.randomUUID());const draft=result.household.planDrafts!.find(d=>d.ownerMemberId==='MEM-002')!;expect(draft.lines.every(l=>l.createdBy==='MEM-002')).toBe(true);expect(result.household.planVersions).toEqual(before.planVersions);});
 it('groups weekly evidence and its dates without charging the same recurrence twice',()=>{const c=context('personal');c.household.planDrafts=[];c.household.planVersions=[];c.household.recurrences=[{...c.household.recurrences[0]!,cadence:'weekly',nextDate:'2026-09-13',amountCents:10000}];const v={...open,protectSource:'known',protectOwner:c.memberId,protectFunding:'available'};const built=buildGuidedPlan(c,v,'weekly');expect(built.lines).toHaveLength(1);expect(built.lines[0]).toMatchObject({amountCents:30000,decision:{contributionSchedule:[{date:'2026-09-13',amountCents:10000},{date:'2026-09-20',amountCents:10000},{date:'2026-09-27',amountCents:10000}]}});const p=guideProjection(c,{...v,lookThrough:'2026-09-30'});expect(p.lines[0]!.issues).toEqual([]);expect(p.lowPoint!.balanceCents).toBe(p.cashNowCents!-30000);expect(()=>prepareAction(c,PLAN_GUIDE_ID,v)).not.toThrow();});
 it('replaces a dated goal decision and clears superseded funding and schedules',()=>{const c=context();const row=c.household.planDrafts![0]!.lines.find(l=>l.lens==='prepare')!;row.decision={...row.decision,contributionSchedule:[{date:'2026-09-15',amountCents:30000}]};const v={...open,prepareSource:row.sourceReference!.id,prepareTarget:'1200',prepareDeadline:'2026-12-01',preparePaydays:'Decide later',prepareAmount:'250',prepareDate:'2026-09-18',prepareFunding:'unknown',prepareStep:'Get a quote'};const p=buildGuidedPlan(c,v,'updated');expect(p.lines.filter(l=>l.sourceReference?.id===row.sourceReference!.id)).toHaveLength(1);expect(p.lines.find(l=>l.id===row.id)).toMatchObject({amountCents:25000,dueDate:'2026-09-18'});const d=p.lines.find(l=>l.id===row.id)!.decision!;expect(d.funding).toBeUndefined();expect(d.paydays).toBeUndefined();expect(d.contributionSchedule).toBeUndefined();expect(()=>prepareAction(c,PLAN_GUIDE_ID,v)).not.toThrow();});
 it('distinguishes keeping previous income from explicitly choosing current money only',()=>{const c=context();c.household.planDrafts![0]!.assumptions=[{id:'expected',kind:'income',expectedDate:'2026-09-18',valueCents:100000,sourceReferences:[],observedAt:'2026-09-11T12:00:00.000Z',confidence:'estimated'}];expect(planGuideFields(c,open).find(f=>f.key==='incomeSource')!.choices!(c,open).find(o=>o.value==='skip')!.label).toBe('Keep my existing money assumptions');expect(buildGuidedPlan(c,open,'keep').assumptions).toHaveLength(1);expect(buildGuidedPlan(c,{...open,incomeSource:'current-only'},'remove').assumptions).toHaveLength(0);});
 it('asks for the month when the request starts outside Plan',()=>{const c=context();expect(guideQuestion(c,initialActionValues(actionById(PLAN_GUIDE_ID,c),'Help me create a plan',c))?.key).toBe('monthKey');});
});

it('retains the recorded amount of a paid occurrence when the next template amount differs',async()=>{const {postEntry}=await import('../src/core/commands.ts');const c=context('personal');c.household.planDrafts=[];c.household.planVersions=[];const bill=c.household.recurrences[0]!;bill.cadence='biweekly';bill.nextDate='2026-09-01';bill.amountCents=10000;const paid=postEntry(c.household,{type:'expense',date:'2026-09-01',amount:'80',accountId:'ACC-CHEQUING',subcategoryId:bill.subcategoryId,createdBy:c.memberId,visibility:'personal',source:'recurring',sourceId:bill.id});c.household=paid.household;c.household.recurrences[0]!.payments=[{occurrenceDate:'2026-09-01',paymentDate:'2026-09-01',amountCents:8000,accountId:'ACC-CHEQUING',transactionId:paid.postedIds[0]!,recordedBy:c.memberId}];c.household.recurrences[0]!.nextDate='2026-09-15';const v={...open,protectSource:'known',protectOwner:c.memberId,protectFunding:'available',lookThrough:'2026-09-30'};const built=buildGuidedPlan(c,v,'paid');expect(built.lines[0]!.decision!.contributionSchedule).toEqual([{date:'2026-09-01',amountCents:8000},{date:'2026-09-15',amountCents:10000},{date:'2026-09-29',amountCents:10000}]);const p=guideProjection(c,v);expect(p.lines[0]!.remainingCents).toBe(20000);expect(p.lowPoint!.balanceCents).toBe(p.cashNowCents!-20000);expect(()=>prepareAction(c,PLAN_GUIDE_ID,v)).not.toThrow();});
it('rescheduling one shared contribution offer replaces its previous expected arrival',async()=>{const {savePlanBridgeDraft,sharePlanBridgeDraft}=await import('../src/core/commands.ts');const c=context();c.household=savePlanBridgeDraft(c.household,{monthKey:'2026-09',kind:'contribution',label:'Fictional contribution',amountCents:100000,expectedDate:'2026-09-18',memberId:c.memberId,createdBy:c.memberId}).household;c.household=sharePlanBridgeDraft(c.household,{draftId:c.household.planBridgeDrafts![0]!.id,memberId:c.memberId,createdBy:c.memberId}).household;const source=c.household.planBridgeDecisions![0]!;c.household.planDrafts![0]!.assumptions=[{id:'old-date',kind:'income',valueCents:100000,expectedDate:'2026-09-18',sourceReferences:[{type:'bridge',id:source.id}],observedAt:'2026-09-11T12:00:00.000Z',confidence:'estimated'}];const v={...open,incomeSource:source.id,incomeAmount:'900',incomeDate:'2026-09-21'};const built=buildGuidedPlan(c,v,'changed');expect(built.assumptions).toHaveLength(1);expect(built.assumptions[0]).toMatchObject({valueCents:90000,expectedDate:'2026-09-21'});expect(()=>prepareAction(c,PLAN_GUIDE_ID,v)).not.toThrow();});
it('reviews and saves all four evidence-linked lenses from conversational answers',()=>{const c=context('personal'),rows=c.household.planDrafts![0]!.lines;const ref=(lens:string)=>rows.find(l=>l.lens===lens)!.sourceReference!.id;const v={...open,protectSource:ref('protect'),protectAmount:'900',protectDate:'2026-09-20',protectOwner:c.memberId,protectFunding:'available',prepareSource:ref('prepare'),prepareTarget:'1200',prepareDeadline:'2026-12-01',preparePaydays:'2026-09-15, 2026-10-01',prepareAmount:'150',prepareDate:'2026-09-15',prepareFunding:'available',prepareStep:'Get a quote',buildSource:ref('build'),buildTarget:'2000',buildDeadline:'2027-06-01',buildPaydays:'Decide later',buildAmount:'100',buildDate:'2026-09-25',buildFunding:'unknown',buildStep:'Compare two dates',everydaySource:ref('everyday'),everydayAmount:'400',everydayDate:'2026-09-11'};expect(guideQuestion(c,v)).toBeUndefined();const review=prepareAction(c,PLAN_GUIDE_ID,v);const result=executeReviewedAction(c,review,crypto.randomUUID());expect(result.household.planDrafts![0]!.lines).toHaveLength(4);expect(result.household.transactions).toEqual(c.household.transactions);expect(review.rows.some(r=>r.value.includes('Get a quote'))).toBe(true);expect(review.rows.some(r=>r.value.includes('2026-09-15, 2026-10-01'))).toBe(true);});

it('excludes a previous private payment from a now-shared bill’s suggestions and new schedule',()=>{const c=context();const r=c.household.recurrences[0]!;c.household.planDrafts=[];c.household.planVersions=[];r.payments=[{occurrenceDate:'2026-09-01',paymentDate:'2026-09-01',amountCents:123456,transactionId:'private-old-payment',accountId:'private-account',recordedBy:'MEM-002'}];c.household.transactions.push({...c.household.transactions[0]!,id:'private-old-payment',visibility:'personal',createdBy:'MEM-002',amountCents:123456});const v={...open,protectSource:'known',protectOwner:'joint',protectFunding:'available'};expect(JSON.stringify(planGuideFields(c,v))).not.toContain('2026-09-01');expect(buildGuidedPlan(c,v,'shared').lines[0]!.amountCents).toBe(90000);});

it('keeps one source owner across lenses instead of reusing a retained reserve in Build',()=>{const c=context('personal');const source=c.household.planDrafts![0]!.lines.find(l=>l.lens==='prepare')!.sourceReference!.id;const v={...open,buildSource:source,buildTarget:'1200',buildDeadline:'2026-12-01',buildPaydays:'Decide later',buildAmount:'100',buildDate:'2026-09-18',buildFunding:'available',buildStep:'Get a quote'};expect(planGuideFields(c,v).find(f=>f.key==='buildSource')!.choices!(c,v).some(o=>o.value===source)).toBe(false);expect(()=>prepareAction(c,PLAN_GUIDE_ID,v)).toThrow();expect(()=>buildGuidedPlan(c,v,'duplicate')).toThrow(/already supports/);});

it('keeps the selected horizon when going back or correcting an answer',()=>{const c=context(),v={...open,lookThrough:'2027-03-01'};expect(guideAnswer(c,v,'purpose','A different purpose').lookThrough).toBe(v.lookThrough);expect(guideBack(c,v,'purpose').lookThrough).toBe(v.lookThrough);});


describe('guided release corrections',()=>{
 it('requires choosing the Personal arrival, reschedules only that payday and rejects a duplicate date',()=>{
  const c=context('personal'),draft=c.household.planDrafts![0]!;
  const source={...c.household.recurrences[0]!,id:'personal-pay',type:'income' as const};c.household.recurrences.push(source);
  draft.assumptions=['2026-09-18','2026-09-30'].map((date,i)=>({id:`pay-${i}`,kind:'income',valueCents:100000,expectedDate:date,sourceReferences:[{type:'recurrence',id:source.id}],observedAt:'2026-09-11T12:00:00.000Z',confidence:'estimated'}));
  const v={...open,incomeSource:source.id,incomeAmount:'900',incomeDate:'2026-09-21'};
  expect(guideQuestion(c,v)?.key).toBe('incomeEntry');expect(()=>buildGuidedPlan(c,v,'new')).toThrow(/which expected arrival/);
  const updated={...v,incomeEntry:'pay-0'},built=buildGuidedPlan(c,updated,'new');
  expect(built.assumptions).toHaveLength(2);expect(built.assumptions[0]).toMatchObject({id:'pay-0',valueCents:90000,expectedDate:'2026-09-21'});expect(built.assumptions[1]).toEqual(draft.assumptions[1]);
  const before=guideProjection(c,{...open,lookThrough:'2026-10-01'}),after=guideProjection(c,{...updated,lookThrough:'2026-10-01'});
  expect(after.movements.filter(m=>m.kind==='contribution').reduce((sum,m)=>sum+m.deltaCents,0)).toBe(before.movements.filter(m=>m.kind==='contribution').reduce((sum,m)=>sum+m.deltaCents,0)-10000);
  expect(()=>buildGuidedPlan(c,{...v,incomeEntry:'new',incomeDate:'2026-09-30'},'duplicate')).toThrow(/already has an arrival/);
  expect(buildGuidedPlan(c,{...v,incomeEntry:'new'},'additional').assumptions).toHaveLength(3);
 });
 it('does not offer or accept retired goals',()=>{const c=context(),g=c.household.goals[0]!;g.status='retired';const v={...open,prepareSource:g.id};expect(planGuideFields(c,v).find(f=>f.key==='prepareSource')!.choices!(c,v).some(o=>o.value===g.id)).toBe(false);expect(()=>buildGuidedPlan(c,v,'retired')).toThrow(/visible goal/);});
 it('replaces generated notes on repeat passes while retaining personal prose and clearing resolved questions',()=>{
  const c=context();c.household.planDrafts![0]!.note='Remember to ask for a quote.';
  const first=buildGuidedPlan(c,open,'first');c.household.planDrafts![0]!.note=first.note;
  expect(buildGuidedPlan(c,open,'again').note).toBe(first.note);
  const row=c.household.planDrafts![0]!.lines.find(l=>l.lens==='prepare')!;
  const next=buildGuidedPlan(c,{...open,purpose:'More time together',prepareSource:row.sourceReference!.id,prepareTarget:'1200',prepareDeadline:'2026-12-01',preparePaydays:'Decide later',prepareAmount:'100',prepareDate:'2026-09-18',prepareFunding:'available',prepareStep:'Get a quote'},'second');
  expect(next.note).toContain('Remember to ask for a quote.');expect(next.note).toContain('More time together');expect(next.note).not.toContain('Less scrambling');expect(next.note).not.toContain('Prepare:');
  c.household.planDrafts![0]!.note=first.note.replace('[Hercules planning notes]\n','').replace('\n[End Hercules planning notes]','');
  expect(buildGuidedPlan(c,open,'legacy').note).toBe(first.note);
  c.household.planDrafts![0]!.note+='\n'+c.household.planDrafts![0]!.note.split('\n').slice(1).join('\n');expect(buildGuidedPlan(c,open,'accumulated').note).toBe(first.note);
  c.household.planDrafts![0]!.note='Remember the appointment.\nWhat matters: protect my sleep';expect(buildGuidedPlan(c,open,'prose').note).toContain('What matters: protect my sleep');
 });
});

it('keeps a received Personal arrival out of rescheduling choices and rejects bypassed ids',async()=>{
 const {postEntry,reversePostedMoney}=await import('../src/core/commands.ts');const c=context('personal');
 const incomeCategory=c.household.categories.find(row=>row.parentId&&row.transactionType==='income')!;
 const source={...c.household.recurrences[0]!,id:'received-pay',type:'income' as const,subcategoryId:incomeCategory.id};c.household.recurrences.push(source);
 c.household=postEntry(c.household,{type:'income',date:'2026-09-10',amount:'1000',accountId:source.accountId,subcategoryId:source.subcategoryId,createdBy:c.memberId,visibility:'personal',source:'recurring',sourceId:source.id}).household;
 c.household.planDrafts![0]!.assumptions=[{id:'received',kind:'income',valueCents:100000,expectedDate:'2026-09-10',sourceReferences:[{type:'recurrence',id:source.id}],observedAt:'2026-09-11T12:00:00.000Z',confidence:'estimated'}];
 const v={...open,incomeSource:source.id,incomeEntry:'received',incomeAmount:'1000',incomeDate:'2026-09-18'};
 expect(planGuideFields(c,v).find(f=>f.key==='incomeEntry')!.choices!(c,v).map(o=>o.value)).toEqual(['new']);
 expect(()=>buildGuidedPlan(c,v,'move')).toThrow(/recorded receipt/);
 expect(buildGuidedPlan(c,{...v,incomeEntry:'new'},'new').assumptions).toHaveLength(2);
 const receipt=c.household.transactions.find(tx=>tx.sourceId===source.id)!;
 c.household=reversePostedMoney(c.household,receipt.id,{createdBy:c.memberId,reversalDate:'2026-09-30'}).household;
 expect(()=>buildGuidedPlan(c,v,'future-reversal')).toThrow(/recorded receipt/);
 expect(()=>buildGuidedPlan({...c,today:'2026-10-01'},{...v,incomeDate:'2026-10-02'},'already-reversed')).not.toThrow();
});
