// @vitest-environment jsdom
import {act,createElement} from 'react';import {createRoot,type Root} from 'react-dom/client';import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';import {SevenShiftsConnectPanel} from '../src/SevenShiftsConnectPanel.tsx';import {WorkShiftPage} from '../src/WorkShiftPage.tsx';import {seedDemoHousehold,clockInShift} from '../src/core/index.ts';
const client=vi.hoisted(()=>({list:vi.fn(),connect:vi.fn(),pull:vi.fn()}));vi.mock('../src/imports/sevenShiftsClient.ts',()=>({readSevenShiftsStatus:async()=>({available:true}),listSevenShiftsConnections:(...args:unknown[])=>client.list(...args),connectSevenShifts:client.connect,pullSevenShiftsPunches:client.pull,probeSevenShifts:vi.fn(),revokeSevenShiftsConnection:vi.fn()}));
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;let host:HTMLDivElement,root:Root;const h=seedDemoHousehold({today:'2026-09-08',environment:'development'});const props=()=>({environment:h.environment,householdId:h.householdId,memberId:'MEM-001',jobs:h.workJobs,disabled:false});
beforeEach(()=>{vi.stubGlobal('fetch',vi.fn(async()=>Response.json({ok:true,available:false,detail:'Unavailable in this fixture'})));Object.defineProperty(window,'innerWidth',{configurable:true,value:390});client.list.mockReset();client.list.mockResolvedValue([]);host=document.createElement('div');document.body.append(host);root=createRoot(host);});afterEach(async()=>{await act(async()=>root.unmount());host.remove();vi.restoreAllMocks();vi.unstubAllGlobals();});const button=(text:string)=>[...host.querySelectorAll('button')].find(b=>b.textContent===text)!;
describe('Desk connection to phone Timesheet',()=>{
 it('keeps mobile tokens disclosed, refreshes same scope and makes navigation an explicit action',async()=>{let opened=0;await act(async()=>root.render(createElement(SevenShiftsConnectPanel,{...props(),onOpenTimesheet:()=>opened++})));expect(host.querySelector('details.seven-shifts-manual')?.hasAttribute('open')).toBe(false);client.list.mockResolvedValue([{connectionId:'connection',jobId:h.workJobs[0]!.id,companyName:'Fictional cafe',state:'active',updatedAt:'',lastPullAt:null}]);await act(async()=>button('Refresh connections').click());expect(host.textContent).toContain('Fictional cafe');expect(client.list.mock.calls.at(-1)![0]).toMatchObject({householdId:h.householdId,memberId:'MEM-001',environment:h.environment});expect(opened).toBe(0);await act(async()=>button('Open Timesheet').click());expect(opened).toBe(1);expect(client.connect).not.toHaveBeenCalled();});
 it('opens the real Fill surface without clocking out a live shift',async()=>{const live=clockInShift(h,{memberId:'MEM-001'}).household,clockOut=vi.fn();await act(async()=>root.render(createElement(WorkShiftPage,{household:live,memberId:'MEM-001',memberName:'Bianca',today:'2026-09-08',environment:'development',busy:false,onClockIn:()=>{},onAbandon:()=>{},onStartBreak:()=>{},onEndBreak:()=>{},onChooseTimeline:()=>{},onClockOut:clockOut,onConfirmShift:()=>{},onCorrect:()=>{},onAskSaveJob:()=>{},onArchiveJob:()=>{},onOpenCalendar:()=>{}})));await act(async()=>button('Jobs').click());await act(async()=>button('Open Timesheet').click());expect(button('Fill from 7shifts')).toBeTruthy();expect(clockOut).not.toHaveBeenCalled();});
 it('drops an old connection response after household replacement',async()=>{let release!:(value:unknown)=>void;client.list.mockImplementationOnce(()=>new Promise(r=>release=r));await act(async()=>root.render(createElement(SevenShiftsConnectPanel,props())));await act(async()=>root.render(createElement(SevenShiftsConnectPanel,{...props(),householdId:'different'})));await act(async()=>release([{connectionId:'old',companyName:'Old private company'}]));expect(host.textContent).not.toContain('Old private company');});
});
