// @vitest-environment jsdom
import {act,createElement} from 'react';import {createRoot,type Root} from 'react-dom/client';import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';import {ShiftReportScanBar} from '../src/ShiftReportScan.tsx';
const fixture=vi.hoisted(()=>({read:vi.fn()}));vi.mock('../src/imports/documentClarity.ts',()=>({scoreDocumentClarityFromFile:(file:File)=>fixture.read(file)}));vi.mock('../src/imports/DocumentCamera.tsx',()=>({DocumentCamera:()=>null}));
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
let host:HTMLDivElement,root:Root,onFile:ReturnType<typeof vi.fn>;
beforeEach(()=>{fixture.read.mockReset();host=document.createElement('div');document.body.append(host);root=createRoot(host);onFile=vi.fn();});afterEach(async()=>{await act(async()=>root.unmount());host.remove();});
const props=()=>({busy:false,scanBusy:false,error:'',onFile});async function choose(){const el=host.querySelector('input[type=file]')!;Object.defineProperty(el,'files',{configurable:true,value:[new File(['image'],'test.jpg',{type:'image/jpeg'})]});await act(async()=>el.dispatchEvent(new Event('change',{bubbles:true})));}
describe('Photo quality stays with its source',()=>{
 it('offers an explicit file override only after two rejected choices and passes every issue',async()=>{fixture.read.mockResolvedValue({ready:false,issues:['dim','soft','small','contrast','edge']});await act(async()=>root.render(createElement(ShiftReportScanBar,props())));await choose();expect(host.textContent).not.toContain('Use this photo anyway');await choose();const override=[...host.querySelectorAll('button')].find(b=>b.textContent==='Use this photo anyway')!;expect(onFile).not.toHaveBeenCalled();await act(async()=>override.click());expect(onFile).toHaveBeenCalledTimes(1);expect(onFile.mock.calls[0]![1]).toEqual({overridden:true,issues:['dim','soft','small','contrast','edge']});});
 it('retires an unresolved file check when camera replaces it',async()=>{let release!:(value:unknown)=>void;fixture.read.mockImplementation(()=>new Promise(r=>release=r));await act(async()=>root.render(createElement(ShiftReportScanBar,props())));await choose();const camera=[...host.querySelectorAll('button')].find(b=>b.textContent==='Take tip sheet photo')!;await act(async()=>camera.click());await act(async()=>release({ready:true,issues:[]}));expect(onFile).not.toHaveBeenCalled();});
 it('keeps failed-scan image warnings visible without any camera draft',async()=>{await act(async()=>root.render(createElement(ShiftReportScanBar,{...props(),error:'Could not read this photo',warnings:['one','two','three','four','five']})));expect(host.querySelectorAll('[role=alert] li')).toHaveLength(5);});
});
