import {describe,it,expect} from 'vitest';
import {catalogHousehold,configureHouseholdFund,archiveAccount,postEntry,splitForSync,type Household} from '../src/core/index.ts';
import {capturedIntent,clearCapturedIntent} from '../src/ledgerSync/capture.ts';
import {commandFromCapture,type Scope} from '../src/ledgerSync/protocol.ts';
import {prepareCommand,type AuthorityState} from '../src/ledgerSync/authority.ts';
import {executeIntent} from '../src/ledgerSync/registry.ts';
function state(h:Household):AuthorityState{const one=splitForSync(h,'MEM-001'),two=splitForSync(h,'MEM-002');return {sequence:h.revision,shared:one.shared,personal:new Map([['MEM-001',one.personal],['MEM-002',two.personal]])};}
async function fixture(){const h=archiveAccount(configureHouseholdFund(catalogHousehold(),{custodianMemberId:'MEM-001',createdBy:'MEM-001',openedOn:'2026-09-01'}).household,'ACC-MC').household;clearCapturedIntent(h);const scope:Scope={environment:h.environment,householdId:h.householdId,memberId:'MEM-001',subject:'test-one',role:'owner',expires:Date.now()+60000,aclEpoch:1};const input={swipeReviewed:true as const,date:'2026-09-08',type:'expense' as const,amount:'12.34',accountId:'ACC-VISA',subcategoryId:'SUB-FOOD-GROCERIES',createdBy:'MEM-001',visibility:'household' as const,funding:{fundId:h.householdFund!.id,fundedCents:1234,destinationAccountId:'ACC-VISA'}};const candidate=postEntry(h,input),command=await commandFromCapture(capturedIntent(candidate.household)!,scope,crypto.randomUUID());return {h,scope,input,command};}
describe('Swipe accepted source review',()=>{
 it('carries only a marker with existing IDs and hashes source meaning through authoritative replay',async()=>{const f=await fixture();expect(f.command.steps[0]!.resources).toEqual([{key:'swipe-review',hash:expect.any(String)}]);expect(JSON.stringify(f.command)).not.toContain('Groceries');const reordered={...f.h,accounts:f.h.accounts.map(a=>Object.fromEntries(Object.entries(a).reverse()) as typeof a)};await expect(prepareCommand(state(reordered),f.command,f.scope,()=>{})).resolves.toBeDefined();const accepted=await prepareCommand(state(f.h),f.command,f.scope,()=>{});expect(accepted.household.transactions.some(t=>t.amountCents===1234&&t.subcategoryId===f.input.subcategoryId)).toBe(true);});
 it('rejects remote category, card, resolver and Fund changes while allowing unrelated entries',async()=>{const f=await fixture();const variants:Household[]=[{...f.h,categories:f.h.categories.map(c=>c.id===f.input.subcategoryId?{...c,name:'Remote category'}:c)},{...f.h,accounts:f.h.accounts.map(a=>a.id==='ACC-VISA'?{...a,name:'Remote card'}:a)},{...f.h,accounts:f.h.accounts.map(a=>a.id==='ACC-MC'?{...a,active:true}:a)},{...f.h,householdFund:{...f.h.householdFund!,custodianMemberId:'MEM-002'}}];for(const h of variants)await expect(prepareCommand(state(h),f.command,f.scope,()=>{})).rejects.toThrow('BUSINESS_PRECONDITION_CHANGED');const unrelated=postEntry(f.h,{date:'2026-09-07',type:'expense',amount:'1.23',accountId:'ACC-VISA',subcategoryId:'SUB-FOOD-COFFEE',createdBy:'MEM-001'}).household;await expect(prepareCommand(state(unrelated),f.command,f.scope,()=>{})).resolves.toBeDefined();});
 it('refuses spoofed or malformed reviewed inputs and retains the unreviewed primitive',async()=>{const f=await fixture();expect(()=>executeIntent(f.h,'postEntry',[f.input],'MEM-002',crypto.randomUUID())).toThrow('ACTOR_MISMATCH');for(const patch of [{swipeReviewed:false},{accountId:'ACC-MC'},{visibility:'personal'},{funding:undefined}])expect(()=>executeIntent(f.h,'postEntry',[{...f.input,...patch}],'MEM-001',crypto.randomUUID())).toThrow('INVALID_SWIPE_REVIEW');const {swipeReviewed,...plain}=f.input;expect(postEntry(f.h,plain).postedIds.length).toBeGreaterThan(0);});
});
