// @vitest-environment jsdom
import { act, createElement } from "react";
import { createRoot } from "react-dom/client";
import { describe, expect, it } from "vitest";
import { FundStage } from "../src/FundStage.tsx";
import { MonthSpread } from "../src/MonthSpread.tsx";
import { buildSharedLedgerStory, sharedMonthCourse, proposeHouseholdFundContribution, confirmHouseholdFundContribution } from "../src/core/index.ts";
import { trustFixture } from "./fixtures/fund-trust.ts";
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
async function mount(course=false,width=390){Object.defineProperty(window,"innerWidth",{value:width,configurable:true});sessionStorage.clear();Object.assign(HTMLElement.prototype,{setPointerCapture(){},releasePointerCapture(){},hasPointerCapture(){return false;}});
 const {h}=trustFixture(),host=document.createElement("div"),root=createRoot(host);document.body.append(host);const writes:string[]=[];
 const props={household:h,memberId:"MEM-001",today:"2026-09-08",view:"household" as "household"|"personal",presentation:"phone" as const,widgetId:"level" as const,busy:false,onKitchen:()=>writes.push("write"),onOpenAccount:()=>{},onOpenDestination:()=>{}};
 const render=async()=>act(async()=>root.render(course?createElement(MonthSpread,{household:props.household,course:sharedMonthCourse(props.household,props.today),story:buildSharedLedgerStory(props.household,props.today),nameOf:id=>id??"Member",custodianName:"Bianca",onOpenFund:()=>{},onOpenRegister:()=>{},onOpenHealth:()=>{},scopeKey:props.view}):createElement(FundStage,props)));
 await render();return {h,host,root,props,writes,render,input:()=>host.querySelector<HTMLInputElement>(".date-turn input")!,button:(name:string)=>[...host.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent===name)!,close:async()=>{await act(async()=>root.unmount());host.remove();}};
}
async function set(input:HTMLInputElement,value:number){await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")!.set!.call(input,String(value));input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));});}
function pointer(node:Element,type:string,id=1){const event=new Event(type,{bubbles:true});Object.assign(event,{pointerId:id,isPrimary:id===1,button:0});node.dispatchEvent(event);}
describe("The Turn on live and legacy reading surfaces",()=>{
 it("serves the live custodian phone Level across the exact visible cross-month interval, preserving today's figure and one drawing",async()=>{const m=await mount();try{expect(m.input().max).toBe("38");const figure=m.host.querySelector("h2")!.textContent,history=m.host.querySelector(".reach-actual")!.getAttribute("d");await set(m.input(),31);expect(m.host.querySelector(".trust-day-reading")!.textContent).toContain("2026-10-01");expect(m.host.querySelector(".trust-day-reading")!.textContent).toContain("Projection");await set(m.input(),38);expect(m.host.querySelector(".trust-day-reading")!.textContent).toContain("No dated projection");expect(m.host.querySelector("h2")!.textContent).toBe(figure);expect(m.host.querySelector(".reach-actual")!.getAttribute("d")).toBe(history);expect(m.host.querySelectorAll("svg")).toHaveLength(1);expect(m.writes).toEqual([]);}finally{await m.close();}});
 it("restores cancel, capture loss, Escape and second-pointer state, suppressing later native input until a new action",async()=>{const m=await mount();try{for(const reason of ["pointercancel","lostpointercapture","Escape","second"]){const input=m.input();await act(async()=>pointer(input,"pointerdown"));await set(input,20);expect(m.button("Next day").disabled).toBe(true);await act(async()=>{if(reason==="Escape")input.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}));else pointer(input,reason==="second"?"pointerdown":reason,reason==="second"?2:1);});expect(input.value).toBe("8");await set(input,25);expect(input.value).toBe("8");}await act(async()=>m.input().dispatchEvent(new KeyboardEvent("keydown",{key:"ArrowRight",bubbles:true})));await set(m.input(),9);expect(m.input().value).toBe("9");expect(m.writes).toEqual([]);}finally{await m.close();}});
 it("retires active input on changed source, restores focus only within the same room and resets its reading",async()=>{const m=await mount();try{m.input().focus();await act(async()=>pointer(m.input(),"pointerdown"));await set(m.input(),20);const proposal=proposeHouseholdFundContribution(m.h,{memberId:"MEM-002",contributorMemberId:"MEM-002",amount:"100",date:"2026-09-08"});m.props.household=confirmHouseholdFundContribution(proposal.household,{memberId:"MEM-001",proposalEventId:proposal.postedIds[0]!}).household;await m.render();expect(m.input().value).toBe("8");expect(document.activeElement).toBe(m.input());await set(m.input(),30);m.props.view="personal";await m.render();expect(m.input().value).toBe("8");expect(document.activeElement).not.toBe(m.input());expect(m.writes).toEqual([]);}finally{await m.close();}});
 it("replaces legacy Course hover targets with the same visible daily reader on phone and desk",async()=>{for(const width of [390,1100]){const m=await mount(true,width);try{expect(m.input()).not.toBeNull();expect(m.host.querySelector(".ms-event[role=button]")).toBeNull();await set(m.input(),7);expect(m.host.querySelector(".ms-readout")!.textContent).toContain("Contribution confirmed");await set(m.input(),30);expect(m.host.querySelector(".ms-readout")!.textContent).toContain("No dated Fund projection");expect(m.host.textContent).not.toContain("Drag the month sideways");expect(m.writes).toEqual([]);}finally{await m.close();}}});
});
