-- AUTH / RLS READINESS PACKET (legacy sketch). DO NOT APPLY.
-- Superseded by docs/AUTH_RLS_CUTOVER.md and
-- supabase/migrations/004_auth_rls_prepare.sql,
-- 005_snapshot_cas_hardening.sql, and 006_auth_rls_cutover.sql.
-- This legacy sketch remains DO NOT APPLY. Migrations 004/005 were applied with
-- approval on 2026-08-24; project-wide cutover 006 remains DO NOT APPLY.
-- Do not paste this into the live household Supabase SQL editor.
-- Do not contact the household project. Do not claim Auth/RLS is complete
-- because this file exists. Hosted RLS today remains
-- USING (true) WITH CHECK (true) for ALL, including DELETE (001_hearth_books.sql).
--
-- NOTE: This sketch assumed a hosted `members.auth_user_id` column that the
-- current SPA schema does not use for continuity. Live membership is
-- `continuity_memberships` (migration 003 / D-117). The cutover packet extends
-- that table instead of inventing a parallel door.
--
-- Prerequisites Jonathan must complete first:
--   1. Supabase Auth for Jonathan and Bianca.
--   2. Keep already-live Development migration 002; separately approve forward
--      repair 005 before the deny-by-default cutover.
--   3. Map auth.uid() onto household membership.
--   4. Explicit approval to replace the open anon door.
--
-- Order:
--   001_hearth_books.sql (already applied historically)
--   002_snapshot_cas.sql (already applied to Development)
--   004 prepare (applied) -> 005 hardening (applied) -> 006 cutover (not applied)
-- Rollback: restore 001 open policies; drop membership/invite tables created here.
--
-- Synthetic proof (when Auth exists, on a throwaway project, never the household):
--   * owner can read/write own household_snapshots
--   * member can read/write own household, cannot DELETE the household row
--   * other household cannot SELECT payload
--   * revoked member cannot read
--   * anon cannot SELECT payload
--   * service_role stays server-only and is never a VITE_ key
--   * Development row cannot be written from a Production session

-- ---------------------------------------------------------------------------
-- 1. Membership and invitations (do not run yet)
-- ---------------------------------------------------------------------------
-- ALTER TABLE members ADD COLUMN IF NOT EXISTS auth_user_id UUID UNIQUE;
-- ALTER TABLE members ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'member'
--   CHECK (role IN ('owner', 'member'));
--
-- CREATE TABLE IF NOT EXISTS household_invitations (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   household_id TEXT NOT NULL REFERENCES households(id) ON DELETE CASCADE,
--   invite_phrase TEXT NOT NULL,
--   environment TEXT NOT NULL CHECK (environment IN ('development', 'production')),
--   invited_email TEXT,
--   invited_auth_user_id UUID,
--   created_by_auth_user_id UUID NOT NULL,
--   status TEXT NOT NULL CHECK (status IN ('draft', 'pending', 'accepted', 'revoked', 'expired')),
--   created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
--   accepted_at TIMESTAMPTZ,
--   revoked_at TIMESTAMPTZ
-- );
--
-- ---------------------------------------------------------------------------
-- 2. Replace open policies (do not run yet)
-- ---------------------------------------------------------------------------
-- DROP POLICY IF EXISTS hearth_anon_all ON households;
-- DROP POLICY IF EXISTS hearth_anon_all ON household_snapshots;
-- DROP POLICY IF EXISTS hearth_anon_all ON members;
--
-- CREATE POLICY hearth_household_member_select ON households
--   FOR SELECT TO authenticated
--   USING (id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid()));
-- CREATE POLICY hearth_household_owner_write ON households
--   FOR INSERT TO authenticated
--   WITH CHECK (id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid() AND role = 'owner'));
-- CREATE POLICY hearth_household_owner_update ON households
--   FOR UPDATE TO authenticated
--   USING (id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid() AND role = 'owner'))
--   WITH CHECK (id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid() AND role = 'owner'));
-- -- No DELETE policy for authenticated. Owners close sharing from the phone; they do not empty hosted books from PostgREST.
--
-- CREATE POLICY hearth_snapshot_member_select ON household_snapshots
--   FOR SELECT TO authenticated
--   USING (
--     household_id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid())
--     AND environment = current_setting('request.jwt.claims', true)::json->>'hearth_environment'
--   );
-- CREATE POLICY hearth_snapshot_member_write ON household_snapshots
--   FOR INSERT TO authenticated
--   WITH CHECK (household_id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid()));
-- CREATE POLICY hearth_snapshot_member_update ON household_snapshots
--   FOR UPDATE TO authenticated
--   USING (household_id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid()))
--   WITH CHECK (household_id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid()));
--
-- REVOKE ALL ON households, household_snapshots, members FROM anon;
-- GRANT SELECT, INSERT, UPDATE ON households, household_snapshots, members TO authenticated;
-- REVOKE DELETE ON households, household_snapshots, members FROM authenticated;
--
-- ---------------------------------------------------------------------------
-- 3. Invitations, revoke, and cross-household isolation (do not run yet)
-- ---------------------------------------------------------------------------
-- CREATE POLICY hearth_invite_owner_select ON household_invitations
--   FOR SELECT TO authenticated
--   USING (
--     household_id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid() AND role = 'owner')
--     OR invited_auth_user_id = auth.uid()
--   );
-- CREATE POLICY hearth_invite_owner_write ON household_invitations
--   FOR INSERT TO authenticated
--   WITH CHECK (household_id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid() AND role = 'owner'));
-- CREATE POLICY hearth_invite_owner_update ON household_invitations
--   FOR UPDATE TO authenticated
--   USING (household_id IN (SELECT household_id FROM members WHERE auth_user_id = auth.uid() AND role = 'owner'));
-- REVOKE ALL ON household_invitations FROM anon;
-- GRANT SELECT, INSERT, UPDATE ON household_invitations TO authenticated;
-- REVOKE DELETE ON household_invitations FROM authenticated;
--
-- Revoked member: members.auth_user_id is set null and role stays 'member' with
-- a revoked_at timestamp, OR the membership row is deleted. Either way, the
-- SELECT policies above fail closed because auth.uid() is no longer in members.
-- Do not keep a dangling policy that allows former members to read snapshots.
--
-- Cross-household: every USING/WITH CHECK clause is membership-scoped. There is
-- no policy that reads households by invite_phrase for anon. Phrase is routing
-- in the app, not a PostgREST password.

-- ---------------------------------------------------------------------------
-- 4. Service-role isolation
-- ---------------------------------------------------------------------------
-- The service role key never ships in VITE_, Cloudflare Pages/Workers env that Vite bakes,
-- household snapshots, or Hearth Pass files. Server jobs that need it stay off this app.
-- GRANT on these tables for service_role stays server-only. Never a VITE_SUPABASE_SERVICE_ROLE.

-- This file is documentation plus a future SQL sketch. It is not live Auth.
-- Local synthetic proof: test/auth-rls-readiness.test.ts (no household project).
