import {PieceGlyph} from './PieceGlyph.tsx';
import type {LookV1} from '../core/herculesCompanionContracts.ts';
import {HerculesFigure,type HerculesFigurePose} from '../HerculesFigure.tsx';
import {fittingColour} from './catalogue.ts';
/** These layers are inside the real body/head groups, so existing poses and rig transforms carry them. */
export function fittingBodyLayer(look:LookV1){const item=look.selections.body;if(item?.itemId!=='cozy-sweater')return item?<g data-fitting-item={item.itemId} transform="translate(87 87) scale(.9 1)"><PieceGlyph itemId={item.itemId} variantId={item.variantId} size={90}/></g>:null;const colour=fittingColour(item.variantId);return <g data-fitting-item={item.itemId} stroke="#40392f" strokeWidth="1.4" strokeLinejoin="round"><path d="M85 97Q120 80 152 109Q174 133 163 166L112 173Q93 146 85 97Z" fill={colour}/><path d="M97 103Q103 139 118 165M113 99Q124 128 135 169M133 105Q149 132 151 166" stroke="#fffaf0" opacity=".52" strokeWidth="3" fill="none"/>{[0,1,2].map(i=><path key={i} d={`M${102+i*16} 111q-6 7 2 13t2 13t4 14`} fill="none" stroke="#514b3e" opacity=".32"/>)}<path d="M108 171Q139 167 163 163" stroke={colour} strokeWidth="7"/></g>;}
export function fittingHeadLayer(look:LookV1){const hat=look.selections.head,glasses=look.selections.eyewear;return <g stroke="#40392f" strokeWidth="1.4" strokeLinejoin="round" fill="none">{hat&&hat.itemId!=='cozy-toque'&&<g data-fitting-item={hat.itemId} transform="translate(34 -2)"><PieceGlyph itemId={hat.itemId} variantId={hat.variantId} size={77}/></g>}{hat?.itemId==='cozy-toque'&&<g data-fitting-item={hat.itemId}><path d="M43 43Q47 14 74 18Q99 17 102 43Z" fill={fittingColour(hat.variantId)}/><path d="M44 40Q76 34 101 42L101 50Q72 44 43 50Z" fill={fittingColour(hat.variantId)}/><circle cx="74" cy="15" r="7" fill={fittingColour(hat.variantId)}/>{[52,62,72,82,92].map(x=><path key={x} d={`M${x} 42v5`} opacity=".45"/>)}</g>}{glasses&&glasses.itemId!=='cozy-glasses'&&<g data-fitting-item={glasses.itemId} transform="translate(23 23)"><PieceGlyph itemId={glasses.itemId} variantId={glasses.variantId} size={78}/></g>}{glasses?.itemId==='cozy-glasses'&&<g data-fitting-item={glasses.itemId} stroke={fittingColour(glasses.variantId)} strokeWidth="2.5"><circle cx="52" cy="63" r="10"/><path d="M62 61q6-5 11 0M73 61l27-5M42 62l-7-1"/><path d="M74 61q3 9-1 12" strokeWidth="1.8"/></g>}</g>;}
export function fittingOuterLayer(look:LookV1){const p=look.selections.outerwear;return p?<g data-fitting-item={p.itemId} transform="translate(84 88) scale(1 1.05)"><PieceGlyph itemId={p.itemId} variantId={p.variantId} size={94}/></g>:null;}
export function fittingNeckLayer(look:LookV1){return <>{(['neckwear','charm'] as const).map(slot=>{const p=look.selections[slot];return p?<g key={slot} data-fitting-item={p.itemId} transform={slot==='charm'?'translate(36 88)':'translate(24 81)'}><PieceGlyph itemId={p.itemId} variantId={p.variantId} size={slot==='charm'?58:76}/></g>:null;})}</>;}
export function fittingTailLayer(look:LookV1){const p=look.selections.tail;return p?<g data-fitting-item={p.itemId} transform="translate(150 74)"><PieceGlyph itemId={p.itemId} variantId={p.variantId} size={46}/></g>:null;}
export function fittingLayers(look:LookV1){return {bodyLayer:<>{fittingBodyLayer(look)}{fittingOuterLayer(look)}</>,headLayer:fittingHeadLayer(look),neckLayer:fittingNeckLayer(look),tailLayer:fittingTailLayer(look)};}
export function FittingFigure({look,size=200,pose='loaf'}:{look:LookV1;size?:number;pose?:HerculesFigurePose}){return <HerculesFigure title="Hercules wearing the current preview" pose={pose} size={size} {...fittingLayers(look)}/>;}
