import {wardrobeReturnFocus} from './focus.ts';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {createPortal} from 'react-dom';
import {useDialog} from '../useDialog.ts';
import {useAppearance} from '../theme/ThemeProvider.tsx';
import type {LookV1} from '../core/herculesCompanionContracts.ts';
import {COZY_LOOK,FITTING_ITEMS,FITTING_REACTIONS,canPlayReaction,fittingColour,type FittingReaction} from './catalogue.ts';
import {fitEdit,fitRedo,fitUndo,fittingDraftKey,loadFittingDraft,saveFittingDraft,type FittingHistory} from './draft.ts';
import {FittingFigure} from './FittingFigure.tsx';
import type {WardrobeScene} from './scene.ts';
import './wardrobe.css';
export default function HerculesDressingRoom({environment,householdId,memberId,view,onClose}:{environment:string;householdId:string;memberId:string;view:'household'|'personal';onClose:()=>void}){
 const appearance=useAppearance(),theme=appearance.scene.theme;const key=fittingDraftKey(environment,householdId,memberId);
 const [storage]=useState(()=>{try{return window.localStorage;}catch{return null;}});
 const [history,setHistory]=useState<FittingHistory>(()=>({past:[],present:loadFittingDraft(storage,key),future:[]}));
 const look=history.present;const latestLook=useRef(look);latestLook.current=look;
 const [selected,setSelected]=useState<string>('cozy-sweater'),[status,setStatus]=useState('loading'),[attempt,setAttempt]=useState(0),[saved,setSaved]=useState(true);
 const [paused,setPaused]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches),[reduced,setReduced]=useState(paused),[pose,setPose]=useState<FittingReaction>('breathe-blink');
 const [angle,setAngle]=useState(27),[zoom,setZoom]=useState(1),[mirror,setMirror]=useState(true),[flat,setFlat]=useState(false);
 const [drawer,setDrawer]=useState<'clothes'|'poses'>('clothes');const host=useRef<HTMLDivElement>(null),controller=useRef<WardrobeScene|null>(null),dialog=useDialog(true,onClose,wardrobeReturnFocus);
 const presentation=useRef({paused:paused||reduced,pose,angle,zoom,mirror});presentation.current={paused:paused||reduced,pose,angle,zoom,mirror};
 const active=FITTING_ITEMS.find(item=>item.id===selected)??FITTING_ITEMS[1];
 useEffect(()=>{setSaved(saveFittingDraft(storage,key,look));},[look,key,storage]);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const changed=()=>{setReduced(media.matches);if(media.matches)setPaused(true);};media.addEventListener('change',changed);return()=>media.removeEventListener('change',changed);},[]);
 useEffect(()=>{
  const node=host.current;if(!node||flat)return;const abort=new AbortController();let live=true;setStatus('loading');
  import('./scene.ts').then(({createWardrobeScene})=>{if(!live)return null;return createWardrobeScene(node,{theme,personal:view==='personal',signal:abort.signal,paused:paused||reduced,onError:()=>{if(live){controller.current=null;setStatus('error');}},onReady:()=>{if(live)setStatus('ready');},onPick:id=>{if(live){setSelected(id);setDrawer('clothes');}}});}).then(instance=>{if(!instance)return;if(!live){instance.dispose();return;}controller.current=instance;const current=presentation.current;instance.setPaused(current.paused);instance.setLook(latestLook.current);instance.setCamera(current.angle,current.zoom);instance.setMirror(current.mirror);instance.setPose(current.pose);}).catch(()=>{if(live)setStatus('error');});
  return()=>{live=false;abort.abort();controller.current?.dispose();controller.current=null;};
 },[attempt,theme,view,flat]);
 useEffect(()=>{controller.current?.setLook(look);if(!canPlayReaction(pose,look)){setPose('breathe-blink');controller.current?.setPose('breathe-blink');}},[look,pose]);
 useEffect(()=>controller.current?.setPaused(paused||reduced),[paused,reduced]);
 useEffect(()=>controller.current?.setCamera(angle,zoom),[angle,zoom]);
 useEffect(()=>controller.current?.setMirror(mirror),[mirror]);
 function change(slot:typeof active.slot,itemId:string|null,variantId?:string){const next:LookV1={...look,selections:{...look.selections}};if(itemId)next.selections[slot]={itemId,variantId:variantId??'cream'};else delete next.selections[slot];setHistory(previous=>fitEdit(previous,next));}
 const roomName=theme==='classic'?'The little dressing room':theme==='taylor'?(view==='personal'?'The woodland wardrobe':'The cottage wardrobe'):(view==='personal'?'The music-room wardrobe':'The dressing lounge');
 const caption=theme==='classic'?'Warm wood, good light, and a rather important appointment.':theme==='taylor'?'Soft knits, collected details, and somewhere quiet to get ready.':'A little brass, a favourite record, and something for the weather.';
 return createPortal(<div ref={dialog} className="hercules-fitting-backdrop" role="dialog" aria-modal="true" aria-labelledby="fitting-title" data-fitting-theme={theme} data-fitting-view={view}>
  <div className="hercules-fitting-room">
   <header className="fitting-header"><div><span className="fitting-eyebrow">Hercules outfits · fitting study</span><h1 id="fitting-title">{roomName}</h1><p>{caption}</p></div><button type="button" data-autofocus className="fitting-close" onClick={onClose} aria-label="Close dressing room">Close <span aria-hidden="true">×</span></button></header>
   <aside className="fitting-rail" aria-label="Cozy at home collection"><div className="fitting-collection"><small>THE FIRST COLLECTION</small><h2>Cozy at home</h2><p>Three pieces. A quiet afternoon. Entirely overdressed for it.</p></div><div className="fitting-hangers">{FITTING_ITEMS.map(item=><button key={item.id} type="button" aria-pressed={selected===item.id} onClick={()=>{setSelected(item.id);setDrawer('clothes');}}><span className={`fitting-miniature fitting-miniature-${item.slot}`} style={{'--piece-colour':fittingColour(look.selections[item.slot]?.variantId??'cream')} as CSSProperties} aria-hidden="true"><span/></span><strong>{item.name}</strong><small>{look.selections[item.slot]?'In this preview':'On the shelf'}</small></button>)}</div><p className="fitting-studio-note">A first fitting, before the full wardrobe arrives.</p></aside>
   <main className="fitting-stage-wrap"><div className="fitting-stage" data-fitting-stage>
     <div ref={host} className="fitting-webgl" hidden={flat||status==='error'} data-state={status}/>
     {(flat||status!=='ready')&&<div className="fitting-fallback"><FittingFigure look={look} size={230}/><p>{flat?'2D outfit preview':status==='error'?'3D is unavailable. Your outfit preview is still here.':'Opening the dressing room…'}</p>{status==='error'&&!flat&&<button type="button" onClick={()=>setAttempt(n=>n+1)}>Retry 3D</button>}</div>}
     <span className="fitting-stage-label">{flat||status==='error'?'2D preview':'Fitting platform'}</span>
    </div><div className="fitting-camera" aria-label="Fitting camera"><label>Turn <input type="range" aria-label="Turn Hercules" min="-180" max="180" step="3" value={angle} onChange={e=>setAngle(Number(e.target.value))} disabled={flat||status!=='ready'}/></label><label>Zoom <input type="range" aria-label="Zoom Hercules" min="0.78" max="1.3" step="0.02" value={zoom} onChange={e=>setZoom(Number(e.target.value))} disabled={flat||status!=='ready'}/></label><button type="button" onClick={()=>{setAngle(-153);setZoom(1);}} disabled={flat||status!=='ready'}>See the back</button><button type="button" onClick={()=>{setAngle(27);setZoom(1);}} disabled={flat||status!=='ready'}>Reset view</button></div><div className="fitting-view-options"><button type="button" aria-pressed={mirror} disabled={flat||status!=='ready'} onClick={()=>setMirror(x=>!x)}>Mirror {mirror?'on':'off'}</button><button type="button" aria-pressed={paused||reduced} disabled={reduced||flat||status==='error'} onClick={()=>setPaused(x=>!x)}>{reduced?'Reduced motion':paused?'Resume motion':'Pause motion'}</button><button type="button" aria-pressed={flat} onClick={()=>setFlat(x=>!x)}>{flat?'Return to 3D':'Compare 2D look'}</button></div></main>
   <aside className="fitting-drawer" aria-label="Fitting controls"><div className="fitting-tabs"><button type="button" aria-pressed={drawer==='clothes'} onClick={()=>setDrawer('clothes')}>The outfit</button><button type="button" aria-pressed={drawer==='poses'} onClick={()=>setDrawer('poses')}>Hercules’s poses</button></div>
    {drawer==='clothes'?<section><p className="fitting-eyebrow">ON THE FITTING TABLE</p><h2>{active.name}</h2><p>{active.detail}</p><div className="fitting-swatches" aria-label={`${active.name} colours`}>{active.variants.map(variant=><button key={variant} type="button" aria-label={`${active.name}: ${variant}`} aria-pressed={look.selections[active.slot]?.variantId===variant} onClick={()=>change(active.slot,active.id,variant)}><span style={{background:fittingColour(variant)}} aria-hidden="true"/>{variant.replace('-',' ')}</button>)}</div><button type="button" className="fitting-remove" disabled={!look.selections[active.slot]} onClick={()=>change(active.slot,null)}>Remove {active.name.toLowerCase()}</button><div className="fitting-look-note"><h3>A little styling note</h3><p>Keep the glasses with the hat. A matching colour feels composed; an unexpected one feels like Hercules.</p></div></section>:<section><h2>A moment in the mirror</h2><p>{flat||status==='error'?'Fitting poses are available in 3D. You can still style the outfit here.':status==='loading'?'Choose a pose for when 3D is ready.':paused||reduced?'Choose a still fitting pose.':'Choose a reaction, then inspect the fit.'}</p><div className="fitting-poses">{FITTING_REACTIONS.map(reaction=><button type="button" key={reaction.id} disabled={flat||status==='error'||!canPlayReaction(reaction.id,look)} aria-pressed={pose===reaction.id} onClick={()=>{setPose(reaction.id);controller.current?.setPose(reaction.id);}}>{reaction.label}{!canPlayReaction(reaction.id,look)&&<small>{reaction.id==='admire-cape'?'Requires a cape':`Add ${'requires' in reaction?reaction.requires:'the piece'} first`}</small>}</button>)}</div></section>}
   </aside>
   <footer className="fitting-footer"><div role="status"><strong>Preview · this device</strong><span>{saved?'Your fitting draft is kept here when you close.':'This preview could not be kept on this device. Keep the room open to retain it.'}</span><small>Wear, saved looks and household sharing arrive with the full wardrobe.</small></div><div className="fitting-history"><button type="button" disabled={!history.past.length} onClick={()=>setHistory(fitUndo)}>Undo</button><button type="button" disabled={!history.future.length} onClick={()=>setHistory(fitRedo)}>Redo</button><button type="button" onClick={()=>setHistory(s=>fitEdit(s,structuredClone(COZY_LOOK)))}>Reset outfit</button></div></footer>
  </div>
 </div>,document.body);
}
