import {wardrobeReturnFocus} from './focus.ts';
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {useDialog} from '../useDialog.ts';
import {useAppearance} from '../theme/ThemeProvider.tsx';
import {legacyCompanionPreview,validateLookForWear,type LookV1,type CompanionSlot,type CompanionScope} from '../core/herculesCompanionContracts.ts';
import type {Household} from '../core/types.ts';
import type {KitchenCommand} from '../kitchenCommand.ts';
import {companionFor} from '../core/herculesCompanion.ts';
import {fitSelection,sameOutfit,shuffleLook} from './lookTools.ts';
import {useWardrobeCommands} from './useWardrobeCommands.ts';
import {PieceGlyph} from './PieceGlyph.tsx';
import {SavedLooks} from './SavedLooks.tsx';
import {COZY_LOOK,COLLECTIONS,COLLECTION_LOOKS,FITTING_MANIFEST,FITTING_ITEMS,FITTING_REACTIONS,canPlayReaction,fittingColour,type FittingReaction} from './catalogue.ts';
import {fitEdit,fitRedo,fitUndo,fittingDraftKey,loadFittingDraft,saveFittingDraft,type FittingHistory} from './draft.ts';
import {FittingFigure} from './FittingFigure.tsx';
import type {WardrobeScene} from './scene.ts';
import './wardrobe.css';
export default function HerculesDressingRoom({environment,householdId,memberId,view,onClose,household,onCommand,connected=false}:{environment:string;householdId:string;memberId:string;view:'household'|'personal';onClose:()=>void;household?:Household;onCommand?:KitchenCommand;connected?:boolean}){
 const appearance=useAppearance(),theme=appearance.scene.theme;const key=fittingDraftKey(environment,householdId,memberId);
 const profile=household?companionFor(household,memberId):null;
 const legacy=household?legacyCompanionPreview(household.kitchen.companion.equipped):null;
 const initial=profile?.wornLook.value??legacy?.look??COZY_LOOK;
 const [online,setOnline]=useState(navigator.onLine);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 const commands=useWardrobeCommands({environment,householdId,memberId} as CompanionScope,connected&&online,onCommand);
 const [collection,setCollection]=useState('cozy'),[category,setCategory]=useState('all'),[locked,setLocked]=useState<CompanionSlot[]>([]),[favourites,setFavourites]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem(key+':favourites')??'[]');return Array.isArray(value)?value.filter(v=>typeof v==='string').slice(0,60):[];}catch{return [];}}),[onlyFavourites,setOnlyFavourites]=useState(false);
 const [replacement,setReplacement]=useState<{look:LookV1;names:string[]}|null>(null),[fitStatus,setFitStatus]=useState('ready'),[shelfStatus,setShelfStatus]=useState('ready'),[keepsake,setKeepsake]=useState<string|null>(legacy?.keepsakes[0]??null);
 const [resolvedLegacy,setResolvedLegacy]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem(key+':legacy-resolved')??'[]');return Array.isArray(value)?value.filter(v=>typeof v==='string'):[];}catch{return [];}});
 function resolveLegacy(slots:string[]){setResolvedLegacy(old=>{const next=[...new Set([...old,...slots])];try{localStorage.setItem(key+':legacy-resolved',JSON.stringify(next));}catch{}return next;});}
 const [storage]=useState(()=>{try{return window.localStorage;}catch{return null;}});
 const [history,setHistory]=useState<FittingHistory>(()=>({past:[],present:loadFittingDraft(storage,key,initial),future:[]}));
 const look=history.present;const latestLook=useRef(look);latestLook.current=look;
 const [selected,setSelected]=useState<string>('cozy-sweater'),[status,setStatus]=useState('loading'),[attempt,setAttempt]=useState(0),[saved,setSaved]=useState(true);
 const [paused,setPaused]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches),[reduced,setReduced]=useState(paused),[pose,setPose]=useState<FittingReaction>('breathe-blink');
 const [angle,setAngle]=useState(27),[zoom,setZoom]=useState(1),[mirror,setMirror]=useState(true),[flat,setFlat]=useState(false);
 const [drawer,setDrawer]=useState<'clothes'|'poses'|'looks'>('clothes');const host=useRef<HTMLDivElement>(null),controller=useRef<WardrobeScene|null>(null),dialog=useDialog(true,onClose,wardrobeReturnFocus);
 const presentation=useRef({paused:paused||reduced,pose,angle,zoom,mirror,collection,keepsake});presentation.current={paused:paused||reduced,pose,angle,zoom,mirror,collection,keepsake};
 const active=FITTING_ITEMS.find(item=>item.id===selected)??FITTING_ITEMS[0]!;
 useEffect(()=>{setSaved(saveFittingDraft(storage,key,look));},[look,key,storage]);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const changed=()=>{setReduced(media.matches);if(media.matches)setPaused(true);};media.addEventListener('change',changed);return()=>media.removeEventListener('change',changed);},[]);
 useEffect(()=>{
  const node=host.current;if(!node||flat)return;const abort=new AbortController();let live=true;setStatus('loading');
  import('./scene.ts').then(({createWardrobeScene})=>{if(!live)return null;return createWardrobeScene(node,{theme,personal:view==='personal',signal:abort.signal,paused:paused||reduced,onError:()=>{if(live){controller.current=null;setStatus('error');}},onReady:()=>{if(live)setStatus('ready');},onFittingState:state=>{if(live)setFitStatus(state);},onCollectionState:state=>{if(live)setShelfStatus(state);},onPick:id=>{if(live){pick(id);}}});}).then(instance=>{if(!instance)return;if(!live){instance.dispose();return;}controller.current=instance;const current=presentation.current;instance.setPaused(current.paused);instance.setLook(latestLook.current);instance.setCamera(current.angle,current.zoom);instance.setMirror(current.mirror);instance.setPose(current.pose);instance.setCollection?.(current.collection);instance.setKeepsake?.(current.keepsake);}).catch(()=>{if(live)setStatus('error');});
  return()=>{live=false;abort.abort();controller.current?.dispose();controller.current=null;};
 },[attempt,theme,view,flat]);
 useEffect(()=>{controller.current?.setLook(look);if(!canPlayReaction(pose,look)){setPose('breathe-blink');controller.current?.setPose('breathe-blink');}},[look,pose]);
 useEffect(()=>controller.current?.setPaused(paused||reduced),[paused,reduced]);
 useEffect(()=>controller.current?.setCamera(angle,zoom),[angle,zoom]);
 useEffect(()=>controller.current?.setMirror(mirror),[mirror]);
 useEffect(()=>{controller.current?.setCollection?.(collection);},[collection,status]);
 useEffect(()=>{controller.current?.setKeepsake?.(keepsake);},[keepsake,status]);
 function change(slot:CompanionSlot,itemId:string|null,variantId?:string){const item=FITTING_ITEMS.find(p=>p.id===itemId);const result=fitSelection(latestLook.current,slot,item?{itemId:item.id,variantId:variantId??item.variants[0]!}:null);if(result.replaced.length)setReplacement({look:result.look,names:result.replaced});else{setReplacement(null);setHistory(previous=>fitEdit(previous,result.look));resolveLegacy([slot]);}}
 function pick(id:string){const item=FITTING_ITEMS.find(p=>p.id===id);if(!item)return;setSelected(id);setDrawer('clothes');change(item.slot,id);}
 function preview(next:LookV1){const first=Object.values(next.selections).find(value=>value&&FITTING_ITEMS.some(item=>item.id===value.itemId));if(first)setSelected(first.itemId);resolveLegacy(legacy?.conflicts.map(c=>c.slot)??[]);setReplacement(null);setHistory(s=>fitEdit(s,structuredClone(next)));}
 function favourite(id:string){setFavourites(old=>{const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];try{localStorage.setItem(key+':favourites',JSON.stringify(next));}catch{}return next;});}
 let wearable=true;try{validateLookForWear(look,FITTING_MANIFEST);}catch{wearable=false;}
 const conflict=!profile?.wornLook.value?legacy?.conflicts.find(c=>!look.selections[c.slot]&&!resolvedLegacy.includes(c.slot)):undefined;
 const shown=FITTING_ITEMS.filter(item=>(onlyFavourites?favourites.includes(item.id):item.collection===collection)&&(category==='all'||item.slot===category));
 const collectionInfo=COLLECTIONS.find(c=>c.id===collection);
 const roomName=theme==='classic'?'The little dressing room':theme==='taylor'?(view==='personal'?'The woodland wardrobe':'The cottage wardrobe'):(view==='personal'?'The music-room wardrobe':'The dressing lounge');
 const caption=theme==='classic'?'Warm wood, good light, and a rather important appointment.':theme==='taylor'?'Soft knits, collected details, and somewhere quiet to get ready.':'A little brass, a favourite record, and something for the weather.';
 return createPortal(<div ref={dialog} className="hercules-fitting-backdrop" role="dialog" aria-modal="true" aria-labelledby="fitting-title" data-fitting-theme={theme} data-fitting-view={view}>
  <div className="hercules-fitting-room">
   <header className="fitting-header"><div><span className="fitting-eyebrow">Hercules outfits · your dressing room</span><h1 id="fitting-title">{roomName}</h1><p>{caption}</p></div><button type="button" data-autofocus className="fitting-close" onClick={onClose} aria-label="Close dressing room">Close <span aria-hidden="true">×</span></button></header>
   <aside className="fitting-rail" aria-label="Wardrobe collections">
    <label className="fitting-select">Collection<select aria-label="Collection" value={collection} onChange={e=>{setCollection(e.target.value);setOnlyFavourites(false);}}>{COLLECTIONS.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}<option value="legacy">Old favourites</option></select></label>
    <div className="fitting-collection"><h2>{collectionInfo?.name??'Old favourites'}</h2><p>{collectionInfo?.note??'Every original piece is here. No financial milestones required.'}</p></div>
    <div className="fitting-filters"><label>Category<select aria-label="Category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All pieces</option>{['head','eyewear','neckwear','body','outerwear','charm'].map(s=><option key={s}>{s}</option>)}</select></label><button type="button" aria-pressed={onlyFavourites} onClick={()=>setOnlyFavourites(v=>!v)}>Favourites</button></div>
    {COLLECTION_LOOKS[collection]&&<button type="button" className="fitting-recommended" onClick={()=>preview(COLLECTION_LOOKS[collection]!)}>Try the collection look</button>}
    {shelfStatus==='error'&&<p role="status">These display pieces could not load. The catalogue still works. <button type="button" onClick={()=>controller.current?.setCollection(collection)}>Retry collection display</button></p>}
    <div className="fitting-hangers">{shown.map(item=><button key={item.id} type="button" aria-label={`Try ${item.name}`} aria-pressed={look.selections[item.slot]?.itemId===item.id} onClick={()=>pick(item.id)}><PieceGlyph itemId={item.id} variantId={look.selections[item.slot]?.itemId===item.id?look.selections[item.slot]?.variantId:undefined}/><strong>{item.name}</strong><small>{look.selections[item.slot]?.itemId===item.id?'In this preview':'Try on'}</small></button>)}</div>
    {!shown.length&&<p>No pieces in this selection. Choose another category or favourite a piece on the fitting table.</p>}
    <details className="fitting-keepsakes"><summary>Keepsakes shelf</summary><p>The original houses decorate the room. Winter ruff is Hercules’s natural mane.</p>{['cottage','townhouse','patio'].map(id=><button type="button" key={id} aria-pressed={keepsake===id} onClick={()=>setKeepsake(id)}>{id}</button>)}<button type="button" onClick={()=>setKeepsake(null)}>Clear shelf</button></details>
   </aside>
   <main className="fitting-stage-wrap"><div className="fitting-stage" data-fitting-stage>
     <div ref={host} className="fitting-webgl" hidden={flat||status==='error'} data-state={status}/>
     {(flat||status!=='ready')&&<div className="fitting-fallback"><FittingFigure look={look} size={230}/><p>{flat?'2D outfit preview':status==='error'?'3D is unavailable. Your outfit preview is still here.':'Opening the dressing room…'}</p>{status==='error'&&!flat&&<button type="button" onClick={()=>setAttempt(n=>n+1)}>Retry 3D</button>}</div>}
     <span className="fitting-stage-label">{flat||status==='error'?'2D preview':fitStatus==='loading'?'Fitting the selected pieces…':fitStatus==='error'?'Last available 3D look':'Fitting platform'}</span>
     {fitStatus==='error'&&!flat&&<div className="fitting-asset-error"><p>The selected piece could not load. Your draft is kept; 3D shows the previous fit.</p><button type="button" onClick={()=>controller.current?.setLook(look)}>Retry pieces</button></div>}
    </div><div className="fitting-camera" aria-label="Fitting camera"><label>Turn <input type="range" aria-label="Turn Hercules" min="-180" max="180" step="3" value={angle} onChange={e=>setAngle(Number(e.target.value))} disabled={flat||status!=='ready'}/></label><label>Zoom <input type="range" aria-label="Zoom Hercules" min="0.78" max="1.3" step="0.02" value={zoom} onChange={e=>setZoom(Number(e.target.value))} disabled={flat||status!=='ready'}/></label><button type="button" onClick={()=>{setAngle(-153);setZoom(1);}} disabled={flat||status!=='ready'}>See the back</button><button type="button" onClick={()=>{setAngle(27);setZoom(1);}} disabled={flat||status!=='ready'}>Reset view</button></div><div className="fitting-view-options"><button type="button" aria-pressed={mirror} disabled={flat||status!=='ready'} onClick={()=>setMirror(x=>!x)}>Mirror {mirror?'on':'off'}</button><button type="button" aria-pressed={paused||reduced} disabled={reduced||flat||status==='error'} onClick={()=>setPaused(x=>!x)}>{reduced?'Reduced motion':paused?'Resume motion':'Pause motion'}</button><button type="button" aria-pressed={flat} onClick={()=>setFlat(x=>!x)}>{flat?'Return to 3D':'Compare 2D look'}</button></div></main>
   <aside className="fitting-drawer" aria-label="Fitting controls"><div className="fitting-tabs"><button type="button" aria-pressed={drawer==='clothes'} onClick={()=>setDrawer('clothes')}>The outfit</button><button type="button" aria-pressed={drawer==='poses'} onClick={()=>setDrawer('poses')}>Hercules’s poses</button><button type="button" aria-pressed={drawer==='looks'} onClick={()=>setDrawer('looks')}>Saved looks</button></div>
    {drawer==='looks'?<SavedLooks household={household} memberId={memberId} look={look} wearable={wearable&&!conflict} commands={commands} onPreview={preview}/>:drawer==='clothes'?<section><p className="fitting-eyebrow">ON THE FITTING TABLE</p><h2>{active.name}</h2><p>{active.detail}</p><div className="fitting-swatches" aria-label={`${active.name} colours`}>{active.variants.map(variant=><button key={variant} type="button" aria-label={`${active.name}: ${variant}`} aria-pressed={look.selections[active.slot]?.itemId===active.id&&look.selections[active.slot]?.variantId===variant} onClick={()=>change(active.slot,active.id,variant)}><span style={{background:fittingColour(variant,active.id)}} aria-hidden="true"/>{variant.replace('-',' ')}</button>)}</div><button type="button" className="fitting-remove" disabled={look.selections[active.slot]?.itemId!==active.id} onClick={()=>change(active.slot,null)}>Remove {active.name.toLowerCase()}</button><div className="fitting-piece-actions"><button type="button" aria-pressed={favourites.includes(active.id)} onClick={()=>favourite(active.id)}>{favourites.includes(active.id)?'Unfavourite piece':'Favourite piece'}</button><button type="button" aria-pressed={locked.includes(active.slot)} onClick={()=>setLocked(old=>old.includes(active.slot)?old.filter(s=>s!==active.slot):[...old,active.slot])}>{locked.includes(active.slot)?'Unlock':'Lock'} {active.slot}</button></div><div className="fitting-look-note"><h3>A little styling note</h3><p>Hats and glasses belong together. Lock a favourite slot before a surprise; Hercules will work around it. Favourites stay on this device.</p></div></section>:<section><h2>A moment in the mirror</h2><p>{flat||status==='error'?'Fitting poses are available in 3D. You can still style the outfit here.':status==='loading'?'Choose a pose for when 3D is ready.':paused||reduced?'Choose a still fitting pose.':'Choose a reaction, then inspect the fit.'}</p><div className="fitting-poses">{FITTING_REACTIONS.map(reaction=><button type="button" key={reaction.id} disabled={flat||status==='error'||!canPlayReaction(reaction.id,look)} aria-pressed={pose===reaction.id} onClick={()=>{setPose(reaction.id);controller.current?.setPose(reaction.id);}}>{reaction.label}{!canPlayReaction(reaction.id,look)&&<small>{reaction.id==='admire-cape'?'Requires a cape':`Add ${'requires' in reaction?reaction.requires:'the piece'} first`}</small>}</button>)}</div></section>}
   </aside>
   <section className="fitting-notices" aria-label="Outfit notices">
    {replacement&&<div role="status"><p>This piece replaces {replacement.names.join(', ')} so the outfit fits.</p><button type="button" onClick={()=>{preview(replacement.look);setReplacement(null);}}>Replace and try on</button><button type="button" onClick={()=>setReplacement(null)}>Keep current outfit</button></div>}
    {Object.entries(look.selections).filter(([,v])=>!FITTING_ITEMS.some(i=>i.id===v.itemId&&i.variants.includes(v.variantId))).map(([slot,value])=><p key={slot}>Unavailable piece: {value.itemId}. It is preserved in this draft. <button type="button" onClick={()=>change(slot as CompanionSlot,null)}>Remove unavailable {slot}</button></p>)}
    {conflict&&<div><p>Your original look has two {conflict.slot} pieces. Choose which one to try; the original household configuration stays preserved.</p>{conflict.itemIds.map(id=><button type="button" key={id} onClick={()=>pick(id)}>Choose {FITTING_ITEMS.find(p=>p.id===id)?.name??id}</button>)}</div>}
    {legacy?.unknown.length? <p>Some original items are unavailable: {legacy.unknown.map(v=>v.itemId).join(', ')}. Their IDs remain in the original household configuration.</p>:null}
   </section>
   <footer className="fitting-footer"><div role="status"><strong>{profile?.wornLook.value&&sameOutfit(profile.wornLook.value,look)?'Your worn look':'Preview · not worn yet'}</strong><span>{commands.message||(!saved?'Device storage is unavailable. Keep this room open to retain the draft.':!online||!connected?'Browsing and fitting are available. Connect to save, wear or share.':saved?'Draft kept on this device. Wear and Save wait for your household’s confirmation.':'Device storage is unavailable. Keep this room open to retain the draft.')}</span>{commands.retry&&<button type="button" disabled={commands.pending||!online||!connected} onClick={()=>void commands.retryNow()}>Retry unconfirmed request</button>}</div>
    <div className="fitting-footer-actions"><div className="fitting-history"><button type="button" disabled={!history.past.length} onClick={()=>setHistory(fitUndo)}>Undo</button><button type="button" disabled={!history.future.length} onClick={()=>setHistory(fitRedo)}>Redo</button><button type="button" onClick={()=>preview(profile?.wornLook.value??initial)}>Reset to worn</button><button type="button" onClick={()=>preview(shuffleLook(look,locked))}>Surprise me</button><button type="button" onClick={()=>preview({...look,selections:{}})}>No accessories</button></div>
     <div className="fitting-save-actions"><button type="button" disabled={!commands.canStart||!wearable||Boolean(conflict)||Boolean(replacement)} onClick={()=>void commands.submit({kind:'look.wear',look,expectedRevision:profile?.wornLook.revision??0})}>Wear this</button><button type="button" onClick={()=>{setDrawer('looks');requestAnimationFrame(()=>document.getElementById('fitting-look-name')?.focus());}}>Save look…</button></div></div>
   </footer>
  </div>
 </div>,document.body);
}
