/** Original garment recipes shared by the exporter, 3D scene and ink figure. */
export const COLLECTIONS = [
  {id:'cozy',name:'Cozy at home',note:'Soft knits. A quiet afternoon. Entirely overdressed for it.'},
  {id:'office',name:'Tiny office manager',note:'He has reviewed the agenda. There will be a tea break.'},
  {id:'rain',name:'Newfoundland rain',note:'A little weather is no reason to abandon a good outfit.'},
  {id:'applause',name:'Dressing for applause',note:'The occasion? His arrival, naturally.'},
  {id:'kitchen',name:'Kitchen royalty',note:'An apron on, a whisk nearby, and absolutely no washing up.'},
  {id:'sunday',name:'Sunday best',note:'Careful stitching and nowhere in particular to hurry.'},
 {id:'night',name:'Hearth after dark',note:'Lamp low, robe on, and a firm opinion about bedtime.'},
 {id:'garden',name:'Garden Sunday',note:'Straw hat, muddy paws, and supervising the tomatoes.'},
 {id:'snow',name:'Snow day',note:'Bundled to the whiskers and not going out anyway.'},
] as const;
export type PieceSlot='head'|'eyewear'|'neckwear'|'body'|'outerwear'|'charm'|'tail';
export type Piece={id:string;collection:string;slot:PieceSlot;name:string;shape:string;detail:string;variants:readonly string[];coversBody?:boolean;legacy?:boolean};
const fabric=['cream','moss','rose','slate'],office=['ink','oat','claret','sage'],rain=['yellow','navy','seafoam','coral'],applause=['plum','midnight','ruby','ivory'],kitchen=['ivory','sage','terracotta','blue'],sunday=['oat','claret','sage','midnight'],metal=['silver','brass','rose-gold'],night=['midnight','plum','lavender','cream'],garden=['sage','yellow','oat','terracotta'],snow=['frost','navy','cherry','pine'];
const rows: [string,string,PieceSlot,string,string,string,readonly string[],boolean?][]=[
 ['cozy-sweater','cozy','body','Cable-knit sweater','cable','Raised cables · fitted sleeves',fabric],
 ['cozy-cardigan','cozy','body','Cardigan','cardigan','Open V · pearl buttons · patch pockets',fabric],
 ['cozy-toque','cozy','head','Pom-pom toque','toque','Ribbed brim · softly rounded crown',fabric],
 ['cozy-scarf','cozy','neckwear','Soft scarf','scarf','Wrapped knit · fringed ends',fabric],
 ['cozy-glasses','cozy','eyewear','Round reading glasses','round','Fine metal rims · open temples',metal],
 ['cozy-teacup','cozy','charm','Teacup charm','teacup','A little cup on a fine chain',metal],
 ['office-waistcoat','office','body','Waistcoat','waistcoat','Pointed hem · three buttons',office],
 ['office-jacket','office','outerwear','Pinstripe jacket','pinstripe','Notched lapels · fine chalk stripes',office,true],
 ['office-visor','office','head','Green visor','visor','Open crown · curved shade',office],
 ['office-glasses','office','eyewear','Rectangular glasses','rectangle','Squared frames · rounded corners',metal],
 ['office-tie','office','neckwear','Silk tie','tie','A small knot · tapered blade',office],
 ['office-watch','office','charm','Pocket-watch charm','watch','Raised bezel · hands at teatime',metal],
 ['rain-coat','rain','outerwear','Yellow raincoat','raincoat','Storm flap · double pockets · long hem',rain,true],
 ['rain-souwester','rain','head','Sou’wester','souwester','Wide weather brim · low crown',rain],
 ['rain-sweater','rain','body','Fisherman’s sweater','fisherman','Textured yoke · horizontal knit bands',rain],
 ['rain-cap','rain','head','Knitted watch cap','watchcap','Close knit · deep folded brim',rain],
 ['rain-neckerchief','rain','neckwear','Nautical neckerchief','neckerchief','Triangular fold · sailor stripe',rain],
 ['rain-puffin','rain','charm','Puffin charm','puffin','Rounded wings · proud little beak',metal],
 ['applause-cape','applause','outerwear','Velvet cape','cape','Draped folds · scalloped hem · clasp',applause],
 ['applause-jacket','applause','outerwear','Sequin jacket','sequin','Raised sequins · cropped evening cut',applause,true],
 ['applause-crown','applause','head','Miniature crown','crown','Five points · inset stones',metal],
 ['applause-glasses','applause','eyewear','Star glasses','star','Five-point frames · a theatrical flourish',metal],
 ['applause-bow','applause','neckwear','Satin bow','bow','Sculpted loops · ribbon tails',applause],
 ['applause-star','applause','charm','Star pendant','starpendant','A polished star on a fine chain',metal],
 ['kitchen-tunic','kitchen','body','Chef tunic','tunic','Double-breasted front · piping',kitchen],
 ['kitchen-apron','kitchen','outerwear','Apron','apron','Bib · waist ties · generous front pocket',kitchen],
 ['kitchen-hat','kitchen','head','Tall chef hat','chef','Pleated band · cloud-shaped crown',kitchen],
 ['kitchen-cap','kitchen','head','Baker’s cap','bakercap','Soft gathered crown · narrow band',kitchen],
 ['kitchen-neckerchief','kitchen','neckwear','Gingham neckerchief','gingham','Woven checks · neatly tied ends',kitchen],
 ['kitchen-whisk','kitchen','charm','Whisk charm','whisk','Wire loops · tiny handle',metal],
 ['sunday-coat','sunday','outerwear','Tailored coat','tailcoat','Long split tails · rolled lapels',sunday,true],
 ['sunday-vest','sunday','body','Embroidered vest','vest','Leaf embroidery · scalloped edging',sunday],
 ['sunday-beret','sunday','head','Beret','beret','Tilted crown · small stem',sunday],
 ['sunday-glasses','sunday','eyewear','Oval glasses','oval','Elongated rims · delicate bridge',metal],
 ['sunday-collar','sunday','neckwear','Ribbon collar','ribbon','A narrow ribbon with a rosette',sunday],
 ['sunday-cameo','sunday','charm','Cameo charm','cameo','Oval setting · raised cat silhouette',metal],
 ['night-cap','night','head','Nightcap','nightcap','Soft cone · tassel at the tip',night],
 ['night-mask','night','eyewear','Sleep mask','sleepmask','Padded shade · stitched closed eyes',night],
 ['night-pyjama','night','body','Pyjama top','pyjama','Piped collar · two little buttons',night],
 ['night-robe','night','outerwear','Plush robe','robe','Shawl collar · tie belt · deep cuffs',night,true],
 ['night-moon','night','charm','Moon pendant','moon','A crescent on a fine chain',metal],
 ['night-ribbon','night','tail','Tail ribbon','tailribbon','A satin bow tied near the tip',night],
 ['garden-hat','garden','head','Straw hat','strawhat','Wide brim · woven band',garden],
 ['garden-smock','garden','body','Linen smock','smock','Loose fit · front pocket · rolled sleeves',garden],
 ['garden-jacket','garden','outerwear','Waxed jacket','waxed','Corduroy collar · two flap pockets',garden,true],
 ['garden-collar','garden','neckwear','Daisy collar','daisy','A chain of little daisies',garden],
 ['garden-seeds','garden','charm','Seed-packet charm','seedpacket','A tiny paper packet · this year’s tomatoes',garden],
 ['garden-tail','garden','tail','Tail daisy','tailbow','A bow with one daisy, tied on the tail',garden],
 ['snow-hat','snow','head','Earflap hat','earflap','Lined flaps · chin ties',snow],
 ['snow-goggles','snow','eyewear','Ski goggles','goggles','One wide lens · wide strap',snow],
 ['snow-fleece','snow','body','Fleece','fleece','Half zip · high collar',snow],
 ['snow-vest','snow','outerwear','Puffer vest','puffer','Quilted channels · layers over a fleece',snow],
 ['snow-flake','snow','charm','Snowflake pendant','snowflake','Six points · a fine chain',metal],
 ['snow-bell','snow','tail','Tail bell','tailbell','A little bell on a ribbon',snow],
];
// Eighteen Play additions to the original six collections; later collections stay intact.
rows.push(
 ['cozy-bow','cozy','neckwear','Sunday knit bow','bow','A soft bow for a very small occasion',fabric],
 ['cozy-beret','cozy','head','Reading-room beret','beret','Low wool crown with a little stem',fabric],
 ['cozy-moon','cozy','charm','Bedside moon charm','moon','A polished crescent for quiet evenings',metal],
 ['office-oval','office','eyewear','Archivist spectacles','oval','Oval brass rims with fine temples',metal],
 ['office-ribbon','office','neckwear','Secretary ribbon','ribbon','A neat silk knot with a rosette',office],
 ['office-star','office','charm','Employee-of-the-moment star','starpendant','A star for his very important desk',metal],
 ['rain-round','rain','eyewear','Harbour spectacles','round','Fine weather-ready circular rims',metal],
 ['rain-bow','rain','neckwear','Sailor’s bow','bow','A small nautical bow',rain],
 ['rain-fish','rain','charm','Silver catch charm','fish','A tiny fish on a bright chain',metal],
 ['applause-beret','applause','head','Velvet artist’s beret','beret','A tilted crown for the encore',applause],
 ['applause-scarf','applause','neckwear','Backstage scarf','scarf','Dramatic fringed folds',applause],
 ['applause-cameo','applause','charm','Leading-cat cameo','cameo','His likeness in a polished setting',metal],
 ['kitchen-round','kitchen','eyewear','Recipe spectacles','round','A closer look at the instructions',metal],
 ['kitchen-bow','kitchen','neckwear','Patisserie bow','bow','A neatly tied confection',kitchen],
 ['kitchen-cup','kitchen','charm','Teatime cup charm','teacup','A cup and saucer on a fine chain',metal],
 ['sunday-scarf','sunday','neckwear','Promenade scarf','scarf','Fringed folds for the window seat',sunday],
 ['sunday-crown','sunday','head','Sunday coronet','crown','Five small points and polished stones',metal],
 ['sunday-watch','sunday','charm','Afternoon watch','watch','There is still time for a little walk',metal],
);
export const NEW_PIECES:Piece[]=rows.map(([id,collection,slot,name,shape,detail,variants,coversBody])=>({id,collection,slot,name,shape,detail,variants,coversBody}));
const legacy:[string,PieceSlot,string,string][]=[['toque','head','Kitchen toque','toque'],['visor','head','Bill visor','visor'],['chef','head','Sit-down chef hat','chef'],['specs','eyewear','Audit spectacles','round'],['copper','charm','Copper chain','chain'],['gold','charm','Gold chain','chain'],['bell','neckwear','Collar bell','bell'],['yarn','neckwear','Yarn collar','yarn'],['fish','charm','Fish treat','fish'],['clip','charm','Card clip','clip'],['tooth','charm','Tooth charm','tooth'],['ink','charm','Green-ink stamp','stamp']];
export const LEGACY_PIECES:Piece[]=legacy.map(([id,slot,name,shape])=>({id,collection:'legacy',slot,name,shape,detail:'From the original wardrobe · always available',variants:['legacy-original'],legacy:true}));
export const PIECES=[...NEW_PIECES,...LEGACY_PIECES];
