import {useState} from 'react';
import type {Household} from '../core/types.ts';
import {companionFor} from '../core/herculesCompanion.ts';
import type {LookV1} from '../core/herculesCompanionContracts.ts';
import {FittingFigure} from './FittingFigure.tsx';
import type {useWardrobeCommands} from './useWardrobeCommands.ts';
export function SavedLooks({household,memberId,look,wearable,commands,onPreview}:{household?:Household;memberId:string;look:LookV1;wearable:boolean;commands:ReturnType<typeof useWardrobeCommands>;onPreview:(look:LookV1)=>void}){
 const profile=household?companionFor(household,memberId):null,personal=profile?.savedLooks.filter(row=>row.value)??[],gallery=household?.companionGallery?.filter(row=>row.value)??[];
 const [name,setName]=useState(''),[replace,setReplace]=useState(''),[shareTarget,setShareTarget]=useState('');const target=personal.find(row=>row.id===replace),publicTarget=gallery.find(row=>row.id===shareTarget&&row.creatorMemberId===memberId);
 return <section className="fitting-saved"><h2>A look to come back to</h2><p>Save your preview privately. Saving a preset does not change what Hercules wears.</p>
  <form onSubmit={e=>{e.preventDefault();if(!name.trim()||!wearable||!commands.canStart)return;void commands.submit({kind:'look.save',look:{...structuredClone(look),id:target?.id??crypto.randomUUID(),name:name.trim()},expectedRevision:target?.revision??0});}}>
   <label>Name<input id="fitting-look-name" value={name} maxLength={64} required onChange={e=>setName(e.target.value)} placeholder="Something for a rainy Tuesday"/></label>
   <label>Save as<select value={replace} onChange={e=>setReplace(e.target.value)}><option value="">A new personal look</option>{personal.map(row=><option key={row.id} value={row.id}>Replace {row.value!.name}</option>)}</select></label>
   <button disabled={!commands.canStart||!wearable||(!target&&personal.length>=50)}>{target?'Replace personal look':'Save personal look'}</button>
  </form>
  {personal.length>=50&&<p>Your 50 personal spaces are full. Replace a named look or remove one below.</p>}
  <h3>My looks · {personal.length}/50</h3>{!personal.length&&<p>A quiet shelf, for now. Give this preview a name to save your first look.</p>}
  {personal.map(row=><article key={row.id} className="fitting-look-card"><FittingFigure look={row.value!} size={110}/><h4>{row.value!.name}</h4><div><button type="button" onClick={()=>onPreview(row.value!)}>Preview {row.value!.name}</button><button type="button" disabled={!commands.canStart} onClick={()=>void commands.submit({kind:'look.remove',lookId:row.id,expectedRevision:row.revision})}>Delete personal look</button></div><form key={`${row.id}:${row.revision}`} onSubmit={e=>{e.preventDefault();const value=String(new FormData(e.currentTarget).get('name')??'').trim();if(value)void commands.submit({kind:'look.save',look:{...row.value!,name:value},expectedRevision:row.revision});}}><label>Rename<input name="name" defaultValue={row.value!.name} maxLength={64} required/></label><button disabled={!commands.canStart}>Rename personal look</button></form><button type="button" disabled={!commands.canStart||(!publicTarget&&gallery.length>=100)} onClick={()=>void commands.submit({kind:'gallery.publish',galleryId:publicTarget?.id??crypto.randomUUID(),sourceLookId:row.id,expectedLookRevision:row.revision,expectedRevision:publicTarget?.revision??0})}>Share to household</button></article>)}
  <h3>Household gallery · {gallery.length}/100</h3><p>Sharing publishes only the look’s name, pieces, colours and your household name. Copying creates an independent personal preset.</p>
  <label>When sharing<select value={shareTarget} onChange={e=>setShareTarget(e.target.value)}><option value="">Create a new gallery look</option>{gallery.filter(row=>row.creatorMemberId===memberId).map(row=><option key={row.id} value={row.id}>Replace my {row.value!.look.name}</option>)}</select></label>
  {gallery.length>=100&&<p>The gallery is full. Replace one of your shared looks or remove one you created.</p>}
  {!gallery.length&&<p>No shared looks yet. Your personal shelf stays private until you choose Share to household.</p>}
  {gallery.map(row=><article key={row.id} className="fitting-look-card"><FittingFigure look={row.value!.look} size={110}/><h4>{row.value!.look.name}</h4><p>Shared by {household?.members.find(m=>m.id===row.creatorMemberId)?.name??'Household member'}</p><button type="button" onClick={()=>onPreview(row.value!.look)}>Preview shared look</button><button type="button" disabled={!commands.canStart||personal.length>=50} onClick={()=>void commands.submit({kind:'look.save',look:{...structuredClone(row.value!.look),id:crypto.randomUUID()},expectedRevision:0})}>Copy to my looks</button>{row.creatorMemberId===memberId&&<><form key={`${row.id}:${row.revision}`} onSubmit={e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('name')??'').trim();if(name)void commands.submit({kind:'gallery.rename',galleryId:row.id,name,expectedRevision:row.revision});}}><label>Public name<input name="name" defaultValue={row.value!.look.name} maxLength={64} required/></label><button disabled={!commands.canStart}>Rename shared look</button></form><button type="button" disabled={!commands.canStart} onClick={()=>void commands.submit({kind:'gallery.remove',galleryId:row.id,expectedRevision:row.revision})}>Remove shared look</button></>}</article>)}
 </section>;
}
