import type { Environment, Household, LedgerView } from '../../core/types.ts';
import type { ImportedSourceRow } from '../../core/importInbox/types.ts';

export type StatementDraftScope = { environment: Environment; householdId: string; memberId: string; authUserId: string; view: LedgerView };
export type StatementCheckpoint = { accountRef: string; accountLast4: string; kind: 'opening' | 'closing'; date: string | null; signedBalanceCents: number | null; page: number; sourceHash: string; periodStart?: string | null; periodEnd?: string | null };
export type StatementPage = { page: number; status: 'pending' | 'scanned' | 'failed' | 'omitted'; warnings: string[]; reviewed: boolean; omissionReason: string };
export type StatementSource = { hash: string; name: string; kind: 'pdf' | 'ofx' | 'qfx' | 'image'; pageCount: number; pages: StatementPage[]; checkpoints: StatementCheckpoint[]; periodStart: string | null; periodEnd: string | null; reviewed: boolean; warnings: string[] };
export type StatementSetupRow = ImportedSourceRow & { sourceIdentity: string; page: number; accountId: string; subcategoryId: string; transferAccountId: string; transferPairRowId: string; type: 'income' | 'expense' | 'refund' | 'transfer' | 'unknown'; decision: 'post' | 'retain' | 'exclude'; exclusionReason: string; retainedTransactionId: string };
export type StatementAccountMapping = { accountRef: string; accountId: string; openingDate: string; openingBalance: string; closingDate: string; closingBalance: string };
export type StatementSetupDraft = { version: 1; id: string; scope: StatementDraftScope; updatedAt: string; sources: StatementSource[]; rows: StatementSetupRow[]; accounts: StatementAccountMapping[] };
export type StatementHistoryInput = { createdBy: string; visibility: 'household' | 'personal'; accounts: Array<{ accountId: string; openingDate: string; openingBalanceCents: number; closingDate: string; closingBalanceCents: number; checkpoints?: Array<{ date: string; balanceCents: number }>; coverage?: Array<{ start: string; end: string }> }>; rows: Array<{ sourceIdentity: string; sourceHash: string; date: string; accountId: string; type: 'income' | 'expense' | 'refund' | 'transfer'; amountCents: number; subcategoryId?: string; toAccountId?: string; note: string; decision: 'post' | 'retain'; retainedTransactionId?: string; transferGroupIdentity?: string; transferSources?: Array<{ accountId: string; sourceIdentity: string; sourceHash: string }> }> };
export type StatementSetupProps = { household: Household; memberId: string; authUserId: string; view: LedgerView; onReviewHistory: (input: StatementHistoryInput, draftId: string) => Promise<void> | void; onUseSuggestions?: (suggestions: StatementSuggestion[]) => Promise<void> | void; acceptedCoverage?: Array<{ accountId: string; from: string; through: string; sourceIds: string[] }>; onDone?: () => void };
export type StatementSuggestion = { id: string; kind: 'category' | 'recurrence' | 'estimate'; label: string; reason: string; sourceIds: string[]; categoryId?: string; amountCents?: number; sampleSize: number; rhythmKey?: string; cadence?: import('../../core/types.ts').RecurrenceCadence };
