const DAY_KEY="toronto42-day-plan-2026-09-19",VISIT_KEY="toronto42-culinary-passport-v1",OUTCOME_KEY="toronto42-outcomes-v1",CUSTOM_KEY="toronto42-custom-stops-v1";
const BLOCKS=[
{id:"launch",start:"05:10",end:"05:25",type:"prep",label:"Launch",title:"Command centre",desc:"Open Work mode, Route Portal and checklist. Read ux-overhaul-feed and establish the exact execution queue before doing production work."},
{id:"ux1",start:"05:25",end:"06:45",type:"ux",label:"UX Sprint 1",title:"Turn the folder into an execution queue",desc:"Sort the folder into must-finish, implementation, review/decision, validation, blockers and later work. Leave with a short ordered queue."},
{id:"ready",start:"06:45",end:"07:30",type:"reset",label:"Reset",title:"Breakfast, shower, pack",desc:"Charge laptop/phone, pack charger or power bank, water and resume copies. Keep this low-cognitive."},
{id:"prep",start:"07:30",end:"08:20",type:"prep",label:"Job Prep",title:"Build the reusable restaurant prep system",desc:"Base cover-letter shell, flash-card template, 30–60 second pitch and Capra’s role talking points. Restaurant-specific prep should be 5–10 minutes after this."},
{id:"travel",start:"08:20",end:"09:20",type:"field",label:"Route",title:"Travel into Toronto + route review",desc:"Use the Route Portal to choose the first viable cluster. Quality conversations are the goal; do not chase pins for their own sake.",action:"portal"},
{id:"ux2",start:"09:20",end:"10:15",type:"ux",label:"UX Sprint 2",title:"First concrete implementation item",desc:"Laptop session near the first district while restaurant access is still early. Move the top executable item from the Work-mode queue."},
{id:"wave1",start:"10:15",end:"11:45",type:"field",label:"Restaurant Wave 1",title:"First manager-access window",desc:"Before serious targets, use Work mode for a micro-pack: research, cover letter and flash cards. Log the outcome immediately after every stop.",action:"district0"},
{id:"ux3",start:"11:45",end:"14:00",type:"ux",label:"Lunch Rush + UX",title:"Eat, then main laptop sprint",desc:"11:45–12:15 eat/decompress. 12:15–1:35 main implementation. 1:35–2:00 test, document and queue the next UX item."},
{id:"wave2",start:"14:00",end:"16:30",type:"field",label:"Restaurant Wave 2",title:"Main restaurant push",desc:"Move through one or two dense districts. Add strong unexpected restaurants immediately. Real conversations matter more than total attempts.",action:"portal"},
{id:"ux4",start:"16:30",end:"17:15",type:"ux",label:"UX Sprint 4",title:"Dinner-rush reset",desc:"Stop pushing busy managers. Fix one bounded issue, test it and update the continuation queue."},
{id:"evening",start:"17:15",end:"19:30",type:"field",label:"Selective Field",title:"Selective evening restaurant wave",desc:"Only revisit places that make sense now: requested returns, strong nearby opportunities or application follow-ups. Do not wait around during slammed service.",action:"portal"},
{id:"review",start:"19:30",end:"20:30",type:"reset",label:"Review",title:"Dinner + progress review",desc:"Check Route Portal totals: visited, interviews, maybes, apply-online pile, revisit list and remaining districts. Decide whether more field work is worth it.",action:"portal"},
{id:"ux5",start:"20:30",end:"21:45",type:"ux",label:"UX Sprint 5",title:"Finish, validate, package",desc:"No giant new feature. Finish the day’s implementation, validate it and leave reviewable output plus the next task."},
{id:"follow",start:"21:45",end:"22:15",type:"follow",label:"Follow-up",title:"Online applications + follow-ups",desc:"Handle every Need to apply online result while the conversations are fresh. Tailor each application from what happened in person.",action:"checklist"},
{id:"close",start:"22:15",end:"22:35",type:"follow",label:"Close",title:"Close the loop",desc:"One clean end-of-day state: restaurant outcomes, interviews, follow-ups, unexpected stops, UX work completed, open work and tomorrow’s first task."}
];

function preview(file,params={}){const qs=new URLSearchParams(params).toString();if(location.hostname==="html-preview.github.io"){const base="https://html-preview.github.io/?url=https%3A%2F%2Fgithub.com%2Fjonathanbeaulne123-blip%2Fdual-ai-budget-app%2Fblob%2Ftoronto-42-host%2Ftoronto42%2F"+encodeURIComponent(file);return base+(qs?"&"+qs:"")}return file+(qs?"?"+qs:"")}
document.querySelector("#backChecklist").href=preview("index.html");document.querySelector("#launchChecklist").href=preview("index.html");document.querySelector("#openPortal").href=preview("map.html");document.querySelector("#launchPortal").href=preview("map.html");

let state=JSON.parse(localStorage.getItem(DAY_KEY)||"{}");
const timeline=document.querySelector("#timeline");
function duration(a,b){const [ah,am]=a.split(":").map(Number),[bh,bm]=b.split(":").map(Number);const n=bh*60+bm-(ah*60+am);return n>=60?Math.floor(n/60)+"h "+(n%60? n%60+"m":"") : n+"m"}
function actions(block){if(!block.action)return"";if(block.action==="portal")return `<a class="mini-link" href="${preview("map.html")}">Open Route Portal ↗</a>`;if(block.action==="district0")return `<a class="mini-link" href="${preview("map.html",{focusDistrict:0})}">Open District 1 ↗</a>`;return `<a class="mini-link" href="${preview("index.html")}">Open checklist ↗</a>`}
function render(){timeline.innerHTML=BLOCKS.map(b=>`<article class="block ${state[b.id]?"done":""}" data-id="${b.id}" data-start="${b.start}" data-end="${b.end}"><div><span class="time">${b.start}–${b.end}</span><span class="duration">${duration(b.start,b.end)}</span></div><div><span class="type ${b.type}">${b.label}</span><span class="now-badge">Now</span><h3>${b.title}</h3><p>${b.desc}</p><div class="block-actions">${actions(b)}</div></div><input class="check" type="checkbox" aria-label="Mark ${b.title} complete" ${state[b.id]?"checked":""}></article>`).join("");timeline.querySelectorAll(".check").forEach(ch=>ch.onchange=()=>{const id=ch.closest(".block").dataset.id;if(ch.checked)state[id]=1;else delete state[id];localStorage.setItem(DAY_KEY,JSON.stringify(state));render();updateProgress()});highlightNow()}
function updateProgress(){const n=BLOCKS.filter(b=>state[b.id]).length,p=Math.round(n/BLOCKS.length*100);document.querySelector("#doneBlocks").textContent=n;document.querySelector("#dayPct").textContent=p+"% done";document.querySelector("#dayFill").style.width=p+"%"}
function highlightNow(){document.querySelectorAll(".block").forEach(x=>x.classList.remove("current"));const now=new Date();if(now.getFullYear()!==2026||now.getMonth()!==8||now.getDate()!==19){document.querySelector("#nowLabel").textContent=now<new Date(2026,8,19,5,10)?"Tomorrow starts at 5:10 AM":"Saturday plan";return}const min=now.getHours()*60+now.getMinutes();const active=BLOCKS.find(b=>{const[aH,aM]=b.start.split(":").map(Number),[eH,eM]=b.end.split(":").map(Number);return min>=aH*60+aM&&min<eH*60+eM});if(active){document.querySelector('.block[data-id="'+active.id+'"]')?.classList.add("current");document.querySelector("#nowLabel").textContent="Current block: "+active.title}else document.querySelector("#nowLabel").textContent=min<310?"Day starts at 5:10 AM":"Scheduled blocks finished"}
function updateSnapshot(){const S=JSON.parse(localStorage.getItem(VISIT_KEY)||"{}"),T=JSON.parse(localStorage.getItem(OUTCOME_KEY)||"{}"),X=JSON.parse(localStorage.getItem(CUSTOM_KEY)||"[]");document.querySelector("#visitedMetric").textContent=Object.keys(S).filter(k=>/^\d+$/.test(k)&&S[k]).length;document.querySelector("#interviewMetric").textContent=Object.values(T).filter(x=>x==="interview").length;document.querySelector("#applyMetric").textContent=Object.values(T).filter(x=>x==="apply-online").length;document.querySelector("#customMetric").textContent=X.length}
document.querySelector("#resetDay").onclick=()=>{if(confirm("Clear all Tomorrow Plan checkmarks?")){state={};localStorage.removeItem(DAY_KEY);render();updateProgress()}};
render();updateProgress();updateSnapshot();setInterval(highlightNow,60000);window.addEventListener("storage",updateSnapshot);
