/* Concise September 19 research additions. No external writes or applications. */
window.PASSPORT_DISCOVERIES = [
  {
    "id": "N01",
    "name": "Habitat Social",
    "address": "70 Lakeshore Rd E, Mississauga",
    "cluster": "Port Credit",
    "tier": "A-GAME",
    "why": "Cocktail-led restaurant with dinner service; direct bar-lead fit.",
    "transit": "Port Credit GO; roughly 7–10 min walk.",
    "hours": "Brunch 11am–3pm; dinner from 5:30pm",
    "site": "https://www.habitatsocial.ca/menu",
    "job": "Bartender application verified earlier September 19.",
    "roles": "Bartender",
    "pay": "C$20/hour + tips",
    "url": "https://www.86network.com/jobs/mississauga/on/habitat-social-modern-kitchen/bartender-bkkitw?index=34&query=lounge-server",
    "status": "active",
    "requirements": "Part-time; two evening days per week advertised.",
    "extra": []
  },
  {
    "id": "N02",
    "name": "Tabule Oakville",
    "address": "234 Lakeshore Rd E, Oakville",
    "cluster": "Downtown Oakville",
    "tier": "A-GAME",
    "why": "Polished Middle Eastern dining; coaching and floor operations offer a leadership step.",
    "transit": "Oakville GO; about 31 min walk or quoted short Uber.",
    "hours": "11:30am–10:30pm",
    "site": "https://tabule.ca/location/tabule-oakville/",
    "job": "FOH Service Manager verified earlier September 19.",
    "roles": "FOH Service Manager",
    "pay": "From C$55,000/year",
    "url": "https://ca.indeed.com/viewjob?jk=c9a0efea8c959705",
    "status": "active",
    "requirements": "1–2 years management/supervision and Smart Serve; match actual responsibilities.",
    "extra": []
  },
  {
    "id": "N03",
    "name": "Cactus Club First Canadian Place",
    "address": "77 Adelaide St W, Toronto",
    "cluster": "King West / Downtown",
    "tier": "A-GAME",
    "why": "Polished high-volume dining with bar and management options.",
    "transit": "Union; roughly 7–10 min walk.",
    "hours": "11:30am–1am",
    "site": "https://www.cactusclubcafe.com/locations/first-canadian-place/",
    "job": "Bartender and manager repost verified earlier September 19. Older manager ad is closed.",
    "roles": "Bartender / Restaurant Manager",
    "pay": "Manager C$57,000–75,000/year",
    "url": "https://www.86network.com/jobs/toronto/on/cactus-club-cafe-first-canadian-place/manager-jgqa5g",
    "status": "active",
    "requirements": "Manager: hospitality-management experience and listed certifications; late finishes need a return plan.",
    "extra": [
      [
        "Bartender",
        "https://www.86network.com/jobs/toronto/on/cactus-club-cafe-first-canadian-place/bartender-zi2gbq"
      ]
    ]
  },
  {
    "id": "N04",
    "name": "Bâton Rouge Oakville",
    "address": "2005 Winston Park Dr, Oakville",
    "cluster": "Oakville north / online first",
    "tier": "OPPORTUNISTIC",
    "why": "Steakhouse with bar, service and supervisory recruitment; a reserve beyond the tighter lakeshore clusters.",
    "transit": "Clarkson GO; 5.9 km last mile. Uber quote needed; not a practical rail/walk stop.",
    "hours": "Noon–11pm",
    "site": "https://www.batonrouge.ca/en/baton-rouge-oakville",
    "job": "Official branch lists roles; standing recruitment, not confirmed urgent vacancies.",
    "roles": "Bartender / Server / Dining Room Supervisor / Service Bar / Manager",
    "pay": "",
    "url": "https://www.batonrouge.ca/en/baton-rouge-oakville",
    "status": "standing",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N05",
    "name": "Laylak Oakville",
    "address": "1515 Rebecca St, unit 19, Oakville",
    "cluster": "Bronte",
    "tier": "STRONG",
    "why": "Upscale Lebanese dining with a supervisory lead.",
    "transit": "Bronte GO; about 38 min walk or quoted short Uber.",
    "hours": "Published 11:30am–10:50pm; recheck",
    "site": "https://laylak.ca/menu-oakville/",
    "job": "FOH Supervisor found on Workopolis; employer confirmation pending.",
    "roles": "FOH Supervisor",
    "pay": "Advertised C$19/hour",
    "url": "https://www.workopolis.com/jobsearch/viewjob/kA3Ut0J-vJeuBTE87lNLzayeUXkaUbTeRCp63fYMNMrIvofVb6xgMFrKTghQhIYi",
    "status": "signal",
    "requirements": "Full-time fixed-term; two years similar work requested. Clarify tips and authority.",
    "extra": []
  },
  {
    "id": "N06",
    "name": "Auberge du Pommier",
    "address": "4150 Yonge St, Toronto",
    "cluster": "North / Midtown",
    "tier": "STRONG",
    "why": "French fine dining, wine and classic cocktails; a meaningful service-development room.",
    "transit": "York Mills; about 5 min walk. Today use Cedarvale → Line 5 → Eglinton → Line 1 north.",
    "hours": "Dinner seating 5–9:30pm",
    "site": "https://www.aubergedupommier.com/",
    "job": "Part-time bartender opening verified earlier September 19.",
    "roles": "Bartender",
    "pay": "C$17.60/hour + gratuities",
    "url": "https://www.86network.com/jobs/york-mills/on/auberge-du-pommier/bartender-part-time-fine-dining-auberge-du-pommier-gg81wg?index=31&query=",
    "status": "active",
    "requirements": "Two years comparable bartending requested; dinner opening is not a hiring window.",
    "extra": []
  },
  {
    "id": "N07",
    "name": "Piano Piano Mount Pleasant",
    "address": "623 Mount Pleasant Rd, Toronto",
    "cluster": "North / Midtown",
    "tier": "STRONG",
    "why": "Distinctive Italian room with a restaurant-management opportunity; different location from original Piano Piano.",
    "transit": "Eglinton; about 14–18 min walk. Use Line 5 detour today.",
    "hours": "Published noon–10:30pm",
    "site": "https://www.pianopianotherestaurant.com/",
    "job": "Restaurant Manager verified earlier September 19.",
    "roles": "Restaurant Manager",
    "pay": "C$40/hour advertised",
    "url": "https://www.86network.com/jobs/toronto/on/piano-piano-the-restaurant/restaurant-manager-nlo0iq",
    "status": "active",
    "requirements": "Three or more years restaurant management; Bar Lead alone does not prove the requirement.",
    "extra": []
  },
  {
    "id": "N08",
    "name": "Baro / Honeycomb Hospitality",
    "address": "485 King St W, Toronto; job lists 487 Adelaide W",
    "cluster": "King West / Downtown",
    "tier": "OPPORTUNISTIC",
    "why": "Cocktails and a distinctive restaurant environment; confirm the assigned venue first.",
    "transit": "Downtown; worksite unresolved, so apply online before travelling.",
    "hours": "Confirm assigned outlet and hours",
    "site": "https://barotoronto.com/contact/",
    "job": "Honeycomb bartender opening verified earlier September 19; Baro assignment not established.",
    "roles": "Experienced Bartender",
    "pay": "",
    "url": "https://www.86network.com/jobs/toronto/on/honeycomb-hospitality/bartender-naxjg",
    "status": "active",
    "requirements": "Two years high-volume bar experience; Smart Serve or willingness to obtain; confirm worksite.",
    "extra": []
  },
  {
    "id": "N09",
    "name": "Befikre",
    "address": "Mississauga — confirm worksite on posting",
    "cluster": "Mississauga / online first",
    "tier": "OPPORTUNISTIC",
    "why": "Contemporary Indian dining with a management lead; keep as an online reserve.",
    "transit": "Exact worksite and Saturday last mile not verified.",
    "hours": "Confirm before travel",
    "site": "https://www.befikre.ca/",
    "job": "Job Bank manager lead; advertised closing date September 24.",
    "roles": "Restaurant Manager",
    "pay": "C$37.50/hour; 35 hours/week",
    "url": "https://on.jobbank.gc.ca/jobsearch/jobposting/50217251",
    "status": "signal",
    "requirements": "College/CEGEP and operational experience need a résumé match.",
    "extra": []
  },
  {
    "id": "N10",
    "name": "Ruth’s Chris Downtown Toronto",
    "address": "145 Richmond St W, Toronto",
    "cluster": "King West / Downtown",
    "tier": "A-GAME",
    "why": "Steakhouse with a direct bar-lead step and a separate experienced private-dining management role.",
    "transit": "Union; mapped roughly 10 min walk.",
    "hours": "3–10pm",
    "site": "https://rct.bamboohr.com/careers/77",
    "job": "Both exact employer applications verified earlier September 19.",
    "roles": "Bartender / Team Leader; Private Dining Sales & Operations Manager",
    "pay": "Bar: minimum wage + tips; separate lead rate. Private dining: C$70,000 + commission/bonus.",
    "url": "https://rct.bamboohr.com/careers/77",
    "status": "active",
    "requirements": "Bar lead: about 4–8 leadership hours/week. Private dining: at least 3 years fine-dining private-dining management.",
    "extra": [
      [
        "Private Dining Sales & Operations Manager",
        "https://rct.bamboohr.com/careers/40"
      ]
    ]
  },
  {
    "id": "N11",
    "name": "Ce Soir",
    "address": "134 Lakeshore Rd E, Oakville",
    "cluster": "Downtown Oakville",
    "tier": "A-GAME",
    "why": "Brasserie and events; strong connection to bar leadership and private-event coordination.",
    "transit": "Oakville GO; mapped 34 min walk or quoted short Uber.",
    "hours": "11am–1am; kitchen until 11pm",
    "site": "https://app.higherme.com/jobs/648498fbd2628?domain=careerbeacon.com",
    "job": "On-Site Event Coordinator verified earlier September 19.",
    "roles": "On-Site Event Coordinator",
    "pay": "C$75,000–85,000/year",
    "url": "https://app.higherme.com/jobs/648498fbd2628?domain=careerbeacon.com",
    "status": "active",
    "requirements": "Prior management or leadership, event background and flexible scheduling. No fixed years published.",
    "extra": []
  },
  {
    "id": "N12",
    "name": "Mercatto Centrale",
    "address": "230 Missinnihe Way, Mississauga",
    "cluster": "Port Credit",
    "tier": "STRONG",
    "why": "Italian dining with bar and service roles; convenient Port Credit cluster.",
    "transit": "Port Credit GO; 1.5 km, allow about 20–25 min walking.",
    "hours": "10:30am–midnight",
    "site": "https://app-elb.pushoperations.com/ats/job-postings/d55b44e7-e061-485f-94c2-967fd0e690e5/public",
    "job": "Two original application forms verified earlier September 19.",
    "roles": "Bartender / Server",
    "pay": "C$17.60/hour + gratuities",
    "url": "https://app-elb.pushoperations.com/ats/job-postings/d55b44e7-e061-485f-94c2-967fd0e690e5/public",
    "status": "active",
    "requirements": "Full-time; Smart Serve and service/POS experience.",
    "extra": [
      [
        "Server",
        "https://app-elb.pushoperations.com/ats/job-postings/9fdb5c16-f729-4625-b01c-8c5f6c628fe6/public"
      ]
    ]
  },
  {
    "id": "N13",
    "name": "PUNCH / Le Germain Toronto Mercer",
    "address": "30 Mercer St, Toronto",
    "cluster": "King West / Downtown",
    "tier": "STRONG",
    "why": "Hotel restaurant with an event-sales and business-development management lane.",
    "transit": "Union; mapped about 13 min walk.",
    "hours": "Dinner 5pm–midnight",
    "site": "https://recruiting.ultipro.ca/GRO5006GRGEI/JobBoard/c725386f-f3f1-4e11-803c-94583205f547/OpportunityDetail?opportunityId=6b4ae5df-0e1b-4da6-a439-034fdcfdbde9",
    "job": "Employer application verified earlier September 19; posting dated September 14.",
    "roles": "Restaurant Business Development Manager",
    "pay": "C$60,000–70,000/year + bonus",
    "url": "https://recruiting.ultipro.ca/GRO5006GRGEI/JobBoard/c725386f-f3f1-4e11-803c-94583205f547/OpportunityDetail?opportunityId=6b4ae5df-0e1b-4da6-a439-034fdcfdbde9",
    "status": "active",
    "requirements": "3–5 years hospitality/event sales or business development; coordination alone is not sales experience.",
    "extra": []
  },
  {
    "id": "N14",
    "name": "CLOCKWORK — Fairmont Royal York",
    "address": "100 Front St W, Toronto",
    "cluster": "Union / Financial District",
    "tier": "OPPORTUNISTIC",
    "why": "Luxury hotel setting; support-role entry rather than a leadership step.",
    "transit": "Across from Union.",
    "hours": "Dinner 4pm–midnight",
    "site": "https://careers.accor.com/id/id/job/assistant-server-clockwork-part-time-in-fairmont-royal-york-toronto-canada-jid-110603",
    "job": "Official application verified earlier September 19.",
    "roles": "Assistant Server — part-time",
    "pay": "",
    "url": "https://careers.accor.com/id/id/job/assistant-server-clockwork-part-time-in-fairmont-royal-york-toronto-canada-jid-110603",
    "status": "active",
    "requirements": "Clarify pay, weekly hours and progression; support role may be a title step down.",
    "extra": []
  },
  {
    "id": "N15",
    "name": "The National Club",
    "address": "303 Bay St, Toronto",
    "cluster": "Union / Financial District",
    "tier": "A-GAME",
    "why": "Private-club events match your coordination background particularly well.",
    "transit": "Union; short downtown walk. Private club: online first.",
    "hours": "Not a public walk-in recruitment stop",
    "site": "https://thenationalclub.com/MENU/Catering",
    "job": "Exact Event Coordinator application verified earlier September 19.",
    "roles": "Event Coordinator",
    "pay": "C$26–28/hour",
    "url": "https://www.86network.com/jobs/toronto/on/the-national-club/event-coordinator-gobwtw",
    "status": "active",
    "requirements": "Event/catering/hospitality experience; proposals, timelines and billing; some evening/weekend work.",
    "extra": []
  },
  {
    "id": "N16",
    "name": "W Toronto",
    "address": "90 Bloor St E, Toronto",
    "cluster": "Yorkville",
    "tier": "STRONG",
    "why": "Luxury hotel bar and service options; exact outlet is not named.",
    "transit": "Line 2 Bloor–Yonge via St George today; short walk.",
    "hours": "Outlet and shift hours unconfirmed",
    "site": "https://careers.marriott.com/bartender/job/7700F4D4012A325C186F6772853F306C",
    "job": "Three official hotel openings verified earlier September 19.",
    "roles": "Bartender / In-Room Dining Server / Host",
    "pay": "Bar C$20.78–25.97; room service C$17.80–20.98; host C$22.08–27.60/hour, tip eligible.",
    "url": "https://careers.marriott.com/bartender/job/7700F4D4012A325C186F6772853F306C",
    "status": "active",
    "requirements": "Bar and room service: one year related experience and Smart Serve. Do not assume a TONO placement.",
    "extra": [
      [
        "In-Room Dining Server",
        "https://careers.marriott.com/in-room-dining-server/job/6A5B5A853CA97AFDF12D3C59A175C16C"
      ],
      [
        "Host",
        "https://careers.marriott.com/host-or-hostess/job/C6EB635C5C44B9D673B9B71B159CAFE9"
      ]
    ]
  },
  {
    "id": "N17",
    "name": "The Ritz-Carlton Toronto",
    "address": "181 Wellington St W, Toronto",
    "cluster": "Union / Financial District",
    "tier": "STRONG",
    "why": "Luxury service experience; seasonal role, outlet unnamed.",
    "transit": "Union or St Andrew; short walk.",
    "hours": "Confirm outlet and shifts",
    "site": "https://careers.marriott.com/server/job/830F2A7C9050DE5393533377A5E39EDD",
    "job": "Official application verified earlier September 19.",
    "roles": "Server — part-time seasonal",
    "pay": "C$17.60–19.47/hour; tip eligible",
    "url": "https://careers.marriott.com/server/job/830F2A7C9050DE5393533377A5E39EDD",
    "status": "active",
    "requirements": "One year related experience; confirm seasonal end date. Do not assume TOCA.",
    "extra": []
  },
  {
    "id": "N18",
    "name": "The St. Regis Toronto",
    "address": "325 Bay St, Toronto",
    "cluster": "Union / Financial District",
    "tier": "OPPORTUNISTIC",
    "why": "Luxury hotel support role; evaluate learning against responsibility and pay.",
    "transit": "King or Union; short downtown walk.",
    "hours": "Outlet and shift hours unconfirmed",
    "site": "https://careers.marriott.com/server-attendant/job/76E23C3B844F28319422FECD1974ED88",
    "job": "Official application verified earlier September 19.",
    "roles": "Server Attendant",
    "pay": "C$17.60–18.72/hour; tip eligible",
    "url": "https://careers.marriott.com/server-attendant/job/76E23C3B844F28319422FECD1974ED88",
    "status": "active",
    "requirements": "Full-time; Smart Serve. No verified Louix Louis assignment or management pathway.",
    "extra": []
  },
  {
    "id": "N19",
    "name": "The Olive Press",
    "address": "2322 Dundas St W, Oakville",
    "cluster": "Oakville north / online first",
    "tier": "OPPORTUNISTIC",
    "why": "Italian restaurant with an evergreen bar, service and manager route; longer-commute reserve.",
    "transit": "Long last mile from GO. Confirm an appointment and Uber quote first.",
    "hours": "Noon–10pm",
    "site": "https://www.olivepress.ca/menu/",
    "job": "Standing job profiles; no specific current vacancy established.",
    "roles": "Server / Bartender / Service Manager",
    "pay": "",
    "url": "https://www.olivepress.ca/jobs/",
    "status": "standing",
    "requirements": "Server/bar: three years preferred; manager: five years high-volume experience requested.",
    "extra": []
  },
  {
    "id": "N20",
    "name": "The Chase",
    "address": "10 Temperance St, fifth floor, Toronto",
    "cluster": "Union / Financial District",
    "tier": "STRONG",
    "why": "Premium dining and cocktail service with a general employer application route.",
    "transit": "Queen or King; short downtown walk.",
    "hours": "Confirm current Saturday hours",
    "site": "https://www.thechasetoronto.com/menu/dinner/",
    "job": "General Service/Culinary interest form; no named current FOH vacancy.",
    "roles": "Future service / bar",
    "pay": "",
    "url": "https://www.thechasetoronto.com/careers-form/",
    "status": "standing",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N21",
    "name": "Library Bar — Fairmont Royal York",
    "address": "100 Front St W, Toronto",
    "cluster": "Union / Financial District",
    "tier": "STRONG",
    "why": "Luxury hotel cocktail room with a direct service opening.",
    "transit": "Across from Union.",
    "hours": "Noon–midnight",
    "site": "https://www.fairmont.com/en/hotels/toronto/fairmont-royal-york/dining/librarybar.bar.html",
    "job": "Exact Server opening verified earlier September 19.",
    "roles": "Server — permanent part-time",
    "pay": "Starting C$17.60/hour; increase after six months compensated service",
    "url": "https://jobs.smartrecruiters.com/AccorHotel/744000146466781-server-library-bar-part-time-",
    "status": "active",
    "requirements": "Restaurant/F&B experience, Smart Serve and weekend/holiday availability; tips and hours unspecified.",
    "extra": []
  },
  {
    "id": "N22",
    "name": "Minami Toronto",
    "address": "225 King St W, Toronto",
    "cluster": "King West / Downtown",
    "tier": "STRONG",
    "why": "Design-led Japanese dining, aburi sushi, sake, cocktails and private events.",
    "transit": "St Andrew; roughly 3–5 min walk.",
    "hours": "4pm–midnight",
    "site": "https://www.minamitoronto.com/",
    "job": "Standing FOH/manager invitation; linked Indeed roles returned 404.",
    "roles": "Future FOH / Restaurant Manager",
    "pay": "",
    "url": "https://www.minamitoronto.com/careers",
    "status": "standing",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N23",
    "name": "Le Sélect Bistro",
    "address": "432 Wellington St W, Toronto",
    "cluster": "Wellington / The Well",
    "tier": "STRONG",
    "why": "French bistro and serious wine cellar. Dinner examples: moules frites C$28, trout C$32.",
    "transit": "Union or St Andrew, then walk; pair with Lulu and La Plume.",
    "hours": "10:30am–late",
    "site": "https://www.leselectbistro.com/menu/dinner/",
    "job": "No current matching vacancy verified.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N24",
    "name": "Lulu Bar Toronto",
    "address": "427 Wellington St W, Toronto",
    "cluster": "Wellington / The Well",
    "tier": "STRONG",
    "why": "Contemporary Pacific-influenced cooking and cocktails; linguini C$24, fried chicken C$32.",
    "transit": "Walk the Wellington cluster from Union or St Andrew.",
    "hours": "11am–midnight",
    "site": "https://www.lulubar.ca/toronto",
    "job": "Checked Server posting is expired.",
    "roles": "Server — closed",
    "pay": "",
    "url": "https://jobs.smartrecruiters.com/OliverBonacini/744000141781144-server-lulu-bar",
    "status": "closed",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N25",
    "name": "7 Enoteca",
    "address": "216 Lakeshore Rd E, Oakville",
    "cluster": "Downtown Oakville",
    "tier": "STRONG",
    "why": "Intimate Italian wine room, wood-fired oven and group dining.",
    "transit": "Oakville GO; long walk or quoted short Uber. Near Ce Soir and Centro.",
    "hours": "Noon–2pm and 5–10pm",
    "site": "https://www.sevenenoteca.com/",
    "job": "Employer profile had kitchen roles, not matching FOH openings.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N26",
    "name": "Verace",
    "address": "312 Lakeshore Rd E, Oakville",
    "cluster": "Downtown Oakville",
    "tier": "STRONG",
    "why": "Polished Italian dining and private events; pasta C$30–36 and branzino C$46.",
    "transit": "Oakville GO plus walk or quoted short Uber; Lakeshore cluster.",
    "hours": "Noon–11pm",
    "site": "https://www.veracepizza.ca/menu",
    "job": "No current matching vacancy verified.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N27",
    "name": "POSTA Italbar Cucina",
    "address": "31 Lakeshore Rd E, Mississauga",
    "cluster": "Port Credit",
    "tier": "STRONG",
    "why": "Waterfront Italian dining, cocktails and private events.",
    "transit": "Port Credit GO; allow about 10–15 min walk.",
    "hours": "11am–midnight",
    "site": "https://www.postaportcredit.com/",
    "job": "No current matching vacancy verified.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N28",
    "name": "La Vita",
    "address": "100 Lakeshore Rd E, Mississauga",
    "cluster": "Port Credit",
    "tier": "OPPORTUNISTIC",
    "why": "Mediterranean food and events; chicken C$26, lamb tajine C$37, branzino C$42.",
    "transit": "Port Credit GO; roughly 10 min walk.",
    "hours": "Noon–11pm",
    "site": "https://lavitaportcredit.ca/",
    "job": "Employer profile showed kitchen jobs, not matching FOH openings.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N29",
    "name": "Cucci",
    "address": "119 Jones St, Oakville",
    "cluster": "Bronte",
    "tier": "STRONG",
    "why": "Fine-dining Italian room with a marble bar and private events.",
    "transit": "Bronte GO; separate local last mile, quote Uber before travelling.",
    "hours": "Dinner from 5pm",
    "site": "https://cucci.ca/",
    "job": "Catch Hospitality accepts future-interest applications; no named vacancy.",
    "roles": "Future FOH / Bar",
    "pay": "",
    "url": "https://catchhospitalitygroup.ca/work/",
    "status": "standing",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N30",
    "name": "La Plume",
    "address": "453 Wellington St W, Toronto",
    "cluster": "Wellington / The Well",
    "tier": "A-GAME",
    "why": "French brasserie, cocktails and speakeasy; strong service-development fit.",
    "transit": "Union or St Andrew then walk; pair with Le Sélect and Bridgette.",
    "hours": "Bar 11am–2am; dinner 5–10:30pm",
    "site": "https://www.laplumebrasserie.com/menu/",
    "job": "Exact Server opening verified earlier September 19; separate from older closed ads.",
    "roles": "Server",
    "pay": "C$17.60/hour + shared gratuities",
    "url": "https://jobs.smartrecruiters.com/OliverBonacini/744000050128725-server-la-plume",
    "status": "active",
    "requirements": "Two years similar serving, Smart Serve and flexible evenings/weekends/holidays.",
    "extra": []
  },
  {
    "id": "N31",
    "name": "Maison Selby",
    "address": "592 Sherbourne St, Toronto",
    "cluster": "Yorkville",
    "tier": "STRONG",
    "why": "Historic-house French bistro with speakeasy and private dining; bar inventory work fits your background.",
    "transit": "Line 2 Sherbourne via St George; short walk.",
    "hours": "Brunch 11am–2:30pm; bar bites to 5pm; dinner 5–9:30pm",
    "site": "https://www.maisonselby.com/menus/",
    "job": "Exact Bartender opening verified earlier September 19. Header/body disagree about full vs part-time.",
    "roles": "Bartender",
    "pay": "C$17.60–18.50/hour + gratuities",
    "url": "https://jobs.smartrecruiters.com/OliverBonacini/744000065044035-bartender-maison-selby",
    "status": "active",
    "requirements": "Body: part-time, three shifts, open availability/doubles; 6–12 months bar experience, Smart Serve; WSET preferred.",
    "extra": []
  },
  {
    "id": "N32",
    "name": "Open Aera",
    "address": "8 Spadina Ave, rooftop, Toronto",
    "cluster": "Wellington / The Well",
    "tier": "STRONG",
    "why": "Premium rooftop cocktails, champagne and bottle service; nightlife-heavy option.",
    "transit": "Union then walk; late closing shifts may miss the train.",
    "hours": "Rooftop from 4pm–late; bottle service 9pm–2am",
    "site": "https://aerarestaurant.com/contact/",
    "job": "Exact Open Aera bartender opening verified earlier September 19; expired Aera management ads are different.",
    "roles": "Bartender",
    "pay": "C$17.60/hour + gratuities",
    "url": "https://jobs.smartrecruiters.com/OliverBonacini/744000116738002-bartender-open-aera",
    "status": "active",
    "requirements": "Two years high-volume restaurant/lounge/nightclub bar work and Smart Serve; confirm seasonality and closing times.",
    "extra": []
  },
  {
    "id": "N33",
    "name": "Cagney’s Steakhouse & Wine Bar",
    "address": "128 Queen St S, Mississauga",
    "cluster": "Streetsville / online first",
    "tier": "STRONG",
    "why": "Steakhouse, wine and group service with a floor-management interest route.",
    "transit": "No Saturday Milton train assumption. Confirm hiring before paying for the last mile.",
    "hours": "11:30am–11pm",
    "site": "https://cagneys.ca/dinner/",
    "job": "Undated official invitation names bartender, experienced server and floor manager; freshness unconfirmed.",
    "roles": "Bartender / Experienced Server / Floor Manager",
    "pay": "",
    "url": "https://cagneys.ca/careers/",
    "status": "standing",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N34",
    "name": "Bridgette Bar Toronto",
    "address": "423 Wellington St W, Toronto",
    "cluster": "Wellington / The Well",
    "tier": "OPPORTUNISTIC",
    "why": "Chef-led food, creative cocktails and a distinctive room beside La Plume.",
    "transit": "Walk within Wellington cluster.",
    "hours": "11:30am–late",
    "site": "https://www.bridgettebar.com/toronto",
    "job": "Checked Bartender posting expired. Scout only.",
    "roles": "Bartender — closed",
    "pay": "",
    "url": "",
    "status": "closed",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N35",
    "name": "Enoteca Sociale",
    "address": "1288 Dundas St W, Toronto",
    "cluster": "Queen West / Ossington",
    "tier": "STRONG",
    "why": "Pasta and private wine-cellar dining; a coherent wine and event-service development prospect.",
    "transit": "Dufferin or Ossington Line 2 plus a longer walk; check route.",
    "hours": "5–11pm",
    "site": "https://sociale.ca/",
    "job": "Indexed bartender signal; current application availability unconfirmed.",
    "roles": "Bartender lead",
    "pay": "",
    "url": "",
    "status": "signal",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N36",
    "name": "Bar Vendetta",
    "address": "928 Dundas St W, Toronto",
    "cluster": "Queen West / Ossington",
    "tier": "OPPORTUNISTIC",
    "why": "Intimate pasta/wine room; sample pasta C$19–29.",
    "transit": "Line 2 plus a longer southward walk; pair with nearby stops.",
    "hours": "5–10:30pm",
    "site": "https://www.barvendetta.com/",
    "job": "Server signal was not confirmed as an exact current opening.",
    "roles": "Server lead",
    "pay": "",
    "url": "",
    "status": "signal",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N37",
    "name": "Centro on the Square",
    "address": "210 Lakeshore Rd E, Oakville",
    "cluster": "Downtown Oakville",
    "tier": "STRONG",
    "why": "Fine dining, wine, cocktails and events; pasta C$36, hen C$39, salmon C$50. Current operator, not old Hexagon.",
    "transit": "Oakville GO plus walk or quoted local Uber; beside 7 Enoteca.",
    "hours": "5–10:30pm",
    "site": "https://www.centroonthesquare.ca/",
    "job": "No current matching vacancy verified. Manuel Gonzalez is publicly named GM/Wine Director.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N38",
    "name": "Por Vida",
    "address": "2330 Lakeshore Rd W, Oakville",
    "cluster": "Bronte",
    "tier": "STRONG",
    "why": "Distinctive Mexican food, tequila/mezcal programme and private bookings.",
    "transit": "Bronte GO plus local last mile; pair with Cucci.",
    "hours": "Noon–midnight",
    "site": "https://porvida.ca/",
    "job": "No current matching vacancy verified.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current requirements and shift times.",
    "extra": []
  },
  {
    "id": "N39",
    "name": "Alobar Downtown",
    "address": "150 York St, Toronto",
    "cluster": "King West / Downtown",
    "tier": "A-GAME",
    "why": "Polished dining, prime cuts, seafood, cocktails and private dining; strong service-training and bar-development potential.",
    "transit": "150 York St; St Andrew, approximately 5–8 minutes. Saturday 5–10pm.",
    "hours": "Saturday 5–10pm.",
    "site": "https://thealobar.com/alobar-downtown/",
    "job": "Alo Food Group has a standing résumé intake. No exact current Downtown vacancy verified. Pitch bar/service with eventual floor leadership, grounded in your actual experience.",
    "roles": "Future bar / service / floor leadership",
    "pay": "",
    "url": "https://alofoodgroup.com/careers/",
    "status": "standing",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N40",
    "name": "Scaramouche",
    "address": "1 Benvenuto Place, Toronto",
    "cluster": "Dupont / St Clair",
    "tier": "A-GAME",
    "why": "Classic fine dining, complex food/wine service and an established luxury environment. A demanding service-development target.",
    "transit": "1 Benvenuto Place; use Dupont on the University side, approximately 20–25 minutes on foot, with hills. Saturday opens 5pm; last reservation 9:30pm.",
    "hours": "Saturday opens 5pm; last reservation 9:30pm.",
    "site": "https://www.scaramoucherestaurant.com/",
    "job": "Official site expressly invites FOH résumés. This is an introduction opportunity, not proof of a specific vacancy.",
    "roles": "Future FOH",
    "pay": "",
    "url": "https://www.scaramoucherestaurant.com/",
    "status": "standing",
    "requirements": "Official intake: scaramouche@rogers.com. Exacting fine-dining service; no specific vacancy.",
    "extra": []
  },
  {
    "id": "N41",
    "name": "Bar Filo",
    "address": "146 Yonge St, Toronto",
    "cluster": "King West / Downtown",
    "tier": "STRONG",
    "why": "Italian cocktail restaurant with lobster risotto, hamachi and ribeye. Direct bar/service relevance and an efficient downtown stop.",
    "transit": "146 Yonge St; Queen, approximately 3–5 minutes. Saturday 5–10pm.",
    "hours": "Saturday 5–10pm.",
    "site": "https://www.barfilo.ca/",
    "job": "The employer's EightSix page lists bartender and server as active; each exact posting displays Apply Now. Bartender: PT, $19/hour, three afternoons/evenings; server: PT, $17.60/hour. Tips are not quantified.",
    "roles": "Bartender / Server",
    "pay": "Bar C$19/hour; server C$17.60/hour",
    "url": "https://www.86network.com/jobs/toronto/on/bar-filo/bartender-qb9c6w",
    "status": "active",
    "requirements": "Part-time, three days; Smart Serve. Bartender copy says typically 5–7 years and has inconsistent education wording; clarify.",
    "extra": [
      [
        "Server",
        "https://www.86network.com/jobs/toronto/on/bar-filo/server-sirb6g"
      ]
    ]
  },
  {
    "id": "N42",
    "name": "GEORGE",
    "address": "111C Queen St E, Toronto",
    "cluster": "King West / Downtown",
    "tier": "STRONG",
    "why": "Tasting-menu service, wine knowledge and events create a credible progression beyond ordinary casual dining.",
    "transit": "111C Queen St E; Queen, approximately 7–10 minutes. Saturday dinner 5:30–10:30pm; last reservation 9pm.",
    "hours": "Saturday dinner 5:30–10:30pm; last reservation 9pm.",
    "site": "https://www.georgeonqueen.com/contact",
    "job": "An assistant-manager listing was found on Workopolis, but an enabled official employer application was not confirmed. Treat management as an unverified lead.",
    "roles": "Assistant Manager — unverified",
    "pay": "",
    "url": "https://www.workopolis.com/jobsearch/viewjob/hnN1up11PEFpR71-9mKGH1vZASchXI7hlLKOFj4mB1oE3iKCkDn3yMeSx4rDNXe8",
    "status": "signal",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N43",
    "name": "Takja BBQ House",
    "address": "962 College St, Toronto",
    "cluster": "College / Bloor West",
    "tier": "STRONG",
    "why": "High-touch Korean BBQ, dry-aged meats, tableside service, curated wine and cocktails. Distinctive experience worth learning.",
    "transit": "962 College St; Dufferin or Ossington, allow 15–20 minutes. Saturday 5–10pm. Pair with Lardo.",
    "hours": "Saturday 5–10pm.",
    "site": "https://www.takja.ca/",
    "job": "The exact bartender listing is closed. Its title and server-focused body also differ. Historic advertised tips are not current earnings evidence.",
    "roles": "Bartender — closed",
    "pay": "",
    "url": "",
    "status": "closed",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N44",
    "name": "Lardo",
    "address": "970 College St, Toronto",
    "cluster": "College / Bloor West",
    "tier": "STRONG",
    "why": "Intimate Italian dining, a serious bar and group dining. Particularly relevant to your combination of bar lead and private-event coordination.",
    "transit": "970 College St, beside Takja; same 15–20-minute Line 2 approach. Saturday 5pm–late. Closing-shift return needs discussion.",
    "hours": "Saturday 5pm–late.",
    "site": "https://www.lardo.ca/about-us",
    "job": "The exact Lead Bartender / Bar Manager listing is closed. A useful signal about the type of role the restaurant has hired, not an available job.",
    "roles": "Lead Bartender / Bar Manager — closed",
    "pay": "",
    "url": "",
    "status": "closed",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N45",
    "name": "Bar Prima",
    "address": "1136 Queen St W, Toronto",
    "cluster": "Queen West / Ossington",
    "tier": "STRONG",
    "why": "A polished Italian room with ambitious cocktails and wine: strong aesthetic and service fit. Official menu lists a $110 chef's menu and $60 pairing.",
    "transit": "1136 Queen St W; allow 25–35 minutes walking from Ossington Line 2, or roughly 25–30 from Exhibition GO. Evening service; published Saturday hours 5–10pm.",
    "hours": "Saturday hours 5–10pm.",
    "site": "https://barprima.ca/",
    "job": "No current relevant vacancy verified. Future bar, server or floor-lead prospect.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N46",
    "name": "Azhar",
    "address": "96 Ossington Ave, Toronto",
    "cluster": "Queen West / Ossington",
    "tier": "STRONG",
    "why": "Fire-led Eastern Mediterranean cooking, cocktails, catering and private dining broaden both beverage and event experience.",
    "transit": "96 Ossington Ave; Ossington Line 2, approximately 20–25 minutes. Saturday noon–10:30pm.",
    "hours": "Saturday noon–10:30pm.",
    "site": "https://azhartoronto.com/about-azhar-soulful-mediterranean",
    "job": "No current relevant vacancy verified. Ask about future bar/service/event needs only if a manager is available.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N47",
    "name": "Mhel",
    "address": "276 Havelock St, Toronto",
    "cluster": "College / Bloor West",
    "tier": "STRONG",
    "why": "Korean/Japanese small plates and sake make this a distinctive beverage-learning option, with a much less conventional luxury format.",
    "transit": "276 Havelock St; Dufferin Line 2, approximately 5–10 minutes. Official hours Wednesday–Sunday 5:30–10:30pm. Add before the College/Dovercourt pair.",
    "hours": "Official hours Wednesday–Sunday 5:30–10:30pm.",
    "site": "https://linktr.ee/mhelisanchovy",
    "job": "No current relevant vacancy verified. Specialist service/sake knowledge is the useful career angle; small-room volume is not a guarantee of high earnings.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N48",
    "name": "ARDO",
    "address": "243 King St E, Toronto",
    "cluster": "King West / Downtown",
    "tier": "STRONG",
    "why": "Sicilian cooking, polished neighbourhood dining and private events; a good fit for the Italian restaurants you liked.",
    "transit": "243 King St E; King, approximately 12–15 minutes. Saturday 5–10:30pm.",
    "hours": "Saturday 5–10:30pm.",
    "site": "https://www.ardorestaurant.com/",
    "job": "No current relevant vacancy verified. Server, bar and event-service introduction rather than an advertised management role.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N49",
    "name": "Shoushin",
    "address": "3328 Yonge St, Toronto",
    "cluster": "North / Midtown",
    "tier": "STRONG",
    "why": "A 12-seat Edomae counter with exacting hospitality and sake/wine service; a real technical career stretch.",
    "transit": "3328 Yonge St; Lawrence, approximately 7–10 minutes. Saturday 5:30–10pm. Today: University-side Line 1 to Cedarvale, Line 5 to Eglinton, then Line 1 to Lawrence.",
    "hours": "Saturday 5:30–10pm.",
    "site": "https://www.shoushin.ca/",
    "job": "Official résumé intake exists. An Indeed experienced-server lead asks for three years of fine-dining service and Smart Serve, but its final application was not verified. Do not assume eligibility.",
    "roles": "Experienced Server — unverified",
    "pay": "",
    "url": "https://ca.indeed.com/viewjob?jk=6f1d2ebee54ffd4f",
    "status": "signal",
    "requirements": "Three years fine dining and Smart Serve in unverified listing. Official intake: careers@shoushin.ca.",
    "extra": []
  },
  {
    "id": "N50",
    "name": "SixtyEight",
    "address": "40 King St W, Scotia Plaza, Toronto",
    "cluster": "King West / Downtown",
    "tier": "STRONG",
    "why": "Premium weddings, corporate events and galas on the 68th floor make unusually good use of your event and bar background.",
    "transit": "40 King St W, Scotia Plaza; King, approximately 2–5 minutes plus building access. Not a normal Saturday walk-in restaurant: investigate online first.",
    "hours": "Saturday walk-in restaurant: investigate online first.",
    "site": "https://www.oliverbonacini.com/event-venues/sixtyeight/",
    "job": "The exact event-bartender listing is closed, despite its body saying “current vacancy.” Monitor O&B for a fresh opening.",
    "roles": "Event Bartender — closed",
    "pay": "",
    "url": "",
    "status": "closed",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N51",
    "name": "The Wood Owl",
    "address": "1380 Danforth Ave, Toronto",
    "cluster": "East / Greenwood",
    "tier": "STRONG",
    "why": "A distinctive wine-focused dining room with seasonal cooking and warm design; fits your “cool and worth working in” exception to conventional fine dining.",
    "transit": "1380 Danforth Ave; Greenwood Line 2, approximately 3–5 minutes. Current Saturday hours need confirmation through its reservation/social page.",
    "hours": "Saturday hours need confirmation through its reservation/social page.",
    "site": "https://www.tastetoronto.com/spots/the-wood-owl",
    "job": "No current relevant vacancy verified. Service and wine knowledge are the angle. This recommendation is specifically the Wood Owl dining room.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N52",
    "name": "STOCK Bar",
    "address": "2388 Yonge St, Toronto",
    "cluster": "North / Midtown",
    "tier": "OPPORTUNISTIC",
    "why": "Terroni/Cumbrae's food, cocktails and event-capable spaces make it a useful midtown room to inspect.",
    "transit": "2388 Yonge St; Eglinton, approximately 8–12 minutes. Saturday 11:30am–10pm. Use Line 5 detour.",
    "hours": "Saturday 11:30am–10pm.",
    "site": "https://stocktc.com/",
    "job": "No current relevant vacancy verified. Possible bar, service or event lane, with leadership progression to establish in conversation.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N53",
    "name": "Eataly Yorkville",
    "address": "55 Bloor St W, Toronto",
    "cluster": "Yorkville",
    "tier": "OPPORTUNISTIC",
    "why": "Multiple full-service restaurants and education/events offer a broad hospitality environment.",
    "transit": "55 Bloor St W; Bay, approximately 5–7 minutes; or Line 2 Bloor–Yonge with an approximately 3–6-minute walk. Check the specific restaurant's service hours.",
    "hours": "Confirm Saturday service before visiting",
    "site": "https://careers.eataly.com/stores/toronto/",
    "job": "Official Toronto careers page was checked: no qualifying current restaurant server, bartender, FOH-events or management-track listing found. Earlier indexed FOH listings were stale.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N54",
    "name": "Joni, Park Hyatt",
    "address": "4 Avenue Rd, Toronto",
    "cluster": "Yorkville",
    "tier": "OPPORTUNISTIC",
    "why": "Luxury-hotel dining, wine and cocktail standards; worth inspecting while in Yorkville.",
    "transit": "4 Avenue Rd; Museum or Bay, approximately 5–8 minutes. Breakfast/lunch/dinner concept; exact Saturday service times need confirmation.",
    "hours": "Saturday service times need confirmation.",
    "site": "https://art.parkhyatttoronto.com/locations/joni-restaurant",
    "job": "A dated Hcareers server-assistant lead exists, but final employer application is unverified. It is a support-role lead, not a leadership or server offer. Weigh any title/pay step down carefully.",
    "roles": "Server Assistant — unverified",
    "pay": "",
    "url": "https://www.hcareers.com/fr/jobs/4363060-joni-server-assistant",
    "status": "signal",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N55",
    "name": "Caffino",
    "address": "1185 King St W, Toronto",
    "cluster": "Exhibition / Liberty Village",
    "tier": "OPPORTUNISTIC",
    "why": "Italian dining in an atmospheric setting with weddings and private events; useful for your coordination experience.",
    "transit": "1185 King St W; Exhibition GO, approximately 15–20 minutes. Saturday 5–10pm. ",
    "hours": "Saturday 5–10pm.",
    "site": "https://caffino.ca/contact-us/",
    "job": "No current relevant vacancy verified. Future events, service or floor-lead prospect.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N56",
    "name": "Lake Inez",
    "address": "1471 Gerrard St E, Toronto",
    "cluster": "East / Greenwood",
    "tier": "OPPORTUNISTIC",
    "why": "Creative food, beverage-led hospitality and a distinctive tasting experience; strongest as a cool-room/service-learning option.",
    "transit": "1471 Gerrard St E; Greenwood, approximately 20–25 minutes walking. Saturday 5–10:30pm; kitchen 10:15pm. A separate east-end outing is more sensible than a rushed downtown add-on.",
    "hours": "Saturday 5–10:30pm; kitchen 10:15pm.",
    "site": "https://www.lakeinezto.com/pages/reservations",
    "job": "No current relevant vacancy verified. No earnings or promotion claim established.",
    "roles": "",
    "pay": "",
    "url": "",
    "status": "scout",
    "requirements": "Confirm current openings and actual clock-out times.",
    "extra": []
  },
  {
    "id": "N57",
    "name": "Salon Private Dining · Alo Food Group",
    "address": "162 Cumberland St, Toronto",
    "cluster": "Yorkville",
    "tier": "A-GAME",
    "why": "Fine-dining event bartending combines your bar-lead, upscale service and private-event experience. Immediate-start seasonal opening with possible later group opportunities, subject to availability.",
    "transit": "Clarkson GO → Union → subway to Bay or Museum, then walk. Actual worksite is Salon in Yorkville, not Alo at 163 Spadina. Confirm event finish and return service.",
    "hours": "Private events by booking; no public walk-in recruitment hours.",
    "site": "https://www.salonbyalo.com/",
    "job": "Fresh browser check September 19: Seasonal Event Bartender ad and role-specific Apply intake active. Immediate Start. Seasonal Fall–Winter 2026; continued employment is not promised.",
    "roles": "Seasonal Event Bartender",
    "pay": "Advertised C$17.60/hour + pooled gratuities",
    "url": "https://www.86network.com/jobs/toronto/on/alo-restaurant/bartender-wjwtqq",
    "status": "active",
    "requirements": "Experienced bartenders; Smart Serve; work eligibility; three days/week availability. Events can occur any day/time. Close after guests leave; check actual release time. Confirm expected hours and seasonal end date.",
    "extra": []
  },
  {
    "id": "N58",
    "name": "Michael’s Back Door",
    "address": "1715 Lakeshore Rd W, Mississauga",
    "cluster": "Clarkson",
    "tier": "OPPORTUNISTIC",
    "why": "Established Italian dining and wine close to Clarkson; a local supplemental-income prospect rather than a full-time job replacement.",
    "transit": "Clarkson GO plus local walk; entrance at the rear via Clarkson Rd N. Confirm the exact last mile and late return if needed.",
    "hours": "Tue–Thu and Sun 5–9pm; Fri–Sat 5–10pm; Monday closed.",
    "site": "https://www.michaelsbackdoor.com/",
    "job": "Fresh September 19 check: bartender advert and Apply intake active. Advertised start October 1 and one day/week. An offer could precede the start, but this is not paid work by September 27.",
    "roles": "Bartender · part-time",
    "pay": "Advertised C$17.95/hour + tips",
    "url": "https://www.86network.com/jobs/mississauga/on/michael-s-back-door-restaurant/bartender-owghuw",
    "status": "active",
    "requirements": "Smart Serve, bar experience and evening/weekend availability. Confirm minimum shifts, tips and the October 1 start before considering it sufficient income.",
    "extra": []
  }
];
(function(root){
  'use strict';
  const data=root.FLOW_DATA;if(!data)return;
  const statuses={active:'CONFIRMED ACTIVE',standing:'GENERAL HIRING / ACCEPTING APPLICATIONS',signal:'POSSIBLE / UNCONFIRMED',closed:'STALE / HISTORICAL ONLY',scout:'NO CURRENT HIRING FOUND'};
  const labels={active:'Listed opening · checked Sept 19',standing:'Accepting interest · vacancy unconfirmed',signal:'Unconfirmed job lead',closed:'Checked posting closed · scout only',scout:'Scout · no opening verified'};
  root.RESTAURANT_INTEL=root.RESTAURANT_INTEL||{};
  root.ADDITIONAL_PROSPECTS=root.ADDITIONAL_PROSPECTS||[];
  root.PASSPORT_DISCOVERIES.forEach(r=>{
    r.statusLabel=labels[r.status];
    const sources=[['Restaurant / employer',r.site],...(r.url?[['Job / careers evidence',r.url]]:[]),...r.extra];
    const actionable=r.status!=='closed'&&r.url;
    const hiring={status:statuses[r.status],roles:r.roles?[r.roles]:[],applicationUrl:actionable||'',careersUrl:r.status==='standing'?r.url:'',requirements:r.requirements,checkedAt:'2026-09-19',caveat:r.job+' Reopen the exact posting before applying.',sources};
    const flow={id:r.id,name:r.name,address:r.address,website:r.site,approvedFit:true,brief:true,tier:r.tier,cluster:r.cluster,reason:r.why,transit:r.transit,hiring,price:{status:'FIT APPROVED',estimate:'Approved for setting / career fit',basis:'Menu-price minimum relaxed by you. Published dishes are examples, not average spend or earnings.'},hours:{official:r.hours},access:{best:'Online first, or ask for a suitable time during a quiet public service. No manager appointment verified.',likelihood:'UNKNOWN',risk:'SERVICE DEPENDENT',avoid:'Busy dinner service'},scores:{fit:16,career:r.tier==='A-GAME'?18:12,access:1,confidence:r.status==='active'?5:2},windows:[],onSiteMinutes:10,askFor:'Who handles front-of-house hiring',prep:r.why+' '+r.requirements,materials:'Résumé, accurate availability and one real bar/service/event example.',failureRisk:'Confirm hiring access and actual clock-out time before travelling.',sources:sources.map(([label,url])=>({label,url})),fit:r.why};
    data.restaurants.push(flow);
    root.ADDITIONAL_PROSPECTS.push({n:r.id,r:r.name,a:r.address,p:'Setting / career fit',d:r.why,b:r.cluster,s:r.transit,discovery:true});
    const note='My experience at Capra’s includes Bar Lead, Server and Private Event Coordinator responsibilities. '+r.why;
    root.RESTAURANT_INTEL[r.id]={brief:true,discovery:r,name:r.name,status:'QUICK BRIEF · SEPT 19',lastVerified:'2026-09-19',summary:r.why,mustKnow:[r.job,r.transit,r.requirements],hiringAngle:note,manager:{name:''},walkIn:{askFor:'The person handling front-of-house hiring',opening:'Hi, I’m Jonathan. My background includes bar leadership, serving and private-event coordination. Is there a suitable person or time to ask about front-of-house opportunities?'},sources,application:{general:'',events:'',phone:'',url:actionable||'',urlLabel:r.status==='active'?'View listed role':r.status==='standing'?'Careers / future interest':'Check unconfirmed lead',urlCaveat:r.job,note},nextSteps:{applyUrl:actionable||'',contactEmail:'',contactName:''}};
  });
  const casa=data.restaurants.find(r=>r.id===16);if(casa){casa.approvedFit=true;casa.tier='OPPORTUNISTIC';casa.reason='Distinctive dining prospect; current menu prices are optional research, not an exclusion. Confirm hiring and a suitable visit time first.';casa.windows=[];}
  data.clusters=[...new Set(['Clarkson GO',...data.clusters,...root.PASSPORT_DISCOVERIES.map(r=>r.cluster)])];
  data.startCluster='Clarkson GO';
  data.checkedAt='September 19, 2026 · expanded quick briefs';
  data.travelCaveat='Start / return: Clarkson GO. Rail and walking first; optional Uber only within your C$30 per-leg cap. Estimated walks are not live navigation. No automatic manager visit windows are assigned to new prospects.';
  root.PASSPORT_TRAVEL={title:'From Clarkson GO',summary:'Lakeshore West to Union, then subway and walking. Keep optional Uber legs within C$30 using a live quote.',closure:'September 19–20: Line 1 is closed College–St Clair. Use the University side to St George for Line 2. For midtown/north: Cedarvale → Line 5 east to Eglinton → northern Line 1.',returnNote:'Weekend timetable: Union 00:47 → Clarkson 01:24 (Sunday morning). Recheck live departures; plan an earlier return. Your latest comfortable home time is not set.',sources:[['TTC weekend notice','https://www.ttc.ca/news/2026/September/Taking-the-TTC-this-weekend'],['Line 5 connections','https://www.ttc.ca/routes-and-schedules/5/1/10785'],['GO timetable','https://assets.metrolinx.com/image/upload/v1787946222/Documents/GO/full-schedules/FS05092025/Table01.pdf']]};
})(window);

document.addEventListener('DOMContentLoaded',function(){
 if(!document.querySelector('#content')&&!document.querySelector('#fieldCommand'))return;
 const t=window.PASSPORT_TRAVEL,box=document.createElement('details');box.className='flow-section travel-brief';
 const safe=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 box.innerHTML='<summary>Clarkson travel · plan for your visit date</summary><p>'+safe(t.summary)+'</p><p>'+safe(t.closure)+'</p><p>'+safe(t.returnNote)+'</p><p>September 19 is preparation day. Use Prep & Visits for later neighbourhood outings. Check the actual date and time for both journeys. Recheck the commute after the expected clock-out before accepting a late-shift role.</p><div class="flow-source-list">'+t.sources.map(([label,url])=>'<a target="_blank" rel="noopener noreferrer" href="'+safe(url)+'">'+safe(label)+'</a>').join('')+'</div>';
 const anchor=document.querySelector('#content')||document.querySelector('#fieldCommand');anchor.before(box);
});
