(function () {
  'use strict';
  const F=window.PassportFlow, data=window.FLOW_DATA, host=document.querySelector('#fieldCommand');
  if(!F||!data||!host)return;
  const e=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const management=window.MANAGEMENT_APPLICATION,managementHost=document.querySelector('#managementApplication');
  if(management&&managementHost){
    managementHost.innerHTML='<article class="management-card"><div><div class="eyebrow">Application-only leadership lead · '+e(management.id)+'</div><h2>'+e(management.role)+' <span>— '+e(management.employer)+'</span></h2><p class="management-meta">'+e(management.location)+' · '+e(management.employment)+'</p><p><strong>'+e(management.compensation.base)+'</strong> · '+e(management.compensation.commission)+'</p><p class="management-caveat">'+e(management.compensation.caveat)+'</p></div><div class="management-actions"><a class="button primary" target="_blank" rel="noopener noreferrer" href="'+e(management.applicationUrl)+'">Open official application ↗</a><span>This opens the employer’s site. Nothing is sent from this Passport.</span></div><div class="management-detail"><h3>Role scope</h3><ul>'+management.scope.map(s=>'<li>'+e(s)+'</li>').join('')+'</ul><h3>Before applying</h3><p>'+e(management.requirements)+'</p></div><details class="management-draft"><summary>Read the tailored cover letter</summary><button type="button" class="copy-btn" data-copy-management="letter">Copy cover letter</button><pre>'+e(management.letter)+'</pre></details><details class="management-draft"><summary>Read the short application note</summary><button type="button" class="copy-btn" data-copy-management="note">Copy short note</button><p>'+e(management.shortNote)+'</p></details><p class="management-boundary">This is M01, a separate online application lead. It is not an original restaurant stop, does not change the 42-stop progress, and has no physical-route recommendation.</p></article>';
    managementHost.querySelectorAll('[data-copy-management]').forEach(button=>button.onclick=async function(){const value=button.dataset.copyManagement==='letter'?management.letter:management.shortNote;try{await navigator.clipboard.writeText(value);button.textContent=button.dataset.copyManagement==='letter'?'Cover letter copied ✓':'Short note copied ✓';}catch(err){button.textContent='Select and copy the text below';}});
  }
  let state=F.read(F.keys.state,{anchors:(data.defaultAnchors||[]).map(a=>({...a})),deferred:{}});
  function save(){localStorage.setItem(F.keys.state,JSON.stringify(state));render();}
  const stopOptions=()=>'<option value="">Choose a restaurant</option>'+data.restaurants.map(r=>'<option value="'+e(r.id)+'">'+e(r.id+'. '+r.name)+'</option>').join('');
  host.innerHTML='<div class="eyebrow">Your next move</div><h2>Saturday field plan</h2><p>Hiring first. A few prepared conversations, with space to act on what you learn.</p><details class="flow-section flow-location"><summary>Time and location</summary><div class="flow-controls"><label>Planning date<input id="flowDate" type="date" value="'+data.date+'"></label><label>Time in Toronto<input id="flowTime" type="time"></label><button id="flowNow" type="button">Use current time</button><label>Current area<select id="flowCluster">'+data.clusters.map(c=>'<option>'+e(c)+'</option>').join('')+'</select></label><label>Last stop<select id="flowLocation">'+stopOptions()+'</select></label></div></details><p id="flowClockNote" class="flow-note"></p><div id="flowMoves" aria-live="polite"></div><details class="flow-section"><summary>Appointments, work blocks and departure</summary><p>Agreed appointments and fixed commitments protect their time in the route. Add the location or allow extra travel yourself. Saved plan assumptions are labelled and editable. These stay on this device.</p><form id="anchorForm" class="flow-controls"><label>Restaurant, if relevant<select id="anchorStop">'+stopOptions()+'</select></label><label>Type<select id="anchorType"><option value="interview">Interview</option><option value="return time">Requested return time</option><option value="work block">Work / rest block</option><option value="departure">Departure deadline</option></select></label><label>Label<input id="anchorTitle" maxlength="100" placeholder="For example, Claude work or Union Station"></label><label>Date<input id="anchorDate" type="date" value="'+data.date+'" required></label><label>Time<input id="anchorTime" type="time" required></label><label>Duration, minutes<input id="anchorDuration" type="number" value="30" min="5" max="360" required></label><label>Extra travel, minutes<input id="anchorTravel" type="number" value="0" min="0" max="180" required></label><button>Save commitment</button></form><div id="flowAnchors"></div></details><details class="flow-section"><summary>Recommended baseline and breaks</summary><div id="flowBaseline"></div></details><details class="flow-section"><summary>Master priority queue · all 42 and additional prospects</summary><p>The queue is separate from the original numbering. Access windows are planning judgments, not appointments.</p><div id="flowQueue"></div></details><details class="flow-section"><summary>Skip, defer and research gaps</summary><div id="flowDeferred"></div></details><p class="flow-note">Research checked '+e(data.checkedAt)+'. '+e(data.travelCaveat)+'</p>';
  const hireLink=document.querySelector('#openHireabilityDay');if(hireLink)hireLink.href=F.link('hireability.html');
  const dateEl=host.querySelector('#flowDate'),timeEl=host.querySelector('#flowTime'),clusterEl=host.querySelector('#flowCluster'),locationEl=host.querySelector('#flowLocation');
  clusterEl.value=state.cluster||data.startCluster;locationEl.value=state.currentStop||'';
  let editingAnchorId='';let manual=!!(state.preview&&state.preview.date&&state.preview.time);const now=F.torontoNow();dateEl.value=manual?state.preview.date:now.date;timeEl.value=manual?state.preview.time:now.time;
  dateEl.onchange=timeEl.onchange=()=>{manual=true;state.preview={date:dateEl.value,time:timeEl.value};save();};
  clusterEl.onchange=()=>{state.cluster=clusterEl.value;save();};
  locationEl.onchange=()=>{state.currentStop=locationEl.value;const r=data.restaurants.find(r=>String(r.id)===locationEl.value);if(r){state.cluster=r.cluster;clusterEl.value=r.cluster;}save();};
  host.querySelector('#flowNow').onclick=()=>{manual=false;delete state.preview;const n=F.torontoNow();dateEl.value=n.date;timeEl.value=n.time;save();};
  host.querySelector('#anchorForm').onsubmit=ev=>{ev.preventDefault();const id=host.querySelector('#anchorStop').value,r=data.restaurants.find(r=>String(r.id)===id);const type=host.querySelector('#anchorType').value;if(!r&&['interview','return time'].includes(type)){host.querySelector('#anchorStop').focus();return;}state.anchors=state.anchors||[];if(editingAnchorId){state.anchors=state.anchors.filter(a=>a.id!==editingAnchorId);editingAnchorId='';}state.anchors.push({id:Date.now().toString(36),stop:id,title:host.querySelector('#anchorTitle').value.trim()||(r?r.name:type),date:host.querySelector('#anchorDate').value,time:host.querySelector('#anchorTime').value,type,duration:Number(host.querySelector('#anchorDuration').value),travelMinutes:Number(host.querySelector('#anchorTravel').value),done:false});save();};
  function actions(r,showDirections=true){return '<div class="flow-actions"><a href="'+e(F.link('restaurant.html',{stop:r.id}))+'">Prepare</a>'+(showDirections?'<a target="_blank" rel="noopener noreferrer" href="'+e(F.maps(r))+'">Directions</a>':'')+(r.hiring.applicationUrl?'<a target="_blank" rel="noopener noreferrer" href="'+e(r.hiring.applicationUrl)+'">Application route</a>':'')+'<a href="'+e(F.link('nextsteps.html',{stop:r.id}))+'">Next steps</a><button data-defer="'+e(r.id)+'">Defer today</button></div>';}
  function brief(r){return F.badges(r)+'<p>'+e(r.reason)+'</p><p><strong>Ask for:</strong> '+e(r.askFor)+'</p><details class="flow-prep"><summary>A-game preparation</summary><p><strong>Know before entering:</strong> '+e(r.prep)+'</p><p><strong>Bring:</strong> '+e(r.materials||'Resume, accurate availability, and one relevant example from Capra’s.')+'</p><p><strong>Keep it brief:</strong> '+e(r.failureRisk||'If the room is under pressure, ask for a better time and leave promptly.')+'</p></details>';}
  function render(){
    const outcomes=F.read(F.keys.outcomes,{}),steps=F.read(F.keys.steps,{}),p=F.plan(data.restaurants,{state,outcomes,steps,date:dateEl.value,time:timeEl.value,cluster:clusterEl.value},data.travel);
    host.querySelector('#flowClockNote').textContent=(manual?'Previewing ':'Using live Toronto time: ')+dateEl.value+' '+timeEl.value+'. Recommendations use saved outcomes; Maps provides current navigation.';
    host.querySelector('#flowMoves').innerHTML=p.moves.map((m,i)=>{
      if(m.kind==='visit')return '<article class="flow-move '+(m.record.tier==='A-GAME'?'agame-move':'')+'"><div class="eyebrow">Move '+(i+1)+' · '+e(m.time)+'–'+e(m.end)+'</div><h3>'+e(m.record.name)+'</h3>'+brief(m.record)+'<p><strong>Why this time:</strong> '+e(m.reason)+'</p><p><strong>Travel:</strong> '+e(m.trip.label)+(m.wait?' · '+m.wait+' min available for preparation':'')+'</p><p><strong>Backup:</strong> '+e(m.record.backup||'Use the next application block; do not chase another closed dining room.')+'</p>'+actions(m.record)+'<label class="flow-outcome">After the visit<select data-outcome="'+e(m.record.id)+'"><option value="">Record what happened…</option><option value="chat">Sat down and chatted</option><option value="no-manager">Manager unavailable</option><option value="maybe">Maybe</option><option value="apply-online">Asked to apply online</option><option value="interview">Got an interview</option><option value="job">Got the job</option></select></label></article>';
      const applicationBlock=m.kind==='work'&&m.record&&!m.anchor&&/application/i.test((m.title||'')+' '+(m.reason||''));
      return '<article class="flow-move"><div class="eyebrow">Move '+(i+1)+(m.time?' · '+e(m.time)+(m.end?'–'+e(m.end):''):'')+'</div><h3>'+e(m.title+(m.record?' · '+m.record.name:''))+'</h3><p>'+e(m.reason)+'</p>'+(m.anchor?'<button data-anchor-done="'+e(m.anchor.id)+'">Mark commitment done</button>':'')+(m.record?actions(m.record,!!m.anchor):'<a href="'+e(F.link('nextsteps.html'))+'">Open next steps</a>')+(applicationBlock?'<button type="button" data-track-application="'+e(m.record.id)+'">Track this application</button>':'')+'</article>';
    }).join('');
    host.querySelector('#flowAnchors').innerHTML=p.anchors.map(a=>'<p><strong>'+e(a.time)+' · '+e(a.title)+'</strong> — '+e(a.type)+(a.assumption?' · saved-plan assumption':'')+' · '+e(a.duration||30)+' min <button data-anchor-edit="'+e(a.id)+'">Change</button> <button data-anchor-done="'+e(a.id)+'">Mark done</button></p>').join('')||'<p>No agreed times saved.</p>';
    host.querySelector('#flowBaseline').innerHTML=(data.baseline||[]).map(b=>'<div class="baseline-row"><strong>'+e(b.time)+'</strong><div><h3>'+e(b.title)+'</h3><p>'+e(b.reason)+'</p>'+(b.stop?'<a href="'+e(F.link('restaurant.html',{stop:b.stop}))+'">Open preparation</a>':'')+'</div></div>').join('');
    host.querySelector('#flowQueue').innerHTML=[...data.restaurants].sort((a,b)=>F.rank(b,clusterEl.value)-F.rank(a,clusterEl.value)).map(r=>'<details class="queue-row"><summary><span>'+e(r.id)+' · '+e(r.name)+'</span><strong>'+e(!F.eligible(r)?'SKIP TODAY':r.tier)+'</strong></summary>'+brief(r)+(r.transit?'<p><strong>Rail / walk:</strong> '+e(r.transit)+'</p>':'')+'<p><strong>Saturday hours:</strong> '+e(r.hours.official)+'</p><p><strong>Window:</strong> '+e(r.access.best)+'</p><p><strong>Price:</strong> '+e(r.price.estimate||'Price not verified')+' — '+e(r.price.basis)+'</p><p><strong>Hiring caveat:</strong> '+e(r.hiring.caveat)+'</p>'+actions(r)+'<div class="flow-source-list">'+(r.sources||[]).map(s=>'<a target="_blank" rel="noopener noreferrer" href="'+e(s.url)+'">'+e(s.label)+'</a>').join('')+'</div></details>').join('');
    host.querySelector('#flowDeferred').innerHTML=p.deferred.map(r=>'<p><strong>'+e(r.name)+'</strong> — '+e(((state.deferred||{})[r.id]===dateEl.value)?'Deferred by you today':outcomes[r.id]?'Outcome saved: '+outcomes[r.id]:!F.eligible(r)?'Fit / price evidence needs review':r.closedSaturday?'Closed Saturday':r.operatingUncertain?'Operating status needs confirmation':'Outside active queue')+((state.deferred||{})[r.id]?' <button data-restore="'+e(r.id)+'">Restore</button>':'')+'</p>').join('')||'<p>No stops deferred.</p>';
    host.querySelectorAll('[data-defer]').forEach(b=>b.onclick=()=>{state.deferred=state.deferred||{};state.deferred[b.dataset.defer]=dateEl.value;save();});
    host.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{delete state.deferred[b.dataset.restore];save();});
    host.querySelectorAll('[data-anchor-edit]').forEach(b=>b.onclick=()=>{const a=state.anchors.find(a=>a.id===b.dataset.anchorEdit);if(!a)return;host.querySelector('#anchorStop').value=a.stop||'';host.querySelector('#anchorType').value=a.type;host.querySelector('#anchorTitle').value=a.title;host.querySelector('#anchorDate').value=a.date;host.querySelector('#anchorTime').value=a.time;host.querySelector('#anchorDuration').value=a.duration||30;host.querySelector('#anchorTravel').value=a.travelMinutes||0;editingAnchorId=a.id;host.querySelector('#anchorForm').closest('details').open=true;host.querySelector('#anchorTime').focus();});
    host.querySelectorAll('[data-anchor-done]').forEach(b=>b.onclick=()=>{state.anchors.find(a=>a.id===b.dataset.anchorDone).done=true;save();});
    host.querySelectorAll('[data-outcome]').forEach(s=>s.onchange=()=>{if(!s.value)return;const o=F.read(F.keys.outcomes,{}),v=F.read(F.keys.visits,{});o[s.dataset.outcome]=s.value;v[s.dataset.outcome]=1;localStorage.setItem(F.keys.outcomes,JSON.stringify(o));localStorage.setItem(F.keys.visits,JSON.stringify(v));state.currentStop=s.dataset.outcome;locationEl.value=state.currentStop;save();if(s.value==='interview'){host.querySelector('#anchorStop').value=s.dataset.outcome;host.querySelector('#anchorForm').closest('details').open=true;host.querySelector('#anchorTime').focus();}});
    host.querySelectorAll('[data-track-application]').forEach(button=>button.onclick=()=>{const id=button.dataset.trackApplication,o=F.read(F.keys.outcomes,{});o[id]='apply-online';localStorage.setItem(F.keys.outcomes,JSON.stringify(o));state.currentStop=id;locationEl.value=id;save();location.href=F.link('nextsteps.html',{stop:id});});
  }
  window.addEventListener('storage',()=>{state=F.read(F.keys.state,state);manual=!!(state.preview&&state.preview.date&&state.preview.time);if(manual){dateEl.value=state.preview.date;timeEl.value=state.preview.time;}render();});
  setInterval(()=>{if(!manual){const n=F.torontoNow();dateEl.value=n.date;timeEl.value=n.time;render();}},60000);
  render();
})();
