/* Public-hours evidence supports draft visits, not manager appointments. */
window.PASSPORT_PREP={
  key:'toronto42-prep-visits-v1', checked:'2026-09-19', defaults:['N15','N57','N12','41'],
  blocks:[
    ['truth','20–30 min','Confirm the facts together','Review your current résumé, availability, certifications and actual bar, service and private-event responsibilities. Pick a direct-fit role and an exciting stretch.'],
    ['evidence','30–45 min','Build our evidence bank','Prepare three real stories: a pressured service, a guest recovery, and an event or team-coordination challenge. Record your actions and actual outcomes; add numbers only if you can support them.'],
    ['packages','45–60 min per prospect','Tailor the résumé and letter','Lead with the experience each role needs. Write a specific reason for this restaurant, adapt the résumé bullets, and draft portal answers. Use three reusable evidence-based versions: bar leadership, upscale service and events. Tailor the opening and selected bullets to each employer; aim for four complete applications today, then the next suitable roles through Monday.'],
    ['study','15–20 min per prospect','Study the room together','Learn the service style, three menu items, two drinks or wines, the event offering and one honest reason you want to work there. Use the current menu, not memorized old prices.'],
    ['interview','20–30 min per prospect','Run a sample interview','I ask one question at a time. You answer, we tighten the evidence and delivery, then retry. Practise the introduction, service judgment, leadership and your questions for them.'],
    ['apply','30–45 min + travel planning','Review, apply, coordinate visits','Recheck the role and location, proofread the exact files and answers, then submit the reviewed package through the best current portal. Save confirmation. Choose a later neighbourhood block and confirm travel for that date.']
  ],
  angles:{
    N15:{label:'First wave · events',role:'Event Coordinator',pitch:'Lead with Capra’s event bookings from inquiry to execution, minimum-spend/package discussions and on-site service. Banquet Server is a separate strong service alternative.',proof:'Explain one event brief, proposal/package discussion, changing detail and final delivery. Describe billing and Office-tool experience accurately; these are required here.',study:'Private-club hospitality, catering formats, event orders and member discretion.',question:'Walk me through an event from the first inquiry to the final bill. Which parts did you personally own?',portal:'Apply to Coordinator if you can evidence its administrative work; otherwise use the Banquet Server alternative. Choose a primary role.'},
    N57:{label:'First wave · bar + events',role:'Seasonal Event Bartender',pitch:'Connect Noble Bistro, Sotto Sotto and your two Bar Lead roles with private-event service. Explain your interest in learning Alo Food Group standards at Salon.',proof:'Describe your preparation, batching or station organisation, timing and service recovery at a real event. Claim only techniques you actually used.',study:'Salon’s private-event format, current event menus and refined beverage service. The worksite is 162 Cumberland, not Alo on Spadina.',question:'How would you prepare and run the bar for an event when most guests arrive together?',portal:'The 86network employer header says Alo, but the body is Salon seasonal event bartending. Confirm season length, shifts and release time.'},
    N12:{label:'First wave · local full-time',role:'Bartender',pitch:'Lead with restaurant bartending, Italian dining familiarity, drinks consistency and team coordination. Server is an alternative if that best matches the current staffing need.',proof:'Use a real busy-service example from Sotto Sotto or your Bar Lead roles, with ticket priorities, guest care and stock organisation.',study:'Mercatto Centrale’s current menu and drinks, its Port Credit room and dietary/service standards.',question:'How would you balance a full bar with service tickets while keeping drinks and guest care consistent?',portal:'Use the exact Port Credit bartender form; the separate Server form is also linked. Do not confuse this location with other Mercatto venues.'},
    '41':{label:'First wave · upscale Italian',role:'Server',pitch:'Foreground Sotto Sotto upscale Italian service, wine/spirits knowledge and Capra’s current event/table service.',proof:'Describe accurate menu explanation, pacing, a wine recommendation and guest recovery from an actual service.',study:'Buca Yorkville’s current menu, Italian service style and wine offering. Be specific about this location.',question:'How do you guide a table through an unfamiliar Italian menu and coordinate the pace of the meal?',portal:'Use the exact Buca Yorkville server vacancy. Immediate Start is an advert signal, not a promised decision date.'},

    N10:{label:'Direct fit + leadership',role:'Bartender / Team Leader',pitch:'Lead with Bar Lead and serving experience. The bartender/team-leader route is closer to your known background than the separate private-dining manager role.',proof:'Describe a real shift where you coordinated people or priorities. Separate what you led from what a manager approved.',study:'Steakhouse service, classic cocktails, wine recommendations and the handoff between bar and floor.',question:'A teammate falls behind while your bar is busy. What do you do first, and when do you involve the manager?',portal:'Use the specific BambooHR bartender/team-leader posting. Do not accidentally apply to the separate private-dining manager vacancy.'},
    N11:{label:'Events career step',role:'On-Site Event Coordinator',pitch:'Make Private Event Coordinator and Private Event Server experience the headline. This is an events-led career step, subject to the full requirements.',proof:'Walk through one real event: guest brief, your responsibilities, a change during service and the result. Be precise about sales, budgets and staffing you did or did not own.',study:'French brasserie positioning, private-dining formats, guest communication and event-to-service handoffs.',question:'An event host changes the timing just before guests arrive. How would you coordinate the floor and kitchen?',portal:'Use the named Ce Soir event-coordinator posting on HigherMe; confirm the employer and Oakville worksite.'},
    N30:{label:'Polished service + growth',role:'Server',pitch:'Foreground serving and event service, with bar knowledge as an advantage. Your résumé documents upscale serving and you confirm current Smart Serve. Prepare accurate service examples and check the exact schedule.',proof:'Use a real example of pacing several tables or coordinating drinks and food without losing the guest connection.',study:'French brasserie menu, wine by the glass, bar-bites service and the wider O&B operation.',question:'How do you suggest wine and additional courses without making a guest feel pressured?',portal:'Use the exact La Plume Server posting on O&B’s SmartRecruiters portal.'},
    N01:{label:'Bar fit + close to home',role:'Bartender',pitch:'Lead with Bar Lead experience and your interest in a cocktail-led room. Confirm that the advertised part-time evening schedule fits your availability.',proof:'Prepare one example of consistent drinks, a clean station and prioritizing tickets under pressure, using only duties you actually performed.',study:'Current cocktail list, dinner concept, service split and the bar’s role in guest experience.',question:'You have service tickets, two guests waiting and a drink sent back. How do you prioritize?',portal:'Use the named Habitat Social bartender posting on 86network; verify the current opening and evening requirements.'},
    N21:{label:'Hotel-service development',role:'Server · part-time',pitch:'A polished hotel-service prospect. Compare the part-time schedule and service expectations before committing to a hotel career track.',proof:'Prepare a real example of discretion, attentive service and resolving a guest concern.',study:'Library Bar’s drinks and service style; learn how the outlet fits into the Royal York.',question:'How do you read whether a guest wants a detailed recommendation or quiet, efficient service?',portal:'Use the Library Bar-specific Accor posting, then complete its mandatory AssessFirst questionnaire. Initial submission alone is incomplete.'},
    N39:{label:'Exciting career prospect',role:'Future front-of-house interest',pitch:'A deliberate fine-dining development prospect. A standing careers intake is not a confirmed vacancy.',proof:'Explain one high-standard service habit and one skill you want to develop. Do not claim fine-dining experience you have not had.',study:'The current menu, wine/service style and the group’s expectations.',question:'Why this room specifically, and what would you need to learn to succeed here?',portal:'Use the current Alo Food Group careers route for genuine future interest; identify the desired location and role.'}
  },
  sprees:[
    {id:'wellington',name:'The Well / Wellington',date:'2026-09-23',start:'14:30',omitted:['N24','N34'],days:[2,3,4],preferred:'Tuesday or Wednesday',station:'Union Station, Toronto',entry:'Clarkson → Union → approximately 20–25 minutes walking to The Well, or subway to St Andrew and walk. Verify the route and train times.',why:'Three nearby rooms without a district transfer. La Plume anchors the trip with a listed role; Lulu and Bridgette are optional scouts. Happy hour starts at 3pm at the latter two, so skip them if the room is filling.',stops:[
      {id:'N30',walk:0,window:['14:30','16:00'],hours:'Tue–Thu: bar open through the afternoon; lunch ends 2:30pm. Dinner starts 5pm.',url:'https://www.laplumebrasserie.com/contact/',note:'Exact server application first. Public bar access continues between services; management may be briefing.'},
      {id:'N24',walk:5,window:['14:15','15:30'],hours:'Tue–Wed 11:30am–10pm; Thu 11:30am–midnight. Happy hour 3–6pm.',url:'https://www.lulubar.ca/toronto',note:'Scout only: checked server ad was closed. Ask whether there is a current need; do not imply you applied to a live vacancy.'},
      {id:'N34',walk:5,window:['14:15','15:45'],hours:'Official site: Tue–Sun from 11:30am; happy hour 3–6pm. Other listings differ; recheck before leaving.',url:'https://www.bridgettebar.com/toronto',note:'Optional scout: checked bartender ad closed. Leave this stop out if happy-hour trade is already building.'}
    ],later:'Le Sélect is nearby, but confirm the chosen day’s between-service access before adding it.'},
    {id:'port-credit',name:'Port Credit',date:'2026-09-22',start:'14:00',days:[2,3,4],preferred:'Tuesday or Wednesday',station:'Port Credit GO, Mississauga',entry:'Clarkson → Port Credit GO → roughly 7–10 minutes walking to Habitat. Return from Port Credit GO. No Uber is required for this two-stop core.',why:'Two live application targets in one area. Habitat comes first before its 3pm lunch closure; Mercatto has continuous weekday hours. Visit only after applying, or when an employer suggests a time.',stops:[
      {id:'N01',walk:0,window:['14:00','14:40'],hours:'Tue 11am–3pm. Wed and Thu 11am–3pm, then dinner from 5:30pm.',url:'https://www.habitatsocial.ca/',note:'Apply to the bartender role first. A late-lunch visit may meet a different team from the evening bar; ask for the hiring contact’s preferred time.'},
      {id:'N12',walk:25,window:['14:00','16:00'],hours:'Mon–Thu 11:30am–11pm; no published afternoon closure.',url:'https://mercatto.ca/menu/dinner?location_id=3658',note:'Live full-time bar/server vacancies. The 25-minute walk allowance is an estimate; check directions. Ask for the hiring contact only if service allows.'}
    ],later:'POSTA and La Vita remain optional scouts if time and employer interest justify them; neither displaces these live roles.'},
    {id:'oakville',name:'Downtown Oakville',date:'2026-09-21',start:'14:15',days:[1,2,3,4],omitted:['N26'],preferred:'Monday · live roles first',station:'Oakville GO, Oakville',entry:'Clarkson → Oakville GO → allow about 30–35 minutes walking downtown, or local transit / a short Uber only if the entire direction, including transit, fits C$30. Plan the return last mile too.',why:'Bring Ce Soir and Tabule forward to Monday after the weekend applications. These are two live career leads, not an outing delayed until Thursday for a scout. Verace is off by default; its checked afternoon access is Thursday only.',stops:[
      {id:'N11',walk:0,window:['14:00','16:00'],hours:'Sun–Thu 11am–11pm; kitchen until 10pm.',url:'https://cesoirbrasserie.com/',note:'Event-coordinator application first. Ask for the person overseeing events; their presence during dining service is unconfirmed.'},
      {id:'N02',walk:7,window:['14:00','16:00'],hours:'Mon–Thu 11:30am–10pm.',url:'https://tabule.ca/location/tabule-oakville/',note:'FOH Service Manager prospect; confirm your supervision experience meets the role. Wednesday wine promotions can affect afternoon trade.'},
      {id:'N26',walk:6,days:[4],window:['14:00','16:00'],hours:'Thu noon–10pm; Tue and Wed 4–10pm.',url:'https://www.veracepizza.ca/reserve-now',note:'Scout, not a verified opening. Thursday adds this stop without waiting for a 4pm opening.'}
    ],later:'7 Enoteca and Centro are nearby alternatives once their hours and hiring interest are confirmed for the chosen day.'}
  ]
};
window.PASSPORT_PREP.sprees.sort((a,b)=>a.date.localeCompare(b.date));
(function(root){
  function min(t){if(!/^\d{2}:\d{2}$/.test(t||''))return NaN;const [h,m]=t.split(':').map(Number);return h<24&&m<60?h*60+m:NaN;}
  function clock(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');}
  function schedule(block,date,start,omitted=[]){
    const day=new Date(date+'T12:00:00').getDay();
    if(!/^\d{4}-\d{2}-\d{2}$/.test(date||'')||!Number.isFinite(day)||new Date(date+'T12:00:00').toISOString().slice(0,10)!==date||!Number.isFinite(min(start)))return{error:'Choose a valid date and arrival time.',stops:[]};
    if(date==='2026-09-19')return{error:'September 19 is preparation day. Pick a later visit date.',stops:[]};
    if(!block.days.includes(day))return{error:'This weekday is outside the block’s checked hours. Choose a supported day or verify a different-day plan together.',stops:[]};
    let cursor=min(start),hasStop=false,walkAllowance=0;
    const stops=block.stops.map(s=>{
      if(hasStop)walkAllowance+=s.walk;
      if(omitted.includes(s.id))return{...s,excluded:'Not included in this draft.'};
      if(s.days&&!s.days.includes(day))return{...s,excluded:'Outside the checked afternoon hours for this day. Arrange a separate visit instead.'};
      const arrival=Math.max(cursor+walkAllowance,min(s.window[0]));
      if(arrival+10>min(s.window[1]))return{...s,excluded:'Too late for this suggested introduction window. Choose an earlier start or arrange a time.'};
      cursor=arrival+20;hasStop=true;walkAllowance=0; // Up to 10 min introduction, 5 min notes, 5 min buffer.
      return{...s,arrival:clock(arrival),end:clock(arrival+10)};
    });
    return{stops,end:hasStop?clock(cursor):'',error:''};
  }
  root.PassportPrep={schedule};
})(window);
