/* User-entered progress only. No outreach or inferred employer outcomes. */
(function(root){
'use strict';
const A=root.PASSPORT_AUDIT,e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let C;
const stageOptions=[['submitted','Awaiting response'],['reply','Employer replied'],['interview','Interview arranged'],['offer','Offer received'],['rejected','Not selected'],['withdrawn','Withdrawn']];
function render(){
 const records=Object.entries(C.state.apps).filter(([id])=>C.get(id));
 const complete=records.filter(([id,a])=>A.complete({...a,assessmentRequired:id==='N21'}));
 const groups=new Set(complete.map(([id])=>A.rows.find(r=>r.id===id)?.group||C.get(id).name));
 const count=stages=>records.filter(([,a])=>stages.includes(a.stage)).length;
 const today=root.PassportFlow.torontoNow().date;
 const due=records.filter(([,a])=>a.submitted&&!['offer','rejected','withdrawn','interview'].includes(a.stage)&&a.followUpDate&&a.followUpDate<=today);
 document.querySelector('#weeklyBoard').innerHTML=(A.claudeNote?'<div class="callout claude-note"><strong>Board reordered Sept 19</strong><p>'+e(A.claudeNote)+'</p></div>':'')+'<div class="callout"><strong>Your confirmed availability</strong><p>Start immediately · flexible worthwhile shifts · Smart Serve current · Clarkson outward and back by available public transport.</p><p>'+e(A.candidate)+'</p></div><div class="week-metrics">'+[[complete.length,'Complete applications recorded'],[groups.size,'Employer groups reached'],[count(['reply','interview','offer']),'Employers responding'],[count(['interview']),'Interviews arranged'],[count(['offer']),'Offers recorded']].map(([n,l])=>'<div><strong>'+n+'</strong><span>'+l+'</span></div>').join('')+'</div><p class="small">Counts come from application workshop records, not portal monitoring; older checklist outcomes remain in Follow-ups. Responses include interviews and offers; the interview count is the current stage. An offer still needs written terms, pay, hours, start date and a workable commute checked.</p><details class="prep-card"><summary>What the deadline and priorities mean</summary><p>'+e(A.probabilityNote)+'</p><p>Success target: a suitable offer by Sunday September 27. An offer, an interview and paid work are different outcomes. “Immediate Start” is an employer label, not a decision deadline. A-game / Strong / Opportunistic describe our prioritisation, not measured selection odds or guaranteed earnings.</p><p>The focused audit rechecked the priority roles below and specific stale leads. It does not make every archived restaurant detail current. No minimum weekly income was supplied: confirm total shifts, tip allocation and realistic take-home expectations with each employer.</p></details><div class="session-grid week-cadence">'+(A.weekPlan||[
 ['Sat 19','Prepare and apply','Build bar, service and events résumé versions from the reviewed CV. Finish National Club, Salon, Mercatto and Buca packages first; submit only after reviewing each final package.'],
 ['Sun 20','Complete the next wave','Ruth’s Chris, Ce Soir, Tabule, Habitat, Henry’s and La Plume. Aim for 10–12 qualified employer applications by Monday evening, not 10–12 generic uploads. Recheck exact openings.'],
 ['Mon 21 · Tue 22','Applications plus short visits','Oakville Monday; Port Credit Tuesday. Check inbox, spam, voicemail and assessments morning and late afternoon. Respond the same day. Keep two willing references ready with their permission.'],
 ['Wed 23','Check whether the plan is working','If no interviews are arranged by Wednesday noon, review résumé clarity, role fit and missing portal steps. Add suitable reserve employers; ask hiring timelines in any conversation. This trigger is a practical rule, not a statistical threshold.'],
 ['Thu 24 · Fri 25','Prioritise interviews and decisions','Replace scouting with interviews. Follow up once after about 2–3 business days unless the advert or contact gives a different timeline; no repeated drop-ins. Ask about next steps, decision date, pay, shifts and actual release time.'],
 ['Sat 26 · Sun 27','Assess real outcomes','Compare written offers and transit feasibility. If no suitable offer arrives, use replies and interview feedback to reset the following week. Do not lower your workplace standards just to claim the deadline was met.']
 ]).map(([day,title,body])=>'<article class="session-card"><small>'+e(day)+'</small><h3>'+e(title)+'</h3><p>'+e(body)+'</p></article>').join('')+'</div><h3>The order to work through</h3><p class="small">Open a prospect to add it to your working shortlist. Existing drafts remain saved. Different roles at the same employer are alternatives, not independent chances.</p><div class="priority-list">'+A.rows.map((r,index)=>{const a=C.state.apps[r.id]||{};return (index===(A.firstWaveCount||4)?'<details class="later-priorities"><summary>Next wave, reserves and later starts · '+(A.rows.length-(A.firstWaveCount||4))+' prospects</summary>':'')+'<article class="priority-row"><div><span class="tag">'+e(r.wave)+(r.urgency==='immediate'?' · immediate-start advert':'')+'</span><h3>'+e(r.name)+'</h3><p>'+e(r.role)+'</p><p>'+e(r.why)+'</p><p class="small">'+e(r.gate)+'</p></div><div><p><strong>'+e(A.stageLabel({...a,assessmentRequired:r.id==='N21'}))+'</strong></p><button data-week-open="'+r.id+'">Prepare / update</button></div></article>';}).join('')+'</details></div><h3>Follow-through due</h3><p>'+ (due.length?due.map(([id,a])=>'<a href="day.html?stop='+encodeURIComponent(id)+'#workshop">'+e(C.get(id).name)+' · '+e(a.followUpDate)+'</a>').join('<br>'):'No dated follow-ups due in your records. Add the submission and next-action dates after applying.')+'</p>';
 document.querySelectorAll('[data-week-open]').forEach(b=>b.onclick=()=>C.open(b.dataset.weekOpen));
}
function mountRecord(host,id,s){
 const box=document.createElement('section');box.className='application-progress';
 box.innerHTML='<h3>Track the employer’s response</h3><p class="small">Record actual events here. Opening a job or checking preparation boxes never creates a submission, reply or offer.</p><div class="editor-grid"><div><label>Submission date<input type="date" data-progress="submittedDate" value="'+e(s.submittedDate||'')+'"></label><label>Employer response<select data-progress="stage">'+stageOptions.map(([v,l])=>'<option value="'+v+'" '+((s.stage||'submitted')===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label><label>Follow-up / next-action date<input type="date" data-progress="followUpDate" value="'+e(s.followUpDate||'')+'"></label></div><div><label>Confirmed interview date and time · Toronto<input type="datetime-local" data-progress="interviewAt" value="'+e(s.interviewAt||'')+'"></label><label>Interview location, contact or offer terms<textarea data-progress="outcomeNotes" placeholder="Record only what the employer said. Include location, duration and travel buffer, or offer pay, hours and start date.">'+e(s.outcomeNotes||'')+'</textarea></label>'+(id==='N21'?'<div class="notice"><strong>Mandatory AssessFirst assessment</strong><p>Follow the questionnaire instructions sent after your application. Initial submission is not counted as complete here until you record this step.</p><label><input type="checkbox" data-assessment '+(s.assessmentDone?'checked':'')+'>I completed the required assessment.</label></div>':'')+'</div></div><p data-next-action></p><p class="small">Interview dates flag same-day visit drafts for manual replanning. The website does not calculate appointment travel or send reminders.</p>';
 host.querySelector('.editor').append(box);
 const update=()=>{C.save();render();box.querySelector('[data-next-action]').textContent='Next: '+A.nextAction(s);C.refreshRoutes();};
 box.querySelectorAll('[data-progress]').forEach(el=>el.onchange=()=>{s[el.dataset.progress]=el.value;update();});
 box.querySelector('[data-assessment]')?.addEventListener('change',ev=>{s.assessmentDone=ev.target.checked;update();});
 box.querySelector('[data-next-action]').textContent='Next: '+A.nextAction(s);
}
root.PassportWeek={init(context){C=context;render();},render,mountRecord};
})(window);
