import {HomeBookContext as Context} from './HomeBookContext.tsx';
export {HomeBookButton,useHomeBook} from './HomeBookContext.tsx';
import {useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import {createPortal} from 'react-dom';
import type {Household} from '../core/types.ts';
import type {DateKey} from '../core/calendar.ts';
import type {KitchenCommand} from '../kitchenCommand.ts';
import {commitHome} from './command.ts';
import {commitPersonalLife} from '../hearthside/personalLifeCommands.ts';
import {useAppearance} from '../theme/ThemeProvider.tsx';
import {useDesignClient} from '../hearthside/DesignProvider.tsx';
import {snapshotKittyDesignRevision} from '../hearthside/design.ts';
import {KittyFlat} from '../kitty/studio/flat.tsx';
import type {HomeDisplayContent} from './displays.ts';
import {BLUEPRINTS,FURNITURE,FINISHES,ROOFS,ARRANGEMENTS,blueprint,furnishing,type Tool} from './catalogue.ts';
import {decodeHome,clone,roomRect,worldObject,visibleObject,layoutIssues,snapRoom,snapObject,allowedFamilies,exportBlueprint,type HomeState,type HomeLayout,type HomeRoom,type HomeObject} from './model.ts';
import {grantHomeMilestones,homeProgress} from './progression.ts';
import './home-book.css';
export function HomeBookProvider({household,memberId,today,run,onOpen,onVisit,children}:{household:Household;memberId:string;today:DateKey;run:KitchenCommand;onOpen:(target:string,object?:string)=>void;onVisit:()=>void;children:ReactNode}){
 const [visitRequested,setVisitRequested]=useState(false),[pendingVisit,setPendingVisit]=useState(false);
 const [open,setOpen]=useState(false),client=useDesignClient(),[displays,setDisplays]=useState<HomeDisplayContent[]>([]),layout=household.personalLife?.ownerMemberId===memberId?household.personalLife.home?.layout??null:null;
 useEffect(()=>{let cancelled=false;setDisplays([]);if(!client||!layout)return;const refs=layout.objects.flatMap(o=>o.display?[o.display]:[]);
  void Promise.all(refs.map(async (d:NonNullable<HomeObject['display']>):Promise<HomeDisplayContent|null>=>{if(d.kind==='memory'){const m=household.hearthside?.memories.find(m=>m.id===d.id&&m.revision===d.revision&&!m.withdrawn&&household.members.filter(m=>m.active).every(a=>m.approvals.some(p=>p.memberId===a.id&&p.revision===m.revision))&&(!m.experienceId||household.hearthside?.experiences.some(e=>e.id===m.experienceId&&e.state==='lived')));const pm=household.personalLife?.ownerMemberId===memberId?household.personalLife.memories.find(m=>m.id===d.id&&m.revision===d.revision&&!m.withdrawn&&m.keptRevision===m.revision&&(!m.experienceId||household.personalLife?.experiences.some(e=>e.id===m.experienceId&&e.state==='lived'))):undefined;return m||pm?{kind:'memory',id:d.id,title:(m??pm)!.title,revision:d.revision}:null;}
   if(![...(household.hearthside?.designs??[]),...(household.personalLife?.ownerMemberId===memberId?household.personalLife.designs:[])].some(i=>i.designId===d.designId&&i.revision>=d.revision&&i.pieceIds.includes(d.id)))return null;
   try{const doc=await client.load(d.designId!,d.revision);if(!doc||doc.scope.ownerMemberId!==null&&doc.scope.ownerMemberId!==memberId||doc.scope.householdId!==household.householdId||doc.scope.environment!==household.environment)return null;const snapshot=snapshotKittyDesignRevision(doc,d.id,d.revision);return {kind:'piece',id:d.id,designId:d.designId!,piece:snapshot.piece,appearance:snapshot.appearance,revision:d.revision};}catch{return null;}
  })).then(items=>{if(!cancelled)setDisplays(items.filter((p):p is HomeDisplayContent=>p!==null));});return()=>{cancelled=true;};
 },[client,layout,household.hearthside,household.members,household.environment,household.householdId,memberId,household.personalLife]);
 const lastFocus=useRef<HTMLElement|null>(null);const close=()=>{setOpen(false);requestAnimationFrame(()=>lastFocus.current?.focus());};
 return <Context.Provider value={{open:()=>{lastFocus.current=document.activeElement as HTMLElement;setOpen(true);},editing:open,visitRequested,pendingVisit,visit:()=>{setVisitRequested(true);setPendingVisit(true);close();onVisit();},acknowledgeVisit:()=>setPendingVisit(false),plotId:household.hearthside?.homePlots?.find(c=>c.memberId===memberId)?.plotId,layout,displays}}>{children}{open&&createPortal(<HomeBook household={household} memberId={memberId} today={today} run={run} onClose={close} onVisit={()=>{setVisitRequested(true);setPendingVisit(true);close();onVisit();}} onOpen={(target,object)=>{close();onOpen(target,object);}} displays={displays}/>,document.body)}</Context.Provider>;
}
export function HomePlan({layout,floor=0,selected,onSelect,provisional=false,stage=3}:{layout:HomeLayout;floor?:number;selected?:string;onSelect?:(id:string)=>void;provisional?:boolean;stage?:number}){
 return <svg className={`home-plan ${provisional?'is-future':''}`} viewBox="-28 -18 56 37" role={onSelect?"group":"img"} aria-label={`${provisional?'Future blueprint':'Home layout'}, ${floor?'upper':'ground'} floor`}>
  <defs><pattern id="home-grid" width="2" height="2" patternUnits="userSpaceOnUse"><path d="M 2 0 L 0 0 0 2" fill="none" stroke="currentColor" strokeWidth=".035"/></pattern></defs><rect x="-26" y="-16" width="52" height="32" rx="1" fill="url(#home-grid)" stroke="currentColor" strokeWidth=".16"/><path d="M 0 11 V 16" stroke="currentColor" strokeWidth="1.6" opacity=".2"/><text x="0" y="18" textAnchor="middle" fontSize="1">Keep the approach clear · north ↑</text>
  {layout.rooms.filter(r=>!r.stored&&r.floor<=floor).map(r=>{const a=roomRect(r),finish=FINISHES.find(f=>f.id===r.finish)!;return <g key={r.id} role={onSelect&&r.floor===floor?'button':undefined} tabIndex={onSelect&&r.floor===floor?0:undefined} aria-label={`Select ${r.name}`} onClick={()=>{if(r.floor===floor)onSelect?.(r.id);}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect?.(r.id);}}} opacity={r.floor===floor?1:.2}><rect x={a.x-a.width/2} y={a.z-a.depth/2} width={a.width} height={a.depth} fill={stage===0?'#aaa598':finish.wall} stroke={selected===r.id?'#ca793b':'#414c46'} strokeWidth={selected===r.id?.35:.17} strokeDasharray={provisional?'1 .5':undefined}/>{stage>=2&&<path d={`M ${a.x-a.width/2} ${a.z} H ${a.x+a.width/2}`} stroke={finish.roof} strokeWidth=".18"/>}<text x={a.x} y={a.z+.5} fontSize="1" textAnchor="middle" fill="#263a37">{r.name}</text></g>;})}
  {stage===3&&layout.objects.filter(o=>visibleObject(o,layout)&&(!o.roomId||layout.rooms.find(r=>r.id===o.roomId)?.floor===floor)).map(o=>{const a=worldObject(o,layout),f=furnishing(o.catalogueId);return <g key={o.id} role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={`Select ${f.name}`} onClick={()=>onSelect?.(o.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect?.(o.id);}}}><rect x={a.x-a.width/2} y={a.z-a.depth/2} width={a.width} height={a.depth} rx=".1" fill={f.shape==='plant'?'#568c64':'#846b52'} stroke={selected===o.id?'#ee9b35':'#f6ecd7'} strokeWidth=".08"/><title>{f.name}{o.display?' · saved display':''}</title></g>;})}
 </svg>;
}
function HomeBook({household:h,memberId,today,run,onClose,onOpen,onVisit,displays}:{household:Household;memberId:string;today:DateKey;run:KitchenCommand;onClose:()=>void;onVisit:()=>void;onOpen:(target:string,object?:string)=>void;displays:HomeDisplayContent[]}){
 const appearance=useAppearance(),theme=appearance.preview??appearance.saved.theme,dialog=useRef<HTMLDialogElement>(null);
 const [base,setBase]=useState(()=>decodeHome(h.personalLife?.ownerMemberId===memberId?h.personalLife.home:undefined)),[draft,setDraft]=useState(()=>decodeHome(h.personalLife?.ownerMemberId===memberId?h.personalLife.home:undefined)),[past,setPast]=useState<HomeState[]>([]),[ahead,setAhead]=useState<HomeState[]>([]),[future,setFuture]=useState(false),[tool,setTool]=useState<Tool|'progress'|'journal'|'storage'>('build'),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState('home'),[floor,setFloor]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[stage,setStage]=useState(3),[note,setNote]=useState(''),[compare,setCompare]=useState<number|null>(null),[goal,setGoal]=useState('');
 const earned=useMemo(()=>grantHomeMilestones(h,memberId,draft,today,goal),[h,memberId,draft,today,goal]),families=allowedFamilies(earned),progress=homeProgress(h,memberId,draft,today,goal),layout=future?(draft.future??draft.layout):draft.layout;
 const room=layout.rooms.find(r=>r.id===selected),object=layout.objects.find(o=>o.id===selected),issues=layoutIssues(layout),changed=JSON.stringify(draft)!==JSON.stringify(base),stale=(h.personalLife?.home?.revision??0)!==base.revision;
 useEffect(()=>{const accepted=h.personalLife?.ownerMemberId===memberId?h.personalLife.home:undefined;if(!busy&&!changed&&accepted?.revision===base.revision&&JSON.stringify(accepted)!==JSON.stringify(base)){setBase(clone(accepted));setDraft(clone(accepted));}},[h.personalLife,memberId,busy,changed,base]);
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close();},[]);
 const mutate=(fn:(s:HomeState)=>void)=>{setPast(p=>[...p.slice(-49),clone(draft)]);setAhead([]);const next=clone(draft);if(future&&!next.future)next.future=clone(next.layout);fn(next);setDraft(next);setMessage('');};
 const edit=(fn:(l:HomeLayout)=>void)=>mutate(s=>fn(future?s.future!:s.layout));
 const undo=()=>{const previous=past.at(-1);if(!previous)return;setAhead(a=>[clone(draft),...a]);setDraft(previous);setPast(p=>p.slice(0,-1));};
 const redo=()=>{const next=ahead[0];if(!next)return;setPast(p=>[...p,clone(draft)]);setDraft(next);setAhead(a=>a.slice(1));};
 const chooseFuture=(value:boolean)=>{if(value&&!draft.future)mutate(s=>{s.future=clone(s.layout);});setFuture(value);setStage(3);};
 const addRoom=(id:string)=>{const b=blueprint(id);if(!families.has(b.family)&&!future){setMessage('This blueprint is locked. Switch to Future home to try it.');return;}const value=snapRoom(layout,id,crypto.randomUUID());edit(l=>l.rooms.push(value));setSelected(value.id);setFloor(value.floor);setStage(future?3:0);if(value.stored)setMessage('No clear attachment point is available. This room is in storage; move it to a valid position before restoring.');};
 const addObject=(id:string)=>{const f=furnishing(id);if(!families.has(f.family)&&!future){setMessage('Try this in Future home, or open its milestone.');return;}const target=room??layout.rooms.find(r=>r.id==='home')!,b=blueprint(target.blueprintId),value:HomeObject={id:crypto.randomUUID(),catalogueId:id,roomId:tool==='garden'?null:target.id,x:tool==='garden'?-23:-b.width/2+f.width/2+.5,z:tool==='garden'?12:-b.depth/2+f.depth/2+.5,rotation:0,stored:false,variant:'hearth'};edit(l=>l.objects.push(snapObject(l,value)));setSelected(value.id);setStage(3);};
 const patch=(value:Partial<HomeRoom&HomeObject>)=>edit(l=>{const target=l.rooms.find(r=>r.id===selected)??l.objects.find(o=>o.id===selected);if(target)Object.assign(target,value);});
 async function save(){if(issues.length||busy)return;setBusy(true);setMessage('Saving through Hearth…');try{await commitHome(run,memberId,{kind:'home.save',expectedRevision:base.revision,value:{layout:draft.layout,future:draft.future,pinned:draft.pinned,arrangements:draft.arrangements,selectedGoalId:goal||undefined}});const saved={...clone(draft),revision:base.revision+1,awards:earned.awards};setBase(saved);setDraft(saved);setPast([]);setAhead([]);setMessage('Home saved. Journey and the island now use this version.');setStage(3);}catch(e){setMessage(e instanceof Error?e.message:'The home was not saved. Your draft is here.');}finally{setBusy(false);}}
 function download(){const file=new Blob([JSON.stringify(exportBlueprint(layout),null,2)],{type:'application/json'}),url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download='hearth-home-blueprint.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function saveNote(){if(!note.trim())return;setBusy(true);const id=`renovation-${base.revision}-${crypto.randomUUID()}`;try{const result=await run(current=>commitPersonalLife(current,{version:1,id,scope:{environment:current.environment,householdId:current.householdId,memberId},operation:{kind:'note.save',expectedRevision:0,value:{version:1,id,revision:1,authorId:memberId,text:`Home renovation ${base.revision}\n${note.trim()}`,room:'common',experienceId:null,archived:false}}}));if(!result?.ok)throw Error('Your private note was not saved.');setNote('');setMessage('Private note saved.');}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 const restoreLayout=(saved:HomeLayout)=>{edit(l=>{const rooms=clone(saved.rooms),objects=clone(saved.objects);rooms.push(...l.rooms.filter(r=>!rooms.some(p=>p.id===r.id)).map(r=>({...r,stored:true})));objects.push(...l.objects.filter(o=>!objects.some(p=>p.id===o.id)).map(o=>({...o,stored:true})));l.rooms=rooms;l.objects=objects;});setCompare(null);setStage(0);};
 const openWorkspace=(target:string)=>{if(changed){setMessage('Save your home or discard the draft before opening another workspace. Your changes are still here.');return;}onOpen(target);};
 const used=(id:string)=>layout.rooms.some(r=>r.blueprintId===id&&!r.stored)||layout.objects.some(o=>o.catalogueId===id&&visibleObject(o,layout));
 const matches=(id:string,name:string,family:string)=>name.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||filter==='available'&&families.has(family as never)||filter==='locked'&&!families.has(family as never)||filter==='placed'&&used(id));
 const status=(id:string,family:string)=>!families.has(family as never)?'Locked':used(id)?'Placed':'Available to build';
 return <dialog ref={dialog} className={`home-book home-book--${theme}`} aria-labelledby="home-book-title" onCancel={e=>{e.preventDefault();if(changed){setMessage('Your draft has changes. Save it, or choose Discard draft and close.');}else onClose();}} onKeyDown={e=>{e.stopPropagation();if((e.ctrlKey||e.metaKey)&&e.key==='z'&&!['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName)){e.preventDefault();e.shiftKey?redo():undo();}}}>
  <header><div><p className="home-book__eyebrow">A HOME MADE YOURS · {future?'PENCIL AND POSSIBILITY':'THE RENOVATION BOOK'}</p><h1 id="home-book-title">{theme==='newfoundland'?'A little place by the water':theme==='taylor'?'Our home, in the margins':'Make yourself at home'}</h1><p>Your own island homestead. The original island house stays intact. Blueprints cost no money and never expire.</p></div><button type="button" onClick={()=>{if(changed)setMessage('Save your changes, or choose Discard draft and close.');else onClose();}} aria-label="Close renovation book">×</button></header>
  <div className="home-book__toolbar"><button aria-pressed={!future} onClick={()=>chooseFuture(false)}>My home</button><button aria-pressed={future} onClick={()=>chooseFuture(true)}>Future home · preview</button><button disabled={!past.length||busy} onClick={undo}>Undo</button><button disabled={!ahead.length||busy} onClick={redo}>Redo</button><button onClick={download}>Export design</button>{future&&draft.future&&<button onClick={()=>{const next=clone(draft);const plan=clone(next.future!);plan.rooms.push(...next.layout.rooms.filter(r=>!plan.rooms.some(p=>p.id===r.id)).map(r=>({...r,stored:true})));plan.objects.push(...next.layout.objects.filter(o=>!plan.objects.some(p=>p.id===o.id)).map(o=>({...o,stored:true})));mutate(s=>s.layout=plan);setFuture(false);setStage(0);setMessage('Future design brought to the building draft. Locked choices must be earned before saving the built home.');}}>Build this future design</button>}<button onClick={onVisit} disabled={changed||!h.personalLife?.home}>Visit my saved home</button><button onClick={()=>{setDraft(clone(base));setPast([]);setAhead([]);onClose();}} disabled={busy}>Discard draft and close</button><button onClick={()=>{setBase(decodeHome(h.personalLife?.ownerMemberId===memberId?h.personalLife.home:undefined));setDraft(decodeHome(h.personalLife?.ownerMemberId===memberId?h.personalLife.home:undefined));setPast([]);setAhead([]);setMessage('Loaded the current saved home.');}} disabled={busy}>Reload saved home</button></div>
  <nav aria-label="Renovation tools">{(['build','furnish','finish','garden','storage','progress','journal'] as const).map(t=><button key={t} aria-pressed={tool===t} onClick={()=>setTool(t)}>{({build:'Build',furnish:'Furnish',finish:'Finishes',garden:'Garden',storage:'Storage',progress:'Blueprints & milestones',journal:'Private journal'})[t]}</button>)}</nav>
  <div className="home-book__body"><main><div className="home-book__plan-head"><span>{future?'Unbuilt future blueprint':'Your working draft'}</span><label>Floor <select value={floor} onChange={e=>setFloor(Number(e.target.value))}><option value={0}>Ground · roof cutaway</option><option value={1}>Upper · roof cutaway</option></select></label></div>
   {future&&<p className="home-book__notice">Pencil preview. Locked choices can stay here. Saving this creates no financial goal or commitment.</p>}
   <HomePlan layout={compare===null?layout:base.history[compare]?.layout??layout} floor={floor} selected={selected} onSelect={setSelected} provisional={future} stage={stage}/>
   <label className="home-book__placed">Select a placed furnishing<select aria-label="Select a placed furnishing" value={object&&visibleObject(object,layout)?selected:''} onChange={e=>{if(!e.target.value)return;setSelected(e.target.value);const placed=layout.objects.find(o=>o.id===e.target.value);setFloor(layout.rooms.find(r=>r.id===placed?.roomId)?.floor??0);setStage(3);}}><option value="">Choose furniture or planting…</option>{layout.objects.filter(o=>visibleObject(o,layout)).map((o,i)=><option key={o.id} value={o.id}>{furnishing(o.catalogueId).name} · {layout.rooms.find(r=>r.id===o.roomId)?.name??'Garden'} · {i+1}</option>)}</select></label>
   {stage<3&&<div className="home-book__assembly" role="status"><b>{['Foundation laid','Frame and doorways','Roof and joinery','Finishing'][stage]}</b><p>This is a draft preview. Save the home after finishing.</p><button onClick={()=>setStage(s=>s+1)}>{['Raise the frame','Fit the roof','Finish the room'][stage]}</button><button onClick={()=>setStage(3)}>Finish preview now</button></div>}
   {issues.length>0&&<div role="alert" className="home-book__issues"><b>Before this can be built</b>{issues.slice(0,5).map(i=><p key={i}>{i}</p>)}</div>}
   {(room||object)&&<section className="home-book__selection"><h2>{room?.name??furnishing(object!.catalogueId).name}</h2><p>{room?'The room keeps its identity, furnishings and workspace when moved.':'Fine placement uses quarter-metre steps. Display originals stay in the Studio.'}</p><div className="home-book__fields"><label>East / west <input type="number" step={room?1:.25} min={-27} max={27} disabled={selected==='home'} value={room?.x??object?.x} onChange={e=>patch({x:Number(e.target.value)})}/></label><label>North / south <input type="number" step={room?1:.25} min={-23} max={23} disabled={selected==='home'} value={room?.z??object?.z} onChange={e=>patch({z:Number(e.target.value)})}/></label><button disabled={selected==='home'} onClick={()=>patch({rotation:(((room?.rotation??object?.rotation??0)+1)%4) as HomeRoom['rotation']})}>Rotate 90°</button><button disabled={selected==='home'} onClick={()=>patch({stored:!(room?.stored??object?.stored)})}>{room?.stored||object?.stored?'Restore':'Store with contents'}</button></div>
    {room&&<><label>Room level <select value={room.floor} disabled={room.id==='home'} onChange={e=>{patch({floor:Number(e.target.value) as 0|1});setFloor(Number(e.target.value));}}><option value={0}>Ground floor</option><option value={1}>Upper floor · needs support below</option></select></label><label>Room name <input value={room.name} maxLength={80} onChange={e=>patch({name:e.target.value})}/></label><label>Replace room, keep identity <select value={room.blueprintId} disabled={room.id==='home'} onChange={e=>{patch({blueprintId:e.target.value});setMessage('Contents kept. Any placements that no longer fit are listed above; move or store them.');}}>{BLUEPRINTS.filter(b=>b.id!=='cottage'||room.id==='home').map(b=><option key={b.id} value={b.id} disabled={!future&&!families.has(b.family)}>{b.name}</option>)}</select></label>{blueprint(room.blueprintId).workspace&&<button onClick={()=>openWorkspace(blueprint(room.blueprintId).workspace!)}>Open {room.name} workspace</button>}<button onClick={()=>mutate(s=>s.arrangements.push({id:crypto.randomUUID(),name:room.name,objects:clone(layout.objects.filter(o=>o.roomId===room.id))}))}>Keep this arrangement</button></>}
    {object&&<><label>Room <select value={object.roomId??''} onChange={e=>patch({roomId:e.target.value||null,supportId:undefined})}><option value="">Garden</option>{layout.rooms.map(r=><option value={r.id} key={r.id}>{r.name}{r.stored?' · stored':''}</option>)}</select></label><label>On a surface <select value={object.supportId??''} onChange={e=>patch({supportId:e.target.value||undefined,x:e.target.value?0:object.x,z:e.target.value?0:object.z})}><option value="">Floor</option>{layout.objects.filter(o=>o.id!==object.id&&o.roomId===object.roomId&&!o.supportId&&furnishing(o.catalogueId).surface).map(o=><option key={o.id} value={o.id}>{furnishing(o.catalogueId).name}</option>)}</select></label>{furnishing(object.catalogueId).surface&&<label>Display an original or a kept memory <select value={object.display?JSON.stringify(object.display):''} onChange={e=>patch({display:e.target.value?JSON.parse(e.target.value):undefined})}><option value="">No display</option>{[...(h.hearthside?.designs??[]),...(h.personalLife?.ownerMemberId===memberId?h.personalLife.designs:[])].flatMap(d=>d.pieceIds.map(id=><option key={d.designId+id} value={JSON.stringify({kind:'piece',id,designId:d.designId,revision:d.revision})}>Pottery · {id.slice(0,16)}</option>))}{(h.personalLife?.ownerMemberId===memberId?h.personalLife.memories:[]).filter(m=>!m.withdrawn&&m.keptRevision===m.revision&&(!m.experienceId||h.personalLife?.experiences.some(e=>e.id===m.experienceId&&e.state==='lived'))).map(m=><option key={'private-'+m.id} value={JSON.stringify({kind:'memory',id:m.id,revision:m.revision})}>{m.title} · private keepsake</option>)}{h.hearthside?.memories.filter(m=>!m.withdrawn&&h.members.filter(m=>m.active).every(a=>m.approvals.some(p=>p.memberId===a.id&&p.revision===m.revision))&&(!m.experienceId||h.hearthside?.experiences.some(e=>e.id===m.experienceId&&e.state==='lived'))).map(m=><option key={m.id} value={JSON.stringify({kind:'memory',id:m.id,revision:m.revision})}>{m.title} · remembered</option>)}</select></label>}</>}
   </section>}
  </main><aside aria-label="Home catalogue">
   {['build','furnish','garden'].includes(tool)&&<><label>Find something <input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rooms, lamps, planting…"/></label><label>Show <select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Everything</option><option value="available">Available</option><option value="locked">Locked</option><option value="placed">Already placed</option></select></label><div className="home-book__catalogue">{tool==='build'?BLUEPRINTS.filter(b=>b.id!=='cottage'&&matches(b.id,b.name,b.family)).map(b=><article key={b.id}><span className="home-book__swatch">{b.kind==='greenhouse'?'♧':b.upper?'⌑':'⌂'}</span><h3>{b.name}</h3><p>{b.description}</p><small>{b.width} × {b.depth} m · {status(b.id,b.family)}</small><button onClick={()=>addRoom(b.id)}>{future?'Sketch this room':families.has(b.family)?'Preview project':'Preview locked project'}</button><button onClick={()=>{mutate(s=>s.pinned=b.id);setTool('progress');}}>Pin for later</button></article>):FURNITURE.filter(f=>f.tool===(tool==='garden'?'garden':'furnish')&&matches(f.id,f.name,f.family)).map(f=><article key={f.id}><h3>{f.name}</h3><p>{status(f.id,f.family)}</p><button onClick={()=>addObject(f.id)}>Place {f.name.toLowerCase()}</button></article>)}</div>
    {tool==='furnish'&&<><h2>Start with an arrangement</h2>{ARRANGEMENTS.map(a=><button key={a.id} onClick={()=>{const target=room??layout.rooms.find(r=>r.id==='home')!;edit(l=>{a.items.forEach((id,i)=>{const f=furnishing(id);if(!future&&!families.has(f.family))return;l.objects.push(snapObject(l,{id:crypto.randomUUID(),catalogueId:id,roomId:target.id,x:-blueprint(target.blueprintId).width/2+2+(i%2)*4,z:-blueprint(target.blueprintId).depth/2+2+Math.floor(i/2)*3,rotation:0,stored:false,variant:'hearth'}));});});}}>{a.name}</button>)}{draft.arrangements.map(a=><button key={a.id} onClick={()=>edit(l=>{const target=room??l.rooms.find(r=>r.id==='home')!;const ids=new Map(a.objects.map(o=>[o.id,crypto.randomUUID()]));l.objects.push(...clone(a.objects).map(o=>({...o,id:ids.get(o.id)!,roomId:target.id,supportId:o.supportId?ids.get(o.supportId):undefined})));})}>Reuse {a.name}</button>)}</>}
   </>}
   {tool==='finish'&&<><h2>Materials with character</h2><p>Select a room or object, then choose a coordinated family.</p>{FINISHES.map(f=><button key={f.id} className="home-book__finish" disabled={!future&&!families.has(f.family)} onClick={()=>patch(room?{finish:f.id}:{variant:f.id})}><span style={{background:f.wall}}/><span style={{background:f.roof}}/><span style={{background:f.floor}}/>{f.name}{!families.has(f.family)?' · locked':''}</button>)}{room&&<label>Roof form <select value={room.roof} onChange={e=>patch({roof:e.target.value as HomeRoom['roof']})}>{ROOFS.map(r=><option value={r} key={r} disabled={!future&&['hip','flat'].includes(r)&&!families.has('architecture')}>{r}</option>)}</select></label>}</>}
   {tool==='storage'&&<><h2>Kept safely</h2><p>Rooms keep all their furniture. A stored shelf keeps its display references.</p>{layout.rooms.filter(r=>r.stored).map(r=><button key={r.id} onClick={()=>setSelected(r.id)}>{r.name} · select to restore</button>)}{layout.objects.filter(o=>!visibleObject(o,layout)).map(o=><button key={o.id} onClick={()=>setSelected(o.id)}>{furnishing(o.catalogueId).name} · {o.stored?'stored':'with its room or shelf'}</button>)}</>}
   {tool==='progress'&&<><h2>Possibilities, permanently yours</h2><p>Historical credit is collected together when you save. Corrections never take an earned room away.</p>{draft.pinned&&<p className="home-book__notice">Pinned: {blueprint(draft.pinned).name}</p>}<label>Optional goal to follow <select value={goal} onChange={e=>setGoal(e.target.value)}><option value="">Use the review alternative</option>{h.goals.filter(g=>g.shared||g.ownerMemberId===memberId).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>{progress.map(p=><article key={p.milestone.id}><h3>{p.milestone.name}</h3><p>{p.milestone.requirement}</p><progress max={p.required} value={p.current}/><p>{p.earned?'Permanently unlocked':p.eligible?'Ready to collect on Save':`${p.current} / ${p.required} distinct periods`}{p.earned&&!p.eligible?' · current evidence has changed':''}</p><button onClick={()=>openWorkspace(p.milestone.target)}>Open the useful workflow</button></article>)}</>}
   {tool==='journal'&&<><h2>A private renovation journal</h2><p>Compare the last twelve saved home versions. Personal notes stay in your member-only ledger.</p><select aria-label="Compare renovation" value={compare??''} onChange={e=>setCompare(e.target.value===''?null:Number(e.target.value))}><option value="">Current working home</option>{base.history.map((r,i)=><option key={r.revision} value={i}>Version {r.revision} · {r.at}</option>)}</select>{compare!==null&&<button onClick={()=>restoreLayout(base.history[compare]!.layout)}>Restore this arrangement as a draft</button>}<label>What this change meant <textarea value={note} maxLength={3900} onChange={e=>setNote(e.target.value)}/></label><button disabled={busy||!note.trim()} onClick={()=>void saveNote()}>Save private note</button>{h.personalLife?.ownerMemberId===memberId&&h.personalLife.notes.filter(n=>n.id.startsWith('renovation-')&&!n.archived).map(n=><p className="home-book__journal-note" key={n.id}>{n.text}</p>)}{displays.filter((d):d is Extract<HomeDisplayContent,{kind:'piece'}>=>d.kind==='piece').map(d=><figure key={d.designId+d.id}><KittyFlat piece={d.piece}/><figcaption>Your saved original · display instance</figcaption></figure>)}</>}
  </aside></div>
  <footer><p role="status" aria-live="polite">{message||`${future?'Future blueprint':'Draft'} · ${layout.rooms.filter(r=>!r.stored).length} spaces · no real budget changes`}</p>{stale&&<p role="alert">A newer home is saved. Your draft is preserved. Export it before reloading the current version.</p>}<button className="home-book__save" onClick={()=>void save()} disabled={busy||stale||issues.length>0||stage<3}>{busy?'Saving…':future?'Save future blueprint':'Save home & collect blueprints'}</button></footer>
 </dialog>;
}
