import {useId} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {FittingFigure} from '../wardrobe/FittingFigure.tsx';
import type {LookV1} from '../core/herculesCompanionContracts.ts';
import {DEFAULT_PORTRAIT,type PortraitSettings} from '../core/playContracts.ts';
const backgrounds={cream:'#eee3d0',rose:'#e4c7cb',harbour:'#b8cbd0'};
export function Portrait({look,settings=look.portrait??DEFAULT_PORTRAIT}:{look:LookV1;settings?:PortraitSettings}){
 const lightId=useId();
 const figure=renderToStaticMarkup(<FittingFigure look={look} pose={settings.pose} size={300}/>,{identifierPrefix:'portrait-'+look.id.replace(/[^a-z0-9]/gi,'')}).match(/<svg[\s\S]*<\/svg>/)![0].replace('width="100%"','width="300"').replace('height="100%"','height="300"');
 const h=settings.format==='square'?500:640;const scale=settings.crop==='head'?2:settings.crop==='seated'?1.4:1.2;
 return <svg className="play-portrait" xmlns="http://www.w3.org/2000/svg" width="500" height={h} viewBox={`0 0 500 ${h}`} role="img" aria-label={look.name||'Hercules portrait'}><style>{`.herc *{animation:none!important;transition:none!important}.herc-head{transform-origin:68px 66px}.herc-tail{transform-origin:140px 152px}.herc-pose-loaf .herc-legs{transform:translateY(9px) scaleY(.34);transform-origin:76px 178px}.herc-pose-perch .herc-legs{transform:translateY(7px) scaleY(.5);transform-origin:76px 178px}.herc-pose-perch .herc-head{transform:rotate(-3deg)}.herc-pose-sleep .herc-head{transform:rotate(9deg) translate(6px,8px)}.herc-pose-sleep .herc-legs{transform:translateY(10px) scaleY(.28);transform-origin:76px 178px}.herc-pose-sleep .herc-tail{transform:rotate(-16deg) translateX(-14px)}.herc-pose-stretch .herc-body{transform:scale(1.1,.84) translateX(6px)}.herc-pose-stretch .herc-head{transform:translate(-9px,5px) rotate(5deg)}.herc-pose-walk .herc-leg-front{transform:rotate(-12deg);transform-origin:76px 150px}.herc-pose-walk .herc-leg-back{transform:rotate(12deg);transform-origin:150px 150px}`.replace(/(^|})(\.herc)/g,'$1.play-portrait $2')}</style><defs><radialGradient id={lightId}><stop stopColor={settings.light==='lamplight'?'#fff0bc':'#ffffff'} stopOpacity=".8"/><stop offset="1" stopColor={backgrounds[settings.background]} stopOpacity="0"/></radialGradient></defs><rect width="500" height={h} rx="8" fill={backgrounds[settings.background]}/><ellipse cx="250" cy={h*.4} rx="330" ry="380" fill={`url(#${lightId})`}/><g transform={`translate(${250-150*scale} ${settings.crop==='head'?h*.08:h*.83-276*scale}) scale(${scale})`}><g className={`herc herc-pose-${settings.pose}`} dangerouslySetInnerHTML={{__html:figure}}/></g><rect x="14" y="14" width="472" height={h-28} rx="3" fill="none" stroke={settings.frame==='brass'?'#9f7f3f':settings.frame==='wood'?'#76523b':'#fffaf2'} strokeWidth="9"/></svg>;
}
export function portraitSvg(look:LookV1,settings=look.portrait??DEFAULT_PORTRAIT){return renderToStaticMarkup(<Portrait look={look} settings={settings}/>);}
export function portraitUrl(look:LookV1){return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(portraitSvg(look));}
export async function exportPortrait(looks:LookV1[],filename='hercules-portrait.png'){
 const width=500,height=Math.max(...looks.map(l=>l.portrait?.format==='square'?500:640));const canvas=document.createElement('canvas');canvas.width=width*looks.length;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)throw Error('Image export is unavailable.');ctx.fillStyle='#faf3e7';ctx.fillRect(0,0,canvas.width,canvas.height);
 await Promise.all(looks.map((look,i)=>new Promise<void>((resolve,reject)=>{const image=new Image();image.onload=()=>{ctx.drawImage(image,i*width,0,width,look.portrait?.format==='square'?500:640);resolve();};image.onerror=()=>reject(Error('Portrait could not be rendered.'));image.src=portraitUrl(look);})));
 const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Image export failed.')),'image/png'));const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
