import type {PlayPerformance} from './room.ts';
import {useEffect,useRef,useState} from 'react';
import type {LookV1} from '../core/herculesCompanionContracts.ts';
import type {Goal} from '../core/types.ts';
import {DEFAULT_PORTRAIT,type PlayReward} from '../core/playContracts.ts';
import {Portrait,exportPortrait,portraitUrl} from './portrait.tsx';
export function playChime(enabled:boolean,variant=0){if(!enabled)return;const audio=new AudioContext(),osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=[392,494,587,784][variant%4]!;gain.gain.setValueAtTime(.045,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.3);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.32);osc.onended=()=>{void audio.close();};}
export function Toy({id,look,looks,goals,reduced,sound,onGoal,onPerform}:{id:PlayReward;look:LookV1;looks:LookV1[];goals:Goal[];reduced:boolean;sound:boolean;onGoal:(id:string)=>void;onPerform:(id:string,cue?:PlayPerformance)=>void}){
 const [running,setRunning]=useState(false),[step,setStep]=useState(0),[shots,setShots]=useState<LookV1[]>([]),[selected,setSelected]=useState<string[]>(()=>looks.slice(0,4).map(l=>l.id)),[caption,setCaption]=useState(''),[colour,setColour]=useState('#d6ae62'),[tempo,setTempo]=useState('gentle'),[error,setError]=useState('');
 const [solution,setSolution]=useState(0),[tiles,setTiles]=useState([0,0,0]),[chosenGoals,setChosenGoals]=useState<string[]>(()=>goals.slice(0,3).map(g=>g.id));const latest=useRef(look);latest.current=look;const stepRef=useRef(0);stepRef.current=step;
 const displayed=looks.filter(l=>selected.includes(l.id));const targets=[[0,1,2],[2,0,1],[1,2,0]];const solved=tiles.every((v,i)=>v===targets[solution]![i]);
 useEffect(()=>{setRunning(false);setStep(0);setShots([]);},[id]);
 useEffect(()=>{if(reduced)setRunning(false);},[reduced]);
 useEffect(()=>{if(id==='key'&&solved)onPerform('key');},[id,solved]);
 useEffect(()=>{if(!running||reduced)return;const timer=setInterval(()=>{const n=stepRef.current,next=n+1;stepRef.current=next;setStep(next);playChime(sound,next);if(id==='camera'){onPerform('camera');const shot={...latest.current,portrait:{...(latest.current.portrait??DEFAULT_PORTRAIT),pose:(['sit','loaf','perch'] as const)[n%3]!}};setShots(old=>[...old,shot].slice(-3));if(next>=3)setRunning(false);}if(id==='theatre'&&next>=displayed.length+1)setRunning(false);},id==='camera'?1200:tempo==='gentle'?2200:1200);return()=>clearInterval(timer);},[running,reduced,id,sound,displayed.length,tempo]);

 async function download(items:LookV1[],name:string){try{setError('');await exportPortrait(items,name);}catch(e){setError(e instanceof Error?e.message:'Could not export this image.');}}
 function toggle(id:string){setSelected(old=>old.includes(id)?old.filter(v=>v!==id):old.length<4?[...old,id]:old);}
 const perform=(object:string)=>onPerform(object,{colour,tempo,portrait:portraitUrl(displayed[step%Math.max(displayed.length,1)]??look)});
 const picker=<fieldset><legend>Choose up to four shared portraits</legend>{looks.length?looks.map(l=><label key={l.id} className="play-check"><input type="checkbox" checked={selected.includes(l.id)} onChange={()=>toggle(l.id)}/>{l.name}</label>):<p>Share an outfit to give this object a performer.</p>}</fieldset>;
 return <section className={`play-toy play-toy-${id}`} data-running={running&&!reduced} style={{'--toy-colour':colour,'--toy-tempo':tempo==='gentle'?'4s':'2s'} as React.CSSProperties}>
 {id==='camera'&&<><p>Three expressions, one little sitting. Your current preview stays yours.</p><div className="play-photo-booth"><Portrait look={shots.at(-1)??look}/><span>{running?`Sitting ${Math.min(step+1,3)} of 3`:shots.length?'A fine little collection.':'Ready for your close-up.'}</span></div><button onClick={()=>{setStep(0);setShots([]);onPerform('camera');playChime(sound);if(reduced){setShots((['sit','loaf','perch'] as const).map(pose=>({...look,portrait:{...(look.portrait??DEFAULT_PORTRAIT),pose}})));}else setRunning(true);}} disabled={running}>{reduced?'Compose three stills':'Start portrait sitting'}</button><div className="play-contact-sheet">{shots.map((l,i)=><button key={i} onClick={()=>void download([l],`hercules-shot-${i+1}.png`)} aria-label={`Export shot ${i+1}`}><Portrait look={l}/></button>)}</div>{shots.length===3&&<button onClick={()=>void download(shots,'hercules-contact-sheet.png')}>Export contact sheet</button>}</>}
 {(id==='theatre'||id==='projector')&&<>{picker}<div className="play-mini-stage"><div className="play-curtain play-curtain-left"/><div className="play-curtain play-curtain-right"/>{displayed.length?<Portrait look={displayed[id==='projector'?step%displayed.length:Math.min(step,displayed.length-1)]!}/>:<p>Your gallery takes the stage.</p>}<p>{id==='theatre'&&step>=displayed.length&&displayed.length?'The household takes a bow.':displayed[step%Math.max(displayed.length,1)]?.name}</p>{id==='projector'&&<blockquote>{caption}</blockquote>}</div>{id==='projector'&&<label>Your caption<textarea value={caption} maxLength={180} onChange={e=>setCaption(e.target.value)} placeholder="A real memory, in your own words."/></label>}<label>Stage light<input type="color" value={colour} onChange={e=>setColour(e.target.value)}/></label><div className="play-actions"><button disabled={!displayed.length} onClick={()=>{setStep(0);setRunning(v=>!v);perform(id);}}>{running?'Pause':reduced?'Open storyboard':id==='theatre'?'Raise the curtain':'Start projection'}</button><button disabled={!displayed.length} onClick={()=>setStep(n=>(n+1)%Math.max(displayed.length,1))}>Next still</button></div>{reduced&&<div className="play-storyboard">{displayed.map(l=><figure key={l.id}><Portrait look={l}/><figcaption>{l.name}</figcaption></figure>)}</div>}</>}
 {id==='key'&&<><p>Turn the three brass pieces to match the engraved arrangement.</p><label>Cabinet arrangement<select value={solution} onChange={e=>{setSolution(Number(e.target.value));setTiles([0,0,0]);}}>{['Morning','Afternoon','Evening'].map((v,i)=><option value={i} key={v}>{v}</option>)}</select></label><p>Engraving: {targets[solution]!.map(i=>['Sun','Paw','Moon'][i]).join(' · ')}</p><div className="play-puzzle">{tiles.map((v,i)=><button key={i} aria-label={`Piece ${i+1}: ${['Sun','Paw','Moon'][v]}. Turn piece.`} onClick={()=>{setTiles(old=>old.map((value,n)=>n===i?(value+1)%3:value));playChime(sound,i);}}>{['☼','♧','☾'][v]}</button>)}</div><p role="status">{solved?'The drawer opens. A tiny paw has signed the velvet lining.':'The mechanism gives a promising little click.'}</p><div className="play-secret-drawer" data-open={solved}>A very important cat was here.</div><button onClick={()=>setTiles([2,2,2])}>Reset mechanism</button></>}
 {id==='orrery'&&<><p>Choose up to three shared ambitions. Every planet opens its real plan.</p><fieldset><legend>In this constellation</legend>{goals.map(g=><label className="play-check" key={g.id}><input type="checkbox" checked={chosenGoals.includes(g.id)} onChange={()=>setChosenGoals(old=>old.includes(g.id)?old.filter(v=>v!==g.id):old.length<3?[...old,g.id]:old)}/>{g.name}</label>)}</fieldset><div className="play-orrery"><span className="play-orrery-sun">✺</span>{chosenGoals.map((goalId,i)=>{const g=goals.find(g=>g.id===goalId);return g?<button key={g.id} style={{'--planet':i} as React.CSSProperties} onClick={()=>onGoal(g.id)}>{g.name}</button>:null;})}</div><button onClick={()=>{setRunning(v=>!v);perform('orrery');}}>{running?'Pause orbit':reduced?'Show still constellation':'Set in motion'}</button></>}
 {id==='lantern'&&<><p>A celebration you can revisit. Replaying it never changes your bank.</p><div className="play-lantern"><span>✺</span></div><label>Light colour<input type="color" value={colour} onChange={e=>setColour(e.target.value)}/></label><label>Tempo<select value={tempo} onChange={e=>setTempo(e.target.value)}><option value="gentle">Gentle</option><option value="bright">Bright</option></select></label><div className="play-actions"><button onClick={()=>{setRunning(v=>!v);perform('lantern');playChime(sound,3);}}>{running?'Pause celebration':reduced?'Light the still scene':'Light the room'}</button><button onClick={()=>void download([{...look,portrait:{...(look.portrait??DEFAULT_PORTRAIT),light:'lamplight'}}],'hercules-celebration.png')}>Export commemorative portrait</button></div></>}
 {error&&<p role="alert">{error}</p>}
 </section>;
}
