import {chromium} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import {writeFile,mkdir} from 'node:fs/promises';
await mkdir('.artifacts/hercules-slice-5',{recursive:true});
const out='.artifacts/hercules-slice-5',records=[],errors=[],requests=[];const browser=await chromium.launch({headless:true,channel:'chrome'});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await context.addInitScript(()=>{delete Object.getPrototypeOf(navigator).locks;});const page=await context.newPage();page.setDefaultTimeout(90000);page.on('pageerror',e=>errors.push(String(e)));page.on('request',r=>{if(/hercules-wardrobe|three|wardrobe\/scene|assets\/scene-/.test(r.url()))requests.push(r.url());});await page.route('**/*',route=>{const u=new URL(route.request().url());if(!['localhost','127.0.0.1'].includes(u.hostname))return route.abort();if(u.pathname.startsWith('/hercules/'))return route.fulfill({status:503,body:'{}'});return route.continue();});
try{
 await page.goto('http://127.0.0.1:5193');await page.getByRole('button',{name:'Open the demo kitchen table',exact:true}).click();await page.getByRole('button',{name:'I am Jonathan',exact:true}).click();await page.locator('nav.nav').waitFor({timeout:90000});const close=page.getByRole('button',{name:'Close reminders',exact:true});if(await close.isVisible())await close.click();records.push({beforeOpen3DRequests:requests.length});
 for(const view of (process.env.FINAL_FIT?['household']:['household','personal']))for(const theme of (process.env.FINAL_FIT?['classic']:['classic','taylor','newfoundland'])){
  await page.setViewportSize({width:1440,height:1000});await page.locator('.view-switch button').nth(view==='household'?0:1).click();await page.locator('nav.nav').getByRole('button',{name:'More',exact:true}).click();await page.locator(`[data-preview-theme="${theme}"]`).click();await page.getByRole('button',{name:'Use theme',exact:true}).click();await page.locator('nav.nav').getByRole('button',{name:'Home',exact:true}).click();
  const drawer=page.locator('.office-wide-drawer');if(!await drawer.getAttribute('open')){if(!await drawer.locator('button').first().isVisible())await drawer.locator('summary').click();}await drawer.getByRole('button',{name:/Hercules outfits/}).click();
  const first=view==='household'&&theme==='classic';const cdp=first?await context.newCDPSession(page):null;if(cdp){await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:50,downloadThroughput:2500000,uploadThroughput:1250000});}const started=Date.now();await page.getByRole('button',{name:'Open dressing room',exact:true}).click();await page.locator('.fitting-webgl[data-state=ready]').waitFor({timeout:120000});await page.getByRole('button',{name:'Try the collection look',exact:true}).click();if(cdp){records.push({firstPreview20Mbps50ms:Date.now()-started,...await page.locator('.fitting-webgl').evaluate(n=>({...n.dataset}))});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});await cdp.detach();}
  for(const width of (process.env.FINAL_FIT?[390,1440]:[320,390,720,1100,1440,1920])){
   await page.setViewportSize({width,height:1000});await page.locator('.hercules-fitting-room').evaluate(n=>n.scrollTop=0);
   const geometry=await page.locator('.hercules-fitting-room').evaluate(n=>({overflow:n.scrollWidth>n.clientWidth+1,roomWidth:n.clientWidth,stageHeight:n.querySelector('.fitting-stage').clientHeight,canvas:n.querySelector('canvas')?.getBoundingClientRect().toJSON()}));
   const axe=await new AxeBuilder({page}).include('.hercules-fitting-backdrop').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
   if([320,390,1440].includes(width))await page.screenshot({path:`${out}/${view}-${theme}-${width}.png`});
   records.push({view,theme,width,...geometry,violations:axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});console.log(view,theme,width,geometry.overflow,axe.violations.length);
  }
  if(view==='household'&&theme==='classic'&&!process.env.MATRIX_ONLY){
   if(!process.env.MATRIX_ONLY){for(const collection of (process.env.CAPE_ONLY?['applause']:['cozy','office','rain','applause','kitchen','sunday','legacy'])){
    await page.getByLabel('Collection',{exact:true}).selectOption(collection);
    const recommended=page.getByRole('button',{name:'Try the collection look',exact:true});if(await recommended.isVisible())await recommended.click();
    await page.waitForFunction(()=>document.querySelector('.fitting-stage-label')?.textContent==='Fitting platform');await page.waitForTimeout(150);
    await page.screenshot({path:`${out}/collection-${collection}.png`});
    if(process.env.CAPE_ONLY){await page.getByRole('button',{name:'See the back',exact:true}).click();await page.screenshot({path:`${out}/cape-back-final.png`});await page.getByRole('button',{name:'Reset view',exact:true}).click();continue;}
    const ids=await page.locator('.fitting-hangers button').evaluateAll(nodes=>nodes.map(n=>n.getAttribute('aria-label')));
    for(const label of ids){await page.getByRole('button',{name:label,exact:true}).click();const replace=page.getByRole('button',{name:'Replace and try on',exact:true});if(await replace.isVisible())await replace.click();await page.waitForFunction(()=>document.querySelector('.fitting-stage-label')?.textContent==='Fitting platform');await page.screenshot({path:`${out}/item-${label.replaceAll(/[^a-zA-Z0-9]/g,'-')}.png`});}
   }}
   await page.getByLabel('Collection',{exact:true}).selectOption('cozy');await page.getByRole('button',{name:'Try the collection look',exact:true}).click();
   await page.getByRole('button',{name:'Hercules’s poses',exact:true}).click();
   for(const label of ['A curious tilt','Ears up','Rather pleased','A small strut','Over the shoulder','Inspect the mirror','Adjust glasses','Check a sleeve','Portrait pose']){await page.getByRole('button',{name:label,exact:true}).click();await page.screenshot({path:`${out}/pose-${label.toLowerCase().replaceAll(' ','-')}.png`});}
   await page.getByRole('button',{name:'The outfit',exact:true}).click();await page.getByRole('button',{name:'See the back',exact:true}).click();await page.screenshot({path:`${out}/fit-back.png`});await page.getByRole('button',{name:'Reset view',exact:true}).click();
   await page.getByRole('button',{name:'Compare 2D look',exact:true}).click();await page.screenshot({path:`${out}/2d.png`});await page.getByRole('button',{name:'Return to 3D',exact:true}).click();await page.locator('.fitting-webgl[data-state=ready]').waitFor({timeout:120000});
  }
  await page.setViewportSize({width:390,height:1000});await page.getByRole('button',{name:'Close dressing room',exact:true}).click();records.push({view,theme,closeFocused:await page.evaluate(()=>document.activeElement?.outerHTML.slice(0,300)),closedCanvas:await page.locator('.fitting-webgl canvas').count()});
 }
}catch(e){console.log(String(e));console.log((await page.locator('body').innerText()).slice(-2500));await page.screenshot({path:`${out}/browser-failure.png`});records.push({failure:String(e)});process.exitCode=1;}
await writeFile(`${out}/${process.env.FINAL_FIT?'fit-final-report':'browser-report'}.json`,JSON.stringify({records,errors,requests},null,2));await browser.close();if(errors.length||records.some(r=>r.overflow||r.violations?.length||r.beforeOpen3DRequests>0))process.exitCode=1;
