import {chromium,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import {writeFile,mkdir} from 'node:fs/promises';
await mkdir('.artifacts/hercules-slice-5',{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),records=[],errors=[];page.on('pageerror',e=>errors.push(String(e)));page.setDefaultTimeout(60000);await page.route('**/*',r=>['localhost','127.0.0.1'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());
const button=name=>page.getByRole('button',{name,exact:true});
try{
 await page.goto('http://127.0.0.1:5193/wardrobe-proof/');await page.getByLabel('Lose next acknowledgement').check();await button('Open dressing room').click();await page.locator('.fitting-webgl[data-state=ready]').waitFor();await button('Try the collection look').click();await button('Wear this').click();await expect(page.getByText('Not confirmed yet. Your preview is kept. Reconnect and retry this same request.',{exact:true})).toBeVisible();await button('Close dressing room').click();records.push({ackLostState:JSON.parse(await page.locator('[data-private]').textContent())});await button('Open dressing room').click();await button('Retry unconfirmed request').click();await expect(page.getByText('Earlier request confirmed. Your latest account look is kept.',{exact:true})).toBeVisible();records.push({recoveredWithoutReplay:true});
 await button('Save look…').click();await page.locator('#fitting-look-name').fill('Synthetic tea appointment');await button('Save personal look').click();await expect(page.getByRole('heading',{name:'Synthetic tea appointment',exact:true})).toBeVisible();records.push({saveOperation:JSON.parse(await page.locator('[data-proof]').textContent())});
 await button('Share to household').click();await expect(page.getByRole('heading',{name:'Synthetic tea appointment',exact:true})).toHaveCount(2);records.push({shareOperation:JSON.parse(await page.locator('[data-proof]').textContent())});await page.screenshot({path:'.artifacts/hercules-slice-5/saved-and-shared.png'});
 const axe=await new AxeBuilder({page}).include('.hercules-fitting-backdrop').withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();records.push({libraryAxe:axe.violations.map(v=>v.id)});
 await button('Close dressing room').click();await page.getByLabel('Synthetic member').selectOption('MEM-002');records.push({partner:JSON.parse(await page.locator('[data-private]').textContent())});await button('Open dressing room').click();await button('Saved looks').click();await expect(page.getByRole('heading',{name:'My looks · 0/50',exact:true})).toBeVisible();await expect(button('Remove shared look')).toHaveCount(0);await button('Copy to my looks').click();await expect(page.getByRole('heading',{name:'My looks · 1/50',exact:true})).toBeVisible();await button('Close dressing room').click();
 await page.getByLabel('Synthetic member').selectOption('MEM-001');await button('Open dressing room').click();await button('Saved looks').click();await button('Remove shared look').click();await expect(page.getByRole('heading',{name:'Household gallery · 0/100',exact:true})).toBeVisible();await button('Close dressing room').click();await page.getByLabel('Synthetic member').selectOption('MEM-002');records.push({copyAfterOriginalRemoval:JSON.parse(await page.locator('[data-private]').textContent())});
 await page.getByLabel('Connected fixture').uncheck();await button('Open dressing room').click();await expect(button('Wear this')).toBeDisabled();await button('Saved looks').click();await expect(button('Save personal look')).toBeDisabled();await button('Close dressing room').click();records.push({offlineBlocked:true});
}catch(e){records.push({failure:String(e)});await page.screenshot({path:'.artifacts/hercules-slice-5/persistence-failure.png'});process.exitCode=1;}
console.log(records,errors);await writeFile('.artifacts/hercules-slice-5/persistence-report.json',JSON.stringify({records,errors},null,2));await browser.close();if(errors.length||records.some(r=>r.libraryAxe?.length))process.exitCode=1;
