import {chromium,expect} from '@playwright/test';import {writeFile,mkdir} from 'node:fs/promises';
await mkdir('.artifacts/hercules-slice-5',{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1100,height:1000},reducedMotion:'reduce'}),page=await context.newPage(),records=[];
const url='http://127.0.0.1:5193/';
page.setDefaultTimeout(60000);
const ready=async()=>{await page.locator('.fitting-webgl[data-state=ready]').waitFor({timeout:120000});await expect(page.getByRole('button',{name:'See the back',exact:true})).toBeEnabled({timeout:120000});};
async function enter(){await page.goto(url,{timeout:120000});await page.waitForFunction(()=>document.querySelector('nav.nav')||[...document.querySelectorAll('button')].some(b=>b.textContent==='Open the demo kitchen table'));const demo=page.getByRole('button',{name:'Open the demo kitchen table',exact:true});if(await demo.isVisible()){await demo.click();await page.getByRole('button',{name:'I am Jonathan',exact:true}).click();}await page.locator('nav.nav').waitFor({timeout:120000});const close=page.getByRole('button',{name:'Close reminders',exact:true});if(await close.isVisible())await close.click();await page.locator('nav.nav').getByRole('button',{name:'Home',exact:true}).click();const drawer=page.locator('.office-wide-drawer');if(!await drawer.getByRole('button',{name:/Hercules outfits/}).isVisible())await drawer.locator('summary').click();await drawer.getByRole('button',{name:/Hercules outfits/}).click();}
await page.addInitScript(()=>{delete Object.getPrototypeOf(navigator).locks;});await page.route('**/*',route=>['localhost','127.0.0.1'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort());
try{
 let reject=true;await page.route('**/assets/HerculesDressingRoom-*.js',route=>reject?(reject=false,route.abort()):route.continue());await enter();await page.getByRole('button',{name:'Open dressing room',exact:true}).click();await page.getByRole('button',{name:'Reload Hearth to retry',exact:true}).waitFor();records.push({chunkFailureContained:true});await page.getByRole('button',{name:'Reload Hearth to retry',exact:true}).click();await enter();await page.getByRole('button',{name:'Open dressing room',exact:true}).click();await ready();await page.getByRole('button',{name:'Try the collection look',exact:true}).click();records.push({chunkRetry:true});
 await page.getByRole('button',{name:'Close dressing room',exact:true}).click();await page.unroute('**/assets/HerculesDressingRoom-*.js');
 let failAsset=true;await page.route('**/hercules-cozy.v1.glb*',route=>failAsset?route.fulfill({status:503,body:'unavailable'}):route.continue());await page.getByRole('button',{name:'Open dressing room',exact:true}).click();await page.getByRole('button',{name:'Retry 3D',exact:true}).waitFor();await page.getByRole('button',{name:'Cable-knit sweater: rose',exact:true}).click();records.push({assetFailureControls:true});failAsset=false;await page.getByRole('button',{name:'Retry 3D',exact:true}).click();await ready();await page.getByRole('button',{name:'Hercules’s poses',exact:true}).click();await page.getByRole('button',{name:'Adjust glasses',exact:true}).click();await page.screenshot({path:'.artifacts/hercules-slice-5/final-raised-paw.png'});await page.getByRole('button',{name:'Breathe & blink',exact:true}).click();await page.getByRole('button',{name:'The outfit',exact:true}).click();await page.screenshot({path:'.artifacts/hercules-slice-5/final-stance.png'});records.push({assetRetry:true,roseRetained:await page.getByRole('button',{name:'Cable-knit sweater: rose',exact:true}).getAttribute('aria-pressed')});
 const frames=await page.locator('.fitting-webgl').getAttribute('data-frames');await page.waitForTimeout(350);records.push({reducedNoFrames:frames===await page.locator('.fitting-webgl').getAttribute('data-frames')});
 await page.locator('.fitting-webgl canvas').evaluate(canvas=>canvas.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await page.getByRole('button',{name:'Retry 3D',exact:true}).waitFor();records.push({lostContextCanvas:await page.locator('.fitting-webgl canvas').count()});await page.getByRole('button',{name:'Retry 3D',exact:true}).click();await ready();
 await page.getByRole('button',{name:'Compare 2D look',exact:true}).click();records.push({flatCanvas:await page.locator('.fitting-webgl canvas').count()});await page.keyboard.press('Escape');records.push({escapeClosed:await page.locator('.hercules-fitting-backdrop').count(),focus:await page.evaluate(()=>document.activeElement.textContent)});

 await page.getByRole('button',{name:'Open dressing room',exact:true}).click();await ready();
 let failCollection=true;await page.route('**/office.v1.glb*',route=>failCollection?route.fulfill({status:503,body:'unavailable'}):route.continue());
 await page.getByLabel('Collection',{exact:true}).selectOption('office');
 await page.getByRole('button',{name:'Retry collection display',exact:true}).waitFor();records.push({collectionErrorContained:true});
 failCollection=false;await page.getByRole('button',{name:'Retry collection display',exact:true}).click();await page.getByRole('button',{name:'Retry collection display',exact:true}).waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Try the collection look',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.fitting-stage-label')?.textContent==='Fitting platform');records.push({collectionRetry:true});
 await page.getByLabel('Collection',{exact:true}).selectOption('cozy');await page.getByRole('button',{name:'Try the collection look',exact:true}).click();
 await page.getByRole('button',{name:'Close dressing room',exact:true}).click();
 await page.unroute('**/hercules-cozy.v1.glb*');
 // Measure isolated uncached GLB/scene loading under the agreed desktop network emulation.
 const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:50,downloadThroughput:20_000_000/8,uploadThroughput:10_000_000/8});
 const start=Date.now();await page.getByRole('button',{name:'Open dressing room',exact:true}).click();await ready();records.push({first3DOn20Mbps50ms:Date.now()-start});await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
 const latencies=await page.evaluate(async()=>{const b=[...document.querySelectorAll('button')].filter(n=>n.getAttribute('aria-label')?.startsWith('Cable-knit sweater:'));const host=document.querySelector('.fitting-webgl'),times=[];for(let i=0;i<12;i++){const before=host.dataset.frames,t=performance.now();await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{observer.disconnect();reject(new Error('No swatch frame within 5 seconds'));},5000);const observer=new MutationObserver(()=>{if(host.dataset.frames!==before){clearTimeout(timeout);observer.disconnect();resolve();}});observer.observe(host,{attributes:true,attributeFilter:['data-frames']});b[(i+1)%4].click();});times.push(performance.now()-t);}return times;});records.push({cachedSwatchMs:latencies});
 await page.getByRole('button',{name:'Close dressing room',exact:true}).click();

}catch(e){records.push({failure:String(e)});console.log(String(e));await page.screenshot({path:'.artifacts/hercules-slice-5/recovery-failure.png'});process.exitCode=1;}
if(records.some(r=>r.reducedNoFrames===false||r.roseRetained==='false'||r.lostContextCanvas>0||r.flatCanvas>0||r.escapeClosed>0))process.exitCode=1;
console.log(records);await writeFile('.artifacts/hercules-slice-5/recovery-report.json',JSON.stringify(records,null,2));await browser.close();
