/** Synthetic browser acceptance; all requests restricted to localhost. */
import {chromium} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';import {mkdir,writeFile} from 'node:fs/promises';
const out=process.env.HEARTH_ARTIFACTS_DIR??'docs/evidence/hercules-play';await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const records=[],errors=[];const origin='http://127.0.0.1:5198';
async function check(page,label){const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);const axe=await new AxeBuilder({page}).include('.hercules-play').withTags(['wcag2a','wcag2aa']).analyze();records.push({label,overflow,violations:axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});}
try{
 for(const theme of ['classic','taylor','newfoundland']){
  const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());const page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(`${theme}: ${e}`));await page.goto(`${origin}/?theme=${theme}&toys`);await page.locator('.play-canvas[data-state=ready]').waitFor({timeout:60000});
  for(const width of [320,390,720,1100,1440,1920]){await page.setViewportSize({width,height:width<720?850:1000});await page.waitForTimeout(150);await page.screenshot({path:`${out}/${theme}-room-${width}.png`,fullPage:true});await check(page,`${theme}/room/${width}`);}
  await page.setViewportSize({width:390,height:850});await page.getByRole('button',{name:'Gallery',exact:true}).click();await check(page,`${theme}/gallery/390`);await page.screenshot({path:`${out}/${theme}-gallery-390.png`,fullPage:true});
  await page.getByRole('button',{name:'Choose a display',exact:true}).click();await page.getByLabel('Display position').selectOption('portrait-5');await page.getByLabel('Object',{exact:true}).selectOption('frame-0');await page.getByRole('button',{name:'Apply to display',exact:true}).click();await page.getByText('Saved to your household account.',{exact:false}).waitFor();await page.getByRole('button',{name:'Done curating',exact:true}).click();
  await page.getByRole('button',{name:'Dress',exact:true}).click();await page.getByRole('button',{name:'Enter private fitting',exact:true}).click();await page.locator('.fitting-webgl[data-state=ready]').waitFor({timeout:60000});await check(page,`${theme}/fitting/390`);await page.screenshot({path:`${out}/${theme}-fitting-390.png`,fullPage:true});await page.getByRole('button',{name:'Create portrait',exact:true}).click();await page.getByLabel('Portrait name',{exact:true}).fill('Browser proof look');await page.getByLabel('Caption',{exact:true}).fill('Shared only after explicit publication.');await page.getByRole('button',{name:'Save privately',exact:true}).click();await page.getByRole('button',{name:'Share saved portrait',exact:true}).waitFor();await page.waitForFunction(()=>!Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Share saved portrait')?.disabled);await page.getByRole('button',{name:'Share saved portrait',exact:true}).click();await page.getByText('Shared to your household.',{exact:false}).waitFor();await check(page,`${theme}/portrait/390`);const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export image',exact:true}).click();const download=await downloadPromise;await download.saveAs(`${out}/${theme}-export.png`);
  await page.getByRole('button',{name:'Curiosities',exact:true}).click();for(const reward of ['The Curator’s Camera','The Velvet Theatre','The Curious Key','The Household Orrery','The Celebration Lantern','The Keepsake Projector']){await page.getByRole('button',{name:new RegExp('^'+reward.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'))}).click();await check(page,`${theme}/toy/${reward}`);}
  await page.getByRole('button',{name:'Window seat',exact:true}).click();await page.getByRole('button',{name:'Ring the bell',exact:true}).click();await page.getByText('Saved to your household account.',{exact:false}).waitFor();await page.screenshot({path:`${out}/${theme}-discoveries-390.png`,fullPage:true});await context.close();console.log(`Finished ${theme}`);
 }
 const context=await browser.newContext({viewport:{width:390,height:850},reducedMotion:'reduce'});const page=await context.newPage();await page.goto(origin+'/?empty');await page.locator('.hercules-play').waitFor();await check(page,'empty');await page.getByRole('button',{name:'Illustrated view',exact:true}).click();await page.getByRole('button',{name:'Gallery',exact:true}).click();await check(page,'empty/fallback/gallery');await context.close();
} catch(e){errors.push(String(e));}finally{await writeFile(out+'/browser-report.json',JSON.stringify({records,errors,scope:'Local Chromium synthetic fixture using actual components and prepareCommand; no physical-device or hosted-authentication claim.'},null,2));console.log(JSON.stringify({cases:records.length,issues:records.filter(r=>r.overflow||r.violations.length),errors}));await browser.close();}
