import type { Household } from '../../core/types.ts';
import { decodeHearthside, identifier, object, revisionValue } from '../../hearthside/contracts.ts';

export const VILLAGE_ROOMS=['kitchen','loft','cellar','atlas','bank','library','glasshouse','studio','cottage','boathouse'] as const;
export type VillageRoom=typeof VILLAGE_ROOMS[number];
export type VillageArrangement={version:1;revision:number;rooms:VillageRoom[];layout:'gather'|'open';plant:'fern'|'flowers';light:'warm'|'daylight';displays:VillageDisplay[];previous?:VillageArrangementSnapshot};
export type VillageArrangementSnapshot=Pick<VillageArrangement,'revision'|'rooms'|'layout'|'plant'|'light'|'displays'>;
export type VillageDisplay={kind:'piece'|'memory';id:string;revision:number;designId?:string};
const choices=<T extends string>(v:unknown, rows:readonly T[]):T=>{if(typeof v!=='string'||!rows.includes(v as T))throw Error('VILLAGE_ARRANGEMENT_INVALID');return v as T;};
const display=(raw:unknown):VillageDisplay=>{const v=object(raw,['kind','id','revision','designId']);const kind=choices(v.kind,['piece','memory'] as const);if(kind==='piece'&&typeof v.designId!=='string')throw Error('VILLAGE_ARRANGEMENT_INVALID');if(kind==='memory'&&v.designId!==undefined)throw Error('VILLAGE_ARRANGEMENT_INVALID');return {kind,id:identifier(v.id),revision:revisionValue(v.revision),...(kind==='piece'?{designId:identifier(v.designId)}:{})};};
const snapshot=(raw:unknown):VillageArrangementSnapshot=>{const v=object(raw,['revision','rooms','layout','plant','light','displays']);if(!Array.isArray(v.rooms)||!Array.isArray(v.displays)||v.rooms.length<1||v.rooms.length>VILLAGE_ROOMS.length||v.displays.length>8)throw Error('VILLAGE_ARRANGEMENT_INVALID');const rooms=v.rooms.map(x=>choices(x,VILLAGE_ROOMS));if(new Set(rooms).size!==rooms.length)throw Error('VILLAGE_ARRANGEMENT_INVALID');const displays=v.displays.map(display);if(new Set(displays.map(x=>`${x.kind}:${x.designId??''}:${x.id}`)).size!==displays.length)throw Error('VILLAGE_ARRANGEMENT_INVALID');return {revision:revisionValue(v.revision),rooms,layout:choices(v.layout,['gather','open'] as const),plant:choices(v.plant,['fern','flowers'] as const),light:choices(v.light,['warm','daylight'] as const),displays};};
export function decodeVillageArrangement(raw:unknown):VillageArrangement{const v=object(raw,['version','revision','rooms','layout','plant','light','displays','previous']);if(v.version!==1)throw Error('VILLAGE_ARRANGEMENT_INVALID');const current=snapshot(v);const previous=v.previous===undefined?undefined:snapshot(v.previous);if(previous&&previous.revision>=current.revision)throw Error('VILLAGE_ARRANGEMENT_INVALID');return {version:1,...current,...(previous?{previous}:{})};}
export function villageDisplaysEligible(h:Household, rows:readonly VillageDisplay[]):boolean {const s=decodeHearthside(h.hearthside),members=h.members.filter(m=>m.active).map(m=>m.id);return rows.every(row=>row.kind==='piece'?s.designs.some(d=>d.designId===row.designId&&d.pieceIds.includes(row.id)&&d.revision>=row.revision):s.memories.some(m=>m.id===row.id&&m.revision===row.revision&&!m.withdrawn&&members.every(id=>m.approvals.some(a=>a.memberId===id&&a.revision===m.revision))));}
export function saveVillageArrangement(h:Household, current:VillageArrangement|undefined, expected:number, raw:unknown):VillageArrangement {if((current?.revision??0)!==expected)throw Error('VILLAGE_ARRANGEMENT_CHANGED');const next=snapshot(raw);if(next.revision!==expected+1||!villageDisplaysEligible(h,next.displays))throw Error('VILLAGE_ARRANGEMENT_INVALID');return {version:1,...next,previous:current?{revision:current.revision,rooms:current.rooms,layout:current.layout,plant:current.plant,light:current.light,displays:current.displays}:undefined};}
export function revertVillageArrangement(h:Household,current:VillageArrangement|undefined,expected:number):VillageArrangement {if(!current?.previous||current.revision!==expected)throw Error('VILLAGE_ARRANGEMENT_CHANGED');if(!villageDisplaysEligible(h,current.previous.displays))throw Error('VILLAGE_DISPLAY_UNAVAILABLE');const before:{revision:number;rooms:VillageRoom[];layout:'gather'|'open';plant:'fern'|'flowers';light:'warm'|'daylight';displays:VillageDisplay[]}={revision:current.revision,rooms:current.rooms,layout:current.layout,plant:current.plant,light:current.light,displays:current.displays};return {version:1,...current.previous,revision:current.revision+1,previous:before};}
