// Local actual-runtime proof. Start Vite on port 5198; no household or financial fixtures.
import {chromium} from '@playwright/test';

import fs from 'node:fs';
const output=process.env.HEARTH_ARTIFACTS_DIR??'/tmp/hearth-offshore-fleet';fs.mkdirSync(output,{recursive:true});
let browser;
(async()=>{browser=await chromium.launch({headless:true,args:['--use-angle=metal','--enable-gpu']});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto((process.env.HORIZON_FLEET_URL??'http://127.0.0.1:5198')+'/horizon-review.html?world=horizon&tier=lite&sun=13:02&date=2026-06-21');await page.waitForFunction(()=>window.__harbour?.stats().chunksLoaded?.length===14,null,{timeout:120000});
const walking=await page.evaluate(async()=>{
 const h=__harbour,L=await import('/src/harbour/horizon/movers/fleet/layout.ts'),M=await import('/src/harbour/horizon/movers/fleet/model.ts'),{HORIZON_MANIFEST}=await import('/src/harbour/horizon/world/manifest.ts');
 const f=M.createFleet({water:()=>0,ground:()=>-12,blocked:()=>false,width:2200,depth:1800});for(const v of h.fleetState().vessels)Object.assign(f.get(v.id),v);for(const d of L.FIXTURES.filter(f=>f.kind==='door'))f.doors.add(d.id);
 // Starting pose is the physical swim-ladder recovery. All later travel is ordinary input.
 h.restore({...M.toWorld(f.yacht,L.BOARDING),yaw:0,place:'court',world:'horizon:horizon-geo-1',geo:'horizon-geo-1'});
 const nodes=new Map(),columns=new Map();for(let ix=-35;ix<=35;ix++)for(let iz=-115;iz<=100;iz++)for(const floor of L.FLOORS){const x=ix/5,z=iz/5;if(!L.inside(floor,x,z))continue;const y=L.floorHeight(floor,z),p=M.toWorld(f.yacht,{x,y,z});if(f.contact(p.x,p.z,p.y,.35)||(f.surface(p.x,p.z,p.y,.48)?.y??-100)>p.y+.02)continue;const key=ix+','+iz+','+y.toFixed(4);if(nodes.has(key))continue;const n={key,ix,iz,x,y,z};nodes.set(key,n);const a=columns.get(ix+','+iz)||[];a.push(n);columns.set(ix+','+iz,a);}
 const nearest=p=>[...nodes.values()].filter(n=>Math.abs(n.y-p.y)<.2).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];
 function navigate(goal){const local=M.toLocal(f.yacht,h.body()),start=nearest(local),end=nearest(goal),q=[start],prev=new Map([[start.key,null]]);for(let i=0;i<q.length&&!prev.has(end.key);i++){const n=q[i];for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]])for(const next of columns.get((n.ix+dx)+','+(n.iz+dz))||[]){if(prev.has(next.key)||Math.abs(next.y-n.y)>.3)continue;prev.set(next.key,n.key);q.push(next);}}if(!prev.has(end.key))throw Error('No path '+JSON.stringify(goal));const path=[];for(let key=end.key;key!==null;key=prev.get(key))path.push(nodes.get(key));path.reverse();
 for(const n of path){const p=M.toWorld(f.yacht,n);let count=0;while(Math.hypot(h.body().x-p.x,h.body().z-p.z)>.035&&count++<45){for(const a of h.fleetActions())if(a.kind==='door'&&a.label.startsWith('Open '))h.fleetAction(a.id);const b=h.body(),dx=p.x-b.x,dz=p.z-b.z,angle=Math.atan2(dx,dz),d=Math.hypot(dx,dz);h.look(Math.atan2(Math.sin(angle-b.yaw),Math.cos(angle-b.yaw)),0);h.input({forward:Math.min(1,d*60/HORIZON_MANIFEST.speeds_ms.walk),strafe:0});h.simulateMotion(1/60);}if(count>=45)throw Error('Walk blocked '+JSON.stringify({node:n,body:M.toLocal(f.yacht,h.body()),actions:h.fleetActions(),block:h.stats().lastMovementBlocker}));}
 h.input({forward:0,strafe:0});return M.toLocal(f.yacht,h.body());}
 const visited=[];for(const [id,p]of Object.entries(L.ROOMS))visited.push({id,at:navigate(p)});for(const s of L.GALLEY){navigate(s.approach);if(!h.fleetAction(s.id))throw Error('Station unreachable '+s.id);visited.push({id:s.id});}for(const s of L.SEATS){navigate(s.stand);if(!h.fleetAction(s.id)||!h.fleetAction('stand'))throw Error('Seat failed '+s.id);visited.push({id:s.id});}
 navigate({x:0,y:3.85,z:-4.5});window.__fleetNav=navigate;window.__fleetModules={M,L};window.__fleetWalking=visited;return{visited,body:h.body(),nodes:nodes.size};
});console.log('WALK',JSON.stringify(walking));await page.screenshot({path:output+'/galley.png'});
const motion=await page.evaluate(()=>{const h=__harbour,{M,L}=__fleetModules;__fleetNav(L.HELM);if(!h.fleetAction('helm')||!h.fleetAction('anchor'))throw Error('Helm/anchor unavailable');h.input({forward:1,strafe:.6});h.simulateMotion(8);const v0=h.fleetState().vessels[3];if(v0.speed<3)throw Error('Yacht did not accelerate');h.fleetAction('leave-helm');const before={...h.body()},local=M.toLocal(v0,before);h.simulateMotion(1);const v1=h.fleetState().vessels[3],after=M.toLocal(v1,h.body());if(Math.hypot(local.x-after.x,local.z-after.z)>1e-5)throw Error('Deck carry wrong '+JSON.stringify({local,after}));h.input({forward:-1,strafe:0});h.simulateMotion(.5);h.input({forward:0});const walked=M.toLocal(h.fleetState().vessels[3],h.body());if(Math.hypot(walked.x-after.x,walked.z-after.z)<.3)throw Error('No independent walking');h.jump();h.simulateMotion(.2);const jumped={...h.body()};h.simulateMotion(1);const v2=h.fleetState().vessels[3],landed=M.toLocal(v2,h.body());if(Math.abs(landed.y-7.05)>.2)throw Error('Jump did not return to moving deck');for(let i=0;i<240&&!h.fleetActions().some(a=>a.id==='helm');i++){const v=h.fleetState().vessels[3],p=M.toWorld(v,L.HELM),b=h.body(),heading=Math.atan2(p.x-b.x,p.z-b.z);h.look(Math.atan2(Math.sin(heading-b.yaw),Math.cos(heading-b.yaw)),0);h.input({forward:.5,strafe:0});h.simulateMotion(1/60);}h.input({forward:0});if(!h.fleetAction('helm')||!h.fleetAction('anchor'))throw Error('Unable to walk back to helm '+JSON.stringify({walked,landed,body:h.body()}));h.fleetAction('leave-helm');h.simulateMotion(10);if(h.fleetState().vessels[3].speed!==0)throw Error('Anchor did not stop');h.savedBody();return{before,local,after,walked,jumped,landed,vessel:h.fleetState().vessels[3]};});console.log('MOTION',JSON.stringify(motion));await page.screenshot({path:output+'/helm.png'});
await page.reload();await page.waitForFunction(()=>window.__harbour?.stats().chunksLoaded?.length===14,null,{timeout:120000});const reloaded=await page.evaluate(()=>({body:__harbour.body(),fleet:__harbour.fleetState()}));console.log('RELOAD',JSON.stringify(reloaded));if(Math.hypot(reloaded.body.x-motion.vessel.x,reloaded.body.z-motion.vessel.z)>15)throw Error('Reload separated player from yacht');
fs.writeFileSync(output+'/walk-proof.json',JSON.stringify({walking,motion,reloaded,errors},null,2));if(errors.length)throw Error(errors.join('\n'));await browser.close();console.log('DONE',errors);
})().catch(async e=>{console.error(e);process.exitCode=1;await browser?.close();});
