import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import {pathToFileURL} from 'node:url';
import {build} from 'esbuild';
// node scripts/horizon/report.mjs [outputDir] [--bake <dir with world/ and terrain/>] (default: public/horizon)
const bakeAt=process.argv.indexOf('--bake'),bakeDir=bakeAt>=0?resolve(process.argv[bakeAt+1]):resolve('public/horizon');
const root=process.cwd(),output=resolve(process.argv[2]&&!process.argv[2].startsWith('--')?process.argv[2]:'/tmp/horizon-evidence'),w=JSON.parse(await readFile(resolve(bakeDir,'world/horizon-geo-1.json'),'utf8')),m=JSON.parse(await readFile('src/harbour/horizon/world/MANIFEST.json','utf8'));
for(const dir of ['probes','perf','rides'])await mkdir(resolve(output,dir),{recursive:true});
const sha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),meta={sha,revision:w.geographyRevision,bake:bakeDir,worldSha256:createHash('sha256').update(await readFile(resolve(bakeDir,'world/horizon-geo-1.json'))).digest('hex'),terrainSha256:createHash('sha256').update(await readFile(resolve(bakeDir,'terrain/horizon-geo-1.bin'))).digest('hex'),workingTreeClean:!execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim()};
const json=(path,value)=>writeFile(resolve(output,path),JSON.stringify({meta,...value},null,2)+'\n'),md=(path,rows)=>writeFile(resolve(output,path),rows.join('\n')+'\n'),round=v=>typeof v==='number'?Number(v.toFixed(3)):v;
await json('probes/horizon-crossings.json',{rawIntersections:w.rawIntersections,crossings:w.crossingProofs,allBuilt:w.crossingProofs.every(p=>p.built),allClear:w.crossingProofs.every(p=>p.clearancePass)});
await json('probes/horizon-thresholds.json',{thresholds:w.thresholds,allBuilt:w.thresholds.every(p=>p.built)});
await json('probes/horizon-views.json',{views:w.views});await json('probes/horizon-sky.json',{sky:w.sky});await json('probes/horizon-journeys.json',{journeys:w.journeyMeasurements,yearWalk:w.journey.stations.map(s=>({id:s.id,stretch:s.stretch}))});
const districts=w.districts.flatMap(d=>[d,...(d.children??[])]);
await json('perf/districts.json',{districts:districts.map(({id,triangles,solidIds,drawCalls,bounds,childOf})=>({id,childOf,triangles,sourceSolidCount:solidIds.length,logicalSourceDrawCalls:drawCalls,bounds,pass:triangles.full<=150000&&triangles.lite<=60000})),simplification:w.geometry.simplification,drawCallNote:'Definition source counts are not rendered calls; actual batched calls are in capture-performance.json.'});
await json('probes/horizon-stations-reserves.json',{stations:w.journey.stations,reserves:w.reserves,homestead:w.journey.homestead,kittyPlaza:w.journey.kittyPlaza});
await json('probes/horizon-diagnostics.json',{diagnostics:w.diagnostics,conflicts:w.diagnostics.filter(d=>d.severity==='conflict')});
const grades=w.collision.beds.map(b=>{const segments=b.points.slice(1).map((p,i)=>{const a=b.points[i],length=Math.hypot(p[0]-a[0],p[2]-a[2]),grade=length?Math.abs(p[1]-a[1])/length:0;return{from:a,to:p,lengthEu:length,gradePct:grade*100};});return{id:b.id,kind:b.kind,profile:b.profile,widthEu:b.width,maximumGradePct:Math.max(0,...segments.map(s=>s.gradePct)),limitPct:b.maxGrade*100,aboveEight:segments.filter(s=>s.gradePct>8.00001),pass:segments.every(s=>s.gradePct<=b.maxGrade*100+.001)};});
await json('probes/horizon-bed-grades.json',{beds:grades});
await md('journeys.md',['# Journey measurements','',`Source ${sha}; scale ${w.scaleFactor}. Actual solved path lengths and unchanged manifest speeds. These are geometric timings, not device rides.`,'','| Journey | Metres/eu | Seconds | Target seconds | Result |','|---|---:|---:|---|---|',...w.journeyMeasurements.map(j=>`| ${j.id} | ${round(j.lengthEu)} | ${round(j.seconds)} | ${JSON.stringify(j.targetSeconds)} | ${j.pass?'PASS':'FAIL'}${j.reason?`: ${j.reason}`:''} |`),'','No timing failure is waived by the approved 1.0 scale.']);
await md('crossings.md',['# Computed crossing register','',`Source ${sha}. Raw intersections: ${w.rawIntersections.length}; physical resolutions: ${w.crossingProofs.length}. Aliased river routes and continuous confluences retain their raw audit records.`,'','| ID / lines | x,z | Resolution | Clear / required eu | Built | Structure |','|---|---|---|---:|---|---|',...w.crossingProofs.map(p=>`| ${p.id}: ${p.a} × ${p.b} | ${p.at.map(round).join(',')} | ${p.resolution} / ${p.kind} | ${round(p.clearHeight)} / ${round(p.requiredClearance)} | ${p.built?'yes':'NO'} | ${(p.structureIds??[]).join(', ')} |`)]);
await md('conflicts.md',['# Open geometry and design conflicts','',`Source ${sha}. This list is a no-go record, not an exception granted by Jonathan. ${w.diagnostics.filter(d=>d.severity==='conflict').length} reported conflicts.`,'',...w.diagnostics.filter(d=>d.severity==='conflict').map(d=>`- **${d.id}**: ${d.message}${d.measured!==undefined?` Measured ${round(d.measured)}; required ${round(d.required)}.`:''}${d.at?` At [${d.at.map(round).join(',')}].`:''}`)]);
await md('highspan.md',['# High Span stack','',`Source ${sha}; heights in engine units.`, '',...Object.entries(m.structures.highSpan).map(([k,v])=>`- Manifest ${k}: ${JSON.stringify(v)}`),'','Actual solids:',...w.geometry.solids.filter(s=>s.sourceId?.startsWith('highSpan')).map(s=>{const ys=s.positions.filter((_,i)=>i%3===1);return`- ${s.id}: ${round(Math.min(...ys))} to ${round(Math.max(...ys))}; ${s.indices.length/3} triangles; role ${s.role}.`;}),'','Gate aperture and obstruction verdict: see probes/horizon-sky.json.']);
await json('probes/horizon-hosts.json',{hosts:w.hosts,doorToolTargets:{home:'conversation',bank:'loft-banks',library:'books',glasshouse:'planner',studio:'pottery',cottage:'wardrobe',boathouse:'wishes'}});
// ---- The review's measures, folded in (R1-73, R1-75, R1-76; auditors 2 and 5): the delivery measures what the review measured.
const entry=resolve(tmpdir(),`horizon-report-${process.pid}.mjs`);
await build({stdin:{contents:"export {decodeTerrainAsset} from './src/harbour/horizon/land/terrain/asset.ts';export {sampleTerrain} from './src/harbour/horizon/land/terrain/index.ts';export {waterHeightAt} from './src/harbour/horizon/land/water/index.ts';",resolveDir:root,loader:'ts'},outfile:entry,bundle:true,platform:'node',format:'esm',logLevel:'warning'});
const {decodeTerrainAsset,sampleTerrain,waterHeightAt}=await import(pathToFileURL(entry).href);execFileSync('rm',['-f',entry]);
const bin=await readFile(resolve(bakeDir,'terrain/horizon-geo-1.bin')),field=decodeTerrainAsset(bin.buffer.slice(bin.byteOffset,bin.byteOffset+bin.byteLength),'full'),ground=(x,z)=>sampleTerrain(field,x,z);
// Vertical column index over every baked solid (4 eu cells): column(x,z) → [{y, up, s}] sorted by height.
const S=w.geometry.solids,CELL=4,grid=new Map();
S.forEach((solid,si)=>{const P=solid.positions,I=solid.indices;for(let k=0;k<I.length;k+=3){const t=[I[k]*3,I[k+1]*3,I[k+2]*3],x0=Math.min(...t.map(i=>P[i])),x1=Math.max(...t.map(i=>P[i])),z0=Math.min(...t.map(i=>P[i+2])),z1=Math.max(...t.map(i=>P[i+2]));for(let cx=Math.floor(x0/CELL);cx<=Math.floor(x1/CELL);cx++)for(let cz=Math.floor(z0/CELL);cz<=Math.floor(z1/CELL);cz++){const key=cx*100000+cz;(grid.get(key)??grid.set(key,[]).get(key)).push([si,t[0],t[1],t[2]]);}}});
function column(x,z,filter){const out=[];for(const [si,a,b,c] of grid.get(Math.floor(x/CELL)*100000+Math.floor(z/CELL))??[]){const P=S[si].positions,ax=P[a],ay=P[a+1],az=P[a+2],bx=P[b],by=P[b+1],bz=P[b+2],cx=P[c],cy=P[c+1],cz=P[c+2],d=(bz-cz)*(ax-cx)+(cx-bx)*(az-cz);if(Math.abs(d)<1e-12)continue;const l1=((bz-cz)*(x-cx)+(cx-bx)*(z-cz))/d,l2=((cz-az)*(x-cx)+(ax-cx)*(z-cz))/d,l3=1-l1-l2;if(l1<-1e-9||l2<-1e-9||l3<-1e-9)continue;if(filter&&!filter(S[si]))continue;out.push({y:l1*ay+l2*by+l3*cy,up:(bz-az)*(cx-ax)-(bx-ax)*(cz-az)>0,s:si});}return out.sort((p,q)=>p.y-q.y);}
function walkBed(b,step,fn){const P=b.points,arc=[0];for(let i=1;i<P.length;i++)arc.push(arc[i-1]+Math.hypot(P[i][0]-P[i-1][0],P[i][2]-P[i-1][2]));let seg=1;for(let d=step/2;d<(arc.at(-1)??0);d+=step){while(seg<P.length-1&&arc[seg]<d)seg++;const a=P[seg-1],c=P[seg],len=arc[seg]-arc[seg-1]||1,t=(d-arc[seg-1])/len;fn([a[0]+(c[0]-a[0])*t,a[1]+(c[1]-a[1])*t,a[2]+(c[2]-a[2])*t],(c[0]-a[0])/len,(c[2]-a[2])/len,d);}}
const own=(solid,b)=>solid.bedIds.includes(b.id)||(solid.sourceId??solid.id).startsWith(`${b.id}.`);
// 1. Terrain–bed gaps (Auditor 2 P12): every terrain-cut bed at 1 m, on the centre and both edges (0.2 inside), outside open spans:
//    the bed's own deck underside against the terrain or another surface directly below. Depth bands; > body height (1.6) is a fall.
{const bands={'0.02-0.3':0,'0.3-1.25':0,'1.25-5':0,'>5':0},per={};let samples=0,voids=0,deeperThanBody=0,max={gap:0};
 for(const b of w.collision.beds){if(!b.terrainCut||['cable','cave','rail'].includes(b.kind))continue;const ex=(b.terrainExclusions??[]).filter(e=>e.openSpan),e=b.width/2+(b.shoulder??0)-.2;
  walkBed(b,1,([x,h,z],tx,tz)=>{if(ex.some(q=>Math.hypot(x-q.at[0],z-q.at[1])<q.radius))return;for(const off of [-e,0,e]){const px=x-tz*off,pz=z+tx*off;samples++;const col=column(px,pz),tops=col.filter(q=>q.up&&Math.abs(q.y-h)<.35&&own(S[q.s],b)&&(S[q.s].role==='deck'||S[q.s].role==='floor'));if(!tops.length)continue;const top=Math.max(...tops.map(q=>q.y)),bots=col.filter(q=>!q.up&&q.y<top&&q.y>top-80&&own(S[q.s],b));if(!bots.length)continue;const bot=Math.max(...bots.map(q=>q.y));let under=ground(px,pz);for(const q of col)if(q.up&&q.y<bot-.01&&q.y>under&&!own(S[q.s],b))under=q.y;const gap=bot-under;if(gap<=.02)continue;voids++;if(gap>1.6)deeperThanBody++;bands[gap<=.3?'0.02-0.3':gap<=1.25?'0.3-1.25':gap<=5?'1.25-5':'>5']++;const p=(per[b.id]??={voids:0,max:0,at:null});p.voids++;if(gap>p.max){p.max=round(gap);p.at=[px,pz,top].map(round);}if(gap>max.gap)max={gap:round(gap),bed:b.id,at:[px,pz].map(round)};}});}
 await json('probes/horizon-bed-gaps.json',{method:'P12 (review): 1 m along every terrain-cut bed, centre and both edges 0.2 inside, outside open-span exclusions; bed deck underside vs the terrain or another surface below. Replaces the every-10th-centreline-point probe (R1-73).',samples,voids,deeperThanBody,bands,max,perBed:Object.fromEntries(Object.entries(per).sort((a,b)=>b[1].voids-a[1].voids)),pass:voids===0});}
// 2. Tunnel clearance per route (Auditor 2, R1-75): every route that passes through a tunnel's plan box is sampled at 1 m inside it;
//    headroom = the lowest roof/tunnel underside above the route − the route; a missing roof is a failure, not a pass.
{const tunnels=[...new Set(S.filter(s=>s.kind==='tunnel'||/Tunnel\./.test(s.sourceId??s.id)).map(s=>(s.sourceId??s.id).split('.')[0]))],rows=[];
 for(const id of tunnels){const parts=S.filter(s=>(s.sourceId??s.id).startsWith(`${id}.`)),xs=parts.flatMap(s=>s.positions.filter((_,i)=>i%3===0)),zs=parts.flatMap(s=>s.positions.filter((_,i)=>i%3===2)),box=[Math.min(...xs),Math.min(...zs),Math.max(...xs),Math.max(...zs)],roofIds=new Set(parts.filter(s=>s.role==='roof').map(s=>S.indexOf(s)));
  for(const b of w.collision.beds){if(b.kind==='cable')continue;let n=0,missing=0,min=Infinity,minAt=null;walkBed(b,1,([x,h,z])=>{if(x<box[0]||x>box[2]||z<box[1]||z>box[3])return;const col=column(x,z,solid=>(solid.sourceId??solid.id).startsWith(`${id}.`));
   // The route is IN the tunnel only where it runs inside the tunnel's own vertical extent at this column (routes crossing over the top are not).
   if(!col.length||h>col.at(-1).y-.05||h<col[0].y-2)return;n++;const roof=col.filter(q=>roofIds.has(q.s)&&!q.up&&q.y>h+.05&&q.y<h+40);if(!roof.length){missing++;return;}const c=roof[0].y-h;if(c<min){min=c;minAt=[x,z].map(round);}});
   if(n)rows.push({tunnel:id,route:b.id,samples:n,missingRoof:missing,minClearance:min===Infinity?null:round(min),at:minAt,required:b.clearHeight,pass:missing===0&&min>=b.clearHeight-1e-3});}}
 await json('probes/horizon-tunnels.json',{method:'Per route through each tunnel box at 1 m: lowest roof/wall/tunnel underside above the route; missing roof = fail (R1-75).',rows,pass:rows.every(r=>r.pass)});}
// 3. Reserves by measurement (Auditor 2 P31, R1-76): beds inside the plot and inside its 6 m margin, the measured margin to the nearest
//    non-service bed edge, and pad-to-ground (the pad against the terrain round its outline).
{const inPoly=(o,x,z)=>{let c=false;for(let i=0,j=o.length-1;i<o.length;j=i++){const [xi,zi]=o[i],[xj,zj]=o[j];if((zi>z)!==(zj>z)&&x<(xj-xi)*(z-zi)/(zj-zi)+xi)c=!c;}return c;},segD=(p,a,b)=>{const dx=b[0]-a[0],dz=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dz)/(dx*dx+dz*dz||1)));return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dz);},polyD=(p,o)=>inPoly(o,...p)?0:Math.min(...o.map((a,i)=>segD(p,a,o[(i+1)%o.length])));
 const beds=w.collision.beds.filter(b=>!['cable','cave','rail'].includes(b.kind)&&!b.id.endsWith('.service')&&b.id!=='DEEP_RUN'),rows=[];
 for(const rs of w.reserves){const o=rs.outline,inside={},margin={};let nearest=Infinity,nearestBed=null;
  for(const b of beds){const half=b.width/2+(b.shoulder??0);for(const p of b.points){const d=polyD([p[0],p[2]],o)-half;if(d<nearest){nearest=d;nearestBed=b.id;}if(d<0)inside[b.id]=(inside[b.id]??0)+1;else if(d<6)margin[b.id]=(margin[b.id]??0)+1;}}
  const pad=w.collision.pads.find(p=>p.id===rs.id||p.id===rs.placeId),edge=o.flatMap((a,i)=>{const b=o[(i+1)%o.length];return Array.from({length:8},(_,k)=>[a[0]+(b[0]-a[0])*k/8,a[1]+(b[1]-a[1])*k/8]);}),lift=pad?edge.map(([x,z])=>pad.centre[1]-ground(x,z)):[];
  rows.push({id:rs.id,measuredMargin:round(nearest),nearestBed,bedsInside:inside,bedsInMargin:margin,padHeight:pad?round(pad.centre[1]):null,padAboveGroundAtEdge:lift.length?[round(Math.min(...lift)),round(Math.max(...lift))]:null,pass:!Object.keys(inside).length&&nearest>=6&&(!lift.length||Math.max(...lift)<=.5)});}
 await json('probes/horizon-reserves-measured.json',{method:'P31 (review): measured margin to the nearest non-service bed edge (≥ 6), beds whose points fall inside the plot or its 6 m margin, pad height against the terrain along the outline (≤ 0.5 eu floating). Replaces the declared-margin check (R1-76).',rows,pass:rows.every(r=>r.pass)});}
// 4. The view proof's ID-buffer pixel counts (world/views.ts, Auditor 5 P27) at 16:9 and 390 × 844.
await json('probes/horizon-view-pixels.json',{method:'First-hit ray-cast ID buffer per Sketchbook page at 16:9 (128×72) and portrait (60×130, MANIFEST v1.7 viewRule.portrait); subject passes at ≥ minPixels.',passLandscape:w.views.filter(v=>v.proof?.passLandscape).length,passPortrait:w.views.filter(v=>v.proof?.passPortrait).length,views:w.views.map(v=>({id:v.id,pass:v.proof?.pass,landscape:v.proof?.passLandscape,portrait:v.proof?.passPortrait,horizonInFrame:v.proof?.horizonInFrame,eyeAboveFloor:v.proof?.eyeAboveFloor,subjects:v.proof?.subjects?.map(s=>({id:s.id,pixels:s.pixels,portraitPixels:s.portraitPixels,pass:s.pass})),minPixels:[v.proof?.landscape?.minPixels,v.proof?.portrait?.minPixels],top:v.proof?.landscape?.top}))});
console.log(JSON.stringify({output,...meta,conflicts:w.diagnostics.filter(d=>d.severity==='conflict').length}));
