import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdir,writeFile} from 'node:fs/promises';
const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext(),page=await context.newPage(),checks=[],errors=[],out=process.env.HEARTH_ARTIFACTS_DIR??'/tmp/hearthside-handoff-proof';await mkdir(out,{recursive:true});page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
try{
 await page.setViewportSize({width:390,height:900});await page.goto('http://127.0.0.1:5195/hearthside-specimen.html');await page.locator('#hearthside-room-studio').click();await page.locator('#hearthside-open-studio').click();await page.getByRole('button',{name:'Start a piece',exact:true}).click();
 await page.getByRole('button',{name:'Paint and decorate',exact:true}).click();await page.getByText('Paint with the keyboard',{exact:true}).click();await page.getByRole('button',{name:'Add point at 50%, 50%',exact:true}).click();await page.getByRole('button',{name:'Finish my 1-point line',exact:true}).waitFor();
 // Leaving the surface retains the authored keyboard draft under this exact account/household/member/piece.
 await page.locator('#hearthside-room-studio').click();await page.locator('.studio-shelf-pieces>button').first().click();await page.getByRole('button',{name:'Join this piece',exact:true}).click();await page.getByRole('button',{name:'Paint and decorate',exact:true}).click();await page.getByText('Paint with the keyboard',{exact:true}).click();await page.getByRole('button',{name:'Finish my 1-point line',exact:true}).click();await page.getByRole('button',{name:'Finish my 0-point line',exact:true}).waitFor();checks.push({keyboardDraft:'retained through room return, transferred once to durable queue',passed:true});
 await page.getByRole('button',{name:/^Leave the piece for Sam/}).click();await page.getByLabel('A shared note for this piece',{exact:true}).fill('I left a little space for your stars.');await page.getByRole('button',{name:'Leave this invitation',exact:true}).click();
 const invitationRevision=await page.locator('.studio-handoff summary').innerText();await page.locator('#hearthside-room-studio').click();await page.getByLabel('Acting as',{exact:true}).selectOption('MEM-002');
 await page.getByRole('button',{name:'Pick up this piece',exact:true}).click();const piecePath=page.url();await page.getByRole('button',{name:'Join this piece',exact:true}).click();await page.getByRole('button',{name:'Paint and decorate',exact:true}).click();await page.getByText('Paint with the keyboard',{exact:true}).click();await page.getByRole('button',{name:'Add point at 50%, 50%',exact:true}).click();await page.getByRole('button',{name:'Finish my 1-point line',exact:true}).click();await page.getByRole('button',{name:'Undo my last gesture',exact:true}).click();await page.getByRole('button',{name:'Redo my gesture',exact:true}).click();
 if(await page.locator('.studio-handoff summary').innerText()!==invitationRevision)throw Error('Invitation revision followed later edits');checks.push({handoff:'same unfinished piece, partner continuation, own undo/redo, original revision retained',piecePath,passed:true});
 await page.locator('#hearthside-room-studio').click();
 for(const theme of ['classic','taylor','newfoundland'])for(const width of [320,390,719,720,1100,1440,1920]){
  await page.getByLabel('World',{exact:true}).selectOption(theme);await page.setViewportSize({width,height:900});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error(`Overflow ${theme}/${width}`);
  let axe=[];if(width===390||width===1440){const r=await new AxeBuilder({page}).include('section.studio-shelf').analyze();axe=r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));if(axe.length)throw Error(JSON.stringify(axe));await page.screenshot({path:`${out}/${theme}-${width}.png`,fullPage:true});}checks.push({theme,width,shelf:true,axe,overflow:false});
 }
 await page.getByLabel('Acting as',{exact:true}).selectOption('MEM-001');await page.locator('.studio-shelf-pieces>button').first().click();await page.getByRole('button',{name:'Withdraw my invitation',exact:true}).click();await page.locator('#hearthside-room-studio').click();await page.getByLabel('Acting as',{exact:true}).selectOption('MEM-002');if(await page.getByRole('button',{name:'Pick up this piece',exact:true}).count())throw Error('Withdrawn invitation still displayed');if(await page.locator('.studio-shelf-pieces>button').count()!==1)throw Error('Withdrawal deleted or duplicated the piece');checks.push({withdrawal:'invitation removed, shared piece stays reachable',passed:true});
 if(errors.length)throw Error(JSON.stringify(errors));await writeFile(`${out}/evidence.json`,JSON.stringify({scope:'Actual Hearthside Studio, canonical local operations and fictional browser authority; no hosted two-device/physical proof',checks,errors},null,2));console.log(JSON.stringify({checks:checks.length,errors}));
}catch(e){await page.screenshot({path:`${out}/failure.png`,fullPage:true});console.error(e);console.error((await page.locator('body').innerText()).slice(-5000));process.exitCode=1;}finally{await browser.close();}
