import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { renderToStaticMarkup } from 'react-dom/server';
import { TheatreProjector } from '../../src/hearthside/TheatreProjector.tsx';
import { KittyFlat } from '../../src/kitty/studio/flat.tsx';
import { newKittyPiece } from '../../src/core/kittyStudio.ts';
import type { MemoryComposition } from '../../src/hearthside/contracts.ts';
import type { ThemeId } from '../../src/theme/scenes.ts';
let liveDownloadAccess = true;
const params = new URLSearchParams(location.search), publication = { id: 'synthetic-publication', revision: 3, manifestDigest: 'a'.repeat(64) };
if (params.has('unsupported')) Object.defineProperty(globalThis, 'MediaRecorder', { value: undefined, configurable: true });
if (params.has('encoder-fails')) { const Original = MediaRecorder; Object.defineProperty(globalThis, 'MediaRecorder', { value: class extends Original { constructor(stream: MediaStream, options?: MediaRecorderOptions) { super(stream, options); throw Error('Synthetic encoder failure'); } }, configurable: true }); }
function png(canvas: HTMLCanvasElement) { return new Promise<Blob>((resolve, reject) => canvas.toBlob(blob => blob ? resolve(blob) : reject(Error('PNG unavailable')), 'image/png')); }
async function picture() { const c = document.createElement('canvas'); c.width = 800; c.height = 420; const ctx = c.getContext('2d')!; ctx.fillStyle = '#dae1ce'; ctx.fillRect(0, 0, 800, 420); ctx.fillStyle = '#6c896d'; ctx.fillRect(50, 170, 700, 200); ctx.fillStyle = '#f5e6c5'; ctx.beginPath(); ctx.arc(400, 220, 100, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#3d5148'; ctx.font = '26px Georgia'; ctx.fillText('Synthetic image fixture', 256, 60); return png(c); }
async function designPicture() { const piece = newKittyPiece('synthetic-piece', '2026-09-12T00:00:00.000Z', 'rose'); piece.paint.parts.head = '#5e8a73'; const markup = renderToStaticMarkup(<KittyFlat piece={piece} title="Synthetic authored piece, revision 7" style={{ color: '#443a35' }}/>).replace('<svg ', '<svg xmlns="http://www.w3.org/2000/svg" width="300" height="360" '); const url = URL.createObjectURL(new Blob([markup], { type: 'image/svg+xml' })); const img = new Image(); try { await new Promise<void>((resolve, reject) => { img.onload = () => resolve(); img.onerror = () => reject(Error('Saved design could not be rasterized')); img.src = url; }); const c = document.createElement('canvas'); c.width = 600; c.height = 720; c.getContext('2d')!.drawImage(img, 0, 0, 600, 720); return png(c); } finally { URL.revokeObjectURL(url); } }
function tone() { const rate = 16000, frames = 19200, bytes = new ArrayBuffer(44 + frames * 2), view = new DataView(bytes); const write = (offset: number, value: string) => [...value].forEach((char, i) => view.setUint8(offset + i, char.charCodeAt(0))); write(0, 'RIFF'); view.setUint32(4, 36 + frames * 2, true); write(8, 'WAVE'); write(12, 'fmt '); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 1, true); view.setUint32(24, rate, true); view.setUint32(28, rate * 2, true); view.setUint16(32, 2, true); view.setUint16(34, 16, true); write(36, 'data'); view.setUint32(40, frames * 2, true); for (let i = 0; i < frames; i++) view.setInt16(44 + i * 2, Math.sin(i / rate * Math.PI * 440) * 5000, true); return new Blob([bytes], { type: 'audio/wav' }); }
const imagePromise = picture(), designPromise = designPicture(), audioBlob = tone();
const base = (id: string, title: string): MemoryComposition => ({ version: 1, id, revision: 3, title, date: '2026-09-12', experienceId: null, media: [], designs: [], recollections: [{ memberId: 'a', text: params.has('long') ? 'My own words stay intact, through every page and every theme. '.repeat(80) : 'I remember the gentle light.\nThese are my own words.' }, { memberId: 'b', text: 'I remember the conversation.\nMy caption stays beside yours.' }], hideAmounts: true, approvals: [{ memberId: 'a', revision: 3 }, { memberId: 'b', revision: 3 }], withdrawn: false });
function Fixture() {
  const [theme, setTheme] = useState<ThemeId>((params.get('theme') || 'classic') as ThemeId), [scope, setScope] = useState(1), [closed, setClosed] = useState(false), [withdrawn, setWithdrawn] = useState(false), [review, setReview] = useState('');
  const first = base('memory-1', 'An ordinary afternoon'); first.media = [{ version: 1, contentId: 'image-1', revision: 2, kind: 'image', alt: 'Synthetic captured image' }, { version: 1, contentId: 'audio-1', revision: 1, kind: 'audio', alt: 'Synthetic test tone, 1.2 seconds' }]; first.designs = [{ version: 1, documentId: 'design-1', pieceId: 'synthetic-piece', revision: 7 }]; first.withdrawn = withdrawn;
  const second = base('memory-2', 'A second kept moment'), unavailable = base('unavailable', 'An unavailable image'); unavailable.media = [{ version: 1, contentId: 'gone', revision: 1, kind: 'image', alt: 'Unavailable test source' }];
  return <><div className="fixture-controls"><span>Synthetic Projector harness</span><label>Theme <select aria-label="Theme" value={theme} onChange={e => setTheme(e.target.value as ThemeId)}><option value="classic">Classic</option><option value="taylor">Taylor</option><option value="newfoundland">Newfoundland</option></select></label><button onClick={() => setWithdrawn(true)}>Withdraw selection</button><button onClick={() => setScope(value => value + 1)}>Change scope</button><button onClick={() => { liveDownloadAccess = false; }}>Revoke download access</button><output>{review}</output></div>{closed ? <p id="closed">Theatre closed.</p> : <TheatreProjector memories={params.has('empty') ? [] : params.has('missing') ? [unavailable] : [first, second]} activeMemberIds={['a', 'b']} theme={theme} scopeKey={`synthetic:${scope}`} draftScope={{environment:'development',householdId:'synthetic',memberId:`viewer-${scope}`,audience:'household'}} publicationEpoch={withdrawn ? 2 : 1} authorLabels={{ a: 'First voice', b: 'Second voice' }} resolveMedia={async (reference, context) => { if (context.signal.aborted) throw new DOMException('Cancelled', 'AbortError'); if (!liveDownloadAccess || reference.contentId === 'gone') return { status: 'withdrawn' }; return { status: 'available', reference, publication, blob: reference.kind === 'audio' ? audioBlob : await imagePromise }; }} loadDesignSnapshot={async reference => ({ status: 'available', reference, rendering: 'authored-flat', blob: await designPromise })} validateDownload={async (proof, context) => !context.signal.aborted && liveDownloadAccess && !withdrawn && proof.memories.every(memory => memory.revision === 3)} onReviewMemory={(id, revision) => setReview(`Review ${id} revision ${revision}`)} onClose={() => setClosed(true)}/>}</>;
}
const style = document.createElement('style'); style.textContent = 'html{background:#e7e4db}body{margin:0;padding:18px;font-family:system-ui}.fixture-controls{max-width:1440px;margin:0 auto 15px;font:11px system-ui;display:flex;gap:10px;flex-wrap:wrap;align-items:center;color:#4b4b44}.fixture-controls select,.fixture-controls button{min-height:36px}@media(max-width:719px){body{padding:6px}.fixture-controls{font-size:10px;gap:5px}}'; document.head.append(style);
createRoot(document.getElementById('root')!).render(<Fixture/>);
