import { createServer, build } from 'vite';
import react from '@vitejs/plugin-react';
import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile, stat, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const output = resolve('docs/evidence/hearthside-projector'); await mkdir(output, { recursive: true });
await build({ configFile: false, plugins: [react()], logLevel: 'error', build: { write: false, lib: { entry: resolve('src/hearthside/TheatreProjector.tsx'), formats: ['es'] }, rollupOptions: { external: ['react', 'react/jsx-runtime'] } } });
const server = await createServer({ configFile: false, root: process.cwd(), cacheDir: 'scripts/tmp/node_modules/.projector-vite', logLevel: 'error', plugins: [react(), { name: 'projector-fixture', configureServer(vite) { vite.middlewares.use('/__projector', async (req, res) => { res.setHeader('Content-Type', 'text/html'); res.end(await vite.transformIndexHtml(req.url || '/__projector', '<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Synthetic Theatre Projector</title></head><body><div id="root"></div><script type="module" src="/scripts/hearthside/projector-fixture.tsx"></script></body></html>')); }); } }], server: { host: '127.0.0.1', port: 0 } }); await server.listen(); const base = `http://127.0.0.1:${server.httpServer.address().port}/__projector`;
const browser = await chromium.launch({ channel: 'chrome', headless: true }), context = await browser.newContext({ acceptDownloads: true }), page = await context.newPage(); page.setDefaultTimeout(30000); const errors = [], checks = []; page.on('pageerror', error => errors.push(error.message));
await page.addInitScript(() => { const create = URL.createObjectURL.bind(URL), revoke = URL.revokeObjectURL.bind(URL), stop = MediaStreamTrack.prototype.stop; window.__projectorResources = { urls: [], revoked: [], tracksStopped: 0 }; URL.createObjectURL = blob => { const url = create(blob); window.__projectorResources.urls.push(url); return url; }; URL.revokeObjectURL = url => { window.__projectorResources.revoked.push(url); revoke(url); }; MediaStreamTrack.prototype.stop = function () { window.__projectorResources.tracksStopped++; return stop.call(this); }; });
try {
 for (const theme of (process.env.PROJECTOR_RECORDING_ONLY ? [] : ['classic', 'taylor', 'newfoundland'])) for (const width of [320, 390, 719, 720, 1100, 1440, 1920]) {
  await page.setViewportSize({ width, height: 900 }); await page.goto(`${base}?theme=${theme}`); await page.getByRole('button', { name: 'Create film', exact: true }).waitFor(); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled); await page.emulateMedia({ reducedMotion: 'reduce' });
  const record = await page.evaluate(() => ({ overflow: document.documentElement.scrollWidth > innerWidth + 1, smallButtons: [...document.querySelectorAll('.htp button,.htp a')].filter(e => e.getBoundingClientRect().width < 43.9 || e.getBoundingClientRect().height < 43.9).map(e => e.textContent), canvas: [document.querySelector('.htp canvas').width, document.querySelector('.htp canvas').height], reelAnimation: getComputedStyle(document.querySelector('.htp-reel')).animationName })); checks.push({ theme, width, ...record }); if (record.overflow || record.smallButtons.length || record.reelAnimation !== 'none') throw Error(`Layout failed ${theme}/${width}: ${JSON.stringify(record)}`); await page.screenshot({ path: resolve(output, `${theme}-${width}.png`), fullPage: true });
  if (width === 390 || width === 1440) { const axe = await new AxeBuilder({ page }).include('.htp').analyze(); checks.push({ theme, width, axe: axe.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.target) })) }); if (axe.violations.length) throw Error(JSON.stringify(checks.at(-1))); }
 }
 for (const theme of (process.env.PROJECTOR_RECORDING_ONLY ? [] : ['classic', 'taylor', 'newfoundland'])) { await page.setViewportSize({ width: 390, height: 900 }); await page.goto(`${base}?theme=${theme}&empty=1`); await page.getByText('There are no mutually kept versions to project yet.').waitFor(); if (await page.locator('.htp canvas').count()) throw Error('Invented empty artwork'); await page.screenshot({ path: resolve(output, `${theme}-empty-390.png`), fullPage: true }); const axe = await new AxeBuilder({ page }).include('.htp').analyze(); if (axe.violations.length) throw Error(`Empty accessibility ${theme}`); checks.push({ theme, emptyWidth: 390, emptyAxeViolations: 0 }); }
 await page.setViewportSize({ width: 390, height: 900 }); await page.goto(base); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled);
 await page.getByRole('button', { name: 'Review our captions', exact: true }).click(); if (!await page.locator('.fixture-controls output').textContent().then(s => s.includes('memory-1 revision 3'))) throw Error('Review callback lost exact revision');
 await page.getByRole('checkbox', { name: /A second kept moment/ }).check(); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled); await page.getByRole('button', { name: 'Move A second kept moment earlier', exact: true }).click(); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled); if (!await page.locator('.htp-selection li').first().textContent().then(s => s.includes('A second kept moment'))) throw Error('Reorder failed');
 await page.getByLabel('Theme', { exact: true }).selectOption('taylor'); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled); if (!await page.locator('.htp-selection li').first().textContent().then(s => s.includes('A second kept moment'))) throw Error('Theme lost order'); await page.getByRole('checkbox', { name: /A second kept moment/ }).uncheck();
 await page.getByLabel('Seconds per page', { exact: true }).fill('1'); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled); await page.locator('.htp canvas').focus(); await page.keyboard.press('ArrowRight'); await page.waitForFunction(() => document.querySelector('.htp-transport span').textContent.includes('2 /')); await page.keyboard.press('ArrowLeft'); await page.getByRole('button', { name: 'Play story', exact: true }).click(); await page.getByRole('button', { name: 'Pause story', exact: true }).click();
 await page.getByRole('button', { name: 'Create film', exact: true }).click(); await page.getByRole('button', { name: 'Download film', exact: true }).waitFor(); const downloading = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download film', exact: true }).click(); const download = await downloading, videoPath = resolve(output, `synthetic-kept-story.${download.suggestedFilename().split('.').at(-1)}`); await download.saveAs(videoPath);
 const video = await page.evaluate(async videoUrl => { const element = document.createElement('video'); element.src = videoUrl; element.muted = true; document.body.append(element); await new Promise((resolve, reject) => { element.onloadedmetadata = resolve; element.onerror = () => reject(Error('Downloaded video could not decode')); }); await element.play(); await new Promise((resolve, reject) => { const timer = setTimeout(() => reject(Error('Recorded film did not finish playing')), 12000); element.onended = () => { clearTimeout(timer); resolve(); }; }); const recorded = await (await fetch(videoUrl)).blob(); const audioContext = new AudioContext(); let audioEvidence; try { const decoded = await audioContext.decodeAudioData(await recorded.arrayBuffer()); const channel = decoded.getChannelData(0); let peak = 0; for (const value of channel) peak = Math.max(peak, Math.abs(value)); audioEvidence = { duration: decoded.duration, channels: decoded.numberOfChannels, peak }; } finally { await audioContext.close(); } const result = { width: element.videoWidth, height: element.videoHeight, currentTime: element.currentTime, duration: element.duration, mime: recorded.type, ended: element.ended, audio: audioEvidence }; element.pause(); element.removeAttribute('src'); element.load(); element.remove(); return result; }, new URL('/docs/evidence/hearthside-projector/' + videoPath.split('/').at(-1), base).href); if (video.width !== 1280 || video.height !== 720 || video.currentTime < 3 || !video.ended || video.audio.peak < 0.01 || video.audio.duration < 1.19) throw Error(`Invalid actual recorded video: ${JSON.stringify(video)}`); checks.push({ film: { ...video, bytes: (await stat(videoPath)).size, filename: download.suggestedFilename() } }); await page.screenshot({ path: resolve(output, 'film-ready-390.png'), fullPage: true });
 await page.getByRole('button', { name: 'Create film', exact: true }).click(); await page.waitForFunction(() => document.querySelector('.htp-progress progress')?.value > 0.02); await page.getByRole('button', { name: 'Cancel export', exact: true }).click(); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled); if (await page.getByRole('button', { name: 'Download film', exact: true }).count()) throw Error('Cancelled partial film retained');
 await page.getByRole('button', { name: 'Create film', exact: true }).click(); await page.waitForFunction(() => document.querySelector('.htp-progress progress')?.value > 0.02); await page.getByRole('button', { name: 'Withdraw selection', exact: true }).click(); await page.waitForFunction(() => !document.querySelector('.htp canvas')); if (await page.getByRole('button', { name: /Download/ }).count()) throw Error('Withdrawn download retained'); await page.getByRole('button', { name: 'Close theatre', exact: true }).click(); await page.locator('#closed').waitFor(); const resources = await page.evaluate(() => window.__projectorResources); if (resources.urls.some(url => !resources.revoked.includes(url)) || resources.tracksStopped < 6) throw Error(`Resource leak: ${JSON.stringify(resources)}`); checks.push({ resources });
 await page.goto(base); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled); await page.getByRole('button', { name: 'Create story file', exact: true }).click(); await page.getByRole('button', { name: 'Download readable story file', exact: true }).waitFor(); let revokedDownloads = 0; const revokedListener = () => { revokedDownloads++; }; page.on('download', revokedListener); await page.getByRole('button', { name: 'Revoke download access', exact: true }).click(); await page.getByRole('button', { name: 'Download readable story file', exact: true }).click(); await page.getByRole('status').filter({ hasText: 'Access could not be verified' }).waitFor(); if (revokedDownloads || await page.getByRole('button', { name: /Download/ }).count()) throw Error('Revoked cached file escaped the fresh access check'); page.off('download', revokedListener); checks.push({ freshDownloadAccess: 'Rejected changed resolver access without any React props change; no download emitted' });
 await page.goto(base); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled); await page.getByRole('button', { name: 'Create film', exact: true }).click(); await page.waitForFunction(() => document.querySelector('.htp-progress progress')?.value > 0.02); await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, get: () => true }); document.dispatchEvent(new Event('visibilitychange')); }); await page.getByRole('status').filter({ hasText: 'the theatre was hidden' }).waitFor(); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled); if (await page.getByRole('button', { name: /Download/ }).count()) throw Error('Hidden film retained'); const hiddenResources = await page.evaluate(() => window.__projectorResources); if (hiddenResources.tracksStopped < 2) throw Error('Hidden recording tracks not stopped'); checks.push({ backgroundCancel: 'Simulated document visibility event during real MediaRecorder capture; no partial file', tracksStopped: hiddenResources.tracksStopped });
 await page.goto(base); await page.waitForFunction(() => !document.querySelector('.htp-export-actions button').disabled); await page.getByRole('button', { name: 'Next →', exact: true }).click(); await page.getByRole('button', { name: 'Next →', exact: true }).click(); await page.locator('.htp-audio audio').waitFor(); await page.locator('.htp-audio audio').evaluate(async node => { window.__lastAudio = node; node.muted = true; await node.play(); }); await page.getByRole('button', { name: 'Change scope', exact: true }).click(); await page.waitForFunction(() => window.__lastAudio.paused && !window.__lastAudio.getAttribute('src')); checks.push({ audioElementCleanup: 'scope change pauses detached voice note and clears its source' });
 for (const query of ['unsupported=1', 'encoder-fails=1']) { await page.goto(`${base}?${query}`); await page.waitForFunction(() => !document.querySelectorAll('.htp-export-actions button')[1].disabled); await page.getByLabel('Seconds per page', { exact: true }).fill('1'); await page.waitForFunction(() => !document.querySelectorAll('.htp-export-actions button')[1].disabled); await page.getByRole('button', { name: query.startsWith('unsupported') ? 'Create story file' : 'Create film', exact: true }).click(); await page.getByRole('button', { name: 'Download readable story file', exact: true }).waitFor(); const storyDownloading = page.waitForEvent('download'); await page.getByRole('button', { name: 'Download readable story file', exact: true }).click(); const storyDownload = await storyDownloading; const storyPath = await storyDownload.path(); const html = await readFile(storyPath, 'utf8'); if (!html.includes('It is not a video.') || !html.includes('My own exact') && !html.includes('These are my own words.')) throw Error('Readable fallback failed'); checks.push({ fallback: query, bytes: html.length }); }
 await page.goto(`${base}?missing=1`); await page.waitForFunction(() => !document.querySelectorAll('.htp-export-actions button')[1].disabled); await page.screenshot({ path: resolve(output, 'withdrawn-media-390.png'), fullPage: true });
 await page.goto(`${base}?long=1&theme=newfoundland`); await page.waitForFunction(() => !document.querySelectorAll('.htp-export-actions button')[1].disabled); await page.addStyleTag({ content: '.htp-caption-copy article p{font-size:34px}.htp-selection strong{font-size:30px}.htp-heading h2{font-size:50px}' }); if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1)) throw Error('Enlarged captions overflow'); await page.screenshot({ path: resolve(output, 'long-caption-large-text-390.png'), fullPage: true });
 if (errors.length) throw Error(`Browser errors ${JSON.stringify(errors)}`); checks.push({ interactions: 'order, theme retention, review callback, keyboard, pause, actual film download/playback, cancel/withdraw cleanup, unsupported/runtime encoder fallback, long text', pageErrors: errors }); await writeFile(resolve(output, 'evidence.json'), JSON.stringify({ createdAt: new Date().toISOString(), base: '429db8ef0447dac6347e89e945dd04aad05e84fb', scope: 'Synthetic component harness; not actual App, authenticated media, native or physical-device acceptance', checks }, null, 2)); console.log(`Projector proof passed: ${checks.length} records.`);
} finally { await browser.close(); await server.close(); }
