import { build, createServer } from 'vite';
import react from '@vitejs/plugin-react';
import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import { resolve } from 'node:path';

await build({configFile:false,plugins:[react()],logLevel:'error',build:{write:false,lib:{entry:resolve('src/hearthside/RoomScene.tsx'),formats:['es']},rollupOptions:{external:['react','react/jsx-runtime']}}});
const output=resolve('docs/evidence/hearthside-rooms');await mkdir(output,{recursive:true});
const server=await createServer({configFile:false,root:process.cwd(),cacheDir:'scripts/tmp/node_modules/.room-scene-vite',plugins:[react(),{name:'room-fixture',configureServer(vite){vite.middlewares.use('/__rooms',async(req,res)=>{res.setHeader('Content-Type','text/html');res.end(await vite.transformIndexHtml(req.url??'/__rooms','<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hearthside synthetic room scene</title></head><body><div id="root"></div><script type="module" src="/scripts/hearthside/rooms-fixture.tsx"></script></body></html>'));});}}],server:{host:'127.0.0.1',port:0},logLevel:'error'});
await server.listen();const base=`http://127.0.0.1:${server.httpServer.address().port}/__rooms`;
const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext(),page=await context.newPage();page.setDefaultTimeout(60000);
const errors=[];page.on('pageerror',error=>errors.push(error.message));const checks=[];
const themes=['classic','taylor','newfoundland'],rooms=['common','studio','conservatory','theatre'],widths=[320,390,719,720,1100,1440,1920];
try {
 for(const theme of themes)for(const room of rooms)for(const width of widths){
  await page.setViewportSize({width,height:900});await page.goto(`${base}?theme=${theme}&room=${room}`);await page.locator('.hsr-object-index button').first().waitFor();await page.emulateMedia({reducedMotion:'reduce'});
  const metrics=await page.evaluate(()=>{const r=document.querySelector('.hsr'),svg=[...r.querySelectorAll('svg')].map(s=>s.outerHTML).join('');return {overflow:document.documentElement.scrollWidth>innerWidth+1,layers:[...r.querySelectorAll('[data-depth]')].map(e=>e.getAttribute('data-depth')),nodes:r.querySelectorAll('svg *').length,svg,targets:[...r.querySelectorAll('button')].filter(b=>b.getBoundingClientRect().width<43.9||b.getBoundingClientRect().height<43.9).map(b=>b.textContent)};});
  const record={theme,room,width,overflow:metrics.overflow,layers:metrics.layers,nodes:metrics.nodes,gzipSvgBytes:gzipSync(metrics.svg).length,smallTargets:metrics.targets};checks.push(record);
  if(record.overflow||record.layers.length!==6||record.nodes>2500||record.gzipSvgBytes>120000||record.smallTargets.length)throw Error(`Geometry check failed: ${JSON.stringify(record)}`);
  await page.screenshot({path:resolve(output,`${theme}-${room}-${width}.png`),fullPage:true});
  if(width===390||width===1440){const result=await new AxeBuilder({page}).include('.hsr').analyze();checks.push({theme,room,width,axe:result.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});if(result.violations.length)throw Error(`axe: ${JSON.stringify(checks.at(-1))}`);}
 }
 // Actual activation, semantic arrangement, cancel/focus, theme retention and connected thresholds.
 await page.setViewportSize({width:390,height:900});await page.goto(`${base}?theme=classic&room=common&long=1`);
 const first=page.locator('.hsr-object-index li').first();await first.locator('button').first().click();if(!await page.locator('#fixture-result').textContent().then(s=>s.includes('Opened experience')))throw Error('Activation failed');
 await first.getByRole('button',{name:/Arrange/}).click();const formAxe=await new AxeBuilder({page}).include('.hsr-arranger').analyze();if(formAxe.violations.length)throw Error('Arranger accessibility failed');checks.push({arrangerAxe:formAxe.violations});const across=page.getByRole('slider',{name:/Across the room/});await across.focus();await page.keyboard.press('End');await page.getByRole('slider',{name:/Nearer or farther/}).focus();await page.keyboard.press('Home');await page.getByRole('button',{name:'Save position',exact:true}).click();
 if(!await page.locator('#fixture-result').textContent().then(s=>s.includes('0.92,0.08')))throw Error('Placement bounds not applied');
 await page.getByLabel('Theme',{exact:true}).selectOption('newfoundland');if(!await page.locator('#fixture-result').textContent().then(s=>s.includes('0.92,0.08')))throw Error('Theme lost placement');
 await first.getByRole('button',{name:/Arrange/}).click();await page.keyboard.press('Escape');if(!await first.getByRole('button',{name:/Arrange/}).evaluate(e=>document.activeElement===e))throw Error('Arrange focus return failed');
 await page.getByRole('button',{name:/Step into The Studio/}).click();if(await page.locator('.hsr').getAttribute('data-room')!=='studio')throw Error('Door did not navigate');
 await page.screenshot({path:resolve(output,'newfoundland-studio-long-390.png'),fullPage:true});
 for(const theme of themes){await page.goto(`${base}?theme=${theme}&room=theatre&empty=1&paused=1&illustrated=1`);if(await page.locator('.hsr-placed').count())throw Error('Invented empty objects');await page.screenshot({path:resolve(output,`${theme}-theatre-empty-390.png`),fullPage:true});}
 await page.goto(`${base}?theme=taylor&room=conservatory&long=1`);await page.addStyleTag({content:'.hsr{font-size:200%}.hsr-object-index li strong{font-size:32px}.hsr-object-detail{font-size:26px}.hsr-heading>span{font-size:30px}'});await page.screenshot({path:resolve(output,'taylor-conservatory-large-text-390.png'),fullPage:true});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Large-text overflow');
 // Repeated objects receive distinct phone slots and stay fully reachable at the narrowest viewport.
 for(const theme of themes)for(const width of [320,1440]){await page.setViewportSize({width,height:900});await page.goto(`${base}?theme=${theme}&room=common&many=1`);
 const crowded=await page.locator('.hsr-placed').evaluateAll(nodes=>{const rects=nodes.map(n=>n.getBoundingClientRect());return rects.some((a,i)=>rects.slice(i+1).some(b=>a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top));});if(crowded)throw Error(`Repeated objects collide: ${theme}/${width}`);await page.screenshot({path:resolve(output,`${theme}-common-eight-${width}.png`),fullPage:true});}
 // Canonical corner values are preserved, while visual margins prevent clipped or title-covered controls.
 for(const width of [320,720,1440]){await page.setViewportSize({width,height:900});await page.goto(`${base}?theme=classic&room=common`);for(const corner of [['Home','Home'],['End','Home'],['End','End'],['Home','End']]){await page.locator('.hsr-object-index li').first().getByRole('button',{name:/Arrange/}).click();await page.getByRole('slider',{name:/Across/}).focus();await page.keyboard.press(corner[0]);await page.getByRole('slider',{name:/Nearer/}).focus();await page.keyboard.press(corner[1]);await page.getByRole('button',{name:'Save position',exact:true}).click();const placed=page.locator('.hsr-placed').first();await placed.scrollIntoViewIfNeeded();const reachable=await placed.evaluate(e=>{const r=e.getBoundingClientRect(),stage=e.closest('.hsr-stage').getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return r.left>=stage.left&&r.right<=stage.right&&r.top>=stage.top&&r.bottom<=stage.bottom&&e.contains(hit);});if(!reachable)throw Error(`Arranged corner inaccessible at ${width}: ${corner}`);}}
 // Pause, offscreen, keyboard-focus, illustration, and OS reduced-motion policies are observed in the real browser.
 await page.setViewportSize({width:390,height:900});await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(`${base}?theme=classic&room=common`);await page.waitForFunction(()=>document.querySelector('.hsr')?.getAttribute('data-still')==='false');
 if(await page.locator('.hsr-steam').first().evaluate(e=>getComputedStyle(e).animationName)!=='hsr-steam')throw Error('Ambient motion missing');await page.getByRole('button',{name:'Pause on',exact:true}).click();if(await page.locator('.hsr-steam').first().evaluate(e=>getComputedStyle(e).animationPlayState)!=='paused')throw Error('Pause ignored');await page.getByRole('button',{name:'Pause off',exact:true}).click();
 await page.locator('.hsr-placed').first().focus();await page.keyboard.press('Tab');if(await page.locator('.hsr').getAttribute('data-still')!=='true')throw Error('Focus did not pause');const focused=await page.evaluate(()=>{const e=document.activeElement;return e.matches('.hsr button:focus-visible')&&getComputedStyle(e).outlineStyle==='solid';});if(!focused)throw Error('Keyboard focus not visible');await page.setViewportSize({width:390,height:350});await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,document.documentElement.scrollHeight);});await page.waitForFunction(()=>document.querySelector('.hsr')?.getAttribute('data-still')==='true');
 await page.goto(`${base}?theme=classic&room=common&illustrated=1`);await page.locator('.hsr-stage').waitFor();if(await page.locator('.hsr-steam').first().evaluate(e=>getComputedStyle(e).animationPlayState)!=='paused')throw Error('Illustrated scene moved');await page.emulateMedia({reducedMotion:'reduce'});if(await page.locator('.hsr-steam').first().evaluate(e=>getComputedStyle(e).animationName)!=='none')throw Error('Reduced motion ignored');checks.push({motion:'pause, offscreen, keyboard focus, illustrated, OS reduced motion verified',placement:'four corners at 320/720/1440 and eight repeated objects at 320/1440 in all three themes verified',productionComponentBuild:'passed in memory; App integration remains separate'});
 if(errors.length)throw Error(`Browser errors: ${JSON.stringify(errors)}`);checks.push({interactions:'activation, bounds, theme retention, cancel/focus, door, empty, illustrated and text enlargement passed',pageErrors:errors});
 await writeFile(resolve(output,'evidence.json'),JSON.stringify({createdAt:new Date().toISOString(),base:'429db8ef0447dac6347e89e945dd04aad05e84fb',scope:'component host harness; not integrated App or physical-device evidence',checks},null,2));console.log(`Room proof passed: ${checks.length} records, 95 screenshots.`);
} finally {await browser.close();await server.close();}
