import {booksPresentationFloor} from './ledgerExperience.ts';
import type {ActionContext, ActionDefinition, ActionField, ActionValues} from './herculesActions.ts';
import type {Appointment, AppointmentCadence, ClaimKind, Split} from './types.ts';
import {ValidationError} from './types.ts';
import * as commands from './commands.ts';
import {householdForView} from './visibility.ts';
import {claimPublicLabel, claimRemainingCents} from './appointments.ts';
import {claimSettlementReview} from './claimSettlementReview.ts';
import {parseWholeCents, formatCad} from './money.ts';

type Helpers = {
 field: (key:string,label:string,question:string,kind?:ActionField['kind'])=>ActionField;
 date:ActionField; amount:ActionField; account:ActionField; category:ActionField; split:ActionField;
 splits:(c:ActionContext,v:ActionValues)=>Split[];
 financial:(c:ActionContext)=>unknown;
};
/** Visits retain their existing expense/claim commands; ordinary events use the native calendar. */
export function appointmentActions({field,date,amount,account,category,split,splits,financial}:Helpers):ActionDefinition[] {
 const views=['household'] as const;
 const facts=(c:ActionContext)=>({financial:financial(c),appointments:c.household.appointments,claims:c.household.claims});
 const choice=(key:string,label:string,question:string,values:readonly string[]):ActionField=>({...field(key,label,question),choices:()=>values.map(value=>({value,label:value==='true'?'Yes':value==='false'?'No':value==='ohip'?'OHIP':value==='quiet'?'Use a quiet label in Hercules and household notices':value==='household'?'Allow details in Hercules and household notices':value}))});
 const appointment:ActionField={...field('appointmentId','Appointment','Which appointment?'),choices:c=>c.household.appointments.filter(a=>a.active).map(a=>({value:a.id,label:a.sensitivity==='quiet'?'Private appointment · '+a.nextDate:a.title+' · '+a.nextDate}))};
 const claim:ActionField={...field('claimId','Claim','Which claim?'),choices:c=>booksPresentationFloor(c.household,c.memberId,c.view).claims.filter(row=>claimRemainingCents(row)>0).map(row=>({value:row.id,label:`${claimPublicLabel(c.household,row,'hercules')} · ${formatCad(claimRemainingCents(row))} still owing`}))};
 const cadence=choice('cadence','Repeats','How often does this appointment repeat?',['once','weekly','monthly','days','nthWeekday']);
 const cadenceFields=(_c:ActionContext,v:ActionValues):ActionField[]=>v.cadence==='once'?[]:v.cadence==='nthWeekday'?[{...field('weekday','Weekday','Which weekday?'),choices:()=>['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((label,index)=>({value:String(index),label}))},{...field('nth','Week of month','Which occurrence of that weekday?'),choices:()=>['First','Second','Third','Fourth','Last'].map((label,index)=>({value:String(index===4?-1:index+1),label}))},field('intervalMonths','Every how many months?','How many months between appointments?','number')]:[field('interval','Repeat interval','How many weeks, months or days between appointments?','number')];
 const toCadence=(v:ActionValues):AppointmentCadence=>{
  const positive=(key:string)=>{const max=key==='intervalMonths'?18:v.cadence==='weekly'?52:v.cadence==='monthly'?36:730;const n=Number(v[key]);if(!Number.isSafeInteger(n)||n<1||n>max)throw new ValidationError(`Choose a whole repeat interval between 1 and ${max}.`);return n;};
  return v.cadence==='once'?{kind:'once'}:v.cadence==='nthWeekday'?{kind:'nthWeekday',weekday:Number(v.weekday),nth:Number(v.nth),intervalMonths:positive('intervalMonths')}:{kind:v.cadence as 'weekly'|'monthly'|'days',interval:positive('interval')};
 };
 const fields:ActionField[]=[field('title','Appointment name','What is the appointment for?'),choice('kind','Visit type','What kind of visit is it?',['dentist','doctor','therapy','optometrist','physio','vet','spa','other']),{...field('memberId','Who it is for','Who is this appointment for?'),choices:c=>[...c.household.members.filter(m=>m.active).map(m=>({value:m.id,label:m.name})),{value:'joint',label:'Everyone'},{value:'companion',label:'Our pet'}]}, {...date,key:'nextDate',label:'Next appointment date'},cadence,choice('sensitivity','Hercules and notice details','Use the appointment name or a quiet label in Hercules and household notices?',['household','quiet']),choice('coverage','Coverage','What coverage applies?',['ohip','private','none']),account,category,{...amount,key:'typicalCost',label:'Expected visit cost (CAD)',question:'What is the expected cost? Enter 0 if there is no cost.'},{...amount,key:'typicalRecovery',label:'Expected reimbursement (CAD)',question:'How much do you expect back? Enter 0 if none.'},...['place','practitioner'].map(key=>({...field(key,key==='place'?'Location':'Practitioner',key==='place'?'Where is the appointment?':'Who is the appointment with?'),optional:true}))];
 const values=(v:ActionValues)=>({title:v.title!,kind:v.kind as Appointment['kind'],memberId:v.memberId!,nextDate:v.nextDate!,cadence:toCadence(v),sensitivity:v.sensitivity as Appointment['sensitivity'],coverage:v.coverage as Appointment['coverage'],accountId:v.accountId!,subcategoryId:v.subcategoryId!,typicalCost:v.typicalCost!,typicalRecovery:v.typicalRecovery!,place:v.place??'',practitioner:v.practitioner??''});
 const claimKind=choice('claimKind','Reimbursement source','Who should reimburse you?',['insurance','employer','person','tax','other']);
 const recoveryFields:ActionField[]=[{...amount,key:'expectedRecovery',label:'Expected reimbursement (CAD)',question:'How much do you expect back? Enter 0 if none.'},claimKind,{...field('claimLabel','Claim name','What should we call this claim?'),optional:true},choice('craEligible','Tax eligibility','Have you established that this expense is eligible for your tax records?',['false','true'])];
 return [
  {id:'add-appointment',title:'Add an appointment',example:'Add a dentist appointment',match:/\b(?:add|schedule|book) (?:a |an |my )?(?:(?:dentist|doctor|therapy|medical) )?appointment\b/i,views,fields,dynamicFields:cadenceFields,dependencies:facts,consequence:'Save the appointment and expected costs. This does not record a visit, expense or reimbursement.',execute:(c,v)=>commands.addAppointment(c.household,values(v))},
  {id:'edit-appointment',title:'Edit an appointment',example:'Edit an appointment',match:/\b(?:edit|update|change) (?:a |an |my |the )?appointment\b/i,views,fields:[appointment,...fields],dynamicFields:cadenceFields,dependencies:facts,consequence:'Update the appointment schedule and expectations. Recorded visits and claims remain attached.',execute:(c,v)=>commands.updateAppointment(c.household,{appointmentId:v.appointmentId!,...values(v)})},
  {id:'move-appointment',title:'Move an appointment',example:'Move an appointment',match:/\bmove (?:a |an |my |the )?appointment\b/i,views,fields:[appointment,{...date,key:'nextDate',label:'New appointment date'}],dependencies:facts,consequence:'Move the next appointment date. Its repeat settings and recorded visits stay attached.',execute:(c,v)=>commands.updateAppointment(c.household,{appointmentId:v.appointmentId!,nextDate:v.nextDate!})},
  {id:'archive-appointment',title:'Archive an appointment',example:'Archive an appointment',match:/\b(?:archive|remove|cancel) (?:a |an |my |the )?appointment\b/i,views,fields:[appointment],dependencies:facts,consequence:'Stop showing this appointment in upcoming visits. Its recorded expenses and claims remain in the books.',execute:(c,v)=>commands.updateAppointment(c.household,{appointmentId:v.appointmentId!,active:false})},
  {id:'record-visit',title:'Record a completed visit',example:'I paid for my appointment',match:/\b(?:record (?:a |my )?(?:completed )?visit|paid for (?:my |an? )?appointment)\b/i,views,fields:[appointment,date,amount,account,category,split,...recoveryFields],dependencies:facts,consequence:'Record the actual visit expense. Any expected reimbursement creates one linked claim; it is not money received.',execute:(c,v,_id,duplicate)=>commands.postVisit(c.household,{appointmentId:v.appointmentId!,date:v.date!,amount:v.amount!,accountId:v.accountId!,subcategoryId:v.subcategoryId!,splits:splits(c,v),expectedRecovery:v.expectedRecovery!,claimKind:v.claimKind as ClaimKind,claimLabel:v.claimLabel,craEligible:v.craEligible==='true',createdBy:c.memberId,visibility:c.view,confirmDuplicate:duplicate})},
  {id:'open-claim',title:'Track an expected reimbursement',example:'Track a reimbursement for a purchase',match:/\b(?:open (?:a )?claim|track (?:a |an )?(?:expected )?reimbursement)\b/i,views,fields:[{...field('expenseTransactionId','Original expense','Which recorded expense should be reimbursed?'),choices:c=>householdForView(c.household,c.memberId,c.view).transactions.filter(t=>t.type==='expense'&&!t.isDuplicate&&!t.reversalOfId&&!c.household.claims.some(cl=>cl.expenseTransactionId===t.id)).map(t=>({value:t.id,label:`${t.date} · ${t.note||'Expense'} · ${formatCad(t.amountCents)}`}))},...recoveryFields],dependencies:facts,consequence:'Create one claim linked to this expense and record the amount expected back as money owed to you. This is not cash received.',execute:(c,v)=>commands.openClaim(c.household,{expenseTransactionId:v.expenseTransactionId!,expectedRecovery:v.expectedRecovery!,claimKind:v.claimKind as ClaimKind,claimLabel:v.claimLabel,craEligible:v.craEligible==='true',createdBy:c.memberId,visibility:c.view})},
  {id:'submit-claim',title:'Mark a claim as submitted',example:'Mark a claim as submitted',match:/\bmark (?:a |my |the )?claim (?:as )?submitted\b/i,views,fields:[claim],dependencies:facts,consequence:'Record that you already submitted this claim. Hearth does not send it to the insurer or other payer.',execute:(c,v)=>commands.submitClaim(c.household,v.claimId!)},
  {id:'receive-claim',title:'Record a full reimbursement',example:'My full reimbursement arrived',match:/\b(?:my full reimbursement arrived|record (?:a |the )?full reimbursement)\b/i,views,fields:[claim,date,amount,{...account,key:'toAccountId',label:'Receiving account',question:'Which account received the reimbursement?'}],dependencies:facts,consequence:'Record the full outstanding reimbursement as a transfer from money owed to you into the receiving account. It is not new income.',execute:(c,v,_id,duplicate)=>{const request={environment:c.household.environment,householdId:c.household.householdId,memberId:c.memberId,view:c.view,claimId:v.claimId!,toAccountId:v.toAccountId!,date:v.date!,amountCents:parseWholeCents(v.amount!,'Amount',{allowZero:false})};const review=claimSettlementReview(c.household,request);if(review.kind!=='ready')throw new ValidationError(review.reason);return commands.settleClaim(c.household,{claimId:v.claimId!,amount:v.amount!,toAccountId:v.toAccountId!,date:v.date!,createdBy:c.memberId,visibility:c.view,confirmDuplicate:duplicate,claimReview:request});}},
  {id:'writeoff-claim',title:'Record a reimbursement shortfall',example:'My claim was partly denied',match:/\b(?:my claim was (?:partly )?denied|record (?:a )?reimbursement shortfall)\b/i,views,fields:[claim,date,amount,choice('denied','Reason','Was this amount denied, or are you no longer expecting it?',['true','false'])],dependencies:facts,consequence:'Reduce the expected reimbursement by this amount and record the shortfall against the original expense category. No bank money moves.',execute:(c,v)=>commands.writeOffClaim(c.household,{claimId:v.claimId!,amount:v.amount!,date:v.date!,denied:v.denied==='true',createdBy:c.memberId,visibility:c.view})},
 ];
}
