import type {ActionContext,ActionDefinition,ActionField} from './herculesActions.ts';
import {companionFor,commitCompanion} from './herculesCompanion.ts';
import {commitCompanionGallery} from './herculesWardrobe.ts';
import {COMPANION_PREFERENCE_KEYS,type CompanionOperation} from './herculesCompanionContracts.ts';
import {ValidationError} from './types.ts';

const PRIVATE_WARDROBE = new Set(['wear-saved-look','save-current-look','remove-saved-look']);
const SHARED_GALLERY = new Set(['publish-saved-look','rename-gallery-look','remove-gallery-look']);
/** Server-owned classification. No model-provided operation or permission flag is used. */
export function companionActionEffect(step:{kind:string;args:readonly unknown[]}):'private-wardrobe'|'shared-gallery'|null {
 if(step.kind!=='executeHerculesAction')return null;
 const id=(step.args[0] as {review?:{actionId?:string}}|undefined)?.review?.actionId;
 return id&&PRIVATE_WARDROBE.has(id)?'private-wardrobe':id&&SHARED_GALLERY.has(id)?'shared-gallery':null;
}
const scope=(c:ActionContext)=>({environment:c.household.environment,householdId:c.household.householdId,memberId:c.memberId});
const profile=(c:ActionContext)=>companionFor(c.household,c.memberId);
const views=['household','personal'] as const;
const field=(key:string,label:string,question:string):ActionField=>({key,label,question});
const savedLook:ActionField={...field('lookId','Saved outfit','Which saved outfit?'),choices:c=>profile(c).savedLooks.filter(r=>r.value).map(r=>({value:r.id,label:r.value!.name}))};
const galleryLook:ActionField={...field('galleryId','Shared outfit','Which of your shared outfits?'),choices:c=>(c.household.companionGallery??[]).filter(r=>r.creatorMemberId===c.memberId&&r.value).map(r=>({value:r.id,label:r.value!.look.name}))};
const lookFacts=(c:ActionContext)=>({worn:profile(c).wornLook,saved:profile(c).savedLooks});
const galleryFacts=(c:ActionContext)=>({...lookFacts(c),gallery:c.household.companionGallery});
const commit=(c:ActionContext,id:string,operation:CompanionOperation)=>commitCompanion(c.household,{version:1,id,scope:scope(c),operation});
function selected(c:ActionContext,id:string){const r=profile(c).savedLooks.find(r=>r.id===id);if(!r?.value)throw new ValidationError('Choose a current saved outfit.');return r;}
function shared(c:ActionContext,id:string){const r=c.household.companionGallery?.find(r=>r.id===id&&r.creatorMemberId===c.memberId);if(!r?.value)throw new ValidationError('Choose one of your current shared outfits.');return r;}
export const companionActions:ActionDefinition[]=[
 {id:'wear-saved-look',title:'Wear a saved outfit',example:'Wear a saved outfit',match:/\bwear (?:a |my )?saved (?:look|outfit)\b/i,views,fields:[savedLook],dependencies:lookFacts,consequence:'Wear this outfit on your Hercules. It remains private unless you separately share it.',execute:(c,v,id)=>commit(c,id,{kind:'look.wear',look:selected(c,v.lookId!).value!,expectedRevision:profile(c).wornLook.revision})},
 {id:'save-current-look',title:'Save the current outfit',example:'Save your current outfit',match:/\bsave (?:your |the |my )?(?:current )?(?:look|outfit)\b/i,views,fields:[field('name','Outfit name','What should I call this outfit?')],dependencies:lookFacts,consequence:'Save a private copy of the current outfit. It is not published to the household gallery.',execute:(c,v,id)=>{const worn=profile(c).wornLook.value;if(!worn)throw new ValidationError('Choose an outfit in the fitting room first.');return commit(c,id,{kind:'look.save',look:{...worn,id:`look-${id}`,name:v.name!},expectedRevision:0});}},
 {id:'remove-saved-look',title:'Remove a saved outfit',example:'Remove a saved outfit',match:/\b(?:remove|delete) (?:a |my )?saved (?:look|outfit)\b/i,views,fields:[savedLook],dependencies:lookFacts,consequence:'Remove this private saved outfit. The current worn outfit and any separately shared gallery copy stay unchanged.',execute:(c,v,id)=>commit(c,id,{kind:'look.remove',lookId:v.lookId!,expectedRevision:selected(c,v.lookId!).revision})},
 {id:'publish-saved-look',title:'Share a saved outfit',example:'Share a saved outfit with our household',match:/\b(?:share|publish) (?:a |my )?saved (?:look|outfit)\b/i,views,fields:[savedLook],dependencies:galleryFacts,consequence:'Publish a copy of this saved outfit to the household gallery, visible to household members. Your private draft and preferences are not shared.',execute:(c,v,id)=>{const look=selected(c,v.lookId!);return commitCompanionGallery(c.household,{version:1,id,scope:scope(c),operation:{kind:'gallery.publish',galleryId:`gallery-${id}`,sourceLookId:look.id,expectedLookRevision:look.revision,expectedRevision:0}});}},
 {id:'rename-gallery-look',title:'Rename a shared outfit',example:'Rename my shared outfit',match:/\brename (?:my |a )?shared (?:look|outfit)\b/i,views,fields:[galleryLook,field('name','New name','What should the shared outfit be called?')],dependencies:galleryFacts,consequence:'Rename your household gallery copy. Its private saved source keeps its existing name.',execute:(c,v,id)=>commitCompanionGallery(c.household,{version:1,id,scope:scope(c),operation:{kind:'gallery.rename',galleryId:v.galleryId!,name:v.name!,expectedRevision:shared(c,v.galleryId!).revision}})},
 {id:'remove-gallery-look',title:'Remove a shared outfit',example:'Remove my shared outfit',match:/\b(?:remove|delete) (?:my |a )?shared (?:look|outfit)\b/i,views,fields:[galleryLook],dependencies:galleryFacts,consequence:'Remove your outfit from the household gallery. Your private saved outfit remains available.',execute:(c,v,id)=>commitCompanionGallery(c.household,{version:1,id,scope:scope(c),operation:{kind:'gallery.remove',galleryId:v.galleryId!,expectedRevision:shared(c,v.galleryId!).revision}})},
 {id:'remembering',title:'Change preference remembering',example:'Change whether Hercules remembers preferences',match:/\b(?:change whether hercules remembers preferences|turn (?:on|off) (?:preference )?remembering)\b/i,views,fields:[{...field('enabled','Remember preferences','Should I remember supported preferences from our conversations?'),choices:()=>[{value:'true',label:'Remember supported preferences'},{value:'false',label:'Stop remembering new preferences'}]}],dependencies:c=>profile(c).remembering,consequence:'Change whether supported preferences are remembered automatically. Saved conversations and existing preferences remain until you clear them separately.',execute:(c,v,id)=>commit(c,id,{kind:'remembering.set',enabled:v.enabled==='true',expectedRevision:profile(c).remembering.revision})},
 {id:'forget-preference',title:'Forget a saved preference',example:'Forget a saved preference',match:/\bforget (?:a |my )?saved preference\b/i,views,fields:[{...field('key','Saved preference','Which preference should I forget?'),choices:c=>profile(c).preferences.filter(r=>r.value!==null).map(r=>({value:r.key,label:({answerLength:'Answer length',explanationStyle:'Explanation style',humour:'Humour',favouriteColours:'Favourite colours',favouriteOutfits:'Favourite outfits',preferredActivities:'Preferred activities'})[r.key]}))}],dependencies:c=>profile(c).preferences,consequence:'Forget this saved preference. This does not erase conversation history or change your books.',execute:(c,v,id)=>{const key=COMPANION_PREFERENCE_KEYS.find(k=>k===v.key);if(!key)throw new ValidationError('Choose a saved preference.');return commit(c,id,{kind:'preference.forget',key,expectedRevision:profile(c).preferences.find(r=>r.key===key)?.revision??0});}},
 {id:'clear-conversation',title:'Clear this conversation',example:'Clear this conversation',match:/\bclear (?:this|my|the) conversation\b/i,views,fields:[],dependencies:c=>{const row=profile(c).conversations.find(r=>r.view===c.view)!;return{generation:row.generation,turns:row.turns};},consequence:'Clear saved conversation history in this ledger view and invalidate ordinary unfinished drafts. Pending submission identities remain available for receipt recovery. Your books and saved preferences remain.',execute:(c,_v,id)=>commit(c,id,{kind:'conversation.clear',view:c.view,expectedGeneration:profile(c).conversations.find(r=>r.view===c.view)!.generation})},
];
