/** Human-facing names shared by deterministic adapters, suggestions and model context. */
export const HERCULES_WORKFLOW_CATALOGUE = [
    { id: 'add-job', title: 'Set up an hourly job', example: 'Add a job', views: ['household', 'personal'] },
    { id: 'reopen-task', title: 'Reopen a to-do', example: 'Reopen a to-do', views: ['household', 'personal'] },
    { id: 'expense', title: 'Record a purchase', example: 'I just bought something', views: ['household', 'personal'] },
    { id: 'income', title: 'Record money received', example: 'I received some money', views: ['household', 'personal'] },
    { id: 'refund', title: 'Record a refund', example: 'I got a refund', views: ['household', 'personal'] },
    { id: 'transfer', title: 'Move money between accounts', example: 'I paid my credit card', views: ['household', 'personal'] },
    { id: 'potential-expense', title: 'Plan a possible expense', example: 'Plan a possible expense', views: ['household', 'personal'] },
    { id: 'budget', title: 'Set a category budget', example: 'Set a category budget', views: ['household'] },
    { id: 'plan-coaching-preference', title: 'Remember a Plan coaching preference', example: 'Remember a Plan coaching preference', views: ['household', 'personal'] },
    { id: 'plan-guided-draft', title: 'Create a Plan with Hercules', example: 'Help me create a plan', views: ['household', 'personal'] },
    { id: 'plan-line-change', title: 'Change a private Plan decision', example: 'Change a Plan decision', views: ['household', 'personal'] },
    { id: 'plan-scenario', title: 'Create a private Plan alternative', example: 'Help me try a Plan alternative', views: ['household', 'personal'] },
    { id: 'plan-personal-revision', title: 'Lock my Personal Plan revision', example: 'Keep this as my Personal Plan', views: ['personal'] },
    { id: 'plan-household-proposal', title: 'Propose a Household Plan', example: 'Propose this Plan to us', views: ['household'] },
    { id: 'plan-bridge', title: 'Create a reviewed Bridge proposal', example: 'Share a contribution through the Bridge', views: ['household', 'personal'] },
    { id: 'plan-acknowledge', title: 'Acknowledge an exact Household Plan', example: 'Acknowledge this exact Plan', views: ['household'] },
    { id: 'add-account', title: 'Add an account', example: 'Add an account', views: ['household', 'personal'] },
    { id: 'goal', title: 'Create a Kitty Bank', example: 'Create a Kitty Bank', views: ['household', 'personal'] },
    { id: 'task', title: 'Add a to-do', example: 'Add a to-do', views: ['household', 'personal'] },
    { id: 'milestone', title: 'Add a milestone', example: 'Add a milestone', views: ['household'] },
    { id: 'clock-in', title: 'Start my shift', example: 'Start my shift', views: ['household', 'personal'] },
    { id: 'clock-out', title: 'Clock out', example: 'Clock out', views: ['household', 'personal'] },
    { id: 'start-break', title: 'Start a break', example: 'Start my break', views: ['household', 'personal'] },
    { id: 'end-break', title: 'End my break', example: 'End my break', views: ['household', 'personal'] },
    { id: 'worked-shift', title: 'Record a finished shift', example: 'I just finished my shift', views: ['household', 'personal'] },
    { "id": "move-potential", "title": "Move a planned expense", "example": "Move a planned expense", "views": ["household", "personal"] },
    { "id": "remove-potential", "title": "Remove a planned expense", "example": "Remove a planned expense", "views": ["household", "personal"] },
    { "id": "post-potential", "title": "Record a planned purchase", "example": "Record a planned purchase", "views": ["household", "personal"] },
    { "id": "pause-bill", "title": "Pause a repeating item", "example": "Pause a bill", "views": ["household"] },
    { "id": "skip-bill", "title": "Skip the next bill occurrence", "example": "Skip the next bill", "views": ["household"] },
    { "id": "add-bill", "title": "Add a repeating bill", "example": "Add a repeating bill", "views": ["household"] },
    { "id": "rename-account", "title": "Rename an account", "example": "Rename an account", "views": ["household", "personal"] },
    { "id": "archive-account", "title": "Archive an account", "example": "Archive an account", "views": ["household", "personal"] },
    { "id": "fund-goal", "title": "Put money towards a goal", "example": "Put money towards a goal", "views": ["household", "personal"] },
    { "id": "reconcile-account", "title": "Check a statement balance", "example": "Reconcile an account", "views": ["household", "personal"] },
    { "id": "create-event", "title": "Add a calendar event", "example": "Add a calendar event", "views": ["household", "personal"] },
    { "id": "edit-event", "title": "Edit a calendar event", "example": "Edit a calendar event", "views": ["household", "personal"] },
    { "id": "remove-event", "title": "Remove a calendar event", "example": "Remove a calendar event", "views": ["household", "personal"] },
    { id: 'pay-bill', title: 'Record a bill payment', example: 'I paid a bill', views: ['household'] },
    { "id": "reverse-entry", "title": "Reverse a recorded entry", "example": "Reverse a recorded entry", "views": ["household", "personal"] },
    { "id": "category", "title": "Add a category", "example": "Add a category", "views": ["household"] },
    { "id": "receive-pay", "title": "Record wages or tips received", "example": "My paycheck arrived", "views": ["household", "personal"] },
    { "id": "pay-tipout", "title": "Record a tip-out payment", "example": "I paid my outstanding tip-out", "views": ["household", "personal"] },
    { "id": "archive-job", "title": "Archive a job", "example": "Archive a job", "views": ["household", "personal"] },
    { "id": "board-note", "title": "Write a household note", "example": "Write a household note", "views": ["household"] },
    { "id": "remove-note", "title": "Remove a household note", "example": "Remove a household note", "views": ["household"] },
    { "id": "close-month", "title": "Close a month", "example": "Close a month", "views": ["household"] },
    { "id": "reopen-month", "title": "Reopen a month", "example": "Reopen a month", "views": ["household"] },
    { "id": "edit-task", "title": "Edit a to-do", "example": "edit a task", "views": ["household", "personal"] },
    { "id": "complete-task", "title": "Finish a to-do", "example": "complete a task", "views": ["household", "personal"] },
    { "id": "remove-task", "title": "Remove a to-do", "example": "remove a task", "views": ["household", "personal"] },
    { "id": "edit-milestone", "title": "Edit a milestone", "example": "edit a milestone", "views": ["household"] },
    { "id": "complete-milestone", "title": "Finish a milestone", "example": "complete a milestone", "views": ["household"] },
    { "id": "remove-milestone", "title": "Remove a milestone", "example": "remove a milestone", "views": ["household"] },
    { id: 'move-event', title: 'Move a calendar event', example: 'Move a calendar event', views: ['household', 'personal'] },
    { "id": "fund-plan", "title": "Set the Fund monthly plan", "example": "Set the Fund monthly plan", "views": ["household"] },
    { "id": "fund-propose", "title": "Propose my Fund contribution", "example": "Propose my Fund contribution", "views": ["household"] },
    { "id": "fund-hold", "title": "Hold a Fund contribution", "example": "Hold a Fund contribution", "views": ["household"] },
    { "id": "fund-release-hold", "title": "Release my Fund hold", "example": "Release my Fund hold", "views": ["household"] },
    { "id": "fund-withdraw", "title": "Withdraw my Fund proposal", "example": "Withdraw my Fund proposal", "views": ["household"] },
    { "id": "fund-received", "title": "Confirm a Fund contribution arrived", "example": "A Fund contribution arrived", "views": ["household"] },
    { "id": "fund-surplus", "title": "Allocate Fund surplus to a goal", "example": "Allocate Fund surplus to a goal", "views": ["household"] },
    { "id": "fund-release-kitty", "title": "Release Fund goal reserves", "example": "Release Fund goal reserves", "views": ["household"] },
    { "id": "fund-setup", "title": "Set up the Household Fund", "example": "Set up the Household Fund", "views": ["household"] },
    { "id": "fund-approve-setup", "title": "Approve the Fund setup", "example": "Approve the Fund setup", "views": ["household"] },
    { "id": "fund-settlement", "title": "Record a Fund settlement", "example": "Record a Fund settlement", "views": ["household"] },
    { "id": "resume-bill", "title": "Resume a repeating item", "example": "Resume a paused bill", "views": ["household"] },
    { "id": "edit-potential", "title": "Edit a planned expense", "example": "Edit a planned expense", "views": ["household", "personal"] },
    { "id": "abandon-shift", "title": "Discard an unfinished shift clock", "example": "Discard my unfinished shift clock", "views": ["household", "personal"] },
    { "id": "investment-value", "title": "Update an investment value", "example": "Update my investment value", "views": ["household", "personal"] },
    { "id": "account-details", "title": "Edit account details", "example": "Edit account details", "views": ["household", "personal"] },
    { "id": "purchase-goal", "title": "Record a goal purchase", "example": "Buy a completed savings goal", "views": ["household", "personal"] },
    {"id": "add-appointment", "title": "Add an appointment", "example": "Add a dentist appointment", "views": ["household"]},
    {"id": "edit-appointment", "title": "Edit an appointment", "example": "Edit an appointment", "views": ["household"]},
    {"id": "move-appointment", "title": "Move an appointment", "example": "Move an appointment", "views": ["household"]},
    {"id": "archive-appointment", "title": "Archive an appointment", "example": "Archive an appointment", "views": ["household"]},
    {"id": "record-visit", "title": "Record a completed visit", "example": "I paid for my appointment", "views": ["household"]},
    {"id": "open-claim", "title": "Track an expected reimbursement", "example": "Track a reimbursement for a purchase", "views": ["household"]},
    {"id": "submit-claim", "title": "Mark a claim as submitted", "example": "Mark a claim as submitted", "views": ["household"]},
    {"id": "receive-claim", "title": "Record a full reimbursement", "example": "My full reimbursement arrived", "views": ["household"]},
    {"id": "writeoff-claim", "title": "Record a reimbursement shortfall", "example": "My claim was partly denied", "views": ["household"]},
    {"id": "wear-saved-look", "title": "Wear a saved outfit", "example": "Wear a saved outfit", "views": ["household", "personal"]},
    {"id": "save-current-look", "title": "Save the current outfit", "example": "Save your current outfit", "views": ["household", "personal"]},
    {"id": "remove-saved-look", "title": "Remove a saved outfit", "example": "Remove a saved outfit", "views": ["household", "personal"]},
    {"id": "publish-saved-look", "title": "Share a saved outfit", "example": "Share a saved outfit with our household", "views": ["household", "personal"]},
    {"id": "rename-gallery-look", "title": "Rename a shared outfit", "example": "Rename my shared outfit", "views": ["household", "personal"]},
    {"id": "remove-gallery-look", "title": "Remove a shared outfit", "example": "Remove my shared outfit", "views": ["household", "personal"]},
    {"id": "remembering", "title": "Change preference remembering", "example": "Change whether Hercules remembers preferences", "views": ["household", "personal"]},
    {"id": "forget-preference", "title": "Forget a saved preference", "example": "Forget a saved preference", "views": ["household", "personal"]},
    {"id": "clear-conversation", "title": "Clear this conversation", "example": "Clear this conversation", "views": ["household", "personal"]},
] as const;
