import {useEffect,useRef,useState,type PointerEvent} from 'react';
import type {VehicleDressing} from '../movers/shared/vehicleArt.ts';
import {DEFAULT_ASSISTS,INGREDIENTS,RECIPES,SERVICES} from './config.ts';
import {itemLabel} from './model.ts';
import type {ChefId,KitchenAssists,KitchenChefInput,KitchenCommand,KitchenItem,KitchenView,ServiceId} from './types.ts';
import './kitchen.css';

export type KitchenHUDProps={view:KitchenView;onCommand:(command:KitchenCommand)=>void;onInput?:(chef:ChefId,input:Partial<KitchenChefInput>)=>void;theme?:VehicleDressing;reducedMotion?:boolean};
const minutes=(seconds:number)=>{const whole=Math.ceil(Math.max(0,seconds));return `${Math.floor(whole/60)}:${String(whole%60).padStart(2,'0')}`;};
const stars=(count:number)=>`${'★'.repeat(Math.max(0,Math.min(3,count)))}${'☆'.repeat(3-Math.max(0,Math.min(3,count)))}`;
const phaseText={raw:'whole',prepared:'prepared',cooking:'cooking',ready:'cooked',burnt:'burnt'};
const INTRO=['Collect bread from the pantry. E picks it up; Q changes the ingredient.','Place the bread on the cooking range. It toasts while you work.','Collect a tomato and prepare it at a chopping board. F starts or stops preparation.','Take a clean plate. Add the toasted bread and prepared tomato.','Carry the finished bruschetta to the serving pass. E delivers it.','Collect the returned dirty plate, take it to the sink, and use F to wash it.','Your first service is complete. A clean plate is ready for the next order.'];
const RECOVERY='Failed food goes in the waste bin. Dirty plates return to the dish rack; wash and reuse them. Hold the extinguisher and prepare at a burning station.';
const recipeSteps:Record<string,string>={salad:'Chop tomato + lettuce → clean plate → serve.',bruschetta:'Toast bread + chop tomato → clean plate → serve.',fish:'Grill fish + prepare garnish → clean plate → serve.',pasta:'Boil pasta + chop and cook tomato → clean plate → serve.',burger:'Cook patty + prepare toppings + bun → clean plate → serve.'};
const cosmetics:Record<string,string>={'chef-apron':'Chef’s apron','galley-sea-glass':'Sea-glass galley finish','sunset-table':'Sunset table runner','captains-memento':'Captain’s memento'};
function itemText(item:KitchenItem|undefined,view:KitchenView){return item?itemLabel(item,view.state):'Empty hands';}
function targetText(chef:KitchenView['state']['chefs'][number],view:KitchenView){const station=view.stations.find(s=>s.id===chef.target),ingredient=station?.ingredients?.[chef.selection%(station.ingredients.length||1)];return ingredient?station!.label+' · '+INGREDIENTS[ingredient].label+' · E pick / Q change':view.targetLabels[chef.id]||'Face a station to interact';}

function TouchControls({chef,onInput,holdPrep}:{chef:ChefId;onInput:NonNullable<KitchenHUDProps['onInput']>;holdPrep:boolean}){
  const pointer=useRef<number|null>(null),prep=useRef<number|null>(null),accessiblePrep=useRef(false),input=useRef(onInput);input.current=onInput;
  const releaseMove=()=>{pointer.current=null;input.current(chef,{x:0,z:0});};
  useEffect(()=>{const release=()=>{pointer.current=null;prep.current=null;input.current(chef,{x:0,z:0,prepareHeld:false});};const stop=(event:globalThis.PointerEvent)=>{if(pointer.current===event.pointerId){pointer.current=null;input.current(chef,{x:0,z:0});}if(prep.current===event.pointerId){prep.current=null;input.current(chef,{prepareHeld:false});}};window.addEventListener('pointerup',stop);window.addEventListener('pointercancel',stop);window.addEventListener('blur',release);return()=>{window.removeEventListener('pointerup',stop);window.removeEventListener('pointercancel',stop);window.removeEventListener('blur',release);release();};},[chef]);
  const move=(event:PointerEvent<HTMLDivElement>)=>{if(event.type==='pointerdown'){event.preventDefault();pointer.current=event.pointerId;event.currentTarget.setPointerCapture?.(event.pointerId);}else if(pointer.current!==event.pointerId)return;const box=event.currentTarget.getBoundingClientRect(),radius=box.width*.36,x=(event.clientX-box.left-box.width/2)/radius,z=(box.top+box.height/2-event.clientY)/radius,magnitude=Math.max(1,Math.hypot(x,z));onInput(chef,{x:x/magnitude,z:z/magnitude});};
  return <div className="kitchen-touch" aria-label={`Chef ${chef+1} touch controls`}>
    <div className="kitchen-stick" role="group" aria-label={`Chef ${chef+1} movement pad`} onPointerDown={move} onPointerMove={move} onPointerUp={releaseMove} onPointerCancel={releaseMove}><span aria-hidden="true">↑<br/>← <b>{chef+1}</b> →<br/>↓</span><span className="kitchen-sr">Use the movement pad, keyboard, or connected controller.</span></div>
    <div className="kitchen-touch__actions">
      <button onClick={()=>onInput(chef,{interact:true})}><kbd>E</kbd> Pick / place</button>
      <button onPointerDown={event=>{if(!holdPrep)return;event.preventDefault();prep.current=event.pointerId;event.currentTarget.setPointerCapture?.(event.pointerId);onInput(chef,{prepareHeld:true});}} onPointerUp={()=>{if(holdPrep){prep.current=null;onInput(chef,{prepareHeld:false});}}} onPointerCancel={()=>{prep.current=null;onInput(chef,{prepareHeld:false});}} onKeyDown={event=>{if(holdPrep&&[' ','Enter'].includes(event.key)){event.preventDefault();if(!event.repeat)onInput(chef,{prepareHeld:true});}}} onKeyUp={event=>{if(holdPrep&&[' ','Enter'].includes(event.key)){event.preventDefault();onInput(chef,{prepareHeld:false});}}} onBlur={()=>{accessiblePrep.current=false;if(holdPrep)onInput(chef,{prepareHeld:false});}} onClick={event=>{if(!holdPrep)onInput(chef,{prepare:true});else if(event.detail===0){accessiblePrep.current=!accessiblePrep.current;onInput(chef,{prepareHeld:accessiblePrep.current});}}}><kbd>F</kbd> {holdPrep?'Hold to prepare':'Prepare / stop'}</button>
      <button onClick={()=>onInput(chef,{toss:true})}><kbd>R</kbd> Toss</button><button onClick={()=>onInput(chef,{cycle:true})}><kbd>Q</kbd> Choose</button>
    </div>
  </div>;
}

export function KitchenHUD({view,onCommand,onInput,theme='classic',reducedMotion=false}:KitchenHUDProps){
  const {state,connections}=view;
  const [service,setService]=useState<ServiceId>(state.service),[players,setPlayers]=useState<1|2>(state.players),[assists,setAssists]=useState<KitchenAssists>({...DEFAULT_ASSISTS,...state.assists}),[touchChef,setTouchChef]=useState<ChefId>(0),[largeText,setLargeText]=useState(false);
  const panel=useRef<HTMLElement>(null),lastPhase=useRef(state.phase);
  useEffect(()=>{if(lastPhase.current!==state.phase&&['menu','ready','paused','results'].includes(state.phase))panel.current?.focus();lastPhase.current=state.phase;},[state.phase]);
  const selected=SERVICES[service],current=SERVICES[state.service],best=view.progress.best[service];
  const changeAssist=<K extends keyof KitchenAssists>(key:K,value:KitchenAssists[K])=>setAssists(previous=>({...previous,[key]:value}));
  const chooseService=(next:ServiceId)=>{setService(next);if(next==='practice'||service==='practice')setAssists(previous=>({...previous,forgiveness:next==='practice'?2:DEFAULT_ASSISTS.forgiveness,hazards:next==='practice'?false:DEFAULT_ASSISTS.hazards}));};
  const chefs=state.chefs.slice(0,state.players),connected=connections.filter(c=>c.connected&&c.kind!=='none');
  const classes=`kitchen kitchen--${theme}${largeText?' kitchen--large':''}${reducedMotion?' kitchen--still':''}`;
  if(state.phase==='idle')return view.available?<div className={classes}><button className="kitchen-open" onClick={()=>onCommand({type:'open'})}>♧ Yacht Kitchen <span>Menu board · E</span></button></div>:null;
  const connectionList=<ul className="kitchen-connections">{Array.from({length:state.phase==='menu'?players:state.players},(_,id)=>{const connection=connections.find(c=>c.chef===id);return <li key={id} className={`kitchen-chef-${id}`}><b>Chef {id+1}</b><span>{connection?.connected?connection.label:'Waiting for a controller'}</span><small>{connection?.kind==='gamepad'?'Stick move · A pick/place · X prepare · B toss · Y choose · Start ready/pause':connection?.kind==='keyboard'?'WASD / arrows · E pick/place · F prepare · R toss · Q choose · Enter ready · Esc pause':'Connect a controller and press a button.'}</small></li>;})}</ul>;
  const notice=view.storageWarning?<p className="kitchen-notice" role="status">{typeof view.storageWarning==='string'?view.storageWarning:'This device cannot save kitchen progress. You can still finish this service.'}</p>:null;
  const help=<details className="kitchen-help"><summary>Recipes & controls</summary><div className="kitchen-help__body"><p><strong>E / A</strong> picks up, places, adds to a plate, or serves. <strong>F / X</strong> prepares, washes, extinguishes, or secures the trolley. <strong>Q / Y</strong> chooses a pantry ingredient or cycles items on a shared counter or appliance. <strong>R / B</strong> tosses a loose, cool ingredient toward the outlined destination.</p><p>{RECOVERY} Look for the chef number on a target; actions only reach the highlighted station.</p><ul>{Object.values(RECIPES).map(recipe=><li key={recipe.id}><b>{recipe.icon} {recipe.label}</b><span>{recipeSteps[recipe.id]}</span></li>)}</ul><p>Two chefs share the service score, orders, dishes, and pause. Two controllers or keyboard + controller; both players control their own chef.</p></div></details>;
  if(state.phase==='menu')return <div className={classes}><section className="kitchen-panel kitchen-menu" ref={panel} tabIndex={-1} role="dialog" aria-modal="false" aria-labelledby="kitchen-title">
    <header><div><p className="kitchen-eyebrow">A little service at sea</p><h2 id="kitchen-title">Yacht Kitchen</h2></div><button aria-label="Close kitchen menu" onClick={()=>onCommand({type:'exit'})}>✕</button></header>
    <p className="kitchen-intro">Make a dish. Pass a tomato. Keep the plates coming.</p>
    {view.resumable&&<div className="kitchen-resume" role="status"><strong>Your interrupted service is safely paused.</strong><div><button onClick={()=>onCommand({type:'resume-saved'})}>Resume service</button><button onClick={()=>onCommand({type:'discard-saved'})}>Start fresh</button></div></div>}
    <fieldset className="kitchen-services"><legend>Choose a service</legend>{Object.values(SERVICES).map(option=><label key={option.id} className={service===option.id?'is-selected':''}><input type="radio" name="kitchen-service" checked={service===option.id} onChange={()=>chooseService(option.id)}/><span><strong>{option.label}</strong><small>{option.subtitle}</small></span><span className="kitchen-service-rating" aria-label={view.progress.best[option.id]?`${view.progress.best[option.id]!.stars} of 3 stars`:'Not completed'}>{view.progress.best[option.id]?stars(view.progress.best[option.id]!.stars):'—'}</span></label>)}</fieldset>
    <div className="kitchen-menu-grid"><fieldset className="kitchen-player-select"><legend>At the counter</legend><label><input type="radio" name="kitchen-players" checked={players===1} onChange={()=>setPlayers(1)}/> One chef</label><label><input type="radio" name="kitchen-players" checked={players===2} onChange={()=>setPlayers(2)}/> Two local chefs</label><p>{players===1?'Orders and patience are paced for one person.':'Keyboard + controller, or two controllers. Ready up together.'}</p></fieldset><div className="kitchen-service-summary"><b>{selected.label}</b><p>{service==='practice'?'No expiring orders. Leave whenever you like.':service==='first'?'Guided introduction · no countdown.':`${Math.ceil(selected.seconds/60)} minute service · ${selected.area==='deck'?'Galley + deck':'Compact galley'}`}</p><span>{selected.recipes.map(id=>RECIPES[id].icon+' '+RECIPES[id].label).join(' · ')}</span>{best&&<p>Personal best: <strong>{best.score}</strong> service score</p>}</div></div>
    {connectionList}
    <details className="kitchen-assists" open={service==='practice'}><summary>Comfort & practice assists</summary><div><label>Cooking forgiveness<select value={assists.forgiveness} onChange={event=>changeAssist('forgiveness',Number(event.target.value))}><option value={1}>Standard warning time</option><option value={1.5}>Longer warning time</option><option value={2}>Extra warning time</option></select></label><label>Order patience<select value={assists.patience} onChange={event=>changeAssist('patience',Number(event.target.value))}><option value={1}>Standard</option><option value={1.5}>More time</option><option value={2}>Twice the time</option></select></label><label>Preparation<select value={assists.prep} onChange={event=>changeAssist('prep',event.target.value as KitchenAssists['prep'])}><option value="toggle">Press to start / stop</option><option value="hold">Hold to work</option></select></label><label>Warnings<select value={assists.warning} onChange={event=>changeAssist('warning',event.target.value as KitchenAssists['warning'])}><option value="normal">Clear sound + labels</option><option value="gentle">Gentle sound + labels</option></select></label><label className="kitchen-check"><input type="checkbox" checked={assists.hazards} onChange={event=>changeAssist('hazards',event.target.checked)}/> Small, recoverable kitchen fires</label><label className="kitchen-check"><input type="checkbox" checked={largeText} onChange={event=>setLargeText(event.target.checked)}/> Larger kitchen text</label></div></details>
    {help}{view.progress.unlocks.length>0&&<details className="kitchen-rewards"><summary>Service mementos · {view.progress.unlocks.length}</summary><ul>{view.progress.unlocks.map(id=><li key={id}>{cosmetics[id]??id.replace(/[._-]/g,' ')}</li>)}</ul></details>}{notice}
    <footer><span>{players===2&&connected.length<2?'Connect both chefs before readying up.':'The yacht stays anchored during service.'}</span><button className="kitchen-primary" disabled={players===2&&connected.length<2} onClick={()=>onCommand({type:'start',service,players,assists})}>Set the table →</button></footer>
  </section></div>;
  if(state.phase==='ready')return <div className={classes}><section className="kitchen-panel kitchen-ready" ref={panel} tabIndex={-1} role="dialog" aria-modal="false" aria-labelledby="kitchen-ready-title"><p className="kitchen-eyebrow">All hands in the galley</p><h2 id="kitchen-ready-title">{current.label}</h2><p>{state.players===2?'Both chefs ready up to begin.':'Ready when you are. The clock starts after you ready up.'}</p>{connectionList}<div className="kitchen-ready-buttons">{chefs.map(chef=>{const present=connections.some(c=>c.chef===chef.id&&c.connected);return <button key={chef.id} className={`kitchen-chef-${chef.id}`} disabled={!present||chef.ready} onClick={()=>onCommand({type:'action',chef:chef.id,action:{type:'ready'}})}>{chef.ready?'✓ Ready':`Ready, Chef ${chef.id+1}`}<small>{present?'Enter / Start':'Connect a controller'}</small></button>;})}</div><p className="kitchen-notice">The yacht is anchored. Helm controls wait until service ends.</p>{help}{notice}<button onClick={()=>onCommand({type:'exit'})}>Back to yacht</button></section></div>;
  if(state.phase==='paused')return <div className={classes}><section className="kitchen-panel kitchen-paused" ref={panel} tabIndex={-1} role="dialog" aria-modal="false" aria-labelledby="kitchen-pause-title"><p className="kitchen-eyebrow">Everything can wait</p><h2 id="kitchen-pause-title">{state.players===2?'Shared service paused':'Service paused'}</h2><p>{state.pauseReason??'Take a moment. Orders, cooking, and hazards are paused together.'}</p><p>Nothing cooks or loses patience while this panel is open.</p>{connectionList}<div className="kitchen-button-row"><button className="kitchen-primary" onClick={()=>onCommand({type:'resume'})}>Resume service</button>{state.players===2&&<button onClick={()=>onCommand({type:'leave-partner'})}>Continue with one chef</button>}<button onClick={()=>onCommand({type:'restart'})}>Restart service</button><button onClick={()=>onCommand({type:'exit'})}>Return to yacht</button></div>{help}{notice}</section></div>;
  if(state.phase==='results'&&state.result){const result=state.result;return <div className={classes}><section className="kitchen-panel kitchen-results" ref={panel} tabIndex={-1} role="dialog" aria-modal="false" aria-labelledby="kitchen-result-title"><p className="kitchen-eyebrow">The last plate is in</p><h2 id="kitchen-result-title">{current.label}</h2><p className="kitchen-stars" aria-label={`${result.stars} out of 3 stars`}>{stars(result.stars)}</p><p>{result.stars>=3?'A service to remember.':result.stars>=1?'Good work in the galley. There’s room for another round.':'Every service teaches you something. Try a quieter pace, or go again.'}</p><dl className="kitchen-results__stats"><div><dt>Service score</dt><dd>{result.score}</dd></div><div><dt>Dishes served</dt><dd>{result.served}</dd></div><div><dt>Orders missed</dt><dd>{result.missed}</dd></div><div><dt>Best sequence</dt><dd>{result.bestSequence}</dd></div></dl><p className="kitchen-fine">A game score for this kitchen. No household money or budgeting tasks are involved.</p>{view.progress.unlocks.length>0&&<p>Service mementos: {view.progress.unlocks.map(id=>cosmetics[id]??id.replace(/[._-]/g,' ')).join(' · ')}</p>}<div className="kitchen-button-row"><button className="kitchen-primary" onClick={()=>onCommand({type:'restart'})}>Another round</button><button onClick={()=>onCommand({type:'open'})}>Choose a service</button><button onClick={()=>onCommand({type:'exit'})}>Return to yacht</button></div>{notice}</section></div>;}
  const waiting=state.orders.filter(order=>order.status==='waiting'),recent=state.events.slice(-3),fires=Object.values(state.fires).some(value=>value>0);
  const cooking=Object.values(state.items).filter(item=>item.kind==='ingredient'&&item.location.kind==='station'&&(item.phase==='cooking'||item.phase==='ready'||item.phase==='burnt'));
  return <div className={`${classes} kitchen--playing${state.service==='first'?' kitchen--guided':''}${state.service==='sunset'?' kitchen--deck':''}`}>
    <section className="kitchen-service-bar" aria-label="Service status"><div><strong>{current.label}</strong><span>{state.players===2?'Two chefs · shared service':'Solo service'}</span></div><p><b>{state.score}</b> <span>service score</span></p><p><b>{state.sequence>0?`×${state.sequence}`:'—'}</b><span>sequence</span></p><p className={state.remaining<30&&!['practice','first'].includes(state.service)?'is-urgent':''}><b>{state.service==='practice'?'∞':state.service==='first'?'—':minutes(state.remaining)}</b><span>{state.service==='practice'?'relaxed':state.service==='first'?'guided':'remaining'}</span></p><button onClick={()=>onCommand({type:'camera'})} aria-label="Use recommended kitchen view">Kitchen view</button>{state.service==='practice'&&<button onClick={()=>onCommand({type:'action',chef:0,action:{type:'ready'}})}>Finish practice</button>}<button onClick={()=>onCommand({type:'pause'})} aria-label={state.players===2?'Pause for both chefs':'Pause service'}>Ⅱ Pause</button></section>
    <ol className="kitchen-orders" aria-label="Orders">{waiting.length?waiting.map((order,index)=>{const recipe=RECIPES[order.recipe],ratio=order.total>0?Math.max(0,Math.min(1,order.remaining/order.total)):1;return <li key={order.id} className={ratio<.25&&!['practice','first'].includes(state.service)?'is-urgent':''}><div><span className="kitchen-order-number">{index+1}</span><strong><span aria-hidden="true">{recipe.icon}</span> {recipe.label}</strong></div><ul>{recipe.components.map((component,i)=><li key={i}><span aria-hidden="true">{INGREDIENTS[component.ingredient].icon}</span> {phaseText[component.phase]} {INGREDIENTS[component.ingredient].label.toLowerCase()}</li>)}</ul><div className="kitchen-patience"><progress max={order.total||1} value={['practice','first'].includes(state.service)?order.total||1:Math.max(0,order.remaining)} aria-label={`${recipe.label} patience`}/><span>{['practice','first'].includes(state.service)?'Take your time':`${Math.ceil(order.remaining)}s${ratio<.25?' · Soon!':''}`}</span></div></li>;}):<li className="kitchen-order-empty">The next order is on its way. A good moment to wash a plate.</li>}</ol>
    {state.service==='first'&&<aside className="kitchen-tutorial"><b>First Service · {Math.min(6,state.tutorial+1)} / 6</b><p>{INTRO[Math.min(state.tutorial,INTRO.length-1)]}</p></aside>}
    <section className="kitchen-work-status" aria-label="Cooking and chef status">
      {cooking.length>0&&<ul className="kitchen-cooking" aria-label="Food on appliances">{cooking.map(item=>{const location=item.location,station=location.kind==='station'?view.stations.find(s=>s.id===location.station):undefined,cook=item.ingredient?INGREDIENTS[item.ingredient].cook:undefined,warning=item.phase==='ready'&&cook&&item.cookElapsed>=cook.seconds+cook.warning*state.assists.forgiveness;return <li key={item.id} className={item.phase==='burnt'||warning?'is-urgent':''}><span>{station?.label??'Appliance'}</span><b>{itemText(item,view)}</b>{item.phase==='cooking'?<progress max={1} value={item.progress} aria-label={`${itemText(item,view)} cooking progress`}/>:<strong>{item.phase==='burnt'?'⚠ Burnt · discard':warning?'⚠ Ready · burning soon':'✓ Ready · collect'}</strong>}</li>;})}</ul>}
      <div className="kitchen-chefs">{chefs.map(chef=><article key={chef.id} className={`kitchen-chef-${chef.id}`}><b>Chef {chef.id+1}{!chef.connected?' · disconnected':''}</b><span>{itemText(chef.held?state.items[chef.held]:undefined,view)}</span><small>{chef.task?`${chef.task.kind==='wash'?'Washing':chef.task.kind==='extinguish'?'Extinguishing':'Preparing'} · F / X to stop`:targetText(chef,view)}</small>{view.tossTargets[chef.id]&&<small>↗ Toss destination marked · R / B</small>}</article>)}</div>
    </section>
    <div className="kitchen-announcements" role="status" aria-live="polite" aria-atomic="true">{fires&&<p className="kitchen-fire">⚠ Kitchen fire · use the extinguisher, then discard the burnt food.</p>}{recent.map(event=><p key={event.seq} className={['warning','burn','miss'].includes(event.kind)?'is-warning':''}>{event.chef!==undefined?`Chef ${event.chef+1}: `:''}{event.message}</p>)}</div>
    {onInput&&<div className="kitchen-touch-wrap">{state.players===2&&<label><span>Chef</span><select aria-label="Touch controls for chef" value={touchChef} onChange={event=>setTouchChef(Number(event.target.value) as ChefId)}><option value={0}>1</option><option value={1}>2</option></select></label>}<TouchControls chef={state.players===1?0:touchChef} onInput={onInput} holdPrep={state.assists.prep==='hold'}/></div>}
    <div className="kitchen-playing-help">{help}</div>{notice}
  </div>;
}
export default KitchenHUD;
