import { useId, useState } from 'react';
import type { CommitResult, Household } from './core/types.ts';
import type { DateKey } from './core/calendar.ts';
import { acknowledgeRitualChange, adoptChapterTasks, completeMove, editRitual, pendingRitualReview, prepareRitualOccurrence, recordRitualHeld, respondToMove, ritualAgreementRevision, ritualTerms, setRitualParticipation, type Move, type Ritual, type RitualTerms } from './core/chapters.ts';
import { chapterTask, ritualOperational } from './core/chapterTasks.ts';
import { acknowledgeTask, taskCompletionBlock, taskIsFinancial, type Task, type TaskEvidence, type TaskMoneyLink } from './core/tasks.ts';
import './chapterTaskControls.css';

export type ChapterRun = (fn: (current: Household) => CommitResult) => Promise<unknown>;
export type ChapterControlProps = { household: Household; memberId: string; onCommand: ChapterRun; busy: boolean };
const name = (h: Household, id: string | null) => id ? h.members.find(m => m.id === id)?.name ?? 'An earlier member' : 'Unassigned';
const money = (cents: number) => new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD' }).format(cents / 100);
const accepted = (value: unknown) => Boolean(value && typeof value === 'object' && 'ok' in value && value.ok === true && 'household' in value);
function useChapterAction(onCommand: ChapterRun) {
  const [error, setError] = useState<string | null>(null);
  const run = async (fn: (h: Household) => CommitResult) => { setError(null); try { const result = await onCommand(fn); return accepted(result); } catch (cause) { setError(cause instanceof Error ? cause.message : 'This action was not saved. Read its current state and try again.'); return false; } };
  return { run, error };
}
export function ChapterAdoption({ household, memberId, onCommand, busy, chapterId }: ChapterControlProps & { chapterId: string }) {
  const { run, error } = useChapterAction(onCommand);
  const needed = household.moves?.some(m => m.chapterId === chapterId && !m.taskId) || household.rituals?.some(r => r.chapterId === chapterId && !r.taskAdoption);
  if (!needed) return null;
  return <aside className="chapter-review" aria-label="Connect earlier Chapter work"><p>Keep your earlier Chapter work in the Planner. Its existing history stays intact; earlier unknown authors remain unknown.</p><button type="button" disabled={busy} onClick={() => void run(h => adoptChapterTasks(h, { memberId, chapterId }))}>Connect existing work to Tasks</button>{error && <p role="alert">{error}</p>}</aside>;
}

function evidenceOptions(h: Household, task: Task): { value: string; label: string; evidence: TaskEvidence }[] {
  const onDate = task.chapterSource?.onDate;
  if (task.moneyLink?.kind === 'goal') return (h.goalContributions ?? []).filter(row => row.goalId === (task.moneyLink as { goalId: string }).goalId && (!onDate || row.date === onDate)).map(row => ({ value: `goal:${row.id}`, label: `${row.date} · ${money(row.amountCents)} · contribution`, evidence: { kind: 'goal-contribution', contributionId: row.id, date: row.date, amountCents: row.amountCents } }));
  return h.transactions.filter(row => !row.isDuplicate && row.visibility !== 'personal' && !row.reversalOfId && row.source !== 'reversal' && !h.transactions.some(other => other.reversalOfId === row.id) && (!onDate || row.date === onDate) && (!task.moneyLink || task.moneyLink.kind === 'recurrence' && row.source === 'recurring' && row.sourceId === task.moneyLink.recurrenceId && row.date === task.moneyLink.date || task.moneyLink.kind === 'potential-expense' && h.potentialExpenses?.some(planned => planned.id === (task.moneyLink as { potentialExpenseId: string }).potentialExpenseId && planned.status === 'posted' && planned.transactionId === row.id))).map(row => ({ value: `transaction:${row.id}`, label: `${row.date} · ${money(row.amountCents)} · ${row.note || 'Accepted receipt'}`, evidence: { kind: 'transaction', transactionId: row.id, date: row.date, amountCents: row.amountCents } }));
}
function TaskCompletion({ household, memberId, task, busy, onComplete }: Omit<ChapterControlProps, 'onCommand'> & { task: Task; onComplete: (evidence?: TaskEvidence) => void }) {
  const [selection, setSelection] = useState('');
  const financial = taskIsFinancial(task), options = evidenceOptions(household, task), chosen = options.find(row => row.value === selection);
  const blocked = taskCompletionBlock(household, task, memberId); const eligible = blocked === null;
  if (!eligible || task.completedAt || task.deleted) return null;
  return <div className="chapter-task-completion">{financial && <><label>Existing accepted evidence<select value={selection} onChange={event => setSelection(event.target.value)}><option value="">Choose a receipt</option>{options.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><p className="muted">Attach the existing receipt for this work. Record any payment through the money review first.</p>{options.length === 0 && <p>No eligible shared receipt is available for this occurrence.</p>}</>}<button type="button" disabled={busy || financial && !chosen} onClick={() => onComplete(chosen?.evidence)}>{financial ? 'Attach receipt and complete' : 'Mark done'}</button></div>;
}
export function ChapterMoveActions(props: ChapterControlProps & { move: Move }) {
  return <MoveActions key={JSON.stringify([props.household.environment, props.household.householdId, props.memberId, props.move.id])} {...props} />;
}
function MoveActions({ household, memberId, move, onCommand, busy }: ChapterControlProps & { move: Move }) {
  const { run, error } = useChapterAction(onCommand), task = move.taskId ? household.tasks?.find(row => row.id === move.taskId) : null;
  if (!task) return <p className="muted">Connect this earlier Move to Tasks to continue.</p>;
  if (task.completedAt || task.deleted) return <p className="muted">{task.completedAt ? `Completed ${task.completedAt.slice(0, 10)}${task.completedBy ? ` by ${name(household, task.completedBy)}` : ' · earlier author not recorded'}` : task.chapterSource?.legacy?.originalState === 'done' ? 'Completed earlier · date and author were not recorded' : 'Kept in the earlier Task history'}</p>;
  const paused = task.participation?.some(row => row.memberId === memberId && row.paused), canTake = !task.assigneeId || task.assigneeId === memberId || task.backupId === memberId;
  const act = (response: 'accept' | 'pause' | 'acknowledge') => void run(h => respondToMove(h, { memberId, moveId: move.id, expectedTaskRevision: task.revision, response }));
  return <div className="chapter-task-controls"><p>{name(household, task.assigneeId)} · {task.assigneeId && !task.acknowledgedBy.includes(task.assigneeId) ? 'assignment awaiting acceptance' : paused ? 'your participation is paused' : 'one Task, shared with the Planner'}</p><div className="chapter-actions">{canTake && (!task.acknowledgedBy.includes(memberId) || paused) && <button type="button" disabled={busy} onClick={() => act('accept')}>{paused ? 'Resume my participation' : 'Take this task'}</button>}{move.needsAcknowledgment && !move.acknowledgedByMemberIds.includes(memberId) && <button type="button" disabled={busy} onClick={() => act('acknowledge')}>Agree to this exact Move</button>}{!paused && <button type="button" disabled={busy} onClick={() => act('pause')}>Pause my participation</button>}</div><TaskCompletion key={task.revision} household={household} memberId={memberId} task={task} busy={busy} onComplete={evidence => void run(h => completeMove(h, { memberId, moveId: move.id, expectedTaskRevision: task.revision, evidence }))} />{error && <p role="alert">{error}</p>}</div>;
}
export function RitualTermsRead({ household, terms }: { household: Household; terms: RitualTerms }) {
  return <dl className="chapter-terms"><dt>Action</dt><dd>{terms.title}</dd><dt>When</dt><dd>{terms.cue}{terms.cueNote ? ` · ${terms.cueNote}` : ''}</dd><dt>Responsibility</dt><dd>{name(household, terms.ownerMemberId)}{terms.backupMemberId ? ` · backup: ${name(household, terms.backupMemberId)}` : ''}</dd><dt>Done means</dt><dd>{terms.doneDefinition}</dd><dt>If we miss it</dt><dd>{terms.recoveryMove || 'Choose a smaller next step together.'}</dd><dt>Shared state</dt><dd>{terms.state}</dd><dt>Evidence</dt><dd>{terms.moneyLink || terms.requiresMoneyEvidence ? `Accepted financial receipt${terms.moneyLink ? ` · ${moneyLinkLabel(household, terms.moneyLink)}` : ' · choose its existing bank or bill'}${terms.expectedAmountCents !== null ? ` · expected ${money(terms.expectedAmountCents)}` : ''}` : 'The responsible person records completion'}</dd></dl>;
}
function moneyLinkLabel(h: Household, link: TaskMoneyLink) { return link.kind === 'goal' ? h.goals.find(row => row.id === link.goalId)?.name ?? 'Earlier bank' : link.kind === 'recurrence' ? `${h.recurrences.find(row => row.id === link.recurrenceId)?.note || 'Recurring bill'} · ${link.date}` : h.potentialExpenses?.find(row => row.id === link.potentialExpenseId)?.title || 'Planned expense'; }
export function RitualCard(props: ChapterControlProps & { ritual: Ritual; today: DateKey }) { return <RitualCardState key={JSON.stringify([props.household.environment, props.household.householdId, props.memberId, props.ritual.id])} {...props} />; }
function RitualCardState({ household, memberId, ritual, today, onCommand, busy }: ChapterControlProps & { ritual: Ritual; today: DateKey }) {
  const { run, error } = useChapterAction(onCommand), [date, setDate] = useState(today), [editing, setEditing] = useState(false);
  const pending = pendingRitualReview(ritual), participation = ritual.participation?.find(row => row.memberId === memberId), task = chapterTask(household, { kind: 'ritual-occurrence', sourceId: ritual.id, onDate: date });
  const eligible = task && (task.assigneeId === memberId || task.backupId === memberId || !task.assigneeId);
  return <article className={`ritual chapter-ritual ritual--${ritual.state}`} aria-label={ritual.title}><h5>{ritual.title}</h5>{(!pending || ritual.agreement?.acceptedProposalId || ritual.agreement?.legacyBaseline) && <RitualTermsRead household={household} terms={ritualTerms(ritual)} />}<p className="muted">{ritual.heldOn.length ? `Kept on ${ritual.heldOn.join(', ')}.` : 'A small habit, ready to find its rhythm.'} A gap costs nothing.</p>
    {pending && <section className="chapter-review" aria-label="Review shared Ritual"><h6>Choose these exact terms together</h6><RitualTermsRead household={household} terms={pending.terms} /><p>Agreed by {pending.approvals.map(row => name(household, row.memberId)).join(' and ')}. Existing dated Tasks keep their reviewed responsibility.</p>{pending.approvals.some(row => row.memberId === memberId) ? <p>Waiting for the other participant’s review.</p> : <button type="button" disabled={busy} onClick={() => void run(h => acknowledgeRitualChange(h, { memberId, ritualId: ritual.id, expectedRevision: ritualAgreementRevision(ritual), proposalId: pending.id, digest: pending.digest }))}>I agree to these Ritual terms</button>}</section>}
    <div className="chapter-actions"><button type="button" disabled={busy} onClick={() => void run(h => setRitualParticipation(h, { memberId, ritualId: ritual.id, expectedMemberRevision: participation?.revision ?? 0, paused: !participation?.paused }))}>{participation?.paused ? 'Resume my Ritual participation' : 'Pause my Ritual participation'}</button><button type="button" disabled={busy} onClick={() => setEditing(!editing)}>{editing ? 'Close edit' : 'Propose a shared change'}</button></div>{participation?.paused && <p role="status">You have paused. Responsibility stays with the person who accepted it.</p>}
    {editing && <RitualEditor key={ritualAgreementRevision(ritual)} household={household} ritual={ritual} busy={busy} onSave={terms => void run(h => editRitual(h, { memberId, ritualId: ritual.id, expectedRevision: ritualAgreementRevision(ritual), terms })).then(ok => { if (ok) setEditing(false); })} />}
    {ritual.taskAdoption && ritualOperational(ritual) && <section className="chapter-occurrence" aria-label="This Ritual occurrence"><label>Occurrence date<input type="date" value={date} onChange={e => setDate(e.target.value)} /></label>{!task ? <button type="button" disabled={busy || !date || participation?.paused} onClick={() => void run(h => prepareRitualOccurrence(h, { memberId, ritualId: ritual.id, expectedRevision: ritualAgreementRevision(ritual), onDate: date }))}>Prepare this occurrence</button> : <><p>{task.title} · {name(household, task.assigneeId)} · {task.completedAt ? `completed ${task.completedAt.slice(0, 10)}` : task.deleted ? 'Earlier completion kept; its author and time were not recorded.' : task.acknowledgedBy.includes(task.assigneeId ?? '') ? 'assignment accepted' : 'assignment awaiting acceptance'}</p>{!task.deleted && !task.completedAt && eligible && !task.acknowledgedBy.includes(memberId) && <button type="button" disabled={busy || participation?.paused} onClick={() => void run(h => acknowledgeTask(h, { memberId, id: task.id, expectedRevision: task.revision }))}>Take this occurrence</button>}{!participation?.paused && <TaskCompletion key={`${task.id}:${task.revision}`} household={household} memberId={memberId} task={task} busy={busy} onComplete={evidence => void run(h => recordRitualHeld(h, { memberId, ritualId: ritual.id, onDate: date, expectedTaskRevision: task.revision, evidence }))} />}</>}</section>}{error && <p role="alert">{error}</p>}</article>;
}
function RitualEditor({ household, ritual, busy, onSave }: { household: Household; ritual: Ritual; busy: boolean; onSave: (terms: RitualTerms) => void }) {
  const [terms, setTerms] = useState(() => ritualTerms(ritual)), formId = useId();
  const links: { value: string; label: string; link: TaskMoneyLink }[] = [ ...household.goals.filter(row => row.shared).map(row => ({ value: `goal:${row.id}`, label: `Bank · ${row.name}`, link: { kind: 'goal' as const, goalId: row.id } })), ...(household.potentialExpenses ?? []).filter(row => row.visibility !== 'personal').map(row => ({ value: `expense:${row.id}`, label: `Planned expense · ${row.title || row.id}`, link: { kind: 'potential-expense' as const, potentialExpenseId: row.id } })) ];
  if (terms.moneyLink && !links.some(row => JSON.stringify(row.link) === JSON.stringify(terms.moneyLink))) links.push({ value: 'current', label: moneyLinkLabel(household, terms.moneyLink), link: terms.moneyLink });
  const chosenLink = links.find(row => JSON.stringify(row.link) === JSON.stringify(terms.moneyLink))?.value ?? '';
  const field = (label: string, key: 'title' | 'cueNote' | 'doneDefinition' | 'recoveryMove') => <label>{label}<textarea rows={key === 'title' || key === 'cueNote' ? 1 : 2} maxLength={key === 'title' ? 120 : key === 'cueNote' ? 240 : 2000} value={terms[key]} onChange={event => setTerms({ ...terms, [key]: event.target.value })} /></label>;
  return <form className="chapter-ritual-editor" aria-labelledby={formId} onSubmit={event => { event.preventDefault(); onSave(terms); }}><h6 id={formId}>Propose the next version</h6>{field('Ritual action', 'title')}<label>Shared cue<select value={terms.cue} onChange={e => setTerms({ ...terms, cue: e.target.value as RitualTerms['cue'] })}>{['payday', 'pre-rent', 'weekly', 'sitdown', 'after-surprise', 'custom'].map(cue => <option key={cue}>{cue}</option>)}</select></label>{field('Cue detail', 'cueNote')}<label>Responsible person<select value={terms.ownerMemberId} onChange={e => setTerms({ ...terms, ownerMemberId: e.target.value, backupMemberId: terms.backupMemberId === e.target.value ? null : terms.backupMemberId })}>{household.members.filter(row => row.active).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label>Backup person<select value={terms.backupMemberId ?? ''} onChange={e => setTerms({ ...terms, backupMemberId: e.target.value || null })}><option value="">No backup</option>{household.members.filter(row => row.active && row.id !== terms.ownerMemberId).map(row => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label>{field('Done means', 'doneDefinition')}{field('If we miss it', 'recoveryMove')}<label>Shared Ritual state<select value={terms.state} onChange={e => setTerms({ ...terms, state: e.target.value as RitualTerms['state'] })}>{['active', 'graduated', 'paused', 'retired'].map(state => <option key={state}>{state}</option>)}</select></label><label>Evidence source<select value={chosenLink} onChange={e => setTerms({ ...terms, moneyLink: links.find(row => row.value === e.target.value)?.link ?? null })}><option value="">No financial record linked</option>{links.map(row => <option key={row.value} value={row.value}>{row.label}</option>)}</select></label><label className="chapter-check"><input type="checkbox" checked={terms.requiresMoneyEvidence} onChange={e => setTerms({ ...terms, requiresMoneyEvidence: e.target.checked })} />This work requires accepted financial evidence</label><label>Expected amount (CAD, optional)<input inputMode="decimal" value={terms.expectedAmountCents === null ? '' : String(terms.expectedAmountCents / 100)} onChange={e => { const amount = e.target.value.trim(); if (amount === '' || /^\d+(\.\d{0,2})?$/.test(amount)) setTerms({ ...terms, expectedAmountCents: amount === '' ? null : Math.round(Number(amount) * 100) }); }} /></label><p>The shared change takes effect when both people agree. Preparing a contribution or choosing this source does not move money.</p><button type="submit" disabled={busy || !terms.title.trim() || !terms.doneDefinition.trim()}>Propose and give my agreement</button></form>;
}
