import { useMemo } from "react";
import { addDays, formatCad, monthKeyFromDateKey, saveBoardTask, type Household, type HerculesNumberSource } from "./core/index.ts";
import { planSelectionForVersion, projectPlan } from "./core/planProjection.ts";
import { SharedBoards, type SharedBoardsProps } from "./widgets/SharedBoards.tsx";
import { shapeSharedBoards } from "./core/sharedBoards.ts";

function acceptedPlan(household: Household, today: string) {
  return [...(household.planVersions ?? [])].filter(row => row.scope === "household" && row.monthKey === monthKeyFromDateKey(today) && row.state === "active").sort((a, b) => b.sequence - a.sequence)[0] ?? null;
}
export function HouseholdPathHome({ household, memberId, today, onOpen }: { household: Household; memberId: string; today: string; onOpen: (source: HerculesNumberSource) => void }) {
  const version = acceptedPlan(household, today);
  const projection = useMemo(() => version ? projectPlan(household, { memberId, scope: "household", acceptedRevision: household.revision, asOf: today, through: addDays(today, 30), selection: planSelectionForVersion(version) }) : null, [household, memberId, today, version]);
  const next = projection?.lines.find(row => row.gapCents > 0 || row.issues.length > 0) ?? projection?.lines.find(row => row.remainingCents > 0);
  return <section className="household-path-home"><div><p className="kicker">The life this money supports</p><h2>{projection?.firstExposed ? "One promise needs us" : version ? "Our agreement, in everyday life" : "Choose the month together"}</h2><p>{!projection ? "Make a private draft, compare the possibilities, then agree on the exact Plan together." : projection.kind !== "ready" ? projection.issues.join(" ") : `${projection.lines.filter(row => ["covered-now", "completed"].includes(row.status)).length} decisions have current coverage or completed evidence. ${projection.lines.filter(row => row.status === "depends-on-income").length} depend on future money.`}</p>{next && <p><strong>{next.line.labelSnapshot}</strong> · {next.dueDate ?? "date to choose"} · {formatCad(next.remainingCents)} remains</p>}</div><button onClick={() => onOpen({ route: "plan", view: "household", label: "Our next Plan decision", ...(version ? { planVersionId: version.id } : {}), ...(next ? { planLineId: next.line.id } : {}) })}>{version ? "See what our next choice changes" : "Begin Our Path"}</button></section>;
}

export function HouseholdTogether({ household, memberId, today, busy, onCommand, scenarioSource, onOpenPlan }: Omit<SharedBoardsProps, "view" | "onOpenGoals"> & { onOpenPlan: (source: HerculesNumberSource) => void }) {
  const version = acceptedPlan(household, today), boards = shapeSharedBoards(household.kitchen.boards);
  const nextSteps = version?.lines.filter(row => row.decision?.nextStep) ?? [];
  const session = [...(household.planHerculesSessions ?? [])].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0];
  return <main className="household-together"><header><p className="kicker">Together</p><h2>Make the agreement easier to live</h2><p>Decisions, responsibilities and a little room for each other.</p></header><section className="together-rhythm"><h3>{session?.state === "closed" ? "What we carry forward" : "Our next conversation"}</h3><p>{session?.rhythm || "Choose one practical rhythm that fits your actual life."}</p><button onClick={() => onOpenPlan({ route: "plan", view: "household", label: "Shared Sitdown", planSitDownSessionId: session?.sitDownSessionId ?? "new", planVersionId: version?.id })}>Resume our Sitdown</button></section><section className="together-responsibilities"><h3>Small actions behind our agreed Plan</h3>{nextSteps.length ? nextSteps.map(line => { const task = boards.tasks.find(row => row.planReference?.planLineId === line.id && row.planReference.planVersionId === version!.id); return <article key={line.id}><div><h4>{line.labelSnapshot}</h4><p>{line.decision!.nextStep}</p><small>{line.responsibility?.kind === "joint" ? "Together" : household.members.find(row => row.id === line.responsibility?.memberId)?.name ?? "Choose a responsible person"}</small></div>{task ? <span>{task.completed ? "Completed" : "On our shared to-do list"}</span> : <button disabled={busy} onClick={() => void onCommand(current => saveBoardTask(current, { id: `BOARD-TASK-${crypto.randomUUID()}`, expectedVersion: 0, memberId, title: line.decision!.nextStep!.slice(0, 200), dueDate: line.dueDate ?? null, completed: false, assigneeId: line.responsibility?.kind === "member" ? line.responsibility.memberId ?? null : null, planReference: { planVersionId: version!.id, planLineId: line.id } }))}>Add this agreed next step to our tasks</button>}<button onClick={() => onOpenPlan({ route: "plan", view: "household", label: line.labelSnapshot, planVersionId: version!.id, planLineId: line.id })}>Read the agreement</button></article>; }) : <p>Practical next steps from an active Plan appear here. Responsibility is separate from who holds an account.</p>}</section><SharedBoards household={household} memberId={memberId} today={today} busy={busy} view="household" scenarioSource={scenarioSource} onCommand={onCommand} onOpenGoals={() => onOpenPlan({ route: "plan", view: "household", label: "Goals & reserves", goalId: household.goals.find(row => row.shared && row.status !== "retired")?.id })} /></main>;
}
