import { useMemo } from "react";
import { addDays, formatCad, monthKeyFromDateKey, type Household, type HerculesNumberSource } from "./core/index.ts";
import { planSelectionForVersion, projectPlan } from "./core/planProjection.ts";
import { SharedBoards, type SharedBoardsProps } from "./widgets/SharedBoards.tsx";
import { PlanNextSteps } from "./hearthside/PlanNextSteps.tsx";

function acceptedPlan(household: Household, today: string) {
  return [...(household.planVersions ?? [])].filter(row => row.scope === "household" && row.monthKey === monthKeyFromDateKey(today) && row.state === "active").sort((a, b) => b.sequence - a.sequence)[0] ?? null;
}
export function HouseholdPathHome({ household, memberId, today, onOpen }: { household: Household; memberId: string; today: string; onOpen: (source: HerculesNumberSource) => void }) {
  const version = acceptedPlan(household, today);
  const projection = useMemo(() => version ? projectPlan(household, { memberId, scope: "household", acceptedRevision: household.revision, asOf: today, through: addDays(today, 30), selection: planSelectionForVersion(version) }) : null, [household, memberId, today, version]);
  const next = projection?.lines.find(row => row.gapCents > 0 || row.issues.length > 0) ?? projection?.lines.find(row => row.remainingCents > 0);
  return <section className="household-path-home"><div><p className="kicker">The life this money supports</p><h2>{projection?.firstExposed ? "One promise needs us" : version ? "Our agreement, in everyday life" : "Choose the month together"}</h2><p>{!projection ? "Make a private draft, compare the possibilities, then agree on the exact Plan together." : projection.kind !== "ready" ? projection.issues.join(" ") : `${projection.lines.filter(row => ["covered-now", "completed"].includes(row.status)).length} decisions have current coverage or completed evidence. ${projection.lines.filter(row => row.status === "depends-on-income").length} depend on future money.`}</p>{next && <p><strong>{next.line.labelSnapshot}</strong> · {next.dueDate ?? "date to choose"} · {formatCad(next.remainingCents)} remains</p>}</div><button onClick={() => onOpen({ route: "plan", view: "household", label: "Our next Plan decision", ...(version ? { planVersionId: version.id } : {}), ...(next ? { planLineId: next.line.id } : {}) })}>{version ? "See what our next choice changes" : "Begin Our Path"}</button></section>;
}

export function HouseholdTogether({ household, memberId, today, busy, onCommand, scenarioSource, onOpenPlan, onOpenPlanner, onOpenPlay, embedded }: Omit<SharedBoardsProps, "view" | "onOpenGoals" | "onOpenPlanner"> & { onOpenPlan: (source: HerculesNumberSource) => void; onOpenPlay?:()=>void; onOpenPlanner?:(taskId?:string)=>void; embedded?:boolean }) {
  const version = acceptedPlan(household, today), Container=embedded?"section":"main";
  const session = [...(household.planHerculesSessions ?? [])].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0];
  return <Container className="household-together"><header><p className="kicker">Together</p><h2>Make the agreement easier to live</h2><p>Decisions, responsibilities and a little room for each other.</p></header>{onOpenPlay&&<section className="together-play-entrance"><div><p className="kicker">Hercules · Play</p><h2>A room for our favourite things</h2></div><button type="button" onClick={onOpenPlay}>Enter Hercules’s room ↗</button></section>}<section className="together-rhythm"><h3>{session?.state === "closed" ? "What we carry forward" : "Our next conversation"}</h3><p>{session?.rhythm || "Choose one practical rhythm that fits your actual life."}</p><button onClick={() => onOpenPlan({ route: "plan", view: "household", label: "Shared Sitdown", planSitDownSessionId: session?.sitDownSessionId ?? "new", planVersionId: version?.id })}>Resume our Sitdown</button></section><PlanNextSteps household={household} memberId={memberId} version={version} busy={busy} onCommand={onCommand} onOpenPlan={onOpenPlan} onOpenPlanner={onOpenPlanner}/><SharedBoards household={household} memberId={memberId} today={today} busy={busy} view="household" scenarioSource={scenarioSource} onCommand={onCommand} onOpenPlanner={onOpenPlanner} onOpenGoals={() => onOpenPlan({ route: "plan", view: "household", label: "Goals & reserves", goalId: household.goals.find(row => row.shared && row.status !== "retired")?.id })} /></Container>;
}
