import { useMemo, useState } from "react";
import { formatCad, markPlanReflectionReviewed, savePlanReflection, todayKey, type CommitResult, type Household, type PlanOutcome, type PlanVersion } from "./core/index.ts";
import { projectedExpenseEffect } from "./core/budget.ts";
import { isVisibleInView } from "./core/visibility.ts";
import { matchPlanEvidence, planIntendedCents } from "./core/planProjection.ts";

export function PlanReflectionEditor({ household, version, memberId, busy, onCommand }: {
  household: Household; version: PlanVersion | null; memberId: string; busy: boolean; onCommand: (fn: (current: Household) => CommitResult) => Promise<unknown>;
}) {
  const reflection = version ? household.planReflections?.find(row => row.planVersionId === version.id && (version.scope === "household" || row.ownerMemberId === memberId)) ?? null : null;
  const [draftOutcomes, setDraftOutcomes] = useState<Record<string, PlanOutcome>>({});
  const [note, setNote] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [limit, setLimit] = useState(20);
  const [error, setError] = useState("");
  const outcomes = useMemo(() => Object.fromEntries((reflection?.outcomes ?? []).map(row => [row.planLineId, row])), [reflection]);
  if (!version) return <section className="plan-editor"><h3>Reflect after a Plan becomes active</h3><p>Keep the intention intact, then compare it with accepted evidence.</p></section>;
  const asOf = todayKey(), byId = new Map(household.transactions.map(row => [row.id, row]));
  const visible = household.transactions.filter(tx => tx.date <= asOf && isVisibleInView(tx, memberId, version.scope) && projectedExpenseEffect(tx, byId) !== 0);
  const valueFor = (id: string): PlanOutcome => draftOutcomes[id] ?? outcomes[id] ?? { planLineId: id, status: "not-relevant", actualCents: 0, transactionIds: [] };
  const evidenceFor = (id: string) => matchPlanEvidence(household, version.lines.find(row => row.id === id)!, version.monthKey, asOf, memberId, version.scope).filter(row => row.kind !== "goal-record");
  const amountFor = (id: string) => { const value = valueFor(id); return value.transactionIds.reduce((sum, id) => sum + (byId.has(id) ? projectedExpenseEffect(byId.get(id)!, byId) : 0), 0) + evidenceFor(id).filter(row => value.evidenceIds?.includes(row.id)).reduce((sum, row) => sum + row.amountCents, 0); };
  const update = (id: string, patch: Partial<PlanOutcome>) => setDraftOutcomes(current => ({ ...current, [id]: { ...valueFor(id), ...patch } }));
  const usedElsewhere = (lineId: string, id: string) => version.lines.some(line => line.id !== lineId && [...valueFor(line.id).transactionIds, ...(valueFor(line.id).evidenceIds ?? [])].includes(id));
  const save = async () => { setError(""); try { await onCommand(current => savePlanReflection(current, { memberId, planVersionId: version.id, outcomes: version.lines.map(line => valueFor(line.id)), expectedUpdatedAt: reflection?.updatedAt, note: note ?? (version.scope === "personal" ? reflection?.privateNote : reflection?.memberNotes.find(row => row.memberId === memberId)?.text) ?? "", createdBy: memberId })); } catch (cause) { setError(cause instanceof Error ? cause.message : "The reflection could not be saved. Your notes remain here."); } };
  return <section className="plan-editor plan-reflection-editor"><header><p className="kicker">What happened, what we learned</p><h3>Understand the month without grading it</h3><div className="plan-reflection-totals"><span>Intended<strong>{formatCad(version.lines.reduce((sum, line) => sum + planIntendedCents(line, version.monthKey), 0))}</strong></span><span>Linked net outcomes<strong>{formatCad(version.lines.reduce((sum, line) => sum + amountFor(line.id), 0))}</strong></span></div></header><label>Find evidence by date, note, place or amount<input type="search" value={search} onChange={event => { setSearch(event.target.value); setLimit(20); }} /></label>
    {version.lines.map(line => { const value = valueFor(line.id), evidence = evidenceFor(line.id); const matches = visible.filter(tx => !usedElsewhere(line.id, tx.id) && !value.evidenceIds?.includes(tx.id) && (search ? `${tx.date} ${tx.note} ${tx.place} ${formatCad(projectedExpenseEffect(tx, byId))}`.toLowerCase().includes(search.toLowerCase()) : tx.date.startsWith(version.monthKey) || value.transactionIds.includes(tx.id))); return <article className="plan-reflection-line" key={line.id}><div><strong>{line.labelSnapshot}</strong><span>{formatCad(amountFor(line.id))} net linked outcome</span><small>Payments, refunds and backed goal contributions keep their own evidence types.</small></div><label>How did this decision end?<select value={value.status} onChange={event => update(line.id, { status: event.target.value as PlanOutcome["status"] })}>{["paid", "moved", "missed", "deferred", "not-relevant"].map(state => <option key={state} value={state}>{state.replaceAll("-", " ")}</option>)}</select></label><fieldset><legend>Matched source evidence</legend>{evidence.map(row => <label key={row.id}><input type="checkbox" disabled={usedElsewhere(line.id, row.id) || value.transactionIds.includes(row.id)} checked={value.evidenceIds?.includes(row.id) ?? false} onChange={event => update(line.id, { evidenceIds: event.target.checked ? [...(value.evidenceIds ?? []), row.id] : value.evidenceIds?.filter(id => id !== row.id) })} />{row.date} · {row.kind.replaceAll("-", " ")} · {formatCad(row.amountCents)}</label>)}{!evidence.length && <p>No supported match yet. Link a receipt below or revisit the decision's source.</p>}<details><summary>Search and link other accepted receipts ({matches.length})</summary>{matches.slice(0, limit).map(tx => <label key={tx.id}><input type="checkbox" checked={value.transactionIds.includes(tx.id)} onChange={event => update(line.id, { transactionIds: event.target.checked ? [...value.transactionIds, tx.id] : value.transactionIds.filter(id => id !== tx.id) })} />{tx.date} · {tx.note || tx.place || "Receipt"} · {formatCad(projectedExpenseEffect(tx, byId))}</label>)}{matches.length > limit && <button onClick={() => setLimit(value => value + 20)}>Show 20 more</button>}</details></fieldset><label>What assumption would you revise?<textarea value={value.note ?? ""} onChange={event => update(line.id, { note: event.target.value })} /></label></article>; })}
    <label>{version.scope === "household" ? "Your note, shared with the household" : "Your private reflection"}<textarea value={note ?? (version.scope === "personal" ? reflection?.privateNote : reflection?.memberNotes.find(row => row.memberId === memberId)?.text) ?? ""} onChange={event => setNote(event.target.value)} /></label>{error && <p role="alert">{error}</p>}<div className="plan-editor-actions"><button disabled={busy} onClick={() => void save()}>Save this reflection</button>{reflection?.scope === "household" && <button disabled={busy || reflection.reviewedByMemberIds.includes(memberId)} onClick={() => void onCommand(current => markPlanReflectionReviewed(current, { reflectionId: reflection.id, expectedUpdatedAt: reflection.updatedAt, memberId, createdBy: memberId }))}>I reviewed this exact reflection</button>}</div>{reflection?.memberNotes.map(row => <blockquote key={row.memberId}><b>{household.members.find(member => member.id === row.memberId)?.name ?? "Member"}</b><p>{row.text}</p></blockquote>)}
  </section>;
}
