import {DurableObject} from 'cloudflare:workers';
import type {DurableObjectState} from '@cloudflare/workers-types';
import type {Scope} from '../src/ledgerSync/protocol.ts';
import {decodeGuestArrangement,decodeGuestPrepare,decodeGuestSourceProof,GUEST_LIMITS,guestAssert,guestChoice,guestDigest,guestDigestValue,guestId,guestInteger,guestNumber,guestOpaque,guestPrincipalEqual,guestPrincipals,guestRecord,guestText,type GuestIdentity,type GuestInvitationReview,type GuestMedia,type GuestPresence,type GuestPrincipal,type GuestReview,type GuestSourceCapture,type GuestStreetCard,type GuestToyEvent,type GuestVisit} from '../src/hearthside/guestContracts.ts';
import {checkedGuestIdentity,resolveGuestAuthority,sameGuestRoster} from './hearthsideGuestAuthority.ts';
import {guestRpcData} from './hearthsideGuestRpc.ts';
import {GuestArchive} from './hearthsideGuestArchive.ts';
import {guestCardStub,guestIndexStub,guestPrivateHeaders,type GuestEnv,type GuestGrant,type GuestPublication,type GuestSourceRoom} from './hearthsideGuestTypes.ts';
type Present={id:string;subject:string;grantId:string|null;label:string;host:boolean;expires:number};
const actor=(scope:Scope):GuestPrincipal=>({memberId:scope.memberId,subject:scope.subject});
const identical=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const review=(p:GuestPublication):GuestReview=>({version:1,id:p.id,ownerMemberId:p.owner.memberId,digest:p.digest,arrangement:p.arrangement,state:p.state,approvals:p.principals.map(member=>({memberId:member.memberId,approved:p.approvals.some(a=>guestPrincipalEqual(a,member))}))});
const invitation=(g:GuestGrant):GuestInvitationReview=>({version:1,id:g.id,publicationId:g.publicationId,digest:g.digest,recipientLabel:g.recipient.label,expiresAt:g.expiresAt,state:g.state,approvals:g.principals.map(member=>({memberId:member.memberId,approved:g.approvals.some(a=>guestPrincipalEqual(a,member))}))});
export class HearthsideGuestRoom extends DurableObject<GuestEnv>{
  private archive:GuestArchive;
  constructor(ctx:DurableObjectState,env:GuestEnv){super(ctx,env);this.archive=new GuestArchive(this.ctx.storage,env.HEARTHSIDE_GUEST_ARCHIVE);this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS guest_presence(id TEXT PRIMARY KEY,data TEXT NOT NULL)');this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS guest_toys(id TEXT PRIMARY KEY,data TEXT NOT NULL)');}
  private publishing(){guestAssert(this.env.HEARTHSIDE_GUESTS_ENABLED==='true'&&this.env.HEARTHSIDE_GUEST_PUBLICATION==='true','GUEST_PUBLICATION_DISABLED');}
  private host(scope:Scope,p?:GuestPublication){guestAssert(scope.environment==='development'&&scope.expires>Date.now()&&/^HH-[A-Za-z0-9_-]{1,96}$/.test(scope.householdId),'GUEST_UNAUTHENTICATED');if(p)guestAssert(p.householdId===scope.householdId&&p.principals.some(person=>guestPrincipalEqual(person,scope)),'GUEST_NOT_FOUND');}
  private source(householdId:string):GuestSourceRoom{guestAssert(this.env.LEDGER_ROOMS,'GUEST_SOURCE_UNAVAILABLE');return this.env.LEDGER_ROOMS.get(this.env.LEDGER_ROOMS.idFromName(`development/${householdId}`));}
  private async load(id:string){await this.archive.ready(`room/${guestOpaque(id)}`);const p=this.archive.get<GuestPublication>('publication');guestAssert(p&&p.id===id,'GUEST_NOT_FOUND');return p;}
  private current(p:GuestPublication){const now=this.archive.get<GuestPublication>('publication');guestAssert(now&&now.id===p.id&&now.digest===p.digest&&now.state!=='revoked','GUEST_CLOSED');return now;}
  private allApproved(p:GuestPublication){const current=this.current(p);guestAssert(current.principals.every(person=>current.approvals.some(a=>guestPrincipalEqual(person,a))),'GUEST_APPROVAL_REQUIRED');return current;}
  private prunePresence(){const now=Date.now();for(const row of this.ctx.storage.sql.exec<{id:string;data:string}>('SELECT id,data FROM guest_presence')){const value=JSON.parse(row.data) as Present;if(value.expires<=now)this.ctx.storage.sql.exec('DELETE FROM guest_presence WHERE id=?',row.id);}for(const row of this.ctx.storage.sql.exec<{id:string;data:string}>('SELECT id,data FROM guest_toys')){if((JSON.parse(row.data) as GuestToyEvent).happenedAt<now-10000)this.ctx.storage.sql.exec('DELETE FROM guest_toys WHERE id=?',row.id);}}
  private closePresence(grantId?:string){if(!grantId){this.ctx.storage.sql.exec('DELETE FROM guest_presence');this.ctx.storage.sql.exec('DELETE FROM guest_toys');return;}for(const row of this.ctx.storage.sql.exec<{id:string;data:string}>('SELECT id,data FROM guest_presence'))if((JSON.parse(row.data) as Present).grantId===grantId)this.ctx.storage.sql.exec('DELETE FROM guest_presence WHERE id=?',row.id);}
  private people(){this.prunePresence();return this.ctx.storage.sql.exec<{data:string}>('SELECT data FROM guest_presence').toArray().map(row=>JSON.parse(row.data) as Present);}
  private grant(id:string){const g=this.archive.get<GuestGrant>(`grant/${guestOpaque(id)}`);guestAssert(g,'GUEST_NOT_FOUND');return g;}
  private async freshHost(scope:Scope,p:GuestPublication,token:string,mode:'activation'|'visit'){
    const fresh=await resolveGuestAuthority(this.env,token,p.householdId);guestAssert(fresh.hostScope&&guestPrincipalEqual(fresh.hostScope,scope)&&sameGuestRoster(fresh.principals,p.principals),'GUEST_ROSTER_CHANGED');this.host(fresh.hostScope,p);guestAssert(await this.source(p.householdId).validateGuestSource(fresh.hostScope,p.proof,mode),'GUEST_SOURCE_UNAVAILABLE');this.current(p);this.host(fresh.hostScope,p);return fresh.hostScope;
  }
  private async copyMedia(pId:string,capture:GuestSourceCapture){
    guestAssert(this.env.HEARTHSIDE_GUEST_MEDIA,'GUEST_DISABLED');const descriptors=capture.arrangement.objects.flatMap(o=>o.kind==='memory'?o.media:[]),ids=new Set<string>();let total=0;
    guestAssert(descriptors.length===capture.media.length&&descriptors.length<=16,'GUEST_MEDIA_CHANGED');
    for(const media of capture.media){guestId(media.id);guestAssert(!ids.has(media.id)&&media.bytes instanceof ArrayBuffer,'GUEST_MEDIA_CHANGED');ids.add(media.id);const expected=descriptors.find(m=>m.id===media.id);guestAssert(expected&&expected.mime===media.mime&&expected.sha256===media.sha256&&expected.byteLength===media.bytes.byteLength,'GUEST_MEDIA_CHANGED');total+=media.bytes.byteLength;guestAssert(media.bytes.byteLength<=GUEST_LIMITS.mediaBytes&&total<=GUEST_LIMITS.totalMediaBytes&&await guestDigest(media.bytes)===media.sha256,'GUEST_MEDIA_CHANGED');
      const bytes=new Uint8Array(media.bytes),isPng=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71,isJpeg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255,isOgg=String.fromCharCode(...bytes.slice(0,4))==='OggS',isWebm=bytes[0]===0x1a&&bytes[1]===0x45&&bytes[2]===0xdf&&bytes[3]===0xa3,isMp4=String.fromCharCode(...bytes.slice(4,8))==='ftyp';
      guestAssert(media.mime==='image/png'?isPng:media.mime==='image/jpeg'?isJpeg:media.mime==='audio/ogg'?isOgg:media.mime==='audio/webm'?isWebm:isMp4,'GUEST_MEDIA_CHANGED');
      const key=`guest-copy-v1/development/${pId}/${media.id}`,created=await this.env.HEARTHSIDE_GUEST_MEDIA.put(key,media.bytes,{onlyIf:{etagDoesNotMatch:'*'},httpMetadata:{contentType:media.mime,cacheControl:'private, no-store'},customMetadata:{sha256:media.sha256}});
      if(!created){const old=await this.env.HEARTHSIDE_GUEST_MEDIA.get(key);guestAssert(old&&old.size===expected.byteLength&&old.customMetadata?.sha256===media.sha256&&await guestDigest(await old.arrayBuffer())===media.sha256,'GUEST_MEDIA_CHANGED');}
    }
  }
  async hostReview(scope:Scope,id:string){const p=await this.load(id);this.host(scope,p);return {publication:review(p),invitations:this.archive.list<GuestGrant>('grant/').map(invitation)};}
  async hostCommand(scope:Scope,principals:GuestPrincipal[],token:string,raw:unknown):Promise<unknown>{
    this.host(scope);const r=guestRecord(raw,['operation','input','id','publicationId','digest','sessionId','label']),operation=guestChoice(r.operation,['prepare','approve','activate','revoke','prepare-invitation','approve-invitation','activate-invitation','revoke-invitation','host-enter','host-pulse','host-leave']);
    if(operation==='prepare'){
      guestRecord(raw,['operation','input']);this.publishing();const input=decodeGuestPrepare(r.input),name=`room/${input.publicationId}`;await this.archive.ready(name);const existing=this.archive.get<GuestPublication>('publication');
      if(existing){this.host(scope,existing);guestAssert(identical(existing.proof.selection,input),'GUEST_ID_REUSED');await guestIndexStub(this.env,`host/${scope.householdId}`).addHostPublication(scope,input.publicationId);return review(existing);}
      const required=guestPrincipals(principals);guestAssert(required.some(a=>guestPrincipalEqual(a,scope)),'GUEST_UNAUTHENTICATED');const capture=guestRpcData(await this.source(scope.householdId).captureGuestSource(scope,input));
      guestRecord(capture,['version','arrangement','proof','media']);guestAssert(capture.version===1&&identical(decodeGuestSourceProof(capture.proof).selection,input),'GUEST_SOURCE_CHANGED');const arrangement=decodeGuestArrangement(capture.arrangement);guestAssert(await guestDigest({selection:input,arrangement,memoryBindings:capture.proof.memoryBindings})===guestDigestValue(capture.proof.digest),'GUEST_SOURCE_CHANGED');
      await this.copyMedia(input.publicationId,{...capture,arrangement});const fresh=await resolveGuestAuthority(this.env,token,scope.householdId);guestAssert(fresh.hostScope&&guestPrincipalEqual(fresh.hostScope,scope)&&sameGuestRoster(fresh.principals,required),'GUEST_ROSTER_CHANGED');guestAssert(await this.source(scope.householdId).validateGuestSource(fresh.hostScope,capture.proof,'activation'),'GUEST_SOURCE_CHANGED');
      const digest=await guestDigest({version:1,id:input.publicationId,arrangement,proofDigest:capture.proof.digest,principals:required,owner:actor(scope)});this.host(fresh.hostScope);const competing=this.archive.get<GuestPublication>('publication');if(competing){guestAssert(competing.digest===digest,'GUEST_ID_REUSED');await guestIndexStub(this.env,`host/${scope.householdId}`).addHostPublication(fresh.hostScope,competing.id);return review(competing);}
      const p:GuestPublication={version:1,id:input.publicationId,householdId:scope.householdId,owner:actor(scope),principals:required,arrangement,proof:capture.proof,digest,state:'prepared',approvals:[],acceptance:null,preparedAt:Date.now()};this.archive.put('publication',p);await this.archive.flush(name);await guestIndexStub(this.env,`host/${scope.householdId}`).addHostPublication(fresh.hostScope,p.id);return review(p);
    }
    const id=guestOpaque(r.publicationId),p=await this.load(id);this.host(scope,p);
    if(operation==='revoke'){
      guestRecord(raw,['operation','publicationId']);this.archive.put('publication',{...p,state:'revoked'});this.closePresence();await this.archive.flush(`room/${id}`);for(const g of this.archive.list<GuestGrant>('grant/'))await this.revokeGrant(p,g);return review(this.archive.get<GuestPublication>('publication')!);
    }
    if(operation==='approve'){
      guestRecord(raw,['operation','publicationId','digest']);this.publishing();this.current(p);guestAssert(p.digest===guestDigestValue(r.digest)&&sameGuestRoster(principals,p.principals),'GUEST_COMPOSITION_CHANGED');if(!p.approvals.some(a=>guestPrincipalEqual(a,scope))){guestAssert(p.state==='prepared','GUEST_REVIEW_CLOSED');p.approvals.push(actor(scope));this.archive.put('publication',p);}await this.archive.flush(`room/${id}`);return review(this.current(p));
    }
    if(operation==='activate'){
      guestRecord(raw,['operation','publicationId']);this.publishing();guestAssert(guestPrincipalEqual(p.owner,scope),'GUEST_CREATOR_REQUIRED');this.allApproved(p);if(p.state==='active'){await this.freshHost(scope,p,token,'visit');return review(this.current(p));}const fresh=await this.freshHost(scope,p,token,'activation');let current=this.allApproved(p);
      if(!current.acceptance){const ref={version:1 as const,publicationId:id,digest:p.digest,kind:'guest' as const,environment:'development' as const,householdId:p.householdId},receipt=guestRpcData(await this.source(p.householdId).acceptVaultPublication(fresh,ref));guestRecord(receipt,['version','publicationId','digest','kind','environment','householdId','receiptId','acceptedAt']);guestAssert(Object.entries(ref).every(([key,value])=>receipt[key as keyof typeof receipt]===value)&&guestId(receipt.receiptId)&&guestInteger(receipt.acceptedAt,1),'GUEST_ACCEPTANCE_CHANGED');current=this.allApproved(p);this.archive.put('publication',{...current,state:'accepted',acceptance:receipt});await this.archive.flush(`room/${id}`);}
      await this.freshHost(scope,p,token,'activation');current=this.allApproved(p);this.archive.put('publication',{...current,state:'active'});await this.archive.flush(`room/${id}`);return review(this.current(p));
    }
    if(operation==='prepare-invitation'){
      guestRecord(raw,['operation','publicationId','input']);this.publishing();guestAssert(this.current(p).state==='active','GUEST_CLOSED');const input=guestRecord(r.input,['id','cardCode','expiresAt']),grantId=guestOpaque(input.id),cardId=guestOpaque(input.cardCode),expiresAt=guestInteger(input.expiresAt,Date.now()+60_000,Date.now()+366*86400_000);const card=await guestCardStub(this.env,cardId).resolve(cardId,true);await this.freshHost(scope,p,token,'visit');const old=this.archive.get<GuestGrant>(`grant/${grantId}`);
      if(old){guestAssert(old.cardId===cardId&&old.recipient.subject===card.subject&&old.expiresAt===expiresAt,'GUEST_ID_REUSED');return invitation(old);}
      guestAssert(this.archive.list('grant/').length<GUEST_LIMITS.grants,'GUEST_ROOM_FULL');const material={id:grantId,publicationId:id,publicationDigest:p.digest,cardId,recipient:{subject:card.subject,label:card.label},expiresAt,principals:p.principals};const digest=await guestDigest(material);this.current(p);const competing=this.archive.get<GuestGrant>(`grant/${grantId}`);if(competing){guestAssert(competing.digest===digest,'GUEST_ID_REUSED');return invitation(competing);}const grant:GuestGrant={version:1,id:grantId,publicationId:id,cardId,recipient:material.recipient,expiresAt,digest,principals:p.principals,approvals:[],state:'prepared'};this.archive.put(`grant/${grantId}`,grant);await this.archive.flush(`room/${id}`);return invitation(grant);
    }
    if(['approve-invitation','activate-invitation','revoke-invitation'].includes(operation)){
      guestRecord(raw,operation==='approve-invitation'?['operation','publicationId','id','digest']:['operation','publicationId','id']);const grantId=guestOpaque(r.id),g=this.grant(grantId);guestAssert(g.publicationId===id,'GUEST_NOT_FOUND');
      if(operation==='revoke-invitation'){await this.revokeGrant(p,g);return invitation(this.grant(grantId));}
      this.publishing();guestAssert(g.state!=='revoked'&&g.expiresAt>Date.now()&&sameGuestRoster(principals,g.principals),'GUEST_GRANT_REVOKED');guestAssert(this.current(p).state==='active','GUEST_CLOSED');
      if(operation==='approve-invitation'){guestAssert(g.digest===guestDigestValue(r.digest),'GUEST_COMPOSITION_CHANGED');if(!g.approvals.some(a=>guestPrincipalEqual(a,scope))){guestAssert(g.state==='prepared','GUEST_REVIEW_CLOSED');g.approvals.push(actor(scope));this.archive.put(`grant/${grantId}`,g);}await this.archive.flush(`room/${id}`);return invitation(this.grant(grantId));}
      guestAssert(g.principals.every(person=>g.approvals.some(a=>guestPrincipalEqual(a,person))),'GUEST_APPROVAL_REQUIRED');await this.freshHost(scope,p,token,'visit');const card=await guestCardStub(this.env,g.cardId).resolve(g.cardId,g.state!=='active');guestAssert(card.subject===g.recipient.subject,'GUEST_CARD_UNAVAILABLE');await guestCardStub(this.env,g.cardId).register(g.cardId,card.subject,id,grantId);await guestIndexStub(this.env,`street/${card.subject}`).addGrant(card.subject,this.card(p,g));
      await this.freshHost(scope,p,token,'visit');const still=await guestCardStub(this.env,g.cardId).resolve(g.cardId,false);guestAssert(still.subject===g.recipient.subject&&this.grant(grantId).state!=='revoked','GUEST_GRANT_REVOKED');guestAssert(this.current(p).state==='active','GUEST_CLOSED');this.archive.put(`grant/${grantId}`,{...this.grant(grantId),state:'active'});await this.archive.flush(`room/${id}`);return invitation(this.grant(grantId));
    }
    guestRecord(raw,operation==='host-enter'?['operation','publicationId','sessionId','label']:['operation','publicationId','sessionId']);const sessionId=guestOpaque(r.sessionId);
    if(operation==='host-leave'){this.removeOwnPresence(scope.subject,sessionId);if(!this.people().some(person=>person.host)&&p.arrangement.mode==='hosted')this.closePresence();return {left:true};}
    await this.freshHost(scope,p,token,'visit');guestAssert(this.current(p).state==='active','GUEST_CLOSED');const old=this.people().find(person=>person.id===sessionId);guestAssert(!old||old.subject===scope.subject,'GUEST_SESSION_CHANGED');const label=operation==='host-enter'?guestText(r.label,60):old?.label;guestAssert(label,'GUEST_SESSION_CHANGED');this.setPresence({id:sessionId,subject:scope.subject,grantId:null,label,host:true,expires:Math.min(scope.expires,Date.now()+GUEST_LIMITS.presenceMs)});return this.visibleVisit(p);
  }
  private card(p:GuestPublication,g:GuestGrant):GuestStreetCard{return {id:g.id,publicationId:p.id,title:p.arrangement.title,theme:p.arrangement.theme,room:p.arrangement.room,mode:p.arrangement.mode,expiresAt:g.expiresAt};}
  private async revokeGrant(p:GuestPublication,g:GuestGrant){this.archive.put(`grant/${g.id}`,{...g,state:'revoked'});this.closePresence(g.id);await this.archive.flush(`room/${p.id}`);await guestIndexStub(this.env,`street/${g.recipient.subject}`).revokeGrant(g.recipient.subject,g.id);}
  async revokeByCard(cardId:string,subject:string,publicationId:string,grantId:string){const p=await this.load(publicationId),g=this.grant(grantId);guestAssert(g.cardId===cardId&&g.recipient.subject===subject,'GUEST_NOT_FOUND');await this.revokeGrant(p,g);}
  private async validGuest(identity:GuestIdentity,token:string,id:string,grantId:string){checkedGuestIdentity(identity);const p=await this.load(id),g=this.grant(grantId);guestAssert(g.publicationId===id&&g.recipient.subject===identity.subject&&g.state==='active'&&g.expiresAt>Date.now()&&p.state==='active','GUEST_NOT_FOUND');
    try{const card=await guestCardStub(this.env,g.cardId).resolve(g.cardId,false);guestAssert(card.subject===identity.subject,'GUEST_NOT_FOUND');const fresh=await resolveGuestAuthority(this.env,token,p.householdId);guestAssert(fresh.identity.subject===identity.subject&&sameGuestRoster(fresh.principals,p.principals),'GUEST_CLOSED');const scope:Scope={environment:'development',householdId:p.householdId,...p.owner,role:'member',expires:fresh.identity.expires,aclEpoch:fresh.identity.checkedAt};guestAssert(await this.source(p.householdId).validateGuestSource(scope,p.proof,'visit'),'GUEST_CLOSED');guestAssert(this.current(p).state==='active'&&this.grant(grantId).state==='active'&&this.grant(grantId).expiresAt>Date.now(),'GUEST_CLOSED');await guestCardStub(this.env,g.cardId).resolve(g.cardId,false);checkedGuestIdentity(identity);return {p,g};}catch(error){this.closePresence(error instanceof Error&&error.message==='GUEST_CLOSED'?undefined:grantId);throw error;}
  }
  async streetCard(identity:GuestIdentity,token:string,id:string,grantId:string){try{const {p,g}=await this.validGuest(identity,token,id,grantId);return this.card(p,g);}catch{return null;}}
  private setPresence(person:Present){this.prunePresence();guestAssert(this.people().length<24||this.people().some(p=>p.id===person.id),'GUEST_ROOM_FULL');this.ctx.storage.sql.exec('INSERT INTO guest_presence VALUES(?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data',person.id,JSON.stringify(person));}
  private removeOwnPresence(subject:string,id:string){const person=this.people().find(p=>p.id===id);if(person){guestAssert(person.subject===subject,'GUEST_SESSION_CHANGED');this.ctx.storage.sql.exec('DELETE FROM guest_presence WHERE id=?',id);}}
  private visibleVisit(p:GuestPublication):GuestVisit{const presence:GuestPresence[]=this.people().map(({id,label,host})=>({id,label,host})),toys=this.ctx.storage.sql.exec<{data:string}>('SELECT data FROM guest_toys ORDER BY id').toArray().map(row=>JSON.parse(row.data) as GuestToyEvent);return {version:1,id:p.id,arrangement:p.arrangement,presence,toys,serverTime:Date.now()};}
  async visit(identity:GuestIdentity,token:string,id:string,raw:unknown):Promise<GuestVisit|{left:true}>{const r=guestRecord(raw,['operation','grantId','sessionId','label','toy','x','y']),operation=guestChoice(r.operation,['enter','pulse','leave','toy','leave-street']),grantId=guestOpaque(r.grantId);const {p,g}=await this.validGuest(identity,token,id,grantId);
    if(operation==='leave-street'){guestRecord(raw,['operation','grantId']);await this.revokeGrant(p,g);return {left:true};}
    const sessionId=guestOpaque(r.sessionId);if(operation==='leave'){guestRecord(raw,['operation','grantId','sessionId']);this.removeOwnPresence(identity.subject,sessionId);return {left:true};}
    if(p.arrangement.mode==='hosted'&&!this.people().some(person=>person.host)){this.closePresence();throw Error('GUEST_HOST_AWAY');}
    const old=this.people().find(person=>person.id===sessionId);guestAssert(!old||old.subject===identity.subject&&old.grantId===grantId,'GUEST_SESSION_CHANGED');
    if(operation==='enter'){guestRecord(raw,['operation','grantId','sessionId','label']);this.setPresence({id:sessionId,subject:identity.subject,grantId,label:guestText(r.label,60),host:false,expires:Math.min(identity.expires,Date.now()+GUEST_LIMITS.presenceMs)});}
    else {guestAssert(old,'GUEST_SESSION_CHANGED');if(operation==='pulse'){guestRecord(raw,['operation','grantId','sessionId']);this.setPresence({...old,expires:Math.min(identity.expires,Date.now()+GUEST_LIMITS.presenceMs)});}else {guestRecord(raw,['operation','grantId','sessionId','toy','x','y']);const toy=guestChoice(r.toy,['chime','firefly','ball']),x=guestNumber(r.x,0,1),y=guestNumber(r.y,0,1);const events=this.ctx.storage.sql.exec<{data:string}>('SELECT data FROM guest_toys').toArray().map(row=>JSON.parse(row.data) as GuestToyEvent);guestAssert(events.length<20&&(!events.length||Date.now()-Math.max(...events.map(e=>e.happenedAt))>=250),'GUEST_TOY_PAUSE');const event:GuestToyEvent={id:crypto.randomUUID(),toy,x,y,happenedAt:Date.now()};this.ctx.storage.sql.exec('INSERT INTO guest_toys VALUES(?,?)',event.id,JSON.stringify(event));}}
    return this.visibleVisit(p);
  }
  private descriptor(p:GuestPublication,id:string):GuestMedia{const ref=p.arrangement.objects.flatMap(o=>o.kind==='memory'?o.media:[]).find(m=>m.id===id);guestAssert(ref,'GUEST_NOT_FOUND');return ref;}
  private async media(p:GuestPublication,id:string){guestAssert(this.env.HEARTHSIDE_GUEST_MEDIA,'GUEST_DISABLED');const descriptor=this.descriptor(p,guestId(id)),object=await this.env.HEARTHSIDE_GUEST_MEDIA.get(`guest-copy-v1/development/${p.id}/${id}`);guestAssert(object&&object.size===descriptor.byteLength&&object.customMetadata?.sha256===descriptor.sha256,'GUEST_NOT_FOUND');return new Response(object.body as unknown as BodyInit,{headers:{...guestPrivateHeaders,'Content-Type':descriptor.mime,'Content-Length':String(descriptor.byteLength)}});}
  private requireHost(p:GuestPublication){if(p.arrangement.mode==='hosted'&&!this.people().some(person=>person.host)){this.closePresence();throw Error('GUEST_HOST_AWAY');}}
  async mediaFor(identity:GuestIdentity,token:string,publicationId:string,grantId:string,id:string){const {p}=await this.validGuest(identity,token,publicationId,grantId);this.requireHost(p);const response=await this.media(p,id);try{await this.validGuest(identity,token,publicationId,grantId);this.requireHost(p);return response;}catch(error){await response.body?.cancel();throw error;}}
  async reviewMedia(scope:Scope,publicationId:string,id:string){const p=await this.load(publicationId);this.host(scope,p);guestAssert(p.state!=='revoked','GUEST_CLOSED');const response=await this.media(p,id);try{this.host(scope,this.current(p));return response;}catch(error){await response.body?.cancel();throw error;}}
  async restoreGuestArchive(name:string,maxEntries=128){guestAssert(name.startsWith('room/'));this.closePresence();return this.archive.restore(name,maxEntries);}
}
